### ISSUE TITLE
Feature Request : People and Member Management (gsoc )

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1000]
**Is your feature request related to a problem? Please describe.**

A modern and updated view of people management with relevance to the new design scheme.

**Describe the solution you'd like**

1.  Implement a member, user and admin view to manage all the users of the organization.
2. Enhance user profiles with the ability to overview required data about itself.
3. Establish a resilient infrastructure for people management, including the ability to :
        -  view all the events that the user registered for,
        -  view all the other public organizations user is a part of,
        -  view all the tags assigned to a user
        -   access to update, delete, view of users information.

**Comment by aashimawadhwa** [comment]
@palisadoes  please assign this to me

**Comment by palisadoes** [comment]
@aashimawadhwa Should this be closed?

**Comment by skushagra9** [comment]
@palisadoes  
I am interested to contribute.
