### ISSUE TITLE
Inappropriate Use of Window Reload in updatePostHandler Function

### ISSUE THREAD

**Issue by skbhagat0502** [PalisadoesFoundation/talawa-admin#1002]
**Issue Description:**

Context:
The updatePostHandler function in the orgPostCard component contains a call to window.location.reload() after a post update. In Single Page Applications (SPAs), this practice is not ideal as it disrupts the seamless user experience that SPAs aim to provide.

**Issues Identified:**

Full Page Reload:

The use of window.location.reload() results in a full page reload. In SPAs, this can lead to a loss of the benefits associated with dynamic content updates without full page reloads.
setTimeout Usage:

The use of setTimeout to delay the page reload raises concerns. In SPAs, it's generally preferred to handle timing and side effects using React's useEffect hook for better control but here the setTimeOut is not required though.

**Loss of SPA Advantages:**

Reloading the entire page contradicts the principles of Single Page Applications, where the goal is to provide a smoother and more dynamic user experience.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/2d86a1d0-fc71-4fd3-9df9-630e09b0d9a7)

The same issue can be seen with the deletePost

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/abecf765-f06b-431c-bee6-fffe31bae9b5)

Here also after deleting a post the full page reloads and with a setTimeOut.

**Comment by skbhagat0502** [comment]
@palisadoes , Please assign me this issue.

**Comment by palisadoes** [comment]
What is your proposed solution? @rishav-jha-mech may have comments too.

**Comment by skbhagat0502** [comment]
@palisadoes , My approach is simple. Here is my approach. 
When creating a post, after successufull creation the refetch function is called to get the updated lists of posts without reloading. With the same approach, we can resolve the issue. Like in case of updating and deleting a post the refetch function is called with the help of props and the refetch function is also passsed as a props. thus it updates the result. 
I am making a pull request you can see my solution also.

**Comment by skbhagat0502** [comment]
@palisadoes , I found the same issue with the login functionality also. Here you can see in the video that how after hitting the login button it redirects user to the same login page and after full reloading it redirects to the application.

https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/e6275e63-3053-41b5-8dc0-0ebfd5384e85

Should I create a new issue for this?

**Comment by rishav-jha-mech** [comment]
@skbhagat0502 the issue you are addressing comes under **Post Feed management** and currently @aashimawadhwa has an open PR for that. Before opening any PRs, make sure you are assigned the issue, please read the contributing guidelines.

**Comment by skbhagat0502** [comment]
ok @rishav-jha-mech

**Comment by palisadoes** [comment]
@skbhagat0502 I'm going to close this, however there are other places in the app where we have to refresh the page after updating values. Creating a standardized methodology to eliminate this need would be good for the project.
