### ISSUE TITLE
Dashboard Items Not Clickable Despite Sidebar Navigation Functionality

### ISSUE THREAD

**Issue by skbhagat0502** [PalisadoesFoundation/talawa-admin#1003]
**Issue Description:**
There are several items shown in the dashboard like members admins posts events etc. These items are not clickable and do not redirects to respective pages like the sidebar.

**Issues Identified:**
Non-Clickable Dashboard Items:
The dashboard items (e.g., "Posts," "Members," "Admins") are not responsive to clicks, rendering them non-functional. Users are unable to access the associated content directly from the dashboard.

**Expected Behavior:**
Clicking on a dashboard item should lead to the relevant section or content within the dashboard.

**Steps to Reproduce:**
Navigate to the dashboard.
Observe that the dashboard items (e.g., "Posts," "Members," "Admins") are not clickable.
Attempt to click on any dashboard item to access its corresponding content.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/fbff3012-cb70-4334-a885-2309a4ca5691)

**The dashboard items should be functional like the sidebar items.**

**Comment by skbhagat0502** [comment]
@palisadoes , Please assign me this issue.

**Comment by palisadoes** [comment]
@skbhagat0502 

1. What are you proposing each click would do?
2. Are the screens already created for this, or would you need to create them?

@rishav-jha-mech is working on completing the Admin redesign by the end of the month. Your input will be helpful in creating issues after that in accordance with our design guide that will soon be published. At that time we'll create smaller issues that will encourage greater participation.

**Comment by skbhagat0502** [comment]
@palisadoes 
Yes the screens are already created for this. I do need to create them. Like clicking on the "posts" button from the sidebar open a page in the dashboard showing all the posts.. I want the same like on cliking on the post button on the dashboard should open the same but instead they are not clickable and do not open the page. The same issue is with all the buttons on the dashboard.

**Comment by palisadoes** [comment]
@rishav-jha-mech Should we proceed with this?

**Comment by rishav-jha-mech** [comment]
@palisadoes, it's an feature request and it is doable so i think we can go ahead with this.
