### ISSUE TITLE
Message isn't clear above delete organisation button also the button colors should be interchanged.

### ISSUE THREAD

**Issue by skbhagat0502** [PalisadoesFoundation/talawa-admin#1008]
**Describe the bug**
In the organisation's setting page there is not a clear message above delete organisation button.It has some mistakes which makes it hard to understand. It can be seen in the image. Also the color's of the button "yes" and "no" should be interchanged signifying that clicking on the "yes" button is destructive.

**To Reproduce**

1.Login.
2.Go to organisation settings.
3.see the mistake in the message written over the delete organisation button.
4.Click on the delete organisation button. You see the wrong color's of the button.

**Expected behavior**
The message should be clear as "By clicking the 'Delete organization' button, the organization will be permanently deleted along with its events, tags, and all related data."
Also the color of the button NO should be green and the color of the button YES should be red.

**Actual behavior**
Mistake in the message written over the delete organisation button. 
Wrong colors of the buttons YES and NO.

**Screenshots**
![Screenshot 2023-10-26 033232](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/608b5a65-1d27-4913-80d5-4b10afe97846)
![Screenshot 2023-10-26 033327](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/715ab2b4-71f0-4581-8e12-e692a90a1e3e)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by skbhagat0502** [comment]
@palisadoes Please assign me this issue.

**Comment by palisadoes** [comment]
Please make sure that you:

1. have translations for all the text you change.
2. include a video with your PR as part of your proof.

@rishav-jha-mech , any comments?

**Comment by rishav-jha-mech** [comment]
I have covered this issue in my recent PR. This is no longer a issue.
