### ISSUE TITLE
Bug Report: Installed Plugins are not fetched correctly and showing errors.

### ISSUE THREAD

**Issue by skbhagat0502** [PalisadoesFoundation/talawa-admin#1009]
**Describe the bug**
When I click on the installed plugins button available at the plugin store page, it shows plugins does not exists even if there are plugins installed. Also after a few milisecond the following error is shown.

![Screenshot 2023-10-26 091859](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/0421b1a3-07a5-4188-aaad-a17bba2518a2)
![Screenshot 2023-10-26 091826](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/d7a9c758-87bb-4337-8f9d-b9ed5948bd09)
![Screenshot 2023-10-26 092228](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/0be83b76-9844-4d50-8fb1-fb85df3d82ff)

**To Reproduce**

1.Login
2.Go to your organisation dashboard.
3.Click on plugin and then plugin store.
4.Click on installed button to see installed plugins.

**Expected behavior**
All installed plugins should be there.

**Actual behavior**
Throwing an error as shown in picture.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by skbhagat0502** [comment]
@palisadoes , Please assign me this issue.

**Comment by palisadoes** [comment]
@SiddheshKukade Please comment on this.

**Comment by palisadoes** [comment]
Unassigning until @SiddheshKukade comments. He's working on fixing the plugin architecture

**Comment by skbhagat0502** [comment]
Ok @palisadoes

**Comment by SiddheshKukade** [comment]
Hello, I've checked and everything's working on my side. I've also made multiple demo video about plugins and setting them up one YouTube that you can check on the channel. 

@skbhagat0502 to check this on your machine can you just put a screenshot of your MongoDB `plugins` collections ?

The most probable reason behind this is happening is that you don't that data in the db. But I've previously made a script that makes sure to put out that data. So maybe you've made some changes in  Talawa-api index file.

**Comment by skbhagat0502** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/d023b2af-b4c5-46b2-ab34-bbee946ea512)
@SiddheshKukade I looked at my MongoDB collections and there is a collection of `plugins` available. I have attached the screenshot above.

**Comment by skbhagat0502** [comment]
@SiddheshKukade @palisadoes I found that after creating a new organisation and going to the plugin store. all the plugins have the uninstall button as they were already installed but I have not installed any of them or not have choosen the option for all plugins. I think the flow should be like there should be Install button and  clicking on It should change it to uninstall. Should I create an Issue for this.

**Comment by skbhagat0502** [comment]
Also I am still getting the error when trying the get the installed plugins. I also checked my repositories they are well synced with the upstream. I think may be it is just an issue on my laptop but I am not able to figure out the reason for that.

**Comment by SiddheshKukade** [comment]
> ![image](https://user-images.githubusercontent.com/109683163/278889909-d023b2af-b4c5-46b2-ab34-bbee946ea512.png)
> @SiddheshKukade I looked at my MongoDB collections and there is a collection of `plugins` available. I have attached the screenshot above.

@skbhagat0502 Can you show the contents of that collection ?

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade @palisadoes I found that after creating a new organisation and going to the plugin store. all the plugins have the uninstall button as they were already installed but I have not installed any of them or not have choosen the option for all plugins. I think the flow should be like there should be Install button and clicking on It should change it to uninstall. Should I create an Issue for this.

@skbhagat0502 Yes this flow is decided my me after taking a lot of feedback from mentors and other contributors over the past few months. This reduces the complexity of the code and the primary features of the org should be accessible. 
We are not looking forward to change any of that. You can also look at some videos from Palisadoes Channel to understand the reason behind this.

**Comment by skbhagat0502** [comment]
> > ![image](https://user-images.githubusercontent.com/109683163/278889909-d023b2af-b4c5-46b2-ab34-bbee946ea512.png)
> > @SiddheshKukade I looked at my MongoDB collections and there is a collection of `plugins` available. I have attached the screenshot above.
> 
> @skbhagat0502 Can you show the contents of that collection ?

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/2628be49-215a-459e-a379-af6a750e323b)
This is the content of the plugins collection.

**Comment by skbhagat0502** [comment]
Closing this as @SiddheshKukade has already resolved this issue in his PR.
