### ISSUE TITLE
Bug Report: Throwing an error when trying to add a plugin.

### ISSUE THREAD

**Issue by skbhagat0502** [PalisadoesFoundation/talawa-admin#1010]
**Describe the bug**
When trying to add a plugin by clicking on the add new button from the plugin store page and filling the form, it shows an error after submitting. The error can be seen in the image.

![Screenshot 2023-10-26 093252](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/c32c123c-4a28-4285-9c1d-04a104e08e3c)
![Screenshot 2023-10-26 093318](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/d232a78b-4462-409d-abd6-0877bef10160)

**To Reproduce**

1.Login
2.Go to manage your organisation.
3.Go to plugin store.
4.Try to add new plugin.

**Expected behavior**
The plugin should be added and should be reflected below in the plugin store page.

**Actual behavior**
Throwing the errors as shown in the image.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by skbhagat0502** [comment]
@palisadoes , Please assign me this issue.

**Comment by palisadoes** [comment]
@SiddheshKukade Please comment on this

**Comment by palisadoes** [comment]
> @palisadoes , Please assign me this issue.

Siddhesh is working on finalizing the plugin code. He'll have comments on this.

**Comment by skbhagat0502** [comment]
Ok @palisadoes

**Comment by SiddheshKukade** [comment]
@skbhagat0502 the add new plugins would be removed as I've decided with my seniors last year. The adding plugins features would be done directly by filling in the JSON data from server.

@palisadoes sir I'm also working on the docs. First I'll put the docs of ads and then will update the docs of plugins.

**Comment by skbhagat0502** [comment]
ok @SiddheshKukade.

**Comment by skbhagat0502** [comment]
@SiddheshKukade @palisadoes Should I create an issue for removing this feature of adding plugins.

**Comment by palisadoes** [comment]
Use this issue and create a PR with the appropriate title and description referring to this issue.

**Comment by skbhagat0502** [comment]
Ok @palisadoes

**Comment by skbhagat0502** [comment]
@palisadoes please assign this issue to me.I will create a PR.

**Comment by SiddheshKukade** [comment]
@skbhagat0502 I've already explained that this would be feature would be removed from my current pr. This issue is not valid

**Comment by skbhagat0502** [comment]
> @skbhagat0502 I've already explained that this would be feature would be removed from my current pr. This issue is not valid

Yes but @palisadoes said to create a PR in the comments.

**Comment by skbhagat0502** [comment]
Ok @SiddheshKukade

**Comment by palisadoes** [comment]
I'll close this issue as @SiddheshKukade  is going to resolve this. I didn't realize the oversight
