### ISSUE TITLE
Modal Not Closing and Events Not Updating Automatically After Creating

### ISSUE THREAD

**Issue by skbhagat0502** [PalisadoesFoundation/talawa-admin#1011]
**Describe the bug**
Upon attempting to add an event through the "add event" button, a modal with a form appears. After filling out the form and clicking "create event," the modal fails to close automatically. While the event is created, it does not reflect in the events list until the page is manually refreshed.

**To Reproduce**

1. Click on the "add event" button.
2. Fill out the form in the modal.
3. Click "create event."
4. Notice that the modal does not close automatically, and the event does not appear until the page is refreshed.

**Expected behavior**
Upon creating an event, the modal should close automatically, and the newly created event should be immediately visible in the events page without requiring a page refresh.

**Actual behavior**
The modal does not close automatically after creating an event, and the event is not displayed in the events page until a manual page refresh is performed.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/13126385-ec8d-43bf-a8b0-0317e92a4ea8

**Additional details**
[Provide any additional context or screenshots related to the issue]

**Potential internship candidates**
If you are considering applying for a Palisadoes Foundation internship, please review additional information [here](https://github.com/PalisadoesFoundation/talawa/issues/359).

**Comment by skbhagat0502** [comment]
@palisadoes  Please assign me this issue.

**Comment by palisadoes** [comment]
@rishav-jha-mech  Please comment. I know you have a very large PR submitted that may include this as a fix.

**Comment by rishav-jha-mech** [comment]
@palisadoes, this is not involved in my current PR. @EshaanAgg would have a better idea about this, maybe he'll be covering this issue in his final PR.

**Comment by EshaanAgg** [comment]
This is a separate issue that is present since the beginning of the GSoC. I feel that this can be assigned to @skbhagat0502. You would need to refetch the data of events after the submit button is called.

**Comment by SiddheshKukade** [comment]
The events are updated on the calendar after a refresh.
