### ISSUE TITLE
Bug Report: Event check in management not updating automatically after adding a new registrant

### ISSUE THREAD

**Issue by kanhaiya04** [PalisadoesFoundation/talawa-admin#1012]
**Describe the bug**
After adding a new registrant to an event, the change is not automatically reflected in the event check-in management. We need to refresh the page.

**To Reproduce**

1. Open event dashboard for any event.
2. Add a new registrant for the event from show registrants.
3. Open event check in management modal from check in registrants.
4. Notice that the newly added registrant in not listed there, until the page is refreshed.

**Expected behavior**
After adding a new registrant, it should be visible in the check in event management modal without any refresh.

**Actual behavior**
The newly added registrant is not visible until the page is refreshed.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/c74d6729-df7d-437a-91fd-69d714c2c531

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
@palisadoes Please assign me this issue.

**Comment by HarshSantoshi** [comment]
@kanhaiya04 have you joined any slack channel of Palisadoes?

**Comment by palisadoes** [comment]
@EshaanAgg Is this something that you are working on with your Event management work?

**Comment by EshaanAgg** [comment]
@palisadoes No sir. I was unaware of this bug. This can be assigned to @kanhaiya04.

**Comment by palisadoes** [comment]
@kanhaiya04 are you still working on this?

**Comment by kanhaiya04** [comment]
@palisadoes, I've already created a pull request related to this issue.
