### ISSUE TITLE
Bug Report: Update and delete buttons of event modal are not working

### ISSUE THREAD

**Issue by kanhaiya04** [PalisadoesFoundation/talawa-admin#1013]
**Describe the bug**
Update and delete buttons of the event modal are not working as expected.

**To Reproduce**

1. Open events page.
2. Open event modal of any event.
3. Notice the update and delete icon in the bottom right are not working.

**Expected behavior**
The update and delete buttons should perform their respective tasks.

**Actual behavior**
Both the buttons are doing nothing.

**Screenshots**
![Untitled design (2)](https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/7e809857-285e-479d-b7ea-6f7a1738378f)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
@palisadoes Please assign me this issue.

**Comment by rishav-jha-mech** [comment]
@palisadoes Event and People screens were out of scope for my project. This modal should be redesigned according to the latest design standards. I'll update the figma file soon, for now @kanhaiya04 can work on this.

**Comment by kanhaiya04** [comment]
Hey @rishav-jha-mech, I attempted to resolve this issue by updating the data-toggle and data-target attributes to data-bs-toggle and data-bs-target, respectively, following the guidelines from [Bootstrap 5.3 documentation](https://getbootstrap.com/docs/5.3/components/modal/#live-demo).

Now, the buttons are producing an error response, whereas previously, there was no response at all.

`ERROR
ne.getInstance(...) is null
./node_modules/bootstrap/dist/js/bootstrap.min.js/</<@http://localhost:3000/static/js/bundle.js:147739:13
i@http://localhost:3000/static/js/bundle.js:146670:53
`

Can you suggest me the fix?

**Comment by rishav-jha-mech** [comment]
@kanhaiya04 follow react-bootstrap, using attribute based elements wont work here
