### ISSUE TITLE
Fix the styling/functionality of create post on the organisation page

### ISSUE THREAD

**Issue by rishuraj1** [PalisadoesFoundation/talawa-admin#1020]
**Describe the bug**
The UI is breaking at the create post modal at orgs. page

**To Reproduce**

1. go to all organisations page
2. click on any org.
3. click on the "view all" button beside latest post
4. click on create post and you can see the inconsistency.

https://github.com/PalisadoesFoundation/talawa-admin/assets/47839626/449567c2-7a55-4a07-b95e-6b75858dd8ce

**Expected behavior**
<img width="960" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/47839626/f2c53b77-ac96-4f14-9cd0-b7346fd77928">

**Actual behavior**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/47839626/bc948493-cdb6-4871-8c69-c1078db5336a)

**Screenshots**

**Additional details**
I want to contribute to this project, please assign me to fix this. Thanks

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@rishuraj1 Have you pulled the latest code? There was an extensive update to the design elements earlier today. This issue may no longer exist.

@rishav-jha-mech This may require your input

**Comment by rishuraj1** [comment]
@palisadoes  yes I am running the latest develop branch on my system.

**Comment by rishav-jha-mech** [comment]
@palisadoes, @aashimawadhwa has an open pr which is dedicated for post and newsfeed management. She has already fixed it i suppose.

**Comment by palisadoes** [comment]
Thanks. @rishuraj1 I'll close this because of the other open PR.
