### ISSUE TITLE
Able to create events with white spaces only.

### ISSUE THREAD

**Issue by skbhagat0502** [PalisadoesFoundation/talawa-admin#1021]
**Describe the bug**
When attempting to create an event using the event creation modal, it is possible to submit the form with no title, no description, and no location, by simply inputting spaces.

**To Reproduce**

1. Login to talawa admin.
2. Go to the dashboard and then events.
3. Click on "Add event" button.
4. Enter spaces in the title field.
5. Enter spaces in the description field.
6. Enter spaces in the location field.
7. Attempt to create the event with the filled but empty information.

**Expected behavior**
I expected the system to validate and prevent the creation of an event with no meaningful information, ensuring at least one of the following fields (title, description, location) is non-empty.

**Actual behavior**
The system allows the creation of an event even when all fields (title, description, location) contain only white spaces.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/3daa1b17-d65d-487b-9fba-988f93f85028

**Additional details**

**Comment by skbhagat0502** [comment]
@palisadoes Please assign me this issue.

**Comment by palisadoes** [comment]
@EshaanAgg Any comments on this?

**Comment by akhilender-bongirwar** [comment]
Hey @skbhagat0502, since you already have 2 issues assigned to you, may I please take up this issue and resolve it?
// @palisadoes

**Comment by skbhagat0502** [comment]
> Hey @skbhagat0502, since you already have 2 issues assigned to you, may I please take up this issue and resolve it? // @palisadoes

Thanks for your interest, @akhilender-bongirwar , I appreciate your willingness to help out. However, I've already started working on this issue and I'm confident in my ability to address it effectively. If you have any other tasks or issues you'd like to tackle, feel free to let me know, and we can coordinate efforts.

**Comment by palisadoes** [comment]
@skbhagat0502 We will soon start enforcing the two issue guidance.

**Comment by skbhagat0502** [comment]
Ok @palisadoes
