### ISSUE TITLE
Layout and Input Field Issues in Post Details Modal

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-admin#1023]
**Describe the bug**
The post details modal has several layout issues. The text area is not properly placed within a div, and the video input field is missing.

**Bug Description:**
The post details modal has several layout issues. The text area is not properly placed within a div, and the video input field is missing.

**To Reproduce:**
1. Open the post details modal.
2. Observe the misaligned text area.
3. Notice the absence of an input field for video uploads.
4. Experience the overall poor user experience.

**Expected Behavior:**
The video input field should allow users to upload video files, and the text area should be properly positioned within the modal for a better user experience.

**Actual Behavior:**
The text area is not correctly placed within a `div` container, and the video input field is missing, resulting in a subpar user experience.

**Proposed Changes:**
1. Ensure the text area is properly enclosed within a `div` for correct alignment.
2. Add a video input field to allow users to upload video files.
3. Revamp the overall user experience for better usability.

**Screenshots**
![WhatsApp Image 2023-11-04 at 00 25 21_70154779](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/7b79dfb8-cd4e-41b2-b1b2-40be40bf9830)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@rishav-jha-mech Please comment on this before assignment.

**Comment by aashimawadhwa** [comment]
This is covered in my pr sor which is yet to be merged i resolved the conflicts for it yesterday. @palisadoes

**Comment by rishav-jha-mech** [comment]
Yes @palisadoes, also this is a duplicate issue which was closed earlier Reference #999
