### ISSUE TITLE
Code Coverage: Create tests for src/screens/MemberDetail/MemberDetail.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1028]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
hey @aashimawadhwa , please assign me this.

**Comment by hharshas** [comment]
Can you assign me this issue @palisadoes I would like to work on this

**Comment by Min2who** [comment]
Hi @hharshas i was working on #1607 and thats why it was getting delayed since i have solved that i am gonna proceed with it as i have done some work for it initially

**Comment by noman2002** [comment]
@hharshas We are assigning on first come first serve basis. Please comment on other open issues to get it assigned.

**Comment by Min2who** [comment]
> Can you assign me this issue @palisadoes I would like to work on this

Hey @hharshas go ahead with this

**Comment by bupd** [comment]
Hi 👋 @noman2002  I noticed that issue #1028 has been assigned but hasn't seen any activity in the past week. I completely understand that everyone has their own commitments and priorities.

I was wondering if the current assignee is still actively working on the issue. If not, I'd be happy to take it over and contribute to the progress of the project.

Thanks.

**Comment by bupd** [comment]
We can consider closing this issue.

**Comment by Cioppolo14** [comment]
@bupd @noman2002 Can you clarify what you mean here? Does this issue need to be closed?

**Comment by noman2002** [comment]
@Cioppolo14 Yes we can close this as the PR related to this issues is merged. Thank you.
