### ISSUE TITLE
Code Coverage: Create tests for src/components/CheckIn/CheckInWrapper.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1031]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
hey @palisadoes , can you assign me this issue i wanna work on it
Thanks !!

**Comment by noman2002** [comment]
@duplixx You already have 2 issues in your name. Please get the PRs merged first, then I'll assign more. As per the rules only 2 issues can be assigned at once.

**Comment by duplixx** [comment]
hey @noman2002 , you can assign me this as my previous PR is merged now!!

**Comment by LakshyaSatpal** [comment]
Please assign this to me.

**Comment by noman2002** [comment]
Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by adi790uu** [comment]
Hey @noman2002 I want to work on this issue!

**Comment by punitkr03** [comment]
Hey ,I want to work on this, please assign me.

**Comment by noman2002** [comment]
@adi790uu  You already have 2 issues assigned to you.

**Comment by punitkr03** [comment]
I tried uncommenting it and the memory leak is still there. I will try to fix that as well.

**Comment by punitkr03** [comment]
@noman2002 Hey, I have been waiting for your input.

**Comment by noman2002** [comment]
@aashimawadhwa @EshaanAgg Please answer his queries.

**Comment by EshaanAgg** [comment]
@punitkr03 I had left the comment to show what the prospective test must look like after the memory leak in broken. The test is not full proof as it hasn't been tested in the wild due to the aforementioned leak. 
- Please first make sure that the memory leak is indeed fixed.
- If it is so, then you can try writing the tests for the same from a fresh perspective, and see how 100% coverage can be achieved. Use the provided test as reference, and not as a strict format.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no pull request

**Comment by DIWAKARKASHYAP** [comment]
@noman2002 I have read the issue. I can solve it. Could you please assign this to me?

**Comment by DIWAKARKASHYAP** [comment]
Hello @noman2002 @palisadoes 
I am facing an issue. When I run the Talawa-admin develop branch, this happens

https://github.com/PalisadoesFoundation/talawa-admin/assets/94478026/9804ffdd-2220-4a31-af97-15822d8a103c

but the main branch is working fine

**Comment by punitkr03** [comment]
@DIWAKARKASHYAP You have to run talawa-api either in docker container or manually. So forl ```talawa-api``` repo and set it up too. I will recommend using docker.

**Comment by DIWAKARKASHYAP** [comment]
I am using docker of talawa api

**Comment by punitkr03** [comment]
Did u set your ```NODE_ENV``` in .env file to development?

**Comment by DIWAKARKASHYAP** [comment]
yes all variable are setup , the main branch is working properly but develop branch give me this problem

**Comment by palisadoes** [comment]
Removing assignment due to inactivity

**Comment by ashutuptiwari** [comment]
@palisadoes  I'd like to work on this :D

**Comment by ashutuptiwari** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/106370097/348ae0d9-567e-4156-b242-fba2b3188d06)
@Cioppolo14

**Comment by Cioppolo14** [comment]
@ashutuptiwari Please fix the memory leak as part of this issue.

**Comment by ashutuptiwari** [comment]
Alright, can you please describe the leak @Cioppolo14

**Comment by palisadoes** [comment]
Unassigning due to inactivity and/or no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Anvita0305** [comment]
Hello, @noman2002 @Cioppolo14 I would like to work on this issue. Can you please assign it to me? Thanks!
