### ISSUE TITLE
Code Coverage: Create tests for src/screens/OrgList/OrgList.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1034]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
hey @aashimawadhwa , please assign me this.

**Comment by kanhaiya04** [comment]
@palisadoes I was waiting for this [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/1076) to get merged of @akhilender-bongirwar. Once merged, I'll be able to write tests aligning with the recent changes. Otherwise, the coverage might drop below 100%.

**Comment by palisadoes** [comment]
Thanks. I've reassigned it to you.

**Comment by hharshas** [comment]
I would like to work on this issue @palisadoes can u assign me

**Comment by VaibhavTalkhande** [comment]
Can I get assigned

**Comment by aashimawadhwa** [comment]
@kanhaiya04 any updates?

**Comment by kanhaiya04** [comment]
I'm waiting because this [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/1076) is still under review.
