### ISSUE TITLE
Code Coverage: Create tests for src/screens/Users/Users.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1035]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
hey @palisadoes ,please assign me this issue as i have completed my previous test `UserPortal\SecuredRouteForUser\SecuredRouteForUser.tsx`

**Comment by palisadoes** [comment]
@Ayush0Chaudhary will be managing this issue and the PR you create.

**Comment by shivansh-bhatnagar18** [comment]
Hey @palisadoes, please assign me this issue, I'll try my level best to work on this issue

**Comment by dz016** [comment]
Hey @palisadoes  please assign me this issue, I want to work on this.

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by Cioppolo14** [comment]
Closing as the code coverage is currently 100%.
