### ISSUE TITLE
Code Coverage: Create tests for src/components/EventStats/Statistics/Feedback.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1036]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by adi790uu** [comment]
Hey I would like to work on this issue!

**Comment by meetulr** [comment]
hey @noman2002, can you assign this to me if available.

**Comment by Min2who** [comment]
@noman2002 I was actually working on it and have acieved the test coverage : )

**Comment by meetulr** [comment]
@Cioppolo14, this issue has been solved, please close it.
