### ISSUE TITLE
Code Coverage: Create tests for src/components/UserPortal/SecuredRouteForUser/SecuredRouteForUser.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1037]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
hey @palisadoes ,please assign me this i am making tests cases for it..

**Comment by duplixx** [comment]
Hey @palisadoes , I Have Made the Test for it 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/dff7b6c1-fb6a-44ec-a05b-1e8d433ac9db)

**Comment by noman2002** [comment]
@duplixx Please submit a PR for the same.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary will be managing this issue and the PR you create.
