### ISSUE TITLE
Code Coverage: Create tests for src/components/AddOn/core/AddOnStore/AddOnStore.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1038]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Min2who** [comment]
can you assigned me this issue ?

**Comment by adi790uu** [comment]
Hey @noman2002 I would like to work on this issue

**Comment by shivansh-bhatnagar18** [comment]
Hey @noman2002 I would love to work on this issue.

**Comment by Veer0x1** [comment]
I would like to add this test.

**Comment by VaibhavTalkhande** [comment]
i would like to work this issue

**Comment by palisadoes** [comment]
@shivansh-bhatnagar18 Are you still working on this? There is no PR

**Comment by shivansh-bhatnagar18** [comment]
Yes @palisadoes I am still working on this issue. Thank you

**Comment by ALOK9442** [comment]
Hey @noman2002  I would love to work on this issue.

**Comment by ALOK9442** [comment]
I have a question regarding to issue, when we encounter failing tests, is the expectation primarily to address the tests themselves or also to make corrections in the corresponding code files? I want to ensure that I align with the issue. 
Your guidance on this matter would be greatly appreciated.

**Comment by palisadoes** [comment]
When tests fail they can be caused by either poorly written source code or poorly written tests. In either case we need the testing goals achieved without any functionality being affected.

**Comment by ParishiB** [comment]
@noman2002 can i work on this issue?

**Comment by palisadoes** [comment]
@SiddheshKukade Please provide some context to this question about port 3005

**Comment by Anvita0305** [comment]
Hello, while working on the tests I am encountering this error and thus,unable to proceed.
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/ea749a0a-a4e7-4f74-984a-77ae6fd72a1e)
1. const result = await fetch(`http://localhost:${process.env.PORT}/store`); this is the line where I'm getting error. const result is undefined.
2. Does this issue need to be solved before writing the tests?
Any help would really be appreciated. Thanks!

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade Please provide some context to this question about port 3005

@palisadoes that was a part of old code. It can be deleted It's not being used anywhere.

**Comment by SiddheshKukade** [comment]
> Hello, while working on the tests I am encountering this error and thus,unable to proceed. ![image](https://private-user-images.githubusercontent.com/78889572/305683978-ea749a0a-a4e7-4f74-984a-77ae6fd72a1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMzI0MTMsIm5iZiI6MTcwODIzMjExMywicGF0aCI6Ii83ODg4OTU3Mi8zMDU2ODM5NzgtZWE3NDlhMGEtYTRlNy00Zjc0LTk4NGEtNzdhZTZmZDcyYTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA0NTUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZTU2NDU4YjQ5OWM5ZDk5YThlNjg1ZGYzMTNkNWZkOTZkOTA5ZmMyNDczYzlhN2E1MjRkMWQwNTcwMWVhMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mz86xM4cCwmJlTC49GlRTGo2yJabWvcJM6NtMva1M34)
> 
> 1. const result = await fetch(`http://localhost:${process.env.PORT}/store`); this is the line where I'm getting error. const result is undefined.
> 2. Does this issue need to be solved before writing the tests?
>    Any help would really be appreciated. Thanks!

@Anvita0305  Not sure about this. But I think you can delete lines if it has any unused variables or code lines. 
You can take some reference from here: https://github.com/PalisadoesFoundation/talawa-admin/pull/1363/files

**Comment by Anvita0305** [comment]
Hello, I have a doubt. In AddOnStore.tsx file, a filter pluginInstallStatus == true is added for the Installed Tab. However I am not able to find it in the schema. 
So, I have upgraded it to filter the orgs whose orgId is not in uninstalled orgs array. Is this logic correct? If not, I will revert it to original code.

**Comment by palisadoes** [comment]
@SiddheshKukade This looks like a question for you.
