### ISSUE TITLE
Inconsistent Theme and Missing Tab Color Change in Event Details Sidebar 

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-admin#1041]
**Bug Description:**
The Event Details sidebar does not match the Orglist UI, and the tab colors do not change when options are selected.

**To Reproduce:**
1. Go to the Events Tab.
2. Create an Event.
3. Click on "Show Event Dashboard."

**Expected Behavior:**
1. The theme of the Event Details sidebar should match the main page.
2. The background color of selected tabs should change to a distinguishable color when options are selected.
3. Icons should align with the existing icon pack.

**Actual Behavior:**
1. The Event Details sidebar does not match the Orglist UI.
2. Tab colors remain unchanged when options are selected.
3. The background color and icons are inconsistent with the expected theme.

**Screenshots**
![WhatsApp Image 2023-11-05 at 16 03 27_2e331e58](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/cc035b2d-8db5-4a89-9038-d0bdaa15ad8a)
![WhatsApp Image 2023-11-05 at 16 03 10_67f70071](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/c3b03973-e345-43de-a8ed-9916e07543f6)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens. Stay tuned, we expect these issues to be created during the first week of November 2023. @rishav-jha-mech is leading this process for the Talawa Admin project
4. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
