### ISSUE TITLE
Code Coverage: Create tests for src/components/AddOn/core/AddOnRegister/AddOnRegister.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1042]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kirtanchandak** [comment]
Hey, @palisadoes the test for this component is already written, do we need to write it again or is it wrong?

**Comment by noman2002** [comment]
Hey, @kirtanchandak the test is written but the coverage is only 93%, you have to get it to 100% by writing tests for missing lines.

**Comment by kirtanchandak** [comment]
got it, can you assign this issue to me?

**Comment by kirtanchandak** [comment]
got it, can you assign this issue to me?

**Comment by noman2002** [comment]
Done

**Comment by palisadoes** [comment]
unassigning due to inactivity

**Comment by punitkr03** [comment]
Hey @palisadoes , I want to work in this issue please assign me.
