### ISSUE TITLE
Bug Report: No option to return back to Event page from Event dashboard page

### ISSUE THREAD

**Issue by kanhaiya04** [PalisadoesFoundation/talawa-admin#1050]
**Describe the bug**
There is no option on event dashboard page to return back to event page of the organization.

**To Reproduce**

1. Open event dashboard page of any event.
2. You will notice that there in no option to return back to events page from here.

**Expected behavior**
There should be **All Events** options in the sidebar through which one can return back to events page.

**Actual behavior**
We have to rely on the browser's back button to navigate back to the events page, which can sometimes lead to a breakdown and result in errors.

**Screenshots**
We can add a new option **All Events** just below the View Event Statistics button in the sidebar.
![Event page](https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/33d794ea-b8d3-43e2-a82f-418df636c346)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
@palisadoes Please assign me this issue.

**Comment by palisadoes** [comment]
@Ayush0Chaudhary will be handling the issue and PR assignments

**Comment by Ayush0Chaudhary** [comment]
@kanhaiya04 updates?

**Comment by kanhaiya04** [comment]
@Ayush0Chaudhary working on it. I will create PR soon.
