### ISSUE TITLE
Parent Tracking issue for Q3 2024 tests

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1056]
These tests need to be completed prior to GSoC 2024

- #1055
- #1054
- #1045
- #1044
- #1043
- #1042
- #1040
- #1039
- #1038
- #1037
- #1036
- #1035
- #1034
- #1033
- #1032
- #1031
- #1030
- #1029
- #1028
- #1027
- #1026

**Comment by ASCE-D** [comment]
Hello @palisadoes, I'm interested in contributing can I create tests for the open one's ?

**Comment by noman2002** [comment]
@ASCE-D Please comment on the children issues to get it assigned.

**Comment by ASCE-D** [comment]
Thank you for replying @noman2002 , I'll comment on the children issues.
