### ISSUE TITLE
Add Password Strength Bar in Signup Form

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-admin#1058]
**Bug Description:**
The signup form currently lacks a password strength bar, making it challenging for users to assess the strength of their chosen passwords during registration.

**To Reproduce:**
1. Navigate to the signup page.
2. Enter a password without a strength indicator.
3. Observe the absence of a password strength bar.

**Expected behavior:**
A password strength bar should be implemented in the signup form to visually represent the strength of the entered password, providing users with feedback on the security of their chosen passwords.

**Actual behavior:**
The signup form does not feature a password strength bar, leaving users unaware of the strength of their passwords during the registration process.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

![example](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/83715dc9-ec91-416f-8312-162b1733ebd9)

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/630f7fd0-630f-4b59-9691-49940cf7209e)

**Comment by noman2002** [comment]
@duplixx We already have validation for the password fields, adding a bar is not required.
