### ISSUE TITLE
Code Coverage: Create tests for src/components/CheckIn/CheckInModal.tsx 

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-admin#1063]
### Description

The `CheckInModal.tsx` component currently lacks comprehensive test coverage. To ensure its robustness and functionality, we need to create test cases that cover various scenarios.

### Steps to Reproduce

1. Open the `CheckInModal.tsx` component.
2. Observe the absence of sufficient test coverage.
3. Recognize the need for comprehensive tests to validate the component's behavior.

### Expected Behavior

The `CheckInModal.tsx` component should have a suite of tests that cover different use cases, ensuring its reliability and responsiveness.

### Suggested Test Cases

- [ ] Test the component when opening the modal.
- [ ] Test the behavior when submitting a check-in.
- [ ] Test the validation of input fields.
- [ ] Test the component with different input scenarios.

### Checklist

- [ ] Write test cases for the `CheckInModal.tsx` component.
- [ ] Ensure the tests cover various use cases and scenarios.
- [ ] Verify that all existing tests pass successfully.
- [ ] Update documentation if necessary.

**Comment by noman2002** [comment]
@duplixx Please add a screenshot of current coverage.

**Comment by duplixx** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/7082ddaa-1968-4f26-8d7a-f8dcb0f260c7)
here it is..

**Comment by noman2002** [comment]
@duplixx The screenshot shows this file already have 100% coverage.
