### ISSUE TITLE
Code Coverage: Create tests for src/components/DeleteOrg/DeleteOrg.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1066]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ShatilKhan** [comment]
Please assign me this issue @palisadoes

**Comment by skbhagat0502** [comment]
@noman2002 if no one is working on this issue then please assign me this

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by ShatilKhan** [comment]
hi, so sorry for the inactivity 
Can you please reassign? @palisadoes 
I will complete it promptly this time
I was not active for a few days actually

**Comment by VaibhavTalkhande** [comment]
I want to work on this issue assign me

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no open PRs

**Comment by meetulr** [comment]
I'd like to solve this.

**Comment by ShatilKhan** [comment]
sorry for the delay, I've made a PR, I'm a bit new to writing test coverage , hence it took me time to understand the code

**Comment by VaibhavTalkhande** [comment]
I am working on it

**Comment by VaibhavTalkhande** [comment]
@palisadoes  i am done can review my pr

**Comment by VaibhavTalkhande** [comment]
Can you close this issue @palisadoes
