### ISSUE TITLE
MVP - Talawa Admin

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1069]
We need to have an Talawa MVP by the end of the year. The MVP will be the master branch. To do this we will need to remove features that either don’t work or have insufficient functionality. 

The features to remove include:

1. Links to chat
1. Notifications
1. Dynamic linking

Other

1. You need to work on removing these functionalities from this repo and work with the contributors below to make sure the correct functionality occurs in the other repos.
1. Documentation related to configuring these features needs to be removed as they will be no longer valid.
1. Test code coverage needs to be maintained. Coverage for the PR patches needs to be 100%

The plan is to:

- remove these features from the develop branch by commenting out the code.
- merge the develop branch not containing these features into our master branch.
- make the master branch the default

Please work with @Ayush0Chaudhary (Talawa impacts), @EshaanAgg & @xoldyckk (Talawa-API impacts) @beingnoble03 (Talawa-Admin impacts). Ask to be assigned this task by them.

Issues related to this one include:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1069
- https://github.com/PalisadoesFoundation/talawa-api/issues/1427
- https://github.com/PalisadoesFoundation/talawa/issues/2108

**Comment by duplixx** [comment]
Hey @Ayush0Chaudhary I can work with you in this milestone, Please let me know if you have any specific guidelines or instructions for this process.

**Comment by skbhagat0502** [comment]
@Ayush0Chaudhary @beingnoble03 @xoldyckk @EshaanAgg  I would also like to work on this issue.

**Comment by palisadoes** [comment]
@duplixx Please work with @beingnoble03 on this. He is very familiar with this repo.

**Comment by duplixx** [comment]
@palisadoes sure, hey @beingnoble03 please let me know if you have any specific instructions regarding the milestone.
Thanks!!

**Comment by duplixx** [comment]
Hey @beingnoble03 ,
I've made progress on the removal of the dynamic linking to the chat section. I've commented out the relevant code and ensured that test coverage is maintained.

Regarding the notification functionality, could you please clarify what specific notifications are being referred to? Is it related to user notifications, system alerts, or something else?

**Comment by noman2002** [comment]
@duplixx Comment out the notification which uses firebase i.e. user notification.

**Comment by duplixx** [comment]
@noman2002 user notification isn't part of Talawa Admin , i have searched in repo..didn't able to find it ,aprt from that everything is done now!!

  **Remove**
- [x] Links to chat
- [x] Dynamic linking

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/2493f256-6396-4098-a2ad-b07bddf8770d)
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/71ac77ac-2cb4-479c-9010-c0f2e2e73dcc)
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/2edbd082-ce4a-45f6-8e28-c1a29245e8bf)

**Comment by palisadoes** [comment]
@duplixx Thanks for that insight. Please proceed with your existing PRs so that we can get the MVP live in the coming days.
