### ISSUE TITLE
Implement sorting on the organizations screen  

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1072]
**Describe the bug**
Currently sorting is not implemented in the organization screen, the aim is to implement the sort functionality with latest first, oldest first etc. options, you can refer from the posts screen.

**To Reproduce**

1. login into the talawa admin dashboard 
2. go to the orglist
3. navigate the sort button
4. see the issue

**Expected behavior**
sorting of organization on the basis of defined and selected attributes.

**Additional details**
NA
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
@aashimawadhwa, I would like to work on this issue. Please assign me :).

**Comment by LakshyaSatpal** [comment]
@akhilender-bongirwar Hey, are you working on this?

**Comment by akhilender-bongirwar** [comment]
@LakshyaSatpal, please check this PR #1076
