### ISSUE TITLE
Implement sorting on the users screen

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1074]
**Describe the bug**
Currently sorting is not implemented in the users screen, the aim is to implement the sort functionality with latest first, oldest first etc. options, you can refer from the posts screen.

**To Reproduce**

1. login into the talawa admin dashboard 
2. from the menu navigate to the users option
3. navigate to the sort button

**Expected behavior**
sorting of users on the basis of defined and selected attributes.

**Additional details**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by chandel-aman** [comment]
@aashimawadhwa 
I would like to work on this issue as well.
Could you assign me this?

**Comment by palisadoes** [comment]
@chandel-aman Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by chandel-aman** [comment]
> Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

Thank you for the reminder.
I understand the policy and will make sure to adhere to it going forward. If it's acceptable, I would like to continue working on the already assigned issue. However, if that's not possible, I'll promptly unassign myself and patiently wait until my existing issues are closed.

**Comment by kirtanchandak** [comment]
Can you assign this issue to me? 
and what basis do we need to sort the users for eg. what should happed when a user clicks on ```Action1```, ```Action 2```...

**Comment by noman2002** [comment]
@kirtanchandak You already have 2 issues assigned to you on talawa-api. Please get the PRs merged before asking for more issues. As per the rules, you can only have 2 issues at once in your name.

**Comment by skbhagat0502** [comment]
@noman2002 Can I work on this issue.

**Comment by akhilender-bongirwar** [comment]
@noman2002 , I would like to work on this issue. Please assign me : )

**Comment by Prajwaldindokar5** [comment]
@noman2002  , i would like to work on this issue , so please provide me more details about it and i have one doubt that to handle sorting first we need to implement the logic on api first then on frontend.

**Comment by noman2002** [comment]
@Prajwaldindokar5 Issues as assigned on the basis of first come first serve basis.

**Comment by Prajwaldindokar5** [comment]
ok , not a problem
