### ISSUE TITLE
Replace CodeQL in GitHub Actions: Deprecation

### ISSUE THREAD

**Issue by DangaRanga** [PalisadoesFoundation/talawa-admin#108]
**Is your feature request related to a problem? Please describe.**
After experiencing quite some difficulty to get CodeQL consistently running for all, we have come to the decision to remove the workflows that use CodeQL.

**Describe the solution you'd like**
In light of this, we will have to find another static code analysis tool to scan the code base for anti-patterns and potential vulnerabilities.

**Comment by palisadoes** [comment]
@uzair-ali10 This may be interesting for you

**Comment by Devesh21700Kumar** [comment]
@palisadoes https://docs.sonarqube.org/latest/analysis/github-integration/
Sonar cube is probably the perfect replacement.

**Comment by Devesh21700Kumar** [comment]
> @palisadoes @yasharth291 @DangaRanga https://docs.sonarqube.org/latest/analysis/github-integration/ Sonar cube is probably the perfect replacement.

Sonarqube has to be updated with repo info too and then with GitHub actions it can be used.

**Comment by palisadoes** [comment]
@Devesh21700Kumar Sonarqube requires a lot of setup, such as:
- importing your repos into their system, and 
- integration with GitHub Enterprise.

Based on my research, CodeQL runner was deprecated and integrated into CodeQL. So this issue may not be relevant from a deprecation point of view.

CodeQL runs, however we are getting this error:

![image](https://user-images.githubusercontent.com/16875803/147848998-a40fa8f5-a343-44b4-bcff-23a34d5b7d9f.png)

Can you determine how to fix this?

**Comment by Devesh21700Kumar** [comment]
> @Devesh21700Kumar Sonarqube requires a lot of setup, such as:
> 
> * importing your repos into their system, and
> * integration with GitHub Enterprise.
> 
> Based on my research, CodeQL runner was deprecated and integrated into CodeQL. So this issue may not be relevant from a deprecation point of view.
> 
> CodeQL runs, however we are getting this error:
> 
> ![image](https://user-images.githubusercontent.com/16875803/147848998-a40fa8f5-a343-44b4-bcff-23a34d5b7d9f.png)
> 
> Can you determine how to fix this?

https://github.com/PalisadoesFoundation/talawa-admin/pull/204

This should fix it

**Comment by palisadoes** [comment]
Fixed with:
- https://github.com/PalisadoesFoundation/talawa-admin/pull/204
