### ISSUE TITLE
Bug Report: Error while loading the organization data

### ISSUE THREAD

**Issue by kanhaiya04** [PalisadoesFoundation/talawa-admin#1080]
**Describe the bug**
On the Edit Profile page for user details, encountering an error occurs after successfully updating the details or clicking the cancel button. This error disrupts the loading of organization data, prompting users to navigate back to the 'All Organizations' page and then return to the dashboard.

**To Reproduce**

1. Open organization dashboard
2. Open the user details of admin or super admin from bottom left
3. Click on the Edit profile options
4. Try to update or just click on the cancel button.

**Expected behavior**
After coming back to organization dashboard from edit profile page either by clicking on save or cancel button, organization details should be displayed properly.

**Actual behavior**
There is a error while fetching the data after coming back to dashboard from edit profile page.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/169aa35c-bc73-4cd5-9b0e-e45fe3a4e7cf

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
hey @aashimawadhwa , please assign me this.

**Comment by aashimawadhwa** [comment]
assigned @kanhaiya04
