### ISSUE TITLE
Bug Report : User profile page is not responsive for mobile screens

### ISSUE THREAD

**Issue by MahendraDani** [PalisadoesFoundation/talawa-admin#1083]
**Describe the bug**
- The `user details` page is not responsive for mobile screens.
- The profile details overflow with the profile image icon
- The `main`, `organizations`, `events` sections are not readable.

**To Reproduce**

1. Login as admin
2. Go to organization dashboard
3. Click on user details by scrolling to bottom of sidebar
4. Inspect the website for responsive viewports. 

**Expected behavior**
- The user details page should be responsive and readable.

**Actual behavior**
- The user details page is not responsive for mobile view and the details overflow over profile image

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/116940083/4c788d8c-3184-460e-a09c-3195b7ff7d9a

**Additional details**
I would like to work on this issue.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by MahendraDani** [comment]
@aashimawadhwa I would like to work on this issue

**Comment by aashimawadhwa** [comment]
@rishav-jha-mech @palisadoes

**Comment by palisadoes** [comment]
@rishav-jha-mech will provide his input by the weekend.

**Comment by noman2002** [comment]
@MahendraDani Reduce the size of avatar as per screen size.

**Comment by MahendraDani** [comment]
> @MahendraDani Reduce the size of avatar as per screen size. 

Yes.
