### ISSUE TITLE
Bug Report: Event Project in Event Dashboard is not Responsive in Desktop Screen

### ISSUE THREAD

**Issue by aialok** [PalisadoesFoundation/talawa-admin#1089]
**Describe the bug**
- In Event Dashboard Event Project Cards are not responsive in desktop screen

**To Reproduce**

1. Login as admin in desktop
2. Go to Event Dashboard
3. Add some Event Projects
4. You will see that event project are not responsive.

**Expected behavior**
Event project cards should be responsive and user-friendly. When adding a project, and inside the project, when adding an event task, the task description is expected to be responsive.

**Actual behavior**
 Event project cards are not responsive; they occupy excessive space vertically and are not aligned properly.
 
**Screenshots**
 Before :

[cinnamon-2023-11-24T220358+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/c4990439-505f-4c65-9119-c8c1bd9ad532)

 After : 
 
[cinnamon-2023-11-24T220451+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/baa444a2-7dd0-4be9-b4cd-b2f339ebdd42)

**Additional details**
I would love to work on this issue : )

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
@aashimawadhwa  I would love to work on this issue : )

**Comment by aashimawadhwa** [comment]
@aialok  assigned to you

**Comment by aialok** [comment]
@aashimawadhwa  please have a look.
