### ISSUE TITLE
Bug Report : Visiting advertisement throws error

### ISSUE THREAD

**Issue by pateldivyesh1323** [PalisadoesFoundation/talawa-admin#1092]
**Describe the bug**
Visiting created advertisement shows error. 
` endDate.toDateString is not a function `

**To Reproduce**

1. Login as Super admin
2. Go to advertisements page
3. Create a new advertisement if there is not any
4. See the error

**Expected behavior**

` endDate ` should be passed as a Date object to use ` toDateString() ` function.

**Actual behavior**

` endDate ` is passes as string which throws the error.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/36c4623d-2523-41a6-ac9e-ad0e8f6e1eb0)

**Additional details**

I would like to work on this.

**Comment by palisadoes** [comment]
Make sure the tests for the file(s) you are modifying have 100% code coverage when complete

**Comment by pateldivyesh1323** [comment]
@palisadoes The file I need to modify has only 45% test coverage, so do I need to write more test?

**Comment by palisadoes** [comment]
Yes to get it to 100% coverage. We are currently at an unacceptable level across the repository code base.

**Comment by AmitSharma512** [comment]
@palisadoes I have fixed the above bug, and some more bug which were on the advertisement page after solving the above bug like : 
1) if we create one advertisement, we get to see 4 cards of same advertisement on the active advertisement page.
2) the link which we provide while creating advertisement was also not visible on the card.
so , I have fixed all the above issues.

**Comment by palisadoes** [comment]
1. @AmitSharma512 Thanks for your enthusiasm. Let's give @pateldivyesh1323 a chance.
2. @pateldivyesh1323 Please work with @noman2002 on any future questions related to this issue or the resulting PR.

**Comment by noman2002** [comment]
@pateldivyesh1323 Did you used the correct relative path ?

**Comment by SiddheshKukade** [comment]
@pateldivyesh1323 have you followed the steps shown in the YouTube video of advertisements ?
