### ISSUE TITLE
Docs: Mark User as Super admin in MongoDB to run talawa-admin locally 

### ISSUE THREAD

**Issue by LakshyaSatpal** [PalisadoesFoundation/talawa-admin#1098]
**Describe the bug**
https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/INSTALLATION.md#talawa-admin-registration
This section in the documentation doesn't say about marking the user as super admin in the database to log in locally. 

**To Reproduce**

See https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/INSTALLATION.md#talawa-admin-registration

**Expected behavior**
We should mention a link to https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#manually-adding-the-first-super-admin-user. This section in `INSTALLATION.md` of `talawa-api`, clearly describes how to mark the user as super admin

**Screenshots**
Following is the screenshot of current documentation
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/81241551/fd4e0ecb-827a-494e-ba3c-965d60ca4516)

**Comment by LakshyaSatpal** [comment]
I can fix this. Please assign it to me

**Comment by palisadoes** [comment]
This is covered in the API documentation which you have to setup prior to installing Admin.
- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/INSTALLATION.md#setting-up-env-last_resort_superadmin_email-parameter 

Closing. If you disagree, let me know.
