### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by AmitSharma512** [PalisadoesFoundation/talawa-admin#1101]
**Describe the bug**
Whenever we create an Advertisement, we provide a link for the advertisement, but when the ad is displayed under the active campaigns section, the link is not rendered on the advertisement Card; in the code, it is written that the link should be present, but somehow, it is not rendering.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create an advertisement.
2. Provide some link while creating.
3. Then, go to the active campaigns section.
4. The link is not visible on the Card.

**Expected behaviour**
The link should also be present on the Card according to the code.

**Actual behaviour**
The link is not being rendered on the Advertisement Card.

**Screenshots**
Advertisement form Image : 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/a1f441c0-3664-4b77-b79c-36540a522151)

Card Image :
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/2ad65a76-9444-4ce3-b194-a149965c274c)

**Additional details**
I would love to work on this issue.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by noman2002** [comment]
@AmitSharma512 What you mean by link is not displayed?? Please attach a video to understand the bug.

**Comment by AmitSharma512** [comment]
Creating ad:
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/29a46f53-e8f0-4cce-b27d-0c55aa8c6513)

The link provided while creating the ad is not rendering before fixing :
   Card image before fixing bug :
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/ed9a13a8-0d7d-454e-afeb-95928da0e958)

The link provided while creating the ad is rendering after fixing :
   Card image after fixing bug :
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/fe685f2d-1736-41b6-9027-94c274a0c6e2)

**Comment by noman2002** [comment]
@AmitSharma512 We don't want that link to be displayed there, it is the link of content that will be shown on the banner.

**Comment by AmitSharma512** [comment]
but in the codebase it is written in code that card contains link:

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/53f26f3a-acd6-4339-a16d-b97fc7c0d19c)

**Comment by noman2002** [comment]
@SiddheshKukade Please have a look.

**Comment by SiddheshKukade** [comment]
The link is not supposed to be displayed. Actually actually image URL. This isue can be closed
