### ISSUE TITLE
Configure Automated Dependabot Updates

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1104]
We need to make sure our code is constantly up to date especially for our `develop` branch. To do this we need to implement automated updates using dependabot. This has already been done with the Talawa repo, but we also need it done for this one.

Requirements

1. Weekly updates
1. Run against the `default` branch
1. Use the appropriate package system
1. Use the appropriate root directory

Other information

1. Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
1. Talawa Example: https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/dependabot.yaml

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Hi @palisadoes 

I would like to work on this.
