### ISSUE TITLE
Toast Messages not working while Deleting Organization.

### ISSUE THREAD

**Issue by AmitSharma512** [PalisadoesFoundation/talawa-admin#1108]
**Describe the bug**
When we delete an organization or a sample organization, no toast message of success is shown.

**To Reproduce**
Steps to reproduce behaviour:

1. Create a sample organization and an organization.
2. Go to the settings of these organizations.
3. Click on the Delete Organization button.
4. Now, you can see that no toast message is shown for both the sample and the created organization.

**Expected behaviour**
There should be a Toast message of success whenever we Delete an organization.

**Actual behaviour**
No Toast message is shown whenever an organization is deleted.

**Screenshots**
Before fixing :
https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/a6ce0fa6-9e3c-4841-865c-066d590b66b4

**Additional details**
I want to work on this issue.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AmitSharma512** [comment]
@palisadoes I want to work on this issue

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens. @rishav-jha-mech is leading this process for the Talawa Admin project
4. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing

**Comment by AmitSharma512** [comment]
@palisadoes the code for the toast message is written in the code , but it is not working, I just fixed it so that the user can interact and the user can know what happened and the code is using windows.replace instead of using react routing like "Use history", 
So , these are the issues which I have fixed.

**Comment by palisadoes** [comment]
Thanks for the clarification. I'll reopen and assign it to you.
