### ISSUE TITLE
Bug Report: Advertisement Deletion Not Reflected on Frontend but getting updated on Backend.

### ISSUE THREAD

**Issue by aialok** [PalisadoesFoundation/talawa-admin#1109]
**Describe the bug**
- Bug: Frontend does not reflect successful advertisement deletion despite backend update.

**To Reproduce**

1. Goto Talawa Admin Dashboard
2. In advertisement section 
3. Select Active or Completed Compaigns
4. Click on Delete Button

**Expected behavior**
- Upon deleting the advertisement, it is expected to be removed from the backend and no longer displayed on the frontend. However, despite deletion on the backend, the advertisement continues to appear on the frontend.

**Actual behavior**
- Despite attempting to delete the advertisement on the frontend, it persists and remains visible.

**Screenshots**
- Before

[Delete_Bug.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/1e633350-2f0b-4048-8d49-9d147cc55ff0)

- After

[Fixes_Delete_bug.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/85b44304-e09e-44fa-96c4-2b536984a599)

**Additional details**
- There are some more issues in the advertisement section. I'm not sure why we use window.location.reload() when creating an advertisement.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
@palisadoes I would love to work on this issue.

**Comment by beingnoble03** [comment]
@aialok We need to remove that `location.reload` function. Please create issues, as required to do so.

**Comment by aialok** [comment]
Sure, also there are some minor bugs. I will create an issue for the same.

**Comment by aialok** [comment]
@noman2002 can we close this now, as the pull request has already been merged?"
