### ISSUE TITLE
Bug Report: When creating a new advertisement in the Advertisement section, our page refreshes unexpectedly.

### ISSUE THREAD

**Issue by aialok** [PalisadoesFoundation/talawa-admin#1115]
**Describe the bug**
- Bug Report: In the Advertisement Section, when creating a new advertisement, our page refreshes due to the use of `window.location.reload()`.

**To Reproduce**

1. Go To advertisement section 
2. Create a new advertisement 

**Expected behavior**
- After creating a new advertisement in the Advertisement Section, the page should remain static without any automatic refresh.

**Actual behavior**
- Currently, upon creating a new advertisement, the page refreshes unexpectedly due to the use of `window.location.reload()`.

**Screenshots**
- Before 

[cinnamon-2023-12-02T215527+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/15a01cf8-4d8d-47a5-8c87-82e8ae311617)

- After

[cinnamon-2023-12-02T223826+0530.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/c48c5ec2-4773-43ad-92ca-766ce7684788)

**Additional details**
- Additonally I have fixed another bug as well. Previously, when creating a new advertisement, it did not appear in the advertisement section immediately; a page reload was required. Additionally, I have set setFormState to its initial state.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
@palisadoes I would love to work on this issue please assign this to me.
Thank you  : )

**Comment by aialok** [comment]
> Hi, the reason it is not loading is because you're not filling up the dates. You can check on code that on those tabs I've used date logic to separate them.

Hi @SiddheshKukade sir, Can you please be more specific about the comment I am not able to find? Or are you referring to the loading of advertisements when we create a new one? Please clarify.

**Comment by git-init-priyanshu** [comment]
Hey @aialok are you still working on this?

**Comment by aialok** [comment]
Yes. I done with the code, I need to write some test case for the code I have changed.
Right now my end sem exams are going on that's why I am not creating a pull request.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no linked pull request

**Comment by hharshas** [comment]
I would like to do this

**Comment by aialok** [comment]
I am working on this issue, basically I have done with the code, but writing test cases creating some problem. I am working on issue. Will make a pull request by today.
And also my end semester exams was there.

**Comment by palisadoes** [comment]
> I am working on this issue, basically I have done with the code, but writing test cases creating some problem. I am working on issue. Will make a pull request by today. And also my end semester exams was there.

OK, I'll reassign it to you
