### ISSUE TITLE
PR Workflow Enhancement - Delta Error/Warning Checks

### ISSUE THREAD

**Issue by tasneemkoushar** [PalisadoesFoundation/talawa-admin#1117]
Description
Currently, our PR Workflow checks the entire codebase for linting, formatting, and type errors, which can be time-consuming. This enhancement request is to optimize the workflow to only check for errors and warnings in the lines of code that are changed or added in the pull request.

Details:

Linting: Only check for linting errors and warnings in the modified or added lines of code.
Formatting: Run formatting checks only on the changes introduced in the pull request.
Type Errors: Optimize the type-checking process to focus on the modified or added code.
Context

This is the required check - PR Workflow / Check for linting, formatting and type errors (pull_request)
This enhancement aims to speed up the PR review process by narrowing down the scope of checks to the code that is directly affected by the pull request. It helps in quicker identification and resolution of issues related to the changes introduced in the PR.
Expected Behavior
The PR Workflow should only check for linting, formatting, and type errors in the modified or added lines of code.
The workflow should be optimized to reduce processing time for pull requests.

Additional Information

 - [x] I have reviewed the current PR Workflow configuration.
 - [x] I have considered potential impacts on existing workflows.
 - [x] This enhancement aligns with our project goals.

**Comment by skbhagat0502** [comment]
@tasneemkoushar Please assign me this issue.

**Comment by noman2002** [comment]
Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by skbhagat0502** [comment]
@noman2002 I have created PRs for the issues which I have assigned for.Now I'm tackling a big LDAP issue challenge,which might take a month. Keeping in touch with @palisadoes for ongoing stuff, taking breaks for suggestions. Also, got the OK to handle smaller issues on the side.I have asked for thier permission to work on some issue on the way while working on this ldap authentication. If you think ok then Please assign me this.

**Comment by skbhagat0502** [comment]
Also I have created a PR for this same issue on the talawa api so I think this issue for this repo will not take time.

**Comment by duplixx** [comment]
@noman2002 i wanna contribute on this issue..please asssign me this
thanks !!

**Comment by tasneemkoushar** [comment]
sure @duplixx go ahead. But take this on priority

**Comment by duplixx** [comment]
yeah sure @tasneemkoushar i'll finish it on priority basis 
thanks!!

**Comment by duplixx** [comment]
Hi @tasneemkoushar,

I've made updates to the PR workflow to specifically check only the changed files rather than the entire repository. Could you please review it so that I can proceed to open the PR?

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/01c52bf6-be23-4d39-9cbf-e891811082c2)

**Comment by duplixx** [comment]
already fixed the issue and merged can you please close it

**Comment by palisadoes** [comment]
I had to revert the PR. A line you added is causing these PR tests to fail.

1. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7174182075/job/19536488975?pr=1180
2. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7170940986/job/19524818348?pr=1178
3. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7170548121/job/19523527658?pr=1170

Please resubmit

Blame output on the file
- https://github.com/PalisadoesFoundation/talawa-admin/blame/develop/.github/workflows/pull-requests.yml

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/dcdead2a-7fe8-4409-893e-90e437725bcf)

Reopening

**Comment by palisadoes** [comment]
@duplixx Please take a look. This needs to be resolved

**Comment by duplixx** [comment]
yeah i am fixing it will push by EOD

**Comment by duplixx** [comment]
`name: PR Workflow
on:
  pull_request:
    branches:
      - '**'

env:
  CODECOV_UNIQUE_NAME: CODECOV_UNIQUE_NAME-${{ github.run_id }}-${{ github.run_number }}

jobs:
  Continuous-Integration:
    name: Performs linting, formatting, type-checking and testing on the application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Install TypeScript
        run: npm install -g typescript

      - name: Run linting check
        run: npm run lint:check

      - name: Count number of lines
        run: |
          chmod +x ./.github/workflows/countline.py
          ./.github/workflows/countline.py --lines 1000 --exclude_files src/screens/LoginPage/LoginPage.tsx

      - name: Check formatting
        run: npm run format:check

      - name: Check for type errors
        run: tsc --skipLibCheck

      - name: Run tests
        run: npm run test -- --watchAll=false --coverage

      - name: Present and Upload coverage to Codecov as ${{env.CODECOV_UNIQUE_NAME}}
        uses: codecov/codecov-action@v3
        with:
          verbose: true
          fail_ci_if_error: false
          name: '${{env.CODECOV_UNIQUE_NAME}}'

      - name: Test acceptable level of code coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "./coverage/lcov.info"
          min_coverage: 95.0

  Graphql-Inspector:
    name: Runs Introspection on the github talawa-api repo on the schema.graphql file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.1'

      - name: Resolve dependency
        run: npm install -g @graphql-inspector/cli

      - name: Clone API repository
        run: git clone https://github.com/PalisadoesFoundation/talawa-api && ls -a

      - name: Validate Documents
        run: graphql-inspector validate './src/GraphQl/**/*.ts' './talawa-api/schema.graphql'
`



this should work now

**Comment by duplixx** [comment]
its merged please close this issue
thanks!!

**Comment by palisadoes** [comment]
We have to revert the PR. It is not being applied to the deltas
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7195213165/job/19597384890?pr=1190

**Comment by duplixx** [comment]
@palisadoes, I've made an attempt to address the issue, but unfortunately, I'm unable to resolve it. I would greatly appreciate assistance from the maintainers, especially @tasneemkoushar  in resolving this.

**Comment by palisadoes** [comment]
@duplixx  Could this work? Use the changed-files GitHub action to get a list of changed files and then use a BASH `for` loop to identify individual files to run the `tsc` against.
- https://github.com/marketplace/actions/changed-files
- https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by palisadoes** [comment]
@duplixx Any updates on this?

**Comment by duplixx** [comment]
Hey @palisadoes, I am resolving it as soon as possible. I have read the reference you shared. I'll update you by EOD

**Comment by duplixx** [comment]
@palisadoes I have added for loop for the changed file, Can you check it once.. 

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/b1a6f2e4-acb6-48d3-9106-001d6b74f2aa)

**Comment by tasneemkoushar** [comment]
@duplixx Yeah, the loop is fine, go ahead.

**Comment by tasneemkoushar** [comment]
@duplixx I have texted you on Slack, please check.

**Comment by duplixx** [comment]
Hello @tasneemkoushar @palisadoes,

I am proposing a solution to enhance our linting checks and streamline the pull request (PR) workflow. My suggestion is to leverage Husky for this purpose.

When we conduct linting checks on selected files through GitHub Actions, it can consume a significant amount of resources and time. Moreover, there's a risk of exceeding the actions time limit. To mitigate these challenges, I propose incorporating Husky into our workflow.

Husky is a tool that automates tasks like checking for ESLint and Prettier errors. It executes these checks on precommit, ensuring that errors are addressed immediately. This approach not only prevents the introduction of errors into the codebase but also fixes or flags lint and Prettier issues directly in developers' terminals.

By implementing Husky in our workflow, we can proactively identify and resolve issues during the development phase, avoiding disruptions to the PR workflow and ensuring a more efficient and error-free coding process.

**Comment by palisadoes** [comment]
1. I'll leave that up to you and @tasneemkoushar 
2. We are already using husky in the API and/or Admin 
3. We'll still need to check the delta files in the PR in case people bypass the husky based CLI. So think of ways in which this could be done.
4. Remember in most cases we are editing only a few files at a time. So the `for` loop won't be a huge burden. Even so, think of ways to optimize the GitHub action to achieve the goal of checking the changed files

**Comment by duplixx** [comment]
It should work now this is solution i got from documentations and many organizations are using this way 

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/460c7065-f4b7-4a8a-8f1b-d3f3f3a5ebb5)




![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/85a7f0f6-2a69-4566-8e01-1ee27a84d58e)

**Comment by duplixx** [comment]
@tasneemkoushar can we check it now if this works

**Comment by palisadoes** [comment]
@duplixx Please work with @anwersayeed on this for the next week as @tasneemkoushar will be unavailable

**Comment by duplixx** [comment]
sure !!

**Comment by duplixx** [comment]
@anwersayeed can you check the pull request i have raised regarding updated workflow
