### ISSUE TITLE
Fix in blocked user card navigation

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1120]
**Describe the bug**
currently in talawa dashboard the blocked user card navigate to all members screen in the block/unblock section.

**To Reproduce**
1. click on manage organization to navigate to dashboard
2. click on blocked user card from the dashboard
3.  see the issue

**Expected behavior**
it should navigate to the blocked user screen in the block/unblock section

**Actual behavior**
it navigates to all members screen in the block/unblock section.

<img width="1438" alt="Screenshot 2023-12-04 at 10 25 12 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/23af9182-b21a-4fe4-9e82-bcf06ae46fe5">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
@aashimawadhwa  I would love to work on this issue.

**Comment by duplixx** [comment]
@aashimawadhwa can you assign me this issue i wanna work on this.
Thanks !!

**Comment by aialok** [comment]
@duplixx  I have already fixed this issue, just waiting for it to be officially assigned to me.

**Comment by duplixx** [comment]
hey @aialok as per policy contributors can be assigned two tasks at times and you have reached your limit . Am i right @aashimawadhwa @noman2002 ??

**Comment by aialok** [comment]
@duplixx  one of the pull request is already merged. Just issue need to get close.

**Comment by hharshas** [comment]
I would like to work on this issue.

**Comment by Vaishali054** [comment]
I would love to work on this issue if it is still available.

**Comment by aashimawadhwa** [comment]
Hey we work on first come first served policy therefore assigning the issue to @aialok, you guys can look around for other issues

**Comment by aialok** [comment]
I will be fixing this by tomorrow as my end sem exams are going on.
