### ISSUE TITLE
Pinning functionality in the create post modal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1122]
**Is your feature request related to a problem? Please describe.**
Adding pin post option in the create post modal in post screen under dashboard.

**Describe the solution you'd like**
The pin post modal should have a toggle button to enable pinning and unpinning post through the create post modal itself.

**Additional context**
you can take reference for the toggle button UI from the create organization modal.
<img width="171" alt="Screenshot 2023-12-04 at 10 59 26 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/dfbb7814-173b-4687-92b5-ed2a1757b729">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by noman2002** [comment]
@AishaAgarwal Please follow the steps in INSTALLATION.md. If you still face the issue, please ask in the slack channel.

**Comment by AishaAgarwal** [comment]
ok..understood,..thanks

**Comment by AmitSharma512** [comment]
@aashimawadhwa can i work on this issue.

**Comment by AmitSharma512** [comment]
@aashimawadhwa what to do with the pin post feature in the post modal ?
like, it should also be there or we have to remove it from there. 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/e97684a3-47e2-48d3-8c0e-87a3d8952b0a)

**Comment by duplixx** [comment]
@aashimawadhwa can you assign me this issue 
Thanks!!

**Comment by AmitSharma512** [comment]
@duplixx Bro i have completed this issue :)))))))

**Comment by duplixx** [comment]
Great @AmitSharma512, make sure to link the PR with the corresponding issue for better tracking.

**Comment by AmitSharma512** [comment]
@duplixx yeah sure, as soon as I am assigned to this task I will make the PR.

**Comment by Cioppolo14** [comment]
@AmitSharma512 Is this still making progress?

**Comment by noman2002** [comment]
Unassigned due to inactivity.

**Comment by pateldivyesh1323** [comment]
@noman2002 I would like to work on this.
