### ISSUE TITLE
fix in position and text of all organization button

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1123]
**Is your feature request related to a problem? Please describe.**
All organization button is not intutive

**Describe the solution you'd like**
Position the all organization button at the top of the menu (i.e above dashboard button) and change all organization text to my organizations

**Additional context**
<img width="317" alt="Screenshot 2023-12-04 at 11 09 09 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/7c333a39-37a9-42fd-a39f-05bd4cf53401">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by adi790uu** [comment]
Hey can I take up this issue!

**Comment by noman2002** [comment]
@adi790uu Create a new PR on develop not main.

**Comment by Veer0x1** [comment]
@noman2002 I would like to work on this.

**Comment by VaibhavTalkhande** [comment]
I would like to work on it assign me

**Comment by Cioppolo14** [comment]
Closing as complete.
