### ISSUE TITLE
 Fix in admin card navigation

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1126]
**Describe the bug**
 currently in talawa dashboard the admin card navigate to all members screen in Talawa Members section.

**To Reproduce**

1. click on manage organization to navigate to dashboard 
2. click on admins card from the dashboard
3. see the issue

**Expected behavior**
 it should navigate to the admin screen in the talawa members section

**Actual behavior**
 it navigates to all members screen in the talawa members section.

**Screenshots**
<img width="1438" alt="Screenshot 2023-12-04 at 10 25 12 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/23af9182-b21a-4fe4-9e82-bcf06ae46fe5">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by chandel-aman** [comment]
Can take this issue?

**Comment by noman2002** [comment]
Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by noman2002** [comment]
Assigned to you. The issue was not closed.

**Comment by chandel-aman** [comment]
> @chandel-aman  Assigned to you. The issue was not closed.

Thank you

**Comment by hharshas** [comment]
I would like to work on this issue @noman2002
