### ISSUE TITLE
Allow for a single object upload for posts

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1127]
**Is your feature request related to a problem? Please describe.**
In the create post modal we have 2 different fields to upload video and image post.

**Describe the solution you'd like**
we want to make  a single field that allows posting both images and videos through it, you can name the field as "Add media".

**Additional context**
make sure you manage the preview of the content within the model itself and manage the close preview state.
<img width="1152" alt="Screenshot 2023-12-05 at 9 19 09 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/209c213b-2bae-42a3-a87a-95ae2b84c604">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
hey can you assign me this issue @aashimawadhwa

**Comment by VaibhavTalkhande** [comment]
I would like to work assign me issue
