### ISSUE TITLE
Code Coverage: Create tests for src/components/Advertisements/Advertisements.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1130]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by PriyeshPandey2000** [comment]
hey @palisadoes can you assign this issue to me

**Comment by Cioppolo14** [comment]
@PriyeshPandey2000 I have now assigned you two issues. Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by RAGHAV-N5** [comment]
can I be assigned?

**Comment by VaibhavTalkhande** [comment]
I would like to work on it
