### ISSUE TITLE
Add the name of the organization as the title in the organization card

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-admin#1145]
**Is your feature request related to a problem? Please describe.**

The organization card on the orglist page contains the name of the organization at the end of the card.

<img width="1440" alt="Screenshot 2023-12-07 at 1 02 09 AM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/74401063-b4d1-466a-bb20-ff503aae14d3">

**Describe the solution you'd like**

It would be better to have the name of the organization displayed as the title of the organization card and also make the title more prominent. 

<img width="1440" alt="Screenshot 2023-12-07 at 11 58 51 AM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/14f8c105-22a3-4e58-95f7-b9e29864a48e">

**Describe alternatives you've considered**

1. Change the position of the name from bottom of the card to top.
2. Make the name of the organization more prominent

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by vivekBoii** [comment]
please assign this to me

**Comment by vivekBoii** [comment]
@palisadoes

**Comment by palisadoes** [comment]
> @palisadoes

Unfortunately I no longer assign issues due to the heavy workload, **no exceptions**. Please join our slack `#general` channel and see who will be handling all new issue assignments and seeking reviewers for PRs. Please work with these contributors on any queries you may have, they may not know the answer but will be able to find someone to assist.

**Comment by palisadoes** [comment]
@disha1202 Follow the issue template to create an issue with a better description of what you want to achieve. It is not clear. Let us know whether you want to work on the issue as the person who created it.

**Comment by noman2002** [comment]
@vivekBoii, Wait for @disha1202 to update the issue description and if she doesn't want to work on this issue then only you'll get assigned as she created the issue.

**Comment by disha1202** [comment]
@palisadoes @noman2002 Sorry for the inconvenience, I have updated the issue description, and I would like to work on resolving this issue.
