### ISSUE TITLE
Searching form members to be a single search modal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1155]
**Is your feature request related to a problem? Please describe.**
Requirement of a single search bar instead of  first name and last name search modal to provide a better search experience.

**Describe the solution you'd like**
A single search bar to search names in all 3 roles users, members and admins.

**Additional context**

**Current Situation:** 
![Screenshot 2023-12-07 at 7 46 04 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/4f603031-5c42-4cf6-ae61-39047cdeb2e9)

**Expected Results:**
![Screenshot 2023-12-07 at 7 46 55 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/8974ef45-fb06-4bab-a00e-923faad65125)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Min2who** [comment]
@aashimawadhwa  can i take this one ?

**Comment by Min2who** [comment]
@palisadoes This Issue can be closed now
