### ISSUE TITLE
Enabling media support to the create ad action

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1158]
**Is your feature request related to a problem? Please describe.**
We need media support on create ad action (both photo and video)

**Describe the solution you'd like**
An method to upload media in the create ad modal (you can refer the create post modal in the posts section from the menu).

**Additional context**
Please discuss your approach before starting with the solution and refer to this issue as well #1127 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by 1010varun** [comment]
Hey, @disha1202 if this issue is not solved yet can we both work on this??

**Comment by disha1202** [comment]
Hi @1010varun 

Here we follow one person, one issue policy. Can you please look for other open issues.

Thanks!

**Comment by disha1202** [comment]
Hi @aashimawadhwa, 

I am done with the implementation, I have added support to upload video and image in create advertisement modal. 



https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/df3fe7f1-cb1c-42f8-97e7-bd59590bedb2

<img width="1440" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/a9622d2b-f93d-408a-84ba-328594923bd3">



Here's the approach that I followed: 

1. Added an input of type file in AdvertisementRegister.tsx which accepts both images and videos
2. Rendered the media in the AdvertisementEntry.tsx file using a ternary operator for checking whether it is an image or video.

Do you have any better approach in mind? 
If not I'll create a PR shortly after some refactoring. 

Thanks!
