### ISSUE TITLE
Change in hamburger icon and handling of left drawer

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1159]
**Describe the bug**
Inappropriate placement of the hamburger icon

**To Reproduce**

1. Login to talawa admin
2. click on the hamburger button 
3.  see the error

**Expected behavior**
we want to change the UI and placement of the button to make the user experience more intuitive.

**Screenshots**
![Screenshot 2023-12-07 at 8 31 12 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/6dd37ba0-12d5-4799-a4ba-1ce2bf0a916f)

**Additional details**
![Untitled](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/b61c7be7-a4f2-4ee5-9ec7-1346f955a056)
Look how Docusaurus handles the left menu drawer in [Talawa Docs](https://docs.talawa.io/docs/)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Vaishali054** [comment]
@aashimawadhwa can you assign this to me

**Comment by hharshas** [comment]
@Cioppolo14 @aashimawadhwa  I would like to work on this issue.

**Comment by Vaishali054** [comment]
@noman2002 can you please close it?
