### ISSUE TITLE
Feature Request: Cache npm dependencies

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-admin#1160]
**Is your feature request related to a problem? Please describe.**
We can cache the `node_modules` folder in workflows with artifacts to ensure faster workflow runs. 

**Describe the solution you'd like**
[Refer to this guide](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by bhav-khurana** [comment]
Can I work on this issue?
