### ISSUE TITLE
Code Coverage: Create tests for src/components/Advertisements/core/AdvertisementEntry/AdvertisementEntry.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1167]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Min2who** [comment]
can i get assigned @palisadoes

**Comment by hharshas** [comment]
I would like to work on this issue @aashimawadhwa

**Comment by Min2who** [comment]
@Cioppolo14 you can close that 
![Screenshot 2023-12-11 105642](https://github.com/PalisadoesFoundation/talawa-admin/assets/127925465/11f81c09-0768-4d67-bf12-7c8c3f5c18d2)
as on working on #1170 i have achieved this

**Comment by GiteshDewangan** [comment]
@saksham-malhotra sir i want to start  with this issue can you provide me with the exact task???🙏🙏🙏

**Comment by Min2who** [comment]
@aarishshahmohsin @palisadoes 
This issue is completed by this PR #1170 on resolving #1156 

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/127925465/d2f9cb5e-e866-4ed7-bce4-baa006ba512b)

**Comment by noman2002** [comment]
@saksham-malhotra You can take other open issues as this is already covered.
