### ISSUE TITLE
Bug Report: An Inappropriate white line along the sidebar

### ISSUE THREAD

**Issue by hharshas** [PalisadoesFoundation/talawa-admin#1171]
**Describe the bug**
Inappropriate line above the hamburger icon in zoomed window or permanently in the mobile view.

**To Reproduce**

1. Login to talawa admin
2. Click manage to any created organization
3.  Go to people or events menu
4.  see the error

**Expected behavior**
Absence of line above hamburger icon or entire sidebar.

**Actual behavior**
we want to change the UI and placement of the line that disturbs the perfect user experience.

**Screenshots**
![Screenshot from 2023-12-09 21-51-01](https://github.com/PalisadoesFoundation/talawa-admin/assets/125907752/2904d65a-233d-4340-847a-57ea9dabef74)
![Screenshot from 2023-12-09 21-52-24](https://github.com/PalisadoesFoundation/talawa-admin/assets/125907752/0583832e-a2a0-451e-8e44-b33dec13f844)
![Screenshot from 2023-12-09 21-52-40](https://github.com/PalisadoesFoundation/talawa-admin/assets/125907752/64efd8f7-3792-4b63-ba86-fb838a9cf0e5)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
@palisadoes  @aarishshahmohsin  I would like to work on this issue.

**Comment by palisadoes** [comment]
> @palisadoes I would like to work on this issue.

Please watch this video and follow the process.
- https://www.youtube.com/watch?v=aYMK3YnTQsQ

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens. @rishav-jha-mech is leading this process for the Talawa Admin project
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
