### ISSUE TITLE
User and Admin toggle on Login and Registration Screen

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1173]
**Is your feature request related to a problem? Please describe.**
We need an interface to login to user portal provided by talawa which can be accessed by this url `http://localhost:3001/user` when you run talawa Admin and talawa API on your local machine

**Describe the solution you'd like**:

1. The login and registration form should have a toggle functionality.
2. This toggle should allow users to switch between user and admin roles seamlessly.
3. Users can select their role preference using a toggle switch to access the respective login or registration form.

https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/5d03cfd1-c0f8-40c8-97d2-6d6180569053

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by chandel-aman** [comment]
@aashimawadhwa @noman2002 
Can I take this issue?

**Comment by ASCE-D** [comment]
Hello Devs, I want to contribute, can I work on this issue?

**Comment by noman2002** [comment]
@chandel-aman You already have 2 issue in your name. 
@ASCE-D Assigning this to you.

**Comment by chandel-aman** [comment]
@noman2002 PR for both the issues have been merged

**Comment by chandel-aman** [comment]
@noman2002 Could you assign this issue to me, as I commented on it first. My both issues were merged but were not closed.

**Comment by noman2002** [comment]
@chandel-aman No worries. Let him work on this one. I think he is new here. You can take other issues. 👍🏻

**Comment by Devesh326** [comment]
Hi @ASCE-D are you still working on this issue?

**Comment by Ravi3727** [comment]
Hello everyone,
Is anyone working on this issue? or is this issue resolved??

**Comment by ASCE-D** [comment]
yes, I'm working, I have some questions that I've asked on slack and am waiting for a response.

**Comment by Ravi3727** [comment]
Ohh, okay fine

**Comment by aashimawadhwa** [comment]
@ASCE-D  what is the progress on this , we needed this on priority. you may ask your question here.

**Comment by hharshas** [comment]
I want to work on this issue.

**Comment by ASCE-D** [comment]
@aashimawadhwa I've been waiting for your response on slack from more than a week,
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/72039675/9e7c520d-33c9-4764-97e2-1b83fc71b618)
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/72039675/90159555-6b1f-4525-8bfc-3776c7914068)
I'll fix the CSS, my Q was can I make a separate component or just a conditional statement is fine
```{showAdmin ? 
 (<div className={styles.active_tab}> //login and registration form  </div>)                  
: <div className={styles.active_tab}>
   <UserLoginPage />
 </div>```

**Comment by aashimawadhwa** [comment]
I request you to ask doubts here not on slack @ASCE-D

**Comment by aashimawadhwa** [comment]
Update the css as it is in the video @ASCE-D

**Comment by ASCE-D** [comment]
@aashimawadhwa please check 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/72039675/01fc1880-2a2b-473d-8de1-2c3836ba4e47)

**Comment by aashimawadhwa** [comment]
Can you update a video showing the behaviour?
@ASCE-D

**Comment by ASCE-D** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/assets/72039675/0467ab40-ce50-4ce8-9fed-c682cb187bdf

@aashimawadhwa please check

**Comment by palisadoes** [comment]
@ASCE-D

If you have completed the task to your satisfaction then open a PR. There is no need to ask for validation here.

**Comment by ASCE-D** [comment]
@aashimawadhwa @noman2002 please review my PR #1332 , thankyou

**Comment by palisadoes** [comment]
Please follow the template for the reasons stated in the PR

**Comment by palisadoes** [comment]
Related PR
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1332

**Comment by palisadoes** [comment]
1. Closed partially in error. Please reopen another PR with the template filled in.
2. Reassigning.

**Comment by palisadoes** [comment]
@ASCE-D Are you still working on this?

**Comment by palisadoes** [comment]
Unassigning due to no response and a desire to get this implemented quickly

**Comment by meetulr** [comment]
I'd like to work on this.

**Comment by meetulr** [comment]
Do we just need a toggle between the two routes, so that we won't have to manually type the url?

**Comment by palisadoes** [comment]
1. Yes. 
2. Ideally with two separate tabs on the same screen without the need to re-enter a URL
