### ISSUE TITLE
Improvement in the SearchBars throughout Talawa Admin

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1174]
**Is your feature request related to a problem? Please describe.**
currently talawa have Dynamic Search Functionality .

**Describe the solution you'd like**
we need to implement search only after the user presses the "Enter" key, it is typically referred to as a "submit on enter" search.

**Additional context**
Implement this on all the search bars across talawa .

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by racky7** [comment]
Please assign this to me.

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by chandel-aman** [comment]
@aashimawadhwa can i take this issue?

**Comment by git-init-priyanshu** [comment]
Is this issue up for grabs? I would like to work on this. Thanks.

**Comment by racky7** [comment]
@git-init-priyanshu I am working on it.

**Comment by asv018** [comment]
Can you assign this issue to me? I will work on it.
