### ISSUE TITLE
Improved calendar view for events screen 

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1175]
**Is your feature request related to a problem? Please describe.**
The calendar screen does not provide with a good user expereince

**Describe the solution you'd like**
A new calendar view to match the User interface of talawa admin

**Additional context**
we can make something like this with colors and themes similar to what  used in talawa 
![Screenshot 2023-12-10 at 10 16 53 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/bc834322-d5ea-467d-88cf-7b5e24ae3e3c)

Note: Do fix the placement of add event button and remove the small calendar

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by chandel-aman** [comment]
@aashimawadhwa can i work on this issue?

**Comment by pateldivyesh1323** [comment]
@noman2002, @palisadoes This can be closed.
