### ISSUE TITLE
Needs UI improvement in User Details page.

### ISSUE THREAD

**Issue by git-init-priyanshu** [PalisadoesFoundation/talawa-admin#1176]
**Describe the bug**
Right now when we click on edit profile button on User Details page the UI looks like this:
<img width="960" alt="Screenshot 2023-12-11 151600" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/1b9c3a97-5bec-4008-bdec-8c5e119a6b7b">
<img width="960" alt="Screenshot 2023-12-11 151608" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/b947486b-c28c-475b-9bc5-fee07a157684">

**To Reproduce**

1. Login to talawa admin.
2. Click on the name of the admin on the bottom left of the screen. It will take you to the user details page.
3. In the user details page, click on edit profile.
4. You will see the issue.

**Expected behavior**
The input boxes here should be taking up more space. And Display Image field should be aligned with other fields.
<img width="960" alt="Screenshot 2023-12-11 151945" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/083bf7a3-430e-4941-ab74-d7da9406cbe5">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by git-init-priyanshu** [comment]
Please assign this to me.

**Comment by 1010varun** [comment]
I really want to work on this issue, please assign this to me
