### ISSUE TITLE
GitHub Action Required for Translation Files

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1185]
We need to create a GitHub action that during the PR process checks all the translation files to make sure that there are translations in all the non-default languages for each English default language entry.

As part of the PR for this issue, all the translations must be correctly present

- **NOTE:** Please watch this video on how to proceed.
[![Click me to start video](https://img.youtube.com/vi/GlqUm1UO-xM/0.jpg)](https://www.youtube.com/watch?v=GlqUm1UO-xM)

**Comment by ibishal** [comment]
can i work on it?

**Comment by Min2who** [comment]
can i get assigned?

**Comment by hharshas** [comment]
can i work on this ??

**Comment by RAGHAV-N5** [comment]
I would love to work on this! can i get assigned?

**Comment by 1010varun** [comment]
@noman2002 I want to work on this issue, please assign this to me.

**Comment by Min2who** [comment]
Hey @palisadoes @noman2002 should i make this github action in the push.yml or should make a new yml file

**Comment by noman2002** [comment]
Add it in both push and pull_request workflows.

**Comment by Min2who** [comment]
Hey @noman2002 some key are not present in the other language as compared to en.json
this would cause all the new PR to fail .Should i make a PR?

**Comment by noman2002** [comment]
Please add those missing keys in all other languages.

**Comment by Min2who** [comment]
anyone want to take it go ahead

**Comment by KRIXUS-alpha** [comment]
Hi @noman2002, requesting you to kindly re-assign this issue to me.

**Comment by sarthak17jain** [comment]
Hello @noman2002, I have read the codebase and I think that I can solve the issue. Please give me a chance to make my first contribution to the codebase.

**Comment by palisadoes** [comment]
Unassigning due to inactivity. We have implemented a similar solution 
1. https://github.com/PalisadoesFoundation/talawa/pull/2275
1. A good update to the script would be to use the ArgParse library to define the directory to be checked for translation files. That way we can use it with other repos.

**Comment by 1010varun** [comment]
@noman2002 can you assign this issue to me. I had commented previously

**Comment by 1010varun** [comment]
Hey @noman2002, 
Kindly review my PR once and suggest any changes that need to be added.

**Comment by 1010varun** [comment]
Hey @palisadoes,
You can close this issue now.

**Comment by palisadoes** [comment]
This issue was raised to fix this issue.
- https://github.com/PalisadoesFoundation/talawa-admin/issues/2260
