### ISSUE TITLE
Remove Filter on the organizations screen 

### ISSUE THREAD

**Issue by Hasnain01-hub** [PalisadoesFoundation/talawa-admin#1189]
**Describe the bug**
Remove filtering in the organization screen, the aim is to remove the filter code.

**To Reproduce**

1. login into the talawa admin dashboard
2. go to the orglist
3. navigate the filter button
4. see the issue

**Screenshots**
<img width="460" alt="Screenshot 2023-12-13 at 12 04 40 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/70531302/0e4d9ff6-ff70-43c0-bafa-817e672f2b95">

**Additional details**
NA

**Comment by Hasnain01-hub** [comment]
@palisadoes can you assign this issue to me?

**Comment by noman2002** [comment]
@aashimawadhwa Is this a valid issue ??

**Comment by Devesh326** [comment]
Hi @palisadoes
I just found this repository and would love to contribute! Can you elaborate  bit more regarding this issue.

**Comment by noman2002** [comment]
@Devesh326 We are assigning on first come first serve basis. This will be assigned to @Hasnain01-hub . You can take other open issues. Thanks

**Comment by Hasnain01-hub** [comment]
Hello @palisadoes @rishav-jha-mech @aashimawadhwa @noman2002, I have implemented the filter option in Orglist, but I have not got the feature parameters yet. So based on location (filter parameter is dynamic) I tried filtering. Also, I have implemented all the logic part on the client side, as it is more complex, and managing the state would be tougher so is it okay?
Result: 
https://github.com/PalisadoesFoundation/talawa-admin/assets/70531302/803f05ea-1522-4409-a410-7c459dd1ba25

**Comment by palisadoes** [comment]
We are currently evaluating our product road map and decided that this feature needs to be removed as we have greater priorities at this time. 

1. Please convert this to a feature removal issue
2. Make sure that the test code coverage is maintained
3. Ensure that no other features are affected

Thanks

**Comment by palisadoes** [comment]
@Hasnain01-hub This issue either needs to be:
1. closed with a new issue created to remove the feature which we can then assign to you, or
2. converted to an issue to remove the feature

**Comment by Hasnain01-hub** [comment]
@palisadoes Yes, convert the issue to remove the feature, Additionally, could you confirm whether the filter implementation meets the condition, in the previously uploaded video, or if it requires additional parameters?

**Comment by palisadoes** [comment]
1. We don't want the filter at all. Please remove it from the screen and any related code behind the scenes that may have been used to implement it.
2. This is an unwanted feature, as explained before

**Comment by Hasnain01-hub** [comment]
@palisadoes Sir I have removed the filter feature from Orglist screen, Please verify it and should I open the pull request for it?
Screenshot:
<img width="1416" alt="Screenshot 2023-12-23 at 12 49 19 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/70531302/bbab83fd-1e0c-40f8-980a-02594b2edc50">

**Comment by palisadoes** [comment]
Yes
