### ISSUE TITLE
Few very small UI bugs.

### ISSUE THREAD

**Issue by git-init-priyanshu** [PalisadoesFoundation/talawa-admin#1192]
**Describe the bug**
Bug 1: On the login page, the mail icon in the email input is overflowing out of the input div.
Bug 2: In the members page, We have 3 radio button, they are very weirdly placed.
Bug 3: The hamburger has a weird line going from top to bottom.

**To Reproduce**
Bug 1:
1. Go to login page
2. Here you can see the email icon is overflowing.
Bug 2:
1. Login 
2. Click on manage on any organization.
3. Click on People tab.
4. Under filter by name and under all the input fields you can see the bug.
Bug 3:
1. Login
2. Click on manage on any organization.
3. Click on People tab or the Events tab.
4. Here you can see the hamburger has that weird line.

**Expected behavior**
Bug 1: The email icon should not overflow out of the input div. It should be contained, just like in the password.
Bug 2: All three buttons should be vertically aligned
Bug 3: There should not be a vertical line across the hamburger.

**Screenshots**
Bug 1:
<img width="291" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/bb56f45b-4023-45bc-aa64-5743134970f4">
Bug 2:
<img width="132" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/b91b9e2d-70a1-444e-b429-ea779ab433ef">
Bug 3:
<img width="88" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/a470f014-08a9-4b86-8ea7-00bcd2acd3a4">

**Additional Details**
Since all these issues are very small, I included them on the same issue.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by git-init-priyanshu** [comment]
I would like to work on these issues. Thanks.

**Comment by Harshsharmaa28** [comment]
can i work on this issue @noman2002
