### ISSUE TITLE
Implement filter functionality for the users list in users page.

### ISSUE THREAD

**Issue by rishuraj1** [PalisadoesFoundation/talawa-admin#1196]
**Is your feature request related to a problem? Please describe.**
Currently the filter option is present in the UI, but not implemented.

**Describe the solution you'd like**
I want to implement the filter functionality.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
Filter by role of the user 
<img width="960" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/47839626/6f1002ec-4e00-4c1d-840f-bc0c0f5812bb">

**Additional context**
I really want to work on this feature, please assign this to me.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by racky7** [comment]
Please assign it to me.

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by PriyeshPandey2000** [comment]
please assign this issue @rishuraj1

**Comment by rishuraj1** [comment]
hi @Cioppolo14 , I was hoping to work on this one, as I have created this issue according to fcfs .

**Comment by noman2002** [comment]
@rishuraj1 This is already assigned to someone. Please look for other open issues.

**Comment by Cioppolo14** [comment]
@aarishshahmohsin  Are you working on this?
