### ISSUE TITLE
A dialog/toast when the API is unavailable, both at login and during the login session in user portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1197]
**Describe the bug**
We require a dialog at user login form  when the API is unavailable which can be accessed from here `http://localhost:3000/user` with the message shown in image below.

**To Reproduce**

1. run the talawa admin and do not run API
2. access the user login form
3. see the issue

**Expected behavior**
A clear message similar to talawa admin portal

**Actual behavior**
No dialog/toast found

**Screenshots**
![Screenshot 2023-12-15 at 3 03 36 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/fbf89e55-7360-4b60-8445-9c5925de4ced)

**Additional details**
NA
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by rishuraj1** [comment]
Hi, @aashimawadhwa I believe it can be achieved by using react-toastify. Can you please assign this one to me. Thanks

**Comment by Shubh152** [comment]
I would like to work on this. Please assign this issue to me @aashimawadhwa

**Comment by nick2432** [comment]
can i work on this ?

**Comment by VaibhavTalkhande** [comment]
I would like to work on it

**Comment by Shubh152** [comment]
Unassigning as the PR was merged
