### ISSUE TITLE
Post dialog needs to be modified like linkedin

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1198]
**Describe the bug**
The post dialog in the home screen in the user portal which can be accessed here `http://localhost:3000/user` needs to be modified like linked in

**To Reproduce**
Steps to reproduce the behaviour:

1. run the talawa admin
2. access the user login form and log in as a user
3. click on any organisation
4. access the issues

**Expected behaviour**
Something similar to linked-in, have attached the image below for reference.
![Screenshot 2023-12-15 at 3 18 54 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/98b8ba95-26ff-4f63-9747-8da3abcf6e31)

**Actual behaviour**
A basic post dialog
![Screenshot 2023-12-15 at 3 14 21 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/5048dfed-ca15-4b15-ac16-6dad24980931)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by chandel-aman** [comment]
@noman2002  Can i work on this issue?

**Comment by hharshas** [comment]
I want to work on this issue @Cioppolo14 @noman2002 , @chandel-aman is assigned today to 2 issues.

**Comment by chandel-aman** [comment]
@hharshas As per Palisadoes' policy, I can work on 2 issues at a time.

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by Cioppolo14** [comment]
@hharshas The best we can do as volunteers is to confirm that the person has less than 2 issues before assigning it.  We assign it to the person who asked first who has less than 2 issues. If the issue has already been assigned, please don't ask to be assigned.

**Comment by VaibhavTalkhande** [comment]
I would like to work on it?
