### ISSUE TITLE
Removing the right bar in user portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1199]
**Is your feature request related to a problem? Please describe.**
Removing the right bar (member and event shortcuts) in user portal and ensuring correct behavior of event and members in navbar when any organization is selected  

**screenshots**
![Screenshot 2023-12-15 at 3 32 57 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/79d405c2-5c58-419d-b2b6-ba90bde97203)

**Additional context**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by PriyeshPandey2000** [comment]
hello i want to dive deep in the codebase can you assign this to me so that i can understand the codebase even better @aashimawadhwa

**Comment by VaibhavTalkhande** [comment]
I would like to work on it

**Comment by adi790uu** [comment]
hey @aashimawadhwa do i need to write tests for ensuring proper behaviour?

**Comment by adi790uu** [comment]
@Cioppolo14 do i need to write tests for ensuring proper behaviour?

**Comment by adi790uu** [comment]
Hey @aashimawadhwa @Cioppolo14 do I need to write tests for checking behaviour?
