### ISSUE TITLE
Redesigning the user portal signup/registeration form 

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1200]
**Is your feature request related to a problem? Please describe.**
The form is not consistent as per the designs of talawa admin, the toggle password button does not works

**Describe the solution you'd like**
An implementation of login/signup form similar to talawa admin

**Additional context**
access the admin login and signup form here `http://localhost:3000/`
aceess the user login and signup form  here `http://localhost:3000/user`

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by adi790uu** [comment]
would like to solve this issue

**Comment by PriyeshPandey2000** [comment]
hello i really want to dive deep in issues please assign this to me so that i can contribute @aashimawadhwa

**Comment by Cioppolo14** [comment]
@adi790uu I just assigned you another item, so you now have two assigned issues. Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects.

**Comment by hharshas** [comment]
@Cioppolo14 similarily @PriyeshPandey2000 is assigned to 2 issues today, i would like to work on this.

**Comment by Harshsharmaa28** [comment]
please assign me this issue i also want to work on this

**Comment by Cioppolo14** [comment]
@hharshas @Harshsharmaa28 

If the issue has already been assigned, please don't ask to be assigned. Please do not repeat this type of request.

**Comment by VaibhavTalkhande** [comment]
I would like work on it assign me the issue

**Comment by palisadoes** [comment]
@PriyeshPandey2000

1. You were assigned this issue 9 days ago and there has been no pull request. 
2. This is a major issue to be resolved as it is blocking us creating other issues for others to pursue.

Do you have any updates on this? It's very important for our development road map

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no pull request

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by aarishshahmohsin** [comment]
please close this issue.
