### ISSUE TITLE
Implementing Calendar View in the user portal of talawa

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1202]
**Describe the bug**
In the user portal which can be accessed here `http://localhost:3000/user` needs to be implemented with a calendar view in the event screen.

**To Reproduce**

1. run the talawa admin
2. access the user login form and log in as a user
3. click on event tab on navbar
4. access the issues

**Expected behavior**
A calendar view similar to talawa-admin

**Actual behavior**
No calendar view

https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/2a66ef14-a83e-4273-a5c8-931c45c46a32

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by chandel-aman** [comment]
@noman2002 can i take this ?

**Comment by PriyeshPandey2000** [comment]
i want to really work on this ? can you assign this to me

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by VaibhavTalkhande** [comment]
I would like to work on this
