### ISSUE TITLE
Upgrading react-router-dom from v5.2.0 to v6.

### ISSUE THREAD

**Issue by git-init-priyanshu** [PalisadoesFoundation/talawa-admin#1210]
**Is your feature request related to a problem? Please describe.**
Right now the talawa uses old version of react-router-dom ( v5.2.0 ).

**Describe the solution you'd like**
I want react-router-dom to upgrade to v6 ( newer version ) and to use createBrowserRouter.

**Approach to be followed (optional)**
Following this document: https://reactrouter.com/en/main/upgrading/v5

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by git-init-priyanshu** [comment]
I would like to work on this issue.

**Comment by Cioppolo14** [comment]
@git-init-priyanshu Could you explain why you want to do this? 

@noman2002 @aashimawadhwa Could I have your opinion on this?

**Comment by git-init-priyanshu** [comment]
Right now react-router-dom works just fine and does not really need an update. I also want to know your thoughts on whether this is a valid issue or not.

**Comment by palisadoes** [comment]
We are focusing on upgrades that are related to GitHub dependabot security updates or those that are necessary to fix a bug or create a meaningful feature that greatly improved the user experience.

Thanks for considering this, but we have bigger priorities.

Closing
