### ISSUE TITLE
Bug Report: Delete sample org button is not working

### ISSUE THREAD

**Issue by kanhaiya04** [PalisadoesFoundation/talawa-admin#1217]
**Describe the bug**
Delete Sample org button is not working.

**To Reproduce**

1. Create a sample org.
2. Go to the setting page of the sample org.
3. Try to delete the sample org.
4. You will notice it will not work.

**Expected behavior**
The sample org should be delete by clicking on the delete button.

**Actual behavior**
The delete sample org button does not worked.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/e2111c7c-4338-4dce-b1d2-d69517e9d462

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
@palisadoes Please assign me this issue.

**Comment by yashmangal112** [comment]
@palisadoes please assign this issue to me. I know how to solve this bug.
