### ISSUE TITLE
A button without any functionality

### ISSUE THREAD

**Issue by Vaishali054** [PalisadoesFoundation/talawa-admin#1221]
**Describe the bug**
The User Details screen has a button named User Details without any functionality associated with it. 

**To Reproduce**

1.Login to the talawa-admin portal
2.Go to the User Details screen by clicking on your UserName in the left Drawer
3.Click on the User Details button, see that it doesnt has any functionality.

**Expected behavior**
To perform some functionality

**Actual behavior**
 It doesn't do anything

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/100770875/7f28a94a-2a07-4877-81da-a2b4c0197194)

**Additional details**
A approach might be to remove the button, multiple headings for same thing might not be a good user experience

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Vaishali054** [comment]
can you please assign it to me, if it is a valid issue?

**Comment by Cioppolo14** [comment]
@Vaishali054 I am assigning you the issue, but please work with @Kevoniat first to vet the issue and solution futher.

**Comment by Vaishali054** [comment]
I was not able to reach @Kevoniat . @aashimawadhwa  could you please take a look if possible ?

**Comment by Vaishali054** [comment]
@palisadoes can you please confirm if this is a valid issue?

**Comment by aashimawadhwa** [comment]
Yes you can start working on it @Vaishali054

**Comment by Vaishali054** [comment]
Thank you @aashimawadhwa !!
