### ISSUE TITLE
Upgrade deprecated `source-map-resolve` library

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1224]
**Describe the bug**
When the command `npm install --legacy-peer-deps` is run for the first time as part of the installation process, this error message is seen.

```
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated

```

**To Reproduce**
- See above

**Expected behavior**
1. No error message because the library has been updated, or suitably replaced, not because the error message has been suppressed.
1. All tests pass and are updated for the new library
1. If the package is no longer used, then it must be removed
1. No application functionality is affected

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
i want to work on this issue

**Comment by palisadoes** [comment]
@hharshas You have requested to be assigned to 10 issues in the space of 5 minutes. Everyone needs to get a chance to work on issues. Once you have been assigned two issues, the next person in line in the remaining 8 will be provided access. Please watch this video for guidance

- https://www.youtube.com/watch?v=3mjap16GYiY

Your actions are not in keeping with the spirit of the community. Please adjust your activities to be more collaborative.

@Cioppolo14 @noman2002 @Kevoniat please take note.

**Comment by palisadoes** [comment]
unassigning due to inactivity and no related PR

**Comment by Veer0x1** [comment]
Can I take up this issue?

**Comment by NayOoLwin5** [comment]
I would like to work on it. Can I be assigned to this issue?

**Comment by Cioppolo14** [comment]
@Veer0x1 @NayOoLwin5 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by aarishshahmohsin** [comment]
@Cioppolo14 

The package ```jest-enzyme``` was removed in the PR [#1501](https://github.com/PalisadoesFoundation/talawa-admin/pull/1501) and with that the error message also disappeared. So there is no need of a PR on this issue. 

The deprecated package that was causing the error message was ```jest-ezyme``` with version '7.1.2' due it being dependent on ```source-map-resolve```. This package is an addition on jest used for react testing but it is not supported for React 17 and hence the package ```enzyme-adapter-react-17``` is used. 

However, the use of an enzyme adapter is a work around and not a concrete solution because now react testing is done with [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/). Should I raise an issue for this?

**Comment by aarishshahmohsin** [comment]
@palisadoes is there any update?

**Comment by palisadoes** [comment]
OK. Open an issue for the best practice and remove all the unnecessary packages from the previous methodology.

Closing
