### ISSUE TITLE
Upgrade deprecated `sane` library

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1225]
**Describe the bug**
When the command `npm install --legacy-peer-deps` is run for the first time as part of the installation process, this error message is seen.

```
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added

```

**To Reproduce**
- See above

**Expected behavior**
1. No error message because the library has been updated, or suitably replaced, not because the error message has been suppressed.
1. All tests pass and are updated for the new library
1. If the package is no longer used, then it must be removed
1. No application functionality is affected

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
i want to work on this issue

**Comment by palisadoes** [comment]
@hharshas You have requested to be assigned to 10 issues in the space of 5 minutes. Everyone needs to get a chance to work on issues. Once you have been assigned two issues, the next person in line in the remaining 8 will be provided access. Please watch this video for guidance

- https://www.youtube.com/watch?v=3mjap16GYiY

Your actions are not in keeping with the spirit of the community. Please adjust your activities to be more collaborative.

@Cioppolo14 @noman2002 @Kevoniat please take note.

**Comment by duplixx** [comment]
@palisadoes can you assign me this !!
Thanks !!

**Comment by Cioppolo14** [comment]
@duplixx Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Shubh152** [comment]
Please assign this issue to me @Cioppolo14.

**Comment by ParishiB** [comment]
@palisadoes can u assign me this

**Comment by ParishiB** [comment]
Looked into issue , i think changing the enzyme with RTL would be helpful.Can i do that?

**Comment by ParishiB** [comment]
Any advice or any other method would be appreciated
Thanks and regards

**Comment by Cioppolo14** [comment]
@ParishiB If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.  This issue has been assigned and has an active PR.

**Comment by ParishiB** [comment]
ok sure
