### ISSUE TITLE
Upgrade deprecated `request-promise-native` library

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1226]
**Describe the bug**
When the command `npm install --legacy-peer-deps` is run for the first time as part of the installation process, this error message is seen.

```
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142

```

**To Reproduce**
- See above

**Expected behavior**
1. No error message because the library has been updated, or suitably replaced, not because the error message has been suppressed.
1. All tests pass and are updated for the new library
1. If the package is no longer used, then it must be removed
1. No application functionality is affected

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
i want to work on this issue

**Comment by palisadoes** [comment]
@hharshas You have requested to be assigned to 10 issues in the space of 5 minutes. Everyone needs to get a chance to work on issues. Once you have been assigned two issues, the next person in line in the remaining 8 will be provided access. Please watch this video for guidance

- https://www.youtube.com/watch?v=3mjap16GYiY

Your actions are not in keeping with the spirit of the community. Please adjust your activities to be more collaborative.

@Cioppolo14 @noman2002 @Kevoniat please take note.

**Comment by hharshas** [comment]
@palisadoes  would keep that in mind from now onwards

**Comment by sarthak17jain** [comment]
I would love to work on this

**Comment by Cioppolo14** [comment]
@sarthak17jain Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Cioppolo14** [comment]
@sarthak17jain Are you working on this?

**Comment by varunsh17** [comment]
Would like to work upon the issue.

**Comment by Cioppolo14** [comment]
Unassigning due to inactivity.

**Comment by varunsh17** [comment]
> Unassigning due to inactivity. 

I have started working on this

**Comment by varunsh17** [comment]
![Screenshot 2024-01-09 235149](https://github.com/PalisadoesFoundation/talawa-admin/assets/81704366/b67ec3b3-63ea-4ac0-8bcc-a0411bdd7d37)

These are the dependencies `request-promise-native` depends and are being used currently.
After uninstalling it, I see no difference (The talawa-admin localhost works fine).
I wanna ask **Why are we not removing this dependency ?**

**Comment by palisadoes** [comment]
Please read the issue's requirements

**Comment by varunsh17** [comment]
The Below mentioned lines indicate that request-promise-native library is still in use as it is indirectly use by other dependencies, our error is coming because of  this.

1. [Link1](https://github.com/PalisadoesFoundation/talawa-admin/blob/59dae2cbf463adab8fe637fd19ed8d66869de192/package-lock.json#L14219)
2. [Link2](https://github.com/PalisadoesFoundation/talawa-admin/blob/59dae2cbf463adab8fe637fd19ed8d66869de192/package-lock.json#L21346)
3. [Link3](https://github.com/PalisadoesFoundation/talawa-admin/blob/59dae2cbf463adab8fe637fd19ed8d66869de192/package-lock.json#L35947)
4. [Link4](https://github.com/PalisadoesFoundation/talawa-admin/blob/59dae2cbf463adab8fe637fd19ed8d66869de192/package-lock.json#L41101)

**Comment by varunsh17** [comment]
@palisadoes @Cioppolo14 
Should I consider those sub-dependencies too ? as I commented above that request-promise-native is still used by another packages internally..

**Comment by palisadoes** [comment]
Upgrade dependencies to the best of your ability by only editing the `package.json` file

**Comment by git-init-priyanshu** [comment]
I think we can close this issue now because the `request-promise-native` and `left-pad` libraries are both dependencies of the `jest-enzyme` library and my PR, #1501, removes the `jest-enzyme` library, thereby resolving both warnings.
