### ISSUE TITLE
Upgrade deprecated `left-pad` library

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1227]
**Describe the bug**
When the command `npm install --legacy-peer-deps` is run for the first time as part of the installation process, this error message is seen.

```
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

```

**To Reproduce**
- See above

**Expected behavior**
1. No error message because the library has been updated, or suitably replaced, not because the error message has been suppressed.
1. All tests pass and are updated for the new library
1. If the package is no longer used, then it must be removed
1. No application functionality is affected

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
i want to work on this issue

**Comment by palisadoes** [comment]
@hharshas You have requested to be assigned to 10 issues in the space of 5 minutes. Everyone needs to get a chance to work on issues. Once you have been assigned two issues, the next person in line in the remaining 8 will be provided access. Please watch this video for guidance

- https://www.youtube.com/watch?v=3mjap16GYiY

Your actions are not in keeping with the spirit of the community. Please adjust your activities to be more collaborative.

@Cioppolo14 @noman2002 @Kevoniat please take note.

**Comment by VaibhavTalkhande** [comment]
Can I work on it

**Comment by sarthak17jain** [comment]
I would love to work on this

**Comment by palisadoes** [comment]
@sarthak17jain You already have 2 issues assigned

**Comment by antriksh-9** [comment]
Hey @palisadoes I would like to work on this issue. 
Please assign it to me.

**Comment by antriksh-9** [comment]
Hey @palisadoes I am getting difficulty in solving the issue, I mean how I need to upgrade it or replace it.
Can you guide me a little bit?

**Comment by palisadoes** [comment]
It should either be listed in this file or a dependency of one of the packages listed there.

- https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/package.json

**Comment by antriksh-9** [comment]
Hey @palisadoes I got a package that is dependent on left-pad, and I thought of upgrading that package but I am getting some errors. Can you guide me here?

![Screenshot 2024-01-04 231739](https://github.com/PalisadoesFoundation/talawa-admin/assets/132576984/b2e85acd-f1d1-4bf7-adb4-301a5971987b)

**Comment by palisadoes** [comment]
Please read the instructions. I am not necessary in the discussion, however your PR reviewers will be. Please work with them on a suitable resolution.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/25130200-9eb1-48c6-bfd8-88bac2fe2065)

**Comment by antriksh-9** [comment]
Hey @noman2002 can you help me here?

**Comment by palisadoes** [comment]
unassigning due to inactivity

**Comment by antriksh-9** [comment]
Hey @palisadoes I am working on this issue but not getting any approach to solve this..
I tried to raise the problem on slack and tagged the reviewers but got no response.
Also no memebers were able to help..

**Comment by palisadoes** [comment]
1. OK. Let someone else give it a try.
2. There will be other issues coming up

**Comment by git-init-priyanshu** [comment]
I would like to work on this issue.

**Comment by git-init-priyanshu** [comment]
The issue arises because of the 'jest-enzyme' library. However, there is no mention or use of this library in the entire codebase. So, is it okay to remove this library?

**Comment by palisadoes** [comment]
Yes

**Comment by git-init-priyanshu** [comment]
ok, I will make a PR now.

**Comment by palisadoes** [comment]
Why is the package in `package-lock.json`? Why does it consistently get reinserted?
