### ISSUE TITLE
Upgrade deprecated `npmcli/move-file` library

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1229]
**Describe the bug**
When the command `npm install --legacy-peer-deps` is run for the first time as part of the installation process, this error message is seen.

```
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

```

**To Reproduce**
- See above

**Expected behavior**
1. No error message because the library has been updated, or suitably replaced, not because the error message has been suppressed.
1. All tests pass and are updated for the new library
1. No application functionality is affected

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
would like to work on this issue

**Comment by palisadoes** [comment]
@hharshas You have requested to be assigned to 10 issues in the space of 5 minutes. Everyone needs to get a chance to work on issues. Once you have been assigned two issues, the next person in line in the remaining 8 will be provided access. Please watch this video for guidance

- https://www.youtube.com/watch?v=3mjap16GYiY

Your actions are not in keeping with the spirit of the community. Please adjust your activities to be more collaborative.

@Cioppolo14 @noman2002 @Kevoniat please take note.

**Comment by Veer0x1** [comment]
would like to work on this

**Comment by Veer0x1** [comment]
@palisadoes @Cioppolo14 We can't fix this deprecated warning of `npmcli/move-file` coz its peer dependency of 
`node-sass` which has latest version 9.0.0 which we are using. 
<img width="540" alt="Screenshot 2023-12-25 at 12 56 40 AM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/96714915/33354bcd-4a70-4b28-8d8f-c7558c2e849e">
