### ISSUE TITLE
Upgrade deprecated `workbox-cacheable-response` and `workbox-background-sync` libraries

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1230]
**Describe the bug**
When the command `npm install --legacy-peer-deps` is run for the first time as part of the installation process, this error message is seen.

```
npm WARN deprecated workbox-cacheable-response@6.6.0: workbox-background-sync@6.6.0

```

**To Reproduce**
- See above

**Expected behavior**
1. No error message because the library has been updated, or suitably replaced, not because the error message has been suppressed.
1. All tests pass and are updated for the new library
1. No application functionality is affected

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
would like to work on this issue

**Comment by palisadoes** [comment]
@hharshas You have requested to be assigned to 10 issues in the space of 5 minutes. Everyone needs to get a chance to work on issues. Once you have been assigned two issues, the next person in line in the remaining 8 will be provided access. Please watch this video for guidance

- https://www.youtube.com/watch?v=3mjap16GYiY

Your actions are not in keeping with the spirit of the community. Please adjust your activities to be more collaborative.

@Cioppolo14 @noman2002 @Kevoniat please take note.

**Comment by aialok** [comment]
I would love to work on this issue : )

**Comment by aialok** [comment]
Hey, I've been working on this issue and  research about it. Essentially, `workbox-cacheable-response@6.6.0` and `workbox-background-sync@6.6.0` are transitive dependencies. If we attempt to fix this issue directly or  by using `resolutions`, it will introduce breaking changes, as I've already experienced. In this case, to update these packages, we would need to upgrade the higher-level packages, such as `react-scripts`. However, `react-scripts` is already on its latest version.

I've also discovered that this deprecation warning has no impact on production. These warnings are a result of npm. 
#### Check out this thread for more information.

- https://github.com/facebook/create-react-app/issues/11174#issuecomment-873190357

- Here is dependency tree of the above both packages.

![workbox](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/0ccecc5d-eb56-46fc-9029-600fb5626532)


![workbox_response](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/0b078b7d-37be-44b3-ad7d-a3cb2f236d89)

Please, do assist me. If you have any Idea how to fix this.
- Thank you : )

**Comment by aialok** [comment]
@palisadoes , Please have a look.

**Comment by palisadoes** [comment]
1. In that case we'll need to close this issue.
2. Thank you for investigating
