### ISSUE TITLE
Upgrade deprecated `urix` library

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1231]
**Describe the bug**
When the command `npm install --legacy-peer-deps` is run for the first time as part of the installation process, this error message is seen.

```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

```

**To Reproduce**
- See above

**Expected behavior**
1. No error message because the library has been updated, or suitably replaced, not because the error message has been suppressed.
1. All tests pass and are updated for the new library
1. No application functionality is affected

**Actual behavior**
- See above

**Screenshots**
- N/A

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
would like to work on this issue

**Comment by palisadoes** [comment]
@hharshas You have requested to be assigned to 10 issues in the space of 5 minutes. Everyone needs to get a chance to work on issues. Once you have been assigned two issues, the next person in line in the remaining 8 will be provided access. Please watch this video for guidance

- https://www.youtube.com/watch?v=3mjap16GYiY

Your actions are not in keeping with the spirit of the community. Please adjust your activities to be more collaborative.

@Cioppolo14 @noman2002 @Kevoniat please take note.

**Comment by Pranavx1** [comment]
Can i work on this?

**Comment by Pranavx1** [comment]
The issue needs to he closed as urix is dependency of jest-enzyme which is already uptodate
