### ISSUE TITLE
Create a Setup Script for the `.env` configuration file

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1233]
**Is your feature request related to a problem? Please describe.**

1. The current `INSTALLATION.md` file describes how to manually setup the `.env` file
    1. https://github.com/PalisadoesFoundation/talawa-admin/blob/main/INSTALLATION.md#creating-env-file 
1. We need a setup script similar to that used in Talawa API that automates the population of the `.env` file

**Describe the solution you'd like**
1. We need a setup script similar to that used in Talawa API that automates the population of the `.env` file
1. It should validate the parameters entered and that any services related to the parameters are working correctly
1. The `INSTALLATION.md` file must be updated with the new procedure
1. The table of contents must be regenerated with a link to the new instructions visible

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
would like to work on this issue

**Comment by palisadoes** [comment]
@hharshas You have requested to be assigned to 10 issues in the space of 5 minutes. Everyone needs to get a chance to work on issues. Once you have been assigned two issues, the next person in line in the remaining 8 will be provided access. Please watch this video for guidance

- https://www.youtube.com/watch?v=3mjap16GYiY

Your actions are not in keeping with the spirit of the community. Please adjust your activities to be more collaborative.

@Cioppolo14 @noman2002 @Kevoniat please take note.

**Comment by disha1202** [comment]
Hi 
Can I work on this?

**Comment by palisadoes** [comment]
unassigning due to inactivity and no related PR

**Comment by disha1202** [comment]
Hi 
Can I get assigned again.
I'll submit a PR soon.
