### ISSUE TITLE
The `INSTALLATION.md` file needs a newly generated table of contents

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1234]
**Is your feature request related to a problem? Please describe.**
1. There are many missing table of contents (TOC) entries in the INSTALLATION.md file.
1. Many of the existing TOC entries are under an inappropriate parent heading

This increases the risk of installation instructions being overlooked.

**Describe the solution you'd like**
1. Add the missing table of contents (TOC) entries in the INSTALLATION.md file.
1. Adjust the resulting TOC entries under the appropriate parent headings
1. Ideally, the auto-generation of the TOC should be automatic as part of the `git` process

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- Consider using a markdown TOC autogenerator

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
@palisadoes  I would love to work on this issue : )

**Comment by Cioppolo14** [comment]
@aialok Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by aialok** [comment]
I am already done with my one of the issue just pull request need to merge : )

**Comment by aialok** [comment]
- Hey @Cioppolo14 . I have implemented this feature in my own repository, and it's working fine. However, I still have some things to ask about:

   - **Considering a New npm Package:**
   I'm thinking about adding a new npm package to help automatically create a table of contents. Ishould I go for it ?

   - **About `markdown-toc` npm package:**
   I'm using `markdown-toc`, but some of its depedency has not been updated

      ![Screenshot from 2023-12-25 00-45-23](https://github.com/PalisadoesFoundation/talawa-admin/assets/66772290/f129bb9d-4be2-46c1-912b-9636f67c4a24)

    -    **Ways to Automate Table of Contents:**
      I'm looking at two ways to automatically generate a table of contents:
        -  Adding a script to GitHub Actions workflows.
        -  Setting up a husky pre-commit hook .

**Comment by palisadoes** [comment]
Yes use the markdown package. Automation is best. It's a non-critical package, so we can take a chance on updates

**Comment by aialok** [comment]
> Yes use the markdown package. Automation is best. It's a non-critical package, so we can take a chance on updates 

Okay alright, I am going with husky pre commit for auto generation of toc on commit.
