### ISSUE TITLE
Deprecation warnings on starting - package  upgrade required

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1235]
**Describe the bug**
When the app starts, this error message flashes across the screen. 

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/91daa06d-5074-44a7-af4d-de11a81af394)

The deprecation needs to be resolved in the app

**To Reproduce**
1. Start the app, the message flashes on the screen
1. Use a screen capture app to capture the result in video

**Expected behavior**

1. No message flashes on the screen because the package is upgraded, not because the error message has been suppressed
2. All other functionality in the app is maintained

**Actual behavior**
- See above

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/8aef9238-3720-46ff-bcb3-4b0721e61c39)

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Tarunmeena0901** [comment]
Hey , @palisadoes @noman2002 i will like to solve this issue .
Thankssss

**Comment by Tarunmeena0901** [comment]
This is a problem inside `node_module` in the `react-scripts/config/webpackDevServer.config` here is a fix i any one want to fix it locally [local fix](https://github.com/PalisadoesFoundation/talawa-admin/pull/1289) but if we want to bring that fix in production we cannot do it directly without using a some dependency like react-rewired-app or CRACO just like i used in this PR [PR for issue#1236](https://github.com/PalisadoesFoundation/talawa-admin/pull/1289) please review so i will proceed accordingly

**Comment by Tarunmeena0901** [comment]
https://github.com/facebook/create-react-app/issues/11860 u can see it is an open issue in Create-react-app so it depends on them when they will fix this

**Comment by NamitBhutani** [comment]
Hi! I would like to try solving this issue! :D
