### ISSUE TITLE
Non standard Talawa Logo is used on the login screen and all other screens

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1237]
**Describe the bug**
The logo icon is not the official icon

**To Reproduce**

1. Access login screen
2. Access any screen after login

**Expected behavior**
1. Use suitable icons found here:
    1. https://docs.talawa.io/docs/design/branding
1. Replace the icon currently used in this repo with one from the source above

**Actual behavior**
- See screenshots

**Screenshots**
1. Here
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/95dbeb9d-d95e-4f77-aeed-b4cdcee7b4be)
1. Here too
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/aaada580-8c38-458d-a0f6-c9eb962d345e)

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by duplixx** [comment]
hey @palisadoes can you assign me this one !!

**Comment by NRaghav05** [comment]
I want to work on this. please assign me this issue.

**Comment by ibishal** [comment]
@palisadoes can i work on it

**Comment by KrishavRajSingh** [comment]
I would like to work on this issue

**Comment by rishav-jha-mech** [comment]
@ibishal any ETA ?

**Comment by aialok** [comment]
Can I work on this issue ?

**Comment by rishav-jha-mech** [comment]
@SwetanshuSingh you can now start your work on this issue

**Comment by SwetanshuSingh** [comment]
Sure @rishav-jha-mech

**Comment by SwetanshuSingh** [comment]
@rishav-jha-mech I went through the codebase and talawa-docs and found that the current logo is an svg and in the official docs the logo is in the png format. So I have to update the logo using the png format if I am not wrong?

**Comment by SwetanshuSingh** [comment]
Hello @KrishavRajSingh , I am working on this issue and waiting for the confirmation for proceeding ahead with my approach

**Comment by palisadoes** [comment]
Unassigning due to inactivity. Closing as it's fixed
