### ISSUE TITLE
The organization images are not centered in their tiles

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1238]
**Is your feature request related to a problem? Please describe.**
1. The organization images are not:
    1. centered in their tiles
    1. appropriately lined up with the `manage` button

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/73bf1982-1b60-43fa-a72a-b9bec5290ca5)

**Describe the solution you'd like**
Adjust the positioning of either the organization image and/or the `manage` button to have a more pleasing result

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by pateldivyesh1323** [comment]
@palisadoes I cannot reproduce this behaviour, the images are already centered.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/6bf8bfc9-09d5-4be6-a0c6-b842e276fe78)

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/22383d3b-5dac-4af0-99f6-ebcfaa97c718)

**Comment by palisadoes** [comment]
I'm seeing it in Firefox. Chrome and Opera are OK

**Comment by pateldivyesh1323** [comment]
@palisadoes It is also aligned in firefox.
@noman2002 Can you confirm this?

**Comment by palisadoes** [comment]
OK, I'll close this. It could be related to my installed browser plugins
