### ISSUE TITLE
Calendar Times Must be Dropdown or Clock Motif

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1239]
**Is your feature request related to a problem? Please describe.**

1. The user has to enter the start and stop times for an event, while the dates are entered using the mouse
2. This is an inconsistent user experience

**Describe the solution you'd like**
1. Create a suitable interface
1. The solution must accommodate the mandatory use of seconds in the calendar timing
1. Work with @aashimawadhwa or @rishav-jha-mech for the desired interface selection
1. 100% test code coverage for the solution

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**

1. Talawa image
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/eb19d9f8-7e2a-4960-91e6-2479a4a2fdbf)
1. Google image
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/b7e61e5f-c383-4443-8574-50be313d1c2f)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by VaibhavTalkhande** [comment]
Hi
Can I work on this issue

**Comment by VaibhavTalkhande** [comment]
![Screenshot from 2023-12-23 16-02-55](https://github.com/PalisadoesFoundation/talawa-admin/assets/49303222/fcd33f42-c4ba-43b5-9172-2c3860e2ecc0)
this is how the drop down should look? @aashimawadhwa @rishav-jha-mech

**Comment by VaibhavTalkhande** [comment]
# Woki on it

**Comment by VaibhavTalkhande** [comment]
You can assign it to someone else I am not able to integrate the custom components to form causing issue

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by rishav-jha-mech** [comment]
@aarishshahmohsin please refer to the conversation from this PR

https://github.com/PalisadoesFoundation/talawa-admin/pull/1284

And let us know your approach

**Comment by aarishshahmohsin** [comment]
I think these two would be apt. I prefer (i) more.

(i) 
![1](https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/203fd7ba-5306-4d79-9697-feba1d326e81)

(ii)
![2](https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/e3ac274e-4f1f-4738-9239-58ef103fa318)

**Comment by rishav-jha-mech** [comment]
@aarishshahmohsin https://github.com/PalisadoesFoundation/talawa-admin/pull/1284#issuecomment-1869971257

Follow this comment, and let us know your approach

**Comment by rishav-jha-mech** [comment]
@aarishshahmohsin you don't have to go and comment over closed PRs, we can have the discussion right here

I have explained in detail what needs to be done, just let me know how you are planning to implement it

**Comment by shreyashidabral** [comment]
Hey can I work on this issue, I see that we have to manually enter the time and it does not check if startTime < endTime. 
Since we already use mui as a dependency we can use their time picker. 
And we can make custom components out of it so that it can be used at different places in the project. Please let me know if this works

**Comment by aarishshahmohsin** [comment]
@rishav-jha-mech 
The approach is to use the time picker component of Material UI. 
![comp](https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/1646fd8f-5cfa-4e97-852f-eda7d69bfe65)
and disable the component when all day is true. for preventing the user from selecting a past date, a toast can be given to select a valid date. 

is there any possiblity of using the custom component, because it would be styled easily and can show only the possible times instead of the toast method.

**Comment by Tarunmeena0901** [comment]
I think we can use MUI components and style them as we want have a look @aarishshahmohsin 
[Customizing base ui component](https://mui.com/base-ui/getting-started/customization/)
here not much is needed to make it look similar to other element so may be we can just do this

**Comment by aarishshahmohsin** [comment]
> I think we can use MUI components and style them as we want have a look @aarishshahmohsin [Customizing base ui component](https://mui.com/base-ui/getting-started/customization/) here not much is needed to make it look similar to other element so may be we can just do this

Sure, this can be done.

**Comment by aarishshahmohsin** [comment]
@rishav-jha-mech Is there any update?

**Comment by Cioppolo14** [comment]
@rishav-jha-mech Are you comfortable with assigning @aarishshahmohsin after reviewing their approach?

**Comment by Cioppolo14** [comment]
@NamitBhutani Please read above.  Before getting this assigned, @rishav-jha-mech would like to know the approach you are going to take.  Before asking to work on an issue, please read the issue and discussion above to gather as much information as possible.  If an issue is already assigned, please do not ask to be assigned, especially if the assignee has submitted an open PR.

**Comment by aarishshahmohsin** [comment]
Is there any update?

**Comment by rishav-jha-mech** [comment]
@aarishshahmohsin please ask me if you are blocked somewhere

**Comment by aarishshahmohsin** [comment]
> @aarishshahmohsin please ask me if you are blocked somewhere 

What do you mean by blocked? I don't know.

**Comment by Cioppolo14** [comment]
@aarishshahmohsin I think @rishav-jha-mech I meant if you get stuck.

**Comment by aarishshahmohsin** [comment]
> @aarishshahmohsin please ask me if you are blocked somewhere

sure

**Comment by aarishshahmohsin** [comment]
Please close this issue.
