### ISSUE TITLE
Inconsistent use of icons to minimize the left column navbar

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1240]
**Is your feature request related to a problem? Please describe.**
The `event dashboard `page does not use the same minimization method as the other screens in the app

**Describe the solution you'd like**
Use the same method used in the main organization pages

**Describe alternatives you've considered**
- None

**Approach to be followed (optional)**
Consider the approach used in this issue
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1159

**Additional context**
1. Calendar Screen
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/6136d133-b173-4261-abf5-5ea7e228c362)
1. Event dashboard page
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/4757b9e0-d585-498c-8e9c-f8e96b34f06e)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
would like to work on this issue removed from another one

**Comment by palisadoes** [comment]
1. You have made it very difficult to track who should be assigned issues. We now have to manually go through dozens of issues to see whether or not someone wanted to work on an issue because your profile appears in the searches, whether or not you have deleted the comment because you were referenced in other comments.
2. I strongly advise you not to continue with this practice. You are creating unnecessary hardship for our volunteers.

**Comment by palisadoes** [comment]
unassigning due to inactivity

**Comment by hubsMIT1** [comment]
Hi @palisadoes, can i work on this issue?

**Comment by hharshas** [comment]
@palisadoes  I am working on this issue and will make PR tommorow or day after tomorrow.  Please reassign me.

**Comment by akhilender-bongirwar** [comment]
@hharshas, have you completed working on this issue.

**Comment by hharshas** [comment]
@palisadoes I will not be able to pr for another one week, so yeah @akhilender-bongirwar go for it.

**Comment by akhilender-bongirwar** [comment]
@Cioppolo14, please assign this issue to me.
