### ISSUE TITLE
The `INSTALLATION.md` file doesn't tell you to install typescript

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1243]
**Is your feature request related to a problem? Please describe.**
1. The `INSTALLATION.md` file doesn't tell you how to install typescript
1. This is an obvious omission and must be fixed

**Describe the solution you'd like**
1. Update the `INSTALLATION.md` file to explain how to install typescript in the correct order after installing `npm`
2. Make this a separate section in the procedure
3. Ensure that the table of contents is correctly updated

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by MahendraDani** [comment]
I would like to work on this issue

**Comment by MahendraDani** [comment]
@Cioppolo14 Would you please close this issue as completed via https://github.com/PalisadoesFoundation/talawa-admin/pull/1251
