### ISSUE TITLE
Console logging shows `{}` values where variables or nothing should appear

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1245]
**Describe the bug**

The console logging shows `{}` values where variables or nothing should appear

**To Reproduce**

1. Start the Admin app
2. The `{}` entries are visible in the console logs

**Expected behavior**
- The  `{}` values should be populated by variables or removed if adding variables has no use case

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/03769c9e-cee5-4ed8-814d-c965d749e9b4)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by RAGHAV-N5** [comment]
I want to work on this issue. Please assign this to me.

**Comment by monkCommits** [comment]
Is this error appearing in the talawa-api console?

**Comment by RAGHAV-N5** [comment]
Yes, it appears on the talawa-api console.

**Comment by RAGHAV-N5** [comment]
@palisadoes 

I have resolved this issue locally. 
![Screenshot 2023-12-23 111709](https://github.com/PalisadoesFoundation/talawa-admin/assets/135726978/a425e28b-3c55-4944-98f1-160eaab41fa1)
Since this issue is appearing on the console of talawa-api, how should I proceed with pull request?

**Comment by palisadoes** [comment]
When you are confident that you have completed the issue then open a PR. There is no need for approvals to do that

**Comment by RAGHAV-N5** [comment]
@palisadoes
okay. since it belongs to talawa-api, should I open this PR in talawa-api repository?

**Comment by palisadoes** [comment]
> @palisadoes okay. Since it belongs to talawa-api, should I open this PR in talawa-api repository?

Ask to be assigned to this issue
- https://github.com/PalisadoesFoundation/talawa-api/issues/1549

I'll close this one
