### ISSUE TITLE
App must run without using `npm install --legacy-peer-deps`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1246]
**Is your feature request related to a problem? Please describe.**

1. The app depends on legacy dependencies
1. The app must be upgraded to not use `--legacy-peer-deps`

**Describe the solution you'd like**
1. Upgrade app packages to not require the `--legacy-peer-deps`  qualifier when running `npm install`
1. Update the INSTALLATION.md file with the new installation process just using `npm install`
1. The  `npm install` must not redirect to `npm install --legacy-peer-deps` in any hidden way. 
1. `npm install --legacy-peer-deps` must not be invoked in any way behind the scenes to install the latest required packages
1. All existing tests must pass
1. No functionality must be removed

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by git-init-priyanshu** [comment]
I would like to work on this issue.

**Comment by monkCommits** [comment]
Hey can I work on this issue please

**Comment by dhiraj0911** [comment]
Hey I'd like to work on this issue too

**Comment by git-init-priyanshu** [comment]
Hey @palisadoes, I have fixed the issue by uninstalling the package `enzyme-adapter-react-16` and using `@wojtekmaj/enzyme-adapter-react-17` (which was already installed and correctly used in place of the previously mentioned package). I am no longer getting errors with peer dependency, but I am receiving several warnings. Should I also resolve those warnings?
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/9af656ee-eb9c-4d39-aff7-81737d0796b7)
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/7534d6c9-45a7-4442-89d2-f264399c44ed)

**Comment by palisadoes** [comment]
Yes. There should be no warnings. We should not be using deprecated or outdated packages. Open a PR when done

**Comment by palisadoes** [comment]
Also, determine the latest version of node that the app will work with and add it to the INSTALLATION.md file under the node installation section.

We need to state what our recommended version of node should be

**Comment by git-init-priyanshu** [comment]
Got it
