### ISSUE TITLE
Remove all unused packages from `package.json`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1254]
**Is your feature request related to a problem? Please describe.**

1. We have implemented dependabot alerts to let us know when we have outdated packages
2. We have noticed in the past that in some cases the packages listed in `package.json` are no longer being used

**Describe the solution you'd like**
1. Remove all references to unused packages from `package.json`
2. Generate `package-lock.json` appropriately

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Veer0x1** [comment]
I would like to work on this.

**Comment by Ritu84** [comment]
I have got a better approach to fix this issue. I would like to work on this issue. pls assign this to me..

**Comment by ManasUpadhyay13** [comment]
I would like to work on this issue
