### ISSUE TITLE
There must be margin between the calander header and the add even for the better interface.

### ISSUE THREAD

**Issue by gauravsingh94** [PalisadoesFoundation/talawa-admin#1255]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

In the event section of the website there must be margin between the calander header and the add even for the better interface.

**Describe the solution you'd like**
we have to add the margin top in order to make it correct.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/307388d0-cc31-4e44-91a5-388d0ac7b44f)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
This issue has been fixed in develop. Closing. 
Please refer to the develop branch when making changes.
