### ISSUE TITLE
Messaging when no posts are found isn't in keeping with the design

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1259]
**Is your feature request related to a problem? Please describe.**
- Messaging when no posts are found isn't in keeping with the design `Post Not Found!`

**Describe the solution you'd like**
- Messaging when no posts are found must be in keeping with the design

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- Use a text size and positioning within the box that is in keeping with the design of the page

**Additional context**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/b4d3750e-091e-4339-8d0b-3d62ecaace2d)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
I have already assigned two issues, but I have submitted a pull request that needs to be reviewed. If I am still allowed to get assigned, please do assign.

**Comment by gauravsingh94** [comment]
Please assign this issue to me i have no issue assign.

**Comment by gauravsingh94** [comment]
Please close this issue it fixed.
