### ISSUE TITLE
Image is not visible in posts - Fresh database

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1260]
**Describe the bug**
- First post of database with image isn't displayed

**To Reproduce**

1. Fresh database with sample data
2. Add post
3. Attempt to upload a PDF. You get an error as expected
4. Upload a JPG. 
5. There is no reported error, but Image doesn't appear

**Expected behavior**
- Post images must be visible

**Actual behavior**
- See above and screenshots

**Screenshots**
1. No image seen
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/bc18be12-57e1-489b-9af5-38977d35c22a)
1. Image dimensions and size
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/66b61674-d749-4e6f-9e32-383be776ebd3)

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
hey @palisadoes ,i have previously worked on this issue can you assign me this issue!!

**Comment by duplixx** [comment]
Hi @palisadoes, I am trying to replicate the issue using the above-given steps, but the issue doesn't appear on my end. I have attached a video for better understanding. If you can point out which step I am doing wrong, it will be really helpful
https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/a24e047f-d2db-45e1-9c82-6e3f3a80350f

**Comment by palisadoes** [comment]
- This must have been fixed after I created the issue. This can be closed

- Why are you getting the red error messages? How can that be fixed?

**Comment by duplixx** [comment]
Hi @palisadoes, it looks like the errors I'm encountering stem from outdated packages that we're currently using.

**Comment by palisadoes** [comment]
Would that be fixed by this issue?
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1274
