### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by pankaj-2503** [PalisadoesFoundation/talawa-admin#1263]
**Is your feature request related to a problem? Please describe.**
Talawa website is not completely mobile responsive . What i see's is that the image used is cut off when using website in mobile, for better understanding see the image below .

**Describe the solution you'd like**
There should be gap between image and left border . It can be improved by adding some css .

**Additional context**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90036864/e1a1701f-70ef-4dff-910d-7648c479c545)

**Comment by Cioppolo14** [comment]
@pankaj-2503  Did you want to work on it?

**Comment by pankaj-2503** [comment]
Yes

**Comment by pankaj-2503** [comment]
Why i am not able to signup when I have setup this project locally. 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90036864/a6194a2c-eadc-4b25-829f-6e89c6b0b8ba)

**Comment by hubsMIT1** [comment]
Hi, @Cioppolo14 can i work on this issue?

**Comment by palisadoes** [comment]
Closing.

1. This issue is related to the Talawa-Docs repository.
2. We are not accepting any design issues related to that repo or the resulting web pages.
