### ISSUE TITLE
Profile Picture is not rendering on the Event Dashboard page.

### ISSUE THREAD

**Issue by AmitSharma512** [PalisadoesFoundation/talawa-admin#1267]
**Describe the bug**
Profile Picture is not rendering on the Event Dashboard page.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create an event.
2. Now click on Show Event Dashboard.
3. Now, you can see that the profile picture is not visible in the left drawer.

**Expected behavior**
The Profile Picture should be visible on the events dashboard page like all other pages.

**Actual behavior**
Profile Picture is not rendering.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/4a026e5e-d553-41be-be5a-7c0446b443ce)

**Additional details**
I would like to work on this.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@AmitSharma512  I appreciate you submitting issues you notice.  I'm not sure if this was something you'd like to work on. If so, you currently have two issues. 

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by AmitSharma512** [comment]
@Cioppolo14 PR for both the issues has been made and are under review

**Comment by Cioppolo14** [comment]
@AmitSharma512 I understand, it is too much on the volunteers to track all the moving PRs & issues without this rule.  As soon as one of your PRs is closed, and thus an issue is also closed, I can assign you another issue.

**Comment by AmitSharma512** [comment]
@Cioppolo14 some tests are failing which are not getting solved on my previous PR , that's why I am working on new issues.

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by palisadoes** [comment]
> @Cioppolo14 some tests are failing which are not getting solved on my previous PR , that's why I am working on new issues.

If you are having difficulties, please ask for help in Slack. If they are not solvable, then close the PR and unassign yourself from the issue so that someone else can get a chance.

**Comment by Cioppolo14** [comment]
@aarishshahmohsin Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by AdityaRaimec22** [comment]
@palisadoes @Cioppolo14 can I get assigend to this issue.

**Comment by AdityaRaimec22** [comment]
@palisadoes can you please tell me why I am getting this error. "Error occured while loading the organisation"

<img width="960" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/118007662/51f4eb5d-8c9f-4043-b03e-78eb0124ddb0">

**Comment by Shubh152** [comment]
Please assign this issue to me @Cioppolo14

**Comment by 1010varun** [comment]
Hey @palisadoes @Cioppolo14,
I have made the changes can you please assign this issue to me.

**Comment by Cioppolo14** [comment]
@Shubh152  You now have two assignments so I am going assign @AmitSharma512

**Comment by AmitSharma512** [comment]
@Cioppolo14 I am not assigned yet.

**Comment by rishav-jha-mech** [comment]
@AmitSharma512 assigned to you
