### ISSUE TITLE
Change of hamburger icon to toggle left drawer for events dashboard.

### ISSUE THREAD

**Issue by AmitSharma512** [PalisadoesFoundation/talawa-admin#1269]
**Describe the bug**
The current hamburger icon to toggle the left drawer for the events dashboard is different from the toggle icon that is used on the main dashboard.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create an event.
2. Click on Show Event Dashboard.
3. Now, you can see that the toggle icon is different.

**Expected behaviour**
The toggle icon and its functioning should match the main dashboard.

**Actual behaviour**
The current hamburger icon to toggle the left drawer for the events dashboard is different from the toggle icon that is used on the main dashboard.

**Screenshots**
On the event dashboard : 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/1df3e3bb-9780-4316-83be-a6061464d185)

On the main dashboard :
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/ea7cd7ee-3b91-494c-a28b-d9493eaca18a)

**Additional details**
I would like to work on this.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@AmitSharma512 

We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens. @rishav-jha-mech is leading this process for the Talawa Admin project
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

**Comment by AmitSharma512** [comment]
@Cioppolo14 there is a PR made for changing the toggle left drawer a few days ago, and this issue is that the event dashboard does not has the changed toggle left drawer button, which is now the main dashboard toggle button.

**Comment by Cioppolo14** [comment]
@AmitSharma512 ok, I will reopen.

**Comment by AmitSharma512** [comment]
@Cioppolo14, now, can I be assigned the task, as both my PRs are closed, and currently, I am not assigned to any task.

**Comment by rishav-jha-mech** [comment]
@AmitSharma512 this single change for this screen will not be considered for a PR, creating the entire UI for the Event Dashboard will include this in accordance to new design. I am closing this issue now.
