### ISSUE TITLE
Apply Linting Only to Files Updated in `git`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1270]
We need the ability to selectively adjust our linting rules so that they are eventually applied to our entire code base.

1. Linting rules are managed by the `.eslintrc.json` file.
1. They are applied to the entire code base at once.
1. If we change a rule from `warn` to `error` then every file in the code base will be checked and we have frequently seen our tests fail for dozens of files in hundreds of lines of code.

This is not acceptable.

We have been trying to more strictly lint the entire code base manually, but it has been very slow.

## At the user CLI
We need a way to edit `.eslintrc.json` with increasingly stricter linting rules in such a way that the tests are only applied to the changed files with every `git commit` and `git push` command. 

These `git` commands must fail if the linting fails.

## With Every Pull Request

We recently merged a Talawa-API pull request that checks each submitted file for linting compliance. This can be used as an example of how to run the test against individual files.

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1242

You must make sure that this functionality applied for all PRs for this repository whenever the  `.eslintrc.json` file is updated

## Other

1. There may be ways to achieve the CLI goals by updating our existing Git Hooks
1. Your solution should preferably work within coding environments such as VScode
1. Please work with @anwersayeed and @tasneemkoushar on this issue
1. Related issues:
    - https://github.com/PalisadoesFoundation/talawa-api/issues/1548

## Screenshots

When complete, you should be able to convert all these  `.eslintrc.json` file lines containing `warn` to `error` and the tests will only be applied to the changed files in `git`

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/40879824-664c-4d6f-9906-7372cf80f848)

**Comment by Shubh152** [comment]
Please assign this issue to me

**Comment by palisadoes** [comment]
@Nitya-Pasrija Please be aware of this issue

**Comment by Nitya-Pasrija** [comment]
I'll review it asap

**Comment by Veer0x1** [comment]
@Cioppolo14 I would like to work on this issue.

**Comment by Cioppolo14** [comment]
@Veer0x1 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by palisadoes** [comment]
@Shubh152 

1. You didn't update the `.eslintrc.json` file with all the options above. The image below is what you have implemented in the PR
2. Please open another PR to finish the job

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/86bb0b1f-2593-4f86-a93a-e3fb5f6b2127)
