### ISSUE TITLE
Update Registrations with a `User Type` - Admin

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1273]
**Is your feature request related to a problem? Please describe.**

Currently our application assumes that all persons tracked in the database are Talawa users. This may not be the case in practice. Administrators will require the ability to manage people who either cannot access our apps or don't want to.

**Describe the solution you'd like**

There are requirements dependent upon the repository

### API
1. We need to update the `User` collection to have a `User Type` field that could have at a minimum these possible values
     1. `App User`
     1. `Non App User`
1. This will need to be a mandatory field
1. Mutations for this field will need to be created for the `User` and related collections

The aim is that this field will be automatically populated during the registration process. Here are some examples:
1. Registrations through the mobile app would automatically be by an `App User`
1. Registrations through the Admin Portal and User Portal features of the Talawa Admin web app would automatically be by an `App User`
1. Admins may want to manually add Users who may be an `App User` or a `Non App User`
1. Persons attending events may need to be checked in. If they are new to the organization, then the event organizer may want to add them as a `Non App User`

### Admin
We require this from you:
1. Registrations through the Admin Portal and User Portal features of the Talawa Admin web app would automatically be by an `App User` and the DB must be updated accordingly

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
Related issues include:
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1552 (Prerequisite)
1. https://github.com/PalisadoesFoundation/talawa/issues/2269
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1273

**Other**
- Valid tests for this must be created as part of the resolution of this issue

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by adi790uu** [comment]
hey i would like to work on this!

**Comment by gauravsingh94** [comment]
Please assign this one to me.

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by Shubh152** [comment]
Please assign this issue to me

**Comment by Shubh152** [comment]
Unassigning as prerequisite not yet satisfied

**Comment by 1010varun** [comment]
hey @Shubh152 can you please tell me what the prerequisites are?
@Cioppolo14 assign this issue to me

**Comment by Cioppolo14** [comment]
@1010varun I think #1552 in Talawa-API is the prereq, see above. Do you still want this issue?

**Comment by adi790uu** [comment]
Hey @Cioppolo14 would like to take this up again!

**Comment by adi790uu** [comment]
Hey @palisadoes is this issue still valid as we have changed how we have changed the whole approach by adding the NON_USER field in the enum and a new user is give the role of USER automatically.

**Comment by Cioppolo14** [comment]
@adi790uu Thank you.  You are correct we don't need this issue. I am going to close this now.
