### ISSUE TITLE
Upgrade to Node 20 (LTS)

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1274]
**Is your feature request related to a problem? Please describe.**

1. We need to ensure that the app runs on an LTS version of Node.js
    1. https://nodejs.org/en/about/previous-releases
1. The installation guide doesn't specify the required LTS version of Node.js to be used
1. The application needs to be tested to make sure that it works with an LTS version of Node.js
1. Our GitHub Actions need to be updated to specify the LTS version of Node.js to be used

**Describe the solution you'd like**
1. Upgrade to Node 20 LTS
1. Update the installation guide to specify this LTS version of Node.js to be used
1. Update the installation or automated setup process to fail if the minimum LTS version isn't being used
    1.  https://github.com/PalisadoesFoundation/talawa-admin/issues/1233
1. Test the application to make sure that it works with this LTS version
1. Our GitHub Actions need to be updated to specify this LTS version of Node.js to be used
1. Address all warnings and errors (especially those related to deprecation) to the best of your ability according to industry best practice
1. All existing tests must pass

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Veer0x1** [comment]
would like to work on it

**Comment by Veer0x1** [comment]
@palisadoes @Cioppolo14 in push workflow somewhere `npm` is used and somewhere `yarn` is used. Is it intentional??


<img width="1440" alt="Screenshot 2023-12-27 at 1 16 04 AM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/96714915/df4e3529-d1f7-4616-864b-094fb1a4c1fc">

**Comment by Veer0x1** [comment]
And in `push.yml` file for node version we are using matrix strategy but it is not defined. So should change it to directly use the LTS version or create a matrix strategy??

<img width="1440" alt="Screenshot 2023-12-27 at 1 28 49 AM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/96714915/6ba36643-fb9e-4c3c-a9bf-8a5689960987">

**Comment by Veer0x1** [comment]
Why isn't issues getting closed, when PR get merged?

**Comment by palisadoes** [comment]
1. Don't remove yourself from assignment when the PR is completed and the issue isn't closed. It means we could assign the issue to someone else by accident
1. The automatic closing seems to only work on the default branch. We sometimes forget to close the issue

**Comment by Veer0x1** [comment]
Okay, I will take care of it from now onwards.
