### ISSUE TITLE
GitHub Actions Test - Fail When Too Many Files Submitted

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1276]
**Is your feature request related to a problem? Please describe.**

1. The repository's MVP is now based on the code in the `main` branch. We make all new changes to the `develop` branch and periodically merge `develop` into `main`
2. Contributors are now frequently submitting pull requests (PR) either merging `main` into `develop` or vice versa. This causes PRs with hundreds of submitted files.

**Describe the solution you'd like**

1. We need a GitHub Action added to the repository that counts the number of files submitted and fails if they exceed 20, which is a reasonable number in most cases.
2. The message must indicate that the contributor may either be merging into an incorrect branch or the source branch is incorrect.
3. If any scripting is required, this must be done in python3 with python `black` and `pydocstyle` linting and formatting rules applied. We have examples in the `.github/workfows` directory.
4. The action must run in its own section after the `Continuous-Integration` section in this workflow file
    - https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Tarunmeena0901** [comment]
@palisadoes i would like to work on this issue

**Comment by Tarunmeena0901** [comment]
this issue is fixed kindly close
