### ISSUE TITLE
Standardize the Pull Request GitHub Action to match Talawa API

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1277]
**Is your feature request related to a problem? Please describe.**

We need to standardize our Typescript GitHub action jobs to have at least these two  jobs:

1. `Code-Quality-Checks`: Handles 
     1.  Setting environment variables
     2. Installing packages
     3. Linting checks
     4. Formatting checks
     5. Counting lines of code submitted
2. `Test-Application`: Relies on  `Code-Quality-Checks` and handles:
    1.  Testing the application

## Talawa Admin
This repository:
- https://github.com/PalisadoesFoundation/talawa-admin/blob/main/.github/workflows/pull-requests.yml

## Talawa API
API standard:
- https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml

## Other

**Describe the solution you'd like**
1. Split the `Continuous-Integration` job section into two separate sections as described above.
1. Leave all other job sections unchanged
1. Verify that the existing functionality is maintained

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- N/A

**Additional context**
- N/A

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
Hey @palisadoes , I would love to work on this issue as I want to contribute to something significant.
Thank you !

**Comment by palisadoes** [comment]
@aialok You already have 2 assigned issues.

**Comment by aialok** [comment]
> @aialok You already have 2 assigned issues.

Pull request is already merged. Issue need to get closed.

**Comment by aialok** [comment]
Should I make pull request to main directly main directly or I have to make pull request to develop as both have diffrent github actions workflows and I have refactor code according to main github actions workflow.

**Comment by palisadoes** [comment]
We are only merging into `develop` at this time

**Comment by aialok** [comment]
> We are only merging into `develop` at this time

Should I refactor the code based on the develop branch or the main branch, considering the slight differences in GitHub Actions workflow codes for each?

**Comment by palisadoes** [comment]
Only work on `develop` we have a formal process to merge `develop` to `main`
