### ISSUE TITLE
Messaging when no Adds are found isn't in keeping with the design

### ISSUE THREAD

**Issue by gauravsingh94** [PalisadoesFoundation/talawa-admin#1278]
**Is your feature request related to a problem? Please describe.**
Messaging when no Adds are found isn't in keeping with the design

**Describe the solution you'd like**
Make it uniform with the design of the website

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/e258eaba-9a38-436d-b242-a9f01bd81cff)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by gauravsingh94** [comment]
Please assign this to me i have solve the similar issue previously.

**Comment by palisadoes** [comment]
1. This is a minor change. 
2. Though we have created minor design element changes, they were because they were not in keeping with the previously approved design.
3. We are working on many higher priority design issues that will soon be opened. Stay tuned.
4. Closing
