### ISSUE TITLE
 Improper positioning of Event Statistics in the mobile view

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-admin#1286]
**Bug Description:**
Encountering inconsistent modal behavior and improper positioning UI in the mobile view for Event Statistics.

**Steps to Reproduce:**
1. Navigate to the organization.
2. Click on "Events."
3. Access the Event dashboard.
4. Click on "View Event Statistics."

**Expected Behavior:**
Anticipating a clear and concise presentation of the UI in line with expectations.

**Actual Behavior:**
Observing discrepancies in the UI, specifically with modal positioning, not aligning with anticipated behavior.

**Screenshots:**
![Screenshot](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/5d690cc2-3462-4fe2-b984-82a36dffa03e)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
@palisadoes  can you assign me this
Thanks!!

**Comment by rishav-jha-mech** [comment]
Closing this Issue, because its fixed now
