### ISSUE TITLE
Improve Responsiveness of orgList

### ISSUE THREAD

**Issue by KrishavRajSingh** [PalisadoesFoundation/talawa-admin#1290]
**Describe the bug**
Admin and members hides below the manage button

**To Reproduce**

1. Sign in to the Talawa Admin Portal
2. Open Inspect and resize the window around 1132 X 997, admin and members will be seen hiding below the Manage Button

**Expected behavior**
Admin and Members should be clearly visible

**Actual behavior**
Admin and Members hides below the manage button

**Screenshots**
![Screenshot (250)](https://github.com/PalisadoesFoundation/talawa-admin/assets/99531396/e4fa7257-b4e4-47f9-b00a-d17448659f5a)

**Additional details**
I would like to work on this issue

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pankaj-2503** [comment]
Hey , I have setup this project locally i am getting error message while filling registration form when giving right credentials . How should I login so that I can work on this issue.

**Comment by Cioppolo14** [comment]
@KrishavRajSingh Is this an issue you wanted to work on?

**Comment by KrishavRajSingh** [comment]
> @KrishavRajSingh Is this an issue you wanted to work on? 

Yes

**Comment by KrishavRajSingh** [comment]
> Hey , I have setup this project locally i am getting error message while filling registration form when giving right credentials . How should I login so that I can work on this issue.

Try to go through Installation.md in talawa-api

**Comment by gautamayush303** [comment]
Can , I work on this please ?

**Comment by KrishavRajSingh** [comment]
> Can , I work on this please ?

I am working on this
