### ISSUE TITLE
Search Functionality Not Triggered by Search Icon

### ISSUE THREAD

**Issue by akhilender-bongirwar** [PalisadoesFoundation/talawa-admin#1292]
**Describe the bug**
The search function does not initiate when the search icon is clicked. It only activates when the Enter key is pressed. The desired behavior is for the search to begin when either the icon is clicked or the Enter key is used.

**To Reproduce**

1. Navigate to Angel Organization
2. Go to Posts Screen
3. Enter a search query in the search bar.
4. Click the search icon.
5. Observe that the search results do not change.

**Expected behavior**
Searching should even function when search icon is clicked not only just by enter key.

**Actual behavior**
Searching only functions when the Enter key is pressed.

**Video**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/4b64df0a-2819-4be4-9915-df71029bf697

**Additional details**

 This issue is not confined to the Posts screen; it pertains to all search bars within the application.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Hasnain01-hub** [comment]
Can I work on this issue??

**Comment by akhilender-bongirwar** [comment]
@Hasnain01-hub, I will be working on this issue after @Cioppolo14 verifies the issue. Please find other open issues to work on.

**Comment by Cioppolo14** [comment]
@akhilender-bongirwar In the future, please indicate with a comment that you'd like to work on the issue when you create one.

**Comment by akhilender-bongirwar** [comment]
@Cioppolo14, I actually linked another issue, so I didn't ask for assignment until the issue was verified. But yes, in the future, I will definitely comment on the issue when I create it.
