### ISSUE TITLE
The sort button is not displaying the selected sorting option

### ISSUE THREAD

**Issue by chandel-aman** [PalisadoesFoundation/talawa-admin#1297]
**Describe the bug**
The sort button in Users and Post screen do not show the selected option nor does it shows that the sort is active.

**To Reproduce**

1. Open Users screen and Posts screen in talawa-admin
2. Change the sorting option

**Expected behavior**
Sorting button should display the selected sorting option, similar to that in Requests screen.

**Actual behavior**
On changing the sorting option though the sort is implemented it does not displays which sorting method is being implemented.

**Screenshots**

[Screencast from 13-12-23 11:45:51 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/bf4c5acc-2e4c-421b-9d38-6ed93611f5a3)

**Expected Behavior**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/f9bb2170-9b6a-4a76-8cac-a5042345b9a3)
- The option selected should be displayed in the sort button

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by rishabhbizzle** [comment]
I would like to work on this issue, can you assign me this?

**Comment by dhiraj0911** [comment]
I would like to work on this

**Comment by dhiraj0911** [comment]
I would like to work on this

**Comment by Nitin007017** [comment]
I want to work on this issue, can you assign it to me ?

**Comment by rishabhbizzle** [comment]
@palisadoes please close this issue
