### ISSUE TITLE
Ensure all non-test Typescript files have < 600 lines - Admin

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1298]
**Is your feature request related to a problem? Please describe.**

Our  GitHub action `countline.py` script is not sufficiently effective as deployed

- https://github.com/PalisadoesFoundation/talawa-admin/tree/main/.github/workflows

We need to also restore our goal of having no typescript files with > 600 lines of code. We do this for readability and to force better coding standards by encouraging the use of more reusable code.

**Describe the solution you'd like**

1. Update our pull request GitHub action to make the `countline.py` script fail for files with > 600 lines of code. Run the  `./countline.py --help` command to see how that is done.
1. Run  the `countline.py` script with the 600 line limit to identify the offending files.
1. Refactor the code in the offending files so that the script does not fail.
**Describe alternatives you've considered**

**Approach to be followed (optional)**
- See above

**Additional context**
- Please work with @noman2002 in reviewing your PR

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Min2who** [comment]
can i work on it?

**Comment by dhiraj0911** [comment]
I'd like to work on this

**Comment by AVtheking** [comment]
Please assign me this issue

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by Sauradip07** [comment]
@palisadoes can i work on it?

**Comment by Tarunmeena0901** [comment]
@palisadoes @Cioppolo14  in my last issue i worked on git hub actions to limit number of file change maybe I can take this one too I remember what we did and did not used last time

**Comment by nimishmedatwal** [comment]
@palisadoes Can you assign this PR to me?

**Comment by Sauradip07** [comment]
I am currently working on an issue to reduce the number of lines of code in some of our TypeScript (.ts) and TypeScript JSX (.tsx) files. The goal is to bring these files, which currently exceed 600 lines of code, down to a more manageable size of 600 lines.

There are 4 specific files that I am focusing on at the moment. I've attached pictures below for your reference.
![Screenshot from 2024-01-13 23-10-21](https://github.com/PalisadoesFoundation/talawa-admin/assets/82558066/40fb60fa-6d88-4e2e-b9ef-a879d722f9a0)

**Comment by palisadoes** [comment]
1. Merge your code with the latest upstream
2. Reopen a PR
3. Make sure the only files updated are typescript files that are over 600 lines in length. They must also be `tsdoc` compliant.
4. Your last PR submitted no files relevant to the issue. Please be more vigilant in your submission
