### ISSUE TITLE
Bug Report: Edit profile page is not responsive

### ISSUE THREAD

**Issue by pateldivyesh1323** [PalisadoesFoundation/talawa-admin#1301]
**Describe the bug**
Edit profile page is not responsive

**To Reproduce**

1. Login to admin portal
2. Go to your profile
3. Click on edit profile
4. Adjust the width of screen

**Expected behavior**
The form should adjust according to screen size

**Actual behavior**
All the input shrinks

**Video**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/d6e3a70a-d148-496b-91e0-0c23720f381c

**Additional details**
I would like to work on this.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pateldivyesh1323** [comment]
I would like to work on this, if this is a valid issue.

**Comment by palisadoes** [comment]
We are working on a new profile page structure and design. The issues related to this will be posted soon. Thanks for noticing this.

Closing
