### ISSUE TITLE
Social Icons Integration on Login and Signup Page 

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1304]
**Is your feature request related to a problem? Please describe.**
yes, Improving social reach of the palisadoes organization

**Describe the solution you'd like**
Social icons of Talawa should be added to the login page and signup page of both user and admin portal, each redirecting to the respective social platform.

**Describe alternatives you've considered**
NA.

**Approach to be followed (optional)**
The login page should include social icons for all Talawa platforms, each redirecting to the respective platform.

**Additional context**
![Screenshot 2023-12-28 at 12 25 20 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/d5627a85-964c-46b8-a76e-36269090b61f)

Add slack icon also

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
I would love to work on this issue : )

**Comment by palisadoes** [comment]
This PR was merged prematurely, we wanted you to make the Palisadoes Logo clickable so that the official website would open.
