### ISSUE TITLE
Enhancements for Session Management in both user and admin portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1305]
**Describe the bug**

The current system lacks admin-configurable session timeouts, leading to unexpected logouts. Additionally, users are not receiving warnings before timeouts, and the messaging upon session logout does not redirect them to the login screen seamlessly.

**To Reproduce**

1. Login to talawa-admin portal.
2. Leave the user logged in until the session times out.
3. The user gets logged out without receiving any warning on session timeout.

**Expected behavior**
- Admin should be able to configure the session timeouts in settings
- the user should receive a warning before the session timeout and should get redirected to login screen automatically.

**Actual behavior**
Admin does not has any feature to configure the session timeouts, nor there is any warning displayed before a session timeout.

**Screenshots**
NA

**Additional details**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by chandel-aman** [comment]
@aashimawadhwa Can I work on this issue?

**Comment by chandel-aman** [comment]
@palisadoes @noman2002
May I be assigned to address this issue?

**Comment by chandel-aman** [comment]
@aashimawadhwa
Regarding the implementation of admin-configurable session timeouts, does this imply that each organization will be able to set its own session timeout values?

**Comment by chandel-aman** [comment]
@aashimawadhwa 
Also, currently, our system logs out users only after a specified period of inactivity. For active users, we manage session timeouts by renewing access tokens through refresh tokens. However, if a user is inactive, implying they are not actively on the screen, is it necessary to display a warning when the session expires? Wouldn't this warning be ineffective if the user is not actively engaged on the screen?

**Comment by chandel-aman** [comment]
@palisadoes @aashimawadhwa

I've got a couple more queries about configurable timeouts:

1. When we say that the admins can configure the session timeout, do we mean for each organization?

   -  If yes, then what should be the timeout duration for users belonging to multiple organization?
   -  Should it be configurable by both admins and super-admins?
   -  And what should be the timeout duration for admins and super-admins?

3. What should be the acceptable time range for admins to configure timeout duration?

    Based on my web research, a time range between 15 to 60 minutes would be reasonable, considering both security and performance concerns. What are your views on this?

**Comment by noman2002** [comment]
@chandel-aman 
- If the user belongs to multiple organizations then take the highest one. 
- yes it will be configurable by both admin and super-admin
- 30 mins by default for everyone. 
- The range can be between 15 to 60 mins.

**Comment by chandel-aman** [comment]
Thanks for the info, @noman2002!

**Comment by palisadoes** [comment]
This would be much better served at the Community level with a single value for all organizations. Therefore it would be managed by the SuperAdmin using this profile page for the configuration
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1334#issuecomment-1879522861

Please make the appropriate changes to make this a single universal parameter

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by AmitSharma512** [comment]
@Cioppolo14 can I work on this?

**Comment by DecodeAndCode** [comment]
i would like to work on this issue.

**Comment by plasma018** [comment]
Unassigning due to inactivity

**Comment by Ramneet04** [comment]
can I start working on this??
