### ISSUE TITLE
Redesign Talawa User Portal Settings Page to Match Admin Portal Design

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1306]
**Is your feature request related to a problem? Please describe.**
yes, consistency in the designs

**Describe the solution you'd like**
Redesign the Talawa user portal settings page  as the design of the Talawa admin portal.

**Describe alternatives you've considered**
NA.

**Additional context**

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/4e5879c7-46ae-4133-9c8e-3a0dbe57ecf6)

Exclude the "Delete Organization" and "Manage Custom Fields" settings

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
hey @aashimawadhwa can you assign me this !!
thanks!!

**Comment by Cioppolo14** [comment]
@duplixx Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by duplixx** [comment]
hi @Cioppolo14 , I wanted to inform you that I have completed the work on the assigned issue and it is ready to be merged. Additionally, I would like to request your permission to unassign myself from the past issue.

**Comment by Cioppolo14** [comment]
@duplixx Until you've completed one of your two issues, I cannot assign you another issue.  Managing issues and PRs in this way would make it impossible for the volunteers to track. Please do not unassign yourself an issue that has an active PR that you plan on owning and pursuing to completion.

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by Hasnain01-hub** [comment]
I would like to work on this issue.

**Comment by pateldivyesh1323** [comment]
@palisadoes @noman2002 This can be closed.
