### ISSUE TITLE
User Dropdown in Navbar Not Redirecting Properly

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1307]
**Describe the bug**

Clicking on options in the user dropdown menu of the user portal navbar, such as "Settings" or "My Tasks," does not redirect properly when clicking on the non-text area of the option. However, it functions correctly when clicking on the text of those options.

**To Reproduce**

1. Log in to the Talawa User Portal.
2. Click on the user dropdown in the navbar.
3. Attempt to click on options like "Settings" or "My Tasks" directly on the non-text area of the option.

**Expected behavior**

Clicking on the option, whether on the text or the non-text area, should correctly navigate to the intended location.

**Actual behavior**

Clicking on the non-text area of the option does not redirect properly, while clicking on the text functions correctly.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/b17c96d3-59d7-4a69-ab9b-9a6d79228f10

**Additional details**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
I would love to work on this issue : )

**Comment by gauravsingh94** [comment]
Please assign this to me

**Comment by rajneesh069** [comment]
Hello, can I work on this issue?

**Comment by Sahil-Shadwal** [comment]
I would love to work on this issue . Please assign this issue to me , i am new here and it would be a good first issue .

**Comment by gauravsingh94** [comment]
@palisadoes  Please close this issue it is merged.
