### ISSUE TITLE
Confusing Alignment of radio buttons to filter members ((Members, Users, Admins)) in Manage section 

### ISSUE THREAD

**Issue by karthxk07** [PalisadoesFoundation/talawa-admin#1311]
**Describe the bug**
The radio buttons for 'Members,' 'Users,' and 'Admins' in the filter section are not aligned properly. Instead of being in a straight line, they are arranged in a confusing and irregular pattern, making it difficult for users to select the desired option.

**To Reproduce**

1. Log in to the admin portal.
2. Go to any organisation (or add a sample organisation if none present)
3. Go to the people's tab on the left hand sidebar.

**Expected behaviour**
The User, Members and Admins radio buttons should be aligned in a straight vertical line.

**Actual behaviour**
Instead the Users, Members and the Admins radio buttons are not aligned properly and are in a irregular pattern.

**Screenshots**

![Screenshot from 2023-12-28 18-13-03](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/cff23295-19c0-49ef-af16-23684b2504f4)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by karthxk07** [comment]
On approval . could i get this issue assigned to me ?

**Comment by gautamayush303** [comment]
Can, I work on this please ?

**Comment by Pranavx1** [comment]
Can i work on this?

**Comment by Kevoniat** [comment]
> Can i work on this?

you now have two issue assigned you are not allowed any more

**Comment by karthxk07** [comment]
@Kevoniat Sir, I had been waiting for this to get assigned to me :/ , mentioned it here #380 . :/

**Comment by karthxk07** [comment]
fixed by #1194 , closing.
