### ISSUE TITLE
Feature Request:Links would look better if it would be in center in mobile view

### ISSUE THREAD

**Issue by pankaj-2503** [PalisadoesFoundation/talawa-admin#1319]
**Is your feature request related to a problem? Please describe.**
The div in which links are provided should be in center in mobile view  for better ui . It can be done by applying css to footer div .

**Describe the solution you'd like**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90036864/8ec9c0c8-3b48-45bf-9a3b-34a561f87038)

**Describe alternatives you've considered**

**Approach to be followed (optional)**
As mentioned in screenshot just inspect and click to mobile view

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by rishabhbizzle** [comment]
can I work on this?

**Comment by pankaj-2503** [comment]
Hey @noman2002  i have tried to install this repo locally but i got error while doing so . First I tried to set up talawa-api  locally then talawa-admin but in talawa-api setup i got error while running the project.Can you please help me what should I try to do.

**Comment by Taher2512** [comment]
I would like to work on this issue. Can it be assigned to me please?

**Comment by gautamayush303** [comment]
Can I work on this please ?

**Comment by noman2002** [comment]
> Hey @noman2002 i have tried to install this repo locally but i got error while doing so . First I tried to set up talawa-api locally then talawa-admin but in talawa-api setup i got error while running the project.Can you please help me what should I try to do.

Please ask in the slack channel, someone will help you out.
