### ISSUE TITLE
Login screen reappears briefly after successful login

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1328]
**Describe the bug**
Upon successful super admin login

1. the screen goes blank
2. then the login screen briefly flashes 
3. the screen goes blank
4. then the organization screen appears

**To Reproduce**
- See above

**Expected behavior**
- The login screen must not be seen again after authentication is validated

**Actual behavior**
- See above

**Screenshots**
https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/9debe957-373e-40a1-a40f-a01f20e76ee9

**Additional details**
- N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by palisadoes** [comment]
Reopening. This issue is still occurring

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?
