### ISSUE TITLE
The language selection div overlaps with the PalisodoesFoundation's icon.

### ISSUE THREAD

**Issue by techmannih** [PalisadoesFoundation/talawa-admin#1329]
**Is your feature request related to a problem? Please describe.**
hello @palisadoes ,
The language selection box on our site covers the PalisodoesFoundation's icon in between 352px to 320px, making it confusing and unfriendly for users.
I want to work on this assign me 

**Describe the solution you'd like**
1.Decrease the width of the language selection div in the website's CSS or styling files
2. Add a margin between the language selection div and the PalisodoesFoundation's icon
3. Verify the changes in different screen sizes and browsers to ensure responsiveness.

**Describe alternatives you've considered**\
The website to confirm that the language div no longer overlaps with the PalisodoesFoundation's icon

**Additional context**
Screenshot
![Screenshot 2023-12-31 162441](https://github.com/PalisadoesFoundation/talawa-admin/assets/125847751/a553439d-3226-48bb-a60f-b9f3eccc2b91)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by rishabhbizzle** [comment]
I want to work on this. Please assign it to me

**Comment by palisadoes** [comment]
1. Closing. 
1. We are focusing on bugs and features that cause real hardship.
1. This is an unlikely usage case
