### ISSUE TITLE
Organization not found error in left drawer

### ISSUE THREAD

**Issue by nitishkumar333** [PalisadoesFoundation/talawa-admin#1333]
**Describe the bug**
When user profile is opened through the orglist page, an error is shown on the member page and redirected back to orglist page.

1. Login 
2. Click on the username on the bottom left

**Expected behavior**
No error should be shown on the member page and should not redirect back to orglist.

https://github.com/PalisadoesFoundation/talawa-admin/assets/123248648/be02ad60-17be-4c32-973a-a3bf5fe5b67e

**Comment by rishabhbizzle** [comment]
I want to work please assign it to me

**Comment by nitishkumar333** [comment]
Please assign it to me.

**Comment by noman2002** [comment]
@aashimawadhwa is this a valid issue ??

**Comment by rishav-jha-mech** [comment]
@noman2002 this is a valid issue. Let me explain.

When the current user is Admin/Superadmin, and tries to open his profile on clicking on the left drawer, he should be redirected to Superadmin Profile screen (Which does not exist yet), instead of going to that screen the user is being sent to an Organisation Profile Screen (Where the admin/superadmin can see other user's profile not his own).

@nitishkumar333 you need to create a new endpoint for this admin profile screen, but try to reuse the same component which we are using in the profile screen. Let me know if you face any problem.

**Comment by nitishkumar333** [comment]
@rishav-jha-mech instead of creating a new endpoint (which will lead to creation of new files), I passed a state parameter with the link and conditionally rendered the MemberDetails component. Please let me know what you think of this approach.

![Screenshot (95)](https://github.com/PalisadoesFoundation/talawa-admin/assets/123248648/e4aeada7-c689-498f-88c0-b468de40e8e2)

![Screenshot (94)](https://github.com/PalisadoesFoundation/talawa-admin/assets/123248648/2380ba6f-cb3c-4cbe-a560-bb8eeacf6c56)

Here is what is looks like, looking for feedback on it

https://github.com/PalisadoesFoundation/talawa-admin/assets/123248648/464a78e5-cdfa-463b-a354-6b0e1547c003

**Comment by rishav-jha-mech** [comment]
@nitishkumar333 good work, open the PR for this soon.

**Comment by varunsh17** [comment]
I am also ecperiencing the same issue 
`Error occured while loading Organization Data
Cast to ObjectId failed for value "undefined" (type string) at path "_id" for model "Organization"` 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/81704366/12f7a3f6-bc34-4bfd-94a4-44f2e4137118)

**Comment by kanhaiya04** [comment]
I also identified this issue a few weeks back and am currently investigating a solution. If no one is currently working on it, I would like to take on the task. @palisadoes

**Comment by nitishkumar333** [comment]
Hi @kanhaiya04 I have already made a PR for this issue, also this issue will no longer exists after #1407

**Comment by kanhaiya04** [comment]
@nitishkumar333 Thanks for letting me know.

**Comment by GlenDsza** [comment]
As the earlier PR was closed and not merged and issue still persists, I would like to work on this issue

**Comment by GlenDsza** [comment]
As the issue still persists and changes are not made I would like to work on this issue
