### ISSUE TITLE
Add the ability to change pre-login imagery

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1334]
**Is your feature request related to a problem? Please describe.**
1. Communities need the ability to change the social media icons and logo images upon login.
1. We don't want users thinking that they are always logging into Palisadoes

**Describe the solution you'd like**

1. Our login screen is not specific to organizations, so we'll need to make this change at the Community level.
1. This will require the creation of a Community Profile button at the Super Admin level which would lead to a Community Profile edit screen
1. This screen must be designed in keeping with our Talawa Admin Figma design found here
    1. https://docs.talawa.io/docs/design/ux/ux-design-system
1. The logo and social media icons to be edited are visible in the attached screen shots
1. By default, when the Palisadoes Logo is changed, the Palisadoes specific social icons should disappear so that the Community can add theirs. If the Logo is left blank, then the Palisadoes imagery should return, but the database parameters must remain so that the Admin doesn't have to re-enter the information.
1. This will require the creation of a new collection in the API
1. Please work with @aashimawadhwa and @rishav-jha-mech on the design approval before submitting a PR
1. You will need to write valid tests for your code
1. No other functionality must be affected

**Related Issues**
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1334
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1611

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
1. Images that should be editable: 
    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/0347a075-e9f5-4117-8816-a9aab27e99d5)
1. Location of the Community Profile
    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/76b8b87b-87d0-4178-97c8-e6c82911a399)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by gauravsingh94** [comment]
Please this to me

**Comment by chandel-aman** [comment]
@palisadoes @noman2002 
Can I work on this issue?

**Comment by palisadoes** [comment]
Take design cues from this issue
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1306

Also coordinate with the person assigned the API issue as you'll need to tell them what you need

**Comment by gauravsingh94** [comment]
Please review this website design.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/4a0f4b55-d864-4b0d-b657-17bc58fdb27d)





 Once the design is approved, I will instruct the @chandel-aman  to create routes for storing the logo, description, and social icons. Afterward, I will integrate these elements into the webpage.

@palisadoes @aashimawadhwa @rishav-jha-mech

**Comment by gauravsingh94** [comment]
**Video**

[Screencast from 2024-01-01 23-47-34.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/88ce0399-dcd4-4d9e-9cba-919877282955)

**Comment by gauravsingh94** [comment]
**Video**

[Screencast from 2024-01-01 23-50-46.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/081a4c0b-dde6-4cfc-92a8-c50cac3b65a7)

**Comment by palisadoes** [comment]
1. The social media icons will each need to have their own image and url
1. This issue will provide the source images for the social media platforms
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1304
1. You will need to have the ability to add URLs for each social icon. If there is no URL, then there should be no icon, unless the reset is applied and the Palisadoes icons and URLs return

**Comment by rishav-jha-mech** [comment]
@gauravsingh94 this is how the screen should look like, the settings icon is already present in our project. 
![Dashboard _ Community Profile (1)](https://github.com/PalisadoesFoundation/talawa-admin/assets/76212518/3558a6dd-5256-49ef-af71-fc378466d056)

**Comment by gauravsingh94** [comment]
> @gauravsingh94 this is how the screen should look like, the settings icon is already present in our project. 
> ![Dashboard _ Community Profile (1)](https://github.com/PalisadoesFoundation/talawa-admin/assets/76212518/3558a6dd-5256-49ef-af71-fc378466d056)
> 

Ok I will update accordingly.

**Comment by gauravsingh94** [comment]
> @gauravsingh94 this is how the screen should look like, the settings icon is already present in our project. ![Dashboard _ Community Profile (1)](https://private-user-images.githubusercontent.com/76212518/293601840-3558a6dd-5256-49ef-af71-fc378466d056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNTEyNzgsIm5iZiI6MTcwNDE1MDk3OCwicGF0aCI6Ii83NjIxMjUxOC8yOTM2MDE4NDAtMzU1OGE2ZGQtNTI1Ni00OWVmLWFmNzEtZmMzNzg0NjZkMDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDIzMTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NGE4Njc2NGRkNmM5NzAwNWIzOGIxZjAxZWI1OWE1MzRhODM2ZDA2NGZlNGFlYTIyNDBlZmEyYjVjNzEyYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rRAgeCIV-TdYXhlilAC-yBMCLcy0hv2dXF7yo4z6NUQ)

Could you kindly share the link to the Figma design so that I can access the icons and obtain their precise dimensions as well as easily export them as SVG files? 

Unfortunately, the community profile section appears to be missing in the Figma design you mentioned earlier.

**Comment by gauravsingh94** [comment]
> @gauravsingh94 this is how the screen should look like, the settings icon is already present in our project. ![Dashboard _ Community Profile (1)](https://private-user-images.githubusercontent.com/76212518/293601840-3558a6dd-5256-49ef-af71-fc378466d056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNTEyNzgsIm5iZiI6MTcwNDE1MDk3OCwicGF0aCI6Ii83NjIxMjUxOC8yOTM2MDE4NDAtMzU1OGE2ZGQtNTI1Ni00OWVmLWFmNzEtZmMzNzg0NjZkMDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDIzMTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NGE4Njc2NGRkNmM5NzAwNWIzOGIxZjAxZWI1OWE1MzRhODM2ZDA2NGZlNGFlYTIyNDBlZmEyYjVjNzEyYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rRAgeCIV-TdYXhlilAC-yBMCLcy0hv2dXF7yo4z6NUQ)

Can you please provide me the link for this figma design so that i can get the exact dimenstions of the icons and easily get the svgs

**Comment by gauravsingh94** [comment]
> > @gauravsingh94 this is how the screen should look like, the settings icon is already present in our project.
> > ![Dashboard _ Community Profile (1)](https://private-user-images.githubusercontent.com/76212518/293601840-3558a6dd-5256-49ef-af71-fc378466d056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNTYwMzQsIm5iZiI6MTcwNDE1NTczNCwicGF0aCI6Ii83NjIxMjUxOC8yOTM2MDE4NDAtMzU1OGE2ZGQtNTI1Ni00OWVmLWFmNzEtZmMzNzg0NjZkMDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDAwMzUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZWQ3YjkzODRlMmI4OWM4Zjc2ZWZlNjgxMWY3MzM5NTgzYzFkYThhNTM4ZWFjMzBhOTFiYjRiMzNiZmYyYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3VwyC5fGE_dq8W4IpEh-yq4aUbTEDRQaH26lGdmtmcM)
> 
> Ok I will update accordingly.

Can you please provide me the figma design so that i can easily get the svgs.

**Comment by gauravsingh94** [comment]
> The link is in the first comment of the issue

In that there is svg and I have use but svgs for reddit and instagram is missing.

**Comment by gauravsingh94** [comment]
These svgs are present in the above figma design.


![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/6cc08c74-66a3-4d8a-af72-0dc0b4d3bcca)




But the  svgs for instagram and reddit is missing.

The svgs that are present i have added them to the website.


![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/71ea38bd-b978-40f2-a2d5-85d0f55d9cb1)

But instagram and reddit are missing so i have not added them.

**Comment by rishav-jha-mech** [comment]
Here @gauravsingh94 

https://www.figma.com/file/dTGr5CnGHvkilU5nwnRXg2/Talawa-Admin-UI-Redesign?type=design&node-id=813-2332&mode=design

**Comment by rishav-jha-mech** [comment]
@gauravsingh94 please refer to this PR, and use X instead of Twitter Icon, add slack to the site as well.

https://github.com/PalisadoesFoundation/talawa-admin/pull/1326

**Comment by gauravsingh94** [comment]
I haven't fully adhered to the `Figma` design as it includes elements like `Community Name` that are not applicable to our use case.

![Pasted image](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/55509bce-621f-412a-bd43-2c5169f228b1)


I've utilized the design above but selectively incorporated only essential components for our `login/signup` page.

Please review this updated changes in the page.

![Screenshot 2024-01-02 at 19-38-30 Talawa Community Profile](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/5bc8a2a7-7e30-47ef-981e-2a617de73f9f)



**Video**

[Screencast from 2024-01-02 19-35-53.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/21a4f994-7e53-4461-b0c1-6db2c1174c78)

**Comment by gauravsingh94** [comment]
@chandel-aman 

Please set up the backend to include the following elements:

- Community Logo: String (encoded as a 64-bit string)
- Community Description: String
- Facebook URL: String
- Twitter URL: String
- LinkedIn URL: String
- GitHub URL: String
- YouTube URL: String
- Slack URL: String
- Reddit URL: String

Create queries and mutations to retrieve information. The query should provide the URL for the logo, and for the other elements, it should return their respective values.

**Comment by rishav-jha-mech** [comment]
@chandel-aman @gauravsingh94 

Website Link should be there, and Community Name should also be there, it maybe needed at some other places in future.

**Comment by rishav-jha-mech** [comment]
@gauravsingh94 any ETA ?

**Comment by gauravsingh94** [comment]
> @gauravsingh94 any ETA ?

I have completed it and make the fronted and wating for @chandel-aman to update the backend so that I can update the fronted so I can make pr.

**Comment by gauravsingh94** [comment]
@rishav-jha-mech Do I need to make the pr ?
But I am not fetching or sending data to the backend.

**Comment by rishav-jha-mech** [comment]
@gauravsingh94 Its okay, no need to create a PR now, just wanted to check if something is blocking you

**Comment by gauravsingh94** [comment]
@rishav-jha-mech Do i need to update the fronted according to this pr but it not passing some tests or wait units it is completely fixed?

**Comment by palisadoes** [comment]
As this PR is almost ready to be merged you can base your changes on it in the API. Test against this code.
- https://github.com/PalisadoesFoundation/talawa-api/pull/1673

Here is how to check out a PR to your local branch. Do this for the API
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally

**Comment by gauravsingh94** [comment]
Hi @chandel-aman, I am currently working on the frontend. Could you please provide the queries for retrieving a community and creating a community mutation? I have only come across the updateMutation.

**Comment by gauravsingh94** [comment]
@palisadoes  @rishav-jha-mech the above pr don't have query for retriving the community and reset option for removing the data , mutation for creating the community.

**Comment by palisadoes** [comment]
1. This API PR is adding it. You can pull the changes to a local branch to add the required feature. 
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1673
1. You can coordinate with the author too.

**Comment by chandel-aman** [comment]
> @palisadoes @rishav-jha-mech the above pr don't have query for retriving the community and reset option for removing the data , mutation for creating the community.
> 
> It have only updateCommunity resolver.

1. For retrieving the community details, you can refer to this API PR:
    https://github.com/PalisadoesFoundation/talawa-api/pull/1665.
2. Regarding the creation of the community, I'm doubtful if the scope of this issue covers it.
    @palisadoes @rishav-jha-mech, could you please comment on this?

**Comment by palisadoes** [comment]
Please create an issue in the API specifying in detail what you need to complete this issue and see if someone will start working on it.

**Comment by chandel-aman** [comment]
> Please create an issue in the API specifying in detail what you need to complete this issue and see if someone will start working on it.

Certainly, sir! Could you please describe the intended flow of creating a community in Talawa? Specifically, I'd like to know who will be able to create a community. Additionally, apart from the community name, description, timeout, and social media URLs, what other information needs to be provided for the creation of a community?

**Comment by palisadoes** [comment]
That's all that is required for now

**Comment by palisadoes** [comment]
1. Unassigning due to no PR for a few weeks.
2. @chandel-aman do you want to work on this to help with the coordination with your API issue?

**Comment by chandel-aman** [comment]
Sure, sir. I'll be more than happy to work on it.

**Comment by Olatade** [comment]
@chandel-aman are you still working on this?

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR

**Comment by Sauradip07** [comment]
Please assign this issue to me

**Comment by Cioppolo14** [comment]
@Sauradip07 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by git-init-priyanshu** [comment]
Hi, I have created the UI as per the Figma design. If there is any issue with the design then let me know, I will fix them. 
Are there APIs available for this page? If not then I would be more than happy to create them. Thanks.

[Screencast from 27-02-24 07:41:53 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/dbd26bba-2b0c-4642-98ea-d7cceaf1cb84)

**Comment by palisadoes** [comment]
1. Please create a PR when ready
2. Coordinate with the person assigned this issue
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1611

**Comment by git-init-priyanshu** [comment]
Right now I am creating tests. Once this is done then I will make a PR.
