### ISSUE TITLE
Letter based avatar in case of blank display picture

### ISSUE THREAD

**Issue by wingman47** [PalisadoesFoundation/talawa-admin#1345]
**Is your feature request related to a problem? Please describe.**
Currently, any organization without any display image have blank squares on My Organizations page while it is letter based everywhere in the website which includes dashboard page and user profile whenever no image is selected.

**Describe the solution you'd like**
Show letter based avatar for organizations based on their initials without any image similar to what we are shown on the dashboard page.

**Approach to be followed (optional)**
We will use dicebear api, similar to how it is being used in LeftDrawerEvent component in dashboard as of now.

**Additional context**
Current condition:
![talawa](https://github.com/PalisadoesFoundation/talawa-admin/assets/49762303/2ba48d98-66fa-4a82-bec7-a153e8155d52)

While the dashboard shows letter based avatar.
![dashboard-1](https://github.com/PalisadoesFoundation/talawa-admin/assets/49762303/b1f19e68-52bd-41b2-9355-d525d2b155f6)

Output we want:
![example-1](https://github.com/PalisadoesFoundation/talawa-admin/assets/49762303/83dd1dd5-4b64-464b-9f15-d771552e7807)

**Comment by wingman47** [comment]
@palisadoes can you please assign this to me?

**Comment by palisadoes** [comment]
1. Please update the issue title with appropriate text to make it more easily searchable
2. How will this approach work with all supported and future languages?

**Comment by wingman47** [comment]
> 1. Please update the issue title with appropriate text to make it more easily searchable
> 2. How will this approach work with all supported and future languages?

1. Done
2. I plan to use dicebear api as it is already being used in different parts of the project like dashboard and user profile.

**Comment by palisadoes** [comment]
@aashimawadhwa  @rishav-jha-mech please comment
