### ISSUE TITLE
Code Coverage:  test failing at src/components/UserPortal/EventCard/EventCard.test.tsx

### ISSUE THREAD

**Issue by ALOK9442** [PalisadoesFoundation/talawa-admin#1348]
1 test failing at src/components/UserPortal/EventCard/EventCard.test.tsx

**To Reproduce**

1. run - npm run test and you'll find that 1 test failed at src/components/UserPortal/EventCard/EventCard.test.tsx 

**Expected behavior**
test should pass and give output in terminal
(The card should be rendered properly, and all the details should be displayed correct)

**Actual behavior**
1 Test failed at await waitFor(() => expect(queryByText('7:49:12 PM')).toBeInTheDocument());
(
expect(received).toBeInTheDocument()

    received value must be an HTMLElement or an SVGElement.
    Received has value: null
)
**Screenshots**
![Screenshot (71)](https://github.com/PalisadoesFoundation/talawa-admin/assets/104527572/c69d81d5-6411-44dd-ac63-c168b5724c26)

**Additional details**
we can solve this issue by matching the time format with 12 hour-format

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ALOK9442** [comment]
I want to work on this issue.

**Comment by palisadoes** [comment]
Why hasn't this test been failing as part of our pull request testing workflow? All tests are run as a part of that process

**Comment by ALOK9442** [comment]
I tried running test without changing any file and it keeps failing and when I am doing certain changes at that place  it gets passed,
so I am not sure about where I am going wrong so that it keeps failing in my system though I looked up in my localhost and couldn't find the error about why it failing in here
and I am unsure about why hasn't this test been failing as part of pull requests

**Comment by palisadoes** [comment]
1. You are probably using a non v20 version of node.
2. Closing. 
3. If using node v20 doesn't fix the issue, then ask to reopen it.

**Comment by nitishkumar333** [comment]
@palisadoes  I am also facing the same issue and my node version is v20.10.0 , also my branch is up to date.

**Comment by ALOK9442** [comment]
I am using the node v20.10.0 only and still facing the same issue.
kindly look into this matter

**Comment by palisadoes** [comment]
You'll need to investigate this yourselves. It is not failing in our workflows

**Comment by ALOK9442** [comment]
can you please guide me how can I get rid of this issue?
I have forked the repo again and did everything from start, followed every step written in INSTALLATION.md file and after this I run the command "npm run test" and stil facing the same issue.

**Comment by palisadoes** [comment]
Please ask the #talawa-admin slack channel
