### ISSUE TITLE
[BUG]: Refresh on registration tab on login page brings to login tab

### ISSUE THREAD

**Issue by Chaitanya-Shahare** [PalisadoesFoundation/talawa-admin#1352]
**Describe the bug**

When a user visits the registration tab on the login page, and reloads the page, login tab is opened instead of registration tab.

**To Reproduce**

1. Go to login page, on development server `http://localhost:3000/`
2. Click on the `Register` button.
3. Optionally can fill some values in the registration form.
4. Refresh the page

**Expected behavior**

User should stay on the Registration tab.

**Actual behavior**

User is redirected to Login tab.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/108579856/8f0aeded-cb2b-4229-a9c4-7dcd231d6961

**Additional details**
This can be solved using `query parameters`

**Comment by Chaitanya-Shahare** [comment]
Can you please assign this issue to me?

**Comment by rishav-jha-mech** [comment]
This is not a valid issue, by default login page is shown.
