### ISSUE TITLE
Organization List screen for SuperAdmin/Admin is refreshing completely while loading more organizations

### ISSUE THREAD

**Issue by rishav-jha-mech** [PalisadoesFoundation/talawa-admin#1359]
**Describe the bug**
Organization List screen for SuperAdmin/Admin is refreshing completely while loading more organizations

**To Reproduce**

1. Go to organization list screen
2. Set the network throttling to 2G
3. Scroll down further
4. Whole screen is getting reloaded

**Expected behavior**
The already loaded organizations should not reload

**Actual behavior**
Whole screen loading animation is played

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/76212518/9ae0afd2-c839-4146-8121-0da0d5703cc5

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
hey @rishav-jha-mech , can you assign me this issue thanks!!

**Comment by Sejal1411** [comment]
i would like to work on this issue

**Comment by duplixx** [comment]
@rishav-jha-mech I am working on talawa-api issue @Sejal1411 you can can take this issue

**Comment by Sejal1411** [comment]
Thanku  for assigning..I have started working on this issue.

**Comment by Cioppolo14** [comment]
Unassigning due to inactivity.

**Comment by NayOoLwin5** [comment]
I would like to work on this
