### ISSUE TITLE
Advertisement button in the left sidebar of talawa-admin dashboard not getting highlighted when active

### ISSUE THREAD

**Issue by chandel-aman** [PalisadoesFoundation/talawa-admin#1364]
**Describe the bug**

On the dashboard of talawa-admin when we open the advertisement page the "Advertisement" button in the menu of left-sidebar is not getting highlighted displaying active state.

**To Reproduce**

1. Login to talawa-admin.
2. Open the dashboard for any organization
3. Open the Advertisement page by clicking on Advertisement button from the left-sidebar.
4. Notice that the Advertisement button is not being highlighted.

**Expected behavior**

When the Advertisement page is open the Advertisement button in the left-sidebar should get highlighted, similar to other buttons.

**Actual behavior**
The Advertisement button is not getting highlighted when Advertisement page is open.

**Screenshots**

[Screencast from 03-01-24 05:47:04 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/6b9b2603-0162-436a-b206-c5e26e6e867b)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Pranavx1** [comment]
Can i work on this?

**Comment by Cioppolo14** [comment]
@Sejal1411 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by Pranavx1** [comment]
it already works for every other button
