### ISSUE TITLE
Improper alignment of Org-Image, Org-details and Manage button on mobile screens.

### ISSUE THREAD

**Issue by KshitijTodkar48** [PalisadoesFoundation/talawa-admin#1365]
**Describe the bug**
The alignment of Organization image, Organization details and the Manage button in the "My Organization" section is not proper on mobile screens.

**To Reproduce**

1. Login to admin portal.
2. Go to "My Organization" section.
3. Change the screen width below 450px.
4. See the layout of the Organization-Card.

**Expected behavior**
On mobile screens, the Organization image, Organization details, and the Manage button in the 'My Organization' section should be aligned properly to ensure a visually cohesive and user-friendly display.

**Actual behavior**
Organization image, Organization details and the Manage button are not aligned properly.

**Screenshots**
![Screenshot 2024-01-03 210831](https://github.com/PalisadoesFoundation/talawa-admin/assets/120639775/84f73f27-cb28-42fd-87ae-ca1185de4cf5)

I would like to work on this issue. Please assign it to me.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by KshitijTodkar48** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens. @rishav-jha-mech is leading this process for the Talawa Admin project
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
