### ISSUE TITLE
Talawa-admin undergoes continuous refreshing.

### ISSUE THREAD

**Issue by chandel-aman** [PalisadoesFoundation/talawa-admin#1370]
**Describe the bug**
The talawa-admin continuously refreshes when navigating from the login page to the organization list page. Notably:

- The issue persists even after server restarts and clearing browser cookies.
- Reproducible across different browsers.
- Token conflict with other applications triggers the problem.

**To Reproduce**
Referenced from [slack](https://thepalisadoes-dyb6419.slack.com/archives/CSWGQ70UQ/p1704291848636899)

**Expected behavior**
Talawa-admin should not refresh continuously.

**Actual behavior**
Talawa-admin undergoes continuous refreshing.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/118bba78-cc4d-4ff0-9556-4913afee4aee

**Additional Context**
This issue may be caused by token conflicts with other applications.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by chandel-aman** [comment]
@palisadoes Can I work on this issue?

**Comment by palisadoes** [comment]
1. I don't see this issue with my installation.
2. Is this the result of someone not following the installation instructions correctly on `develop`?

**Comment by chandel-aman** [comment]
This issue is not related to instructions in installation guide, but this is development related issue which occurs due to conflicts in key name stored in local storage.
When an application is locally run on same port say localhost:3000 and both the application stores data in local storage with same key name then the data is over written, here in talawa's case when token is changed in local storage it gives error as the user is not found but we have a token so the recurring refreshes.

**Comment by palisadoes** [comment]
1. So the source of the error is that two applications are running on the same port.
2. Therefore Talawa-Admin must fail to start if it detects this situation. That sounds like a better solution.

**Comment by chandel-aman** [comment]
1. As mentioned earlier this error is caused due to any change in the local storage data.

2. The change in data is caused when talawa -admin server is stopped without proper logout, and another application is started on same port on which talawa was running. And if the second application also stores the data in local storage and with same name then it alters the data stored by talawa-admin. And when talaw admin is started again on same port it gets error since the token data has been changed. But as we have token present, but since the token is not for a valid talawa user it starts a loop of trying to validate the user using token and getting an error of User not found.

3. This error is related to development environment and won't affect the production.

4. Though the temporary solution works by clearing the local storage for that domain and port, but it will occur everytime there is overwriting of data in local storage. And even clearing the local storage for that domain and port is difficult as the application refreshes continuously making it unable to clear the local storage.
-One has to stop the reloading by commenting out the
```
window.location.href = '/orglist'
```
when isLoggedIn is true, and then clear the local storage.
-Other temp solution is to run another application on the same port and then try clearing the local storage.

5. This can be handled efficiently by having two sets of keys for local storage data, one for development and other for production, or both could be same, where we can have some unique prefix added to the key for unique identification by talawa-admin.

**Comment by chandel-aman** [comment]
> 1. So the source of the error is that two applications are running on the same port.
> 
>     2. Therefore Talawa-Admin must fail to start if it detects this situation. That sounds like a better solution.

I'm sorry, it seems I've caused a confusion. I think we can not have two applications running on same port for same domain simultaneously, so Talawa-Admin won't run on the same port if it is already occupied. This issue arises from two applications which were running on same port, altering each other's the data stored in browser's local storage due to key conflict.

**Comment by palisadoes** [comment]
Would this be an issue with the API to Admin communication too?

**Comment by chandel-aman** [comment]
1. Indeed, implementing error handling for incorrect tokens in the talawa-api can enhance communication with the Admin. Currently, during user authenticity checks with jwt tokens, it might be beneficial to consider sending a more specific error message and code, rather than relying on the generic "User not found" error.

2. In this particular issue, where token overwriting caused problems and jwt verification threw an "Invalid algorithm used" error, it could be worth considering throwing a more relevant error specific to token verification failures instead of a "User not found" error.

3. Regarding the automatic forcible logout of Admin users, I'm not well-versed in this area. However, I'll look into whether there are methods to detect the running state of the server and potentially trigger an automatic logout when the server is stopped.

**Comment by palisadoes** [comment]
Taking action upon shutdown in a predictable way will be difficult because the app could stop due to a bug.

Forcing a known working state on startup would seem easier to implement

**Comment by KshitijTodkar48** [comment]
@palisadoes This is an issue even I faced, when I first set up the 'main' branch of talawa-admin locally, logged in as 'Superadmin' and after when I set up the 'develop' branch it started to refresh continuously. Initially I thought I messed up the setup procedure but no, it is a real issue. @chandel-aman, if you require any assistance, I'll be more than happy to help.

**Comment by chandel-aman** [comment]
> Taking action upon shutdown in a predictable way will be difficult because the app could stop due to a bug.
> 
> Forcing a known working state on startup would seem easier to implement
> 
> Please open a PR when ready and work with the assigned reviewers on defending the details of implementation

Thanks for the advice. I'll focus on ensuring a robust startup.
Planning to open a PR soon. Appreciate your input.

**Comment by chandel-aman** [comment]
> This is an issue even I faced, when I first set up the 'main' branch of talawa-admin locally, logged in as 'Superadmin' and after when I set up the 'develop' branch it started to refresh continuously. Initially I thought I messed up the setup procedure but no, it is a real issue. @chandel-aman, if you require any assistance, I'll be more than happy to help.

Thanks for sharing your experience. I'm curious if you encountered any specific error during this issue. Also, did you happen to identify how it relates to the problem discussed in the comments above? Your insights could be valuable in understanding and addressing the issue. Feel free to share any details, and I appreciate your willingness to help out!

**Comment by KshitijTodkar48** [comment]
> > This is an issue even I faced, when I first set up the 'main' branch of talawa-admin locally, logged in as 'Superadmin' and after when I set up the 'develop' branch it started to refresh continuously. Initially I thought I messed up the setup procedure but no, it is a real issue. @chandel-aman, if you require any assistance, I'll be more than happy to help.
> 
> Thanks for sharing your experience. I'm curious if you encountered any specific error during this issue. Also, did you happen to identify how it relates to the problem discussed in the comments above? Your insights could be valuable in understanding and addressing the issue. Feel free to share any details, and I appreciate your willingness to help out!

No, I didn't encounter any specific error, but as mentioned the app started to refresh continuously. And I couldn't figure out any reason to why it was happening apart from assuming that I might have messed up the setup procedure. I think you are correct, this is definitely related to auth token and altering in token-data.

**Comment by chandel-aman** [comment]
@palisadoes @rishav-jha-mech 
I made the required changes for this implementation, where I've used custom React hooks to perform operations on local storage. This ensures that data prefixing is done from a single place rather than implementing changes everywhere local storage is used. However, while the code is working correctly, I'm facing an issue with testing the hook. The current version of `@testing-library/react (11.1.0)` does not have `renderHook`, which is used for testing hooks in React.

**Comment by chandel-aman** [comment]
As discussed with @rishav-jha-mech, we agreed to update the react-testing-library library. However, a challenge arises as support for React 17 and below was dropped in [v13.0.0](https://github.com/testing-library/react-testing-library/releases/tag/v13.0.0), and the `renderHook` function was introduced in [v13.1.0](https://github.com/testing-library/react-testing-library/releases/tag/v13.1.0).

Alternatively, we could consider using [react-hooks-testing-library](https://github.com/testing-library/react-hooks-testing-library) for testing hooks, as it provides the `renderHook` functionality and currently works seamlessly with the version of React used in Talawa-Admin. Also, adding a library just to test hooks, which is not vastly used in Talawa-Admin, requires careful consideration.

I'd appreciate any suggestions on how to proceed in light of these considerations.

**Comment by chandel-aman** [comment]
I've attempted to test the code using the existing version of `react-testing-library (v11.1.0)`, and I've covered all the cases. The tests are functioning as expected, but the lines still appear as uncovered.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/539c4ef9-f9bc-49b2-9b28-3a96c2e491a1)

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/90d54dbb-4c2a-4a9d-926e-56666388069e)

**Comment by palisadoes** [comment]
1. @chandel-aman This is a real hardship. Please open a PR
2. @aashimawadhwa @rishav-jha-mech please comment

**Comment by palisadoes** [comment]
It's been over a week

**Comment by chandel-aman** [comment]
> It's been over a week

I apologize for the delay in opening the PR for this issue. I understand the urgency, and I want to assure you that I've resolved the problem. However, the changes required modifications in over 60 files, encompassing tests as well. Currently, over 20 tests are failing, and although I've addressed the failing tests for many files, there are still some remaining. Additionally, there has been a drop in test coverage of many files that I am actively working to mitigate.

**Comment by chandel-aman** [comment]
@palisadoes @rishav-jha-mech @aashimawadhwa 
As a potential fast resolution, we could consider applying the prefixing solely to the access token and refresh token. This approach would not impact the tests to the same extent and resolve the current issue promptly. However, it's important to note that this would mean other values stored in local storage might still be vulnerable to conflicts, potentially resulting in anomalies

**Comment by palisadoes** [comment]
> @palisadoes @rishav-jha-mech @aashimawadhwa As a potential fast resolution, we could consider applying the prefixing solely to the access token and refresh token. This approach would not impact the tests to the same extent and resolve the current issue promptly. However, it's important to note that this would mean other values stored in local storage might still be vulnerable to conflicts, potentially resulting in anomalies

@chandel-aman 

1. We need a long term solution, so we are willing to wait the extra time.
2. Can the problem be fixed temporarily if developers run Talawa Admin in incognito mode?

**Comment by chandel-aman** [comment]
> > @palisadoes @rishav-jha-mech @aashimawadhwa As a potential fast resolution, we could consider applying the prefixing solely to the access token and refresh token. This approach would not impact the tests to the same extent and resolve the current issue promptly. However, it's important to note that this would mean other values stored in local storage might still be vulnerable to conflicts, potentially resulting in anomalies
> 
> @chandel-aman
> 
>     1. We need a long term solution, so we are willing to wait the extra time.
> 
>     2. Can the problem be fixed temporarily if developers run Talawa Admin in incognito mode?

I apologize for the delay; I'll make the PR as soon as possible.
Unfortunately, this issue persists even when we run it in incognito mode. I tested it specifically in incognito, but it didn't work.

**Comment by palisadoes** [comment]
So it sounds like we'll need to test with a browser dedicated to Talawa Admin like Opera

**Comment by nitishkumar333** [comment]
@chandel-aman @palisadoes just using "npm run import:sample-data -- --format" fixes the issue, no idea why it does but I hope it will help in resolving the issue

**Comment by palisadoes** [comment]
@chandel-aman 

How's progress? It's causing real hardship and the solutions are complicated and don't always work
- https://thepalisadoes-dyb6419.slack.com/archives/CSWGQ70UQ/p1705471999945939

**Comment by chandel-aman** [comment]
> @chandel-aman
> 
> How's progress? It's causing real hardship and the solutions are complicated and don't always work
> 
>     * https://thepalisadoes-dyb6419.slack.com/archives/CSWGQ70UQ/p1705471999945939

Sorry for the late response; I was traveling. I've completed the implementation, but due to a lot of conflicts, I closed the PR. I'll resolve the conflicts and make the PR today itself.
