### ISSUE TITLE
Inconsistent Left Drawer Handling in Event Management Screen

### ISSUE THREAD

**Issue by akhilender-bongirwar** [PalisadoesFoundation/talawa-admin#1372]
**Describe the bug**
There is an inconsistency in the handling of the left drawer in the Event Management screen. Unlike other screens where the opening and closing of the left drawer are managed differently, the Event Management screen uses a hamburger icon for this purpose.

**To Reproduce**

1. Create an Event.
2. Navigate to the Event Dashboard by clicking on the created Event.
3. Observe the handling of the left drawer.

**Expected behavior**
The handling of the left drawer (open and close) should be consistent throughout the application.

**Actual behavior**
In the Event Management screen, the left drawer handling is inconsistent, using a hamburger icon.

**Video**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/68688bb0-ff2e-4d1c-aa08-5bb63c7c0207

**Additional details**
As shown in the video, the left drawer handling in the Event Management screen deviates from the expected consistency in the application.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
@Cioppolo14, please assign this issue to me.

**Comment by rishav-jha-mech** [comment]
This is a duplicate issue

https://github.com/PalisadoesFoundation/talawa-admin/issues/1240

I am closing this for now
