### ISSUE TITLE
Inconsistent Organisation Cards Manage Button   

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-admin#1374]
**Describe the bug**
There is an inconsistency in the Orglist Cards Manage Button. When creating a sample organization by following these steps:

**To Reproduce**

1. Click on Create Organisation
2. Click on Create Sample Organisation

**Expected behavior**
The Manage Button on Orglist Cards should maintain consistency throughout the UI.

**Actual behavior**
Some buttons contain only text, while the Manage Button on the sample organization created by clicking "Create Sample Organisation" includes icons, causing a break in the consistent UI.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/14222ef5-290d-486e-b5d9-5d1d35d8ff7c)
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/dec54edb-c377-44c1-88bb-d8f520f74b57)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by harshpreet14** [comment]
Please assign this issue to me. I would like to work on it.
