### ISSUE TITLE
Remove Requests Screen from Superadmin Panel

### ISSUE THREAD

**Issue by rishav-jha-mech** [PalisadoesFoundation/talawa-admin#1375]
**Is your feature request related to a problem? Please describe.**
The use of Requests screen on Superadmin panel is redundant because, it only shows the requests from the admins who have isAdminApproved attribute as false. Since the new flow goes like this, that a superadmin will create a normal user an admin, we no longer require this screen, so this screen needs to be removed along with its specific corresponding assets (Like icons).

![Dashboard _ REQUESTS](https://github.com/PalisadoesFoundation/talawa-admin/assets/76212518/382cdd54-2f6f-4206-9026-22b8070494d5)

**Describe the solution you'd like**
Remove this screen

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
NA

**Additional context**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by KshitijTodkar48** [comment]
Hey I want to work on this.

**Comment by rishav-jha-mech** [comment]
@KshitijTodkar48 I expect a PR for this issue soon

**Comment by KshitijTodkar48** [comment]
@rishav-jha-mech I have raised the PR. Please check it.

**Comment by KshitijTodkar48** [comment]
@palisadoes @rishav-jha-mech, this issue has been resolved, the PR has been merged. Please close this issue.
