### ISSUE TITLE
Refactor: Use the same Login/Register Component on User and Admin

### ISSUE THREAD

**Issue by rishav-jha-mech** [PalisadoesFoundation/talawa-admin#1377]
**Is your feature request related to a problem? Please describe.**
The user and admin currently have their respective Login and Register Components
The user portal's UI for Login and Register Component does not look similar to what we have in admin portal
This creates unnecessary dependency in our project where we always need to synchronise the UI and other elements for both the User portal and Admin portal.

**Describe the solution you'd like**
Keeping the logic intact for authentication of user and redirection to respective User Portal or Admin Panel, create a single Login/Register Component made from the base UI and code of Admin Panel's Login/Register Component.

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
NA

**Additional context**
Follow this PR, as it implements tab based navigation b/w User Login and Admin Login (However the components are different and they should be one), make sure that you are also aware of the current changes that are being made to Login/Register Component.

https://github.com/PalisadoesFoundation/talawa-admin/pull/1371

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by rishabhbizzle** [comment]
I would like to work on this

**Comment by rishabhbizzle** [comment]
Hey, @rishav-jha-mech should I start working on this once the above toggle feature PR gets merged??

**Comment by rishav-jha-mech** [comment]
Yeah sure

**Comment by rishav-jha-mech** [comment]
@rishabhbizzle 
https://github.com/PalisadoesFoundation/talawa-admin/pull/1376

This PR implements all the validations required to create a password, the same validation should be made on Login Page's Password field too, if someone is trying to login with an invalid password, instead of making an api call, show the user a toast notification, that their password is wrong.

**Comment by rishabhbizzle** [comment]
> @rishabhbizzle #1376
> 
> This PR implements all the validations required to create a password, the same validation should be made on Login Page's Password field too, if someone is trying to login with an invalid password, instead of making an api call, show the user a toast notification, that their password is wrong.

Okay

**Comment by rishabhbizzle** [comment]
@rishav-jha-mech I'm done with the changes please take a look at this video demonstrating the whole functionality. Let me know your thoughts.

https://github.com/PalisadoesFoundation/talawa-admin/assets/100997409/7057365a-91f1-4542-a3ff-3b0d3c66353b

**Comment by rishav-jha-mech** [comment]
Good work @rishabhbizzle !,

Just change these two things and open the PR

1. Register Page is redundant for the Admin, because the first registered user automatically becomes the superadmin, and he is the person who will make a normal user admin, so we don't require that, just remove the corresponding code for that.
2. When you are checking that the user has entered a wrong password, before calling the api, you are showing the user an alert, the message in that alert should be just incorrect password, no need to give an explanation why the inputted password is incorrect, also add minimum length of the password field to be 6.

**Comment by rishabhbizzle** [comment]
> Good work @rishabhbizzle !,
> 
> Just change these two things and open the PR
> 
> 1. Register Page is redundant for the Admin, because the first registered user automatically becomes the superadmin, and he is the person who will make a normal user admin, so we don't require that, just remove the corresponding code for that.
> 2. When you are checking that the user has entered a wrong password, before calling the api, you are showing the user an alert, the message in that alert should be just incorrect password, no need to give an explanation why the inputted password is incorrect, also add minimum length of the password field to be 6.

Okay I'll make these changes but I need your help regarding an issue please see the test coverage report in the above-closed PR for this issue @rishav-jha-mech .

**Comment by rishabhbizzle** [comment]
Please help me with this coverage issue @rishav-jha-mech 
https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/1402?src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=PalisadoesFoundation

**Comment by rishabhbizzle** [comment]
@rishav-jha-mech Please help

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue.
