### ISSUE TITLE
UI Redundancy with Close Options in Manage Features Modal after Org is Created in OrgList.tsx

### ISSUE THREAD

**Issue by harshpreet14** [PalisadoesFoundation/talawa-admin#1380]
**Describe the bug**
In the 'Manage Features' modal, users are presented with two options to close the modal: a clickable 'X' icon and a 'Cancel' button. This presents a UI redundancy that could potentially lead to user confusion. The issue is observable in the OrgList.tsx component on both the `develop` and `main` branches.

**To Reproduce**

1. Navigate to the organization list view on SuperAdmin Screen.
2. Click on 'Create New Organization', fill in the details, and proceed to create the organization.
3. After creation, the ‘Manage Features’ modal will appear.
4. Note the presence of two close options in the top-right corner: an 'X' icon and a 'Cancel' button.

**Expected behavior**
A single, intuitive method should be available for closing the modal to streamline the user experience.

**Actual behavior**
The modal features both an 'X' icon and a 'Cancel' button, offering two similar methods for closing which can be confusing.

**Screenshots**
<img width="960" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/114172812/213e1c4a-a3ef-4473-b714-2787b06b7e61">

**Additional details**
I'd like to inquire with the maintainers whether the presence of both close options was an intentional design choice. If one of them is to be removed to resolve this UI redundancy, could the maintainers advise which they would prefer? The 'X' icon offers a common modal dismissal pattern, while the 'Cancel' button provides explicit instruction, which might be more accessible. I would be more than happy to work on resolving this. Please assign this issue to me, and I will ensure to make the changes in accordance with the project's design principles.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@rishav-jha-mech @aashimawadhwa Your comments please

**Comment by rishav-jha-mech** [comment]
@harshpreet14 you are right, for this modal both cancel and cross icon is redundant, you can modify this modal and remove the cancel button.

The behaviour should be like this

1. On clicking cross button the modal should close
2. On clicking outside the modal the modal should close
3. On pressing escape key on keyboard the modal should close

Since this modal is related to creation, make sure the header of the modal is in Primary Colour and its text is in white colour,

**Comment by harshpreet14** [comment]
Thankyou, working on it. Would raise a PR by tonight.
