### ISSUE TITLE
Bug Report: Incorrect header and UI of create advertisement modal is not consistent

### ISSUE THREAD

**Issue by kanhaiya04** [PalisadoesFoundation/talawa-admin#1381]
**Describe the bug**
Header and UI of the modal is incorrect

**To Reproduce**

1. Open organization dashboard.
2. Open the advertisement page.
3. Click on Create advertisement button.

**Expected behavior**
Modal with Create advertisement header and proper UI should opened.

**Actual behavior**
Modal have incorrect header and designs is not consistent.

**Screenshots**
![Screenshot from 2024-01-06 02-20-33](https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/e61f82d5-dbd5-4d7f-a218-f0c01fb5eab6)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
@Cioppolo14, Please assign me.

**Comment by Cioppolo14** [comment]
We are not focused on smaller layout issues right now. I'm going to close this as unplanned for now.
