### ISSUE TITLE
Feature Request : Aligning Manage button for better navigation

### ISSUE THREAD

**Issue by varunsh17** [PalisadoesFoundation/talawa-admin#1383]
**Is your feature request related to a problem? Please describe.**
1. For the mobile view, the manage button is always at the right side of cards
2. The Organization name is also hiding behind the 'Manage' button whenever the Organisation name exceeds some length.

**Describe the solution you'd like**
Centre the Manage button for Mobile view and make adjustments for Organisation names for full visibility.

**Additional context**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/81704366/673242ef-b121-41d4-9773-b0d69b16570f)
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/81704366/8275d4e2-0606-4d47-8486-5bdc6036c99e)
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/81704366/de5267ff-f13a-425c-a439-d2a59bc22e6d)
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/81704366/a78ab012-8a55-4f8a-a9c8-e65b78be281a)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

### Would Like to work upon this feature/improvements.

**Comment by rishav-jha-mech** [comment]
I am closing this, it is a duplicate issue

https://github.com/PalisadoesFoundation/talawa-admin/issues/1374
