### ISSUE TITLE
[Bug] Error Triggered When Pressing "Enter" Instead of Clicking "Submit" Button When Adding Custom Field in Settings

### ISSUE THREAD

**Issue by karthxk07** [PalisadoesFoundation/talawa-admin#1395]
## Describe the bug
When attempting to add a custom field in the settings, an error occurs if the "Enter" key is pressed instead of clicking on the "Submit" button.

## To Reproduce

* Navigate to the settings section.
* Look for the option to add a custom field.
* Fill in the necessary details for the custom field.
* Instead of clicking on the "Submit" button, press the "Enter" key.

## Expected behavior
The custom field should be added successfully, regardless of whether the "Submit" button is clicked or the "Enter" key is pressed.

## Actual behavior
An error is triggered when the "Enter" key is pressed as the method of submission.

## Screenshots
[Screencast from 2024-01-07 09-10-37.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/16f57433-b83a-4e4a-bb30-a55d24b55ba7)

## Potential internship candidates
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by karthxk07** [comment]
Hello, can I work on this please.

**Comment by palisadoes** [comment]
@karthxk07 

We have a policy of unassigning contributors who close PRs without getting validation from our reviewer team. This is because:

1. We start looking for people to review PRs when you submit them. 
2. We often contact them and link to the PR. If the PR is closed the whole effort is wasted.
3. The historical thread of reviewer comments is broken when the work is spread across multiple PRs. The quality of our code is affected negatively.

Please be considerate of our volunteers' limited time and our desire to improve our code base.

**Comment by palisadoes** [comment]
This issue is open for other contributors

**Comment by ashutuptiwari** [comment]
@palisadoes I'd like to work on this :D

**Comment by AmitSharma512** [comment]
@palisadoes can I work on this ??

**Comment by ashutuptiwari** [comment]
Hey @Cioppolo14, i am getting this error while setting up the redis-server

**Comment by ashutuptiwari** [comment]
nvm that error was resolved

**Comment by ashutuptiwari** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/106370097/d90c1f71-8e58-472d-be33-aa401f7bf2b9)
can't see the custom fields section. How to access it?
The above is a ss from the SUPERADMIN user for the Angel Foundation(Sample database)
@Cioppolo14 @noman2002

**Comment by palisadoes** [comment]
Unassigning due to inactivity and/or no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue
