### ISSUE TITLE
Add Email Verification during Register(Sign-Up)

### ISSUE THREAD

**Issue by aarishshahmohsin** [PalisadoesFoundation/talawa-admin#1396]
**Is your feature request related to a problem? Please describe.**
There is currently no email verification in both the admin and user login. Email verification is crucial for signup as it authenticates users, enhances security, complies with regulations, aids communication, prevents spam, and enables password recovery. It ensures a reliable user base and positive user experience.

**Describe the solution you'd like**
Adding email verification to the register (sign up) process.

**Describe alternatives you've considered**
Some alternatives include phone number verification, two-factor authentication (2FA), or incorporating third-party identity providers (e.g., Google or Facebook login) for additional authentication layers. 

**Approach to be followed (optional)**

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Shubh152** [comment]
Please assign this issue to me

**Comment by nimishmedatwal** [comment]
@aarishshahmohsin I can work on this issue

**Comment by Cioppolo14** [comment]
@aarishshahmohsin Thank you for your submission. I am going to close this as not planned for now, as it is a complicated item. 

Setup needs to verify the SMTP email credentials configured in the .env configuration file. We will need a way to enable email verification in the Admin panel. We need to figure out what URL would be used for the confirmation and how will the API get access to it. How would that all be configured? This is especially important when testing on a laptop. 

These are considerations for the future. 

I am going to close as not planned for now.
