### ISSUE TITLE
Add a drop down for location field instead of plain input text while creating a new organization

### ISSUE THREAD

**Issue by Anvita0305** [PalisadoesFoundation/talawa-admin#1398]
**Is your feature request related to a problem? Please describe.**
While creating a new organization the user can enter anything in the location field. Currently, the user is expected to enter location in state, country format but it is not checked.

**Describe the solution you'd like**
Instead of plain input field, add two drop downs having list of all the locations (state, country). 

**Approach to be followed (optional)**
1. Add a drop down in place of input field.
2. Use "Country State City" API to get a list of states and countries.

**Additional context**
As shown in the ss the user can enter anything in the location field. 
![Screenshot from 2024-01-07 18-15-15](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/6b295aa3-deec-4a08-978a-7170303e4a6f)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Anvita0305** [comment]
I would like to work on this issue

**Comment by dz016** [comment]
hello, I would like to work on this issue.

**Comment by palisadoes** [comment]
1. @Anvita0305 Please change the title of the issue
2. @aashimawadhwa @rishav-jha-mech please take a look at this as there may be API schema implications if we want a similar structure to that of Users

**Comment by palisadoes** [comment]
1. Please work with @rishav-jha-mech and @aashimawadhwa on a design that matches our figma found here:
    1. https://docs.talawa.io/docs/design/ux/ux-design-system
1. Work with whoever is assigned this issue on the ensuring the functionality
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1650

**Comment by Anvita0305** [comment]
Hello, I have created a sample design including dropdowns.
https://www.figma.com/file/IXod5VDC6GTR4zg0hdNe1H/Location-dropdown-added?type=design&node-id=0%3A1&mode=design&t=mQoqjoZwOPtRPwrk-1 
Can someone please check and provide feedback? Thanks!

**Comment by varshith257** [comment]
@Anvita0305 It looks cool !! I think you can make the dropdown and select country options more interactive by following:

https://www.figma.com/community/file/1192432611766182122/alphabetical-arrangement-of-country-flags-ready-to-use-for-your-prototype

https://www.figma.com/community/file/978009302809014736/interactive-dropdown

**Comment by palisadoes** [comment]
@Anvita0305 The only field in Address that can easily use this methodology is the Country. Handling the different variations of state/department/province and city names depending on the country will make the scope of your idea too broad. Focus on Country and open a PR.

**Comment by palisadoes** [comment]
@Anvita0305 

1. Make your changes based on this PR. We need to coordinate merging.
2. When do you think your PR will be ready? You'll need to coordinate with @Anubhav-2003

**Comment by Anvita0305** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/a17b3b7b-704e-454d-bbee-7447b784fa5d)
Do I need to include all these fields in form as earlier you suggested that it would make the scope too broad? @palisadoes

**Comment by Anubhav-2003** [comment]
@Anvita0305 hello Anvita, actually I was working on the api for this issue. In my opinion the best approach is to call an api that retrieves all the details down to the street address as we see on may websites at the production level these days, and then pass them as mutations to the backend. That way the chances of errors minimizes a lot, and also looks a lot professional. 

That is just my approach. Feel free to tell if you have any other design pattern in mind, I am just suggesting.  Because unless some concrete data is sent from the client side, there are always chances of tangible errors occurring. 

Thank You.

**Comment by palisadoes** [comment]
@Anvita0305 

1. We need to close this issue. It's been over two weeks. Sadly we don't have the luxury of time for implementing a very straight forward suggestion where guidance was provided last week.
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1398#issuecomment-1890703448
1. This a good feature, but the delay is costing us time in implementing Organization Address support in the API. 
    1. A PR was created for this which we had to revert when your issues was discovered. 
        1. https://github.com/PalisadoesFoundation/talawa-api/pull/1666
    1. This API PR was created as part of a greater need to implement our new screen designs for Organization CRUD activities. This will require updates to several screens

This is not a reflection of worth of your idea. We need to get some key features implemented before GSoC period starts. Please continue participating in the community. We have many other issues planned in the coming days.
