### ISSUE TITLE
Add  a  "Delete Button" in the User Profile component.

### ISSUE THREAD

**Issue by Sejal1411** [PalisadoesFoundation/talawa-admin#1406]
Is your feature request related to a problem? Please describe.
There is no DELETE button in the user profile section. If the user wants to delete the existing profile, he/she can't. 

**Describe the solution you'd like**
Add a "delete" icon infront of the display image section.

**Additional context**
![Screenshot 2024-01-08 191728](https://github.com/PalisadoesFoundation/talawa-admin/assets/106868816/5cac1257-43ff-4150-967a-53b187574534)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sejal1411** [comment]
If this feature needs to be added. Pls assign!

**Comment by palisadoes** [comment]
Thanks, but this is not required at this time.
Closing
