### ISSUE TITLE
Bug Report: Dependencies upgrade

### ISSUE THREAD

**Issue by varunsh17** [PalisadoesFoundation/talawa-admin#1408]
**Describe the bug**

1. @testing-library/react                   ` 11.2.7  ->  14.1.2  `
2. @types/jest                              `26.0.24  ->  29.5.11`
3. @types/node                             `12.20.55  ->  20.10.5`
4. i18next                                  `21.10.0  ->  23.7.16`
5. redux                                     ` 4.2.1  ->  5.0.1`

The above packages also require updates in admin.

There are many good features provided by the new updated dependencies with better TS support.
We can use many great features this way and enhance the site security/testing with will overall improve performance to great extend.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship [Link](https://github.com/PalisadoesFoundation/talawa/issues/359)

**Comment by varunsh17** [comment]
**If there's need to upgrade any of the package, I would like to work upon them with our fellow contributor friends.**

**Comment by palisadoes** [comment]
1. There is no need for this. Our repo is automatically upgraded using dependabot. We create manual issues when dependabot fails
2. Closing
