### ISSUE TITLE
misaligned organization card for medium size screens

### ISSUE THREAD

**Issue by Ayushhgupta39** [PalisadoesFoundation/talawa-admin#1409]
**Describe the bug**
The Organization card component in the organizations list gets misaligned when viewed on medium sized screens (viewing on a 14-inch laptop screen)

**To Reproduce**

1. Login using admin credentials
2.
3.
4.

**Expected behavior**
The button inside the card should have proper spacing in all screen sizes.

**Actual behavior**
The button gets collapsed over the text.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/96309609/857ae98d-d9dc-4ed0-afde-7859c2a86665)

**Additional details**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

I would like to work on this issue. Please assign it to me.

**Comment by varunsh17** [comment]
I would like to work upon this.

**Comment by palisadoes** [comment]
This has already been fixed on the develop branch. Closing

**Comment by palisadoes** [comment]
Please read the `CONTRIBUTING.md` file in the root directory of the repo

**Comment by Ayushhgupta39** [comment]
Okay, thank you
