### ISSUE TITLE
Misalignment and unnecessary 'X' symbol in Create Organization 

### ISSUE THREAD

**Issue by aarishshahmohsin** [PalisadoesFoundation/talawa-admin#1410]
**Describe the bug**
The dialog after Creating and Organization after logging in as the Super Admin has 'X' icon that is unnecessary and the Cancel Button is Misaligned.

**To Reproduce**

1. Login as the Super Admin
2. Create an Organization
3. After the creation, the bug can be seen 

**Expected behavior**
Either only the Cancel button or the 'X' should appear

**Actual behavior**
Both of them appear and cause misalignment

**Screenshots**
![Screenshot_2024-01-08_23-05-28](https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/62d34753-2258-415e-ae6b-2a5ecc1dff91)

**Comment by Ayushhgupta39** [comment]
I want to work on this. Please assign

**Comment by Cioppolo14** [comment]
This is a duplicate issue, I am going to close.
