### ISSUE TITLE
The user login and the admin login alignment is inconsistent

### ISSUE THREAD

**Issue by aarishshahmohsin** [PalisadoesFoundation/talawa-admin#1411]
**Describe the bug**
The user login and the admin login alignment is inconsistent

**To Reproduce**

1. Go to the Talawa admin portal
2. Click on the USER section 
3. Click on the ADMIN section

**Expected behavior**
Both sections should have identical interfaces.

**Actual behavior**
different alignments in both of them

**Screenshots**
Admin Portal
![Screenshot from 2024-01-09 15-34-38](https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/6b8fe2fb-ca39-465a-b723-385cdb831af7)

User login Portal
![Screenshot from 2024-01-09 15-34-45](https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/f6ca2bdf-6115-4c19-a1dd-6dc135decfe0)

**Comment by Cioppolo14** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens. @rishav-jha-mech is leading this process for the Talawa Admin project
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing as unplanned for now.
