### ISSUE TITLE
Standardize The Left Drawer Minimization and Maximization Methodology Throughout the App

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1413]
**Is your feature request related to a problem? Please describe.**

1. There must be a single methodology to minimize and maximize the left drawer _**THROUGHOUT THE APP**_ no matter the size of the screen.
2. The hamburger icon methodology must be removed as it is not intuitive to use

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/04071cdc-5b94-4afa-bd36-0f9837e43f1f)

**Describe the solution you'd like**
1. The expectation is that this would be the sole methodology of expanding the drawer
    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/b96bf9f1-4293-42fe-97ef-246bb081300c)
1. And that this way would be the sole way to retract it.
   ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/c8061b3a-d08c-438e-81e7-64513f0a8b6d)

**Describe alternatives you've considered**
- None

**Approach to be followed (optional)**
- N/A

**Additional context**
1. Calendar Screen
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/6136d133-b173-4261-abf5-5ea7e228c362)
1. Event dashboard page - No hamburger methodology
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/4757b9e0-d585-498c-8e9c-f8e96b34f06e)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
I would like to work on it. Please assign me.
