### ISSUE TITLE
Eliminate the need to use `npm install --legacy-peer-deps` to run the app or tests

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1418]
**Is your feature request related to a problem? Please describe.**

There are several places in our documentation where we mention the need to use the command:

```
npm install --legacy-peer-deps
```

We want to only use the latest code and the use of this command does not meet this goal.

**Describe the solution you'd like**

1. Verify whether the use of this command is still necessary
2. If so, upgrade any packages and take any other action to eliminate the need while not affecting any code functionality
3. When the investigation and remediation is complete, remove all references to the command from our documentation

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
- Examples of documentation

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/ee248b97-270b-42d1-b5c2-617debcbe2e5)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by PoulavBhowmick03** [comment]
I would like to work on this. Please assign it to me

**Comment by palisadoes** [comment]
unassigning due to inactivity

**Comment by adi790uu** [comment]
Hey @palisadoes would like to solve this.

**Comment by adi790uu** [comment]
hey @palisadoes I am getting npm depracation warnings, I have used npm audit fix which has removed some vulnerabilites but there 21 vulnerablities still remaining changing, auditing those can be a breaking change.How should I proceed?

**Comment by palisadoes** [comment]
The scope of this issue is to `Eliminate the need to use npm install --legacy-peer-deps` by updating the `package.json`  file, not to eliminate deprecation warnings. That will need to be fixed another issue.
