### ISSUE TITLE
Mismatched Logout Button Color in Organization and Event Dashboards

### ISSUE THREAD

**Issue by akhilender-bongirwar** [PalisadoesFoundation/talawa-admin#1421]
**Describe the bug**
The logout button's color needs to be changed to red in both the organization dashboard page and the event dashboard, matching the color scheme present in the superadmin screen.

**To Reproduce**

1. Navigate to any organization dashboard
2. Check the color of the logout button
3. Navigate to Event Dashboard 
4. Check the color of logout button

**Expected behavior**
The logout button color should be consistent and set to red, matching the appearance in the superadmin screen.

**Actual behavior**
The logout button is not red in color on the organization dashboard and event dashboard screens.

**Screenshots**
- Organization Dashboard Screen
![logout1](https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/7f3cb812-04da-477d-8674-1db167e4297f)
- Event Dashboard Screen
![logout2](https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/24856b7e-bd7e-435e-8b3f-23ef309ffe2e)

**Additional details**
The expected color of the logout button should match the appearance in the superadmin screen.
![logout0](https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/15a0dd5f-5926-40de-83c0-7983c4774667)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
This is a good first issue, anyone can take it : )

**Comment by Cioppolo14** [comment]
Thank you for your submission. We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens. @rishav-jha-mech is leading this process for the Talawa Admin project
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
