### ISSUE TITLE
 Implement day view in calendar of event screen for both admin and user portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1422]
**Is your feature request related to a problem? Please describe.**
 Yes, there is a need for a multi-calendar view in both the admin and user portals, necessitating a solution to enhance the calendar functionality.

**Describe the solution you'd like**
 Implementation of a day view for the calendar, similar to the layout observed in Google Calendar. This would involve displaying events on a daily basis for improved user experience and functionality.

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
To address this requirement, we recommend incorporating a day view feature into the calendar, inspired by the user-friendly design of Google Calendar. This would involve presenting events in a clear and organized manner on a day-to-day basis.

**Additional context**
![Screenshot 2024-01-14 at 4 11 20 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/235b3f75-8bc0-4d9a-bd8f-e567facb19c6)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by nitishkumar333** [comment]
Hi @aashimawadhwa, I was thinking if a library like [fullcalender](https://fullcalendar.io/) can be asked, it will be convenient.

**Comment by karthxk07** [comment]
@aashimawadhwa Can i work on this issue please?

**Comment by karthxk07** [comment]
@aashimawadhwa Unlike in Google Calendar , Events on Talawa have both a start 'date' and end 'date'. So I am in dilemma if the event is to be showed on the start date view or the end date view.

**Comment by karthxk07** [comment]
@aashimawadhwa I have implemented the logic , i needed to add more CSS, does this look fine?
[Screencast from 2024-01-16 22-26-40.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/3757c40c-4c3e-4432-a469-ca581ac70802)

**Comment by karthxk07** [comment]
@palisadoes Sir, can i get leads on this, is this functioning ok?

> @aashimawadhwa I have implemented the logic , i just need to add more CSS, does this look fine?
> 
>  Screencast.from.2024-01-16.22-26-40.webm
