### ISSUE TITLE
GitHub Action Introspection Test Failure

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1429]
**Describe the bug**

The introspection GitHub Action checks are failing in our PRs

**To Reproduce**

1. Submit a PR
2. The introspection check fails 
 
This is because the git clone command defaults to cloning the default Talawa-API branch which is `main` instead of `develop`. We are therefore comparing `main` in one repo with `develop` in the other.

**Expected behavior**

1. The introspection check must clone Talawa API using the same branch as that target branch of the  Talawa Admin PR. This must be done automatically using GitHub action variables.
    1. If the PR is merging the contributor's code into the Talawa Admin `XXXXXXX` branch then the `XXXXXXX` branch must be automatically cloned in the GitHub action file.
1. It's been suggested in the comments link below that this command could be used:
```
git clone -b branch_name --single-branch REPO_NAME && ls -a
```
1. All other functionality must be maintained.
1. The above suggested change may require adjustment

**Actual behavior**

- See above

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/f8e2cb51-4778-4c7d-948e-5d1881453c72)

**Additional details**

Comments from other PRs and issues and failed GitHub actions
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1327#issuecomment-1891049919
1. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7521006577/job/20472163884

The GitHub Action File that needs editing
1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
I would love to work on this issue.
