### ISSUE TITLE
We need to implement character limits for input fields such as the title and information when creating an Posts.

### ISSUE THREAD

**Issue by gauravsingh94** [PalisadoesFoundation/talawa-admin#1431]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
We need to implement character limits for input fields such as the title and description when creating an organization.

**Describe the solution you'd like**
We have to apply limit on the input fields.
title : 100 words
information: 200 words

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

[Screencast from 2024-01-15 16-27-14.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/99260988/75503cf1-fcbd-4e90-880f-5da9972c8fe1)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by gauravsingh94** [comment]
Please assign this issue to me.

**Comment by Cioppolo14** [comment]
@gauravsingh94 Should the issue be for creating an organization or a post?

**Comment by gauravsingh94** [comment]
@Cioppolo14 for organizations.

**Comment by gauravsingh94** [comment]
Sor

> @gauravsingh94 Should the issue be for creating an organization or a post?

Sorry i uploaded the wrong video.

**Comment by Cioppolo14** [comment]
I thought this was resolved here: https://github.com/PalisadoesFoundation/talawa-admin/pull/1321 Can you clarify what I am missing?

**Comment by gauravsingh94** [comment]
> @gauravsingh94 I thought this was resolved here: #1321 Can you clarify what I am missing?

sorry i got confused because i am on mobile. 
i am talking about the posts one and the organization i have already fixed and both have the same issue.

**Comment by Cioppolo14** [comment]
@gauravsingh94 Ok, please edit the issue to clarify that and I will follow up.

**Comment by gauravsingh94** [comment]
@Cioppolo14  I have updated it please review it.

**Comment by Ajen07** [comment]
@Cioppolo14  please assign me this issue

**Comment by Cioppolo14** [comment]
@gauravsingh94 Thank you for updating it. I have one more request, I am going to close this one, as we'd like to address in the API.  Can you create this issue in the API repo?  Thank you!
