### ISSUE TITLE
Admin: GitHub Action - Failure when PRs made against the main branch

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1435]
**Is your feature request related to a problem? Please describe.**

We are having an increasing number of PRs made against the `main` branch when they should be made against the `develop` branch.

**Describe the solution you'd like**
1. We need a separate job added to the end of this GitHub action file that has no `needs: ` statement that tests to make sure that the target branch of the PR is `develop`. It must fail without affecting any of the other jobs in the file. The aim of this is to alert contributors of their likely mistake as in most cases we will be merging against `develop`
    - https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml
1. There must be messaging that explains that the job is testing whether the `develop` branch is being used.

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**

Sample PR made against `main`
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1363

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue. Please assign me.

**Comment by Veer0x1** [comment]
I would like to work on it.
