### ISSUE TITLE
Bug Report: Uncaught runtime errors when trying to open event dashboard

### ISSUE THREAD

**Issue by kanhaiya04** [PalisadoesFoundation/talawa-admin#1439]
**Describe the bug**
Got a runtime error when tried to open the event dashboard of an event.

**To Reproduce**

1. Open the organization dashboard.
2. Try to open the event dashboard of an event.

**Expected behavior**
The event dashboard should have opened up.

**Actual behavior**
Got a runtime error.

**Screenshots**
![Screenshot from 2024-01-16 02-31-43](https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/a92a30e6-11dc-4ee3-9dc3-467f7ed60831)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
I believe there have been changes made in the API part, but not in the frontend. Is this issue valid?
If yes, would like to work on it. @palisadoes .
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/a3fddeb3-2aac-4be5-8725-a087b5fee74e)

**Comment by palisadoes** [comment]
This should be closed as a duplicate. It's being handled here. 
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1346
