### ISSUE TITLE
Admin - Select organization on registration

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1440]
**Is your feature request related to a problem? Please describe.**

We are working on migrating the approval of requests to join organizations to a new Admin screen as outlined in this issue:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1416

Prior to this the process was:

1. New registrants joined the Community
1. Super Admins would approve the request
1. Approved registrants would login and select an organization

There were disadvantages to this approach:

1. This gave too much responsibility to the Super Admin who may not necessarily know people requesting to join in the way an Admin would. 
1. The two step process where the organization was selected post approval, could have been reduced to a simpler single step.

**Describe the solution you'd like**

_TALAWA API_

- This new requirement means that:
    1.  New `USER`s and `NON_USER`s will need to select an organization when registering so that the request can be directed to the correct organization's Admin screens.
    1. The setup script needs to create a single organization with a generic name on installation to facilitate registration to choice of at least one organization
    1. There can never be less than one organization in the DB
    1. The registration mutation must include organization ID information that issue https://github.com/PalisadoesFoundation/talawa-admin/issues/1416 will be able to detect.
    1. The current GitHub action pull request workflow needs to be updated so that the default organization is created successfully. This is in addition to the already existing test data importation test.
    1. The default organization creation mode mutation needs set the registration approval required flag to True to err on the side of caution.

_TALAWA MOBILE_
- This new requirement means that:
    1.  The user registration screen(s) will need to prompt for the organization and use the updated `Talawa API` registration mutation.
    1. The screen(s) design must follow the guidelines of our Design System found here:
        - https://docs.talawa.io/docs/design/ux/ux-design-system

_TALAWA ADMIN_
- This new requirement means that:
    1.  The user registration screen(s) will need to prompt for the organization and use the updated `Talawa API` registration mutation.
    1. The screen(s) design must follow the guidelines of our Design System found here:
        - https://docs.talawa.io/docs/design/ux/ux-design-system

_OTHER_

1. You will need to write tests for the updated code 
1. All other functionality must be maintained
1. We will need to add your Figma page designs to our official Figma document

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**
1. Related issues:
     1. https://github.com/PalisadoesFoundation/talawa-api/issues/1703
     3. https://github.com/PalisadoesFoundation/talawa/issues/2330
     4. https://github.com/PalisadoesFoundation/talawa-admin/issues/1440
1. User definitions in the DB schema
![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/4b8cb6bb-7b38-4dde-ad8d-136bb0877349)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by karthxk07** [comment]
@palisadoes Can i work on the Talawa-admin part for this, please?

**Comment by manishjha-04** [comment]
@palisadoes can i work on this?

**Comment by Cioppolo14** [comment]
@Sejal1411 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Dcode2100** [comment]
I would like to work on the talawa-admin part of this issue please assign it to me

**Comment by Sejal1411** [comment]
@Cioppolo14 I have unassigned myself from one of the issues. Can i get assigned to this issue?

**Comment by karthxk07** [comment]
@Sejal1411 i got this issue assigned already , maybe you can work on the api part for the same :eyes:

**Comment by Cioppolo14** [comment]
@Sejal1411 If this issue wasn't already assigned, at this point I could assign you.  In the future, if you are first to comment requesting an issue and you really want that issue, make sure you have less than 2 total issues for when I go to do assignments.  Thank you for understanding.

**Comment by palisadoes** [comment]
@karthxk07 

1. We will need to add your Figma page designs to our official Figma document

**Comment by palisadoes** [comment]
@karthxk07 

1. The blocking API PR for this issue has been merged. 
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1741
1. Please proceed with your work on this with urgency

**Comment by karthxk07** [comment]
@palisadoes I had been working on another issue and have been ignorant about this one. I will be immediately on this sir :+1:

**Comment by karthxk07** [comment]
@palisadoes Sir , in the select organization page, should the user have options to join multiple organizations or only one to start with. Can it be something like this where instead of topics we have organizations ?

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/ff32e50f-ff0a-4025-98be-05b7624738b3)

**Comment by palisadoes** [comment]
One

**Comment by karthxk07** [comment]
@palisadoes  Sir, Is something like this fine? 

https://www.figma.com/file/CCUKLqu8AYb3uBGQrXLJwE/Untitled?type=design&node-id=0%3A1&mode=design&t=5FkVhuIFeHKU7avH-1

**Comment by palisadoes** [comment]
How can you make the selection a part of the existing registration screen?

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/8c6ac019-5523-4705-92e4-022ad4524386)

**Comment by karthxk07** [comment]
@palisadoes Sir, maybe we can add a dropdown field to select from all available organisations?

**Comment by palisadoes** [comment]
OK

**Comment by palisadoes** [comment]
When do you think you'll be able to raise a PR for this?

**Comment by karthxk07** [comment]
@palisadoes Sir , I have completed the frontend part , I am working on implementing the logic. I will make the PR ASAP or latest by this weekend.

**Comment by karthxk07** [comment]
@palisadoes  Sir, Is this signUp mutation behavior expected, because in the above merged blocking PR , the expected output was somewhat different. How should I proceed about this?

[Screencast from 2024-02-08 22-29-31.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/fed5073a-519b-4897-b29a-658732206467)

**Comment by palisadoes** [comment]
If that case comment on the PR's issue with what you'd expect and let's reopen it to have the expected behavior

**Comment by palisadoes** [comment]
However, this PR was created to rectify a previously identified bug.
- https://github.com/PalisadoesFoundation/talawa-api/pull/1770

**Comment by karthxk07** [comment]
@palisadoes Sir, The PR is still pending to be merged, I will work on all the other things, and as soon as the blocking PR is merged I will implement the remaining functionality. :+1:

**Comment by aashimawadhwa** [comment]
Also @karthxk07  The organization selection drop down design looks good !

**Comment by karthxk07** [comment]
@aashimawadhwa Thank you :blush: , @palisadoes I have completed adding the other functionalities, does this look fine? Also as soon as the blocking PR is resolved , I will make the remaining changes :+1: . Should I open a pull request now or later 

[Screencast from 2024-02-21 22-27-21.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/21d9c1b7-2df3-4322-b1a1-38ee67d4796c)

**Comment by palisadoes** [comment]
Please work with @aashimawadhwa. Submit a PR when ready.

**Comment by Cioppolo14** [comment]
@karthxk07 Are you still working on this?

**Comment by karthxk07** [comment]
@Cioppolo14 Yes Ma'am , there is a blocking PR related to this issue.
It is currently under review to be merged 
I am ready with all the other changes , as soon as the blocking PR is merged i will start working on the remaining things and make a PR.

**Comment by palisadoes** [comment]
Unfortunately the blocking issue is still open

**Comment by palisadoes** [comment]
@karthxk07 

The API PR is now complete. You can proceed. This is could be showstopper issue for new registrations. Do you have time to complete this by the weekend?

- https://github.com/PalisadoesFoundation/talawa-api/issues/1703

**Comment by karthxk07** [comment]
@palisadoes That is good news sir. Unfortunately I have exams till the end of the week. But , most of the other work is done so, I can work modestly this week, get done with most work on weekend plus one two more days and make the PR ASAP.

**Comment by palisadoes** [comment]
Good luck with your exams. That comes first. Thanks for the update.

**Comment by karthxk07** [comment]
@palisadoes Yes sir. I have already fixed it locally . This issue will rise for not only the super admin but also for every user trying to register. I will push it up with all the changes.

**Comment by palisadoes** [comment]
The `userType` methodology was removed. The description of the new way can be found here:

- https://github.com/PalisadoesFoundation/talawa-api/issues/1711

**Comment by karthxk07** [comment]
[Screencast from 14-04-24 12:55:33 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/aaa1e825-f4a2-4e20-8d69-bcbda18c322a)

@palisadoes Sir , this is ready. Does this look fine?

**Comment by palisadoes** [comment]
Yes. Finally!

How does it work with a fresh installation where the `LAST_RESORT_SUPERADMIN_EMAIL` is set? Where the email address isn't one of the sample data users, for example

**Comment by karthxk07** [comment]
@palisadoes Sir , here is how it works for `LAST_RESORT_SUPERADMIN_EMAIL`. 

[
![Screenshot from 2024-04-15 19-15-51](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/c8e1430a-3ce2-4fe0-95cd-890f88e50f7f)
](url)

[Screencast from 15-04-24 07:16:02 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/40a528d8-7f0b-4ad2-871e-2de548767637)

**Comment by palisadoes** [comment]
Thanks. Please submit a PR
