### ISSUE TITLE
Implementing Functionality for the "View" Button on Advertisement Card

### ISSUE THREAD

**Issue by Vaishali054** [PalisadoesFoundation/talawa-admin#1446]
**Describe the bug**
The "View" button on the advertisement card is currently non-functional, and users are unable to access additional information such as startDate related to the advertised content. This issue is raised to propose the implementation of functionality for the "View" button to enhance user experience and provide a seamless interaction with the advertised content.

**To Reproduce**

1. Navigate to the advertisement card.
2. Observe the presence of the "View" button.
3. Click on the "View" button and note the lack of any response or functionality.

**Expected behavior**

- Implement a modal that appears upon clicking the "View" button.
- Ensure the modal design maintains consistency with other modals associated with Advertisement content

**Actual behavior**
- The "View" button is present on the advertisement card but does not perform any action when clicked.

**Screenshots**
![Screenshot 2023-12-09 152730](https://github.com/PalisadoesFoundation/talawa-admin/assets/100770875/7fd41eb4-6ebb-4d30-abd8-e2df1cfe3aaf)

**Additional details**
NA

**Comment by Vaishali054** [comment]
Can you please assign this to me.

**Comment by Cioppolo14** [comment]
Thank you for your submission.  This is a duplicate, as issue #1158 should address this.  The PR is still open right now.  I am going to close this one.

**Comment by Vaishali054** [comment]
@Cioppolo14 that issue is for adding media support for example a image in the advertisement. There is a view button in the card which does nothing as of now. It should show addition details about the advertisement which are not shown in the advertisement card.
