### ISSUE TITLE
Bug Report : getting multiple reload in develop branch

### ISSUE THREAD

**Issue by DIWAKARKASHYAP** [PalisadoesFoundation/talawa-admin#1454]
**Describe the bug**

When I run the develop branch of the Talawa Admin on my local system and simultaneously run the develop branch of the Talawa API using Docker, I experience multiple reloads on localhost:3000 
but the main branch is working perfect 

**To Reproduce**

1. run talawa api "develop" branch on docker
2. run talawa admin "develop" branch on localhost
3. do login 

**Expected behavior**
non stop reload

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/94478026/2c77daab-36e1-4a99-a4af-b0e989e09913

**Additional details**
i am using windows system

**Comment by AVtheking** [comment]
fetch the latest upstream of talawa api from the develop branch rebuild docker images ,this would resolve your issue
