### ISSUE TITLE
Admin: GitHub Action Required: Fail on detection of eslint-ignore statements

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1460]
**Is your feature request related to a problem? Please describe.**

The quality of our code is paramount to us. This includes:

1. Functionality
2. Consistency of coding style for improved readability
3. Following best practice coding standards

To achieve the last 2 points, we have been gradually increasing the linting rules enforced in the repository to maintain a consistency of our code style. We have implemented `githooks` to try to enforce this linting best practice.

Even so, we have seen contributors adding statements to ignore our linting rules.

**Describe the solution you'd like**

1. Remove the typescript linting ignore statements to reveal the original linting errors
1. Fix the causes of the linting errors without affecting functionality
1. Add a test to our pull request GitHub action file to fail if any files submitted in the PR:
    1. under the `src/` directory have ignore statements
    2. the `setup.ts` script in the root directory
1. There may be cases in test files where linting is required, but this should not be the case in non-test typescript files.
1. The GitHub action file is:
    1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

- Evidence of the use of the ignore statements in the `src/` directory

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/5f978018-cf45-47c4-b393-8ba3f5dbb0a3)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ParishiB** [comment]
@palisadoes assign me please

**Comment by Sauradip07** [comment]
@palisadoes please assign this issue to me

**Comment by takshakmudgal** [comment]
I'd really like to work on this issue, I haven't really been assigned to a issue lately and am really waiting to get my contributions in.

**Comment by Cioppolo14** [comment]
@takshakmudgal Please keep your eye on the issues! We will find you one.  Our policy is to assign the first person to ask who has less than 2 issues across the repos.  Thank you!

**Comment by Cioppolo14** [comment]
@ParishiB Are you still working on this?

**Comment by ParishiB** [comment]
yes , i am working on it. will close it soon

**Comment by palisadoes** [comment]
@ParishiB 

When do you think you'll be able to submit a PR for this? It's an important code quality issue that needs to be resolved.

**Comment by ParishiB** [comment]
yes , i am doing it , just facing issue with react indent , it is taking time fixng the lint v/s prettier issue.Any advice would be appreciated

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by techmannih** [comment]
I want to work on this issue. Assign me

**Comment by techmannih** [comment]
I want to work on this issue, assign me

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by aarishshahmohsin** [comment]
@palisadoes @Olatade please review this PR or close it.

**Comment by palisadoes** [comment]
@aarishshahmohsin Thanks for the reminder. It's been merged.
