### ISSUE TITLE
Admin - Add support for Action Items

### ISSUE THREAD

**Issue by meetulr** [PalisadoesFoundation/talawa-admin#1462]
**Is your feature request related to a problem? Please describe.**
Adding support for Action Items in talawa-admin.

**Describe the solution you'd like**
1. A screen for action item categories on the org leftDrawer, through which we could create, edit and view all the categories.
2. A screen for action items on the org leftDrawer, for similar crud functionalities. We could also add custom filter and search functionality for getting action items for a single category, assigned to a certain user, etc.
3. A screen on the event dashboard for action items associated with that event (as was previously the case for event projects). Here also, aside from the basic crud, we could add filter search functionality like the one described above.

**Additional context**
It's a companion issue for [this](https://github.com/PalisadoesFoundation/talawa-api/issues/1595) one in the api.

**Comment by meetulr** [comment]
.

**Comment by meetulr** [comment]
@palisadoes Please let me know if the solution I proposed is acceptable, and if anything else is required.

**Comment by palisadoes** [comment]
**Layout**

1. Action Item CRUD (Organization wide), your suggestion is OK
2. Action Item CRUD (Event specific), your suggestion is OK
3. Category CRUD should be on the organization settings page, however we are doing some redesigns for it that will cause merge conflicts. Your suggestion is OK, and when the redesign work is complete we can rearrange things

**Other**

1. Make sure your designs are in keeping with our design standards. The Figma file can be found here:
    - https://docs.talawa.io/docs/design/ux/ux-design-system
1. We'll need your Figma designs to be added to the project's when you are done

**Comment by palisadoes** [comment]
@rishav-jha-mech @aashimawadhwa  This is an issue to watch. There will be some design modifications required.

**Comment by meetulr** [comment]
> **Layout**
> 
> 1. Action Item CRUD (Organization wide), your suggestion is OK
> 2. Action Item CRUD (Event specific), your suggestion is OK
> 3. Category CRUD should be on the organization settings page, however we are doing some redesigns for it that will cause merge conflicts. Your suggestion is OK, and when the redesign work is complete we can rearrange things
> 
> **Other**
> 
> 1. Make sure your designs are in keeping with our design standards. The Figma file can be found here:
>    
>    * https://docs.talawa.io/docs/design/ux/ux-design-system
> 2. We'll need your Figma designs to be added to the project's when you are done

Could you please elaborate on that third point. Categories should be on the organization settings page? Could you direct me to the issue addressing the redesign that you mentioned.

Also, please assign me so that I can start working on it.
Thanks.

**Comment by palisadoes** [comment]
@meetulr 

1. We will need to add your Figma page designs to our official Figma document
2. Please plan for this

**Comment by palisadoes** [comment]
This is the issue that will be modifying the Organization Settings page. Categories are going to be organization wide. Moving the CRUD for this to the settings page leaves the main left drawer for the most commonly accessed features.

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1457

**Comment by meetulr** [comment]
Alright! Thank you.

**Comment by meetulr** [comment]
@aashimawadhwa @rishav-jha-mech Where do we want action items on the event dashboard:
![Screenshot (16)](https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/b7c85b58-10f9-4599-bcc1-2b3c7476e71b)

Shall I put them below the details:
![Screenshot (18)](https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/fc69b136-3f18-4825-887e-e536d65d494a)

I could add some designs in the details later.

**Comment by palisadoes** [comment]
Access the volunteers via a button below this one.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/a4bbda4c-5835-45b1-8d1a-532f4ef46a89)

**Comment by meetulr** [comment]
Could you please clarify😅.
We need a custom sort and filter functionality for action items right? (Like that in the organizations list).

Would it be ok to keep the search bar and Action Item cards directly below the event details? (To view all the action items, and perform operations on them directly from there).
Or do I move everything related to action items inside a modal, accessible from the left drawer under the event options?

**Comment by palisadoes** [comment]
Every button on this page is related to showing a different aspect of event detail. We need separate detail for action items.

What type of sorting and search were you planning on providing?

**Comment by meetulr** [comment]
So everything related to action items should be inside a modal, accessible from the left drawer in the event options (below the check in registrants)?

About the search, I was thinking we should be able to sort the action items (latest/oldest). And to filter them by categorieId or assigneeId, for better monitoring and management.

**Comment by palisadoes** [comment]
The API PR has been merged

- https://github.com/PalisadoesFoundation/talawa-api/pull/1648

**Comment by palisadoes** [comment]
> Yes, so everything related to action items should be inside a modal, accessible from the left drawer in the event options (below the check in registrants)?
> 
> About the search, I was thinking we should be able to sort the action items (latest/oldest). And, to be able to filter them, by actionItemCategoryId or assigneeId, for better monitoring and management.
> 
> Would that be ok?

I was thinking that for an event, the sort and search features won't be necessary as they would be rarely used. Then I realized that for general non-event activities there could be many items. 

Your suggestion is OK. Please proceed.

**Comment by palisadoes** [comment]
@meetulr 

Your PR for the API was much too large. Dozens of files and thousands of lines of code. This issue will need to be split into at least 3 separate PRs.

1. Category CRUD
1. Non-Event Action Item CRUD 
1. Event Action Item CRUD

**Comment by meetulr** [comment]
Yes, thank you! That would be more convenient for everyone.

**Comment by meetulr** [comment]
Where do I put the section for action item category on the settings page?
![orgSettings1](https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/a45eba32-1ec8-4e79-bf8f-8e9b31312f64)
![orgSettings2](https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/20d8c866-c4d3-4c10-b3f1-c7d5510fb992)

**Comment by palisadoes** [comment]
1. Consider a new left drawer for settings
    1. One button for general settings like what we have
    1. Another button for creating Action Item categories
1. Have a back arrow to get back to the main menu
1. The left drawer title must be `Settings`, not `Menu`

**Comment by meetulr** [comment]
Actually, I realize that the Action Item Categories have only it's name to show, having a whole screen to it wouldn't make sense.
The left drawer as it is now has access to all the screens, which is appropriate.
I could just add a section for action item categories.
![actionItemCategory](https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/711aa67c-5fe1-4bad-b550-84ea4ba3cc20)

I would add some designs around the categories and an update icon.

**Comment by palisadoes** [comment]
1. Yes, there will be new organization specific parameters to edit.
1. Yes, like the event details
1. In your original note you said that "Action Item Categories have only it's name to show". You could consider a misc button which goes to a screen with tabbed sections, like the user profile pages design in the Admin figma here. One tab would cover Action Item categories.
    1. https://docs.talawa.io/docs/design/ux/ux-design-system

**Comment by meetulr** [comment]
Yes, I like the tabs approach:

https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/9e2210d7-1233-4e61-b186-2619c28a84c6

It's just for the tabs sample. I would improve on the categories design. And add modals for create and edit functionalities.

Is that ok?

**Comment by palisadoes** [comment]
The tabs need to follow our design scheme with a white background, grey borders like in the Figma document.

- https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=307-212&mode=design&t=9mErk5fwtC7PLwY2-0

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/ee272536-5385-4b6e-b074-51723b4a6a31)

**Comment by meetulr** [comment]
Yes, I'll make the design adjustments. Thank you.

**Comment by palisadoes** [comment]
1. Make the corners rounder to match the Figma

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/36fd7423-8f62-4dcd-b7df-9393b15e4567)
1. Use the same background color as the Figma. It should already be in the CSS
2. Use the same color for the lines around the button as the Figma

**Comment by meetulr** [comment]
This is a demo:

https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/600bdbc8-3479-41ab-88b5-520140c80d00

**Comment by meetulr** [comment]
How's this design for action items (organization wide)
![Action Item](https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/68252c29-a10c-41d5-89a1-cfaea90e7d24)

**Comment by palisadoes** [comment]
1. One row per entry. It's more intuitive.
1. We are going to have to migrate to that approach across the app

**Comment by meetulr** [comment]
![actionItems](https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/d46f1401-2aa3-40cb-bb64-c67f49cdc226)

**Comment by palisadoes** [comment]
1. This looks OK. 
2. Can you provide the figma link to this designs so that we can add to our official one? We'll probably create issues to fine tune them later. 
    1. @aashimawadhwa @rishav-jha-mech take note

**Comment by meetulr** [comment]
@palisadoes part 2 and part 3 of this issue are still remaining.

**Comment by meetulr** [comment]
> 1. This looks OK.
> 2. Can you provide the figma link to this designs so that we can add to our official one? We'll probably create issues to fine tune them later.
>    
>    1. @aashimawadhwa @rishav-jha-mech take note

Oh and I'm sorry I missed this comment. I'm learning figma. I'll make the designs and share the links😅.

**Comment by palisadoes** [comment]
Did you see that your PR didn't pass the tests after merging?

**Comment by meetulr** [comment]
Ok, I'll have to look into it.

**Comment by meetulr** [comment]
A pr is up for review #1596, after this, one last pr would be required for event dashboard. Then the basic functionalities would be done.

**Comment by palisadoes** [comment]
> @palisadoes what will the home screen of the Event Dashboard ultimately display?
> 
> Currently, it only shows basic event information. Event-specific details, such as registrants, check-in registrants, action items, and event stats, are all accessed through the left drawer in the form of modals.

We'll be creating an issue for this via either @aashimawadhwa and/or @rishav-jha-mech

**Comment by meetulr** [comment]
> > @palisadoes what will the home screen of the Event Dashboard ultimately display?
> > Currently, it only shows basic event information. Event-specific details, such as registrants, check-in registrants, action items, and event stats, are all accessed through the left drawer in the form of modals.
> 
> We'll be creating an issue for this via either @aashimawadhwa and/or @rishav-jha-mech

I'm sorry, I don't understand😅. I wanted to know what the home screen would eventually show.
As all the event-specifics are currently in the left drawer.
Is it not planned yet?

**Comment by palisadoes** [comment]
1. Understood. Yes, the default screen is bare.
2. We're working on a design

**Comment by palisadoes** [comment]
We'll need issues for the API and Admin to cover action items for recurring events
