### ISSUE TITLE
Admin: Flawless Installation - Write Tests for `setup.ts`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1463]
**Is your feature request related to a problem? Please describe.**

1. We frequently add new configuration parameters to our code base.
2. The changes mean that the `setup.ts` file is always being modified.
3. Most PRs that modify this file introduce various types of failure.

PRs related to `setup.ts` require a high degree of manual verification by our reviewers and errors are frequent.

**Describe the solution you'd like**

Your job is to make the execution of the `setup.ts` file be:

1. foolproof
2. intuitive to use
3. easier and simpler to use

A tech novice or new contributor should be able to install the API without issue.

For the successful completion of this issue:

1. Write code to thoroughly test the `setup.ts` file without manually inputting responses to prompts, including:
    1.  all relevant functions, methods and classes where applicable.
    5. all user prompts
6. Ensure that running the tests is a part of our existing PR and Husky `git commit` workflows

This may mean making changes to the `setup.ts` file.

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

This issue may require the refactoring of this script file to make it:

1. Easier to test
4. Easier to maintain

Testing must verify that the:

1. Default values for input are correct:
     1. When a parameter is already configured 
     1. When a parameter is not configured 
1. Functionality when parameters are missing from the configuration is maintained
1. Sequencing of the prompts is maintained
1. Configuration parameters that rely on any external APIs (eg. database, mail) must be tested.
    1. The tests don't hang when testing these APIs whether or not the API connectivity is validated
1. Preexisting comments in the test configuration file are maintained when the final configuration is saved
1. Final configuration isn't saved until the last question is answered. In other words, hitting CTRL-C at any point before the last question will not affect the original configuration.
1. Wording of the prompts in all scenarios is unchanged
1. Previously correctly answered questions are not repeated
1. Correct values are echoed when:
    1. entered, 
    1. updated or 
    1. previously found in the configuration
1. Input of mandatory parameters cannot be avoided if they are not previously configured

Plus any other tests that could avoid failure based on the PR comments for the issues below.

Other items to consider include:

1. The test file must be located in the existing `tests/` directory
1. The test file has good readability
1. Not making any changes to files in the `.github` directory
1. Use the `setup.ts` file in the API repo as a guide on how the script functionality should work.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aialok** [comment]
I am already assigned three issue of which is one merge issue need to get closed, one is being in reviewed, If possible can I work on this issue.

**Comment by Sauradip07** [comment]
@palisadoes please assign this issue to me

**Comment by takshakmudgal** [comment]
Hii, I'd like to work on this issue.

**Comment by Cioppolo14** [comment]
@aialok Thank you for your honesty. There will be more issues to request once your issues are closed.  Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Sauradip07** [comment]
@palisadoes 
I Create a File `setup.test.ts` That Contained the test for the `setup.ts` file that ensure 
 thoroughly test the setup.ts file without manually inputting responses to prompts, including All relevant functions, methods, and classes.

```
//Import necessary packages
import inquirer from 'inquirer';
import {
  checkConnection,
  isValidUrl,
  askForTalawaApiUrl,
  askForCustomPort,
} from './setup.ts'; // replace 'your-file' with the actual file name

// Mock the fetch function globally
global.fetch = jest.fn();

describe('checkConnection', () => {
  it('returns false when the fetch fails', async () => {
    (fetch as jest.Mock).mockImplementationOnce(() =>
      Promise.reject('API is down')
    );
    const url = 'http://localhost:4000/graphql/';
    const result = await checkConnection(url);
    expect(result).toBe(false);
  });
});

describe('isValidUrl', () => {
  it('returns true for a valid URL', () => {
    const url = 'http://localhost:4000/graphql/';
    expect(isValidUrl(url)).toBe(true);
  });

  it('returns false for an invalid URL', () => {
    const url = 'not a valid URL';
    expect(isValidUrl(url)).toBe(false);
  });
});

jest.mock('inquirer');

describe('askForTalawaApiUrl', () => {
  it('returns the endpoint entered by the user', async () => {
    const mockEndpoint = 'http://localhost:4000/graphql/';
    (
      inquirer.prompt as jest.MockedFunction<typeof inquirer.prompt>
    ).mockResolvedValueOnce({ endpoint: mockEndpoint });
    const endpoint = await askForTalawaApiUrl();
    expect(endpoint).toBe(mockEndpoint);
  });
});

describe('askForCustomPort', () => {
  it('returns the port entered by the user', async () => {
    const mockPort = 4321;
    (
      inquirer.prompt as jest.MockedFunction<typeof inquirer.prompt>
    ).mockResolvedValueOnce({ customPort: mockPort });
    const port = await askForCustomPort();
    expect(port).toBe(mockPort);
  });
});
```
**Now**
**Need Help on how to add the file in** `Husky git commit workflows` **pre-commit hook**
Because there is no `tests/ `directory

Take a Look into the setup.test.ts file and Some changes I make on setup.ts file and also raised the PR is that changes are veracious ??

**Comment by palisadoes** [comment]
You don't need to ask permission to open a PR if you feel you have a working solution. 

Please take the initiative. It helps is all

**Comment by palisadoes** [comment]
You don't need to ask permission to open a PR if you feel you have a working solution. 

Please take the initiative. It helps us all.

Either update the githook or create a test directory or move the setup script to a husky compliant location. Make a professional decision which will be best for the repo in the long run. 

No other functionality must be changed.

**Comment by palisadoes** [comment]
Unassigning because the PR became dormant

**Comment by techmannih** [comment]
I want to work on this issue , assigned me

**Comment by adi790uu** [comment]
@Cioppolo14 I would like to work on this.

**Comment by adi790uu** [comment]
unassigned myself to work on another issue, anyone else can take this.

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by aarishshahmohsin** [comment]
@Cioppolo14 @palisadoes The setup.ts file does not exist in this repository. Does this issue demand making the setup.ts file or is this issue wrongly made in the admin repo?

**Comment by palisadoes** [comment]
It's in the `develop` branch where we do all our development.
