### ISSUE TITLE
Feature Request: Introduce Batch Post Deletion for Improved User Convenience

### ISSUE THREAD

**Issue by Shyam-Raghuwanshi** [PalisadoesFoundation/talawa-admin#1464]
**Describe the solution you'd like**

To enhance the user experience, I propose implementing a feature in the /orgpost section that allows users to delete multiple posts simultaneously. Currently, the process involves clicking on a post, followed by selecting the dots icon to access the delete option. Introducing a select option with radio buttons for each post would simplify this process, enabling users to choose multiple posts at once for deletion.

**Approach to be followed (optional)**

I suggest adding a radio button next to each post in the /orgpost section. When a user selects a radio button, a delete button will appear, allowing them to delete all the selected posts at once. This approach streamlines the deletion process and provides users with a more convenient and efficient way to manage their posts.

**Comment by Shyam-Raghuwanshi** [comment]
Please assign me this issue if this is a valid feature request!

**Comment by Cioppolo14** [comment]
@Shyam-Raghuwanshi This is a great feature, but we aren't ready for it yet.  I am going to close as unplanned for now. 

We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code are not acceptable under this policy.

Closing
