### ISSUE TITLE
bug: Pin post feature not working

### ISSUE THREAD

**Issue by Shyam-Raghuwanshi** [PalisadoesFoundation/talawa-admin#1465]
**Describe the bug**
the pin post feature not working

**To Reproduce**

1. go to the any post 
2. try to pin the post
3. 
https://www.loom.com/share/a2c499e35d9f4d3daf90864a1bcacacc?sid=113f61c1-f9e7-4f24-b7d9-9f9dd72eb706

**Comment by Shyam-Raghuwanshi** [comment]
Please assign me this issue

**Comment by noman2002** [comment]
@aashimawadhwa Is this a valid issue ? If yes, please have a look and assign.

**Comment by SanjeevKrSingh** [comment]
Hey @palisadoes  I want to work on this issue can you plz assign this issue to me.

**Comment by Abhinob-Bora** [comment]
@palisadoes please assign this issue to me if its still open

**Comment by Cioppolo14** [comment]
I am not having this issue. I am going to close this as unplanned.
