### ISSUE TITLE
[Enhancement] Replace default browser confirmation prompts with React Bootstrap prompts

### ISSUE THREAD

**Issue by DangaRanga** [PalisadoesFoundation/talawa-admin#147]
**Is your feature request related to a problem? Please describe.**
Currently browser native prompts are being used for confirming user input such as `window.confirm`, `window.alert` and `window.prompt`

**Describe the solution you'd like**
These should be replaced with React Bootstrap alternatives to improve the consistency in the UI of the application, whilst also improving the user experience.

Additionally the appropriate toast notifications should be utilized whenever an action is performed to ensure the user that the action was successful or unsuccessful.

**Approach to be followed (optional)**
For the confirmation prompts the approach outlined in [this article](https://morioh.com/p/d516ea000e8d) should be utilized.

For the toast notifications, react bootstrap has a native toast component which may be found [here](https://react-bootstrap.github.io/components/toasts/)

**Comment by karan2704** [comment]
Can I work on this issue?

**Comment by DangaRanga** [comment]
Sure thing!

**Comment by karan2704** [comment]
I'm getting a series of eslint / prettier errors when a change the code even slightly. How do I resolve this?
![err](https://user-images.githubusercontent.com/59208977/142715458-65847f3c-cef6-45cc-b128-fcb7945af45b.JPG)

**Comment by karan2704** [comment]
I have made some changes on the login/register page but I'm not able to register ... it shows 'failed to fetch' error. 
How do I resolve this?

**Comment by yasharth291** [comment]
just type ```yarn format```

**Comment by karan2704** [comment]
The issue persists
![reg](https://user-images.githubusercontent.com/59208977/142747682-2e0e0dc9-98a7-4f70-b58a-b26146162b28.JPG)

**Comment by karan2704** [comment]
Can someone help me out in understanding what the above issue is about? It seems like a problem with backend integration.

**Comment by yasharth291** [comment]
I think you haven't read the things provided in readme first you have to run the API locally on your computer then only you will be able to run it

**Comment by karan2704** [comment]
> I think you haven't read the things provided in readme first you have to run the API locally on your computer then only you will be able to run it @karan2704

Ok, I've set up the API .. working on the issue now. Thanks!

**Comment by karan2704** [comment]
Commits are to be made in the develop branch, right?

**Comment by palisadoes** [comment]
> Commits are to be made in the develop branch, right?

Yes

**Comment by palisadoes** [comment]
> Commits are to be made in the develop branch, right?

Yes
