### ISSUE TITLE
Feature Request: Having an editorconfig file

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-admin#1471]
**Is your feature request related to a problem? Please describe.**
We have been working on the linting aspect for quite some time, and having the workflows does detect it well at the time of merging PRs, but it would be helpful if the contributors get an overview of the changes they would be required to make while they code to resolve the other issues

**Describe the solution you'd like**
Creating an editorconfig would enable us to maintain and check for certain code practices on code editors such as VSCode, Atom and Sublime. Via this the code editors would help maintain a consistent coding style in the project so that new contributors can benefit and they can resolve any chances of GitHub workflow checks failing

**Approach to be followed**
A ".editorconfig" would be added, and the plugin can be added on the contributor's end so that the code aligns with the linting rules in their particular code editor

**Comment by takshakmudgal** [comment]
I'd like to work on this issue.
