### ISSUE TITLE
Updating the Contributing.md file

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-admin#1472]
**Is your feature request related to a problem? Please describe.**

This update aims to implement and enforce linting rules for all future submissions. The contributing.md file will include information on a plugin that contributors can install to automatically adhere to these rules. Additionally, the contributing.md file will provide a comprehensive list of the linting rules that must be followed.

**Describe the solution you'd like**

Detailed linting rules for contributors will be outlined in the contributing.md file. If contributors decide to install any plugins to help automate this process via their code editors, then the required steps would be provided for proper installation.

**Additional context**
Linting practices include enforcing consistent indentation and identifying unused variables, helping maintain code readability and identifying potential issues during development.

**Comment by Vankydwivedi** [comment]
Hey @Nitya-Pasrija 
I would like to work on this issue. Could you please assign this to me?

**Comment by Vankydwivedi** [comment]
working on it, please don't unassign
