### ISSUE TITLE
Encountering unexpected behavior when attempting to update Talawa Members' profiles.

### ISSUE THREAD

**Issue by Devesh326** [PalisadoesFoundation/talawa-admin#1473]
**Describe the bug**
1. When attempting to update a member's profile, it seems to require changing the email ID. If this behavior is by design then its fine, else it should also update when the member's name is modified.
2. Despite updating the profile, the member's actual profile remains unchanged. Instead, the user's (your) profile credentials are updated to match the member's credentials.

**To Reproduce**

1. Open Talawa Admin website
2. Click on your profile at the bottom left  
3. Click People Tab on the sidebar
4. Press users checkbox and update a members profile

**Expected behavior**
1. When a user updates a member's profile, the member's profile should get updated even if only the name is edited.
2. After updating the member's profile, it should not affect the user's (your) profile.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/76838871/b72d2ea3-a0d6-4eca-891e-51c2e12a7988

**Additional details**
@palisadoes @aashimawadhwa , If these issues are valid, can I work on it?

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Pranavx1** [comment]
Can i work on this?

**Comment by noman2002** [comment]
@Devesh326 Do you want to work on this issue ?

**Comment by Devesh326** [comment]
> @Devesh326 Do you want to work on this issue ?

Yess!

**Comment by rahulrangers** [comment]
i want to work on this issue.

**Comment by Devesh326** [comment]
Hey @noman2002,

This Bug also involves a few changes in the Talawa-Api. I've already implemented the necessary changes. Should I open a new issue in the Talawa API repository and create a corresponding pull request to address this issue?
