### ISSUE TITLE
Posts are not responisve

### ISSUE THREAD

**Issue by rahulrangers** [PalisadoesFoundation/talawa-admin#1474]
Describe the bug
when viewing post of an organization the model which appears on clicking the post is not responsive

To Reproduce

1.Open Talawa Admin website.
2.Enter an organization.
3.Click on the post.
4.Inspect and check the responsiveness.

Expected behavior
The expected behavior can be the image can be on the middle and text can be down
Actual behavior
Image is not clear

Screenshots

https://github.com/PalisadoesFoundation/talawa-admin/assets/127782777/05870f33-2465-4419-8612-b2a63879054b

**Comment by NayOoLwin5** [comment]
I would like to work on this

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code are not acceptable under this policy.

Closing
