### ISSUE TITLE
Update Talawa Admin to use a port other than 3000 

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1484]
**Describe the bug**
Talawa admin is continuously updating on `localhost:3000` as of now, we need a temporary fix for this, that suggests changing the port to some other local host port other than that of 3000. 

P.S: update the port in the root directory markdown files and possibly the GitHub actions and  src/ directories for references to the current default 3000

**Expected behavior**
1. Use port `4321` instead of `3000`.
1. Update the `setup.ts` script to prompt for the port, defaulting to the new default if the parameter isn't already configured. Save this as `.env` file variable to be used by the app
1. Update the `.env.samole` for with the new variable with the appropriate explicatory text.
1. Replace all references to port 3000 in code URLs with the new variable.
1. Update the markdown files in the root directory with the new default port.
1. Update the hard coded URLs in the typescript code base referring to `localhost` to use relative links where applicable. This is because the app may break if accessed from a remote system. Many of these URLs refer to port 3000
1. All existing tests must pass
1. No other functionality must be affected.

**Additional details**

- Note: This is an urgent issue please take it if you are willing to raise a PR immediately.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue.

**Comment by Keshav-0907** [comment]
Can you please assign this issue to me.

**Comment by palisadoes** [comment]
@akhilender-bongirwar 

The requirements have been updated with more details
