### ISSUE TITLE
Advertisement End date can be earlier than Start date

### ISSUE THREAD

**Issue by Keshav-0907** [PalisadoesFoundation/talawa-admin#1485]
**Describe the bug**
When creating a new advertisement, the end date of advertisement can be earlier than its start date.

**To Reproduce**

1. Go to : `orgads/id={some_id}`
2. Click on `Create new advertisement`
3. Now you can enter the end date of advertisement earlier than the start day

**Expected behavior**
The end date of advertisement should be equal to or greater than the start day of advertisement.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/91189139/a445602a-524e-4b3d-b970-edb56b6fce25

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Keshav-0907** [comment]
Hi, @aashimawadhwa @rishav-jha-mech @tasneemkoushar 

What are your suggestions on resolving this issue through validators on the frontend side, considering it's not related to security measures? Do you believe it's effective in reducing server load and providing faster feedback.

**Comment by Abhinob-Bora** [comment]
Hi @Keshav-0907,
I have seen the issue and by Implementing frontend validators can enhance user experience by providing quick feedback and potentially reduce server load by preventing unnecessary requests with invalid data to backend. However, it's crucial to maintain robust backend validation for security.

If security is not a big concern then the following validation logic of the code will be a efficient one -

The file location: talawa-admin\src\components\Advertisements\core\AdvertisementRegister\AdvertisementRegister.tsx and
customized handleRegister function within the AdvertisementRegister component -


const handleRegister = async (): Promise<void> => {
  try {
    console.log('At handle register', formState);

    // Check if the end date is greater than or equal to the start date
    if (formState.endDate < formState.startDate) {
      toast.error('End date must be greater than or equal to start date');
      return;
    }

    // If the validation passes, proceed with creating the advertisement
    const { data } = await create({
      variables: {
        orgId: currentOrg,
        name: formState.name as string,
        link: formState.link as string,
        type: formState.type as string,
        startDate: dayjs(formState.startDate).format('YYYY-MM-DD'),
        endDate: dayjs(formState.endDate).format('YYYY-MM-DD'),
      },
    });

    if (data) {
      toast.success('Advertisement created successfully');

      // Reload the page after 2 seconds
      setTimeout(() => {
        window.location.reload();
      }, 2000);
    }
  } catch (error) {
    console.log('Error occurred', error);
  }
};

**Comment by palisadoes** [comment]
We have a policy of unassigning contributors who close PRs without getting validation from our reviewer team. This is because:

1. We start looking for people to review PRs when you submit them. 
2. We often contact them and link to the PR. If the PR is closed the whole effort is wasted.
3. The historical thread of reviewer comments is broken when the work is spread across multiple PRs. The quality of our code is affected negatively.

Please be considerate of our volunteers' limited time and our desire to improve our code base.

This policy is stated as a pinned post in all our Talawa repositories. Our YouTube videos explain why this practice is not acceptable to our Community.

This is the fourth time you have done this and you were previously warned.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/f2b1626b-221b-4f6c-b40f-7b54bddfa8e5)

**Comment by AmitSharma512** [comment]
@palisadoes can i work on this issue ??

**Comment by palisadoes** [comment]
Reopening. This is not fixed
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1547

**Comment by MSVaibhav4141** [comment]
Hey I will like to work on this issue .. kindly assign it to me . Thanks :)

**Comment by AmitSharma512** [comment]
> Reopening. This is not fixed
> - https://github.com/PalisadoesFoundation/talawa-admin/issues/1547

@palisadoes sir, this issue is fixed as there was this bug while creating an advertisement only not while editing, error while editing an advertisement is not mentioned in this issue.
