### ISSUE TITLE
Bug Report: `Edit Profile` button should be removed while visiting another user's profile

### ISSUE THREAD

**Issue by pateldivyesh1323** [PalisadoesFoundation/talawa-admin#1489]
**Describe the bug**

When a user visits another user's profile on the admin panel, it can see `Edit Profile` button which leads to edit profile page where there prefilled information of the user it was visiting. Now the user thinks that it is editing another user's profile but it is actually editing his own profile with prefilled information of another user and when it submits it's profile gets updated with information of another user.

So, to solve this issue the `Edit profile` button should be removed while viewing another user's profile.

**To Reproduce**

1. Go to people
2. Visit any user
3. Click on `Edit profile`
4. Change email and some fields
5. Click on submit

**Expected behavior**

`Edit profile` button should be removed while viewing some other user's profile

**Actual behavior**

`Edit profile` button exists, which misleads the user.

**Video**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/da8befb7-c324-4869-bccc-e2ffb622fe8b

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pateldivyesh1323** [comment]
I would like to work on this, if this is a valid issue.

**Comment by Cioppolo14** [comment]
@pateldivyesh1323 have you tried this when you are logged in as a regular user and not a superadmin?

**Comment by pateldivyesh1323** [comment]
@Cioppolo14 Regular user cannot login into admin portal, but this issue exists for both admin and superadmin.

**Comment by Cioppolo14** [comment]
@pateldivyesh1323 Thank you for the correction! I am going to look into whether this is intentional or not. I will follow up.

**Comment by ssarkar551** [comment]
Hey @Cioppolo14 , if this issue is verified I would like to work on this

**Comment by Cioppolo14** [comment]
This is an intentional design feature, I am going to close this as unplanned.
