### ISSUE TITLE
Fix the introspection GitHub action tests

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1491]
**Is your feature request related to a problem? Please describe.**

1. Our introspection PR tests have been failing. This seems to be caused by code that references now deprecated Event and User task functionality.
2. Here is a recent example:
    1. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7639204501/job/20811725032?pr=1488

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/cfcbee91-fe5c-41b8-a2d3-b7761b069818)

**Describe the solution you'd like**

1. Update  the offending code to make the introspection tests
2. All existing tests must pass and must be valid tests of the code base
3. No other functionality must be affected

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Keshav-0907** [comment]
Can you please assign this issue to me.

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue. Please assign me.
