### ISSUE TITLE
Bug Report: User login requires refresh to fetch data

### ISSUE THREAD

**Issue by kanhaiya04** [PalisadoesFoundation/talawa-admin#1498]
**Describe the bug**
After logging as user we need to refresh the page to fetch the data.

**To Reproduce**

1. Login as user
2. You will notice no data is present, showing undefined.

**Expected behavior**
Data of the user should be fetched after successful login.

**Actual behavior**
Data is not fetched properly after the login, need to refresh to the page to get the data.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/179b8da7-6ba7-4624-bac3-a4108acd9f41

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
@palisadoes Please assign me this issue.

**Comment by Abhinob-Bora** [comment]
@Cioppolo14 @palisadoes please assign me this issue

**Comment by kanhaiya04** [comment]
After debugging the issue, I found the reason why this is happening.

**The header for the HTTP server is not set with the token after a successful login.**

`const httpLink = new HttpLink({
  uri: BACKEND_URL,
  headers: {
    authorization: 'Bearer ' + localStorage.getItem('token') || '',
  },
});`

This piece of code in **index.js** sets the header with the token initially as **null** when the client starts, but the header value dynamically does not change as the value changes in local storage.

That's why it needs a refresh after login to fetch the token from local storage and set the header.

**To fix this,** we have a few options:

First: Use the **setContext** function from **ApolloClient** to update the header dynamically as the value changes in local storage. It requires a few changes in how the ApolloClient is created in the index.js file.

Second: Pass the header along with the request. Example:
 `const {
    data: userData,
    error: errorUser,
  }: {
    data: InterfaceUserType | undefined;
    loading: boolean;
    error?: Error | undefined;
  } = useQuery(USER_ORGANIZATION_LIST, {
    variables: { id: localStorage.getItem('id') },
    context: {
      headers: { authorization: `Bearer ${localStorage.getItem('token')}` },
    },
  });`

**Third:**: use **window.location.replace('url')** after successful login to redirect the user.

@palisadoes  I'd appreciate your view on this.

**Comment by palisadoes** [comment]
Open a PR. Discuss your approach with the reviewers
