### ISSUE TITLE
Admin: Deprecate Organization `Location`. Replace with `Address` 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1502]
**Is your feature request related to a problem? Please describe.**

Organizations only have a `location`  field to describe their physical location

**Describe the solution you'd like**

1. Replace the `location` field with the existing `address` type
    1. `Location` is deprecated and must not be supported  
1. Repo actions required
    1. _Talawa API_
        1. Verify whether your repo is using `location` for organizations and remove support and replace it with `address` 
        1. Update the appropriate mutations and queries
    1. _Talawa Mobile_
        1. Verify whether your repo is using `location` for organizations and remove support and replace it with `address` 
        1. Update the appropriate mutations and queries used to interact with the API
    1. _Talawa Admin_
        1. Verify whether your repo is using `location` for organizations and remove support and replace it with `address` 
        1. Update the appropriate mutations and queries used to interact with the API
1. Create and update the appropriate tests to have valid test criteria
1. No other features must be affected by this change

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
1. Address Type
    ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/26c1390a-a302-4917-98c3-74069fe2176f)
1. Organization Type
    ![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/d9be1764-1979-4110-8a51-6de4eb334b20)

**Related Issues**

- https://github.com/PalisadoesFoundation/talawa-api/issues/1650
- https://github.com/PalisadoesFoundation/talawa/issues/2354
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1502

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by manishjha-04** [comment]
Can I work on this issue?

**Comment by lokeshwar777** [comment]
would like to work on this issue

**Comment by varshith257** [comment]
Would like to work on this issue

**Comment by Anubhav-2003** [comment]
@palisadoes Why is this issue again been created. I have already been assigned to this issue, and have already raised a PR for it. Here is the issue and the PR link. 

https://github.com/PalisadoesFoundation/talawa-admin/issues/1457

https://github.com/PalisadoesFoundation/talawa-admin/pull/1490

**Comment by palisadoes** [comment]
I'm tracking too many issues. Thanks. Closing
