### ISSUE TITLE
Event Creation Bug (UWI_SWEN3120_area_group1)

### ISSUE THREAD

**Issue by BNivia** [PalisadoesFoundation/talawa-admin#151]
**Describe the bug**
talawa-admin site crashes when attempting to add an event. 

**To Reproduce**

1. Log in to talawa-admin as a super admin
2. Navigate to organization
3. Navigate to events 
4. Select the option to add/create an event
5. Fill in event details
6. Press submit/enter

**Expected behavior**
The add event feature should add an event for that organization

**Actual behavior**
Upon pressing submit, the site crashes and the event was not added.

**Comment by SiddheshKukade** [comment]
Events are working fine now.
