### ISSUE TITLE
USER REDESIGN: redesign the sidenav for the talawa user portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1510]
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the sidenav for the user portal and follow a theme similar to the talawa admin portal.

**Additional context**

1. These are the two side navbars that require modifications.
   Please refer the figma file below : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1
1. Try to split this up into several smaller PRs, possibly 2-3 screens at a time. This will make the reviewing process much faster.

**Screenshots**
![Screenshot 2024-01-28 at 10 59 53 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/75577370-f3c3-422d-982b-de316cb07bbd) ![Screenshot 2024-01-28 at 11 00 02 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/9ac188ae-6b70-482c-aad6-47a91b829969)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by AnshulKahar2729** [comment]
Divyesh are you still working on it? I would like to help in it.

**Comment by AnshulKahar2729** [comment]
@aashimawadhwa let me know if I can contribute to it.

**Comment by Cioppolo14** [comment]
@AnshulKahar2729 Thank you for your interest! We aim to do only one issue per person as outlined in our CONTRIBUTING.md file.  If the currently assigned person, or a mentor feels that it is a big enough issue to be split, then that could be done. This is very important if you are planning on applying for an internship. With shared issues, it is difficult to know the level of contribution of each person.

**Comment by pateldivyesh1323** [comment]
@palisadoes @aashimawadhwa Where this button will take the user as there I cannot see profile page on user portal?

![Screenshot 2024-01-31 221606](https://github.com/PalisadoesFoundation/talawa-admin/assets/109150688/e4d4661c-4db9-4a84-ad3a-5bcb29c6fe1a)

**Comment by palisadoes** [comment]
The profile page edit will be in a subsequent issue. Let it remain.

**Comment by palisadoes** [comment]
@aashimawadhwa @rishav-jha-mech Please respond to this design question

**Comment by aashimawadhwa** [comment]
So the whole purpose is to stash the top navbar. We will have a sidenavbar which will render all the menu.
@pateldivyesh1323

**Comment by pateldivyesh1323** [comment]
@palisadoes The files were changed due to the `Update Documentation` commit which happens automatically. The original fix was changing around 35-40 files.  Now I will have to manually filter the original PR files and documentation files. It will take some time for me to make another PR.

**Comment by palisadoes** [comment]
Why did no other PRs have this issue?

I opened a test PR today against the same repo that didn't generate the files

**Comment by palisadoes** [comment]
This one opened today didn't generate them

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1596

**Comment by palisadoes** [comment]
Similarly this one too

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1592

**Comment by pateldivyesh1323** [comment]
@palisadoes Maybe it is fixed now, but some PR previously had this problem.
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1560
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1570

**Comment by palisadoes** [comment]
1. We were trying to fix the documentation workflow some weeks ago and some of the earlier PRs had the issue
1. I would submit again but find a way to not include the documentation branches. (If necessary) This may help
    1.  https://stackoverflow.com/questions/12481639/remove-file-from-latest-commit

**Comment by palisadoes** [comment]
1. I'm sorry about this. It has been troubling to me that so many people were inconvenienced by our efforts to get the documentation workflow working.
1. We should have used a separate branch for testing rather than develop. 
1. Part of the problem was that some GitHub features we considered only worked on the default branch and the YAML syntax was very sensitive. 
1. We now have a solution that hopefully works for all branches.

Automated documentation is really important for the repositories. It helps all developers when it's current. This was a priority for a small team of our volunteers.

We tried, we failed and we now think we have succeeded.

**Comment by pateldivyesh1323** [comment]
@palisadoes Your dedication towards the community is truly admirable. I have raised another PR please take a look.

**Comment by palisadoes** [comment]
@pateldivyesh1323 

Given the difficulties of the most recent PR related to this issue, are you still willing to work on this issue or should we assign someone else?

**Comment by pateldivyesh1323** [comment]
@palisadoes Please assign it to someone else,  they can take reference of the closed PR.

**Comment by palisadoes** [comment]
1. Whoever gets assigned to this issue should try to split it up into several smaller PRs, possibly 2-3 screens at a time.
2. This will make the reviewing process much faster

**Comment by karthxk07** [comment]
@palisadoes @aashimawadhwa Can I work on this issue ?

**Comment by palisadoes** [comment]
@karthxk07 

Do you have any concerns about this? I ask because the issue has been open for 6 weeks with multiple assignees and many aborted closed PRs. This is a defining feature in the user portal that will make it closely resemble the Admin screens which have a superior UI/UX. It is important for user acceptance.

**Comment by palisadoes** [comment]
@karthxk07 

Please respond. We'll need to reassign otherwise

**Comment by karthxk07** [comment]
@palisadoes Sorry sir , due to some work i wasn't able to reply to the message. 

I have been working on the issue. Half of the work is done. The sidebar on the main screen is complete, only sidebar for organisation dashboard is remaining. I'll post the screenshots soon.

**Comment by karthxk07** [comment]
@palisadoes @aashimawadhwa Is this collapse action ok?

[Screencast from 2024-03-17 20-45-29.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/1606b36b-fcbb-4715-9d11-bd2369d799ac)

I still need to get done with the designing part inside the navbar. I will complete that soon.

However, I have found that the design architecture in the user web portal is not proper. Each page is hard coded, which could have been avoided by having a fixed layout. This forces me to add hard coded sidebar logic for every page(which might not be the efficient way). Redesigning the whole layout would be out of scope for this PR. Maybe a new issue can be opened to re-implement a efficient design architecture. I will take this issue up there.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/ce341c9e-4c03-4df8-96e4-d9e31569a600)


![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/973f9c19-13d7-4cd8-b176-ca2da3aca011)

**Comment by palisadoes** [comment]
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/27/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by palisadoes** [comment]
1. The collapse action is OK
2. Please create an issue to fix the hard coding. There is an issue for the sidenav already

**Comment by karthxk07** [comment]
@palisadoes Sir, Most of the work is complete. Here is how it looks. I just need to write the test. I will make the PR asap.

[Screencast from 2024-03-24 23-19-01.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/109301536/bc1ca342-41c2-4eec-9f17-a3b59c72210f)

Following the PR i will create the issue for the layout issue.

**Comment by palisadoes** [comment]
It's a big improvement. Thanks for the effort. The improvements in the repo have been remarkable in the past 12 months.

**Comment by karthxk07** [comment]
@palisadoes Sir, It is always a pleasure helping. Hoping to get my proposal for GSOC accepted, so that I can contribute more. :blush:

**Comment by palisadoes** [comment]
Look at this issue for guidance. The should be no scroll bar, nor boxes around the cards. There are other things too

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1612

**Comment by palisadoes** [comment]
> @palisadoes Sir, It is always a pleasure helping. Hoping to get my proposal for GSOC accepted, so that I can contribute more. 😊

I hope for the best with all applicants. Work with the mentors, they are your window into improvement.

**Comment by karthxk07** [comment]
@palisadoes Sir,  writing tests has been giving problems. I am working on it nevertheless. Also , I will pull the latest pr and reuse the admin sidebar styles on the user sidebar , that should be easy.

**Comment by palisadoes** [comment]
Good luck with your exams. That comes first. Thanks for the update.

**Comment by Cioppolo14** [comment]
@karthxk07 Are you working on this?

**Comment by karthxk07** [comment]
@Cioppolo14 I surely am working on this. But it might take me time. But In Organization's interest, I think I should give up on this issue, and let someone else take it up. I should not keep it hanging any longer, and let somebody else complete the remaining work fast.

**Comment by pranshugupta54** [comment]
From the previous screen recording, it looks like you've finished working on the design and only writing tests is left. Maybe you can make a PR for the design and we can cover the tests independently (I can work on it).

**Comment by palisadoes** [comment]
@karthxk07 Please submit a PR and share your repo with others so that others can contribute to get this implemented. We have done this before with positive results.

**Comment by palisadoes** [comment]
That's unfortunate. I'll unassign you and see whether anyone else is willing to work on it. Thanks for letting us know and pass by again to assist with issues when you have the time.

**Comment by disha1202** [comment]
Hi
I would like to work on this

**Comment by duplixx** [comment]
@indresh149 I can work on this
