### ISSUE TITLE
USER REDESIGN: redesign the organization screen for the talawa user portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1511]
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the organizations screen for the user portal and follow a theme similar to the talawa admin portal.

**Screenshots**
- Attaching the screenshots for reference.
current situation :
![Screenshot 2024-01-28 at 11 07 52 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/f89376fb-b5c3-4fbb-9dce-688b0313fb52)
Desired Result:
 ![Screenshot 2024-01-28 at 11 05 48 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/686480bc-6da2-40f6-8f64-d39e22ab8b7d)

   Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**_Related issue_** : #1510 (sidenavbar is covered in this issue)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Hi, 
I would like to work on this

**Comment by takshakmudgal** [comment]
I'd like to work on this issue.

**Comment by aashimawadhwa** [comment]
@disha1202 assigned 👍🏼

**Comment by palisadoes** [comment]
@aashimawadhwa @disha1202 

The design will need an update:
1. In the User portal the user will want to `join` the organization, not `manage` it. 
2. The tiles should therefore have some way of indicating whether the user has already joined or not.

**Comment by AnshulKahar2729** [comment]
I'd like to work on this issue. Any updates?

**Comment by Cioppolo14** [comment]
@AnshulKahar2729 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by disha1202** [comment]
Hi @palisadoes  @aashimawadhwa 

Here's the design for organization screen for user portal

<img width="817" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/78ab7cf4-116d-41a2-8933-74b00e582b04">

Please take a look.

**Comment by palisadoes** [comment]
1. This is OK
2. Submit a PR when ready

**Comment by disha1202** [comment]
> * This is OK
> * Submit a PR when ready

Sure, I'll create a PR soon.

**Comment by palisadoes** [comment]
@disha1202 
1. How will you handle the case where a person has requested to join an organization but it hasn't yet been approved? What API modifications would be required for this?

**Comment by disha1202** [comment]
> @disha1202
> 
> 1. How will you handle the case where a person has requested to join an organization but it hasn't yet been approved? What API modifications would be required for this?

As per my observation, 
1. There are two types of organisations, one which requires the user to register and other one does not. The organisations that does not requires the user to register have the `userRegistrationRequired` flag defined as `False`.

2. For organisations with `userRegistrationRequired` flag defined as `True` the user needs to be approved by the `ADMIN` of the organisations. 

3. When a new user registers they are supposed to select an organization to join, if the organization that the user wants to join requires users to be approved then a request is sent to the `ADMIN` of the organization. 
If the user does not selects any organization then they are made to join the default organization and a request is sent to the `ADMIN` of the default organization.

4. When an admin approves a user the `adminApproved` flag is set to `True` and the organisationId is appended to the `joinedOrganizations` Array. 
 
As shown in the sample users data below
<img width="665" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/072663e5-f4dd-41d7-b3a4-d3863d012d5f">

Although it will be difficult to manage the state of multiple organisations with a single `adminApproved` flag. 
Instead it should be something similar to 

` joinedOrganizations: [ 
  { organizationId: '6537904485008f171cf29924', status: 'pending'},
  { organizationId: '6537904485008f171cf29924', status: 'approved'},
   { organizationId: '6537904485008f171cf29924', status: 'rejected'},
]`

Please let me know if I am missing something or misunderstood anything.

**Comment by palisadoes** [comment]
Thanks,

How will you handle the case where the:
1. approval is pending?
1. user wants to withdraw their join request?

Does the API support providing the necessary queries and mutations for this?

**Comment by palisadoes** [comment]
Regarding this:
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1511#issuecomment-1921527633

Yes, this will need to be done. The registration process will benefit greatly.

```
joinedOrganizations: [ { organizationId: '6537904485008f171cf29924', status: 'pending'}, { organizationId: '6537904485008f171cf29924', status: 'approved'}, { organizationId: '6537904485008f171cf29924', status: 'rejected'}]
```

1. You should open an issue in the API describing what you want in detail.
2. Ask to be assigned if necessary.

**Comment by disha1202** [comment]
> Regarding this:
> 
> * [USER REDESIGN: redesign the organization screen for the talawa user portal #1511 (comment)](https://github.com/PalisadoesFoundation/talawa-admin/issues/1511#issuecomment-1921527633)
> 
> Yes, this will need to be done. The registration process will benefit greatly.
> 
> ```
> joinedOrganizations: [ 
>   { organizationId: '6537904485008f171cf29924', status: 'pending'}, 
>   { organizationId: '6537904485008f171cf29924', status: 'approved'}, 
>   { organizationId: '6537904485008f171cf29924', status: 'rejected'}
> ]
> ```
> 
>  1. You should open an issue in the API describing what you want in detail.
> 2. Ask to be assigned if necessary.

Sure I'll create an issue in Tarawa API and also share the updated designs to handle pending state and option to withdraw request.

**Comment by Cioppolo14** [comment]
@disha1202 Are you working on this?

**Comment by disha1202** [comment]
> @disha1202 Are you working on this? 

Yes I'm working on it

**Comment by disha1202** [comment]
Hi 
Please find the updated design
<img width="949" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/6332dea1-8131-4a7b-a477-7acefd1e37db">

**Comment by disha1202** [comment]
> Regarding this:
> 
> * [USER REDESIGN: redesign the organization screen for the talawa user portal #1511 (comment)](https://github.com/PalisadoesFoundation/talawa-admin/issues/1511#issuecomment-1921527633)
> 
> Yes, this will need to be done. The registration process will benefit greatly.
> 
> ```
> joinedOrganizations: [ 
>   { organizationId: '6537904485008f171cf29924', status: 'pending'}, 
>   { organizationId: '6537904485008f171cf29924', status: 'approved'}, 
>   { organizationId: '6537904485008f171cf29924', status: 'rejected'}
> ]
> ```
> 
>  1. You should open an issue in the API describing what you want in detail.
> 2. Ask to be assigned if necessary.

@palisadoes 
We might not require this. We already have `membershipRequests` in user schema which will provide the status of the requests. 

Also, I came across [this](https://github.com/PalisadoesFoundation/talawa-api/pull/1643#issuecomment-1879947274) comment which states that we have removed support for `privateOrganizations`.

[`joinPublicOrganization`](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/src/resolvers/Mutation/joinPublicOrganization.ts) mutation which throws error if the `userRegistrationRequired` flag is `true` does not makes sense.

It should be updated to `joinOrganization` mutation which which creates a `membershipRequest` with `ACTIVE` status if `userRegistrationRequired` flag is `true` else works as is.

**Comment by palisadoes** [comment]
1. Take a look at this PR. It may answer your questions. If not, create an issue to implement your suggestion.
    1. https://github.com/PalisadoesFoundation/talawa-api/pull/1770
1. Yes, `adminApproved` should be removed

**Comment by palisadoes** [comment]
1. My mistake on the PR above.
2. Yes, please open an issue to fix the expected behavior

**Comment by disha1202** [comment]
> Hi Here is the updated design
> 
> @aashimawadhwa @rishav-jha-mech Please take a look
> 
> <img alt="image" width="948" src="https://private-user-images.githubusercontent.com/58461801/305404143-59c7d769-0f12-441b-87d9-04b8d5a04b2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MDgxMzQsIm5iZiI6MTcwODUwNzgzNCwicGF0aCI6Ii81ODQ2MTgwMS8zMDU0MDQxNDMtNTljN2Q3NjktMGYxMi00NDFiLTg3ZDktMDRiOGQ1YTA0YjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA5MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZTY4Yjk3NGFlNGVkNmEzOTc4NWU4NjEyZjdkYTBiOGJhYzFiMWZlMWRiNTA5MWI3OWFlYmVlMmUxNmQ1OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WEVUj0Rlr58a4JfZTZ9KNbdrmTNBi974KhTFl4fAzx4">

@aashimawadhwa @rishav-jha-mech 
Any update on this?

**Comment by aashimawadhwa** [comment]
@disha can you make buttons like this?

![Screenshot 2024-02-28 at 11 45 18 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/f77ac8e8-eac5-4d0d-a7da-933a8eef6025)

**Comment by disha1202** [comment]
> @Disha can you make buttons like this?
> 
> ![Screenshot 2024-02-28 at 11 45 18 PM](https://private-user-images.githubusercontent.com/73706697/308667583-f77ac8e8-eac5-4d0d-a7da-933a8eef6025.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyOTIxNTQsIm5iZiI6MTcwOTI5MTg1NCwicGF0aCI6Ii83MzcwNjY5Ny8zMDg2Njc1ODMtZjc3YWM4ZTgtZWFjNS00ZDBkLWE3ZGEtOTMzYThlZWY2MDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDExMTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MjEyNjc0MDZiZmU4OGExNTY4MTBmNjJhNmE0NGVhMDMxOTU3NzEwOTdhY2NhNTI5NTQxM2ZjNzk3MTk5YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yBnwCjhVnbbMgjODVAmfoteam6KHm-Tx4c9OZV8Pst8)

@aashimawadhwa Updated the buttons
<img width="1440" alt="Screenshot 2024-03-01 at 2 24 58 AM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/52ce166c-5453-445a-b29f-21d7d4cad127">
