### ISSUE TITLE
In Code Documentation - SWEN3120Group1

### ISSUE THREAD

**Issue by naomitheqa** [PalisadoesFoundation/talawa-admin#152]
**Describe the bug**
No identified in code documentation for the components  which outlines their behavior, documentation on any functions it may contain and so on.

**Comment by yasharth291** [comment]
Is this issue still active @BNivia

**Comment by reachaadrika** [comment]
@yasharth291  Is @BNivia  Working on this  issue ?

**Comment by reachaadrika** [comment]
@yasharth291  Is @BNivia Working on this issue ?

**Comment by palisadoes** [comment]
@BNivia I'm going to allocate this to someone else if you are not working on it.
