### ISSUE TITLE
GitHub Action: Fix `authorized-changes-detection`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1526]
**Is your feature request related to a problem? Please describe.**

1. We have a GitHub action file `authorized-changes-detection.yml` that, during pull requests, detects when sensitive files are modified and exits with an error.
    1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/authorized-changes-detection.yml
1. Unfortunately, as seen in the example PR  below, it does not mention the file(s) that is modifed. This would be very helpful
   1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1488

**Describe the solution you'd like**

1. Migrate the functionality of the `authorized-changes-detection.yml` file to:
    1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml
1. The action must:
    1.  Identify when one or more configured directories and files are modified during a PR
    2. List the file(s) in this list that were modified
    3. Exit with failure code.
1. The configuration of the list of sensitive files and directories must be done only once in the file. 
1. Do not use the `paths:` statement. It was suitable for a standalone file, but not for `pull-requests.yml` where other jobs run
1. The `authorized-changes-detection.yml` file must be deleted.
1. The new action must not depend on any other job in the YAML file.

**Describe alternatives you've considered**

We think that this GitHub action could be used
- https://github.com/tj-actions/changed-files

**Approach to be followed (optional)**

- See above

**Additional context**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
@palisadoes 
i would love to work on this

**Comment by duplixx** [comment]
Hi @palisadoes, I tried running the workflow on the forked repo. It seems that the paths are not correct.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/1eeccd01-e8cf-4c03-87cd-1fc4a16a4b41)

**Comment by AdityaRaimec22** [comment]
@palisadoes can I get assigned to this issue.

**Comment by palisadoes** [comment]
@duplixx 

1. The action currently works correctly in all three repos.
1. I've added a link to a PR where it detected a sensitive file being modified
    1. `setup.ts` , `.env.example`  and  `scripts/config-overrides/custom_start.js`
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1488#issuecomment-1908750216

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/88e492e3-c537-40f3-a857-e84a373fbf7d)

**Comment by duplixx** [comment]
Hey @palisadoes, we already have a Python script for checking changed files, known as check-changes-files. My proposal is, why don't we add the sensitive files check to the existing count_changed_files.py file? Should I go with this approach?


![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/5c633137-6eb5-4b43-b6b1-61ddc62d44dc)
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/92e3d20d-b482-4c4a-b1ef-df53e347ed49)

**Comment by palisadoes** [comment]
This is a good suggestion.

1. We will most likely use this across all three repos, so we cannot have a predefined set of defaults. They have to be provided as a CLI argument, preferably a file located in `.github/workflows` with the list of paths.
2. The paths provided must be relative to the repo root
3. The python `glob` module will be helpful in expanding file path wildcards
4. Use a namedtuple to return the `file_count` and `unauthorized_changes` values. It's easier to follow
5. Make sure to exit with the `1` value if either the file count is exceeded, the authorized paths are modified, or both.
6. Make the authorized file check a separate function for readability.
7. The names of the modified files must be clearly identifiable from the output
8. The script description docstring must be updated to explain this new functionality
9. Make sure the changes are compliant with the Google python style guide
    1. https://google.github.io/styleguide/pyguide.html#doc-function-raises
    2. Especially the function docstrings for readability
    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/4388f02d-4038-4264-bf35-0e28045dfec8)

**Comment by duplixx** [comment]
Yeah, great! Thanks for your suggestions. Also for sensitive files, I can create a text file with a list of files that can be modified according to the different repo's. The running command will look like this:

`python .github/workflows/count_changed_files.py --base_branch "${{ github.base_ref }}" --pr_branch "${{ github.head_ref }} --sensitive_files sensitive_files.txt`

**Comment by palisadoes** [comment]
1. OK
2. Also make it fail if any of the paths don't exist with a clearly understandable reason and how to fix it
3. This must be added as a mandatory argument

**Comment by palisadoes** [comment]
@duplixx This needs more work.

1. I did a test PR with 25 files and the changes were not detected
2. I added a file in the .github directory and the change was not detected.

Take another look

**Comment by duplixx** [comment]
here's is working demo of check_files.py 

https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/df006253-091f-425f-8e63-501c9d7b8626

**Comment by palisadoes** [comment]
It didn't work. Here's the PR, unfortunately the state is lost. But you can see I placed files in the `.github` directory and had > 20 files in total.
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1600

**Comment by palisadoes** [comment]
Remove this. None of the checks in the script require the code quality to be complete. It will also make your troubleshooting faster.

```
needs: Code-Quality-Checks
```

**Comment by palisadoes** [comment]
Here you can see that it failed:
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7947071353
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/7947025968

**Comment by palisadoes** [comment]
1. The original count files script worked
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1543/files#diff-cdcabb373b992496cb11acdc5ca2a6a88631ab47e3f0c0be44e13c0c3f3796cb
1. It identified files that were changed using the `command = f"git diff --name-only {base_branch}...{pr_branch} | wc -l"` command. This could be modified to exclude the ` | wc -l ` to get the file names which could then be compared with the sensitive files list.
1. When resubmitting please allow  for `#` style comments in the sensitive files list
1. Use the new name for the script, it makes more sense as it's doing more than just counting files

**Comment by duplixx** [comment]
Awesome!! @palisadoes I'll make changes and raise the PR

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by AdityaRaimec22** [comment]
@palisadoes can I get assigned to the issue.

**Comment by AdityaRaimec22** [comment]
@palisadoes While solving the issue I came across the below error
```bash
Run python3 .github/workflows/check_files.py --base_branch "develop" --pr_branch "myNewBranch" --sensitive_files .github/workflows/sensitive_files.txt --verbose
You are trying to merge on branch: develop
You are making a commit from your branch: myNewBranch
Error: fatal: ambiguous argument 'origin/develop..origin/myNewBranch': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
GitHub Actions are failing to recognize any of the branches, despite trying various solutions. It remains unclear why this issue persists despite attempts to address it.

**Comment by palisadoes** [comment]
Try this to verify whether you are using the correct variable values. Sometimes forked repos behave differently from the upstream.
- https://stackoverflow.com/questions/67503656/echo-github-action-environment-variables

**Comment by lakshz** [comment]
I would like to work on this. Please assign it to me.

**Comment by lakshz** [comment]
@palisadoes Instead of doing this with the `count_changed_files.py` Python script. 
I think a better solution here would be to use the `tj-actions/changed-files` action. Why:
- Code Quality Checks in `pull_request.yml` already this action, for linting in changed typescript files
- Talawa-API project also uses it
- No overhead to manage the workflows manually with a script.
- More consistency

We can get rid of the script then.

**Comment by palisadoes** [comment]
I noticed it in the PR. OK

**Comment by palisadoes** [comment]
Thanks.

We'll need this in the other repos. It will be very useful to have. Please create issues if you can.
