### ISSUE TITLE
Error on Active Advertisement page.

### ISSUE THREAD

**Issue by AmitSharma512** [PalisadoesFoundation/talawa-admin#1527]
**Describe the bug**
When there is no active advertisement and we click on the active campaigns tab, it shows some runtime error.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to advertisements.
2. Click on the Active Campaigns tab.
3. Now you can see the error.

**Expected behaviour**
There should be no error shown. 

**Actual behaviour**
Some runtime errors are getting popped on the screen.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/605e2124-e3fd-4c6a-91a4-9293f2065937)

**Additional details**
I would like to work on this :))

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
@Cioppolo14 and @AmitSharma512 

This issue has already been fixed in this [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/1529)

**Comment by AmitSharma512** [comment]
@disha1202 if the problem will be solved after merging your PR then I will close this issue.

**Comment by AmitSharma512** [comment]
@palisadoes I am closing this issue as i want to work on another issue and this issue will be fixed in the PR made by @disha1202
