### ISSUE TITLE
Conflict with React version and enzyme-adapter-react-16

### ISSUE THREAD

**Issue by gautam-divyanshu** [PalisadoesFoundation/talawa-admin#1532]
## Bug Description
While trying to install packages, I encountered an ERESOLVE error related to a conflict between the version of React our project is using (17.0.2) and the version required by `enzyme-adapter-react-16` (16.x.x).

## Steps to Reproduce
1. Run `npm install` in the project root directory.

## Expected Behavior
The packages should install without any errors.

## Actual Behavior
The installation fails with the following error message:

I've tried several solutions including using the `--legacy-peer-deps` flag, downgrading React, and upgrading `enzyme-adapter-react-16`, but none have resolved the issue.

If anyone has encountered this issue before or has any suggestions on how to resolve it, your help would be greatly appreciated.

Thank you!
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/db89aeaf-d487-4fa9-93e1-c968fd05eaaf)

**Comment by Cioppolo14** [comment]
@aarishshahmohsin If you are going to make a best practice issue that covers this issue as well, please let me know so I can close this as a duplicate.

**Comment by samiali12** [comment]
@gautam-divyanshu just tried npm install --legacy-peer-dep

**Comment by gautam-divyanshu** [comment]
@samiali12 It iqnores the warnings, these may cause trouble during runtime.

**Comment by palisadoes** [comment]
We don't want to use this command. Our apps must use current packages even if it means using replacement packages. We have opened issues in the past to rectify this on the `develop` branch

```
npm install --legacy-peer-dep
```

**Comment by aarishshahmohsin** [comment]
@palisadoes  @Cioppolo14  I have made the issue [(link)](https://github.com/PalisadoesFoundation/talawa-admin/issues/1536). Please tell if I should make any changes to issue.

**Comment by palisadoes** [comment]
Closing in favor of this issue:
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1536
