### ISSUE TITLE
Migrate Unit Testing from jest-enzyme to react-testing-library

### ISSUE THREAD

**Issue by aarishshahmohsin** [PalisadoesFoundation/talawa-admin#1536]
**Describe the bug**
Unit testing on Talawa Admin is done using jest-enzyme which is a library that provides additional utility functions for testing React components with Jest and Enzyme. jest-enzyme does not support React 17 and above and hence an unofficial adapter ```@wojtekmaj/enzyme-adapter-react-17 ``` is being used to make it compatible. This is a workaround and not the optimal solution to the problem. 

**To Reproduce**
NA

**Expected behavior**
All tests of Talawa Admin should be written using [react-testing-library](https://testing-library.com/docs/react-testing-library/intro/) instead of enzyme which requires an adapter.

**Actual behavior**
All tests are written using jest-enzyme which is not supported for React 17 and above without using unofficial adapters.

**Screenshots**
NA

**Additional details**
This would require refactoring of the entire testing suite.

**Comment by palisadoes** [comment]
@aarishshahmohsin Do you want to be assigned this issue?

**Comment by aarishshahmohsin** [comment]
> @aarishshahmohsin Do you want to be assigned this issue?

yes.

**Comment by Cioppolo14** [comment]
Closing this, the PR is merged so this is complete.
