### ISSUE TITLE
We cannot Create a Post with a title without Pinning it.

### ISSUE THREAD

**Issue by AmitSharma512** [PalisadoesFoundation/talawa-admin#1544]
**Describe the bug**
We cannot Create a Post with a title without Pinning it, which means we need to pin a post to add the title.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Posts Tab.
2. Click on the Create Post button.
3. Now, try to create a post without pinning it.
4. You will get an error warning: You cannot create a post with a title without pinning it.

**Expected behaviour**
A post must have a title, and we should be able to create a post with a title without pinning it.

**Actual behaviour**
We cannot create a post with a title without pinning it.

**Screenshots**
![Screenshot 2024-02-05 204724](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/d6270fb8-c94e-44f2-a91d-2f8eed183bbd)

**Additional details**
I would like to work on this :)))

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pateldivyesh1323** [comment]
@AmitSharma512 It will get fixed with https://github.com/PalisadoesFoundation/talawa-admin/issues/1486. The error is occuring because the API(https://github.com/PalisadoesFoundation/talawa-api/issues/1739) part of it is merged.

**Comment by AmitSharma512** [comment]
@palisadoes I am closing this issue as it will be fixed soon in another PR.
