### ISSUE TITLE
Inconsistent Initial Rendering of User Information: Admin Panel Displays Null, User Panel Shows Undefined Until Manual Refresh

### ISSUE THREAD

**Issue by MSVaibhav4141** [PalisadoesFoundation/talawa-admin#1545]
**Describe the bug**
Upon the initial render after logging in, the state of the username in the admin panel is displayed as null. Similarly, when logged in as a user, the states of both the username and organization appear as undefined until a manual refresh is performed, after which they load correctly.

**To Reproduce**

1.Refresh the login page.
2.Log in as admin or user.

**Expected behavior**
The username and organizations should be correctly displayed on the initial render without requiring a manual refresh.

**Actual behavior**
Upon the initial render, the username is displayed as null for admin, and both username and organization are displayed as undefined for users until a manual refresh is performed.

**Screenshots**
Video:-

https://github.com/PalisadoesFoundation/talawa-admin/assets/106318667/ace49738-e4f2-4027-ba48-b17f53edb444

P.S: If this issue has not been reported previously, I am eager to contribute and address it. I look forward to enhancing the efficiency of the application. Your consideration is greatly appreciated:)

Thanks

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
Thank you for your submission.  This issue is being addressed in #1498, so I am going to close this as a duplicate.
