### ISSUE TITLE
The location tags on the My Organization page are not aligned properly.

### ISSUE THREAD

**Issue by AmitSharma512** [PalisadoesFoundation/talawa-admin#1546]
**Describe the bug**
The location tags on the My Organization page need to be appropriately aligned.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to My Organization page.
2. Create an Organization by entering the name, location, etc.
3. You can see that the location is not aligned correctly.

**Expected behaviour**
The design should match the Figma file, and the location should be appropriately aligned.

**Actual behaviour**
The design does not match the Figma file, and the location is not aligned correctly.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/26151f81-e249-4469-8a19-c2c2b8270c1f)

**Additional details**
I would like to work on this :))))

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by i-m-Paras** [comment]
can I work on this issue?

**Comment by 1010varun** [comment]
hey @AmitSharma512 this issue has already been created #1538.

**Comment by rishav-jha-mech** [comment]
Closing this as it is an duplicate issue

**Comment by AmitSharma512** [comment]
@rishav-jha-mech it is not a duplicate issue , I want to re design the UI of the page according to the figma file.

**Comment by palisadoes** [comment]
Duplicate
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1538
