### ISSUE TITLE
Bug While Editing an Advertisement.

### ISSUE THREAD

**Issue by AmitSharma512** [PalisadoesFoundation/talawa-admin#1547]
**Describe the bug**
While Editing an Advertisement. We can make the start date of an advertisement after the end date of that advertisement.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create an Advertisement.
2. Now click on the Edit button.
3. You can make the start date of an advertisement after the end date of that advertisement.

**Expected behaviour**
We cannot make the Start Date of an advertisement after the End Date.

**Actual behavior**
While Editing an Advertisement. We can make the start date of an advertisement after the end date of that advertisement.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/28d98651-b9e7-4eef-912d-da8badd19f36

**Additional details**
I would like to work on this issue :)))

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AmitSharma512** [comment]
@i-m-Paras bro, i have created this issue, so let me complete this issue :))

**Comment by i-m-Paras** [comment]
@AmitSharma512  sure brother , it was a really great observation finding that bug. I appreatiate it!

**Comment by palisadoes** [comment]
Closing. Duplicate. @AmitSharma512 You must have created the bug. 
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1485

**Comment by AmitSharma512** [comment]
@palisadoes sir, I have not created this bug, while creating an advertisement there is no bug, I have fixed it in the previous PR, as the previous issue was there while creating the ad only, not while editing and after few days when I was editing the advertisement I found this bug .
