### ISSUE TITLE
Bug Report: Text coming out of box and going behind button in my organisation page

### ISSUE THREAD

**Issue by i-m-Paras** [PalisadoesFoundation/talawa-admin#1548]
**Describe the bug**
With open sidebar in my organisations page, if the page is dragged to left the text start coming out of box and some of text go behind 'manage' button.

**To Reproduce**

1.log in to talwa admin portal.
2.choose my organisations option from menu.
3. drag the screen to right , try resizing.
4. observe the text coming out of box.

**Expected behavior**
The text should fit in the box, 'manage' button should not cover text.

**Actual behavior**
Text is coming out of box and going behind 'manage' button

**Screenshots**
[Screencast from 06-02-24 02:09:23 AM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/121304240/63c7c306-84c7-44f0-bf43-45447fa64659)

**Additional details**
If this issue is in priority then I would like to work on this issue.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
Thank you for your issue. I'm going to close this as unplanned for now, as we are focusing on major bugs at this time.
