### ISSUE TITLE
Admin Redesign: custom scrollbar

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1551]
**Is your feature request related to a problem? Please describe.**
we require a thin scrollbar in talawa to match the design consistency 

**Additional context**
To be implemented here across sidenavbar and calendar:
![Screenshot 2024-02-06 at 10 25 33 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/7b3cdeee-b86a-45d9-ba25-69b0caca5993)
![Screenshot 2024-02-06 at 10 26 00 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/46e9635d-7e8d-4bda-b899-d3f765cdf42c)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AmitSharma512** [comment]
@palisadoes can i work on this ??

**Comment by pateldivyesh1323** [comment]
I would like to work on this.

**Comment by MSVaibhav4141** [comment]
i would like to work on this

**Comment by Cioppolo14** [comment]
@AmitSharma512 I have assigned you.  Please don't tag palisadoes in assignment requests, you are better off tagging me or someone on the list for the week in Slack. I don't mind if you tag me every time. It can take away from palisadoes time in managing code questions and PRs. Thank you!

**Comment by AmitSharma512** [comment]
@aashimawadhwa, what will be the design specs of the scrollbar ?

**Comment by Olatade** [comment]
@Cioppolo14 i assigned you [this issue](https://github.com/PalisadoesFoundation/talawa-admin/issues/1514) Please complete that first.

**Comment by Cioppolo14** [comment]
@priyakumari02 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.
