### ISSUE TITLE
Automatic Population of States Based on Selected Country in Dropdown

### ISSUE THREAD

**Issue by MSVaibhav4141** [PalisadoesFoundation/talawa-admin#1554]
**Is your feature request related to a problem? Please describe.**
When users select a country, the current system requires manual entry of the state name. This process can be cumbersome and prone to errors.

**Describe the solution you'd like**
Implement a feature that automatically populates the state dropdown menu based on the selected country. This enhancement will streamline the user experience by reducing manual data entry and aligning with the functionality seen on many other websites.
And it will also reduce the false entries.

**Additional context**
Existing:-

https://github.com/PalisadoesFoundation/talawa-admin/assets/106318667/79597fbc-1014-4bdb-997b-06ee6493c6c3

Desired:-

https://github.com/PalisadoesFoundation/talawa-admin/assets/106318667/79f27630-bc4c-4a7b-a878-b911d555a206

If this could be a feature ,  I express my interest in working on its implementation. Kindly consider assigning this issue to me. 
Thanks!

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
There are thousands of states, departments, districts, counties, to include. It's a good idea, but it is not a pressing need.
Closing
