### ISSUE TITLE
Adding validation to users password 

### ISSUE THREAD

**Issue by MSVaibhav4141** [PalisadoesFoundation/talawa-admin#1556]
**Describe the bug**
Minimal Validation of Users password while registering a user 

**To Reproduce**

1.Register the user with any password of minimum of 8 length character

**Expected behavior**
Users password while registration should require more validation.
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/106318667/b64b9ac9-ecec-41ed-8a7b-53b15ad39682)

**Actual behavior**
While users registration a password check of only 8 characters is needed.
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/106318667/21d1609b-234a-470a-9b2e-9b3fb9252097)

**Additional details**
Password with minimal validation may lead to brute force attacks.

If this could be an issue i would like to work on this, kindly assign me with this issue. Thanks:)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by MSVaibhav4141** [comment]
I would like to work on this issue.

**Comment by its-VinayKumar** [comment]
@MSVaibhav4141 @palisadoes , Please assign this issue. I want work on it.

**Comment by Cioppolo14** [comment]
@aashimawadhwa what do you think of this issue?

**Comment by its-VinayKumar** [comment]
@Cioppolo14 @aashimawadhwa
 Plz assign me this issue. I want to work on it and Will make PR as soon as possible.

**Comment by PiyushXmishra** [comment]
@Cioppolo14 I believe having too many red validation messages could create a negative impact on the UI.

**Comment by MSVaibhav4141** [comment]
> @Cioppolo14 I believe having too many red validation messages could create a negative impact on the UI.

@PiyushXmishra, thanks for your suggestion. However, I don't think it's going to create such a negative impact on the UI. The admin panel already has a similar UI, and it doesn't look bad. If the team prefers a minimal UI for validation, we could erase the validation messages as the password passes each validation instead of stacking them, or we could have a single-line validation message that updates and gradually disappears as the user types a password that passes validation.

**Comment by Cioppolo14** [comment]
@MSVaibhav4141 Thank you for your patience. I will assign you.  We would like all the 6 warnings in one sentence, please be specific with warnings and don't miss on any criteria.  Thank you!

**Comment by MahendraDani** [comment]
@Cioppolo14 
I worked on creating the present input validation under guidance of @palisadoes and @rishav-jha-mech. And I was told to let the minimum length of password be of *6 characters*.
https://github.com/PalisadoesFoundation/talawa-admin/pull/1376

**Comment by Cioppolo14** [comment]
@rishav-jha-mech @aashimawadhwa Can you both provide answers to this?

**Comment by rishav-jha-mech** [comment]
@Cioppolo14 @MSVaibhav4141 

https://github.com/PalisadoesFoundation/talawa-admin/pull/1493

This will be a redundant issue, since a PR is already open for this which would integrate both User and Admin Login and Register screens into one.

I am closing this issue for now.
