### ISSUE TITLE
Validation while updating the Address fields in an Org not added.

### ISSUE THREAD

**Issue by Anvita0305** [PalisadoesFoundation/talawa-admin#1559]
**Describe the bug**
While updating the address information, validation of fields is not added.

**To Reproduce**

1. Head to the Org where you want to update the address.
2. Update the different fields in an address.
3. The user can enter any gibberish values for these fields and they get updated in the DB as no validation is present.

**Expected behavior**
If unexpected values are entered, an error must be raised and a warning must be shown.

**Actual behavior**
Storing the data without validation.

**Screenshots**
[Screencast from 07-02-24 07:56:23 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/63a9b19f-893f-4341-b6c9-32c8b3608f9f)

**Additional details**
1. Validation needs to be added to talawa-api too.
2. Currently while updating the org, the user is supposed to enter State, City. However, there are APIs available for the same. So, can it be used? This will ensure that the city and state name fall under the same country and are correct.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
Thank you for the proposed issue. We are focusing on bugs and severe hardships in the code right now.  I am going to close this as unplanned for now.
