### ISSUE TITLE
Manage button overlapping in OrganizationList cards

### ISSUE THREAD

**Issue by PiyushXmishra** [PalisadoesFoundation/talawa-admin#1562]
**Describe the bug**
Manage button is overlapping in some screen sizes 

**To Reproduce**

1. Login as SUPERADMIN
2. Click on Organizations option in sidebar.

**Expected behavior**
 Button and Card  must be responsive in all screen sizes.

**Actual behavior**
 Button is overlapping.
**Screenshots**
 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110087602/f27a66ea-01b2-451b-9528-cb96f9ad34c5)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

Closing
