### ISSUE TITLE
hard refresh needed to remove the deleted advertisement 

### ISSUE THREAD

**Issue by wasifkareem** [PalisadoesFoundation/talawa-admin#1564]
**Describe the bug**
We need to perform a hard refresh to remove the deleted advertisement

**To Reproduce**

1.Goto `orgads/id={id}`
2.Create an advertisement
3.Try deleting it

**Expected behavior**
pressing the delete button should remove the advertisement.

**Actual behavior**
Advertisement persist even after deleting, we need to do a hard refresh to remove it.

**Screenshots**
https://github.com/PalisadoesFoundation/talawa-admin/assets/119349657/b3f4d648-2d12-4583-a674-cea6da782246

**Additional details**
if this needs fixing, I want to work on this please @palisadoes 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@wasifkareem Are you using the latest code on the develop branch?

**Comment by wasifkareem** [comment]
Sorry @Cioppolo14 , I was testing in the main branch, this issue is already solved, "develop" branch is not mentioned there in docs, let me know if you want to update the docs, also I'm actively looking for issues, do assign me one please. closing this issue

**Comment by wasifkareem** [comment]
Sorry @Cioppolo14 , I was testing in the main branch, this issue is already solved, "develop" branch is not mentioned there in docs, let me know if you want to update the docs, also I'm actively looking for issues, do assign me one please. closing this issue
