### ISSUE TITLE
Cast to ObjectId fails for _id: "undefined" at both User and Organization model

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-admin#1565]
**Describe the bug**

An error is occurring while loading Organization , people and  settings screen . The Cast to ObjectId failed for value _id at Organization model and User model.

**To Reproduce**

1. Login as Admin
2. Go to People screen and switch between users
3. or else go to settings you can see the error

**Expected behavior**

The update organization screen should be rendered without any error. Similarly, the people screen should also  be  rendered without any error and Organizations should be loaded correctly without any error.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![WhatsApp Image 2024-02-10 at 01 48 17_97cb17ab](https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/0e8cfa97-e7e8-4c57-973e-dd2e01a2bbd2)

![WhatsApp Image 2024-02-10 at 01 47 43_40663eaf](https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/26fac721-a38d-4723-801f-dc4dd55c6d66)
**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
@varshith257 Are you using the latest code from the develop branch?

**Comment by varshith257** [comment]
yes

**Comment by Cioppolo14** [comment]
I am not seeing this error when I try to replicate it.

**Comment by varshith257** [comment]
Yesterday, I pulled both develop branches into my local machine while trying to work on issue #1550. I suspect that the problem arises when the admin is not assigned to any organization, and the null values are not being cast into array objects. To replicate this issue, you can create a new admin account and not assign them to any organization.

**Comment by Cioppolo14** [comment]
@varshith257 I appreciate your investigation, I logged in as an admin without an organization, and did not see this error.  I believe that if this is an issue, it will be resolved by some upcoming changes, as every admin should have an assigned organization based on the intent of this application.  I am going to close this as unplanned.
