### ISSUE TITLE
Installation guide link is not correct in Contribution.md

### ISSUE THREAD

**Issue by ice-009** [PalisadoesFoundation/talawa-admin#1583]
**Describe the bug**
Installation guide link is not correct in Contribution.md

**To Reproduce**

1. When we try to find installtion.md or guide from main readme file. It redirects to the root directory of the folder.

**Expected behavior**
It should redirect to the installation.md file.

**Actual behavior**
 It redirects to the root directory of the folder.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/97959326/c8067afc-0bb3-4c87-a7cc-ada3615dba13

**Comment by Cioppolo14** [comment]
Thank you for your submission.  Our intention there is to redirect the person to all the main information files.  I'm going to close this as unplanned.
