### ISSUE TITLE
Bug Report: infinitely reroute to / and then to /orglist.

### ISSUE THREAD

**Issue by ice-009** [PalisadoesFoundation/talawa-admin#1587]
**Describe the bug**
When i am routing to orglist route it infinitely reroute to / and then to /orglist.

**To Reproduce**

1. Logging in as superadmin
2. routing to /orglist

**Expected behavior**
It should show the orglist 

**Actual behavior**
Infinitely routing and rerouting

**Screenshots**

Uploading Untitled video - Made with Clipchamp (1).mp4…

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ice-009** [comment]
I would like to work on this issue

**Comment by palisadoes** [comment]
1. This has been fixed in the develop branch.
1. There is also another PR to fix this permanently by not using local storage
