### ISSUE TITLE
Upgrade prettier from 2.3.2 to 3.2.5

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1591]
**Is your feature request related to a problem? Please describe.**

We need the the default formatting for Talawa-Admin to match that of Talawa-API

**Describe the solution you'd like**

1. Upgrade [prettier](https://github.com/prettier/prettier) from 2.3.2 to 3.2.5.
1. Format the code base according to the new default prettier rules
1. Submit PR. The prettier pull request check must pass. The check can be found here
    1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-request.yml
    2. This file must not be edited
1. All tests must pass
1. No other functionality must be affected 

**Describe alternatives you've considered**

- N/A 

**Approach to be followed (optional)**

- N/A 

**Additional context**

The upgrade will cause many files to be modified to meet the new prettier defaults. Refer to these items for guidance.

- https://github.com/PalisadoesFoundation/talawa-api/issues/1814
- https://github.com/PalisadoesFoundation/talawa-api/pull/1840

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
I would like to work on this issue.

**Comment by techmannih** [comment]
I want to work on this issue. Assign me
