### ISSUE TITLE
Create a post without pin it in the Organization

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-admin#1595]
**Describe the bug**
1. While creating a new post, it must be pinned in order to post it.
2. If a post is created as a pinned post and then unpinned, it can't be pinned again and throws an error message: `Post needs to be pinned inorder to add a title`.
3. When a post is created by clicking on post, it only shows the `author` and `description`, but not the `title`.

**Steps to Reproduce**
1. Navigate to the organization.
2. Create a post without clicking on 'pin'.
3. Create another post and click on 'pin'.
4. Try to unpin the post and then pin it again.
5. Observe the error message.

**Expected Behavior**
1. A post should be able to be created whether it is pinned or not.
2. A post should be able to be pinned again after being unpinned, without throwing an error.
3. When a post is created and clicked on, it should show the title, author, and description of the post.

**Actual Behavior**

The `OrgPostCard` component  and `OrgPost `screen have to be updated.

**Screenshots**
![Screenshot 2024-02-17 130419](https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/ddae51df-edc9-4c9e-81c2-30ec8d2aa84a)

postTitle isn't displayed:
![Screenshot 2024-02-17 130450](https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/43011651-42a4-4b5f-b60a-95a318442d88)

While trying to pin the post throwing error even though title is present:
![Screenshot 2024-02-17 130625](https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/531336e7-90de-4a20-9e3f-48a358735cd1)

Post can't be created if it doesn't pinned:
![Screenshot 2024-02-17 152137](https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/fbd9a51d-5f23-4f03-8323-0463418300bc)

**Additional Details**
Please provide any additional context or screenshots that could help with the feature request.

**Potential Internship Candidates**
If you are planning to apply for a Palisadoes Foundation internship, please read this https://github.com/PalisadoesFoundation/talawa/issues/359.

**Comment by varshith257** [comment]
@Cioppolo14 I have made all these fixes and I have already assigned two issues if it is a case where I can assign another issue. I would make an immediate PR. 
Otherwise, others can work on it.

**Comment by GlenDsza** [comment]
I would like to work on this issue.

**Comment by Cioppolo14** [comment]
#1486 is working on pinned posts, so I am going to close this as unplanned for now. If this issue remains after that issue is addressed we can reopen.
