### ISSUE TITLE
Implement CI/CD Pipeline to run tests before PR merges

### ISSUE THREAD

**Issue by DangaRanga** [PalisadoesFoundation/talawa-admin#16]
**Is your feature request related to a problem? Please describe.**
To ensure that tests are run before code is merged we need a tool to automatically run the tests to improve the reliability of Talawa-Admin as all feature/pull requests need to be adequately tested before they are merged.

**Describe the solution you'd like**
The tool must be :
    - Free for non-profit organizations (ideally)
    - Automated against the master and develop branches

**Describe alternatives you've considered**
I have considered using vercel's github integration for this. The approach I had in mind can be found here
https://github.com/vercel/vercel/discussions/4589

**Comment by yasharth291** [comment]
We can use nodejs 4 pipeline too i have used it before and it works for the react projects very well

**Comment by DangaRanga** [comment]
Okay we can use that, I'll assign the issue to you

**Comment by yasharth291** [comment]
Thank you so much sir working on it right now
