### ISSUE TITLE
USER REDESIGN: redesign the People screen for the talawa user portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1607]
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the People screen for the user portal and follow a theme similar to the talawa admin portal.

**Screenshots**
- Attaching the screenshots for reference.

current situation:
![Screenshot 2024-02-21 at 1 04 25 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/c89c1102-20db-4e35-ac7c-eb0c99e75968)

Desired Result:
![Screenshot 2024-02-21 at 12 58 59 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/80bed471-0419-40bc-9c52-5e38667ced9c)

Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**_Related issue_** : #1510 (sidenavbar is covered in this issue)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by rahat2134** [comment]
@aashimawadhwa can you assign this to me?

**Comment by Cioppolo14** [comment]
@rahat2134 Are you working on this?

**Comment by rahat2134** [comment]
hmm

**Comment by palisadoes** [comment]
When do you expect to submit a PR? Others need to get a chance of it's not soon

**Comment by rahat2134** [comment]
@palisadoes sorry, actually i was some busy. Others can try this.

**Comment by pranshugupta54** [comment]
Hey, I'd like to work on this!
I'll cover up Side Panel too.

**Comment by Cioppolo14** [comment]
@pranshugupta54 Stick with what it described by @aashimawadhwa in this issue.  It looks like the sidenavbar will be address in #1510.
