### ISSUE TITLE
USER REDESIGN: redesign the Event screen for the talawa user portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1608]
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the Event screen for the user portal and follow a theme similar to the talawa admin portal.

**Screenshots**
- Attaching the screenshots for reference.

current situation :
![Screenshot 2024-02-21 at 1 14 52 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/620a3779-2940-4c0e-9c84-85f6c2bdbe38)

Desired Result:
![Screenshot 2024-02-21 at 1 10 01 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/4b44a8d0-cb11-4037-aeb8-1d1e142921e0)

   Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**_Related issue_** : 
- #1510 (sidenavbar is covered in this issue)

**Additional context**

1. **_NOTE:_** This is going to require someone with experience with the repo, or proven long term experience with typescript, MERN, and / or graphQL in their GitHub profile

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by hharshas** [comment]
i have asked at both place for the (user redesign and admin redesign) of event page, it will be faster to make both as overall ui is same.

**Comment by GlenDsza** [comment]
I would like to work on this task

**Comment by palisadoes** [comment]
1. Unassigning due to inactivity. No submitted PR
1. This is open for reassignment, preferably to someone with an active GitHub profile on the technologies used or experience with the repository

**Comment by palisadoes** [comment]
@Sauradip07 

We'd prefer to give this to someone with more consistent experience in the repo and/or a proven long term experience with the MERN stack. You have closed numerous PRs without merging them in the recent past.

**Comment by wasifkareem** [comment]
Hi @palisadoes , I have PR ready for review for the issue [#1901](https://github.com/PalisadoesFoundation/talawa-api/pull/1932) that was assigned to me. Please assign this to me, I would love to work on this

**Comment by Cioppolo14** [comment]
@wasifkareem You would be a good candidate for this issue, but you currently have two assigned issues. Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by wasifkareem** [comment]
Hi @Cioppolo14 , I unassigned myself from one of the issue, can you please assign me this one, i think I can work on this

**Comment by wasifkareem** [comment]
![events](https://github.com/PalisadoesFoundation/talawa-admin/assets/119349657/a2219c52-486b-4a90-8ad8-fcd8fd6abac6)
Hi @aashimawadhwa ,I have a few questions regarding the event categories in the calendar UI. Will the `event created by organizations` category contain all events created by other users within the organization, except for the current user? And is it correct that the `event created by user` category will only contain events created by the current user?

**Comment by aashimawadhwa** [comment]
- `event created by organizations` are events created by admin/super-admin which are org based events.
- `event created by user` is events created by user across the platform.

@wasifkareem

**Comment by wasifkareem** [comment]
Hi @duplixx , the eventdata array from admin side done not have creator object, I'm using creator id to see if the event creator is admin or not. can you please the same query that is used on the user side so that we can have creator info available

user side eventdata object
![Screenshot from 2024-03-11 13-14-39](https://github.com/PalisadoesFoundation/talawa-admin/assets/119349657/61bd7d29-6d2f-474b-aef7-a06eb5cc5bab)

admin side eventdata obj
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/119349657/5988ddc5-dca8-4111-a328-6b5a1e48fa43)

**Comment by wasifkareem** [comment]
Hi @aashimawadhwa , sorry for the delay, I'm almost done with the PR, just have to write the test , will create PR soon.

**Comment by palisadoes** [comment]
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/27/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by palisadoes** [comment]
@wasifkareem 

1. This issue is now closed:
     1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1611
1. Please open a PR soon for the new layout. It'll be a great improvement to the app.
     ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/43ff3cad-fcd3-4793-87c5-5cd5170d7649)

**Comment by wasifkareem** [comment]
Hi @palisadoes , most of th work is complete, I'm new to testing so its taking little longer. will create PR very soon.

https://github.com/PalisadoesFoundation/talawa-admin/assets/119349657/dd8b03fe-bb6c-4120-87ce-77cc76f3a3ec

**Comment by palisadoes** [comment]
It's encouraging to see the progress being made in the UI/UX

I remember that the tasks were going to be split. Will this calendar change be visible in both the user and admin portals? That is what I understood the agreement to be.

**Comment by wasifkareem** [comment]
> @wasifkareem nicee work⚡️ just a little suggestion to close this gap and add little padding around whole div ![image](https://private-user-images.githubusercontent.com/90516956/316986646-72c8881e-d497-4e0f-8a9e-372f2801a673.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTg3MDksIm5iZiI6MTcxMTUxODQwOSwicGF0aCI6Ii85MDUxNjk1Ni8zMTY5ODY2NDYtNzJjODg4MWUtZDQ5Ny00ZTBmLThhOWUtMzcyZjI4MDFhNjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA1NDY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NDhjYTE1MzE5NTA4ZjhjM2IzMGRhZDkzNjQ3ZjkwZjgyZDg5OGMyMTQ3YjA5NjM3M2QxM2UxNGVkMWJhZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._S-s4UVp-k-8wuie3TngRnd86Ny23Mj6M8w3Wxjmn3o)

Thanks for the suggestion @duplixx , will make the changes

**Comment by wasifkareem** [comment]
> It's encouraging to see the progress being made in the UI/UX
> 
> I remember that the tasks were going to be split. Will this calendar change be visible in both the user and admin portals? That is what I understood the agreement to be.
Yes @palisadoes , it will be visible on both sides.

**Comment by wasifkareem** [comment]
> It's encouraging to see the progress being made in the UI/UX
> 
> I remember that the tasks were going to be split. Will this calendar change be visible in both the user and admin portals? That is what I understood the agreement to be.

yes @palisadoes , it will be visible on both sides

**Comment by duplixx** [comment]
@wasifkareem raise the PR for this 
do let me know if you are facing any blocker's ??

**Comment by wasifkareem** [comment]
> @wasifkareem raise the PR for this do let me know if you are facing any blocker's ??

Hi @duplixx , Sorry I was little busy, hence the delay. right now I'm facing git rebasing issues, but now i understand the problem and its almost resolved, give me some more time ,will let you know when PR is ready

**Comment by palisadoes** [comment]
@wasifkareem 

This is one of the last major design changes for the web portal. How is progress going? It's been over a month.

**Comment by wasifkareem** [comment]
Hi @palisadoes , @duplixx I'm trying to commit my changes but constantly getting these errors.please help me resolve this and then I will write the tests and submit the PR
![Screenshot from 2024-03-31 11-12-30](https://github.com/PalisadoesFoundation/talawa-admin/assets/119349657/a7319532-ab09-4381-ae3a-500e8a90215b)

**Comment by pranshugupta54** [comment]
@wasifkareem, you need to change type from `any` to something suitable for typescript. 
We can kinda help more if you show the code? Like the line numbers are written here - 
<img width="88" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/efe686fa-fb93-47ff-a90f-cf18a7751389">

**Comment by palisadoes** [comment]
@wasifkareem 

If you open a PR it will be easier for others to evaluate the problem

**Comment by wasifkareem** [comment]
Hi @palisadoes , I might not be able to continue with this issue, lots of lint errors and stuff, @duplixx you can go ahead and work on this, you can use my [branch](https://github.com/wasifkareem/talawa-admin/tree/develop) if you want . I'm unassigning myself.sorry for inconvenience.

**Comment by palisadoes** [comment]
@duplixx 

I've assigned this to you.

**Comment by duplixx** [comment]
@palisadoes Okay, I'll do it.

**Comment by duplixx** [comment]
@palisadoes sir we should keep the "today" button as it helps to easily navigate through calender
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/cb8fbe47-10ac-449d-9cc9-4cb4fa8111c8)

**Comment by palisadoes** [comment]
Sure. As long as the `Today` day is  subtlety highlighted when the navigation is activated.

**Comment by duplixx** [comment]
@palisadoes can we remove good first issue label from this issue😅
