### ISSUE TITLE
USER REDESIGN: redesign the Create Event Modal for the talawa user portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1609]
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the user portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the create event modal for the user portal and follow a theme similar to the talawa admin portal.

**Screenshots**
- Attaching the screenshots for reference.

current situation :
![Screenshot 2024-02-21 at 1 33 03 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/862fb0df-01a4-4f08-86e6-1513c6174594)

Desired Result:
![Screenshot 2024-02-21 at 1 21 54 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/00d8ee3c-3a91-4045-833f-6bbd338989d8)

   Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by i-m-Paras** [comment]
please assign this to me.

**Comment by Cioppolo14** [comment]
@i-m-Paras These REDESIGN issues are time intensive, so we're going to try to assign one per person to ensure that the assignee's focus can be on the issue.

**Comment by Anvita0305** [comment]
Hello, I would like to work on this issue. Can you please assign it to me? Thanks!

**Comment by anuragnegi000** [comment]
Please assign this issue to me. I'd like to work on it.

**Comment by MSVaibhav4141** [comment]
Please assign to me

**Comment by techmannih** [comment]
I want to work on this issue assign me this isuue

**Comment by i-m-Paras** [comment]
> @i-m-Paras These REDESIGN issues are time intensive, so we're going to try to assign one per person to ensure that the assignee's focus can be on the issue.

@Cioppolo14 okay, I understand. I will focus on my part.

**Comment by krishna-p060** [comment]
@Cioppolo14 @aashimawadhwa , I would like to work on this issue , and I have time to focus fully on this issue.
can you please assign this to me

**Comment by Anvita0305** [comment]
Hello @aashimawadhwa ,
While working on the events portal on user side, I observed a minor issue in list view:
1. If the user enables AllDay then timing is not displayed in Starts and Ends section:
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/ba90a5b5-08a6-4f2b-bed5-c600305eb3e7)
2. If the user manually enters start and end timing by disabling the AllDay then:
a. Then timing displayed vs the user has entered is not same.
b. In list view timing is displayed unlike as in the above image.
[Screencast from 26-02-24 10:34:44 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/e0a41a78-465e-4e85-89ce-8b9245b056b2)

So should I handle this in redesign issue itself or another issue needs to be created for it?

**Comment by Anvita0305** [comment]
Hello @aashimawadhwa ,
While working on the events portal on user side, I observed a minor issue in list view:
1. If the user enables AllDay then timing is not displayed in Starts and Ends section:
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/ba90a5b5-08a6-4f2b-bed5-c600305eb3e7)
2. If the user manually enters start and end timing by disabling the AllDay then:
a. Then timing displayed vs the user has entered is not same.
b. In list view timing is displayed unlike as in the above image.
[Screencast from 26-02-24 10:34:44 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/78889572/e0a41a78-465e-4e85-89ce-8b9245b056b2)

So should I handle this in redesign issue itself or another issue needs to be created for it?
