### ISSUE TITLE
ADMIN REDESIGN: redesign the Event screen for the talawa admin portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1611]
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the admin portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the Event screen for the admin portal and follow a theme similar to the talawa user portal.

**Screenshots**
- Attaching the screenshots for reference.

current situation :
![Screenshot 2024-02-21 at 1 50 02 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/fba88718-248b-4d40-9e9c-f4612f499334)

Desired Result:
![Screenshot 2024-02-21 at 1 55 22 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/d8b737e8-256c-4bb1-a47c-8dc8f3fbb8f8)

   Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=307%3A212&mode=design&t=hBVanpDXxbRFi51m-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
I would like to work on this issue

**Comment by Cioppolo14** [comment]
@varshith257 The current docker issue you have looks like it might be time intensive, is it?  This one will be too.  We are trying to assign one REDESIGN or time intensive issue per contributor to make sure their time is focused on the issue needed.  Will you be able to complete both in a timely manner?

**Comment by hharshas** [comment]
i want to work on this issue

**Comment by git-init-priyanshu** [comment]
I would like to work on this. Thanks.

**Comment by palisadoes** [comment]
1. Unassigning due to inactivity. No submitted PR
1. This is open for reassignment, preferably to someone with an active GitHub profile on the technologies used or experience with the repository

**Comment by duplixx** [comment]
@Cioppolo14 I would like to work on this issue

**Comment by duplixx** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/acccdfc1-d5f5-4fa1-9923-08917250ab9f)
@palisadoes @aashimawadhwa
The proposed UI requires a new calendar UI component. The existing event calendar code cannot be reused as its approach is totally different from what we want to achieve.

**Comment by wasifkareem** [comment]
Hi @palisadoes @aashimawadhwa @duplixx , I'm working on #1608 where I've to redesign the event screen on user portal side, both the portals use same `<EventCalender/>` component, IMO either me or @duplixx should redesign UI for calender comp and create a PR separately for it.  or we can use create separate components for both cases.

@duplixx"Why do you think it can't be reused? What are the blockers?"

**Comment by duplixx** [comment]
@wasifkareem

Boilerplate Code: It seems like there's indeed a lot of manual definitions for days, months, and hours in the current implementation. We should explore ways to refactor this to make the codebase cleaner and more maintainable. Perhaps we can utilize libraries or utilities to handle date-related operations more efficiently.

User Search Functionality: There's a mention of user search functionality, which seems out of place within the context of the Calendar component. This might need clarification or could be related to a broader functionality.

Additionally, @aashimawadhwa could you provide clarification on the functionalities of Event View and Month View?

**Comment by aashimawadhwa** [comment]
@wasifkareem @duplixx  coordinate with each other and try to make a cleaner and reusable ui component for it.

the year view and day view will be same for now. Try to segregate these if this all code is in one file. Apply modularization as much as you can.

do let me know for any other doubts.

**Comment by palisadoes** [comment]
Is there a practical way to split this between you as  clearly defined `Part A` and `Part B` PRs?

**Comment by wasifkareem** [comment]
Hi @palisadoes I think it's more reasonable for one person to redesign the calendar comp and the holiday, events slots at the bottom. @duplixx can I please work on this when the above mentioned things are complete I will make a separate PR and then you can use those components on the admin side as well.

**Comment by duplixx** [comment]
@wasifkareem, I discussed with @aashimawadhwa on Slack, and we've agreed on this approach: You can focus on the calendar UI as you prefer, while I'll handle the modularity of the search and toggle components.  ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/43ff3cad-fcd3-4793-87c5-5cd5170d7649)

**Comment by wasifkareem** [comment]
Sure @duplixx , already started working on the calendar UI comp.

**Comment by duplixx** [comment]
@wasifkareem awesome !!🚀

**Comment by wasifkareem** [comment]
Sure will do @duplixx , you can also move month view dropdown from `<EventCalendar.tsx` to `<Events.tsx>` . because `<EventCalendar.tsx>` won't have the month view dropdown

**Comment by palisadoes** [comment]
@wasifkareem 

This issue is complete. You can submit your changes for the calendar UI. It'll be such a big improvement.

 ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/43ff3cad-fcd3-4793-87c5-5cd5170d7649)
