### ISSUE TITLE
ADMIN  REDESIGN: redesign the user profile for the talawa admin 

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1615]
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the admin portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the user profille screen for the admin portal and follow a theme similar to figma.

**Figma**
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=307-212&mode=design&t=R8JOYRzxgITPiwTg-0

**Screenshots**
Current :
![Screenshot 2024-02-22 at 4 17 58 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/2ca5dc9f-91ca-4d60-a2c6-755fff270c27)

Desired:
![Screenshot 2024-02-22 at 4 10 34 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/d235ecd9-a214-455b-a377-15ac9abc3a50)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Balaji-Avk** [comment]
I would like to work on it please assign me this issue.

**Comment by Balaji-Avk** [comment]
I would like to work on this please assign me this issue

**Comment by its-VinayKumar** [comment]
@aashimawadhwa Plz Assign me this issue I want work on this.

**Comment by anuragnegi000** [comment]
i can work on this issue, please assign this to me

**Comment by varshith257** [comment]
@Cioppolo14 I would like to work on this issue. I have taken up issue #1451 and have already worked on it. However, due to the redesign of some functionalities, the issue has been closed. I have completed half of the work, and this is also a prerequisite for my GSOC proposal.

**Comment by Cioppolo14** [comment]
@varshith257 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by palisadoes** [comment]
@Balaji-Avk Are you still working on this? It's been almost 2 weeks.

**Comment by its-VinayKumar** [comment]
@palisadoes Please assign me this issue.

**Comment by Balaji-Avk** [comment]
@palisadoes i am still working on it will mostly finish it by tomorrow.

**Comment by palisadoes** [comment]
> @palisadoes i am still working on it will mostly finish it by tomorrow.

The completion of this issue is dependent on your PR. Hopefully we can get your work merged in a couple of days.

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1653

**Comment by Balaji-Avk** [comment]
@palisadoes Apologies for the delay, I've been caught up with exams. I won't be able to complete the assigned issue this week.I am sorry for wasting your time and I will make sure it to not happen again. Could you please re-assign it to someone else. Thank you for your understanding.

**Comment by pranshugupta54** [comment]
Hey, I'm interested in working on this.

Extra note:
- [x] I'm assigned to another similar issue (User People re-design) - I've already made a PR for it though!
- [ ] Working on fixing a deprecated package on api repo

**Comment by palisadoes** [comment]
I'm assigning as an exception due to the similarity of the issues.

**Comment by pranshugupta54** [comment]
Hey @aashimawadhwa, can you clarify a bit about the design?

What's `Joined on` date? Is it `createdAt` for `User` or is there a way to find, _joining date for particular organization_
<img width="214" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/8ca0b02b-b8cb-49ee-a9b2-a6d0c5e1848b">

**Comment by pranshugupta54** [comment]
Also, I've added `userType` below the Avatar
<img width="403" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/10555faf-0892-48b1-9391-c309c3c63c58">

**Comment by aashimawadhwa** [comment]
Fir this created at is not the date when user joined the community I will check with code wnd let you know.
Design wise, put the label of user below the name in a transparent green button and not below the avtar.
Let me know for any doubts.
@pranshugupta54
