### ISSUE TITLE
Event end  time can be earlier than the start time

### ISSUE THREAD

**Issue by wasifkareem** [PalisadoesFoundation/talawa-admin#1618]
**Describe the bug**
When initiating a new event, it's possible to designate an End time before the Start time.

**To Reproduce**

1. Go to `/orgevents/id={id}`
2. Click on `Add Event`
3. Turn off the `all day` option
4. now you can create event with end time before the start time

**Expected behavior**
It should throw a toast error if user try to set end time before the start time.

**Actual behavior**
even though the time preceding the start time is inactive in the dropdown menu, users still have the ability to manually input a time earlier than the start time
**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/119349657/876beb68-4fa2-4a74-ac2b-ed21dbef9ca7

@Cioppolo14  if this is a real issue, please assign it to me, I will work on it.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by takshakmudgal** [comment]
I would like to work on this issue.

**Comment by Cioppolo14** [comment]
@wasifkareem If the API is allowing this as well, can you make a corresponding issue in API to correct that?

**Comment by AspireSsp** [comment]
Are you still working on Issue #1618? If not, could you please assign it to me? I'd like to contribute. Thanks!

**Comment by wasifkareem** [comment]
Hi @Cioppolo14 @AspireSsp  , unassigning myself because this is not a frontend issue, I already created an issue for this in talawa-api and I'm working on it.
