### ISSUE TITLE
Add support for Fundraising campaigns

### ISSUE THREAD

**Issue by AVtheking** [PalisadoesFoundation/talawa-admin#1623]
**Is your feature request related to a problem? Please describe.**
Adding support for fundraising campaign in talawa-admin.

**Describe the solution you'd like**
1. screens for the CRUD operation of the organization funds
2. screens for the CRUD operation of the  fund campaings.
3. screens for the CRUD operation of the fund campaigns pledges.

**Additional context**
This is campaign issue of the api-issue https://github.com/PalisadoesFoundation/talawa-api/issues/1663

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AVtheking** [comment]
please assign me this issue

**Comment by AVtheking** [comment]
Do I have to make design of the screen by myself?

**Comment by aashimawadhwa** [comment]
@AVtheking yes please, initiate the design yourself.

**Comment by AVtheking** [comment]
@aashimawadhwa actually I am not good at designing 😅,but I will try my best 👍

**Comment by AVtheking** [comment]
@palisadoes thanks sir ,I would soon start working on pledges one.

**Comment by AVtheking** [comment]
> @palisadoes thanks sir ,I would soon start working on pledges one. Should I create pledges options in the left navbar or open the pledges screen while clicking on the campaigns ?

@palisadoes  sir ?

**Comment by palisadoes** [comment]
1. @AVtheking While clicking on the campaigns. This is not ideal, but will work for now
2. @aashimawadhwa We are going to need a screen for managing fundraising campaigns

**Comment by AVtheking** [comment]
@palisadoes sir wouldn't the pledges would be done by members of the organization ?
Wouldn't this functionality should be added in the user portal instead of admin ?

**Comment by palisadoes** [comment]
1. Both Admins and users should be able to make pledges. Someone may tell an admin to record a pledge on their behalf.
2. Focus on the Admin screens.
3. We can figure out the Member screens later. They will only need view privileges for funds and campaign screens and visibility into only their pledges.

When the Admin functionality is complete we can use the Admin screens as templates for the Member UI/UX.

**Comment by palisadoes** [comment]
@AVtheking Can this be closed now?

**Comment by AVtheking** [comment]
@palisadoes yes
