### ISSUE TITLE
Git commit workflows adding unnecessary symbols during commit

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-admin#1624]
On committing your changes, the scripts/workflows defined to run automatically adds symbols such as hyphen (-) (in below example) in `README.md` file. Maybe the above issue is caused due to issue in EOL handling or during conversion from LF to CRLF. 

1. Make changes to codebase 
2. Stage the changes
3. Commit the changes
4. The scripts defined to run per commit will make auto changes in README.md file

**Expected behavior**
The staged changes should be committed without adding of (-) symbol to README.md file which seems unnecessary.

**Screenshots/Video**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/1a9b1c71-ad35-47d1-9be5-20ca4b11a7b4

- Before committing changes (Table of Contents section in README.md):

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/610ec903-f2ce-4c29-9560-c2305f7d8654)

- After committing changes (auto added -- post documentation word at line 29):

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/3ae02f13-ab55-4185-977e-5d36d2b2e217)

**Comment by palisadoes** [comment]
1. We generate new TOCs in the PR to ensure our documentation is up to date.
2. If you have not merged with the latest upstream,  or have edited the markdown files there will changes.
3. This is expected behaviour
4. Closing
