### ISSUE TITLE
Change of post by organisation query 

### ISSUE THREAD

**Issue by AVtheking** [PalisadoesFoundation/talawa-admin#1626]
**Describe the bug**
Post by organisation query need to be changed according to this PR [#1722 ](https://github.com/PalisadoesFoundation/talawa-api/pull/1722)

**Additional details**
As PR [#1722 ](https://github.com/PalisadoesFoundation/talawa-api/pull/1722)changed the implementation of the PostByOrganization query,this need to be changed in admin and mobile repo as soon as possible 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
1. Please correct the PR link and make sure it works
2. Open an issue in Talawa as well

**Comment by AVtheking** [comment]
I have opened it in talawa 
Please assign me this issue
