### ISSUE TITLE
 ADMIN REDESIGN: redesign the User Request for the talawa admin portal 

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1631]
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the admin portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
we want to redesign the User Request for the admin portal .

**Screenshots**
- Attaching the screenshots for reference.

Desired Result:
![Screenshot 2024-02-28 at 11 47 17 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/fd909941-5ebf-45a1-b168-c253a022bd64)

Please refer the figma file for a detailed understanding : 

https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=307%3A212&mode=design&t=hBVanpDXxbRFi51m-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sahi1l-Kumar** [comment]
Please assign this issue to me

**Comment by its-VinayKumar** [comment]
@palisadoes @aashimawadhwa @Crystian Ioppolo 
Please assign me this issue. :)

**Comment by Sahi1l-Kumar** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/135227614/2c4ad820-694f-423a-ab0f-eeb967bb7227)
On what basis should `Search Requests` be done? name or email?

**Comment by Sahi1l-Kumar** [comment]
The current  GraphQL schema does not support `Search requests`. I'm considering implementing the search functionality on the client-side. What should I do?

**Comment by palisadoes** [comment]
1. Open an issue on the API side
2. When you are ready to submit the PR let us know that it's pending API support for searching. Searching on the client side is going to be inefficient. We may merge and open another issue to handle search for the design

**Comment by Sahi1l-Kumar** [comment]
Should I proceed with this design or does it need some changes?
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/135227614/24ddec6d-7eff-4616-acfc-6c75c72e8931)

**Comment by pranshugupta54** [comment]
LGTM 👍

**Comment by palisadoes** [comment]
@Sahi1l-Kumar Please go ahead

**Comment by Sahi1l-Kumar** [comment]
@palisadoes There seems to be another missing `field` in the API. It does not have `skip` field which is leading to infinite scroll. 
Should I create a seperate issue or amend the recently opened issue to incorporate search functionality as well?

**Comment by palisadoes** [comment]
Create an issue in the API

**Comment by pranshugupta54** [comment]
@aashimawadhwa, can you clarify over the design?

`membershipRequests` is a part of Organisation so every Org has its separate list but the design contains them all together under one list before even choosing the Organisation?


Solution:
1) Move this screen after Organisation is selected in this list:
<img width="240" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/02bde7ea-98fc-4f44-9507-154df3656f3c">

2) Add Org Name along with request (this will be very messed up and bad UX)

**Comment by Sahi1l-Kumar** [comment]
Can I get a clarification on both of these?
https://github.com/PalisadoesFoundation/talawa-admin/issues/1631#issuecomment-1995070106
https://github.com/PalisadoesFoundation/talawa-admin/issues/1631#issuecomment-1995179168
