### ISSUE TITLE
Bug: Data of Newly Registered Users Requires Hard Reload

### ISSUE THREAD

**Issue by anuragnegi000** [PalisadoesFoundation/talawa-admin#1638]
**Describe the bug**
The bug occurs in the users section where newly registered users fail to render unless a hard reload is performed. This issue specifically affects all newly registered users, excluding the sample data.

**To Reproduce**

1.Register as a new admin.
2.Click on the users section.
3.Notice that the newly registered data is not displayed.

**Expected behavior**
When a new user is registered, their data should be immediately visible on the screen without the need for a hard reload. The page should dynamically update to display the newly added user information seamlessly.

**Actual behavior**
Upon registering a new user, the data does not appear on the screen until the page is hard-reloaded. Despite the registration process completing successfully, the page fails to update dynamically to reflect the newly added user information. As a result, users are required to perform a manual hard reload to view the updated data, which disrupts the expected user experience.

**Screenshots**
[

https://github.com/PalisadoesFoundation/talawa-admin/assets/115611556/65a314b6-aaac-4953-9801-dc66aa9f5d54

](url)

**Additional details**
---

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Rajeshpatel07** [comment]
I would like to work on this issue.

**Comment by Cioppolo14** [comment]
@anuragnegi000 @Rajeshpatel07 Are you seeing this in the develop branch? I believe this issue should have fixed it: https://github.com/PalisadoesFoundation/talawa-admin/issues/1498

**Comment by anuragnegi000** [comment]
@Cioppolo14 yes this bug is still occurring in develop branch

**Comment by Rajeshpatel07** [comment]
In the users portal there is no issue if you want to see all the users,admins,superadmin the data is fetched dynamically when we scroll down and added to the top of th list. But if you filter them and the the admins are only few we cannot see them until we scroll down. But in larger screens we can't scroll down and the data is not visible.

[Talawa admin.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/145205731/e1f545e3-bd94-4ca3-a219-08f81f0d39a0)

## Please tell me how to proceed with this.

**Comment by Cioppolo14** [comment]
@Rajeshpatel07 This isn't referring to the users panel.  You can recreate this issue following these steps:
1) Make a new user login
2) Log into the talawa with the brand new user
3) See in the upper left where the new users name should be it shows as "undefined" until the page is refreshed.

**Comment by Rajeshpatel07** [comment]
@Cioppolo14 

Thank you for guiding me to how to recreate the issue. But this issue has already been resolved by another contributor. There is nothing else to do. The users data is fetched dynamically when we scroll down.

[Talawa.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/145205731/272a59aa-bcc2-4443-883e-2c6f75ea91e5)

**Comment by Cioppolo14** [comment]
@Rajeshpatel07 You are logging in to the admin side, click on the user side on the login screen, and make a new user there. Then log in as just a regular user.

**Comment by Rajeshpatel07** [comment]
@Cioppolo14 
Sorry for the confusion but the description of the bug is that the newly registered users are not visible until hard reload.

**To Reproduce the issue**
1.Register as a new admin.
2.Click on the users section.
3.Notice that the newly registered data is not displayed.

In the screenshot he is logged in as a admin.

 But you are suggesting me to login as a regular user and I didn't understanding it. But have tried that aswell and there is no problem.

Thank you.

**Comment by Cioppolo14** [comment]
@Rajeshpatel07 I apologize, I had some confusion on my end. You are correct this is resolved.  I will close this.  Let's find you a new issue to work on.
