### ISSUE TITLE
Bug Report: Sidebar buttons are not working.

### ISSUE THREAD

**Issue by skbhagat0502** [PalisadoesFoundation/talawa-admin#1640]
**Describe the bug**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/782c565a-c97d-429a-88e4-07666886a7bc)

The button highlighted above opens this sidebar.

![Screenshot 2024-02-29 230622](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/a8cc759e-1ada-4816-b851-60714ec78046)

You can see that it cant find any organization. Hence none of the sidebar buttons are working as all functionalities in those pages are dependent or `orgId`
**To Reproduce**

1. Click on the profile button.
2. Click on Post, advertisement people, events you will see none of them is working.

**Expected behavior**
This side bar should only be visible after choosing an organization.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by skbhagat0502** [comment]
@dhanagopu Please assign me this issue. Also Please give your suggestions on that the sidebar should be only visible after choosing an organization or how it should work.

**Comment by palisadoes** [comment]
1. Run setup again with the latest API update. Import the sample data too.
2. We did a recent change

**Comment by skbhagat0502** [comment]
@palisadoes I am not able to connect to the talawa-api server. Getting this cors error in the console.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/b1f86281-e5f0-4c42-ad72-c9e56c209a6c)

Am I doing anything wrong?

**Comment by palisadoes** [comment]
Reinstall your packages. It should be OK

**Comment by skbhagat0502** [comment]
Ok @palisadoes

**Comment by GlenDsza** [comment]
@palisadoes  The above issue is fixed in #1592 as on click of profile Button in `LeftDawer`, user is directed to profile screen and only on click of organization (which provide orgId) `LeftDrawerOrg` is rendered thereby elimination "Organization Not found in LeftDrawer"
