### ISSUE TITLE
[Enhancement] Improved GitHub Issue Template

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1644]
### Utilizing input fields for submitting feature requests and bug reports.
Refer to the documentation for assistance: - [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests)

Example:
<img width="1423" alt="image" src="https://github.com/PalisadoesFoundation/talawa-api/assets/76090263/afca407b-683e-41ef-ad60-15ba00dd9393">

**Comment by pranshugupta54** [comment]
I'd like to work on this! 🚀

**Comment by palisadoes** [comment]
Closing. We are focusing on fixing bugs that caused real hardship and features that focus on the expectations of the end user to alleviate talk hardship too
