### ISSUE TITLE
Bug Report: Unable to open User joined Organization Home Screen due to Error 

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-admin#1651]
**Describe the bug**
- If a user opens organization's home screen which he has joined error is shown. 
- The error can be traced to following file `src/screen/UserPortal/Home/Home.tsx` which occurs due to accessing undefined attribute.

**To Reproduce**

1. Sign in as user (Must've joined atleast 1 org)
2. Open any joined Organizations home page
3. The error will be shown

**Actual behavior**
An error occurs due to accessing undefined attribute without proper checks

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/d6422cbe-2807-4a66-87b0-5f26f8377aab

**Expected behavior** (Have identified and solved the bug on local)
No Error must be shown. and Home Screen must be displayed 

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/37f9be97-bc09-4138-ad7c-6fd9fec87cd1

Additionally write tests for `src/screen/UserPortal/Home/Home.tsx` whose code coverage currently 
[Link](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/blob/develop/src%2Fscreens%2FUserPortal%2FHome%2FHome.tsx) 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/018bf193-a6cf-43de-8630-af29f85d896f)

**Comment by GlenDsza** [comment]
@palisadoes would like to work on this issue 
and as would be modifying `src/screen/UserPortal/Home/Home.tsx` file to resolve issue
would simultaneously make sure to add tests  and improve code coverage mentioned in issue #1131 which will be solved as well

**Comment by Cioppolo14** [comment]
@GlenDsza Can you open an organization profile as an admin or superadmin?

**Comment by GlenDsza** [comment]
> @GlenDsza Can you open an organization profile as an admin or superadmin?

@Cioppolo14 Yes the Organization profile screen opens perfectly fine on Admin/SuperAdmin
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/725a54a0-12f7-44f1-924c-9dd434ee2165)
