### ISSUE TITLE
ADMIN REDESIGN: Add User/Member Capability

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1653]
**Is your feature request related to a problem? Please describe.**

We need to add new features as part of the Admin Portal redesign.

**Describe the solution you'd like**

We need the ability for Admins to:

1. add a brand new user to the system and automatically make them members of their organizations.
1. make sure they are not adding preexisting users to the system, creating duplicates. (Make the user's email address the unique identifier.)
1. access this feature from the Organization People screen. (Refer to this issue)
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1550

**Figma**

- https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Desi

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

1. **_NOTE:_** This is going to require someone with experience with the repo, or proven long term experience with typescript, MERN, and / or graphQL in their GitHub profile
1. You will need to work closely with the person assigned this issue as the design elements overlap
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1615

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Hi 
Can I work on this?

**Comment by its-VinayKumar** [comment]
@palisadoes Please Assign me this issue :)

**Comment by palisadoes** [comment]
1. The title should be `Add Member` in the second image to reduce confusion.
1. There is an edit user screen design in the official figma that should be used as a guide. It will help with a more consistent UI/UX. What you have works for a quick addition, but we'll also need to figure out a way to easily add all the other expected user details if required. Possibly going directly to the more detailed user profile edit after adding. @aashimawadhwa has been working on some ideas for this. Try contacting her in slack for guidance, in addition to here in the GitHub comments. It may be faster

**Comment by palisadoes** [comment]
@disha1202 

In the interest of time. Go ahead with this design. We can open issues related to a final design later

**Comment by disha1202** [comment]
@palisadoes 
I'll proceed with the above designs and submit a PR soon.

**Comment by aashimawadhwa** [comment]
@disha1202 i think your designs are good to go for now. Just one question what is the use of exsisting user in the add member dropdown? In the first screenshot you attached.

**Comment by disha1202** [comment]
> @disha1202 i think your designs are good to go for now. Just one question what is the use of exsisting user in the add member dropdown? In the first screenshot you attached.

The existing user option is for adding a member in the organization which already exists but is not a member of the organization. Also when an admin clicks on the existing user option the modal the second image pops up with the list of all the user excluding the users which are already members of the organization.

**Comment by palisadoes** [comment]
@aashimawadhwa FYI. This is complete
