### ISSUE TITLE
Bug Report: Join Organization Error on "View All Organizations" Page

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-admin#1656]
**Describe the bug**
An error occurs when a user clicks on an organization card "Join now" listed on the "View all Organizations" page.

**To Reproduce**

1. Sign in as a User
2. Go to View all Organizations
3. Click on Join now
4. Error will Popup

**Expected behavior**
The error message should ideally be displayed in a toast format rather than being thrown directly onto the screen.

**Actual behavior**
The Error is thrown on the screen

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/490869b2-2650-4f98-a579-55a80b13f9db

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
I would like to work on this issue

**Comment by Cioppolo14** [comment]
@duplixx I just assigned you another issue, so now you already have 2 issues.   Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by duplixx** [comment]
@Cioppolo14  https://github.com/PalisadoesFoundation/talawa-api/pull/1675 This issue was resolved by me weeks ago and I am waiting for the review. I don't want this to be a blocker for my contribution @palisadoes can I get assigned in this issue

**Comment by Cioppolo14** [comment]
@duplixx I understand, hopefully we can get your PR moving forward soon.  For now, I must stick to our policy.

**Comment by duplixx** [comment]
@Cioppolo14  In that case, can I be unassigned from revamping the event screen Figma update and work on this issue? UI revamping can be done by new contributors as well.

**Comment by Cioppolo14** [comment]
@duplixx One of your PRs was merged, so you don't need to unassign from any issues.  We got it worked out.

**Comment by duplixx** [comment]
@palisadoes @Cioppolo14 Thank you 😊

**Comment by duplixx** [comment]
@palisadoes When a user joins an organization, there should be an option to leave it. Should I add this functionality for it as well. 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/f54d203a-ecae-479a-a762-7f2667e748c3)


here is the overview
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/45c1c472-c4fc-4138-a1d0-fc7ec869b9de)

**Comment by palisadoes** [comment]
You may not be using the latest code. Take guidance from this PR for design. 
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1628

**Comment by disha1202** [comment]
> You may not be using the latest code. Take guidance from this PR for design.
> 
> * [redesign: user portal organization screen #1628](https://github.com/PalisadoesFoundation/talawa-admin/pull/1628)

@palisadoes The design was updated a bit. Please refer to this comment https://github.com/PalisadoesFoundation/talawa-admin/issues/1511#issuecomment-1973005096

**Comment by disha1202** [comment]
@palisadoes @duplixx 
The actual issue is when you click on the `Join Now` button, the user is added to the organization but not reflected one the screen. Ideally it should refetch the data of the organization that the user has joined. 

https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/src/components/UserPortal/OrganizationCard/OrganizationCard.tsx#L61 Here instead of userId we'll have to pass the organizationId

This is a quick fix. Can you assign it to me?

**Comment by duplixx** [comment]
@disha1202 , I fixed the fetching issue and also added a try-catch block for handling errors, providing updates on the screen using a toaster. Thanks!

**Comment by disha1202** [comment]
> @disha1202 , I fixed the fetching issue and also added a try-catch block for handling errors, providing updates on the screen using a toaster. Thanks!

Cool Thanks @duplixx
