### ISSUE TITLE
Feature : LOGO REPLACEMENT  

### ISSUE THREAD

**Issue by reachaadrika** [PalisadoesFoundation/talawa-admin#166]
**Is your feature request related to a problem? Please describe.**
The Talawa Admin website , still shows the default React Icon in the title . 

**Describe the solution you'd like**
The default react icon should be replaced with the Original Palisadoes Foundation icon .

**Describe alternatives you've considered**
Replacing the icon with original Palisadoes icon .

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
![image](https://user-images.githubusercontent.com/64789514/143220029-9e8a662b-4974-4d2d-a251-256f3eebeee9.png)

**Comment by reachaadrika** [comment]
If this is a valid issue can I work on this

**Comment by yasharth291** [comment]
go on @reachaadrika

**Comment by reachaadrika** [comment]
Thank You @yasharth291 !

**Comment by reachaadrika** [comment]
Done with the PR !
