### ISSUE TITLE
Fix Organization Card Layout - Insufficient Data and Poor Layout

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1661]
**Is your feature request related to a problem? Please describe.**

1. The Organization cards on the `/orglist` URI page need to be updated with the end user in mind
1.  In a recent PR:
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1622
        1. The addresses were removed
        2. The descriptions overflow behind the manage button
1. If the organization names are all the same then you cannot identify them separately by the city location. This is a likely scenario where each organization in an API instance could be branch offices of the same organization, therefore having the same names. This is why the sample data has duplicate organization names to reduce the risk in our design.

**Describe the solution you'd like**

1. Restore the city and country information to the card. Add the first line of the address too. 
1. Place the Admins and Members information on the same line to save space
1. Truncate the description so that it will not overlap the manage button no matter how long it is. Make the fact that the text is truncated obvious and aesthetically pleasing. Think of a way to view the entire description if necessary without having to click.
1. Adjust the dimensions of the card if necessary
1. Use our Design System Figma files as a guide. Be aware that the figma design does not take these factors into consideration and will need to be updated.
    1. https://docs.talawa.io/docs/design/ux/ux-design-system/

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

1. Create a Figma example before starting
3. Ask @aashimawadhwa @rishav-jha-mech for design approvals before making a PR

**Additional context**

1. Current Design
    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/7e5084e6-c165-48fe-b0a5-bdce7035cf28)

1. Previous Design
    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/f54947ec-56b7-47f3-8d5f-c9fd11010824)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by its-VinayKumar** [comment]
@palisadoes Please assign me this issue.

**Comment by palisadoes** [comment]
@AmitSharma512 I think you should work on this. You need to rectify the original PR.

**Comment by AmitSharma512** [comment]
@palisadoes yeah sure, plz assign me the issue.

**Comment by AmitSharma512** [comment]
@palisadoes can you please close the last issue for which I have submitted the PR.

**Comment by AmitSharma512** [comment]
@palisadoes have a look at this new design

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/baf3d6d9-8bf2-4d03-8ac6-3bc76869f722)

**Comment by AmitSharma512** [comment]
@palisadoes, I guess we should make the "line 1" address compulsorily filled so we can get the whole address.

**Comment by palisadoes** [comment]
Thanks

1. Put the address immediately below the organization name
2. Remove the map pin icon
3. Yes, we should make `line 1` compulsory because of this
4. Make sure this is applied to both the Admin and User portal screen designs
5. Create a PR when ready

**Comment by AmitSharma512** [comment]
> Thanks
> 
> 1. Put the address immediately below the organization name
> 2. Remove the map pin icon
> 3. Yes, we should make `line 1` compulsory because of this
> 4. Make sure this is applied to both the Admin and User portal screen designs
> 5. Create a PR when ready

Sir, I guess we should put the address on the last line only because description should be just below the Name.

**Comment by palisadoes** [comment]
The member and admin counts should be last. They are the least important data points for the admin. The address can be below the description
