### ISSUE TITLE
GraphQL Validation Error when Querying allotedRoom and allotedSeat in eventCheckIns

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-admin#1662]
**Describe the bug**
When executing the GraphQL query for eventCheckIns, which includes fields allotedRoom and allotedSeat in the checkIn object, the server returns a GraphQL validation error. The error messages indicate that these fields cannot be queried on the type CheckIn.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/52276473/4ca4d173-fa77-4786-9c25-b069734b0328)
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/52276473/8d6ec241-31dd-4d5d-9514-484866883af1)

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cioppolo14** [comment]
For whoever becomes the assignee of this item: Please verify that allotedseat and allotedroom are completely unused. If so, functionality of allotedSeat & allotedRoom can be removed.

**Comment by krishna619** [comment]
@Cioppolo14 
If possible,Assign this to me

**Comment by krishna619** [comment]
It has been covered in https://github.com/PalisadoesFoundation/talawa-admin/pull/1744

Closing
