### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by DecodeAndCode** [PalisadoesFoundation/talawa-admin#1674]
**Describe the bug**
Drop down button is stuck to top of white background, proper spacing is needed.

**To Reproduce**

1. go to any organization.
2. go to left drawer.
3. click fund section.

**Expected behavior**
Proper margin is needed from the top.

**Actual behavior**
stuck to top no margin provided.

**Screenshots**

**BEFORE-**

<img width="1440" alt="Screenshot 2024-03-06 at 3 53 39 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/107995043/d276f59c-5b8e-448d-a7a5-eb970d91a422">

**AFTER-**

<img width="1433" alt="Screenshot 2024-03-06 at 4 04 34 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/107995043/5d3c7d4a-9eca-4864-b3ef-d93c850cf3a6">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by DecodeAndCode** [comment]
I would like to fix this issue.

**Comment by Cioppolo14** [comment]
Thank you for your issue suggestion. We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

I am going to close this issue.
