### ISSUE TITLE
Add Support for Organization Agenda Item Categories

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1676]
**Is your feature request related to a problem? Please describe.**

1. Add CRUD support for the newly implemented organization agenda item categories in the API

**Describe the solution you'd like**
1. Add the feature to the current Admin organization settings section
1. Follow the Figma design guide look and feel. This screen has not been designed.
    1. https://docs.talawa.io/docs/design/ux/ux-design-system

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Related Issues**

- https://github.com/PalisadoesFoundation/talawa-api/issues/1588
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1676

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by takshakmudgal** [comment]
I would like to contribute to this issue.

**Comment by meetulr** [comment]
@palisadoes @takshakmudgal  I think there's been typo, this issue refers to Agenda Category, right? Action Item Category is already implemented in api and admin.

**Comment by palisadoes** [comment]
Thanks @meetulr you are correct. @takshakmudgal take note. The issue and title has been adjusted

**Comment by takshakmudgal** [comment]
Alright @palisadoes thanks @meetulr I'll look into it!

**Comment by takshakmudgal** [comment]
I am having problems with this issue, and would like someone to take a look at my branch and guide me with that.
https://github.com/takshakmudgal/talawa-admin/tree/takshakmudgal/1676

**Comment by Atharva-Kanherkar** [comment]
Hi @takshakmudgal , can you please update me with whatwork have you done? I am working on the same parent issue, so i think if we could coordinate, it would be better. Can you please tell me what components have you already made? And if you have any doubts regarding agendas, you can ask me as i have implemented them in API too.

**Comment by palisadoes** [comment]
unassignining due to inactivity

**Comment by gautam-divyanshu** [comment]
working this issue

**Comment by Atharva-Kanherkar** [comment]
hi @gautam-divyanshu should we connect on slack because this is a common issue i am working on, so that the frontend designs are common and do not intercept each other?

**Comment by gautam-divyanshu** [comment]
@Atharva-Kanherkar Okay

**Comment by gautam-divyanshu** [comment]
Working on this issue, I was active because of health issues.

**Comment by palisadoes** [comment]
Unassigning. inactivity

**Comment by gautam-divyanshu** [comment]
@palisadoes  I have college exams, so I can continue after few days

**Comment by gautam-divyanshu** [comment]
@palisadoes  I've made significant progress, including creating mutations, queries, necessary components, and test cases. However, there are still some errors that need to be resolved. Since I have exams, I won't be able to dedicate as much time to this, but I'm aiming to submit a pull request by the first week of May. The pull request should be ready to merge by then.

**Comment by Atharva-Kanherkar** [comment]
@palisadoes Similarily for me. Me and @gautam-divyanshu are interacting on slack to get this done as soon as possible. How ever we both got exams until the first week of may. We will try our best to make a PR after exams. Thank you for your patience sir.

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by gautam-divyanshu** [comment]
Yes, my exams are just over.

**Comment by gautam-divyanshu** [comment]
Solving some errors
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/2a0120ad-2284-4434-8f38-d8a6c05916a4)

**Comment by gautam-divyanshu** [comment]
@palisadoes I am working with @Atharva-Kanherkar to complete this as soon as possible.

**Comment by gautam-divyanshu** [comment]
@palisadoes I will create PR end of this week.

**Comment by gautam-divyanshu** [comment]
@palisadoes @Atharva-Kanherkar Please take a look.

https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/74027912-7f64-4911-b7c5-61b049b2d9ef

**Comment by Atharva-Kanherkar** [comment]
> @palisadoes @Atharva-Kanherkar Please take a look.
> 
> https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/74027912-7f64-4911-b7c5-61b049b2d9ef
> 
> 

It looks good to me divyanshu!

**Comment by Atharva-Kanherkar** [comment]
@palisadoes please tell if any thing else can be added here.

**Comment by palisadoes** [comment]
How are pre-existing agendas affected when an agenda category is deleted?
