### ISSUE TITLE
Parent Issue: Add Support for Event Agenda Items

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1677]
## This is a parent issue for multiple related issues

**Is your feature request related to a problem? Please describe.**
Community based organizations will often need to have agendas for their events. Reasons for this requirement would include:

1. The order of ceremony for a wedding
2. The order of ceremony for a concert
3. Agendas for committee meetings

**Describe the solution you'd like**
The app needs to support the API's newly implemented ability to make events have agendas. The agenda has a sequence of agenda items with the following characteristics:

1. Title
1. Description
1. Agenda item type (See "Note" type below)
1. Agenda item type information (For example if an organization creates a type called "Song, they may want to make this track the key of the music)
1. Duration of the agenda item
1. Multiple Attachments stored on the system
1. Multiple URL links
1. Agenda item "User" to indicate a speaker, performer or similar party
1. Agenda item category which would come from a Agenda category list that is universal to the organization.
1. Agenda section which would allow agenda items to be grouped together. The section will require:
    1. A description
    1. An ordered sequence of sections so that they can follow one another
    1. An ordered sequence of agenda items belonging to a section

This is already implemented in the API schema. Mutations and queries have been created for:

1. Agenda sections and their sequencing within an event
1. Agenda items and their sequencing with a section
1. Agenda item URLs
1. Agenda item attachments
1. Agenda categories within an organization

There is a special type of agenda item:

1. Called a "Note"
1. Contains a description
1. No duration, no title, attachments, URLs, user 
1. Has all the other characteristics of an Agenda item in terms of sequencing
1. Could be identified by a `Note` flag field in the Agenda schema

There are some additional requirements:

1. When the first section is created, all existing agenda items must be tied to it while maintaining the agenda item order.
1. Changing the sequencing of an agenda section must not alter the sequencing of the agenda items within each section.
1. Changing the sequencing of agenda items must not alter:
    1. The sequencing of sections
    1. The sequencing of any other sections should other sections exist
1. You will need to write valid tests for this work
1. No other functionality must be affected

**Describe alternatives you've considered**
- N/A

**Approach to be followed (optional)**
- See above

**Additional context**
1. This issue would be best handled by someone who already has experience with updating our schema, mutations etc or can prove it in other scenarios. 

**Related and Child Issues**
- https://github.com/PalisadoesFoundation/talawa-api/issues/1588
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1676

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by rahulch07** [comment]
@palisadoes as this is a big feature request I would like to provide help if needed.

**Comment by takshakmudgal** [comment]
I would like to contribute to this issue.

**Comment by Atharva-Kanherkar** [comment]
@palisadoes I'm eager to enhance the admin portal by designing and implementing more advanced and feature-rich functionalities on the frontend. 
Considering that I've also developed the backend code, I believe this will facilitate a faster implementation process on the frontend.

**Comment by meetulr** [comment]
@palisadoes there's been a typo in the title, this issue refers to `Event Agendas`, right? support for `Event Action Items` has already been implemented in both api and admin.

**Comment by palisadoes** [comment]
Thanks @meetulr you are correct.

**Comment by Atharva-Kanherkar** [comment]
@palisadoes  I know right now we are focusing on the merging of develop and develop-userType fix, but can i make issues for Agenda Items Admin portal and Agenda sections? No work has been done and i think this is a good time to implement those.

**Comment by palisadoes** [comment]
OK
