### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ManashAnand** [PalisadoesFoundation/talawa-admin#1679]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
On the organisation page as a user , I can direct to base url after clicking the logo

**Describe the solution you'd like**
By putting a simple route handler we can give better user experience

**Describe alternatives you've considered**
We can also redirect it to different path as you suggest for better experience

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.
Just a appropriate route handler will work 

**Additional context**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/91553087/5d23a31b-0076-4883-9e54-154fee81351f)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ManashAnand** [comment]
I would like to work on this issue
Please assign the issue to me

**Comment by Cioppolo14** [comment]
Thank you for your submission. We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy. I am going to close this issue as unplanned for now.
