### ISSUE TITLE
UserUpdate always tries to update the current logged in user

### ISSUE THREAD

**Issue by nitishkumar333** [PalisadoesFoundation/talawa-admin#1680]
**Describe the bug**
When we try to update user details (of other users), we always try to update the current logged in user.

**To Reproduce**

1. Login to Talawa admin
2. Go to People's page in Organization
3. Edit any user details

**Expected behavior**
Details should be updated of the respective user.

**Actual behavior**
Always tries to update the current logged in user no matter which user we edit.

https://github.com/PalisadoesFoundation/talawa-admin/assets/123248648/6911ee95-edb5-4e72-825f-2e19b7a16edc

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by nitishkumar333** [comment]
Please assign it to me.

**Comment by Cioppolo14** [comment]
@nitishkumar333 Have you searched to see if there is already an issue out there for this? I think there is but I'm having trouble finding it right now.

**Comment by nitishkumar333** [comment]
@Cioppolo14 yes you are right, there is an open issue for it #1499 it's corresponding talawa api PR is not merged yet that's why the problem still exists. I will ask to reopen this issue if it doesn't get merged. Thank you.
