### ISSUE TITLE
Fix the `MemberDetail` Screen in the `develop-userTypeFix` branch

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1682]
### NOTE

1. This issue will require close coordination with persons assigned issues in the reference section.
1. This work will need to be done on the `develop-userTypeFix` branch

**Describe the bug**

1. The schema doesn't apply a person's `userType` by organization. 
1. The `userType` is currently a part of the `User` definition not part of a `userOrganization` definition or something similar. 
    1. This means that an `Admin` is an `Admin` for all organizations which grants the same rights as a `SuperAdmin`. This is not the intention.
    2. This has created historical confusion in the `Admin` and `SuperAdmin` roles.
1. We have created the `develop-userTypeFix` branch from the `develop` branch to fix this.
     1. All remedial work is being done on the `develop-userTypeFix` branch 
     2. When the development work is complete on the `develop-userTypeFix` branch it will be merged back into `develop`
     1. This is planned to be completed shortly
1. This issue was created to apply the desired functionality for the screen in this issue's title
    
This needs to be resolved as it is a showstopper bug.

**Expected behavior**

These conditions must apply:

1. The `userType` must be applied per person per organization.
1. Each `SuperAdmin` must be a `SuperAdmin` for all organizations
1. All other `userType`s would be on a per organization basis
1. This has already been implemented in the `develop-userTypeFix` branch of Admin and the API. Your role will be to apply the change to the screen in this issue's title to the `develop-userTypeFix` code.
4. **The new functionality of `userType` must be unchanged.**
5. No other features must be affected
6. All tests must be valid and pass

**Screenshots**

The current API schema:

![image](https://github.com/PalisadoesFoundation/talawa-api/assets/16875803/cbd791b2-3ff7-44b9-b936-023c9d979b01)

The new API schema:

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/eb274dc6-878f-4bd2-b711-a8fc38042b71)

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**

1. This is going to require someone with experience with the repo, or proven long term experience with typescript, MERN, and / or graphQL in their GitHub profile
1. Research these issues for context with the new `userType` functionality:

Related issues:

1. https://github.com/PalisadoesFoundation/talawa-api/issues/1711
1. https://github.com/PalisadoesFoundation/talawa/issues/2373
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1445
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1451
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1452
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1862
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1904
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1445
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1682
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1683
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1684
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1685
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1686

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by adi790uu** [comment]
@palisadoes can you assign me this one.

**Comment by pranshugupta54** [comment]
This issue will conflict with the current Admin panel re-design - #1667

**Comment by adi790uu** [comment]
@pranshugupta54 when we merge the develop-userTypeFix to develop this should be fixed at that point for now I believe it's fine to merge this PR in develop-userTypeFix branch.
