### ISSUE TITLE
Unexpected behaviour of npm run setup

### ISSUE THREAD

**Issue by Sourabh-awasthy** [PalisadoesFoundation/talawa-admin#1689]
**Describe the bug**
the command written in documentation to setup (npm run setup) is not working as expected it must be corrected by editing package.json manually.

**Expected behavior**

**Actual behavior**
the npm run setup should work like tsx setup.ts command

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/116659744/28fb3d7d-dfee-4a2d-a0db-a42ec34563e6)

**Comment by Cioppolo14** [comment]
@Sourabh-awasthy Are you running node.js version 20?

**Comment by Sourabh-awasthy** [comment]
@Cioppolo14 NO npm install was not working in v20 so i am now using v18.19.1

**Comment by varshith257** [comment]
@Cioppolo14 There are many package compatibility issues with node v20. To get further move to check the packages which aren't compatible with node v20 the node saas issue has to be resolved  #1503

**Comment by palisadoes** [comment]
The `sass` upgrade package has been merged.
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1503

This issue doesn't appear any more for v20. Closing unless it needs to be reopened for other compatibility reasons.
