### ISSUE TITLE
Plugin.helper.ts fetches endpoints that do not exist

### ISSUE THREAD

**Issue by aarishshahmohsin** [PalisadoesFoundation/talawa-admin#1691]
**Describe the bug**
the file src/components/AddOn/support/services/Plugin.helper.ts contains endpoints that do not exist on the admin and the api.
due to this error the addon component does not work.

**To Reproduce**

1. go the plugin addon page
2. click on either the available or the installed plugins.

**Expected behavior**
They should fetch their respective plugins and properly display them

**Actual behavior**
```
    const result = await fetch(`http://localhost:${process.env.PORT}/store`);
    const result = await fetch(`http://localhost:3005/installed`);

```
these fetch statements are fetching endpoints that do not exist and hence are causing errors while opening the plugins

**Screenshots**

![Screenshot from 2024-03-09 14-04-59](https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/3bda6bd7-642d-4517-b342-1eb5efa58519)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@SiddheshKukade PTAL

**Comment by omsai11** [comment]
Here port is showing undefined check once that port is accessing or not

**Comment by omsai11** [comment]
@aarishshahmohsin change the port to 3005 may be it will work

**Comment by Devilshree123** [comment]
I would like to work on this issue.
Please assign this to me.

**Comment by SiddheshKukade** [comment]
@Devilshree123 This file is outdated. We need to delete this file.
