### ISSUE TITLE
Sidebar does not work on mobile devices

### ISSUE THREAD

**Issue by aarishshahmohsin** [PalisadoesFoundation/talawa-admin#1692]
**Describe the bug**
when on mobile devices , the sidebar does not work

**To Reproduce**

1. open admin portal on a mobile device
2. tap on the sidebar button

**Expected behavior**
the sidebar should open

**Actual behavior**
the sidebar does not open on tapping the button

**Screenshots**
![ezgif-1-3ee365039e](https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/9c7eb304-da72-48b4-87d6-f3a31ff3b3ce)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by wasifkareem** [comment]
Hi @aarishshahmohsin , are you working on this?? if not I would like to work on this. @palisadoes

**Comment by Cioppolo14** [comment]
The sidebar is being addressing in #1510. I am going to close this as a duplicate.
