### ISSUE TITLE
[userTypeFix] Update queries for new `adminApproved` functionality

### ISSUE THREAD

**Issue by Shubh152** [PalisadoesFoundation/talawa-admin#1693]
**Is your feature request related to a problem? Please describe.**
Changes to queries have to be made in Admin repo corresponding to https://github.com/PalisadoesFoundation/talawa-api/issues/1862

**Describe the solution you'd like**
Change GraphQl Queries

**Describe alternatives you've considered**

**Approach to be followed (optional)**
Make changes only in the "develop-userType" branch

**Additional context**
follow this issue's description -> https://github.com/PalisadoesFoundation/talawa-api/issues/1862

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Shubh152** [comment]
@palisadoes Please assign me this issue as it is linked to the API repo issue https://github.com/PalisadoesFoundation/talawa-api/issues/1862

**Comment by Huy1996** [comment]
@Shubh152 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Shubh152** [comment]
Sorry for the trouble. Please assign this to others, I asked as it was linked to a current issue I was solving.

**Comment by Manik2708** [comment]
Can I work on this issue, as I am already working on an issue related to it!

**Comment by Rajeshpatel07** [comment]
@Huy1996 @Shubh152 
Do have to wait until the issue https://github.com/PalisadoesFoundation/talawa-api/issues/1862 
has been resolved. Can you please clarify to me.

**Comment by Rajeshpatel07** [comment]
@palisadoes @Huy1996 
I have a doubt about the queries.Do I have to update the queries according to this https://github.com/PalisadoesFoundation/talawa-api/pull/2013 PR or should i have to update all queries according to other related issue aswell. Like

In this talawa-admin mutations.ts the in LOGIN_MUTATION there is a adminApproved this is causing problem while login. In the user model there is no adminApproved field this is causing the problem.

[user login.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/145205731/d9c39c5e-989a-45fd-853d-67e31eeb4179)

After importing sample data some of the user don't have AppUserProfile field in them this is causing problem when we login as a superadmin and see the users.

[sample data.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/145205731/9cb53ca8-0d77-4e62-b6bf-e7e75e764fcf)

So can you please clarify

**Comment by palisadoes** [comment]
You will need to use the `develop-userTypeFix` branch in all repos. @Shubh152 will be able to provide additional guidance
- https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql

**Comment by Rajeshpatel07** [comment]
I am in the `develop-userTypeFix` branch. And I want to know that should I have to update other queries aswell or only regarding to this
 https://github.com/PalisadoesFoundation/talawa-api/blob/develop-userTypeFix/schema.graphql

Thank you for the guidence

**Comment by palisadoes** [comment]
Just adminApproved for now

**Comment by Shubh152** [comment]
@Rajeshpatel07 the login mutation in the admin repo queries for the adminApproved flag from the User model which is wrong and this should be changed to query from the AppUserProfie model.

**Comment by Rajeshpatel07** [comment]
@Shubh152 If there are any other things to change just tell about it. Thank you for the guidence.

**Comment by Shubh152** [comment]
As part of this issue, you have to change all the queries and mutations that try to query adminApproved flag from the User profile. Search the repo to find wherever it is this way.

**Comment by palisadoes** [comment]
1. Are you still working on this?
2. The changes still need to be applied to the `develop` branch

**Comment by palisadoes** [comment]
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by Rajeshpatel07** [comment]
Previously I created a PR for this issue in  `develop-userTypeFix `branch  but it had codecov patch 75℅ so I marked it as a draft and added tests to it. Before I can  push the changes the PR was closed. So I assumed that this issue was closed. 

So now should i work on this in `develop` branch.

**Comment by palisadoes** [comment]
Yes

**Comment by Rajeshpatel07** [comment]
@palisadoes 
I have done all the changes regarding to the `adminApproved` but when I commit my change It is giving me `eslint` error for type `any`. I changed them to type `unknow` or `object` and tried to write interface aswell. It is still giving me error. So can you tell me what to do.

![commit error eslint](https://github.com/PalisadoesFoundation/talawa-admin/assets/145205731/19419f10-3800-4750-9549-8fc5cdd38334)

Additional info:
In this commit the `eslint` configuration is changed https://github.com/PalisadoesFoundation/talawa-admin/commit/f309a48eaceaa6b93803e6844c15d98aa67243c6

**Comment by adi790uu** [comment]
@Rajeshpatel07 try to fix these you might have done some changes in this particular file.

**Comment by palisadoes** [comment]
Closing. There is an active discussion about how to approach this.
- https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1711717178931399
