### ISSUE TITLE
Issue: Missing Steps for Setting Up Project for ContributorsBug Report

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [PalisadoesFoundation/talawa-admin#1699]
**Describe the bug**
Currently, the documentation for setting up the Talawa Admin project for contributors lacks essential steps, leading to potential confusion and inefficiencies in the onboarding process. These missing steps are crucial for ensuring contributors can effectively set up the project environment and make meaningful contributions to the codebase.

**Missing Steps:**
1. After switching to the develop branch, contributors need to run npm install to download all the required packages.
2. Once the packages are installed, contributors should run npm run serve to start the development server. The project will be accessible at http://localhost:4321/.
3. Upon accessing the project, contributors need to sign in by selecting a user. 

**Expected behavior**
The expected behavior is that the documentation for setting up the Talawa Admin project for contributors includes all necessary steps to ensure a smooth onboarding process. Specifically, after following the documented steps, contributors should be able to successfully set up the project environment, run the development server.

**Actual behavior**
Upon reviewing the setup documentation for the Talawa Admin project, it was found that essential steps were missing, leading to potential confusion and inefficiencies for contributors. Specifically, the steps for running npm install to download required packages, starting the development server with npm run serve, and making oneself an administrator after signing in were omitted. This deviation from the expected behavior hinders new contributors' ability to effectively set up the project environment and proceed with testing and development.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/94298791/b5b6d7f7-d12b-4011-8a92-25dc4a3e112f

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by i-am-SnehaChauhan** [comment]
Hey, could you please assign this task to me? I'll make the required changes in the CONTRIBUTING.md. file.

**Comment by pranshugupta54** [comment]
Hey @i-am-SnehaChauhan, you missed out INSTALLATION.md
> https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/INSTALLATION.md
