### ISSUE TITLE
Add and test GitHub action to lint all PRs before submission

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#17]
We need to lint all code as part of the pull request process. 

1. The commands for the actions file can be found at the beginning of the documentation of this [outdated GitHub action](https://github.com/marketplace/actions/run-eslint)
1. We will need the action to be activated only on a pull request. [We have an example of how to do that in the Talawa repo](https://github.com/PalisadoesFoundation/talawa/blob/master/.github/workflows/linter.yml)
1. Make the action be defined in a file named `linter.yml`

Test and make sure it doesn't break the code. Try running the linter on the code base as proof.

**Comment by yasharth291** [comment]
should i work on this @palisadoes sir

**Comment by yasharth291** [comment]
please can you assign me this

**Comment by yasharth291** [comment]
thanks sir

**Comment by palisadoes** [comment]
@yasharth291 we are migrating to react @XshubhamX  is working on a pull request #24 

You will need to adjust the linting mechanism

**Comment by yasharth291** [comment]
yeah sir i am working on this please tell me what changes should i do regarding this

**Comment by palisadoes** [comment]
@yasharth291 I'm going to unassign this from you as #36 was closed

**Comment by palisadoes** [comment]
@yasharth291 Are you still working on this issue?

**Comment by yasharth291** [comment]
yeah sir i and @DangaRanga  sir are working together on it

**Comment by yasharth291** [comment]
if someone can do it then i will be happy to be assigned to anyone else

**Comment by DangaRanga** [comment]
It should be good to go now
