### ISSUE TITLE
[Feature][Plugins] Refactor UI Components 

### ISSUE THREAD

**Issue by xsh2047** [PalisadoesFoundation/talawa-admin#170]
Refactor UI Components to extend plugin components. This will allow for a consistent experience throughout the application when working with plugins for extending features.

**Comment by anshgoyalevil** [comment]
@palisadoes I would love to work on this issue. Can you please assign it to me.

**Comment by palisadoes** [comment]
@anshgoyalevil we are not accepting new features now. This issue is being covered by our [GSoC 2023 ideas](https://palisadoesfoundation.github.io/talawa-docs/docs/internships/internship-ideas)
