### ISSUE TITLE
[BUG] Invalid name and email on scroll

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1702]
**Describe the bug**
When we scroll down to fetch more users for the Roles screen, half of the data gets messed up

**To Reproduce**

1. Login via Admin panel
2. Goto `/users` (example: `http://localhost:4321/users`)
3. Scroll down
4. Users on top gets messed up

**Expected behavior**
Data should remain correct

**Actual behavior**
Incorrect data

**Screenshots**
https://www.loom.com/share/aaca8ef44a364130b55c1edf35d7e088?sid=a477502e-636c-4121-be2c-a4d5289daed0

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ShubhamTiwari55** [comment]
@pranshugupta54 Are you sure this issue is not specific to your machine as I am not facing this issue. Can you please elaborate the issue you are facing...

https://github.com/PalisadoesFoundation/talawa-admin/assets/125534462/9ea56dbb-49ea-404a-b26d-b2b7d1b02212

**Comment by pranshugupta54** [comment]
@ShubhamTiwari55, are you on the develop branch?

**Comment by ShubhamTiwari55** [comment]
> @ShubhamTiwari55, are you on the develop branch?

No, Main branch

**Comment by pranshugupta54** [comment]
Can you try out with `develop`? We only work on `develop`

**Comment by ShubhamTiwari55** [comment]
> Can you try out with `develop`? We only work on `develop`

Sure

**Comment by pranshugupta54** [comment]
The issue got fixed after resetting all the user data
