### ISSUE TITLE
GitHub Action: Fail when the PR source and target branches are the same

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1704]
**Is your feature request related to a problem? Please describe.**

1. We frequently have to close PRs when the source and target PR branches are the same. This means that our reviewers will not be able to checkout the changes and test on their systems using this methodology which will cause a rejection error:
    1. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
1. For example if a the author of the PR is working on the `develop` branch in their local repository and submits a PR to this repository's `develop` branch, then the PR reviewer will not be able to use the procedure in the link to review the operation of the code first hand.

**Describe the solution you'd like**

1. A GitHub action that is part of the code quality checks section that fails when the source and target branches are the same
    1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-request.yml
1. The YAML block added must clearly indicate that: 
    1. it's testing whether the source and destination branches are different. 
    2. the names of the source and destination branch names with explicatory text, possibly using one or more echo commands

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

- Here is a screen shot of an example where the two branches are the same. (`develop`)
    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/6c61e26c-9d97-4a02-9de4-74718d8f40d6)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
Can I get this assigned? All my assigned issues are already awaiting review so I'm up for solving more issues.

**Comment by Cioppolo14** [comment]
@pranshugupta54 We appreciate your willingness to contribute. Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues.   We will get your PRs reviewed soon.

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?
