### ISSUE TITLE
[Bug] Infinite scroll issue

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1706]
**Describe the bug**
On scrolling a user list, it automatically scrolls down till the end and also sorts them.

**To Reproduce**

1. Login as Admin
2. Goto `/users`
3. Scroll down after 12 then 24

**Expected behavior**
- After 12 users, it should stop at 24 users and then stop at 36.
- User list sequence should remain same

**Actual behavior**
- It goes from 12 to 24 to 36 automatically 
- It automatically sorts them

**Solution**:
- After scrolling from 12 users, it stops at 13. OR
- Use of pagination for the better user experience because of finite number of users

**Video**:
https://www.loom.com/share/5c39a600c172446fbb3c8fb6d2a7c30c?sid=47b71f0e-3566-4512-9dbe-31b7538aac37

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by rahulch07** [comment]
I would like to work on this. I would use pagination as it gives a good user experience.

**Comment by palisadoes** [comment]
Closing. We want infinite scrolling. That is our design goal for all screens

**Comment by pranshugupta54** [comment]
Hey @palisadoes, even if we want infinite scroll, the bug still needs to be fixed.
