### ISSUE TITLE
ADMIN REDESIGN: redesign the Community Profile for the talawa admin portal

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-admin#1708]
**Is your feature request related to a problem? Please describe.**
It is a part of planning to redesign the admin portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
Need to redesign the Community Profile for the admin portal.

**Screenshots**

- Attaching the screenshots for reference.

Desired Result:
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/45465b57-2f27-4b1a-a415-1d0ba23d0bed)

**Additional context**
Please refer to the Figma file for a detailed understanding :

https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3288-3727&mode=design&t=qTJr2o8FYMkmvBkt-0

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by DevToon** [comment]
Can I work on this

**Comment by palisadoes** [comment]
Closing. Duplicate This is covered in this PR
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1649
