### ISSUE TITLE
ADMIN REDESIGN: redesign the Organization Settings  for the talawa admin portal

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-admin#1709]
**Is your feature request related to a problem? Please describe.**
It is a part of planning to redesign the admin portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
Need to redesign the Organization settings for the admin portal.

**Figma:**
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3288-378&mode=design&t=Exs7w4AYXovWBFES-0

**Screenshots**

- Attaching the screenshots for reference.

Current:
![WhatsApp Image 2024-03-11 at 01 45 11_899ad962](https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/ef0d25f0-75d0-4564-8a52-eb7f2a2117a4)
![WhatsApp Image 2024-03-11 at 01 45 26_51e94d0b](https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/3cc99fbc-5672-4745-be1a-765e09334134)

Desired Result:
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/3f2392fd-27ca-4e7a-9390-83df7ef89812)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by DevToon** [comment]
Can I work on this

**Comment by palisadoes** [comment]
Closing. This is complete, the Figma is behind the implemented design
