### ISSUE TITLE
ADMIN REDESIGN: redesign the Organization Tag Detail for the talawa admin 

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-admin#1711]
**NOTE**

- This issue will require close coordination with persons assigned issues in the reference section.

**Is your feature request related to a problem? Please describe.**
It is a part of planning to redesign the admin portal, this issue is a part of that redesigning.

**Describe the solution you'd like**
Need to redesign the Organization tag detail for the admin portal.

**Figma:**
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3288-1217&mode=design&t=Exs7w4AYXovWBFES-0

**Screenshots**

- Attaching the screenshots for reference.

Desired result:
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/117595548/81f9f970-b7f9-4cda-8837-d5a9fb28fc7a)

**Additional context**

Related Issues :
1. #1612 
2. #1710 
3. #1711

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by varshith257** [comment]
@aashimawadhwa Is there anything to add related to the implementation of the Actions card above?

**Comment by palisadoes** [comment]
Thanks for working on this, however this is going to be covered in detail as a GSoC idea. Closing
- https://docs.talawa.io/docs/internships/gsoc/gsoc-ideas/#user-tag-management---talawa-admin

We appreciate your efforts on creating design issues, however the biggest need is to create issues to make the user portal screens UI/UX match that of Admin. Creating issues for those will be more beneficial
