### ISSUE TITLE
Video Post Creation - DOMException: The play() request was interrupted by a call to pause() 

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-admin#1713]
**Describe the bug**
When creating a post with a video upload and subsequently viewing the post, the following error occurs in the console: "Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause()."

**To Reproduce**

1. Create a post with a video upload.
2. View the created post.
3. Open the browser console.

**Expected behavior**
The video should play without any interruptions or errors when viewing the post.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/52276473/29a1e249-fa9d-4cfa-a604-c16c892480a9)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Devilshree123** [comment]
I think we're not handling the video play Promise in our code that's why the error message appears

Assign this issue to me I want to work on it.

**Comment by krishna619** [comment]
> I think we're not handling the video play Promise in our code that's why the error message appears
> 
> Assign this issue to me I want to work on it.

yes, it is due to the asynchronous function.

**Comment by Shreyas2309** [comment]
Hi ! I have raised a PR for this issue. Please review it .

**Comment by Shreyas2309** [comment]
#1727

**Comment by ALOK9442** [comment]
hello @dhanagopu,  can i work on this issue if no one is working?

**Comment by Cioppolo14** [comment]
@ALOK9442 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by palisadoes** [comment]
unassigning as the PR seems abandoned

**Comment by Shreyas2309** [comment]
Hello , I want to work on this please assign this to me.

**Comment by Cioppolo14** [comment]
@ALOK9442 If someone is assigned, please do not ask to be assigned.

**Comment by palisadoes** [comment]
Unassigning, inactivity

**Comment by AnshulKahar2729** [comment]
@palisadoes I would like to work on this issue.

**Comment by AnshulKahar2729** [comment]
> Unassigning, inactivity


@palisadoes @Cioppolo14 @varshith257

**Comment by palisadoes** [comment]
@AnshulKahar2729 

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by prayanshchh** [comment]
can i work on this issue @palisadoes
