### ISSUE TITLE
Events not rendering on UserPortal.

### ISSUE THREAD

**Issue by AmitSharma512** [PalisadoesFoundation/talawa-admin#1714]
**Describe the bug**
Events not rendering on UserPortal.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a User.
2. Create an organization with some events from the super admin account.
3. Now, Join the organization from the User account.
4. After joining the organization, go to the events section on the user portal.
5. You can see that no events are rendered

**Expected behaviour**
Events should be rendered.

**Actual behaviour**
No event is being rendered.

**Screenshots**
Event is made:
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/a71a75c5-55fc-4f1d-8c98-d3ce37cff29a)

UserPortal showing no events:
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/110725065/b13f515a-64a3-4fe7-8f62-703a37d8b798)

**Additional details**
It is essential to fix this bug because this page is used in one of the GSoC Projects, but the events are not rendered due to some bug.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AmitSharma512** [comment]
@palisadoes please assign me this issue as It is essential to fix this bug because this page is used in one of the GSoC Projects, and the events are not rendered due to some bug.

**Comment by pranshugupta54** [comment]
Hey @AmitSharma512, check the URL, do you have `id=1234...` in it? Make it `1234...`

**Comment by AmitSharma512** [comment]
@pranshugupta54, but the URL generated has id="123", so I guess the code should make it 123 rather than manually doing it as you suggested.

**Comment by pranshugupta54** [comment]
Yeah, should be fixed under #1510

**Comment by Cioppolo14** [comment]
@AmitSharma512 Is this still an issue?

**Comment by AmitSharma512** [comment]
@Cioppolo14 Yes, this issue still exists.

**Comment by Cioppolo14** [comment]
@AmitSharma512 I have assigned you, sorry for the delay.

**Comment by pranshugupta54** [comment]
Fixed in https://github.com/PalisadoesFoundation/talawa-admin/pull/1833.
@AmitSharma512, are you still facing this issue? Make sure to take pull from latest upstream.

**Comment by akhilender-bongirwar** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/f58306bf-366d-4307-abdc-a343a6ff0f22)

Works Fine. This issue can be closed.
