### ISSUE TITLE
ADMIN REDESIGN: Tweaks/Changes in leftdrawer and title section

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1718]
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the admin portal, this issue is a part of that redesigning flow.

**Describe the solution you'd like**
we want to make some changes in the sidenavbar(leftdrawer) and title section

**Screenshots**
- Attaching the screenshots for reference.

Desired Result:
we want this user profiles in all screens at the top right corner across talawa admin and talawa user portal for both of them.

![Screenshot 2024-03-12 at 5 30 38 PM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/0b0b235a-5a0c-413a-9d2f-d9ae4000fcab)

Also remove this section:
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/bc317101-cc41-4b6b-9aaa-c8165e0e3566)

Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
@aashimawadhwa can you assign me this issue

**Comment by DevToon** [comment]
Can I work on this?
