### ISSUE TITLE
[BUG] CheckIn doesn't work

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1722]
**Describe the bug**
The CheckIn feature for events doesn't work

**To Reproduce**

1. Make an event
2. Add some attendees
3. Login with Admin/SuperAdmin
4. Try to goto Event Dashboard and checkIn

**Expected behavior**
The CheckIn option should list all users and allow us to checkIn

**Actual behavior**
Throws error

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

Related issue: PalisadoesFoundation/talawa-api#2002

**Comment by pranshugupta54** [comment]
After getting more into Events structure, I found that checkIn model doesn't have `allotedRoom` and `allotedSeat`.

- The checkIn mutation should be fixed for `checkIn` (under `MARK_CHECKIN`)
- The `eventCheckIns` query should be fixed under `EVENT_CHECKINS`
- Also remove reference for this in `TableRow.tsx` file

**Comment by krishna619** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/issues/1662
I feel this covers it, might be a duplicate

**Comment by pranshugupta54** [comment]
Oh yeah, thanks!
