### ISSUE TITLE
Feature Request: Admin Redesign: Make the talawa members page responsive to mobile & standardise the set

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-admin#1735]
**Is your feature request related to a problem? Please describe.**
The current layout of the Talawa members page is not responsive to mobile devices, making it difficult for users to navigate and access information on smaller screens. This lack of responsiveness hampers user experience and accessibility, especially for those accessing the platform on mobile devices.
<img width="1205" alt="Screenshot 2024-03-17 at 4 59 42 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/65951872/e6589462-cc39-4c0a-aa09-2e034b4d0aba">

**Describe the solution you'd like**
I would like the Talawa members page to be redesigned to be responsive to mobile devices. This would ensure that users can easily view and interact with the content on the page regardless of the device they are using. Additionally, standardizing the set would enhance consistency and coherence across the platform.

 
**Approach to be followed (optional)**
Please provide your designs first to get assigned.

 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SiddheshKukade** [comment]
Please provide your designs first to get assigned.

**Comment by akhilender-bongirwar** [comment]
@SiddheshKukade, this issue should be handled in PR #1703

**Comment by palisadoes** [comment]
We can close this. The screen design has changed.
