### ISSUE TITLE
Feature Request: Minor tweaks in admin

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-admin#1737]
**Is your feature request related to a problem? Please describe.**
The current labeling and organization within the admin interface are causing confusion and inefficiency. Users are having difficulty navigating and understanding the functions due to unclear and inconsistent terminology.

**Describe the solution you'd like**

- [ ] Rename “Talawa Posts” to “Posts” to simplify and generalize the label, making it more intuitive for users.

- [ ] Rename “Talawa Block /Unblock” to “Block / Unblock” for clarity and consistency with action verbs.
- [ ] Remove the "manage ads" sub-heading from the advertisement page to declutter and streamline the interface.
- [ ] Remove the “events” subheading from the events page to simplify and unify the page structure.
- [ ] Rename “Talawa Settings” to “Settings” for consistency and clarity.
- [ ] On the Settings page, for the “Action Item categories” button, remove the hover effect to enhance usability and prevent confusion.
 

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
Can I work on this? 
(this is a minor change so I can implement it real quick)
(My PRs are under some minor review changes only)

**Comment by Cioppolo14** [comment]
@pranshugupta54 We try very hard to limit to 2 issues, and you currently have 3.  I realize they're all in the PR/review stage, but I'd like to leave this one to give another contributor a chance.

**Comment by adi790uu** [comment]
@Cioppolo14 I would like to fix this.

**Comment by adi790uu** [comment]
@Cioppolo14 this can be closed.
