### ISSUE TITLE
Display unique identifiers(Email Id) in add existing member functionality

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-admin#1738]
**Is your feature request related to a problem? Please describe.**
When adding an existing user to an organization in Talawa Admin, the interface currently displays only the names of the members. This can cause confusion when multiple members have similar or identical names.

**Describe the solution you'd like**
The system should display unique identifiers (such as email IDs) alongside member names to distinguish between members with similar names.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SiddheshKukade** [comment]
kindly attach screenshot for better reference.

**Comment by krishna619** [comment]
> kindly attach screenshot for better reference.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/52276473/9217ca13-cc9d-4353-9738-54659e4645ae)

**Comment by krishna619** [comment]
@SiddheshKukade Assign this to me

**Comment by krishna619** [comment]
Update: since usernames are undefined, I will raise a PR as soon as this PR https://github.com/PalisadoesFoundation/talawa-admin/pull/1844/ gets merged.

**Comment by palisadoes** [comment]
The PR has been merged. You can open your PR
