### ISSUE TITLE
Enum values

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1739]
Expanding the **enum** values in utilities for broader reusability.

Reason for addition:
- Multiple pull requests are encountering conflicts due to the absence of these elements. They are being added individually, leading to conflicts.

**NOTE:**
Kindly assign this task to me, as I am currently working on a related pull request where I have already integrated this enum.

**Comment by Cioppolo14** [comment]
I am going to close this.  If you feel this is needed, please complete the issue template as completely as possible and resubmit.

**Comment by pranshugupta54** [comment]
> I am going to close this. If you feel this is needed, please complete the issue template as completely as possible and resubmit.

@Cioppolo14, this is very much needed to avoid conflicts. I've added complete template and resubmitted #1741
