### ISSUE TITLE
Lint errors on running the project

### ISSUE THREAD

**Issue by Devesh21700Kumar** [PalisadoesFoundation/talawa-admin#174]
**Describe the bug**
Lint errors are seen on running the project locally.

**To Reproduce**

1. Run yarn serve on WIndows 11 OS.
2. RUn yarn lint --fix to see the *no files matched error*

**Expected behavior**
There should not have been any linting errors

**Actual behavior**
`No files matching the pattern "'**/*.{ts,tsx}'" were found. Please check for typing mistakes in the pattern.` 
The above error is observed.

**Additional details**

Changing single quotes to escaped double quotes i.e., 

From:

"lint": "eslint '**/*.{ts,tsx}'"
To:

"lint": "eslint \"**/*.{ts,tsx}\""

solved the issue.

**Comment by palisadoes** [comment]
@Devesh21700Kumar Please submit a PR for this.

**Comment by Devesh21700Kumar** [comment]
> @Devesh21700Kumar Please submit a PR for this.

#175 is the PR which resolves this issue

**Comment by yasharth291** [comment]
Wait a minute @Devesh21700Kumar  could you write while the server is running in the terminal. It would be better is you could make a screen recording of reproducing the issue, please. it is not at all clear to me.

**Comment by yasharth291** [comment]
closing issue as it is already solved
