### ISSUE TITLE
Adding enum values to utilities 

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1741]
**Is your feature request related to a problem? Please describe.**
Currently, the application lacks a comprehensive set of **enum** values, leading to limited options for categorization and classification.

**Describe the solution you'd like**
I would like to propose the addition of a variety of enum values to enhance the versatility and flexibility of the application. This would enable users to classify data more precisely and accurately according to various criteria.

**Describe alternatives you've considered**
One alternative could be to continue using the existing limited set of enum values. However, this may lead to difficulties in adequately representing certain types of data and could result in ambiguity or inconsistency.

**Approach to be followed (optional)**
Adding more `enum` values in utilities folder.

**Additional context**
- Multiple pull requests are encountering conflicts due to the absence of these elements. They are being added individually, leading to conflicts.
- Kindly assign this task to me, as I am currently working on a related pull request where I have already integrated this enum.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship [here](https://github.com/PalisadoesFoundation/talawa/issues/359).

**Comment by pranshugupta54** [comment]
please assign this

**Comment by Cioppolo14** [comment]
@pranshugupta54 Right now you have too many issues to assign another one. Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by pranshugupta54** [comment]
Got fixed in other PR. (https://github.com/PalisadoesFoundation/talawa-admin/pull/1858)
