### ISSUE TITLE
Bug - Privilege Escalation in Admin Dashboard Access

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-admin#1745]
**Describe the bug**
When a `user` tries to log in to the admin dashboard in Talawa, he encounters an error stating that they are not authorized which is obvious. However, upon intercepting the login mutation and modifying the response to set the `userType` to "ADMIN" and `adminApproved` to true, users are able to successfully log in to the admin dashboard. 

**To Reproduce**

1. Intercept the login mutation and modify the response to set userType to "ADMIN" and adminApproved to true.
2. Attempt to log in.
3. Notice that the user is now able to successfully access the admin dashboard.

**Expected behavior**
Admins and Super Admins should only be able to access the admin dashboard. Modifying the response of the login mutation to bypass authorization checks should not result in successful access to the admin dashboard.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/52276473/9a38510c-14bb-41fa-a94e-b5a1feb5542f)

https://github.com/PalisadoesFoundation/talawa-admin/assets/52276473/7ea8393d-148a-4233-b002-ec4ce9eeb766

test email : testuser3@example.com
userType: USER
adminApproved: false

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Abhinav232004** [comment]
@palisadoes Can you assign this issue to me?

**Comment by Kaushik-Nishant** [comment]
isn't this happening because testuser3@example.com must have been registered as an ADMIN also in the backend?

**Comment by Abhinav232004** [comment]
Nope,I was able to reproduce this bug, and it allows users to register as admins even if they are not admins in the backend

**Comment by pranshugupta54** [comment]
We can address this issue later, along with state management, which we plan to tackle between the GSoC 24 and 25 gap. Implementing a temporary fix isn't worth the time and effort right now.

cc: @palisadoes

**Comment by palisadoes** [comment]
OK. We'll close this issue
