### ISSUE TITLE
ADMIN REDESIGN: redesign the Event Management's Registrant tab for the talawa Admin portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1750]
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the admin portal, this issue is a part of that redesigning flow.

**Describe the solution you'd like**
we want to redesign the Event Management Registrant Tab for the talawa Admin portal
- we want to club show registrant and check-ins registrant in a single parent tab i.e registrant
- The show registrant is ready for now please leave check-in registrant button non functional for now.
- After clicking on the add registrant button , the registrant should dissapper from this screen after a react toast with success message.

**Screenshots**
- Attaching the screenshots for reference.

Current Situation:
![Screenshot 2024-03-20 at 12 22 18 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/3d8b26ac-0473-40e6-a04c-fa246cc0954e)

Desired Result:
![Screenshot 2024-03-20 at 12 17 14 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/e11d7269-2c8a-4ab0-9400-634f24f4ae56)

Related Issues: 

#1748

Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sahi1l-Kumar** [comment]
Can I get this issue assigned? I currently have 2 pull requests under review. I know the policy is to have only 2 issues assigned but since this issue is not getting traction I can work on it.

**Comment by Cioppolo14** [comment]
@Sahi1l-Kumar Thank you for your enthusiasm.  We do our best to stick with the 2 issue policy unless there is an important exception. I will work on getting your PRs reviewed soon.  Thank you for understanding.

**Comment by MahendraDani** [comment]
@Cioppolo14 Should I work on this?

**Comment by palisadoes** [comment]
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/27/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by MahendraDani** [comment]
@aashimawadhwa @palisadoes would you please explain the following:

### Current Situation:
<img width="1470" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/116940083/4352e600-fecb-4646-b55d-c40694e07d15">

The above screen is shown when we click on `Show Registrants` button in the event dashbaord.

  
<img width="1470" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/116940083/f237d6d6-7772-49e5-bdaf-9f9f4e89e6b7">

The above screen is shown when we click on `Check-In Registrants` button in the event dashboard.

### Expected Situation:
<img width="763" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/116940083/f1c71629-3469-4a72-966b-7877be7d5dee">


As I have understood the scope of this issue, we have to update the screens(modals) mentioned in Current Situation section above with the new design screens (tables).
Furthermore, we have to combine `Show Registrants` and `Check-In Registrants` button into one single button named `Registrants`.(This is to be displayed in top navbar)
 
![1](https://github.com/PalisadoesFoundation/talawa-admin/assets/116940083/f75c5f3e-7ab7-4b43-879d-cad47c7fcb21)
- Please refer to the highlighted section in `red color`

And below the top navbar, we have to provider two buttons `Check-In Registrants` and `All Registrants` which will change the list of registrants based on their check-in status.

  
![2](https://github.com/PalisadoesFoundation/talawa-admin/assets/116940083/1e64e7cd-d2b3-46e9-ac71-83289dcfa58e)
- Please refer to the highlighted section in `yellow color`

Please let me know if I am missing any detail. 
Thank you

**Comment by palisadoes** [comment]
Go ahead

**Comment by MahendraDani** [comment]
ok

**Comment by palisadoes** [comment]
This pull request was just merged which will help with your layout

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1878

**Comment by palisadoes** [comment]
Unassigning. 12 days without activity or PR

**Comment by Sahi1l-Kumar** [comment]
Please assign this issue to me

**Comment by Sahi1l-Kumar** [comment]
I think the `Add Registrant` column should be in a different `Non-Registrants` table.
The `All Registrants` table should have `Remove Registrant` option instead. What are your thoughts @palisadoes ?

**Comment by palisadoes** [comment]
Please work with @aashimawadhwa  on this.

**Comment by AnshulKahar2729** [comment]
@palisadoes  I would like to work on this issue.

**Comment by syedali237** [comment]
Can I be assigned this issue?

**Comment by duplixx** [comment]
@syedali237, what's the update on this issue? It's an important functionality that needs to be done for the MVP functionality to be working fine.

**Comment by syedali237** [comment]
Working on it, would need some more time.

**Comment by duplixx** [comment]
@syedali237 what's the update on this, if you facing any blockers please share it here

**Comment by syedali237** [comment]
@duplixx wanted to clarify a few things. Do I need to redesign the entire event management portal or simply add sections for "Check-in" and "All Registrants"? Here’s the current layout of the event management portal for reference: (if am looking at the wrong place, please can you correct me and guide me through it)

<img width="1440" alt="Screenshot 2024-11-23 at 1 24 24 PM" src="https://github.com/user-attachments/assets/08a5869a-4f7e-4119-a868-d81b1ea24b52">

**Comment by duplixx** [comment]
@syedali237, you don't need to redesign the whole thing. You just need to add check-in, all registrations, and a table of registrants to this tab. Refer to the existing people screen or attendance screen, or you can directly refer to the Figma design that was shared earlier.

**Comment by syedali237** [comment]
@duplixx I’ve created the basic structure of the EventRegistrants component for now. I have a couple of questions regarding the implementation: 
Since there is no separate collection for event registrations, and the data comes from the eventAttendance collection, should I filter users with `isRegistered = true` to display them as All Registrants? Similarly, for "Check-In Registrants," should I filter users with `isCheckedIn = true`?
Could you guide me on what the AddRegistrants button should direct to?

<img width="1438" alt="Screenshot 2024-11-25 at 4 47 29 AM" src="https://github.com/user-attachments/assets/7b0cc26f-27fa-4dc0-8c73-ed0db14810c8">

**Comment by duplixx** [comment]
@syedali237 
Great, the design looks good.
Check-in registrants should open up a modal where the volunteer can check in participants by searching for their names.(the modal is already built see` addRegistrantWrapper.tsx`)
The functionality of the Add Registrants button is similar to the Check-in button, as it will essentially add registrants to the attendees list.

**Comment by duplixx** [comment]
@syedali237 whats the update, if its done please raise the PR

**Comment by syedali237** [comment]
@duplixx Still working on it and need a bit more time. I’ll have it completed and raise the PR within this week.

**Comment by duplixx** [comment]
@syedali237 looks good

**Comment by palisadoes** [comment]
1. Please use the new universal stylesheet when creating the PR.
2. We are moving towards a color blind friendly design that the CSS supports

**Comment by syedali237** [comment]
@duplixx Could you please provide the new stylesheet?

**Comment by palisadoes** [comment]
It can be found here:
- https://github.com/PalisadoesFoundation/talawa-admin/tree/develop-postgres/src/style

**Comment by syedali237** [comment]
@duplixx @palisadoes  the package.json does not include a package @pdfme/common which is essential for generating a PDF while check-in, and also it's template has been already imported in several file. Can I add this package into the package.json as a check will be failing when this would be committed?

<img width="560" alt="Screenshot 2024-12-23 at 2 34 17 AM" src="https://github.com/user-attachments/assets/2c656ff3-ab22-4ca3-a7cb-a00eefe992e0" />

**Comment by duplixx** [comment]
@syedali237 
I don't think there will be any need of it 
use latest node version and use `npm i` to install latest node_modules

**Comment by syedali237** [comment]
@duplixx I have downloaded the latest node_modules. Earlier the only file that imports this package pdfme/common was not used in the codebase after developing the Event Registrants tab, when the admin check-ins a user a pdf is generated that uses this file as the template as shown above in the snapshot. So it is necessary to render this component in the Event Management Dashboard. 


<img width="1109" alt="Screenshot 2024-12-23 at 5 32 03 PM" src="https://github.com/user-attachments/assets/3266f131-dd35-4f4c-9964-d738168c9a59" />

With the component commented out it doesn't show any error but as I comment out the component, this error shows up:
(As the package is being used when rendering this component, without this package the functionality wont work)

<img width="1436" alt="Screenshot 2024-12-23 at 5 30 19 PM" src="https://github.com/user-attachments/assets/bf3b5c0e-f90a-43e7-a739-550203e3a9b6" />

**Comment by duplixx** [comment]
@syedali237 okay go for it.
