### ISSUE TITLE
ADMIN REDESIGN: redesign the Event Management's Action Items tab for the talawa Admin portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1751]
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the admin portal, this issue is a part of that redesigning flow.

**Describe the solution you'd like**
we want to redesign the Event Management's Action Items Tab for the talawa Admin portal
- This issue consist of the redesign of screen with table and the modals.

**Screenshots**
- Attaching the screenshots for reference.

Current Situation:
![Screenshot 2024-03-20 at 12 35 38 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/84f8453b-6f74-4344-b2ec-b7522b5fd7c7)

Desired Result:
![Screenshot 2024-03-20 at 12 33 08 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/8416b5e5-d23f-4004-a4fc-06ae6445b9f8)

Related Issues: 
#1748

Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sivam2313** [comment]
I would like to work on this.

**Comment by palisadoes** [comment]
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/27/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by palisadoes** [comment]
Unassigning. Inactivity, no PR

**Comment by Anvita0305** [comment]
Hello, I would like to work on this issue. Can you please assign it to me? Thanks!

**Comment by palisadoes** [comment]
This pull request was just merged which will help with your layout

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1878

**Comment by palisadoes** [comment]
Updating the UI/UX is important, especially in the Admin portal. How's progress?

**Comment by Anvita0305** [comment]
Yes, I have completed create modal and the table showing the details of action items. Will complete the update modal and raise PR asap.
