### ISSUE TITLE
ADMIN REDESIGN: redesign the Event Management's Event Statistics tab for the talawa Admin portal

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1752]
**Is your feature request related to a problem? Please describe.**
we are planning redesigning the admin portal, this issue is a part of that redesigning flow.

**Describe the solution you'd like**
we want to redesign the Event Management's Event Statistics Tab for the talawa Admin portal

**Screenshots**
- Attaching the screenshots for reference.

Current Situation:
![Screenshot 2024-03-20 at 12 38 51 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/a7795f47-1b8c-4b8d-9d0d-89e5b38af60f)

Desired Result:
![Screenshot 2024-03-20 at 12 39 07 AM](https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/4e189364-b399-4424-ba0e-8b34108d5655)

Related Issues: 
#1748 

Please refer the figma file for a detailed understanding : 
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=3447%3A59&mode=design&t=fkgMPaaz67qLwmMz-1

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by sahildkun** [comment]
Can i work on this issue

**Comment by palisadoes** [comment]
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/27/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by palisadoes** [comment]
Unassigning. Inactivity, no PR

**Comment by sahildkun** [comment]
I am working on it , got busy in work lately so could not keep u updated, Would you reassign me pls ?

**Comment by sahil-idk** [comment]
Pls assign the issue on this id if you can

**Comment by palisadoes** [comment]
@sahil-idk 

This is a priority issue. It requires someone with significant experience in the repo or an active GitHub profile using the technologies in the repo. Do you have that?

**Comment by sahil-idk** [comment]
> omeone with significant experience in the repo or an active GitHub profile using the technologies in the repo. Do you have that

yes I have experience in react and UI design and have starred repositories to showcase the skillset

**Comment by palisadoes** [comment]
This pull request was just merged which will help with your layout

- https://github.com/PalisadoesFoundation/talawa-admin/pull/1878

**Comment by palisadoes** [comment]
Updating the UI/UX is important, especially in the Admin portal. How's progress?

**Comment by sahil-idk** [comment]
> Updating the UI/UX is important, especially in the Admin portal. How's progress?

I had some troubles setting up the project then i set up the dev branch using the help of slack members and have started modifying the event stats page

**Comment by sahil-idk** [comment]
Can i know a simple thing on how to add reviews and feedback to events to populate my event stats window before i make changes 

![Screenshot from 2024-04-08 15-34-42](https://github.com/PalisadoesFoundation/talawa-admin/assets/141494404/04600efa-4f51-4b94-9251-70351eb58589)
](url)

**Comment by sahil-idk** [comment]
@aashimawadhwa @palisadoes   
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/141494404/fbbcf1e6-9cdc-4524-ace7-ec0466c3f1cc)

Just need  a confirmation that this will do right before i start writing tests for the components

**Comment by palisadoes** [comment]
OK. Please submit a PR

**Comment by palisadoes** [comment]
Use a new local branch and make the PR against `PalisadoesFoundation/develop`

**Comment by pranshugupta54** [comment]
Hey @sahil-idk, are you facing any issues? Feel free to ask!

**Comment by pranshugupta54** [comment]
Hey @sahil-idk, are you facing any issues? Feel free to ask!

**Comment by sahildkun** [comment]
> Hey @sahil-idk, are you facing any issues? Feel free to ask!

Yeah nothing just a bit busy in exams , can I make the PR after 2 may ? As that way I would be active to any changes in PR if some issue happens

**Comment by YashwantOstwal** [comment]
Please assign me this issue.

**Comment by sahil-idk** [comment]
@YashwantOstwal  the PR i made already fixed the issue the only issue was i didnt format the code so u  can refer and format/proper indentate   the code if you make th PR.  

https://github.com/PalisadoesFoundation/talawa-admin/pull/1955

**Comment by YashwantOstwal** [comment]
Sure man. Will mention your contributions in my PR, if it helps me. Also I am having a tough time in Forking the repository (talawa-Admin) along with (talawa-Api). Can you help me out?

**Comment by sahil-idk** [comment]
Yeah sure tell me what are you facing problem with

**Comment by avantika-rawat** [comment]
Is this issue still open?
Can I work on it?
