### ISSUE TITLE
Bug: Error on fetching Installed plugins  

### ISSUE THREAD

**Issue by lakshz** [PalisadoesFoundation/talawa-admin#1754]
**Describe the bug**

**To Reproduce**

1. Click on "Manage" for an Organization on `/orglist` 
2. Navigate to `Plugin` > `Plugin Store` 
3. Click on `Installed` to get the installed Plugins 
4. The error should appear with the following message:
<img width="1710" alt="Screenshot 2024-03-21 at 01 14 54" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/81241551/fa4b8ced-8ff3-467d-875c-e1fb1144b7bf">

**Expected behavior**
There should be no errors, and the installed plugins for an organization should be shown.

**Additional details**
The error is probably coming from the `src/components/AddOn/support/services/Plugin.helper.ts` file, which uses `process.env.PORT` in the fetch path. `process.env.PORT` is undefined.
 
<img width="809" alt="Screenshot 2024-03-21 at 01 25 05" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/81241551/ed7ada0a-e19f-4cc8-8c10-42a9acd5f910">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by M-SAI-SOORYA** [comment]
Can you assign this issue to me?

**Comment by Cioppolo14** [comment]
@M-SAI-SOORYA Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by varshith257** [comment]
@palisadoes Can I get this issue assigned? It is related to my GSOC Project Proposal. It will get me exposed more to the Plugin system in our Talawa. Will work on it if time persists before GSOC Applications deadline

**Comment by varshith257** [comment]
Will work on it soon.

**Comment by varshith257** [comment]
Working on it

**Comment by varshith257** [comment]
I didn't see any bug on this. Let me clarify with others and give a final decision on this issue.

**Comment by varshith257** [comment]
Fixing the bug. Will submit a PR ASAP
