### ISSUE TITLE
first-interaction action check fails due to deprecated workflow event

### ISSUE THREAD

**Issue by AvneetSingh2001** [PalisadoesFoundation/talawa-admin#176]
**Describe the bug**
The first time interaction GitHub action doesn't work.
When a user submits a PR for the first time in talawa, the first interaction action fails.

**Expected behavior**
The GitHub action checks must pass on pull request from a new contributor

**Actual behavior**
The GitHub action checks fail due to lack of required permissions.

**Screenshots**
<img width="300" alt="Screenshot 2021-12-09 at 11 42 17 PM" src="https://user-images.githubusercontent.com/77102514/145622173-8eeba68c-fa9b-41c1-b52d-05e2c624807f.png">

**Proposed Solution**
GitHub has solved this issue. Reference : https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

In the workflows, one simply needs to change the the event from pull_request to pull_request_target.

**Comment by yasharth291** [comment]
go on @AvneetSingh2001  best of luck

**Comment by AvneetSingh2001** [comment]
Hey @yasharth291, This issue is already solved in this repo. So, I should close this issue. Thanks a lot for assigning me this.
