### ISSUE TITLE
[userTypeFix] Toast error encountered when navigating to 'Block/Unblock' tab as super admin.

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1763]
**Describe the bug**
When logged in as a super admin and selecting any organization from the list, navigating to the "Block/Unblock" tab from the left side panel results in a toast error.

**To Reproduce**
1. Log in as a super admin.
2. Select any organization from the list.
3. Navigate to the "Block/Unblock" tab from the left side panel.

**Expected behavior**
Upon navigating to the "Block/Unblock" tab, the page should load without any errors, allowing the super admin to perform block or unblock actions on the selected organization.

**Actual behavior**
Upon navigating to the "Block/Unblock" tab, a toast error is displayed, preventing further action on the page.

**Screenshots**
<img width="1092" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/51e8d450-2676-44ac-80b8-2872359603e8">

**Additional details**
[Add any other relevant context or details about the bug here]

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Doraemon012** [comment]
@palisadoes I would like to work on this issue, please assign it to me.

**Comment by palisadoes** [comment]
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by palisadoes** [comment]
Unassigning. Inactivity, no PR
