### ISSUE TITLE
[userTypeFix] Error encountered in 'People' page after selecting organization as super admin.

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1765]
**Describe the bug**
After logging in as a super admin and selecting any organization from the list, navigating to the "People" page from the left panel results in a blank screen.

**To Reproduce**
1. Log in as a super admin.
2. Select any organization from the list.
3. Navigate to the "People" page from the left panel.

**Expected behavior**
The "People" page should display a list of users associated with the selected organization.

**Actual behavior**
Upon navigating to the "People" page, a blank screen is displayed, preventing the display of users.

**Additional details**
<img width="997" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/73df471d-bcad-42f2-b206-12b255f53655">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Hi 
Can I work on this?

**Comment by palisadoes** [comment]
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by disha1202** [comment]
This issue no longer persists.
<img width="1439" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/b9e19efc-4bbc-45f1-a494-b65dc26b0980">

It can be closed.
