### ISSUE TITLE
[userTypeFix] Continuous loading observed in 'Users' tab, no user data displayed when accessed as super admin.

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1766]
**Describe the bug**
Upon logging in as a super admin and accessing the 'Users' tab from the left panel, continuous loading is observed with no user data displayed.

**To Reproduce**
1. Log in as a super admin.
2. Navigate to the 'Users' tab from the left panel.

**Expected behavior**
The 'Users' tab should display a table with user data, including usernames, roles, and other relevant information.

**Actual behavior**
Upon accessing the 'Users' tab, the table continues to load indefinitely without displaying any user data.

**Additional details**
<img width="1437" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/3a281c36-4414-4f5e-94f9-940429981e56">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sahi1l-Kumar** [comment]
Can I work on this?

**Comment by Sahi1l-Kumar** [comment]
@palisadoes The solution for this issue is completely in the API. I can create an issue on the talawa-api and this can be closed.

**Comment by palisadoes** [comment]
OK. Please go ahead open the API issue and close this one only when that API PR is merged and we can verify

**Comment by varshith257** [comment]
@Sahi1l-Kumar Create an issue there, get it fixed and if it is s working fine. We can close this issue.

**Comment by Sahi1l-Kumar** [comment]
This issue can be closed now

**Comment by pranshugupta54** [comment]
Fixed in https://github.com/PalisadoesFoundation/talawa-api/issues/2047
