### ISSUE TITLE
[userTypeFix] Error encountered in Settings page (MemberDetail file) as superadmin.

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1767]
**Describe the bug**
When logged in as a superadmin and clicking on the User option (Avatar and username) from the left side panel in the Settings page (MemberDetail file), a blank screen is encountered.

**To Reproduce**
1. Log in as a superadmin.
2. Navigate to the Settings page (MemberDetail file).
3. Click on the "Username" option from the left side panel.

**Expected behavior**
Clicking on the "Username" option should display relevant user details or allow for user management actions.

**Actual behavior**
Clicking on the "Username" option results in a blank screen, preventing access to user-specific details or management options.

**Additional details**

<img width="1069" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/25012fb4-642b-42ab-aeda-a771337ee88a">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
@palisadoes I would like to work on this issue

**Comment by pranshugupta54** [comment]
This is irrelevant now, re-designed page for the left side panel is merged. 
User card is shifted to top right now.

**Comment by palisadoes** [comment]
@duplixx Should this be closed?
