### ISSUE TITLE
[userTypeFix] Error on Redirect if Tab closed and reopened on baseUrl

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-admin#1775]
**Describe the bug**
- If the user is logged in as user and then closes tab and reopens it from base url (here localhost:4321/) user is redirected to wrong screen causing error.

**To Reproduce**

1. Login as User
2. Close the tab
3. In new Tab enter base url (in this case `localhost:4321`)
4. Error is showned

**Expected behavior**
If we close the tab and reopen baseUrl `localhost:4321` then if previously logged in user is (Type) user should redirect to user home screen.

**Actual behavior**
If we close the tab and reopen baseUrl `localhost:4321` then error is shown.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/362d407a-bb71-4ed0-b363-8f45cbfba6fa

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/785e60bc-4fe3-4502-aa19-478b6487112c)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by GlenDsza** [comment]
@palisadoes would like to work on this issue

**Comment by GlenDsza** [comment]
@palisadoes I  am unable to create PR due to PR workflow scripts checking linting rules. Due to changes of strict linting in #1700 around 271 occurrences of `any` datatype need to be changed across repo before I could push a commit. 

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/4c240bdf-1351-4a5b-9cbf-88a582f83421)

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/4ed89aca-26ba-4d2a-9618-c30f011c8361)

How should this be handled, separate issue to all occurrences of `any` datatype or maybe easing of strict linting rules and then eventually eradicate use of `any` to implement strict linting?

**Comment by palisadoes** [comment]
Linting should be fixed
