### ISSUE TITLE
Test: Create tests for src/screens/OrganizationPeople/OrganizationPeople.tsx v2

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1784]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
This looks 100%,
> https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/blob/develop/src%2Fscreens%2FOrganizationPeople%2FOrganizationPeople.tsx

<img width="1386" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/38f1191f-6796-474c-bc03-4fc0ea092d13">
