### ISSUE TITLE
Test: Create tests for src/screens/OrgList/OrganizationModal.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1785]
We will need unittests done for all methods, classes and functions found in this file.

Any widgets, components, modals referenced in this file must also have unittests done

### PR Acceptance Criteria

- When complete this file must show at least **100%** coverage when merged into the code base. 
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
@palisadoes, do we really need a separate Test file for `src/screens/OrgList/OrganizationModal.tsx`. 
This modal is always used inside `src/screens/OrgList/OrgList.tsx` and should never be used separately. 

Currently the test file of `OrgList.tsx` is covering 32/37 tests for `OrganizationModal` (So creating a new file for this part will only produce duplicate code). I think it's better to cover the remaining 5 inside `src/screens/OrgList/OrgList.test.tsx` itself.
