### ISSUE TITLE
[Help-Needed] Error while running project

### ISSUE THREAD

**Issue by Devesh21700Kumar** [PalisadoesFoundation/talawa-admin#179]
While running Talawa-admin I get this error

![image](https://user-images.githubusercontent.com/59202075/145704101-39533d5e-ed0c-49fe-a8f2-c267ca64fce7.png)

I am running the talawa-api server which is on localhost:4000 but it seems that some other stuff has to be run in localhost:30005 as well.

What exactly do I need to run locally to fix this error?

**Comment by palisadoes** [comment]
@yasharth291 Please respond.

**Comment by Devesh21700Kumar** [comment]
@yasharth291  What do i run to avoid error in fetching from localhost:3005 ?

**Comment by yasharth291** [comment]
Sorry @Devesh21700Kumar @palisadoes  for the late reply I was out of station for some time and will be seeing this issue tomorrow

**Comment by xsh2047** [comment]
Hey, @Devesh21700Kumar this is an additional local JSON server. I thought the functionality was only triggered on interacting with the Plugins. (my bad)

I will be stubbing the functionality on the API and then I'll update the calls.

**Comment by Devesh21700Kumar** [comment]
> Hey, @Devesh21700Kumar this is an additional local JSON server. I thought the functionality was only triggered on interacting with the Plugins. (my bad)
> 
> I will be stubbing the functionality on the API and then I'll update the calls.

@xsh2047 so what's the way to bypass this instance and work on other features?
Can we just comment the calls to 3005 out and work on the rest?
