### ISSUE TITLE
[userTypeFix] Unauthorized Access of User in Admin Panel

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-admin#1792]
**Describe the bug**
If user tries to login in admin panel via user credentials then he is redirected to `/orglist` i.e. admin home page resulting in error screen. 

**To Reproduce**

1. Open Login Screen
2. Select Admin Login Tab
3. Enter User Credentials
4. User will be redirected to `/orglist` i.e. Admin Home page

**Expected behavior**
If user tries to login in admin panel toast displaying unautorized,etc should be shown and user must not be redirected to admin home page.

**Actual behavior**
If user tries to login in admin panel user is redirected to admin home page causing errors.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/021bf728-916f-4392-b2c3-30bdf524be95

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/2edfc491-6a08-46a8-a5b1-094e82339bb3)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by GlenDsza** [comment]
@palisadoes would like to work on this issue

**Comment by palisadoes** [comment]
We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.

1. When you create your PR, please link it back to this project:
    1. https://github.com/orgs/PalisadoesFoundation/projects/24/views/1
1. The process is simple. It can be found here:
    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

**Comment by GlenDsza** [comment]
@palisadoes should Admin/SuperAdmin be allowed to login to user portal as user with their admin credentials? Or Admin/SuperAdmin should as well be restricted to Admin Portal.

**Comment by varshith257** [comment]
I think it is better to have Admin/SuperAdmin login to the user portal with their credentials. As they are supreme authority they can get flexibility login wherever. But Admin doesn't want to login into SuperAdmin unless he is a SuperAdmin :)

**Comment by GlenDsza** [comment]
Got it

> I think it is better to have Admin/SuperAdmin login to the user portal with their credentials. As they are supreme authority they can get flexibility login wherever. But Admin doesn't want to login into SuperAdmin unless he is a SuperAdmin :)

Got it 👍

**Comment by GlenDsza** [comment]
> We are tracking this issue with one of our projects, and we'd like to track its progress especially as the GSoC announcement dates draw near.
> 
> 1. When you create your PR, please link it back to this project:
>    
>    1. https://github.com/orgs/PalisadoesFoundation/projects/24/views/1
> 2. The process is simple. It can be found here:
>    
>    1. https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar

@palisadoes Unable to link PR, maybe manually linking requires write permission to repo

**Comment by palisadoes** [comment]
Thanks. Are you able to give the PRa fix `userType` label?

**Comment by GlenDsza** [comment]
> Thanks. Are you able to give the PRa fix `userType` label?

No not able to add any labels

**Comment by palisadoes** [comment]
OK. That's good to know

**Comment by palisadoes** [comment]
1. We had to revert the PR. Please fix the errors, and merge with the latest upstream.
2. It appears you may have bypassed the husky protections in submitting your PR

**Comment by palisadoes** [comment]
@GlenDsza Please resubmit. I think I made a mistake in my previous note. This was probably caused by us updating the linting file while the PR was in progress.

Sorry

**Comment by GlenDsza** [comment]
> @GlenDsza Please resubmit. I think I made a mistake in my previous note. This was probably caused by us updating the linting file while the PR was in progress.
> 
> Sorry. Please accept my apologies.



> @GlenDsza Please resubmit. I think I made a mistake in my previous note. This was probably caused by us updating the linting file while the PR was in progress.
> 
> Sorry. Please accept my apologies.

Np sir will submit new PR by tonight
