### ISSUE TITLE
bug: Posts not visible on Organization Posts page

### ISSUE THREAD

**Issue by Doraemon012** [PalisadoesFoundation/talawa-admin#1796]
**Describe the bug**
When logging in as a user, posts are not displayed on the "Organization Posts" page.

**To Reproduce**

1. Open the Talawa Admin portal.
2. Log in as a user.
3. Navigate to a joined organization.
4. Notice that posts are not visible on the page.

**Expected behavior**
Upon visiting an organization's page, the posts should be visible.

**Actual behavior**
After logging in as a User, posts are not visible on the "Organization Posts" page.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/116624667/b6e215a8-3224-4921-8295-20d9ab0bb657)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by GlenDsza** [comment]
@palisadoes would like to work on this issue

**Comment by Cioppolo14** [comment]
@GlenDsza You currently have 2 issues. Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by GlenDsza** [comment]
@Cioppolo14 one of the issue is resolved now, would like to work on this issue
