### ISSUE TITLE
Create `Talawa-Admin` Installer

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#18]
# Introduction

1. We need a single CLI script or program to install Talawa Admin.
1. It must be 100% intuitive and worry free.
1. Must be able to run on Linux or Windows

# General Requirements

1. It is highly preferred that the user does not have to install any additional script interpreter other than those used to run Talawa-Admin.
1. Any failing OS commands must be logged to STDIO, STDERR and .
1. The script must fail if any underlying OS command fails.

The script must:

1. Not require the installation of any prerequisite packages for the script itself to run.
    1. This could be achieved by it installing any missing prerequisite packages for itself to run as part of its operation.
1. Install all required prerequisite packages for `Talawa-Admin` to operate
1. Activate `Talawa-Admin` upon completion of the script
1. Be a part of the `Talawa-Admin` code base
1. Be documented as part of the `Talawa-Admin` installation guide

# Installer Operation
The installation process must:

1. Prompt for:
    1. The API keys required to communicate with the `Talawa-API` server.
    1. The URL to use for communicating with the `Talawa-API` server.
1. Insert all information prompts in a configuration file.
1. Provide the web URL to use to access `Talawa-Admin`

# Post Installer Operation
1. The script (or a second script) must be able to be run to show the status of `Talawa-Admin`.
    1. This must display whether the connection to `Talawa-API` correctly operational
    1. This must display whether `Talawa-Admin` correctly operational

# Related Issue
- https://github.com/PalisadoesFoundation/talawa-api/issues/241

The ability to create organizations in the app must be removed.

**Comment by sumitra19jha** [comment]
@palisadoes Recently I have done course related to vue, Can I work on this issue?

**Comment by palisadoes** [comment]
@sumitra19jha  we are migrating to react as more contributors feel comfortable with it.

**Comment by sumitra19jha** [comment]
Ok. That's really great @palisadoes

**Comment by palisadoes** [comment]
@sumitra19jha are you still working on this?

**Comment by sumitra19jha** [comment]
No @palisadoes 
I am not working on this currently. Anyone interested can take up the issue

**Comment by palisadoes** [comment]
@sumitra19jha Please unassign yourself from any work you don't plan to do. Let's give others a chance to participate.

**Comment by sumitra19jha** [comment]
Sure @palisadoes

**Comment by sandeep-v1404** [comment]
Can I work on this issue?

**Comment by palisadoes** [comment]
@sandeep-v1404 You are already working on a lot of issues. Please focus on the three you already have open: 
- https://github.com/PalisadoesFoundation/talawa-api/issues/assigned/sandeep-v1404

**Comment by asmitsirohi** [comment]
Hello, I would like to work on this, could you please assign it to me.

**Comment by palisadoes** [comment]
This issue has been dormant for some time. We need someone to work on it ASAP. The original PR was:
- https://github.com/PalisadoesFoundation/talawa-admin/pull/208

The new assignee can use the PR as a base for completing the work.

**Comment by palisadoes** [comment]
@kailash360 are you still working on this? We need to implement the installer.

**Comment by palisadoes** [comment]
This was a good start but there are necessary improvements. The current installer needs to be modified to:

1. The installer must automatically generate token secrets if they don't already exist in the `.env` file. The result must be stored in the `.env` file.
1. Prompt for the Talawa-API URL to be used.
   1. The URL must be stored in the `.env` file
   1. Talawa-Admin must use the URL when launched. **There must be no hard-coded URLs in the code base**
