### ISSUE TITLE
Add a Logout Button on Organization list page

### ISSUE THREAD

**Issue by Prathamesh010** [PalisadoesFoundation/talawa-admin#180]
**Is your feature request related to a problem? Please describe.**
Currently, there is no logout option on the site, except the one that logs the user out of the organization page. 
If a user wants to log out he has to manually go to the '/' route and the local storage is cleared which is not a widely used logout flow.

**Describe the solution you'd like**
Add a Logout Button on the /orgList page. On clicking it, localstorage will be cleared and the user will be redirected to login page.

**Comment by palisadoes** [comment]
@ Prathamesh010 Good observation. I've assigned the bug to you. 

Do you want to work on it?

**Comment by Prathamesh010** [comment]
Yes, i am working on it.
