### ISSUE TITLE
Funds and Actions Items design Enhancements

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-admin#1801]
**Describe the bug**
There is an issue of overlapping present in new screens, such as Funds and Action Items.

**To Reproduce**

1.Sign in as admin/superadmin
2.Select any Organization
3.Select Funds/Action Items

**Expected behavior**
The UI should follow same structure in all screen's

**Actual behavior**
"Create" button overlaps with profile down

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/00bee9a3-9eca-4f91-92f5-b86f3c7181fe)
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/63e48254-3484-4571-a592-4d9afc76ab3a)

It should looks like this
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/ac908ce0-b3d9-4264-b448-23f6f0d3bb2a)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
@palisadoes good first issue for new contributors

**Comment by JeelRajodiya** [comment]
@palisadoes please assign this to me

**Comment by JeelRajodiya** [comment]
@duplixx 
I did find the create button misplaced under **action items** section

However, under the **funds** section it is aligned properly. Am I looking at the wrong section here?
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/63534268/d706693b-214b-4b29-ace4-c82b25da1ed0)

**Comment by duplixx** [comment]
yeah go ahead fix the action items alignment

**Comment by JeelRajodiya** [comment]
@duplixx you can close the issue
