### ISSUE TITLE
Admin: Store all dates in the database in UTC

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1813]
**Is your feature request related to a problem? Please describe.**

The Talawa applications assume that the:

1. user and organization are in the same timezone
1. API server and the organization are in the same timezone

This will create confusion when an organization’s stakeholders and its service providers are geographically dispersed.

For example someone someone in the US state of New Mexico creating and event in neighboring Texas will have concerns. There are some cities in the USA like Minneapolis and Kansas City that straddle timezones. 

**Describe the solution you'd like**

The client must:

1. Only update the database with date values in UTC. This means you will have to use the local timezone of the client as the basis for converting database times to UTC.
1. Convert dates read from the database to the local timezone of the client for presentation to the end user

There must be a date data conversion function that is used to make this consistent.

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

Related issues:

1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1800
1. https://github.com/PalisadoesFoundation/talawa-api/issues/2096
1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1813
1. https://github.com/PalisadoesFoundation/talawa/issues/2446

**Potential internship candidates**

- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
@palisadoes, should we use [UnixTimeStamp](https://www.unixtimestamp.com/) instead?

**Comment by palisadoes** [comment]
1. UTC would be the timezone. The aim is to use a methodology with minimal disruption to the database schema
2. Epoch is seconds since Jan 01 1970. (UTC)

**Comment by AVtheking** [comment]
I would like to work on this

**Comment by dhanagopu** [comment]
@AVtheking  Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects.  You have reached your limit, please wait until your existing issues are closed before requesting more issues.

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by aarishshahmohsin** [comment]
@palisadoes @dhanagopu 

The dates and times using in the repository are very inconsistent and would cause the use of a lot of different conversion functions to get this issue resolved. These should firstly be standardized to one format.

![imgonline-com-ua-twotoone-howjA6TR1FaZplq](https://github.com/PalisadoesFoundation/talawa-admin/assets/49566965/65ebbd40-100c-4acf-8710-c6ecdf00bbc8)

**Comment by palisadoes** [comment]
Yes. 

The aim is that the Talawa clients would convert their posted times to UTC and convert them to local times when they are displayed. 

Converting times to UTC for this issue would therefore be related to standardizing the way dates are stored in the database

**Comment by palisadoes** [comment]
Closing. We need to discuss this more here:
- https://github.com/PalisadoesFoundation/talawa-api/discussions/2222
