### ISSUE TITLE
Bug: Event Calendar functionalities not working 

### ISSUE THREAD

**Issue by meetulr** [PalisadoesFoundation/talawa-admin#1818]
### Describe the bug

**Some of the functionalities for the Event Calendar are not working.**

https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/429e8237-df3d-47e3-b07e-c28d0404587d

### To Reproduce

1. Go to the event Calendar.
2. Try changing months.
3. Try switching views.

**They're not working as expected.**

### Additional details

This bug was most likely introduced with one of the recent admin PRs.

Take a look at this PR, it might have caused it #1696, as it modified event calendar files, or some other PRs that modified the associated files.

**Comment by meetulr** [comment]
I won't be able to work on it for a couple days😅, anyone please feel free to take it, could be a good first issue.

**Comment by palisadoes** [comment]
@duplixx PTAL here

**Comment by duplixx** [comment]
@palisadoes I'll check for these errors once this issue's PR (#1608) gets merged, as some functionality might not work correctly until then.
