### ISSUE TITLE
[userTypeFix] Admin: Remove legacy references to `userType` 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1827]
**Is your feature request related to a problem? Please describe.**

We recently updated the code base to replace the authorization mechanism for users from being a `userType` field in the database’s User collection to an `appUserProfile` field.

**Describe the solution you'd like**

1. Though the updated code works, there are still many unused references to `userType` in the code base. 
1. Some of these references may still be accessible under certain circumstances creating malfunctioning code. These sections will need to be refactored.

The aim is for the  `userType`  to be removed, while maintaining the expected functionality of the app

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**

1. This is the project tracking the `userType` adjustment
    1. https://github.com/orgs/PalisadoesFoundation/projects/24/views/1
1. All tests must be valid and pass. There must be no reduction in test code coverage
1. All functionality must be maintained
1. These are the files that need to be updated in this repo

```
public/locales/en.json
public/locales/fr.json
public/locales/hi.json
public/locales/sp.json
public/locales/zh.json
schema.graphql
src/App.test.tsx
src/components/DeleteOrg/DeleteOrg.test.tsx
src/components/DeleteOrg/DeleteOrg.tsx
src/components/LeftDrawerEvent/LeftDrawerEvent.test.tsx
src/components/LeftDrawerEvent/LeftDrawerEvent.tsx
src/components/LeftDrawer/LeftDrawer.test.tsx
src/components/LeftDrawer/LeftDrawer.tsx
src/components/LeftDrawerOrg/LeftDrawerOrg.test.tsx
src/components/OrgAdminListCard/OrgAdminListCard.tsx
src/components/OrganizationScreen/OrganizationScreen.test.tsx
src/components/ProfileDropdown/profileDropdown.tsx
src/components/RequestsTableItem/RequestsTableItem.test.tsx
src/components/SuperAdminScreen/SuperAdminScreen.test.tsx
src/components/UserPortal/Login/Login.test.tsx
src/components/UserPortal/OrganizationSidebar/OrganizationSidebar.test.tsx
src/components/UserPortal/StartPostModal/StartPostModal.test.tsx
src/GraphQl/Mutations/mutations.ts
src/GraphQl/Queries/Queries.ts
src/screens/MemberDetail/MemberDetail.test.tsx
src/screens/OrganizationDashboard/OrganizationDashboard.test.tsx
src/screens/OrganizationEvents/OrganizationEvents.tsx
src/screens/OrganizationPeople/OrganizationPeople.test.tsx
src/screens/OrgList/OrganizationModal.tsx
src/screens/OrgList/OrgListMocks.ts
src/screens/OrgList/OrgList.tsx
src/screens/OrgSettings/OrgSettings.test.tsx
src/screens/Requests/Requests.test.tsx
src/screens/Requests/Requests.tsx
src/screens/UserPortal/Chat/Chat.test.tsx
src/screens/UserPortal/Events/Events.tsx
src/screens/UserPortal/People/People.test.tsx
src/screens/UserPortal/People/People.tsx
src/screens/UserPortal/Settings/Settings.test.tsx
src/screens/Users/Users.tsx
src/utils/interfaces.ts
src/utils/memberFields.ts
```

**Potential internship candidates**
- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
@palisadoes, how are we planning to work on this?
1) Spreadsheet like before and a common PR
2) Everyone gets assigned to this issue and works (Every user can make a separate issue themselves, link it to this parent issue and start working on it)

**Comment by palisadoes** [comment]
It was recommended in the slack discussion that this could all be handled by a single person because it was mostly removing unused code.

**Comment by pranshugupta54** [comment]
I'd like to work on this, please assign. (I have only 1 assigned -> issue template -> PR already in review)
I'll make multiple PRs to fix this (Probably categorize similar files like Org, User, Admin etc)

**Comment by pranshugupta54** [comment]
@palisadoes, after checking more files - I found that some of them are actually bugs. Not all of the code is un-used. 
Some of the code is making changes in features like Delete org and etc doesn't work. 

I'll make separate PRs for each of these fixes so that it's easy to review and merge.

**Comment by pranshugupta54** [comment]
@Cioppolo14 / @palisadoes, please assign

**Comment by pranshugupta54** [comment]
- [ ] public/locales/en.json
- [ ] public/locales/fr.json
- [ ] public/locales/hi.json
- [ ] public/locales/sp.json
- [ ] public/locales/zh.json
- [ ] schema.graphql
- [ ] src/App.test.tsx
- [ ] src/components/DeleteOrg/DeleteOrg.test.tsx
- [ ] src/components/DeleteOrg/DeleteOrg.tsx
- [ ] src/components/LeftDrawerEvent/LeftDrawerEvent.test.tsx
- [ ] src/components/LeftDrawerEvent/LeftDrawerEvent.tsx
- [ ] src/components/LeftDrawer/LeftDrawer.test.tsx
- [ ] src/components/LeftDrawer/LeftDrawer.tsx
- [ ] src/components/LeftDrawerOrg/LeftDrawerOrg.test.tsx
- [ ] src/components/OrgAdminListCard/OrgAdminListCard.tsx
- [ ] src/components/OrganizationScreen/OrganizationScreen.test.tsx
- [ ] src/components/ProfileDropdown/profileDropdown.tsx
- [ ] src/components/RequestsTableItem/RequestsTableItem.test.tsx
- [ ] src/components/SuperAdminScreen/SuperAdminScreen.test.tsx
- [ ] src/components/UserPortal/Login/Login.test.tsx
- [ ] src/components/UserPortal/OrganizationSidebar/OrganizationSidebar.test.tsx
- [ ] src/components/UserPortal/StartPostModal/StartPostModal.test.tsx
- [ ] src/GraphQl/Mutations/mutations.ts
- [ ] src/GraphQl/Queries/Queries.ts
- [ ] src/screens/MemberDetail/MemberDetail.test.tsx
- [ ] src/screens/OrganizationDashboard/OrganizationDashboard.test.tsx
- [ ] src/screens/OrganizationEvents/OrganizationEvents.tsx
- [ ] src/screens/OrganizationPeople/OrganizationPeople.test.tsx
- [ ] src/screens/OrgList/OrganizationModal.tsx
- [ ] src/screens/OrgList/OrgListMocks.ts
- [ ] src/screens/OrgList/OrgList.tsx
- [ ] src/screens/OrgSettings/OrgSettings.test.tsx
- [ ] src/screens/Requests/Requests.test.tsx
- [ ] src/screens/Requests/Requests.tsx
- [ ] src/screens/UserPortal/Chat/Chat.test.tsx
- [ ] src/screens/UserPortal/Events/Events.tsx
- [ ] src/screens/UserPortal/People/People.test.tsx
- [ ] src/screens/UserPortal/People/People.tsx
- [ ] src/screens/UserPortal/Settings/Settings.test.tsx
- [ ] src/screens/Users/Users.tsx
- [ ] src/utils/interfaces.ts
- [ ] src/utils/memberFields.ts

**Comment by palisadoes** [comment]
1. The Part 1 PR is complete.
2. Are these remaining files on your roadmap?

```
src/components/LeftDrawerEvent/LeftDrawerEvent.tsx
src/components/OrgAdminListCard/OrgAdminListCard.tsx
src/components/UserPortal/OrganizationSidebar/OrganizationSidebar.test.tsx
src/components/UserPortal/SecuredRouteForUser/SecuredRouteForUser.test.tsx
src/GraphQl/Mutations/mutations.ts
src/screens/OrganizationPeople/MockDataTypes.ts
src/screens/OrganizationPeople/OrganizationPeople.test.tsx
src/screens/Requests/Requests.tsx
src/screens/UserPortal/Chat/Chat.test.tsx
src/screens/UserPortal/People/People.test.tsx
src/screens/UserPortal/People/People.tsx
src/screens/Users/Users.tsx
```

**Comment by pranshugupta54** [comment]
@palisadoes,
**Will be fixed in their respective PRs:**
- src/components/LeftDrawerEvent/LeftDrawerEvent.tsx - to be fixed in 1853
- src/components/OrgAdminListCard/OrgAdminListCard.tsx - to be fixed in 1852
- src/GraphQl/Mutations/mutations.ts - to be fixed in api 2139

--
**Have an issue with Orgmember connection API, having conversation with others over this:**
- src/components/UserPortal/OrganizationSidebar/OrganizationSidebar.test.tsx - o
- src/screens/OrganizationPeople/OrganizationPeople.test.tsx - o
- src/screens/UserPortal/Chat/Chat.test.tsx - o
- src/screens/UserPortal/People/People.test.tsx - o
- src/screens/UserPortal/People/People.tsx - o

--
**Need to first fix eslint issue in functions:**
- src/screens/Users/Users.tsx - eslint 
- src/screens/Requests/Requests.tsx - eslint
- src/screens/OrganizationDashboard/OrganizationDashboard.test.tsx 
- src/screens/UserPortal/Events/Events.tsx - eslint

--
**To check:**
- src/screens/OrganizationPeople/MockDataTypes.ts
- src/components/UserPortal/SecuredRouteForUser/SecuredRouteForUser.test.tsx - code is commented

**Comment by pranshugupta54** [comment]
<img width="312" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/9ec65b47-cf7f-43fd-a7c6-b701ebb6877c">


To fix:
--

To be fixed in admin/1852:
- `schema.graphl`
- `src/components/OrgAdminListCard/OrgAdminListCard.tsx`
- `src/GraphQl/Mutations/mutations.ts`

Still API issue:
- `src/screens/UserPortal/People/People.tsx`
