### ISSUE TITLE
Bug Report: OrgID being passed in Wrong Format in UserPortal

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-admin#1829]
**Describe the bug**
The Organization ID being set in URL should be set as URL parameter instead of URL query vars. The following inproper format leads to events and rest of entities in UserPortal not being rendered.

**To Reproduce**

1. Login To User Portal
2. Select a Organization
3. Open Events/Donation Page 
4. Events/Donations wont render due to failing graphql queries

**Expected behavior**
OrgID should be passed as params without any 'id=' prefix so that proper orgId is passed to various graphQl queries

**Actual behavior**
OrgID is passed as params but with 'id=' prefix leading to failings graphQl queries

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/741688ed-003b-439b-947c-316962b49aaf)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by GlenDsza** [comment]
@palisadoes would like to work on this issue

**Comment by pranshugupta54** [comment]
Same for `people` screen
