### ISSUE TITLE
Unable to create a venue | Bad User Input

### ISSUE THREAD

**Issue by krishna619** [PalisadoesFoundation/talawa-admin#1840]
**Describe the bug**
As an admin of an organization, I am not able to create a venue.

PFA the error SS
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/52276473/7e7eea39-a062-4dbb-bd4e-c66abc7a1069)

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/52276473/47a0fdc9-7e42-4198-8c5a-04f16aa236e0)

A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
A recent PR was merged on this, did you take pull?
https://github.com/PalisadoesFoundation/talawa-admin/pull/1810

**Comment by krishna619** [comment]
Yes @pranshugupta54 
I am on the latest upstream

**Comment by GlenDsza** [comment]
@krishna619 Just checked, the Venue Creation is working Fine. The above error will probably arise if instead of integer value in Capacity you enter string. Maybe there should be issue regarding applying these checks on client itself before sending to server is required.

**Comment by krishna619** [comment]
@GlenDsza either it should validate `capacity` field client side or it should make it optional.

**Comment by GlenDsza** [comment]
> @GlenDsza either it should validate `capacity` field client side or it should make it optional.

Probably optional is not a good Idea, as Capacity would be used to check and warn user before inviting other users for event if capacity is reached.

**Comment by pranshugupta54** [comment]
@krishna619, it does have a warning on the client side which makes it required while making Venue on client.

The only improvement could be having a better warning message for this.

<img width="992" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/09aa8a83-f0ea-4c72-86f6-0615b9004944">

**Comment by GlenDsza** [comment]
@palisadoes Would like to work on this issue
