### ISSUE TITLE
 Complement GraphlQl Error Handling: Multiple Resolvers

### ISSUE THREAD

**Issue by NamitBhutani** [PalisadoesFoundation/talawa-admin#1841]
**Is your feature request related to a problem? Please describe.**
The error handling for certain resolvers namely: 
`createMember, createAdmin, createComment` . They now return a userErrors array based on the error that occurred.
example GraphQL definitions
```
 createAdmin(data: UserAndOrganizationInput!): CreateAdminPayload!
type CreateAdminPayload {
  user: AppUserProfile
  userErrors: [CreateAdminError!]!
}
union CreateAdminError = OrganizationMemberNotFoundError | OrganizationNotFoundError | UserNotAuthorizedError | UserNotFoundError
```
Below is an example of how errors are now returned from the resolvers - 
```
if (!organization) {
    return {
      user: new AppUserProfile(),
      userErrors: [
        {
          __typename: "OrganizationNotFoundError",
          message: requestContext.translate(
            ORGANIZATION_NOT_FOUND_ERROR.MESSAGE,
          ),
        },
      ],
    };
  }
```

**Describe the solution you'd like**
 We need to update the repository to handle the new errors methodology for the given resolvers.

**Additional context**

1. Refer the issue #1486 and the linked [Pull Request](https://github.com/PalisadoesFoundation/talawa-api/pull/1746) to the issue.
2. [https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/docs/developers/talawa-api/error-handling.md](https://github.com/PalisadoesFoundation/talawa-docs/blob/develop/docs/developers/talawa-api/error-handling.md)
3. [https://productionreadygraphql.com/2020-08-01-guide-to-graphql-errors/](https://productionreadygraphql.com/2020-08-01-guide-to-graphql-errors/)

**Comment by Cioppolo14** [comment]
@NamitBhutani Is this one you wanted to be assigned?
