### ISSUE TITLE
no-non-null-assertion causes difficulty in testing

### ISSUE THREAD

**Issue by aarishshahmohsin** [PalisadoesFoundation/talawa-admin#1843]
**Describe the bug**
The "no-non-null-assertion" configuration in ./.eslintrc.json results in difficulty making tests.
This is because any file containing any parameter of the type ```<type> | null``` has to use an if statement even if the parameter will never be null.
This causes branches that are impossible to cover while testing and hence forces the usage of ignore statements. These ignore statements can been seen throughout out the codebase

``` js
onChange={(date: Dayjs | null): void => {
	 /* istanbul ignore next */
	if (date) {
		setEndDate(date?.toDate());
	}
}
```
 
**To Reproduce**
1. Try to make unit tests for any file that has any parameter which is of the type ```<type> | null```

**Expected behavior**
Allow using non null assertions in the code or propose any other solution.

**Actual behavior**
Non null assertions are not allowed and hence the usage of such ignore statements is forced.

**Screenshots**
NA

**Additional details**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Olatade** [comment]
Do you want to work on this issue? If so you should do so immediately after creating it. That way we don’t have to visit the issue twice. Once to ask you and then again to assign you. We’ll update the ISSUE_GUIDELINES.md to state this.

**Comment by aarishshahmohsin** [comment]
> Do you want to work on this issue? If so you should do so immediately after creating it. That way we don’t have to visit the issue twice. Once to ask you and then again to assign you. We’ll update the ISSUE_GUIDELINES.md to state this.

I am already assigned 2 issues.

**Comment by pranshugupta54** [comment]
We shouldn't remove this, instead add two different tests 
1) Having the data with given `<type>`
2) Add data with null value

Like for the datepicker, by default the date selected is `null` so we have to accept `value` as null too. When it comes to `onChange`, we can probably remove the null part because that's something unexpected.

So, we need to remove `| null` for some parts.

**Comment by palisadoes** [comment]
Closing
