### ISSUE TITLE
Migrating from CRA to Vite

### ISSUE THREAD

**Issue by lakshz** [PalisadoesFoundation/talawa-admin#1848]
### Discussed in https://github.com/PalisadoesFoundation/talawa-admin/discussions/1838

<div type='discussions-op-text'>

<sup>Originally posted by **lakshz** March 28, 2024</sup>
We should consider migrating from CRA to Vite for the following reasons:
1. Faster build time. Hence, a better development experience
2. Optimized production builds
3. More compliant with modern/best practices

The only hurdle can be compatibility. We'll have to make sure all the existing dependencies work well with Vite. 

</div>

**Comment by lakshz** [comment]
I would like to work on it, if this sounds good.

**Comment by Cioppolo14** [comment]
@lakshz Please get more feedback in the slack discussion before opening an issue. We need a consensus.
