### ISSUE TITLE
Remove Linting Warnings 

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa-admin#185]
**Describe the bug**
We need to remove all the linting warnings that are coming

the thing to make is ```yarn lint``` will produce this and then we should fix this accordingly

**Comment by palisadoes** [comment]
@yasharth291 
- Please provide the commands that people can use to reproduce the issue you want to fix. 
- Please provide sample output of what needs to be fixed.

**Comment by yasharth291** [comment]
@palisadoes 
done sir

**Comment by veerreshr** [comment]
is someone working on this? if not could you please assign it to me
