### ISSUE TITLE
Calendar Month / Day View Switch Doesn't Work

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1850]
**Describe the bug**

Switching between the Calendar Month / Day View Switch Doesn't alter the calendar

**To Reproduce**

1. Log into admin or user portal
2. View the calendar
3. Try switching between views
4. Nothing changes

**Expected behavior**

1. The layout should switch between the monthly and daily views

**Actual behavior**

1. See above
2. See screenshot

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/6fa5e406-52f8-4d6f-b98f-dad98a0f1747)

**Additional details**

- N/A

**Potential internship candidates**

- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
Reference: https://github.com/PalisadoesFoundation/talawa-admin/issues/1611

**Comment by palisadoes** [comment]
@duplixx is this related to your most recent PR?

**Comment by duplixx** [comment]
yes @palisadoes , assign me this issue i'll work on it

**Comment by duplixx** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/7cba8734-f7da-44b6-bc61-705b287ce8d5

**Comment by meetulr** [comment]
@palisadoes I covered this in #1818. Should I close that one?
