### ISSUE TITLE
Calendar Month View: Next / Previous Arrows Don't Work

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1851]
**Describe the bug**

1. The calendar month view next / previous arrows increment one day at time instead of one month at a time.
2. The date shown is a specific date versus the month

**To Reproduce**

1. Log into admin or user portal
2. View the calendar
3. Try clicking the next or previous arrows

**Expected behavior**

1. The layout should switch between the monthly and daily views

**Actual behavior**

1. See above
2. See screenshot

**Screenshots**

1. Talawa
    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/556366da-2907-46cd-9eb9-889ff1ca276a)

1. Google Calendar
    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/f6a938b4-8ba7-42fc-88cd-c258f49cd11e)

**Additional details**

- N/A

**Potential internship candidates**

- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@duplixx is this related to your most recent PR?

**Comment by duplixx** [comment]
@palisadoes i wanna work on this

**Comment by meetulr** [comment]
@palisadoes It's a duplicate issue of #1818 😅. Should I close that one?

**Comment by palisadoes** [comment]
Yes. Thanks
