### ISSUE TITLE
Event Dashboard: Multiple Layout Issues (March 2024)

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1853]
**Describe the bug**

The event dashboard has multiple minor issues that need to be resolved

**To Reproduce**

1. The All Events card redirects to the organization dashboard and not to the organization's events
2. The Action Items card has incorrect text
3. The user role is Null
4. The width of the event card is too narrow. The dates are not formatted correctly if the event description is very short
5. The event box has a link that doesn't work. It should be removed.

**Expected behavior**

- See above

**Actual behavior**

- See above

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/4aa38082-d244-4bc0-b444-bfcb9bd6b757)

**Additional details**

- See above

**Potential internship candidates**

- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@GlenDsza

You should make sure these fixes are applied to your issue. Ask to be assigned to this one.
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1748

**Comment by GlenDsza** [comment]
@palisadoes please assign, would fix these issues as related to existing one

**Comment by pranshugupta54** [comment]
@GlenDsza, can you fix the user type null here? Or do I fix it in userType issue, to avoid any conflicts.

**Comment by GlenDsza** [comment]
@pranshugupta54 I would fix it
