### ISSUE TITLE
Login Page Images, Social Icons and URLs Missing When the Sample Database is Loaded

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1859]
**Describe the bug**

- Login Page Images, Social Icons and URLs Missing When the Sample Database is Loaded

**To Reproduce**

1. Load sample database in the API
2. Access the Talawa-Admin login page
3. Social media icons and images are missing
4. Login as a SuperAdmin
5. Reset the community settings
6. Logout
7. The correct login page images are shown

**Expected behavior**

1. Display the correct images, icons and URLs when the community collection values are blank
    1. The issues linked below indicate where you can look to research the fix.
    2. The default values should be located in the `src/constants.ts` file
3. This could be done in the default data load, but that would mean editing values in two repos. Doing it all here increases the chances of consistency.

**Actual behavior**

- See above

**Screenshots**

1. Login page showing the bug

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/cdd98746-69db-447a-b8ec-3cb3e32e2587)

1. Community Profile reset page

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/2c8697bd-fada-445a-9d84-ae541dee1ee4)

1. Login page after resetting

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/dc884855-9b84-4989-95ba-03981b8e990c)

**Additional details**

1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1334
1. https://github.com/PalisadoesFoundation/talawa-admin/pull/1649
1. https://github.com/PalisadoesFoundation/talawa-api/issues/1611
1. https://github.com/PalisadoesFoundation/talawa-api/pull/1935

**Potential internship candidates**

- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
I just went through this issue and realized that we are unnecessarily populating data for communities, as we already have supported code in our frontend to handle null data. The simple solution is to remove the default data population while importing sample data, and everything will work fine.

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/4588de66-21e7-40f0-b9fa-170d8618777d


@palisadoes sir, please check the video. If this is what we are expecting, then I would like to open an issue and work on it for the talawa-api.

**Comment by palisadoes** [comment]
Please prove that this works using the `setup.ts` script when the:

1. sample data is loaded
2. default organization data is loaded

**Comment by akhilender-bongirwar** [comment]
I used `npm run setup` command.

- When the sample data is loaded 

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/7918555d-c34e-4437-a9ff-77665074268d

- When the default organization data is loaded 

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/5ead8548-cccb-497a-9190-f93bbb43d8e0

**Comment by palisadoes** [comment]
Thanks. Please create a PR

**Comment by akhilender-bongirwar** [comment]
> Thanks. Please create a PR

Made an issue in the API. Will create a PR once assigned.

**Comment by akhilender-bongirwar** [comment]
@dhanagopu,  as per the [conversation](https://thepalisadoes-dyb6419.slack.com/archives/CSWGQ70UQ/p1712337289226219). This issue can be closed as completed.
