### ISSUE TITLE
About the recent Merge in the repo 

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa-admin#186]
**Describe the bug**
The recent merge will fail in linting errors and some of them should be removed as soon as possible. I would encourage @karan2704  to take up this bug as all the lining errors are related to the code he wrote in recent times.

**To Reproduce**

1. type ```yarn lint```

**Comment by palisadoes** [comment]
@yasharth291 
- Is this something we can add to the GitHub action so that the problem doesn't happen again? 
- If so, should we create a new issue for the GitHub action?

**Comment by karan2704** [comment]
Yes I'm looking into it. I faced similar linting issues when I ran the app on my system. At that time I fixed it using `yarn lint-fix` but the problem persisted after I changed some files and I had to run the same command and restart the app every time I made changes. Is it a problem on my end and if not then please guide me on how to go about it since I am not quite familiar why eslint error occurs.

**Comment by palisadoes** [comment]
@ karan2704 We are going to need this included in our GitHub actions. We don't want to have this repeat itself. Let me know if this is something you can do?

**Comment by karan2704** [comment]
Okay... I'll work on it

**Comment by Tejas-Ladhani** [comment]
Hey, is this fixed ?? am still getting the linting errors on the first run

**Comment by karan2704** [comment]
@Tejas-Ladhani  Try running `yarn lint-fix` then restart the app if you haven't done that already. I'll generate a PR for this by tomorrow.

**Comment by Tejas-Ladhani** [comment]
@karan2704, Yes I have , even after that, I am getting 10 errors (+72 warnings)

**Comment by karan2704** [comment]
Since the previous PR was reverted I'd like to go back in the commit history of my forked repository so that can be on the same page as the develop branch. How do I do that without losing the commit history?

**Comment by palisadoes** [comment]
Use the `git log` command to see a commit history. Each commit will have a hexadecimal reference number that can be used to revert your repo to a previous historical version.

**Comment by SiddheshKukade** [comment]
The linter works fine now
