### ISSUE TITLE
Bug: Date Input field styling in Event Creation Modal  

### ISSUE THREAD

**Issue by lakshz** [PalisadoesFoundation/talawa-admin#1862]
**Describe the bug**

**To Reproduce**

1. Login as an Admin
2. Go to Event page
3. Click "Create Event" button on top-right

**Expected behavior**
The border should not collide with label. The line should be removed where there is label. This can be done with CSS changes.

**Actual behavior**
In the date fields, the label is colliding with the border. 

**Screenshots**
This is zoomed in version of the Event Creation Modal
<img width="949" alt="Screenshot 2024-04-02 at 22 49 55" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/81241551/621f852d-5e7f-4740-affc-978b879db5dd">

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
Looks like some PR added this css to all input boxes everywhere

**Comment by Ratul-Saha-003** [comment]
Is this issue still open?
