### ISSUE TITLE
Bug: Action Items overflowing text on right navigation bar

### ISSUE THREAD

**Issue by lakshz** [PalisadoesFoundation/talawa-admin#1863]
**Describe the bug**

**To Reproduce**

1. Login as an Admin/Superadmin
2. Go to Event Page
3. Create an Event
4. Click on the newly Event created from the calendar
5. Click "Show Event Dashboard"
 

**Expected behavior**
The text should be changed to "Event Action Items" 

**Actual behavior**
The right navigation bar shows overflowed text, "organizationActionItems.eventActions"

**Screenshots**
<img width="1710" alt="Screenshot 2024-04-02 at 23 12 37" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/81241551/e9b00a2b-8252-4919-b822-4342e5b27e76">

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Closing: Duplicate

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1853
