### ISSUE TITLE
Bug Report: User is unable to register in the user portal.

### ISSUE THREAD

**Issue by gautam-divyanshu** [PalisadoesFoundation/talawa-admin#1869]
**Describe the bug**
User is unable to register.

**Expected behavior**
USER should be able to register.

**Actual behavior**

**Screenshots**

**Additional details**
I think issue is related to this PR https://github.com/PalisadoesFoundation/talawa-api/pull/2143

**Slack conversation related to this:-** https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1712220653046069

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by gautam-divyanshu** [comment]
[Screencast from 2024-04-04 14-18-48.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/0308430b-9a61-49aa-a649-537fc914f83b)

**Comment by pranshugupta54** [comment]
Should be covered in https://github.com/PalisadoesFoundation/talawa-admin/issues/1440

**Comment by akhilender-bongirwar** [comment]
@gautam-divyanshu you can close this issue.
