### ISSUE TITLE
[BUG] Unable to Join Org from user portal

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1872]
**Describe the bug**
There is no "Join" button for the listed orgs.

**To Reproduce**

1. Login via User
2. Check all Orgs
3. No option to join

**Expected behavior**
"Join" button to join the Organization

**Actual behavior**
No button

**Screenshots**
<img width="1440" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/b049c90a-b612-43cf-871b-9ef1cd2c9f04">

**Additional details**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
I can work on this.

**Comment by pranshugupta54** [comment]
duplicate: #1849

**Comment by gautam-divyanshu** [comment]
@pranshugupta54  just opened an pr
