### ISSUE TITLE
Feature: An option for users to leave the Organization

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1873]
**Is your feature request related to a problem? Please describe.**
There is no way for the user to exit/leave the Organization.

**Describe the solution you'd like**
An option on the left panel for users to leave the Organization.

**Describe alternatives you've considered**
Can discuss on design

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Will this require an corresponding issue in the API?

**Comment by varshith257** [comment]
@palisadoes There is no need for any API work for this. Already sufficient code is present in the API.

**Comment by duplixx** [comment]
do we have any existing UI for this @palisadoes

**Comment by pranshugupta54** [comment]
- This is Posts page under User Portal (Most probably the username and Sign Out button from left right will be shifted to top right like we changed in Admin panel to keep it similar)
- We can put "Leave Org" at the current place of "Sign Out"

_We first need to get this left side of users completed_ in https://github.com/PalisadoesFoundation/talawa-admin/issues/1510

<img width="551" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/ef549a18-9a6c-4fdd-99d5-3ec348b604d8">

**Comment by duplixx** [comment]
@pranshugupta54 that won't look good and it will be confusing for users 

> * This is Posts page under User Portal (Most probably the username and Sign Out button from left right will be shifted to top right like we changed in Admin panel to keep it similar)
> * We can put "Leave Org" at the current place of "Sign Out"
> 
> _We first need to get this left side of users completed_ in #1510
> 
> <img alt="image" width="551" src="https://private-user-images.githubusercontent.com/76090263/320081152-ef549a18-9a6c-4fdd-99d5-3ec348b604d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzc0OTUsIm5iZiI6MTcxMjMzNzE5NSwicGF0aCI6Ii83NjA5MDI2My8zMjAwODExNTItZWY1NDlhMTgtOWE2Yy00ZmRkLTk5ZDUtM2VjMzQ4YjYwNGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE3MTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMzdlNTZlY2E1MGFiMDg0ZjhlYzFhNWU3Y2ZiMjY1YTBkNjkzNDViMmIzYTBhNjhiYTYzY2M5ZmY1YTFlY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EL0iC-d4sBgZzORiiXIrmbO0xRJDI5sjjOeLbsNCUDk">

**Comment by pranshugupta54** [comment]
We should keep it easy to use, I know we want more user engagement but at the same time we want the platform to be easy to use. For accidentally leaving, we can implement two steps (using confirmation modal)

**Comment by duplixx** [comment]
Yeah, @pranshugupta54, if we're placing the 'leave organization' feature in the sidebar, a two-step process would definitely be more secure.

**Comment by chandel-aman** [comment]
I think keeping the "leave organization" feature in the sidebar won't be a good idea, as it may encourage users to leave the organization instead of increasing engagement. 

1. We could place it in the user's settings, or,
2. We could have a separate screen to manage organizations and related activities, as we will be adding notifications for users. There is a GSoC project for Chat and Notifications, as well as for event-related broadcasts for the user from the admin.

**Comment by chandel-aman** [comment]
As both @pranshugupta54 and @duplixx suggested we should keep it easily accessible with 2-step user flow.
We could take inspiration from Breezechms, where they have hidden the "Cancel Account" option but made it easily accessible.

[Screencast from 05-04-24 11:20:59 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/8c2b729c-88f9-4ff1-8b4a-1c291ebbe296)

**Comment by pranshugupta54** [comment]
We can use existing designs in Talawa, i think we have similar modal in Delete Org (For superAdmin). We can use that same design directly instead.

**Comment by chandel-aman** [comment]
@pranshugupta54 Yeah, we could surely do that to maintain design consistency throughout the project.

**Comment by duplixx** [comment]
@chandel-aman yup the conclusion is add 2-step modal for "leave organization" button

**Comment by pranshugupta54** [comment]
I can take this up, I only have one assigned which is waiting for other issues to be resolved first.

**Comment by palisadoes** [comment]
> So the final changes would be this?
> 
> > We can use existing designs in Talawa, i think we have similar modal in Delete Org (For superAdmin). We can use that same design directly instead.

1. There isn't an organization settings option to mimic the admin screen functionality.
2. You'll need to think of a different approach

**Comment by AnshulKahar2729** [comment]
@palisadoes 
![image](https://github.com/user-attachments/assets/d939b596-7a50-4860-afb3-ad2c2f5aeb4f)
What about having a dropdown menu when you click on the organization name present in the left sidebar, there will be two options in dropdown menu, one will be to leave the organization and the other will be to visit the corresponding page.

This will solve both of our problems, the inconsistency of the design and the less user engagement.

**Comment by AnshulKahar2729** [comment]
Any discussion on this issue, as this is still not implemented. I want to work on this once the design is decided.

**Comment by palisadoes** [comment]
There should be the option to deselect the organization on the home screen where users select their organization.

**Comment by AnshulKahar2729** [comment]
![image](https://github.com/user-attachments/assets/62887a93-810a-4e35-95fb-d04575e56a45)

Is this okay for ui perspective? I'm working on the functionality.

**Comment by AnshulKahar2729** [comment]
@palisadoes 

"Which UI should we choose?"
![Screenshot from 2024-09-02 15-54-30](https://github.com/user-attachments/assets/09e0ebc2-a889-469b-a63f-85f80f9e1f5c)
![image](https://github.com/user-attachments/assets/b1218e38-18a2-4a55-988e-4459f9d1eda6)

**Comment by gopalepic** [comment]
@palisadoes  first of all thankyou to you that this repo is highly active as compare to other orgs , I have gone through the whole issue and would like to work on it , I wanted to implement this Enhancement and merge it , can you assign it to me

**Comment by gopalepic** [comment]
@palisadoes as i see @AnshulKahar2729 is just at the verge to merge the PR ,  

I am good at writings apis , TS ,and making UI development , pls let me know is there any other issue that I should work on ?

**Comment by AnshulKahar2729** [comment]
working

**Comment by AnshulKahar2729** [comment]
@palisadoes , assign me this issue again. I will try to work again on this and if I find any problem, I will communicate that on slack with the team.

**Comment by Cioppolo14** [comment]
@AnshulKahar2729 Are you making progress on this?

**Comment by palisadoes** [comment]
Unassigning. Inactivity. No PR

**Comment by raggettii** [comment]
Can you please assign it to me

**Comment by raggettii** [comment]
i have solved the issue but confused how to create PR as i also have made some changes in the talawa-api repo

**Comment by palisadoes** [comment]
> i have solved the issue but confused how to create PR as i also have made some changes in the talawa-api repo

Please refer to this guide:
- https://developer.palisadoes.org/docs/git-guide/quickstart

Also:

1. Read the CONTRIBUTING.md file in this repo
2. The slack channels will help.
3. There are many tutorials on YouTube.

**Comment by raggettii** [comment]
![github_image](https://github.com/user-attachments/assets/fdebc94c-4879-4a58-a227-4184647aded4)
i am getting this error while trying to commit can you help me out as i also have asked for the same on slack but no luck @palisadoes
