### ISSUE TITLE
Minor Bug: Member and admin count for Joined Orgs

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1874]
**Describe the bug**
Member and Admin count not being displayed for Joined Orgs in User Portal

**To Reproduce**

1. Login as user
2. View all orgs
3. Select "Joined Orgs" from dropdown

**Expected behavior**
Should display value

**Actual behavior**
Empty value for both

**Screenshots**
<img width="1440" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/52c54d48-d8cd-4718-86fb-262e68e496c0">

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
I can work on this.

**Comment by pranshugupta54** [comment]
@gautam-divyanshu, you should take this up. It's part of your PR (#1875) with just minor few line changes.

**Comment by gautam-divyanshu** [comment]
@pranshugupta54  its showing in my pr
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/b99fb52f-e348-42fb-8ae1-fb1e6ccee41a)

**Comment by pranshugupta54** [comment]
Please re-read the issue and steps, "Joined Organisations"

**Comment by gautam-divyanshu** [comment]
Yaa , sorry for misreading, I will cover this issue

**Comment by dhanagopu** [comment]
@gautam-divyanshu Do you want to work on this issue?

**Comment by gautam-divyanshu** [comment]
@dhanagopu I will cover this issue in my PR. Just have to update some queries.
