### ISSUE TITLE
Bug report:  "Module '\"@testing-library/react\"' has no exported member 'screen'."

### ISSUE THREAD

**Issue by Tejas-Ladhani** [PalisadoesFoundation/talawa-admin#188]
**Describe the bug**
the "screen" which is being imported from "@testing-library/react" (@testing-library/react/types/index.d.tx) has no export member with the name "screen".

**To Reproduce**
1. running application on localhost via the stable version of yarn ( that is, running ```yarn serve```)

**Screenshots**
![image](https://user-images.githubusercontent.com/67834407/146575695-5dcc0d88-8425-47cd-9a7b-4eadb354012b.png)

**Comment by palisadoes** [comment]
@ Tejas-Ladhani Do you want to work on this?

**Comment by yasharth291** [comment]
@Tejas-Ladhani

**Comment by Tejas-Ladhani** [comment]
> @ Tejas-Ladhani Do you want to work on this?

@palisadoes, Yes, I'd like to do that once the linting errors are resolved.

**Comment by Tejas-Ladhani** [comment]
> @Tejas-Ladhani what is the progress

Hey 🙋‍♂️ @yasharth291, wasn't able to give it a priority because of some other work. Haven't done much for it.
(un-assigning it)

**Comment by floppey** [comment]
Adding this line of code fixed the issue for me:

`import '@testing-library/jest-dom';`

**Comment by palisadoes** [comment]
@floppey would you like to work on this?

**Comment by Maagztech** [comment]
I want to work on this can you assign me?
