### ISSUE TITLE
ADMIN REDESIGN: Add role change in People screen

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1880]
**Is your feature request related to a problem? Please describe.**
Currently user roles can only be changed from `/users` in Superadmin screen which lists all users of all orgs.

**Describe the solution you'd like**
We should add a user role dropdown in Org -> People screen too for making it easier for Superadmin

- We can add a dropdown for roles 
- This dropdown should be disabled for Admins (to only view role) and only allowed for SuperAdmins
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/8a286ea0-3cc1-4f70-9848-39f234afb335)

### Take example reference from /users screen of superadmin
<img width="1104" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/07d15f03-185f-4dfa-9f72-092f5c81b40c">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
@palisadoes, don't you think it's gonna be difficult for Superadmins?
Currently Superadmins have "Users" screen which has all users of all orgs. They have no option for particular organization individually.

**Comment by palisadoes** [comment]
The aim is to make these modifications on the Organizations tab on an updated User Details screen. This is incomplete in the design figma

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/025af13b-1f50-4846-9cbc-cfb02c36dd02)

**Comment by pranshugupta54** [comment]
Sounds perfect

**Comment by palisadoes** [comment]
This is what we want
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1885
