### ISSUE TITLE
ADMIN & USER REDESIGN - List of events and holidays in calender view of events.

### ISSUE THREAD

**Issue by chandel-aman** [PalisadoesFoundation/talawa-admin#1887]
**Is your feature request related to a problem? Please describe.**
Currently, the event calendar does not provides the list of events and holidays.

**Describe the solution you'd like**

1. Adding a list of holidays, and
2. adding list events below the event calendar.
3. Using color coding for events

**Describe alternatives you've considered**
NA

**Additional context**

**Current**
Talawa-User
![Screenshot from 2024-04-07 06-03-11](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/bdbc2e15-8898-4e03-ac3b-219c76abc0be)
Talawa-Admin
![Screenshot from 2024-04-07 05-45-06](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/1ee744e1-82c9-4e73-8bb8-5c34774c05e5)

We already figma design made for this.

![Screenshot from 2024-04-07 05-46-34](https://github.com/PalisadoesFoundation/talawa-admin/assets/97614113/452d7449-003a-4c39-a77c-a169facfb1b2)

Figma link: https://www.figma.com/file/dTGr5CnGHvkilU5nwnRXg2/Talawa-Admin-UI-Redesign?type=design&node-id=910-355&mode=design&t=EVDV5SZ2cKnOAc2R-0

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
@chandel-aman do we have a need for this, as we can already see holidays and events in the calendar itself
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/454db518-9f98-4a55-a6f3-e3bea49a7bd3)

**Comment by palisadoes** [comment]
@aashimawadhwa PTAL

**Comment by aashimawadhwa** [comment]
we require this as we have initiated a different color coding and this feature will improvise and complete the calendar. we can approve this issue.
@palisadoes

**Comment by palisadoes** [comment]
@chandel-aman did you want to work on this?

**Comment by AmitSharma512** [comment]
@palisadoes can i work on this ?

**Comment by palisadoes** [comment]
Unassigning. inactivity

**Comment by sethdivyansh** [comment]
@Cioppolo14  can i work on this issue?

**Comment by palisadoes** [comment]
@sethdivyansh 

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by DipanshuOjha** [comment]
Hey...
I would like to work on this

**Comment by palisadoes** [comment]
unassigning. Inactivity

**Comment by anshuman008** [comment]
i would like to work on this issue!

**Comment by Dhiren-Mhatre** [comment]
Hi @palisadoes , could you assign this issue to me?

Here's how I’d plan to approach it:

First, I'll start by reviewing the Figma designs to get a clear understanding of how the events and holidays should be displayed on the calendar. I’ll ensure that the layout aligns with the current app design, keeping it user-friendly and visually cohesive.

For implementation, I’ll add a section below the event calendar to display the list of events and holidays. I’ll also use color coding to differentiate between events and holidays to make it easier for users to identify them at a glance.

Once the functionality is added, I’ll test the calendar thoroughly, checking how it displays on both Talawa-User and Talawa-Admin interfaces to ensure consistency. If any adjustments are needed, I’ll refine the design accordingly.

**Comment by palisadoes** [comment]
> Hi @palisadoes , could you assign this issue to me?
> 
> Here's how I’d plan to approach it:
> 
> First, I'll start by reviewing the Figma designs to get a clear understanding of how the events and holidays should be displayed on the calendar. I’ll ensure that the layout aligns with the current app design, keeping it user-friendly and visually cohesive.
> 
> For implementation, I’ll add a section below the event calendar to display the list of events and holidays. I’ll also use color coding to differentiate between events and holidays to make it easier for users to identify them at a glance.
> 
> Once the functionality is added, I’ll test the calendar thoroughly, checking how it displays on both Talawa-User and Talawa-Admin interfaces to ensure consistency. If any adjustments are needed, I’ll refine the design accordingly.

Please work with @aashimawadhwa and @duplixx on this. Also try the #talawa-admin slack channel

**Comment by VanshikaSabharwal** [comment]
@aashimawadhwa @duplixx are you still working on this issue? And if yes then can i help you out as well?

**Comment by gurramkarthiknetha** [comment]
hey i would like to work on this issue . @palisadoes could you assign this issue to me

**Comment by palisadoes** [comment]
Do you need assistance with your PR? Please ask the #talawa-admin slack channel if you do.

**Comment by gurramkarthiknetha** [comment]
> Do you need assistance with your PR? Please ask the #talawa-admin slack channel if you do.

sure
