### ISSUE TITLE
Issue Report Guidelines : no  #gsoc-newissues channel exists

### ISSUE THREAD

**Issue by Tejas-Ladhani** [PalisadoesFoundation/talawa-admin#189]
**Describe the bug**
It seems like the "Issue Report Guidelines" are not updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/67834407/146577406-b2730a92-d663-4bdd-8849-b8863417aece.png)

I would like to make the possible changes.

**Comment by palisadoes** [comment]
@Tejas-Ladhani the slack channel exists, it doesn't currently have any historical activity, but it exists. [Please join our slack channel to verify.](http://slack.palisadoes.org)

**Comment by Tejas-Ladhani** [comment]
@palisadoes The fourth point, however, confuses the aspiring contributor because the named channel is not directly visible from our (non-admin members) side.

**Comment by palisadoes** [comment]
@Tejas-Ladhani It's a public channel and should be visible.

Use the channel browser. Click on the three dots beside the word `channel` and you should see this menu.

![image](https://user-images.githubusercontent.com/16875803/146648016-dfede448-37c0-40fe-bd53-03fd4f36bcf5.png)
