### ISSUE TITLE
Figma Designs for advertisement and plugin section

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#1892]
**Is your feature request related to a problem? Please describe.**
this issue is about creating new design in figma for advertisement and plugin section 

**Describe the solution you'd like**
we require a contributor to replicate something consistent yet the same with the existing features.

**Approach to be followed (optional)**
- once assigned we can provide you access to the files requires, from where you can start you work.

**current situation**

<img width="1439" alt="Screenshot 2024-04-07 at 7 29 03 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/8aa2daee-213d-41b1-93cf-465f11055c50">

<img width="1439" alt="Screenshot 2024-04-07 at 7 28 45 PM" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/73706697/33d54a91-035e-496e-82df-04b04fa98730">

**Additional Context**
This is a no code, only design issue.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
@aashimawadhwa I can work in this can you assign me the issue

**Comment by duplixx** [comment]
@aashimawadhwa, do we have any existing designs available, or should I propose one myself?

**Comment by duplixx** [comment]
sounds good @palisadoes !!

**Comment by AmitSharma512** [comment]
@duplixx are you still working on this issue?

**Comment by duplixx** [comment]
yes @AmitSharma512

**Comment by AmitSharma512** [comment]
@duplixx if you need some help for designing I can help with figma :))

**Comment by AmitSharma512** [comment]
> yes @AmitSharma512 

@duplixx ok,  if you need some help for designing I can help with figma :))

**Comment by duplixx** [comment]
@aashimawadhwa https://www.figma.com/file/4baYvJdNqJXEZg0ajxngNo/Talawa-Design-System-(Official)-(Copy)?type=design&node-id=7398-449&mode=design
I have added advertisement design can you review it once

**Comment by palisadoes** [comment]
We are already in the Advertisement screen, and there is the title. There isn't a need to have the word Advertisement repeated. Please update

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/20132eae-22fb-4a8a-87f2-967027101f0f)

**Comment by palisadoes** [comment]
1. OK. Let's go with this.
2. @rishav-jha-mech and @aashimawadhwa may have comments later, but I expect them to be relatively minor

**Comment by duplixx** [comment]
sure @palisadoes

**Comment by duplixx** [comment]
https://www.figma.com/file/4baYvJdNqJXEZg0ajxngNo/Talawa-Design-System-(Official)-(Copy)?type=design&node-id=7412-436&mode=design
@palisadoes I have made a screen for plugins, can you review it once

**Comment by palisadoes** [comment]
OK. Please proceed.

**Comment by palisadoes** [comment]
This is much better than the previous design. Thanks

**Comment by duplixx** [comment]
Thanks, @palisadoes! I have a doubt here. This issue was addressed to create Figma designs only, 'no code required.' So, how should I raise a PR for the Figma changes?

**Comment by palisadoes** [comment]
Create one if you think you have the time and capacity. If not, we'll create another issue specifically for that.

**Comment by duplixx** [comment]
Okay got it I'll create issue for redesign implementation in admin panel

**Comment by palisadoes** [comment]
Did you create the issue?
