### ISSUE TITLE
USER REDESIGN: Make Calendar Views Match Admin

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1893]
**Is your feature request related to a problem? Please describe.**

The Events view in the Admin portal is very different from that in the User portal. 

1. Admin Portal

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/e76ab8e8-ffce-4f92-92a9-495b6e655b75)

1. User Portal

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/db9f3a89-51be-483d-b8e5-90f279aed8f0)

**Describe the solution you'd like**

1. Convert the User Portal event calendar views match that of Admin
3. There should be the same default behaviors and screen elements

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

- N/A

**Potential internship candidates**

- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@duplixx You may be interested in this. You worked on the code recently

**Comment by duplixx** [comment]
@palisadoes yeah sure I would love to work on it

**Comment by duplixx** [comment]
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/9460810b-1b4b-40b5-865f-d0645d5aeb98)
Hi @palisadoes, I've shared the new user portal design. I'm wondering about the 'create Event' feature. Can regular users make events too?

**Comment by palisadoes** [comment]
1. Yes, regular users can create events. They have always been able to in the mobile app. 
1. We will need to create issues to figure out how to limit what events users can see. For example, public events and ones they are invited to. We can do that after the PR for this is merged
1. Please proceed. The design looks good.

**Comment by duplixx** [comment]
@palisadoes, now that we've matched the UI #1908, we also need to provide registration functionality. Should I propose a design for registering events through the event calendar?

**Comment by palisadoes** [comment]
OK, but please take a look at this PR to see whether coordination is required.  
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1861
