### ISSUE TITLE
Inconsistent Left Drawer Expansion/Collapse Behavior

### ISSUE THREAD

**Issue by akhilender-bongirwar** [PalisadoesFoundation/talawa-admin#1897]
**Describe the bug**
The left drawer expansion/collapse functionality for screens smaller than `820px` is inconsistent. When the screen width is less than or equal to `820px`, the left drawer fails to function properly, both in the SuperAdmin screen and the Organization Dashboard screen.

**To Reproduce**

1. Login as SuperAdmin.
2. Adjust the screen width to tablet size or anything less than or equal to `820px`.
3. Attempt to interact with the left sidebar by clicking on it.
4. Navigate to any organization Dashboard.
5. Adjust the screen width to tablet size or anything less than or equal to `820px`.
6. Try clicking on the left sidebar.

**Expected behavior**
The left drawer should expand and collapse smoothly when clicked, mirroring its functionality on screens wider than `820px`.

**Actual behavior**
Expansion and collapse of the left drawer for both the SuperAdmin screen and Organization Dashboard screen are malfunctioning on screens with a width of `820px` or less.

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/fdb4cbee-40ea-487b-a0db-2baf00bb079a

**Additional details**
Same as above.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
Please assign this issue to me.

**Comment by dhruvgupta0503** [comment]
Hi, Is this issue still open. I would like to work on this issue.
