### ISSUE TITLE
Bug: Blocked users not displayed in list

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1898]
**Describe the bug**
Blocked users not displayed in list

**To Reproduce**

1. Login via superadmin
2. Select org
3. Block users
4. List is still empty

**Expected behavior**
Should show list of blocked users

**Actual behavior**
Blocked users not displayed in list

**Screenshots**
NA

**Additional details**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
I can work on this

**Comment by palisadoes** [comment]
Wouldn't this be fixed by this issue?

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1885

**Comment by pranshugupta54** [comment]
Oh yes, so we will remove the block/unblock screen. 
<img width="1000" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/70386316-c1f3-4050-b5f6-f6a486d512f9">


--

We can add an option for "Blocked Users" on People page itself
<img width="1118" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/ab535b91-779d-454e-ba93-9d46657b7ff8">
