### ISSUE TITLE
Feature: Add Audit logs for Administrators of the Organizations

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#1899]
**Is your feature request related to a problem? Please describe.**
Currently, there are no audit logs capturing every activity within a particular organization. This lack of comprehensive auditing makes it challenging for administrators to track and monitor actions within their organization effectively.

**Describe the solution you'd like**
We propose implementing audit logs with filter features. Organization administrators should have access to audit logs specific to their organization, enabling them to monitor and review activities relevant to their operations. Additionally, a community superadmin should have access to logs spanning across all organizations within the community, providing a broader oversight capability.

**Describe alternatives you've considered**
One alternative solution could be manually tracking activities through ad-hoc methods, such as spreadsheets or notes. However, this approach is prone to errors, lacks automation, and can be time-consuming. Another alternative could be implementing third-party audit log solutions, but this may incur additional costs and integration complexities.

**Approach to be followed (optional)**
1. **Define Audit Log Schema**: Establish a clear schema outlining the types of activities to be logged, including user actions, timestamps, and relevant metadata.
2. **Implement Access Control**: Define access levels for organization administrators and community superadmins to ensure appropriate access to audit logs.
3. **Develop Filter Features**: Create filters within the audit log interface to enable users to search and filter logs based on various criteria such as user, action type, and time frame.
4. **Integrate with Existing Infrastructure**: Ensure seamless integration with the existing organizational and community management systems to provide a unified experience.
5. **Test and Iterate**: Conduct thorough testing to validate the functionality and usability of the audit log feature, gathering feedback from stakeholders to iterate and improve as necessary.

**Additional context**
The implementation of comprehensive audit logs with filter features will significantly enhance transparency, accountability, and security within organizations and communities. This feature will empower administrators to efficiently monitor activities, detect anomalies, and mitigate risks effectively.

**Design:**
<img width="818" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/2d0288cc-e3ef-4cf5-a119-d62939086209">

**Reference:** https://github.com/PalisadoesFoundation/talawa-api/issues/2195

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship [here](https://github.com/PalisadoesFoundation/talawa/issues/359).

**Comment by pranshugupta54** [comment]
I'll work on this

**Comment by Cioppolo14** [comment]
Closing this as not planned for now.  We need to focus on other issues currently.
