### ISSUE TITLE
Add the ability to create new organizations

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#19]
Talawa Admin installation (Issue #18) prompts to create a Organizational Creator Admin (OCA). There needs to be a way where this user can create additional organizations suitable for creating a cloud service.

The creation of the organization will need to:

1. Create a different organization URI for `Talawa` users to select in their mobile app
2. Allow the OCA to access the administration panel of any regular Administrator who only have access to their own panel.

We need to also remove the ability to create new organizations in the mobile app as a part of this 

Parent issue:
#48

Related Issues:

1. [Issue 236 - Talawa API](https://github.com/PalisadoesFoundation/talawa-api/issues/236)
2. [Issue 19 - Talawa Admin](https://github.com/PalisadoesFoundation/talawa-admin/issues/19)
3. [Issue 710 - Talawa](https://github.com/PalisadoesFoundation/talawa/issues/710)

**Comment by yasharth291** [comment]
hello @palisadoes sir

**Comment by utkarshshendge** [comment]
@yasharth291 @DangaRanga I'd like to know if the organization's photo will also be added when the admin creates an organization.
Also, could you please specify what details of the organizations will be visible to users of the Talawa App?

**Comment by yasharth291** [comment]
please @utkarshshendge  ask peter sir and jason sir to what information will be taken

**Comment by utkarshshendge** [comment]
@palisadoes could you please specify what details of the organizations will be visible to users of the Talawa App? I will create few child issues based on that.

**Comment by palisadoes** [comment]
These would be the most useful. Let me know if you can think of others.

1. Organization Name
2. Physical Address
3. Phone number 
4. Contact Email address
5. Administrator name and link to be able to chat to them
