### ISSUE TITLE
Bug Report: Add new member mutation is not working

### ISSUE THREAD

**Issue by kanhaiya04** [PalisadoesFoundation/talawa-admin#1905]
**Describe the bug**
In the people screen the `ADD MEMBER` option is not working. Both the ways are not working `Existing User` and `New User`.

**To Reproduce**

1. Open the people screen of any org
2. Try to add a new member
3. You will both options are not working as expected.

**Expected behavior**
A new member should be added from the existing user or by creating a new one depending upon the option selected.

**Actual behavior**
The new member is not added because of some error in the mutation.

**Screenshots**
![Screenshot from 2024-04-16 21-44-55](https://github.com/PalisadoesFoundation/talawa-admin/assets/93936630/1aac4740-7d04-4cc4-8f43-5303e8a108ea)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
I would like to work on this.

**Comment by palisadoes** [comment]
Should this be closed and reopened in the API?

**Comment by kanhaiya04** [comment]
No, I got the reason behind this issue which is mainly due to the incorrect implementation of the mutation in the admin.
So just need to change few mutation in the admin and I will create the PR.
