### ISSUE TITLE
Bug: Incorrect Usage of Removed Mutation `updateUserType` in Organization People Screen

### ISSUE THREAD

**Issue by akhilender-bongirwar** [PalisadoesFoundation/talawa-admin#1907]
**Describe the bug**

Despite the recent update in the userType feature, where the `updateUserType` mutation was removed, it is still being used in the Organization People screen within the `orgAdminListCard.tsx` file for removing admins.

**To Reproduce**

1. Navigate to `Organization People` screen
2. Attempt to remove any admin present in the organization.
3. You will be encountering an error message with status 400.

**Expected behavior**
The `updateUserType` mutation should be modified according to the new userType fix. 

**Actual behavior**
The `updateUserType` mutation persists in the codebase and is being utilized in the Organization People screen, despite its removal from the API.

**Screenshots**
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/956d842a-a02d-4a1e-a108-d74d88ff4fba)
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/112749383/b38f07b6-42f1-4c11-bcdb-5c87530aa1e8)

**Additional details**
The API PR - [Link](https://github.com/PalisadoesFoundation/talawa-api/pull/2179) which removed the mutation.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
@kanhaiya04, this issue is also related to the `Organization People` screen. Can you work on this as it is an extension for issue #1905

**Comment by kanhaiya04** [comment]
@akhilender-bongirwar, I have already considered and fixed this issue in PR #1902.

**Comment by kanhaiya04** [comment]
@palisadoes, You can close this issue.

**Comment by akhilender-bongirwar** [comment]
Thanks for informing @kanhaiya04 👍

**Comment by akhilender-bongirwar** [comment]
@kanhaiya04, I guess you can fix the issue #1905 in the same PR #1902 since it is related to Organization People screen itself.
