### ISSUE TITLE
Regular Users cannot access the event dashboard for events they create 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1912]
**Describe the bug**

Regular Users cannot access the event dashboard for events they create 

**To Reproduce**

1. Login as a regular user
2. Create an event entry
3. Access the event dashboard
4. You get a 404 error

**Expected behavior**

1.  There should not be a 404 error. The correct screen must be displayed
2. All tests for the fix must be valid and comprehensive

**Actual behavior**

- See above

**Screenshots**

- N/A

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
I can work on this

**Comment by Cioppolo14** [comment]
@pranshugupta54 I just assigned you an issue so now you have 2. If this is still open when one of those is closed, let me know and I'll assign you.

**Comment by kanhaiya04** [comment]
@Cioppolo14, I want to work on this.

**Comment by kanhaiya04** [comment]
@palisadoes Just need one clarification.
Users should have the access to the dashboard of any event or only the event created by them.

**Comment by pranshugupta54** [comment]
@kanhaiya04, title clearly says "event dashboard for events they create". So basically if a user created some event then they should be able to access dashboard for their events. Not all events
