### ISSUE TITLE
Newly created events not visible in the Day view 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1913]
**Describe the bug**

Newly created events not visible in the Day view 

**To Reproduce**

1. Log in as a regular, admin or super admin user
2. Create an event
3. The event is visible in the monthly view
4. The event is not visible in the day view

**Expected behavior**

1. The event must be visible in the day view
2. All tests for the fix must be valid and comprehensive
3. Ensure that the fix is applied to events created by all user types

**Actual behavior**

- See above

**Screenshots**

- N/A

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
I can work on this 
@palisadoes

**Comment by palisadoes** [comment]
Please also remove the filter by type dropdown. It's not used.

**Comment by duplixx** [comment]
@palisadoes yeah sure

**Comment by dhanagopu** [comment]
@duplixx Are you still working on this?

**Comment by duplixx** [comment]
yes i'll be working on it and finish in couple days

**Comment by Cioppolo14** [comment]
@duplixx is there progress on this?

**Comment by duplixx** [comment]
@Cioppolo14 i would like to unassign myself from this issue, cuz I am not getting enough time to go through this.

**Comment by Cioppolo14** [comment]
Okay, thank you!

**Comment by Ratul-Saha-003** [comment]
Can I work on this?

**Comment by Ratul-Saha-003** [comment]
I don't think either the days view or month view are showing the recently added events. We need to refresh the event page to see the recently added event.
