### ISSUE TITLE
Bug in Recurring Daily Event Creation

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-admin#1916]
**Describe the bug**
When creating recurring event with recurrence daily the events should be created only from start date to end date. Rather it creates almost 365 events  per request not following date range.

**To Reproduce**

1. Login as admin
2. Set Date range
3. Create Event with Recurring on and frequency set as Daily

**Expected behavior**
Events should be created within given range

**Actual behavior**
Event creation don't follow date range if recurrence frequency is set to daily 

**Screenshots**

https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/2d0e03e2-f68a-4cbf-9a74-cbbd6256b680

**Comment by meetulr** [comment]
@GlenDsza This is how it should be😅. You're selecting the start and end dates for the recurring event instances, the recurrence end date (by default null, i.e. infinitely recurring) would be selected from the custom recurrence modal.

I'll update the doc soon explaining the approach in detail. Please confirm the functionalities with me until then. There have been changes in implementation recently as I've mentioned.
