### ISSUE TITLE
ADMIN REDESIGN: redesign the advertisement and plugin screen in talawa-Admin portal

### ISSUE THREAD

**Issue by duplixx** [PalisadoesFoundation/talawa-admin#1918]
**Is your feature request related to a problem? Please describe.**
Redesigning the Advertisement and Plugin Screen from existing design
we are planning redesigning the admin portal, this issue is a part of that redesigning flow.

**Describe the solution you'd like**
Attaching the screenshots for reference

**Current Situation**
Advertisement:
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/fe6f4de8-2ad7-4854-be7d-f125f94cfe98)
Plugin:
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/3d5c4ee9-0f2a-493c-81bc-3934557ec987)

Redesign:
<img width="1440" alt="Organization_ Advertisement (1)" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/dcbe64b4-94fe-41a6-8a96-3b4ab0d11f7a">

<img width="1440" alt="Organization_ Advertisement" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/644317f5-2b58-4ec4-9c3e-bfbd088abcd1">

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by duplixx** [comment]
@palisadoes can you assign me this issue

**Comment by dhanagopu** [comment]
@duplixx Are you working on this?

**Comment by duplixx** [comment]
yes will be finishing this up

**Comment by duplixx** [comment]
update so far
will be finishing up advertisement screen as well
https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/1b8b47da-f0f1-4ffb-a25c-5482cd6f4f04

**Comment by duplixx** [comment]
will finish the advertisement screen by this weeknd

**Comment by duplixx** [comment]
Updated Advertisement screen as well, will make final tweaks and raise PR soon

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/92a5e429-ac31-4d37-839e-059c560d2f51)

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/90516956/d8eaf301-51a6-49e0-a9b9-a4ad45b08756)

**Comment by VanshikaSabharwal** [comment]
@palisadoes Can i work on this issue

**Comment by palisadoes** [comment]
This is a GSoC issue
