### ISSUE TITLE
TS error on ApolloLink instance while running locally

### ISSUE THREAD

**Issue by Devesh21700Kumar** [PalisadoesFoundation/talawa-admin#192]
This error did not pop up before. Now it shows this on running yarn serve:-

`Type 'ApolloLink' is not assignable to type 'ApolloLink | RequestHandler'.`

![image](https://user-images.githubusercontent.com/59202075/146657363-012a1ca3-3ff1-45b0-b1e1-334e587dec95.png)
Line 31 of src/index.ts

**Comment by yasharth291** [comment]
just remove the errorlink
