### ISSUE TITLE
Web browser doesn't automatically launch when starting the application

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1922]
**Describe the bug**

Web browser doesn't automatically launch when starting the application

**To Reproduce**

1. Start the latest version of the app
2. The browser doesn't launch

**Expected behavior**

1. Start the latest version of the app
2. The browser launches
3. Create appropriate tests to prevent this happening again. All tests must be valid and pass.

**Actual behavior**

- See above

**Screenshots**

Nothing is visible after the web pack complies.

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/4b24ef44-988d-48d1-82b8-ab88da3c2dd3)

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by lokeshsingh3721** [comment]
but in my desktop its automatically opening .  I have mac and default browser is set to firefox .

**Comment by gautam-divyanshu** [comment]
@palisadoes It's working fine on my system also. 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/137816099/fa9d7170-fc4f-4f6e-ae39-f3d2a81b6b9b)

**Comment by Cioppolo14** [comment]
@pranshugupta54 Can this be closed?

**Comment by pranshugupta54** [comment]
Can not reproduce, it's automatically launching. Maybe some issue with Peter's default settings for code editor.

Can close 👍
