### ISSUE TITLE
Error when editing Super Admin profile

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1924]
**Describe the bug**
Error when editing Super Admin profile

**To Reproduce**

1. Start at the Super Admin organization screen:
1. Navigate to the view profile screen
1. Error is visible:

**Expected behavior**

1. No visible error
2. Tests must be created for this fix. All tests must be valid and pass

**Actual behavior**

- See above

**Screenshots**

1. Start at the Super Admin organization screen:

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/757ce29a-a8f8-442f-90ab-62f530d18adf)

1. Navigate to the view profile screen

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/31edf4ad-137f-4d2f-853a-63a504fa8bec)

1. Error is visible:

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/9cb4b515-b744-491e-8921-d5ebbebed582)

**Additional details**

- See above

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
@palisadoes, do you mean the error on the left side for Org not found? or email address coming out on the right side?

We have designed this page to be Organization specific, where the user profile will have options related to Org.

**Comment by palisadoes** [comment]
The loading organization error in the top left hand corner

**Comment by pranshugupta54** [comment]
It's going to be same for Admin profile bcuz the side left panel is same for Organization options hence causing error when directly going to Member screen without selecting Org first.

**Comment by coderpawan** [comment]
Ohhh I also faced the same error when i tried to logout but that time i didnot notice this raised issue in the repo. I have solved the issue by putting conditional statement . Actually the error was in the LoginPage.tsx file where org.address was used to access the city but there was nothing to handle if org.address would get null which was the root of the error. So After adding the conditional statement I have solved it. Now tell me what to do next?

**Comment by palisadoes** [comment]
Our playlists explain your next steps

1. https://www.youtube.com/watch?v=iYdyBfXdV2w&list=PLv50qHwThlJUIzscg9a80a9-HmAlmUdCF&index=7&pp=gAQBiAQB
2. https://www.youtube.com/watch?v=lmNeydX_0sQ&list=PLv50qHwThlJUIzscg9a80a9-HmAlmUdCF&index=9&pp=gAQBiAQB
3. https://www.youtube.com/watch?v=dQuEKpsy1vM&list=PLv50qHwThlJUIzscg9a80a9-HmAlmUdCF&index=10&pp=gAQBiAQB

**Comment by AnshulKahar2729** [comment]
@palisadoes please assign me the issue, I would like to work on this.

**Comment by AnshulKahar2729** [comment]
I would like to work on this issue, is this issue still a priority?

**Comment by palisadoes** [comment]
@AnshulKahar2729 

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by AnshulKahar2729** [comment]
now you can assign me, previous issue assigned to me is now resolved.

**Comment by palisadoes** [comment]
@AnshulKahar2729

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by AnshulKahar2729** [comment]
> @AnshulKahar2729
> 
> Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

Yeah but I have only one issue assign.

**Comment by Cioppolo14** [comment]
@AnshulKahar2729 It looks like you have 2 issues assigned.  The total is counted across all 3 repositories.

**Comment by ARYANSHAH1567** [comment]
Can you please assign it to me?

**Comment by ARYANSHAH1567** [comment]
I have solved the issue, Can anyone please assign it to me so that i can create a pr

**Comment by ARYANSHAH1567** [comment]
The error was that for the organizations creator id was being passed to the api and it was treating it to be as orgId so i have to also change a file in the talawa-api so will i have to create a issue in api and link it here to fix it?

**Comment by ARYANSHAH1567** [comment]
I tried Solving the issue, identified the thing that was causing the issue but there were some tests that were still failing that i couldnt fix so i am unassigning myself this issue

**Comment by sethdivyansh** [comment]
Please assign me

**Comment by sethdivyansh** [comment]
@palisadoes @pranshugupta54 do we need orgSidebar in admin profile? What will it show in people, events, venue etc?

**Comment by palisadoes** [comment]
Modifying the orgSidebar is out of scope of this issue. We need the error fixed as described.

**Comment by sethdivyansh** [comment]
@palisadoes  The issue has now been resolved through pull request #2386.
