### ISSUE TITLE
ADMIN REDESIGN: More intuitive fundraising screens

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1927]
**Is your feature request related to a problem? Please describe.**

We need more intuitive fundraising screens with updated functionality.

**Describe the solution you'd like**

1. When a fund is created:
    1. The `Manage` button updates the base fund parameters. `Edit` would be more appropriate.
    2. Clicking the fund's name, gets you to the fund's Campaigns screen. It's not clear that this is what the link does. We need a button or some other device to do this. `View Campaigns` or something similar would be better
    3. The `Non Archived` status is technically correct, but not intuitive. It should be `Active`
    4. The tab text needs to be updated
1. When clicking through on a Fund to view the campaigns:
    1. The left drawer doesn't indicate that you got to this screen via Funds. We normally use green for selected items, but this is one screen in, so possibly another color or shade would be appropriate. Suggestions welcome, I'm not familiar with the best practices on this.
    1. Creating a campaign gives an `input validation` error
        1. The newly created campaign must be visible in the list for the fund.
        2. There must be a way to edit the campaign 
1. Tests must be created for these updates. The must be valid and pass. We especially don't want this campaign failure bug occurring again.

**Describe alternatives you've considered**

- See above

**Approach to be followed (optional)**

- See above
**Additional context**

1. Funds screen:

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/634190c1-0336-464a-8a29-f0585a5cc2bc)

1. The tab text that needs updating:

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/d6371530-cd2e-4847-ac96-5a4ffe4cfb56)

1. Campaigns screen:

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/accbc8f5-f4e3-4255-bb3c-9f986dce4b4c)

1. The create campaign modal:

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/621ed40f-9bd8-4d08-807b-9585f4edf984)

1. Create campaign `input validation` error:

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/d92af2c8-5978-42bb-99ae-88db0344917f)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by pranshugupta54** [comment]
> 2.i. The left drawer doesn't indicate that you got to this screen via Funds. We normally use green for selected items, but this is one screen in, so possibly another color or shade would be appropriate. Suggestions welcome, I'm not familiar with the best practices on this.

Can have nested like:
<img width="291" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/825e3c4c-24ff-4536-bd3c-cbf99b1d0d4a">

_The nested can NOT be directly accessed without selecting Fund_

**Comment by pranshugupta54** [comment]
5. Not able to reproduce this:
<img width="300" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/1cc6cf95-49c3-4894-9d10-3bb94e8f3511">

<img width="1103" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/76090263/9c02c8e0-e654-4674-b169-ab69b9395d4a">

**Comment by palisadoes** [comment]
I'm using the latest sample DB data and API / Admin code

**Comment by GlenDsza** [comment]
@palisadoes Pls assign

**Comment by GlenDsza** [comment]
@palisadoes This can be closed now
