### ISSUE TITLE
Fix Organization Action Items Modal Text

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1929]
**Describe the bug**

Fix Organization Action Items Modal Text

**To Reproduce**

1. Create an organization action item
2. Click on the completion checkbox
3. The modal text is incorrect

**Expected behavior**

1. Correct translated modal text
2. All tests must be valid and pass. We don't want this error repeating

**Actual behavior**

- See above

**Screenshots**

1. Completed check box

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/f1cf2cac-ad20-4f3e-b005-730d2b6e1518)

1. Completion modal:

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/84f6ea80-8dff-4766-ad66-f072994691d0)

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by NamitBhutani** [comment]
i'd like to work on this issue!
