### ISSUE TITLE
Event and Organization Action item layouts need to be the same

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1930]
**Describe the bug**

Event and Organization Action item layouts need to be the same

**To Reproduce**

1. Create action items for an event. Observe the screens
2. Create action items for an organization Observe the screens
3. The screens and modals are different

**Design**

1. Before starting the work, create a figma design that can be reviewed.
2. The styling must be in keeping with our existing esthetic

**Expected behavior**

1. The layouts and modals must match
1. We must have valid tests to ensure that we don't have this future divergence. All tests must pass.

**Actual behavior**

- See above

**Screenshots**

1. Organization Action Items Screen

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/be2f18db-7a56-40bb-ad2a-c349d06eba45)

1. Event Action Items Screen

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/c88afa68-51f1-48c5-966f-31a99c862e80)

1. Event action item manage modal doesn't show the assignee

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/11ccabd1-79dc-49a8-8416-28dccb910566)

1. Action item headings should be "Notes" and "Completion Notes"

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/65bc4bf1-b8d4-45b3-ac80-12934485d8e2)

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 

- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kanhaiya04** [comment]
@palisadoes I want to work on this.

**Comment by Cioppolo14** [comment]
@kanhaiya04 Are you working on this still? We know it is exam time.

**Comment by kanhaiya04** [comment]
Currently, I am in the midst of my final term, which is still ongoing for a while.
Therefore, I am unassigning myself from this task so that someone else can take it over.

**Comment by Chaitanya1672** [comment]
@Cioppolo14 I want to work on this

**Comment by Chaitanya1672** [comment]
working on it

**Comment by Chaitanya1672** [comment]
PR is raised for it
