### ISSUE TITLE
Feature request : Button on Dashboard Page of Organization 

### ISSUE THREAD

**Issue by reachaadrika** [PalisadoesFoundation/talawa-admin#195]
**Is your feature request related to a problem? Please describe.**
On the dashboard of organization , the delete organization button looks weird and a bit absurd .

**Describe the solution you'd like**
Change the way the button looks like (according to the theme , like other buttons in the web app ) 
For eg : Create organization 
I propose to create a delete organization button with a bin icon .

**Describe alternatives you've considered**
Change the way the button looks like (according to the theme , like other buttons in the web app ) 
For eg : Create organization 
I propose to create a delete organization button with a bin icon .

**Approach to be followed (optional)**
Change the styles and add a dustbin icon .

**Additional context**
![image](https://user-images.githubusercontent.com/64789514/146819522-7c520dc7-342e-4c0f-bf25-24ff5ad29a3c.png)

**Comment by reachaadrika** [comment]
If this is a valid issue can I work on this ?

**Comment by reachaadrika** [comment]
@yasharth291  I was planning to add a bin icon on the delete button , for that I would need to install react-icons library or the feather icons library in the project , Should I do it ? Or drop the idea of adding an icon ?

**Comment by yasharth291** [comment]
sure you should add it. @reachaadrika

**Comment by reachaadrika** [comment]
@yasharth291 I have added react-icons dependency to the project , so should I also commit the Package.json file in PR?

**Comment by yasharth291** [comment]
yes

**Comment by Lord-Aman** [comment]
@palisadoes I would like to work on this.

So, Here's what the procedure will look like :

Only the Creator of an Organization can delete it (according to the api) : So whenever the creator will click on the delete button, We can prompt them with all the consequences of deleting an Organization. And if he's sure to delete it then we will ask again for his password and the organization username to be manually typed. (Similar to as github does while deleting a repository ).

**Comment by Lord-Aman** [comment]
@palisadoes I think that you have mistakenly unassigned me just after assigning...

**Comment by yasharth291** [comment]
@Lord-Aman  what is the progress

**Comment by Lord-Aman** [comment]
> @Lord-Aman what is the progress
I have created a pull request for this issue : https://github.com/PalisadoesFoundation/talawa-admin/pull/238. But, due to low code coverage, it hasn't been merged yet. Also, I didn't have much idea about testing, so I'm currently learning it. Will make a new Pull Request soon with required code coverage.

**Comment by manassinghdewari** [comment]
> **Is your feature request related to a problem? Please describe.** On the dashboard of organization , the delete organization button looks weird and a bit absurd .
> 
> **Describe the solution you'd like** Change the way the button looks like (according to the theme , like other buttons in the web app ) For eg : Create organization I propose to create a delete organization button with a bin icon .
> 
> **Describe alternatives you've considered** Change the way the button looks like (according to the theme , like other buttons in the web app ) For eg : Create organization I propose to create a delete organization button with a bin icon .
> 
> **Approach to be followed (optional)** Change the styles and add a dustbin icon .
> 
> **Additional context** ![image](https://user-images.githubusercontent.com/64789514/146819522-7c520dc7-342e-4c0f-bf25-24ff5ad29a3c.png)



> **Is your feature request related to a problem? Please describe.** On the dashboard of organization , the delete organization button looks weird and a bit absurd .
> 
> **Describe the solution you'd like** Change the way the button looks like (according to the theme , like other buttons in the web app ) For eg : Create organization I propose to create a delete organization button with a bin icon .
> 
> **Describe alternatives you've considered** Change the way the button looks like (according to the theme , like other buttons in the web app ) For eg : Create organization I propose to create a delete organization button with a bin icon .
> 
> **Approach to be followed (optional)** Change the styles and add a dustbin icon .
> 
> **Additional context** ![image](https://user-images.githubusercontent.com/64789514/146819522-7c520dc7-342e-4c0f-bf25-24ff5ad29a3c.png)

Hiii I want to work on this issue .
Can i work on this issue
