### ISSUE TITLE
Upgrade @testing-library/jest-dom from 5.16.5 to 6.4.2

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#1951]
## Rationale
1. This was previously attempted by the automated dependabot job but the PR tests failed.
1. This issue has been created to fix the issue as there may be multiple dependency requirements that need updating

This is a major revision upgrade and many files may need to be updated to the new syntax, functions, methods and classes

## Task

1. Upgrade [@testing-library/jest-dom](https://github.com/testing-library/jest-dom) from 5.16.5 to 6.4.2.
1. Existing configurations must not be modified 
1. No other functionality must be affected
1. All tests must be valid and pass

## Background Failing PRs
- https://github.com/PalisadoesFoundation/talawa-admin/pull/1947

**Comment by BishalJena** [comment]
please unassign me. won't be able to get it right after couple tries.

**Comment by VanshikaSabharwal** [comment]
@palisadoes Assign me this issue and i will solve it by today.
