### ISSUE TITLE
Admin Redesign: Update the post ui in admin portal

### ISSUE THREAD

**Issue by noman2002** [PalisadoesFoundation/talawa-admin#1953]
**Describe the solution you'd like**
Update the post ui in admin portal.

https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=307-212&mode=design&t=H7b4fN3TuT0jTicu-0

**Approach to be followed (optional)**
<img width="897" alt="post" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/54404474/1defce71-6ea8-4465-a229-73bff943fb95">

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ayush-sss** [comment]
I want to work on this issue. @palisadoes please assign me this issue

**Comment by palisadoes** [comment]
@Ayush-sss, @disha1202

Please collaborate on these issues so that we reduce the duplication of code

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1953
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1954

**Comment by palisadoes** [comment]
Unassigning due to inactivity

@disha1202 You should work on this as you are doing the same work for the User portal

**Comment by disha1202** [comment]
Yes, please assign it to me.
Thanks!

**Comment by Cioppolo14** [comment]
@disha1202 Are you still working on this?

**Comment by disha1202** [comment]
Working on it. Will submit a PR soon.

**Comment by Cioppolo14** [comment]
@disha1202 Are you still working on this?

**Comment by disha1202** [comment]
Working on it.

**Comment by disha1202** [comment]
Working on it.

**Comment by palisadoes** [comment]
@disha1202 Are you still working on this?

**Comment by Ratul-Saha-003** [comment]
Can I work on this?

**Comment by disha1202** [comment]
> Can I work on this?
Sure go ahead. 

@palisadoes
I am unassigning myself from the issue because I am unable to work on this.

**Comment by palisadoes** [comment]
Unassigning. Inactive

**Comment by AnshulKahar2729** [comment]
I would like to work on this issue, please assign me @palisadoes

**Comment by Ramneet04** [comment]
@palisadoes Hey I want to work on this, Can you assign me the issue as it's my first issue and would love to start from this as i matches my interest.

**Comment by Cioppolo14** [comment]
I have assigned the first person to ask, since that is our policy.  Please keep looking for other interesting issues to complete. Thank you!

**Comment by AnshulKahar2729** [comment]
@palisadoes I think multiple PR is already merged with this issue, can you tell me the reason why it is still opened?

**Comment by palisadoes** [comment]
Thanks. Closing. We probably didn't close it after the merge
