### ISSUE TITLE
User Portal Redesign: Update post ui in user portal

### ISSUE THREAD

**Issue by noman2002** [PalisadoesFoundation/talawa-admin#1954]
**Describe the solution you'd like**
Update post ui in user portal.
https://www.figma.com/file/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?type=design&node-id=307-212&mode=design&t=H7b4fN3TuT0jTicu-0

**Approach to be followed (optional)**
<img width="897" alt="post" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/54404474/31153233-1814-4c9f-ae6f-6c0b32f75d5c">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Hi 
I would like to work on this.

**Comment by palisadoes** [comment]
@Ayush-sss, @disha1202

Please collaborate on these issues so that we reduce the duplication of code

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1953
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1954

**Comment by disha1202** [comment]
> @disha1202
> 
> I merged this PR and issue, not realizing it was a duplicate.
> 
> * [USER REDESIGN: redesign the Posts screen for the talawa user portal #1514](https://github.com/PalisadoesFoundation/talawa-admin/issues/1514)
> * [Redesign of Posts screen for talawa user portal. #1896](https://github.com/PalisadoesFoundation/talawa-admin/pull/1896)
> 
> Are you still working on this?
> 
> There needs to be an update to the design. Though there is a horizontal scroll bar for the pinned posts it's not obvious that the feature exists.
> 
> 1. A person using a computer without a touch screen will find this difficult to use.
> 2. There needs to be an intuitive way to click next / prev arrows, or dots like this:
>    
>    1. The website shown here also has the pinned posts automatically scrolling which may be the better approach.
>    
>    ![image](https://private-user-images.githubusercontent.com/16875803/329805191-8c1c05d6-7cc7-450a-ace8-6e3d2b1c3714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1MjE1NzQsIm5iZiI6MTcxNTUyMTI3NCwicGF0aCI6Ii8xNjg3NTgwMy8zMjk4MDUxOTEtOGMxYzA1ZDYtN2NjNy00NTBhLWFjZTgtNmUzZDJiMWMzNzE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDEzNDExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NjkwMDlhYWVlNmM2OTM3OWY2MzI5NTQ3ZDY3NDhhOTNlZTM5YmEwZGUzOGYxNGI2MjRlYTA5MDI2NTQ1MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zi_FQL9Tl_X5D3xEYv8FZqX4qmv05s913z9f6_uwM8U)
> 
> @aashimawadhwa @rishav-jha-mech Do you have any suggestions to add?

Yes, I'll add this feature for better user experience.

**Comment by palisadoes** [comment]
Thanks

**Comment by disha1202** [comment]
Hi @palisadoes 

Is this okay?

https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/2b2db88f-da7b-4fef-be48-b5a35c53e466

**Comment by palisadoes** [comment]
1. Yes, it does.  @aashimawadhwa @rishav-jha-mech @DMills27 @Kevoniat What do you think?
2. Do we have a mechanism for removing pinned posts? Is there an archive option, a convert to regular posts or do we have to delete it? It's out of scope for this issue, but it wouldn't be good to have 100 pinned posts to scroll through

**Comment by disha1202** [comment]
> 2. Do we have a mechanism for removing pinned posts? Is there an archive option, a convert to regular posts or do we have to delete it? It's out of scope for this issue, but it wouldn't be good to have 100 pinned posts to scroll through

Yes, the admins and super admin can unpin posts from admin portal.
<img width="1440" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/b01756ef-e3c1-4540-a6df-dba7763237dc">

**Comment by disha1202** [comment]
@palisadoes 

What about promoted posts (advertisements)

1. Should we display advertisements similar to pinned posts in a horizontal scrollable section?
2. Or like normal posts?


This is how it looks right now.
<img width="1440" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/2bed37c6-5905-470b-9880-f60b3302c6bb">

**Comment by disha1202** [comment]
@palisadoes 
This is not in the scope of this issue but right now the number of posts fetched from the server is hardcoded. It only fetches 10 posts. Ideally we should implement infinite scroll or pagination. 

And if we implement pagination/infinite scroll, then this will not work as expected. We'll need two different queries, one for fetching only pinned posts and other for fetching normal posts.

I'll create a separate issue for it after I am done with this.

**Comment by palisadoes** [comment]
Thanks. The desire is to have infinite scroll for unpinned posts. Check @aashimawadhwa and @rishav-jha-mech on slack for details

**Comment by disha1202** [comment]
Working on it.

**Comment by Cioppolo14** [comment]
@disha1202 Are you still working on this?

**Comment by disha1202** [comment]
Working on it.

**Comment by palisadoes** [comment]
@disha1202  Are you working on this?

**Comment by disha1202** [comment]
Working on it.
