### ISSUE TITLE
Redesign Fund Pledge Screen, Add/Edit Modals & Add Search/Sort

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-admin#1979]
**Is your feature request related to a problem? Please describe.**
- The current Pledge screen table is inconsistent with rest of the Talawa design system.
- The add pledge button overlaps, logged in user component (at right top).
- Add Search & Sort (by date, amount) functionality
- No option for admin to create pledge on behalf of other members

**Current Screen:**

1] Pledge Screen
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/afd3c0f2-7f6c-4814-9d9b-705b90baeaf6)
 
2] Pledge Modal
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/c5d72595-2ceb-44fb-bbde-7d2f3a101512)

**Describe the solution you'd like**

- The current Pledge Screen should resemble existing table design, 
 E.g. People Screen:
 
![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/80c6acc1-3e0c-4c59-8b93-10547a1e57f1)

**Comment by GlenDsza** [comment]
@palisadoes Pls Assign

**Comment by Cioppolo14** [comment]
@GlenDsza Are you working on this?

**Comment by GlenDsza** [comment]
@Cioppolo14  yes
Delayed due to exams, will submit PR soon

**Comment by Cioppolo14** [comment]
@GlenDsza Checking in on this one too. I hope the exams went well!

**Comment by GlenDsza** [comment]
> @GlenDsza Checking in on this one too. I hope the exams went well!

Yes working on it
