### ISSUE TITLE
Create a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2]
Use the ones in `talawa-api` and `talawa` as a guide.

**Comment by XshubhamX** [comment]
Sir I can do this Can you please assign this to me

**Comment by yasharth291** [comment]
@palisadoes  sir it should be closed as it is done

**Comment by MayankVir** [comment]
Here @palisadoes I am working on this issue. Please assign to me!!

**Comment by yasharth291** [comment]
Contributing file is already present in the project @MayankVir i think you should read the project again

**Comment by MayankVir** [comment]
Okay.. Thanks @yasharth291

**Comment by yasharth291** [comment]
No problem :)

**Comment by palisadoes** [comment]
File already created
