### ISSUE TITLE
Screen and functionality for an OCA to add an organizational admin

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#20]
[Refer to this document for terminologies and a summary of features required in Talawa Admin.](https://palisadoesfoundation.github.io/talawa-docs/docs/features/admin-portal/admin-portal-overview)

1. When an OCA creates an organization, they must also be able to create an admin user for the organization.
2. The admin username must be unique for all the OCA's organizations

Parent issue:
#48

**Comment by yasharth291** [comment]
@DangaRanga  hello sir
