### ISSUE TITLE
URL Issue: ID Passed as Query Parameter Instead of Path Segment

### ISSUE THREAD

**Issue by lokeshsingh3721** [PalisadoesFoundation/talawa-admin#2017]
**Describe the bug**

The URL currently uses a query parameter to pass the ID (e.g., url/id=343434) instead of including the ID as part of the path (e.g., url/343434). This format does not adhere to the expected RESTful URL structure.

**To Reproduce**

1. Login as a the user 
2. go the donation page 
3. click on "view all" on the right
4. you will see not any members because of the invalid url but if you remove " id=" from the url , you will see all members. 

**Expected behavior**
All members should be visible. 

**Actual behavior**
Members are not visible .

**Screenshots**

<img width="1422" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/71646466/bedc5782-7c15-443d-a435-b7de82218798">

https://github.com/PalisadoesFoundation/talawa-admin/assets/71646466/e7df0612-30e5-4c59-8a23-6df88fc0da79

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by lokeshsingh3721** [comment]
assign me this ..

**Comment by pranshugupta54** [comment]
Hello @lokeshsingh3721, I wanted to confirm, is this issue occurring exclusively on the People screen, or is it also affecting other parts of the application?

**Comment by lokeshsingh3721** [comment]
> Hello @lokeshsingh3721, I wanted to confirm, is this issue occurring exclusively on the People screen, or is it also affecting other parts of the application?

Nah , i dont think so .

**Comment by lokeshsingh3721** [comment]
@palisadoes Could you please guide me on where to look for the correct types to replace instances of any in the code? Some places have any written, which is preventing me from committing the code. How should I address this properly?

Thank you.

**Comment by palisadoes** [comment]
Please ask on the slack `#talawa-admin` channel

**Comment by lokeshsingh3721** [comment]
@palisadoes I want to add types. 

There are three ways:- 

1) add on the top of the file. 
2) make a folder called types in the root dir and then put the types there. 
3) create a file in that same folder.

please suggest me.
