### ISSUE TITLE
ADMIN: Implement Tags UI (GSoC)

### ISSUE THREAD

**Issue by meetulr** [PalisadoesFoundation/talawa-admin#2037]
### Describe the feature.

Adding support for `Tags` in the admin.

### Describe the solution you'd like

Making the `Tags` UI, adding a `Tags` option in the sidebar that would show us organization tags, as shown in the image below:

![Organization_ Tags](https://github.com/PalisadoesFoundation/talawa-admin/assets/55585268/14b9371f-e9ab-44eb-b915-9bc49d3f2173)

### Additional context

This issue is part of the GSoC project `Tag management system`.

**Comment by meetulr** [comment]
Please assign this to me.

**Comment by Cioppolo14** [comment]
@meetulr Are you still working on this?

**Comment by meetulr** [comment]
yes

**Comment by meetulr** [comment]
will start raising PRs soon...

**Comment by ajitkumarpal1** [comment]
i see   a PR is merged so this issue should be closed

**Comment by meetulr** [comment]
There'll be more PRs.

**Comment by Cioppolo14** [comment]
@meetulr Is this still something you're working on?

**Comment by meetulr** [comment]
Yes, it’s on hold due to potential design adjustments related to upcoming features. I plan to expand this issue to include additional features and cover them in either one PR or multiple simultaneous PRs
