### ISSUE TITLE
Showing API unavailable while doing signup

### ISSUE THREAD

**Issue by Priyang1310** [PalisadoesFoundation/talawa-admin#2039]
![Screenshot 2024-06-13 145641](https://github.com/PalisadoesFoundation/talawa-admin/assets/139229134/ed748a37-333a-4378-9fff-8167cd7f41ae)
As you can see I am unable to signup

**Comment by gautam-divyanshu** [comment]
@Priyang1310 you have to run the api which is in other repo, read the installation.md of talawa api and admin.
