### ISSUE TITLE
Add Test Coverage Check for Pull Requests as a GitHub Action

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#205]
**Is your feature request related to a problem? Please describe.**

1. The code base is insufficiently testable.
1. We need all code to be tested as part of each pull request.

**Describe the solution you'd like**

1. We need a way to add a GitHub action that automatically checks the codebase for the percentage coverage by tests.
1. The check should error out when the percentage is below a predefined level
1. The aim is that we’ll set increasingly higher percentage coverage until the codebase is 100% covered
1. We also want to ensure and verify that all tests in the repo are automatically run as part of each pull request as a GitHub action.
1. We also need to be able to report on the current code coverage percentage for the repo using the `codecov` tool. We use this with Talawa where a badge in the README.md file displays the code coverage value. [![codecov](https://codecov.io/gh/PalisadoesFoundation/talawa/branch/develop/graph/badge.svg?token=3PJXIKRS1S)](https://codecov.io/gh/PalisadoesFoundation/talawa)
 1. Ideally the modified workflow would create a `lcov.info` file that could be analyzed with a GitHub action like `VeryGoodOpenSource` which we have successfully used with `Talawa`.

**Describe alternatives you've considered**

1. None

**Approach to be followed (optional)**

1. **Pushes:** 
    1. The update / creation of a `push.yml` GitHub Action file that updates the `codecov` dashboard with each push. An example of how this could work is in the [`push.yml` file we use in the Talawa repo](https://github.com/PalisadoesFoundation/talawa/blob/develop/.github/workflows/push.yaml).
1. **Pull Requests:** 
    1. The update of the `pull-request.yml` GitHub Action file that will generate code coverage data in an `lcov.info` file. [An example of how this could work is provided by the codecov team](https://about.codecov.io/blog/javascript-code-coverage-using-github-actions-and-codecov/).
    1. The integration of the [VeryGoodOpenSource](https://github.com/VeryGoodOpenSource/very_good_coverage) GitHub action to analyze the `lcov.info` file created by the previous step. The minimum coverage level of the GitHub action must be set to the current code coverage level.

**Additional context**

A similar issue was created for Talawa-API:
- https://github.com/PalisadoesFoundation/talawa-api/issues/419

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

**Comment by palisadoes** [comment]
@yasharth291 I added this because though we run tests on the repo with each pull request, we are not checking the code coverage level with an aim to improving it. This should help. We recently implemented something similar for Talawa. Let me know your comments. It looks like an easy fix.

**Comment by yasharth291** [comment]
I will fix it in 2 days sir

**Comment by yasharth291** [comment]
@palisadoes  i need which framework is being used here to test the code. because if we are using any jest cases it would be really easy to do it.

**Comment by palisadoes** [comment]
What framework are we using now? Are we using any at all?

**Comment by yasharth291** [comment]
we are using many frameworks for testing right now we should be sticking to anyone which should be jest only

**Comment by palisadoes** [comment]
OK, then let's standardize on jest and use that for calculating code coverage

**Comment by yasharth291** [comment]
yes

**Comment by palisadoes** [comment]
Please proceed.

**Comment by yasharth291** [comment]
we have to create an issue regarding it to change the current test to jest component

**Comment by palisadoes** [comment]
Please go ahead.

**Comment by palisadoes** [comment]
Please use this code to create a badge in the `README.md` file:

[![codecov](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/branch/develop/graph/badge.svg?token=II0R0RREES)](https://codecov.io/gh/PalisadoesFoundation/talawa-admin)

`[![codecov](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/branch/develop/graph/badge.svg?token=II0R0RREES)](https://codecov.io/gh/PalisadoesFoundation/talawa-admin)`

**Comment by Devesh21700Kumar** [comment]
@yasharth291 @palisadoes I would like to work on this issue.

**Comment by Devesh21700Kumar** [comment]
> @yasharth291 @palisadoes I would like to work on this issue.

I tested on my branch that this Github action successfully uploads coverage report to codecov

  *Code-Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test --watchAll=false --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1 *

**Comment by palisadoes** [comment]
- We need to also have an action that fails when the coverage level isn't met (PRs only) - VeryGoodOpenSource 
- It needs to run on pushes (without VeryGoodOpenSource )

**Comment by Devesh21700Kumar** [comment]
> * We need to also have an action that fails when the coverage level isn't met (PRs only) - VeryGoodOpenSource
> * It needs to run on pushes (without VeryGoodOpenSource )

Yeah in package.json I can change threshold parameters for lines and statements 
![image](https://user-images.githubusercontent.com/59202075/148670416-e0769c3c-3374-47f5-9376-11b8bbe01c0b.png)

if the % falls below the given percentage then it will automatically fail (also tested this)

Adding this to both pull-request.yml and push.yml will do the job

**Comment by Devesh21700Kumar** [comment]
> > * We need to also have an action that fails when the coverage level isn't met (PRs only) - VeryGoodOpenSource
> > * It needs to run on pushes (without VeryGoodOpenSource )
> 
> Yeah in package.json I can change threshold parameters for lines and statements ![image](https://user-images.githubusercontent.com/59202075/148670416-e0769c3c-3374-47f5-9376-11b8bbe01c0b.png)
> 
> if the % falls below the given percentage then it will automatically fail (also tested this)
> 
> All of this can happened using the same action above
> 
> Adding this to both pull-request.yml and push.yml will do the job

The present test coverage after #215 is merged would be around 21.5% so i think that i should set the threshold to 21% or so

**Comment by palisadoes** [comment]
- We need to have the threshold value placed in the GitHub action configuration for it to work correctly with the GitHub workflow. 
- We have done it that way for Talawa and Talawa-API

**Comment by palisadoes** [comment]
Please look at those workflows for inspiration

**Comment by Devesh21700Kumar** [comment]
Sure
