### ISSUE TITLE
Event Action Items are Displayed on the Organization Action Item Screen

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2058]
**Describe the bug**

1. Event Action Items are Displayed on the Organization Action Item Screen
2. In this case the Vyvyan Kerry action item was created in an event and is visible in the Organization acreen

    ![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/16875803/55a7b534-a6fe-4d74-84f0-920bd4dbfff5)

**To Reproduce**

1. Create an event action item
2. The action item is visible on the organization wide action item screen

**Expected behavior**

1. Event specific action items must not be visible in the Organization (non-event) action items screen
2. Write tests to verify this behavior. No other functionality must be affected.

**Actual behavior**

- See above

**Potential internship candidates**

- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Alfredoeb9** [comment]
I'd like to take this on, but just a few questions. Following To Reproduce steps listed above: 

1. I click on Action Items tab on the left navigation bar then click create 

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/32616945/78048a7b-2a1b-4c65-a5bb-2ea3c048d1ec)

2. After I create a new Action Item it gets displayed but where would the Organization (non-event) action items screen be? 

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/32616945/e895dadd-5a7c-4a0f-b3e1-37d1771562e9)

I'm confused on expected behavior if there can be more clarification on this.

**Comment by palisadoes** [comment]
1. You have the correct screen.
2. There is a separate action item screen for events under the event itself

**Comment by Alfredoeb9** [comment]
Can you send a screen shot of the "separate action item screen for events under the event itself". Not sure I see that screen on my end.

**Comment by palisadoes** [comment]
1. Please create an event.
2. Look at the event details
3. There is an action item screen there too

**Comment by Alfredoeb9** [comment]
I created an event and then clicked on the event details ( "i" icon under options) 

Which now I am on the "Action items Details" screen modal. Is the bug that the buttons on bottom of the modal are not suppose to be there? @palisadoes 
![image](https://github.com/user-attachments/assets/d928e1cc-a80f-41b7-ab85-69e31d1590c7)

**Comment by palisadoes** [comment]
The issue is that action items created for events are visible as action items created at the organization level.

1. Action items created for events should only be visible on the events detail screen
2. Action items created for for the organization as a whole should only be visible on the organization action item screen.

If this is not possible, then the API needs to be modified to handle this differentiation.

**Comment by Alfredoeb9** [comment]
Ahh I see the issue now! I'll get on that ASAP! Thank you for the clarification.

I'll follow up if the API layer is the problem.
