### ISSUE TITLE
Upgrade the `react-scripts` package to latest version to eliminate security vulnerabilities

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#206]
**Describe the bug**

We have many dependabot security notifications for the repo.

- https://github.com/advisories/GHSA-ww39-953v-wcq6
- https://github.com/advisories/GHSA-93q8-gq69-wqmw
- https://github.com/advisories/GHSA-rp65-9cf3-cjxr
- https://github.com/advisories/GHSA-c36v-fmgq-m8hx
- https://github.com/advisories/GHSA-33f9-j839-rf8h
- https://github.com/advisories/GHSA-whgm-jr23-g3j9
- https://github.com/advisories/GHSA-w8qv-6jwh-64r5

The recommended fixes are:
- Upgrade `browserslist` to the earliest fixed version of 4.16.5.
- Upgrade `immer` to version 9.0.6 or later. 
- Upgrade `nth-check` to version 2.0.1 or later.
- Upgrade `glob-parent` to version 5.1.2 or later. 
- Upgrade `ansi-regex` to version 5.0.1 or later. 

However, the vulnerabilities are  related to Talawa-Admin using `react-scripts v4.0.3 `. 

- `react-scripts@4.0.3 requires immer@8.0.1 via a transitive dependency on react-dev-utils@11.0.4`
- `react-scripts@4.0.3 requires nth-check@^1.0.2 via a transitive dependency on css-select@2.1.0`
- `react-scripts@4.0.3 requires glob-parent@^3.1.0 via a transitive dependency on chokidar@2.1.8`
- `react-scripts@4.0.3 requires browserslist@^4.16.6 via a transitive dependency on @babel/helper-compilation-targets@7.14.5`
- `react-scripts@4.0.3 requires browserslist@^4.16.6 via a transitive dependency on core-js-compat@3.15.2`
- `react-scripts@4.0.3 requires browserslist@4.14.2 via a transitive dependency on react-dev-utils@11.0.4`

**_NOTE_** : These packages repeatedly show vulnerabilities. The most likely way to improve our long term security is to upgrade `react-scripts` package to the latest version. 

**To Reproduce**

See above

**Expected behavior**
Elimination of dependabot errors.

**Actual behavior**
See above

**Screenshots**
![image](https://user-images.githubusercontent.com/16875803/147888299-d2bdb972-af8c-4ffb-8eba-27a8a265ac45.png)

**Additional details**

**Comment by Devesh21700Kumar** [comment]
From #209 it seems like upgrading react-scripts to latest version will cause other dependencies and packages to be a bit incompatible as well.
Upgrading is leading others to have problems among themselves if not upgraded.

**Comment by Devesh21700Kumar** [comment]
> From #209 it seems like upgrading react-scripts to latest version will cause other dependencies and packages to be a bit incompatible as well. Upgrading one package is leading others to have problems among themselves if not upgraded.

I have marked that PR as draft for now.

**Comment by palisadoes** [comment]
@Devesh21700Kumar Please request to be assigned the issue in future. This prevents more than one person from working on this. I am going to close this PR.

- https://github.com/PalisadoesFoundation/talawa-admin/pull/209
