### ISSUE TITLE
USER: implement chat UI (GSOC)

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-admin#2060]
**Is your feature request related to a problem? Please describe.**
Implement Chat UI in user portal.

**Describe the solution you'd like**
<img width="744" alt="image" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/58461801/1b4e31b7-cd2b-436b-9678-32a6d57eea28">

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Please assign this to me.

**Comment by pranshugupta54** [comment]
@disha1202, PR looks merged - can we close this issue?

**Comment by disha1202** [comment]
Yes, we can.
