### ISSUE TITLE
[UI]- Responsiveness issues [Parent issue]

### ISSUE THREAD

**Issue by Devesh21700Kumar** [PalisadoesFoundation/talawa-admin#207]
`Parent Issue`

There are instances where responsiveness is not maintained and the UI becomes inconsistent

Here are some screenshots:-

Possible solution:- Adding a margin-right

1). At a width breakpoint of 1024px The navbar navlinks go below the navbar (overflow)
![image](https://user-images.githubusercontent.com/59202075/148770828-d08adf04-5ee1-427f-9189-ef46d73ccfd2.png)

Possible solution:- Replacing with a hamburger menu at that width

2). Dashboard with the tags section and delete button

![image](https://user-images.githubusercontent.com/59202075/147916540-38720e37-7191-4f10-914b-646674695a04.png)

3). People's Section

![image](https://user-images.githubusercontent.com/59202075/147916585-9e219383-0003-454e-a2d4-5fed096ffbdb.png)

4). All sections have their main content portion not correctly spaced and overflowing beyond the viewports when opened and when the screen is smaller

![image](https://user-images.githubusercontent.com/59202075/147916831-92dedf5a-c845-4433-8bcd-68706efdfdca.png)

It overflows towards the left

The UI in the Plugins section was working correctly and had almost 0 issues with responsiveness but the rest of the sections have it

They can be refactored to be made maximum responsive

(not sure whether it good to have them clubbed at once or to break them separately into separate issues so went with the former)

Children Issues:-
- [x] #221 
- [x] #222 
- [x] #223 
- [x] #224

**Comment by Devesh21700Kumar** [comment]
@yasharth291 @palisadoes

**Comment by palisadoes** [comment]
@Devesh21700Kumar Do you want to work on this?

**Comment by Devesh21700Kumar** [comment]
Yeah sure, I'll try to fix as many as I can.

**Comment by Devesh21700Kumar** [comment]
@palisadoes created a Tasklist of children issues and referenced the parent in each of the children issues

**Comment by palisadoes** [comment]
Thanks. This should help resolve the overall situation.

**Comment by Devesh21700Kumar** [comment]
@palisadoes @yasharth291 This can be closed as well as all 4 tasks are done
