### ISSUE TITLE
USER: Add Campaign & My Pledges Screen in user portal

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-admin#2070]
**Is your feature request related to a problem? Please describe.**
The Admin Portal supports almost all aspects of Funds/Campaigns/Pledges but User portal doesn't have any screens to access Funds/Campaigns/Pledges.

The User portal misses following screen/features:
- **Campaigns screen** displaying all campaigns ongoing in organization.
- Functionality to **make a pledge** for a campaign.
- **My Pledges** screen showing all pledges and mock functionality to pay certain amount.
- All the search/sort functionality required for above screens.

**Describe the solution you'd like**
- Add Campaigns Tab in SideNav which will redirect to Campaigns Screen displaying all ongoing campaigns in organization.
- Add functionality to pledge certain amount towards a campaign via the Campaign Screen
- Add My Pledges Tab in SideNav which will redirect to My Pledges Screen displaying all the pledges 
- Add mock functionality to pay certain amount of a pledge

**Comment by GlenDsza** [comment]
approaches:
1. Campaigns tab in SideNav redirects to Campaign Screen displaying all ongoing campaigns.
2. Funds Tab in SideNav Redirect to Funds screen which first shows all funds and then via a fund, user can see all associated campaigns

@palisadoes which approach should be followed, suggest if something else should be implemented

**Comment by GlenDsza** [comment]
Pls assign

**Comment by piyushzingade** [comment]
assign to me please I can solve this issue
