### ISSUE TITLE
USER: Misplaced Screen Title & Fix Layout Structure

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-admin#2071]
**Describe the bug**
In User Portal, across the screens, The title of the screen is placed in child container, resulting in empty space at top of all screen. Like Admin Portal, Screen Titles should be move from screen container to Parent Outlet Container.

**To Reproduce**

1. Login to User Portal
2. Visit All screens and view empty space between title due to misplacement in screen container instead of Parent Outlet container.

**Expected behavior**
All the Screen title's should be moved from individual screen container to parent outlet container.

**Actual behavior**
Screen title's are placed in child screen container resulting in uneven look and empty space at top of screen.

**Screenshots**

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/53720a83-55eb-49db-bdc5-8588f0d82022)

![image](https://github.com/PalisadoesFoundation/talawa-admin/assets/109027247/ca76bde9-9dc6-4af6-91ec-e77d58cb54b6)

Similarly for other screen as well.

**Comment by GlenDsza** [comment]
Pls Assign

**Comment by dhanagopu** [comment]
@GlenDsza Our policy is to assign no more than two issues to each contributor across all repositories.  This way everyone gets a chance to participate in the projects, You have reached your limit, please wait until your existing issues are closed before requesting more issues.

**Comment by anuragnegi000** [comment]
assign this issue to me

**Comment by anuragnegi000** [comment]
sorry for the delay, i'm still working on it give me some more time please

**Comment by anuragnegi000** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/assets/115611556/9129af9c-50c3-41bd-8205-7eb4ff352a29

I have made changes within the child container itself without moving items from the child to the parent. The results are as expected. If any further changes are needed, please let me know. Otherwise, please grant me permission to raise a PR.

**Comment by palisadoes** [comment]
1. This looks OK.
2. You don't need to ask permission to raise a PR or create an issue.

**Comment by anuragnegi000** [comment]
![why](https://github.com/user-attachments/assets/671513ea-2bc1-4468-8e19-0c21025282c3)
why i'm getting these conflicts while re-setting up the project

**Comment by palisadoes** [comment]
Please ask our slack channel for assistance

**Comment by AnshulKahar2729** [comment]
Is anurag still working on this?

**Comment by anuragnegi000** [comment]
@AnshulKahar2729 yes

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by anuragnegi000** [comment]
@palisadoes yes i am working on this

**Comment by palisadoes** [comment]
Unassigning inactivity

**Comment by anuragnegi000** [comment]
I am working on it please assign me

**Comment by palisadoes** [comment]
Unassigning. Inactivity

**Comment by VanshikaSabharwal** [comment]
@palisadoes please assign me this issue.

**Comment by VanshikaSabharwal** [comment]
i am working

**Comment by VanshikaSabharwal** [comment]
I have raised PR

**Comment by VanshikaSabharwal** [comment]
i have raised PR and working on this issue.
