### ISSUE TITLE
Login issue 

### ISSUE THREAD

**Issue by lokeshsingh3721** [PalisadoesFoundation/talawa-admin#2098]
**Describe the bug**

login page giving error

**To Reproduce**

1. start the project locally
2. go to the http://localhost:4321/
3. you will see an error (if not logged in )
4. if logged in, please logout. 

**Expected behavior**
Login page should be functional 

**Actual behavior**
Login page is not functional 

**Screenshots**
<img width="1429" alt="image" src="https://github.com/user-attachments/assets/7495f622-0673-4f93-9324-e66c09dbf0ac">

**Additional details**
Browser [mozila firefox]
OS [MacOS]

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by lokeshsingh3721** [comment]
please assign me this issue.

**Comment by anuragnegi000** [comment]
@lokeshsingh3721 Hello lokesh, login page is working totally fine at my side, maybe you have missed some installation part

**Comment by varshith257** [comment]
@lokeshsingh3721 Login page seems working fine. Pull latest upstream of both admin and api and make ensure you are on develop branches on both repos.

If you need further assistance, reach out at slack in talawa-admin channel
