### ISSUE TITLE
USER : Profile Details Overlap on User Dashboard After Registration

### ISSUE THREAD

**Issue by Saanvi26** [PalisadoesFoundation/talawa-admin#2099]
**Describe the bug**
Upon successfully registering as a user, the user dashboard displays an overlap issue in the Profile Details section, where the email address is superimposed on the profile image. This UI glitch reduces the user experience, and for long names, it results in poor UI, decreasing the readability.

**To Reproduce**

1. Setting up Talawa-api and Talawa-admin
2.Register and Login as a USER
3.Navigate to the USER dashboard
4.In cases of long names and email the UI glitch can be observed. 

**Expected behavior**
A column layout for the avatar image and other details, along with a tooltip to display the full text when it is overflowing, when hovered over.

**Actual behavior**
Overflowing of long names and emails out of the block giving rise to a poor UI.

**Screenshots**
<img width="488" alt="Screenshot 2024-07-18 at 2 45 50 AM" src="https://github.com/user-attachments/assets/9189018a-ba1d-48d7-bac7-a9953f7b9fc9">
<img width="702" alt="Screenshot 2024-07-18 at 2 46 47 AM" src="https://github.com/user-attachments/assets/91107df0-1f58-4ea8-8939-387fbc8140ac">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Saanvi26** [comment]
Please assign me this issue

**Comment by YashwantOstwal** [comment]
Can @pranshugupta54  assign me this issue ?

**Comment by pranshugupta54** [comment]
This issue is already assigned, you can comment on some other issue.

**Comment by YashwantOstwal** [comment]
Hey @pranshugupta54, Can I get a high level roadmap on how to start contributing to this repository consistently. How should I approach the codebase and make most out of it and few tips on start of my Open source journey.

**Comment by anuragnegi000** [comment]
@YashwantOstwal join slack community and ask all of your doubts there
