### ISSUE TITLE
Screen and functionality for an OCA to remove an organizational admin

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#21]
[Refer to this document for terminologies and a summary of features required in Talawa Admin.](https://palisadoesfoundation.github.io/talawa-docs/docs/features/admin-portal/admin-portal-overview)

Parent issue:
#48

1. An OCA needs to have the ability to delete an organization admin.

**Comment by yasharth291** [comment]
HEllo sir
