### ISSUE TITLE
CodeQL GitHub Action Fails on Pull Requests

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#210]
**Describe the bug**
Based on this error message our CodeQL GitHub action is not configured to evaluate JavaScript on Pull Requests, but is for Pushes.

**To Reproduce**
- [Follow this link to see the actual error.](https://github.com/PalisadoesFoundation/talawa-admin/pull/208/checks?check_run_id=4698808042)
- [This is the first pull request where we noticed this issue.](https://github.com/PalisadoesFoundation/talawa-admin/pull/208)

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

- Pull Request
![image](https://user-images.githubusercontent.com/16875803/148059217-c479ccc9-9b6b-451c-a0b2-55a08f24f662.png)

- GitHub Action Error
![image](https://user-images.githubusercontent.com/16875803/148058958-dd016b7a-f03f-4dab-a590-b6219f7a8d57.png)

**Additional details**
None

**Comment by Devesh21700Kumar** [comment]
@yasharth291 @palisadoes I would like to work on this issue.

**Comment by palisadoes** [comment]
Please comment on the issue so we can assign it. I don't see your comment
there.

**Comment by palisadoes** [comment]
This is very important for us to fix.

**Comment by Devesh21700Kumar** [comment]
Yes I would like to solve this

This error is occurring in the push.yml workflow
I have to give an on.pull-request branch specification in the push.yml file then it will get fixed

![image](https://user-images.githubusercontent.com/59202075/148725187-e6436529-d9f5-42b4-afb2-504630314b7f.png)

**Comment by palisadoes** [comment]
- Please  read the [README.md](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/README.md) file in the `workflows` directory. 
- If the fix is related to pull requests, then it must be placed in the `pull-requests.yml` file.
- This works without issue in the [Talawa-API workflows](https://github.com/PalisadoesFoundation/talawa-api/tree/develop/.github/workflows). Please use that as a reference.

**Comment by Devesh21700Kumar** [comment]
> * Please  read the [README.md](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/README.md) file in the `workflows` directory.
> * If the fix is related to pull requests, then it must be placed in the `pull-requests.yml` file.
> * This works without issue in the [Talawa-API workflows](https://github.com/PalisadoesFoundation/talawa-api/tree/develop/.github/workflows). Please use that as a reference.

I think that talawa-api also has the same issue
![image](https://user-images.githubusercontent.com/59202075/148731847-14dd6dd7-2a60-4087-8cca-468c3cc67f28.png)

https://github.com/PalisadoesFoundation/talawa-api/pull/415/checks?check_run_id=4684406167

**Comment by palisadoes** [comment]
Then why does it work with Talawa-API and not this repo?  Talawa-API runs the workflow on pull-reqests and pushes, but in separate files.

**Comment by Devesh21700Kumar** [comment]
> Then why does it work with Talawa-API and not this repo? Talawa-API runs the workflow on pull-reqests and pushes, but in separate files.

the errors are of talawa-api
It has these errors as well

**Comment by palisadoes** [comment]
Please provide a link to where it's failing in `talawa-api`, I want to get a better picture of your research.

**Comment by Devesh21700Kumar** [comment]
> Please provide a link to where it's failing in `talawa-api`, I want to get a better picture of your research.

https://github.com/PalisadoesFoundation/talawa-api/pull/415/checks?check_run_id=4684406167

https://github.com/PalisadoesFoundation/talawa-api/actions/runs/1646204512

**Comment by palisadoes** [comment]
If you expand the actions you'll see that the CodeQL actions ran and are
green.

Please double check

**Comment by Devesh21700Kumar** [comment]
> If you expand the actions you'll see that the CodeQL actions ran and are green. Please double check

![image](https://user-images.githubusercontent.com/59202075/148776831-6e407f14-f442-4bb3-8b11-4454ba19b137.png)

Just checked
pls check this link
https://github.com/PalisadoesFoundation/talawa-api/pull/415/checks

**Comment by Devesh21700Kumar** [comment]
> > If you expand the actions you'll see that the CodeQL actions ran and are green. Please double check
> 
> ![image](https://user-images.githubusercontent.com/59202075/148776831-6e407f14-f442-4bb3-8b11-4454ba19b137.png)
> 
> Just checked pls check this link https://github.com/PalisadoesFoundation/talawa-api/pull/415/checks

also this 
![image](https://user-images.githubusercontent.com/59202075/148776993-c0542ccd-918e-409f-8ce4-b7c93698f93a.png)

https://github.com/PalisadoesFoundation/talawa-api/pull/415#partial-pull-merging

**Comment by palisadoes** [comment]
OK. Please proceed with your solution.
