### ISSUE TITLE
Add reply to messages functionality in direct chat and group chat (GSoC)

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-admin#2103]
**Is your feature request related to a problem? Please describe.**
Add reply to messages functionality in direct chat and group chat
**Describe the solution you'd like**
Users should be able to reply to messages in direct chat and group chat
**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
![image](https://github.com/user-attachments/assets/da7a822d-1623-4d86-b9ef-f67ab921d29d)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Please assign

**Comment by coderpawan** [comment]
- Okay lets modify the schema of the message to include parent id also and if the messsage is top then parent id is set to null.
- creating post api to get the req from /message/:parentid/reply.
- as we hit the reply button on the message a post api would be called
- here we will handle the function and receive the parent text message which would be shown in frontend as a parent message.
- now a input would be provided along with the parent message which would be broadcasted to all the clients connected on web socket/socket.io being it a personal chat or groupchat

I am ready to take this assignment

**Comment by Cioppolo14** [comment]
@disha1202  I am closing this issue, as the PR is merged.  Please let me know if I need to reopen it.
