### ISSUE TITLE
Improving User Experience During Login/Registration with Non-Intrusive Loading Indicators

### ISSUE THREAD

**Issue by ajitkumarpal1** [PalisadoesFoundation/talawa-admin#2110]
**Is your feature request related to a problem? Please describe.**
Currently, when a user attempts to log in or register, the entire form disappears, and a circular loader is displayed in the center of the screen. This abrupt transition can be disorienting and frustrating for users. After the loader, the user is either redirected or remains on the same page with an error pop-up. This process blocks the entire page, which is not user-friendly and can lead to a poor user experience.
**Describe the solution you'd like**
To improve the user experience, the form should not disappear entirely. Instead:

1. Disable Form on Submit: When the form is submitted, disable the form fields and submit button to prevent multiple submissions.
2. Dim Background: Reduce the opacity of the background when the loader appears to indicate that an action is being processed without completely hiding the form.
3. Top Loader Indicator: or we can Use a progress bar or loader at the top of the page instead of a full-screen loader. This keeps the form visible and provides a visual indicator that the process is ongoing.

**Describe alternatives you've considered**

1. we can reduce the opacity of lower back ground 
2. or we can disable the form field and show a progress bar on top of page

**Additional context**
1. login page
![Screenshot 2024-07-22 210756](https://github.com/user-attachments/assets/43e1d3c0-5aa5-482e-bbe1-a9f009616de0)
2. after click on login
![Screenshot 2024-07-22 211213](https://github.com/user-attachments/assets/ceef786c-ab09-497c-83a7-594ad26bcaa8)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Prakhar-commits** [comment]
can you please assign this issue to me @varshith257

**Comment by ajitkumarpal1** [comment]
@varshith257 please assign me this issue  here i update it already
![Screenshot 2024-07-23 102942](https://github.com/user-attachments/assets/00566f98-ae32-45ac-af98-c6f57a1a21be)

**Comment by Cioppolo14** [comment]
@ajitkumarpal1 Are you working onthis?

**Comment by AnshulKahar2729** [comment]
I would like to work on this issue if ajit is not working.

**Comment by AnshulKahar2729** [comment]
Should we do the same thing to register or just log in?

**Comment by palisadoes** [comment]
I'll approve this as most websites follow this design aesthetic, however we must not eliminate the loading page anywhere else. We have other more important areas to focus on, such as reducing our code bloat and the resulting high memory utilization.
