### ISSUE TITLE
Text Input Allowed in Donation Field Causes Runtime Error and Incorrect Success Message

### ISSUE THREAD

**Issue by ajitkumarpal1** [PalisadoesFoundation/talawa-admin#2112]
**Describe the bug**
Currently in donation page the DONATION field allows in text and its even makes toast appear as sucessfully **_img 2_** while giving a following error Uncaught runtime errors

**To Reproduce**

1. go to donation page
2. type random text and click on button
3.  you get an error and when you close the error you'll get successfull toast message

**Expected behavior**
1. Donation field should not allow any text field
2. even if it allows a text we can have error toast and not let it send sucessfull

**Screenshots**
**img 1**
![Screenshot 2024-07-23 124924](https://github.com/user-attachments/assets/7f1f4947-1757-4857-a512-b73d5ebebfdc)
**img 2**
![Screenshot 2024-07-23 124904](https://github.com/user-attachments/assets/ed67ee33-e369-41ca-8276-0cae7aea5d97)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ajitkumarpal1** [comment]
@palisadoes @pranshugupta54  please assign me ...

**Comment by Girishbari** [comment]
@ajitkumarpal1 update your issue title

**Comment by ajitkumarpal1** [comment]
> @ajitkumarpal1 update your issue title

👍okay

**Comment by Cioppolo14** [comment]
@ajitkumarpal1 Are you working on this?

**Comment by AnshulKahar2729** [comment]
If ajitkumar is not working on this, I would like to work on this issue.

**Comment by AnshulKahar2729** [comment]
> @ajitkumarpal1 Are you working on this? 

@palisadoes I think the PR of the previous assignee is already closed and there has been no update from the past long time from him. In that case, I would like to work on this issue.
