### ISSUE TITLE
Bug Report - Under Profile Page - Marital status dropdown settings.separated translation not available

### ISSUE THREAD

**Issue by mahak-juriani** [PalisadoesFoundation/talawa-admin#2115]
**Describe the bug**
Under Profile Page - Marital status dropdown settings.separated translation not available

**To Reproduce**

1. Login
2. Go to user profile page
3. Click on marital status dropdown
4. last option shows as settings.separated

**Expected behavior**
Marital status should show Separated as an option

**Actual behavior**
Marital status shows settings.separated as an option

**Screenshots**
<img width="914" alt="Talawa - settings separated" src="https://github.com/user-attachments/assets/4e47d215-fac8-46ca-ba05-33e6b398bdbd">

https://github.com/user-attachments/assets/764ee3fc-c014-4b91-84e1-764e82391651

**Comment by mahak-juriani** [comment]
Please assign this to me as a good first issue 🙌 
I've made the changes, will create a PR once unapproved tag is removed.
Thanks

**Comment by mahak-juriani** [comment]
@varshith257 @pranshugupta54 Please assign this to me as a good first issue 🙌
I've made the changes, will create a PR once unapproved tag is removed.
Thanks

**Comment by palisadoes** [comment]
1. Please write tests as part of the PR. 
2. We don't want this error to be repeated.
3. Ensure that you test all the drop down values and placeholder text in all languages.

**Comment by mahak-juriani** [comment]
Hey @palisadoes 
Could you please assign a priority tag to this issue
For example, if this seems to be a medium issue - could you please assign a label priority : medium
Requesting this since my university provides grades on the basis of priority of the issue I'm solving
Thanks in advance 🙌
