### ISSUE TITLE
Bug Report - Organizations Page placeholder, rows option fix

### ISSUE THREAD

**Issue by mahak-juriani** [PalisadoesFoundation/talawa-admin#2117]
**Describe the bug**
Under My Organizations - for pagination options - rows per page has an option of -1, 
search placeholder shows 'Search users' instead of 'Search organizations'

**To Reproduce**

1. Login as User
2. Go to My Organizations
3. Search bar placeholder shows 'Search users' instead of 'Search organizations'
4. One more, at the bottom rows per page dropdown has an option with -1 value

**Expected behavior**
Placeholder should be Search organizations.
-1 should not be an option for rows per page

**Screenshots**
<img width="499" alt="Talawa - select organization placeholder" src="https://github.com/user-attachments/assets/7540b0b9-1496-4f4f-b89b-d112a0b45565">

<img width="479" alt="rows per page -1" src="https://github.com/user-attachments/assets/bc63eae9-7751-4298-923c-27a72b941d48">

**Comment by mahak-juriani** [comment]
Please assign me this issue as good first issue.
Will close this fast once approved. Thanks

**Comment by mahak-juriani** [comment]
Please assign me this issue @varshith257 @pranshugupta54 as good first issue
Thank you

**Comment by palisadoes** [comment]
1. Please write tests as part of the PR. 
2. We don't want this error to be repeated.
3. Ensure that you test all the drop down values.

**Comment by Cioppolo14** [comment]
@mahak-juriani Are you working on this?

**Comment by Ramneet04** [comment]
@Cioppolo14 hey can I work on this, I'll make sure to do it as early it is possible
Thanks..

**Comment by Ramneet04** [comment]
I have resolved the issue why I got Unassigned here?? @mahak-juriani

**Comment by Ramneet04** [comment]
Hey @palisadoes I have solved the Bug over here But how can run test to check it?? Here's the screenshots.
![RowsPerPage](https://github.com/user-attachments/assets/3e47abb1-6ab7-4452-9f02-c283e3e61e48)
![Uploading SearchOrg.PNG…]()

**Comment by palisadoes** [comment]
Please ask the `#talawa-admin` slack channel

**Comment by Ramneet04** [comment]
Alright

**Comment by Ramneet04** [comment]
Will raise pr in a day or 2 days.

**Comment by palisadoes** [comment]
Unassigning. inactivity.

**Comment by AnshulKahar2729** [comment]
@palisadoes  Would like to work on this

**Comment by palisadoes** [comment]
@AnshulKahar2729 

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by prayanshchh** [comment]
can i work on this issue?

**Comment by prayanshchh** [comment]
I have fixed the bug, I just need to write tests, can you assign the issue?

**Comment by prayanshchh** [comment]
Hi, there is not test present for Pagination, shall I create a file?
