### ISSUE TITLE
Bug Report: Parent container and create advertisement button are clashing/colliding

### ISSUE THREAD

**Issue by anuragnegi000** [PalisadoesFoundation/talawa-admin#2119]
**Describe the bug**
The design of parent container and create new advertisement button are clashing

**To Reproduce**

1.Login as admin
2.Click on advertisement

**Expected behavior**
There should be a proper gap between both parent and button

**Actual behavior**
Both are clashing

**Screenshots**
![advertisement](https://github.com/user-attachments/assets/074e6d00-6bca-4e86-bd73-8be1768bc0b1)

**Additional details**
No

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by anuragnegi000** [comment]
Please assign this issue to me

**Comment by Cioppolo14** [comment]
@anuragnegi000 Are you still working on this?

**Comment by anuragnegi000** [comment]
yes @Cioppolo14
