### ISSUE TITLE
[BUG] Type 'StaticMockLink' is not assignable to type 'ApolloLink'

### ISSUE THREAD

**Issue by Raj-Mandal-20** [PalisadoesFoundation/talawa-admin#2121]
**Describe the bug**
Showing Type 'StaticMockLink' is not assignable to type 'ApolloLink' in each and every test files.

**To Reproduce**

1. start your `talawa-admin` development server you will see this error

**Screenshots**
![image](https://github.com/user-attachments/assets/8b97e642-b17b-42b6-b2f7-597bdb2d0075)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
1. Closing. 
2. This is not reproduceable.
3. Ensure you are using the develop branch in all cases
