### ISSUE TITLE
Instead of rendering component, whole page is reloading!

### ISSUE THREAD

**Issue by asmitsirohi** [PalisadoesFoundation/talawa-admin#214]
**Describe the bug**
While rendering components from the navigation bar page is reloading. Instead of just rendering the component.

**Here is GIF**
![demo_talawa](https://user-images.githubusercontent.com/63240102/148642335-44d55c56-1f82-4421-a146-53a85bd5a21f.gif)

**Possible solution**
When the user clicks on a navigation link, only the component is loaded instead of the whole page.

**Comment by palisadoes** [comment]
Do you want to work on this?

**Comment by asmitsirohi** [comment]
Yeah sure, I'll fix this one.
