### ISSUE TITLE
Learn More button opens link in the same tab instead of a new tab

### ISSUE THREAD

**Issue by NayanshiSingh** [PalisadoesFoundation/talawa-admin#2146]
Describe the bug:
A clear and concise description of what the bug is:
On the home page, when clicking the "Learn More" button, the link opens on the same page instead of opening in a new tab.

To Reproduce:

1. 
2. Go to the home page.
3. Click on the "Learn More" button.
4. Observe that the link opens in the same tab.
5. Expected behavior:
6. A clear and concise description of what you expected to happen:
7. The "Learn More" button should open the link in a new tab, not in the same tab.

Desktop :

OS:  Windows 11
Browser chrome
Version 23H2

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by NayanshiSingh** [comment]
@palisadoes can you assign this issue to me?

**Comment by Cioppolo14** [comment]
Thank you for your submission! We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

I am going to close this.
