### ISSUE TITLE
Change Twitter to X links

### ISSUE THREAD

**Issue by BishalJena** [PalisadoesFoundation/talawa-admin#2147]
**Describe the bug**

In social column it should be X instead of twitter.
**To Reproduce**

1. Scroll down to footer
2. Check socials

**Expected behavior**
Should show "https://x.com/palisadoesorg?lang=en"
**Actual behavior**
the link shows "https://twitter.com/palisadoesorg?lang=en" 

**Screenshots**
![image](https://github.com/user-attachments/assets/b7301024-33fa-4138-8bed-7281533ed3d3)
**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by BishalJena** [comment]
im working on this!

**Comment by Cioppolo14** [comment]
@BishalJena Thank you for submitting your issue. In the future, please ask to be assigned the issue and wait for a reviewer to review, approve, and assign.

**Comment by BishalJena** [comment]
I'd like to be unassigned here. Let anyone else try solving this issue.

**Comment by Atharv-2004** [comment]
can @Cioppolo14 assign this issue to me?

**Comment by Atharv-2004** [comment]
@varshith257 Can you give me a collaborator role to raise the pr

**Comment by varshith257** [comment]
@Atharv-2004 You don't need a collaborator acces to raise PR. Please follow the getting started guide and fork this repo to raise PR

**Comment by Atharv-2004** [comment]
@varshith257 @Cioppolo14  Can anyone review my pr please?

**Comment by AnshulKahar2729** [comment]
Atharv any updates regarding this issue, if not I would like to work on this.

**Comment by Suswetha6** [comment]
Hey @palisadoes @Atharv-2004 ,can i work on this issue ?
