### ISSUE TITLE
GSoC: Redesign & Add Delete, Search, Sort for Action Item Categories (ADMIN)

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-admin#2165]
**Is your feature request related to a problem? Please describe.**
There are various common features such as search sort and delete features are missing on Action Items & Action item Category Screen. These screens could be redesigned and refactored to match UI system of Talawa Project
Bug: 
- Organization Left Drawer misses scroll bar, so for small height screens clicking on last options is not possible
- In Left Drawer, Organization image avatar gets stretched on small screens 

**Describe the solution you'd like**

**Action Item Category Screen:**
- Add Delete functionality (Modal) & description while creation
- Add Search, search by and Sort functionality
- Display Active/Disabled for each Action Item Categories 
- Redesign screen, Add/View & Edit Modal for Action Item Category

**Action Item Screen (Global):**
- Add search options along with filters
- Add Delete Functionality (Modal)
- Add Due Date & status as Late or Label like 2 days remaining per action item
- Redesign screen, Add/View & Edit Modal for Action Item Category

- Similarly update Event Dashboard Event Actions screen w.r.t global *Action Items Screen.

Existing Screens:
Action Item Category (Settings)
![image](https://github.com/user-attachments/assets/5efc5773-d95f-4b96-a776-bf41535fb090)

Action Items screen (Global)
![image](https://github.com/user-attachments/assets/7eaebc47-3583-49c8-8a24-8782c3dd6862)

Action Items screen in Event Management Dashboard
![image](https://github.com/user-attachments/assets/a6cb0fdb-bbc2-4e30-a333-448cec420ed8)

**Comment by GlenDsza** [comment]
@palisadoes Pls assign

**Comment by Ramneet04** [comment]
Hi, I want to design these functionalities, Can you assign me too?

**Comment by Cioppolo14** [comment]
@Ramneet04 Thank you for your interest. We assign one person per issue.
