### ISSUE TITLE
Setup Script doesn't set the REACT_APP_BACKEND_WEBSOCKET_URL

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2183]
**Describe the bug**

1. The setup script doesn't set the REACT_APP_BACKEND_WEBSOCKET_URL `.env` file variable
    1. This parameter is required for the proper functioning of plugins
1. The use of this parameter is not described in the `INSTALLATION.md` file

**To Reproduce**

1. Run the setup script. The parameter is not requested or updated
2. The parameter is not described in the `INSTALLATION.md` file

**Expected behavior**

1. The parameter must be automatically configured based on the value of `REACT_APP_TALAWA_URL` parameter value
2. The parameter must be described in the `INSTALLATION.md` file

**Actual behavior**

- See above

**Screenshots**

- N/A

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Cappybara12** [comment]
Can you please assign this issue to me

**Comment by palisadoes** [comment]
Unassigning. You already have 2 issues across our repos. Let's give others a chance.

**Comment by Yashgupta9330** [comment]
@palisadoes can you pls assign it to me?

**Comment by palisadoes** [comment]
Unassigning. inactivity

**Comment by akshayw1** [comment]
I could fix this, Please assign

**Comment by zakhaev26** [comment]
Can i work on this @palisadoes

**Comment by varshith257** [comment]
@zakhaev26 let's give @akshayw1 a chance to solve it as commented first

**Comment by Yashgupta9330** [comment]
@varshith257 Could you please reassign this task to me? I had previously written the code, but only 1-2 test cases were failing. After that, I contracted dengue, which is why I couldn't continue.

**Comment by varshith257** [comment]
@akshayw1 I will assign you the issue you requested in the Slack

**Comment by varshith257** [comment]
Okay raise it. Let's see

**Comment by Yashgupta9330** [comment]
hey @varshith257 I made the pr can you check?

**Comment by palisadoes** [comment]
Unassigning. Inactivity

**Comment by adithyanotfound** [comment]
If no one is working on this issue please assign the issue to me
