### ISSUE TITLE
Screen and functionality for an OCA to delete organization

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#22]
[Refer to this document for terminologies and a summary of features required in Talawa Admin.](https://palisadoesfoundation.github.io/talawa-docs/docs/features/admin-portal/admin-portal-overview)

Parent issue:
#48

1. An OCA needs to have the ability to delete an organization and all its content.
2. There must be sufficient safeguards to reduce the risk of accidental deletion.

**Comment by XshubhamX** [comment]
@palisadoes adding member to organization or removing them will be done from talawa app ,if i'm right?

**Comment by ssaumyaa7** [comment]
@palisadoes Sir we can start this only after the base structure of admin portal is created right ?

**Comment by XshubhamX** [comment]
@ssaumyaa7 I am currently building the home page and login page for the application so that a person having a valid id can atleast login to the portal.I will make pr in 3-4 days after that this issue can be tackled

**Comment by ssaumyaa7** [comment]
@XshubhamX that's great... okay

**Comment by yasharth291** [comment]
hello sir
