### ISSUE TITLE
[UI-responsiveness] Navigation bar is not responsive for viewports

### ISSUE THREAD

**Issue by Devesh21700Kumar** [PalisadoesFoundation/talawa-admin#221]
**Describe the bug**
`CHILD ISSUE`

Navigation bar is not responsive for viewports (at width break points of 1024px and less)

Mobile View:-

![image](https://user-images.githubusercontent.com/59202075/148887648-eac5e3ad-bb0e-472b-8b5c-222512c2c5dd.png)

Tablet/Ipad view

![image](https://user-images.githubusercontent.com/59202075/148887794-aaf56614-66e8-45a0-bc83-a1ee0dd051bf.png)

**Expected behavior**
Navbar remains responsive

Expected solution:-
A hamburger which expands on click at about 1024px max-width breakpoint

Parent issue:-
- [ ] #207

**Comment by asmitsirohi** [comment]
@palisadoes @Devesh21700Kumar I'm working on this one.

**Comment by Devesh21700Kumar** [comment]
> @palisadoes @Devesh21700Kumar I'm working on this one.

Sure
