### ISSUE TITLE
Fix the Admin and User Portal's `User Profile` Screen

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2219]
**Describe the bug**

1. Improper capitalization and spacing with the drop down values.
1. Many  pre-populated values are not required

**To Reproduce**

1. Log into the relevant portal
2. Select the User Profile
3. View the user's profile screen values

**Expected behavior**

1. The bug issues should be rectified in all supported languages
2. All other functionality must be maintained
3. Complete and valid tests must be added to verify your changes

**Actual behavior**

- See screenshot section

**Screenshots**

1. Improper capitalization and spacing with the drop down values. Translations for each are required
    ![image](https://github.com/user-attachments/assets/12f96f92-8086-479b-a87c-33f0919fa0b4)    
    ![image](https://github.com/user-attachments/assets/c2cc5c96-ea73-4ed4-b22b-a9db27a978d6)
    ![image](https://github.com/user-attachments/assets/d6013eff-758f-40b0-b544-aa5fcd68249f)
    ![image](https://github.com/user-attachments/assets/a91e3a9a-4d58-4b96-9094-656acbec00b2)
1. These pre-populated values are not required
    ![image](https://github.com/user-attachments/assets/19e23247-d290-44bf-8cec-35b76c342607)

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AnshulKahar2729** [comment]
Proper capitalization and spacing are correct but why prepopulated is not required.

**Comment by palisadoes** [comment]
It has very little relevance to the end user. The headings are sufficient.

**Comment by Shrijan125** [comment]
I believe there might be some confusion here. The pre-populated values are not placeholder text; they actually represent the user details stored in the database. For example, "Line1" refers to the admin's address stored in the database and it must be visible to him for making changes. Could you please clarify this further? Thank you!

**Comment by syedali237** [comment]
Can I be assigned this issue?

**Comment by akathedeveloper** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by AnshulKahar2729** [comment]
> It has very little relevance to the end user. The headings are sufficient.

@palisadoes assign me this, I will fix it but once again those pre-populated values are required. They are just looking the same in the screen shot because someone has entered the label as values.

**Comment by Abhinav232004** [comment]
@palisadoes ,Could you please assign it to me ?

**Comment by AnshulKahar2729** [comment]
> > It has very little relevance to the end user. The headings are sufficient.
> 
> @palisadoes assign me this, I will fix it but once again those pre-populated values are required. They are just looking the same in the screen shot because someone has entered the label as values. 

@palisadoes

**Comment by palisadoes** [comment]
@AnshulKahar2729 

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by prashantrai-30** [comment]
Hey @palisadoes can you tell me which part of the code is causing this problem?

**Comment by prashantrai-30** [comment]
Hey @palisadoes can you assign this to me.

**Comment by AnshulKahar2729** [comment]
> @AnshulKahar2729
> 
> Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

Ok, you can re-assign me this, one of my PR is going to be merged soon.

**Comment by duplixx** [comment]
@palisadoes I am working on it recently in my GSoC timeline

**Comment by palisadoes** [comment]
@prashantrai-30 We have to reassign this to @duplixx

**Comment by yashaghane21** [comment]
@duplixx please assign this issue to me .

**Comment by duplixx** [comment]
Hey @yashaghane21, I have already fixed this issue in my GSoC idea
