### ISSUE TITLE
[UI-responsiveness] Dashboard with the tags section and delete button

### ISSUE THREAD

**Issue by Devesh21700Kumar** [PalisadoesFoundation/talawa-admin#222]
**Describe the bug**
`CHILD ISSUE`

Dashboard with the tags section and delete button is not responsive and goes beyond the line of seperation

![image](https://user-images.githubusercontent.com/59202075/148888780-7545d12c-73f1-479a-a5e4-d8ff8e0739e4.png)

**Expected behavior**
Should remain responsive and within the line of separation between the left and right section

Grids/Flex should be correctly used/implemented

Parent issue:-
- [ ] #207

**Comment by asmitsirohi** [comment]
@palisadoes @Devesh21700Kumar  I'm working on this one as well.
