### ISSUE TITLE
The Admin Portal's Left Drawer Doesn't Scroll

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2223]
**Describe the bug**

1. The Admin Portal's Left Drawer Doesn't Scroll when the menu items don't fit vertically on the screen
2. This means it is not intuitive to access the organization settings option

**To Reproduce**

1. Adjust the magnification of the browser so that the settings menu item is not visible
2. You cannot scroll to view it

**Expected behavior**

1. There should be a scrolling ability
2. No other functionality must be affected
3. All tests for correcting this issue must be thorough and valid

**Actual behavior**

No scrolling

**Screenshots**

https://github.com/user-attachments/assets/df4caaef-aa14-4596-9ea1-219edb6c709c

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by syedali237** [comment]
Can I be assigned to this issue?

**Comment by GlenDsza** [comment]
@palisadoes Pls assign

**Comment by GlenDsza** [comment]
@palisadoes This can be closed now
