### ISSUE TITLE
Move the Organization `Agenda Items Category` menu to the Organizations `Settings` menu

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2225]
**Is your feature request related to a problem? Please describe.**

1. Move the Organization `Agenda Items Category` menu to the Organizations `Settings` menu
2. The current UI/UX does not match that of the similar `Action Item Categories` functionality

**Describe the solution you'd like**

1. Move the Organization `Agenda Items Category` menu to the Organizations `Settings` menu
2. See the **Additional context** below for more details
2. No other functionality must be affected
3. All tests for correcting this issue must be thorough and valid

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

1. The current location of the option
    ![image](https://github.com/user-attachments/assets/f750198e-85fa-4887-a47d-a67c069bb96a)
1. The desired location of the option
    ![image](https://github.com/user-attachments/assets/19537ff8-e059-44aa-addc-b3cf7f35d44e)
1. The UI/UX must match that of `Action Items Categories` with the appropriate adjustments to make Agenda Items manageable using equivalent clicks
    ![image](https://github.com/user-attachments/assets/aad093ac-1634-4e8e-9aaa-5a49195795a7)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by GlenDsza** [comment]
@palisadoes @tasneemkoushar  Pls Assign

**Comment by GlenDsza** [comment]
@palisadoes This can be closed now
