### ISSUE TITLE
[UI-responsiveness] People's Section checkbox type input overflows beyond line

### ISSUE THREAD

**Issue by Devesh21700Kumar** [PalisadoesFoundation/talawa-admin#223]
**Describe the bug**
 People's Section checkbox type input overflows beyond line

![image](https://user-images.githubusercontent.com/59202075/148889095-87d8dad5-5fd0-4e08-9918-6aec536aa30e.png)

**Expected behavior**
It should stay within the line and should not go beyond.
Flex and media queries should be properly used

Parent issue:-
- [ ] #207

**Comment by asmitsirohi** [comment]
@palisadoes I'm working on this.
