### ISSUE TITLE
Multiple `Add Member` Screen Layout Issues 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2232]
**Describe the bug**

1. Most of the headings are not translated
1. The heading isn't translated. The layout should reflect the key elements of the screen behind. For example, there are no icons beside the member names. 

**To Reproduce**

1. Login as an Admin or Super Admin
2. Select an organization
3. Select the people page
4. Attempt to add a new or an existing member

**Expected behavior**

**Actual behavior**

- A better user experience with the mentioned issues corrected 

**Screenshots**

1. Most of the headings are not translated
    ![image](https://github.com/user-attachments/assets/d21a9ae2-b5e5-482e-b9da-00219f331e5b)

1. The heading isn't translated. The layout should reflect the key elements of the screen behind. For example, there are no icons beside the member names. 
![image](https://github.com/user-attachments/assets/be1bc9b7-3851-4fc1-bf26-bdae7e71dc20)

**Additional details**
- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Nandika-A** [comment]
Hi @palisadoes! can I work on this issue?

**Comment by KoyalkarAditya** [comment]
Hi @palisadoes can i work on this issue too?
