### ISSUE TITLE
Max Limit for donation

### ISSUE THREAD

**Issue by AnshulKahar2729** [PalisadoesFoundation/talawa-admin#2236]
**Describe the bug**

**To Reproduce**

1. Go to the donation screen
2. Enter the donation amount

**Expected behavior**
There should be a limit for the donation.

**Actual behavior**
No limit is there right now, it just checks for nonnegative.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AnshulKahar2729** [comment]
@varshith257 @palisadoes you guys can discuss about the max limit here.

**Comment by palisadoes** [comment]
This is not necessary
