### ISSUE TITLE
[UI-responsiveness] Main content should be within viewports (no overflow)

### ISSUE THREAD

**Issue by Devesh21700Kumar** [PalisadoesFoundation/talawa-admin#224]
**Describe the bug**
`CHILD ISSUE`

All sections have their main content portion not correctly spaced and overflowing beyond the viewports when opened
and when the screen is smaller

![image](https://user-images.githubusercontent.com/59202075/148889233-4bcbc132-be8c-4cf1-89db-268cd7f1d1d2.png)

**Expected behavior**
They should remain within the viewports

Parent issue:-
- [ ] #207

**Comment by Devesh21700Kumar** [comment]
I'll work on this

**Comment by asmitsirohi** [comment]
@palisadoes I'm working on this as well.

**Comment by Devesh21700Kumar** [comment]
> @palisadoes I'm working on this as well.

Ok.

**Comment by palisadoes** [comment]
@asmitsirohi  you are working on many issues. I've allocated this to Devesh. If there are no PRs on this in a few days, I'll reassign. We've had cases in the past where people have monopolized issues and not closed them. I want to make sure everyone gets a chance.

**Comment by asmitsirohi** [comment]
> 

Ok, no problem
