### ISSUE TITLE
ADMIN: Automatic Labeling for Dependencies, Security and Design Related Issues

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2256]
**Is your feature request related to a problem? Please describe.**

1. We spend a lot of time manually labeling issues that are created.
2. Automation will significantly reduce this overhead

**Describe the solution you'd like**

Using the `auto-label` GitHub action that we currently use: https://github.com/marketplace/actions/auto-label

1. Make configuration changes to the existing `issue.yml` file. 
1. Do not rename the existing `issue.yml` file.
1. **Dependencies**
    1. When the words `dependabot`, `dependency` or `dependencies` are in the body of the issue 
    2. Add the labels `dependencies`, `security` and `good first issue`
1. **Security**
    1. When the word `security` are in the body of the issue 
    2. Add the label `security` and `good first issue`
1. **Design**
    1. When the words `layout`, `screen`, `design` or `figma` are in the body of the issue 
    2. Add the label `ui/ux` and `good first issue`

**Describe alternatives you've considered**

- See above

**Approach to be followed (optional)**

- See above
- No other functionality must be affected

**Additional context**

Related Issues. The same person must be assigned to both:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/2256
- https://github.com/PalisadoesFoundation/talawa/issues/2555

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sumitsh28** [comment]
@palisadoes Hey, can I work on this issue?

**Comment by Sumitsh28** [comment]
@palisadoes , @varshith257 I have made a PR for this issue. [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/2279)

**Comment by Sumitsh28** [comment]
@varshith257 I have already made a [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/2280)

**Comment by SGI-CAPP-AT2** [comment]
Hey There,
I would like to work on this if @Sumitsh28 is not working on it.
@palisadoes

**Comment by palisadoes** [comment]
Unassigning. Inactivity

**Comment by SGI-CAPP-AT2** [comment]
Hello @palisadoes ,
I have edits in `issues.yml` and created `auto-label.json5`.
But how can i test it on my fork ?

**Comment by palisadoes** [comment]
Please ask the #talawa-admin slack channel

**Comment by palisadoes** [comment]
Unassigning. Inactivity.

**Comment by Suyash878** [comment]
Is this issue fixed? or Are there more improvements to make because I see a PR merged regarding the same, So just wanted to clarify.

**Comment by Cioppolo14** [comment]
@SGI-CAPP-AT2 I am closing this as complete based on your merged PR.  Please let me know if this needs to be reopened.
