### ISSUE TITLE
ADMIN: Fix the `eslint_disable_check.py` script

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2257]
**Describe the bug**

1. Our code base has suffered over the years because contributors ignored linting errors
2. We created a `eslint_disable_check.py` script to detect the use of the `eslint-disable` string in files submitted in the PR
3. It does not work with this line `// eslint-disable-next-line @typescript-eslint/no-unused-vars`

**To Reproduce**

1. Submit a PR
2. Make one of the files have the following line in it
    1. `// eslint-disable-next-line @typescript-eslint/no-unused-vars`
1. The PR does not fail

**Expected behavior**

1. Submit a PR
2. Make one of the files have the following line in it
    1. `// eslint-disable-next-line @typescript-eslint/no-unused-vars`
1. The PR must fail

The script must fail with the string `eslint-disable` discovered any where in any line

**Actual behavior**

- See above

**Screenshots**

- N/A

**Additional details**

The same person should be assigned to both these issues

- https://github.com/PalisadoesFoundation/talawa-api/issues/2519
- https://github.com/PalisadoesFoundation/talawa-admin/issues/2257

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by ARYANSHAH1567** [comment]
I  fixed the issue in API. Can you please assign it to me as i would fix it in admin also

**Comment by palisadoes** [comment]
It's assigned to you

**Comment by ARYANSHAH1567** [comment]
@palisadoes Can you please close the issue since the pr is merged and i can be assigned other issues
