### ISSUE TITLE
Fix Linting for Submitted PR Files

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2259]
**Describe the bug**

1. We want to have consistent coding standards for our repositories.
2. To do this we added linting to our automated processes. 
3. On certain conditions husky commits and files committed to PRs should fail if the linting fails.
4. These issues were created to fix this:
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1427
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/1270
    1. https://github.com/PalisadoesFoundation/talawa-admin/issues/861
5. We need the linting rules to be tightened for each commit and PR 

**To Reproduce**

1. Start the server
2. Linting messages occur

We don't need the messages on starting the server to be eliminated. We just need to make sure that code committed to the code base in PRs does not have these linting issues. Eventually the linting messages will go away as the code base is improved.

**Expected behavior**

1. CLI Husky commits must fail if any of these eslint conditions are present in the committed code:
    1. react/destructuring-assignment
    2. @typescript-eslint/explicit-module-boundary-types
    3. @typescript-eslint/no-explicit-any
    4. @typescript-eslint/no-non-null-assertion
    5. @typescript-eslint/no-unused-vars
1. PRs must fail if any of these eslint conditions are present in the committed code:
    1. react/destructuring-assignment
    2. @typescript-eslint/explicit-module-boundary-types
    3. @typescript-eslint/no-explicit-any
    4. @typescript-eslint/no-non-null-assertion
    5. @typescript-eslint/no-unused-vars

**Actual behavior**

- See above

**Screenshots**

When starting the Admin server, we get these linting errors.

![image](https://github.com/user-attachments/assets/d1beadc2-7221-4e3c-8d29-32ff426a7c3b)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Abhinav232004** [comment]
@palisadoes ,Could you please assign me this issue?

**Comment by palisadoes** [comment]
Unassigning. inactivity

**Comment by Abhinav232004** [comment]
"I was working on it. Could you please assign this issue to me again?

**Comment by palisadoes** [comment]
unassigning. inactivity

**Comment by prayanshchh** [comment]
I will start my work on this in 3-4 days as festive season is going on

**Comment by prayanshchh** [comment]
do i only need to add `"@typescript-eslint/no-unused-vars": "error"` in .eslintrc.json to solve this issue, as in pull-request.yml we already have:
   run: npx eslint ${CHANGED_FILES} && python .github/workflows/eslint_disable_check.py
and in .husky/pre-commit
 npm run lint-staged
so we already have checks for linting, Is there something more to do here?

**Comment by palisadoes** [comment]
Are all the cases listed in the original issue handled?

**Comment by palisadoes** [comment]
During the week of November 11, 2024 we will start a code freeze on the `develop` branches in Talawa, Talawa Admin and Talawa-API. 

We have completed a project to convert the Talawa-API backend to use PostgreSQL. Work will then begin with us merging code in the `develop` branches to a new `develop-postrgres` branch in each repository.

Planning activities for this will be managed in our #talawa-projects slack channel. A GitHub project will be created to track specially labeled issues. We completed a similar exercise last year using a similar methodology. 

Starting November 12, California time no new PRs will be accepted against the `develop` branch. They must be applied to the `develop-postrgres` branch. 

There are some GSoC project features that will need to be merged into develop. These will be the only exceptions.

This activity and the post GSoC 2024 start date was announced in our #general Slack channel last month as a pinned post.

**Comment by prayanshchh** [comment]
> Are all the cases listed in the original issue handled?

except this rule: @typescript-eslint/no-unused-vars
everything is implemented

**Comment by palisadoes** [comment]
Thanks. Please implement that one

**Comment by prayanshchh** [comment]
alright sir

**Comment by prayanshchh** [comment]
i am unassigning myself from this one as I need to work on workflow files for postgres in api

**Comment by prayanshchh** [comment]
would be happy to do this once I am done with api issue

**Comment by palisadoes** [comment]
This needs to be done for both the `develop` and `develop-postgres` branches.

**Comment by prayanshchh** [comment]
alright I will do it after the api issue, as I already have two issues assigned

**Comment by Suyash878** [comment]
I would like to implement the necessary changes for the `develop-postgres` branch.

**Comment by Suyash878** [comment]
I am unassigning myself, since my PR got merged.
