### ISSUE TITLE
Translations Are Not Correctly Tested in Our PR Workflow

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2260]
**Describe the bug**

1. Multilingual support is an important feature of our application.
2. We need to ensure that we have translations created for every language entry
3. We created a script to test for this in Talawa mobile to test for this. It was added to this repo, but doesn't appear to work.
    1. https://github.com/PalisadoesFoundation/talawa/pull/2284
1. We need to apply the script to this repository and make adjustments where necessary. Ideally the script in both repos must be identical and apply the logic to different directory trees. Make updates accordingly.
1. Without correct translations, the end user UI/UX is unacceptable.

**To Reproduce**

- See the **Actual behavior** section below

**Expected behavior**

1. We need to create a GitHub action that during the PR process checks all the translation files to make sure that there are translations in all the non-default languages for each English default language entry.
1. As part of the PR for this issue, all the translations must be correctly present

**Actual behavior**

1. This PR failed to notice the incomplete translations
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/2254
1. Only one translation file was edited
    ![image](https://github.com/user-attachments/assets/4864b3f6-c994-48fe-bb1c-b19946d20978)
1. There are no errors in the PR workflow
    ![image](https://github.com/user-attachments/assets/6d49b062-da8a-4bb4-bf20-d7af6c246b26)
    ![image](https://github.com/user-attachments/assets/e9723a26-b672-4c9e-84df-5710182f4dc7)

**Screenshots**

- See above

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Nandika-A** [comment]
Hi @palisadoes ! Can I work on this issue?
