### ISSUE TITLE
Sync translations

### ISSUE THREAD

**Issue by pranshugupta54** [PalisadoesFoundation/talawa-admin#2264]
**Describe the bug**
We have many keywords which don't have proper translation added to their json.

**Expected behavior**
All the keywords should be properly translated. Each locale file should match for all the languages.

**Actual behavior**
We have incomplete json data.

**Screenshots**
<img width="1159" alt="image" src="https://github.com/user-attachments/assets/464c183d-2216-4525-b5b9-149d1c18ca61">

**Additional details**
Can simply use `en` locale and then translate them to other languages and sync.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by VanshikaSabharwal** [comment]
@pranshugupta54 please assign me this issue. I am willing to work on it.

**Comment by pranshugupta54** [comment]
Looks like this already got fixed in previous merged PR. Closing the issue. You can pick some other issue.
