### ISSUE TITLE
User icon on user profile

### ISSUE THREAD

**Issue by ARYANSHAH1567** [PalisadoesFoundation/talawa-admin#2267]
**Describe the bug**
The user icon of its initals exceeds it boundary which disrupts the ui of the profile page.

**To Reproduce**
Log in as User via the credentials of the user and click on the user icon and go to view profile

**Expected behavior**
As we can see for admins it is correct
![image](https://github.com/user-attachments/assets/48441a41-6fd1-4470-ade1-716d6ac7e282)

**Actual behavior**
![Screenshot 2024-09-14 223806](https://github.com/user-attachments/assets/68bb51e7-cc29-4a2b-a147-3dec4a37bf05)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aditya-bansal-7** [comment]
I like to work on this issue. Please assign it to me.

**Comment by akshayw1** [comment]
Can I work on this issue @palisadoes

**Comment by palisadoes** [comment]
1. The final output must match our official figma design
    1. https://www.figma.com/design/WksD4uIa5sQJMIk3pR4l0c/Talawa-Design-System-(Official)?node-id=307-212&node-type=canvas
    ![image](https://github.com/user-attachments/assets/d66c781a-de5e-4650-b2a1-ddb3f2c0c500)

**Comment by aditya-bansal-7** [comment]
I've made the necessary modifications, please review it now.
![image](https://github.com/user-attachments/assets/c364239b-d748-4d27-9b06-02f71aa61d11)

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

Closing
