### ISSUE TITLE
Sign-up form incorrectly treats blank spaces as special characters, causing validation errors

### ISSUE THREAD

**Issue by syedali237** [PalisadoesFoundation/talawa-admin#2283]
**Describe the bug**
When attempting to sign up, the form validation incorrectly recognizes blank spaces as special characters. As a result, users encounter validation errors when they input a name with spaces, even though spaces should be valid characters.

**To Reproduce**

1. Navigate to the sign-up form.
2. Enter the first name or last name with spaces.
3. Submit the form.

**Expected behavior**
Spaces should be ignored, and the user should be able to submit the form without errors.

**Actual behavior**
A validation error triggers a pop-up notification stating that only lower and upper-case characters are allowed.

**Video:**

https://github.com/user-attachments/assets/5b19d04c-fc3f-44e3-829a-226f57859a3d

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sumitsh28** [comment]
@syedali237 Can I work on this issue?

**Comment by syedali237** [comment]
@Sumitsh28 wait before it gets approved.

**Comment by akshayw1** [comment]
Can I work on this issue?

**Comment by syedali237** [comment]
@palisadoes Can you please review and assign this issue?

**Comment by syedali237** [comment]
Working on it.

**Comment by syedali237** [comment]
@avantika-rawat yes.
