### ISSUE TITLE
Update chat related functionalities to work with the updated chat schema (GSoC)

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-admin#2285]
**Is your feature request related to a problem? Please describe.**
Update chat related functionalities to work with the updated chat schema

**Describe the solution you'd like**
Update chat related functionalities to work with the updated chat schema

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Please assign

**Comment by akshayw1** [comment]
Please assign

**Comment by disha1202** [comment]
Closing as completed
