### ISSUE TITLE
Convert Talawa-Admin to React - Parent Issue

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#23]
**Is your feature request related to a problem? Please describe.**
@XshubhamX suggested in [Talawa-API Issue 236](https://github.com/PalisadoesFoundation/talawa-api/issues/236) that we should migrate talawa-admin to react to get more contributions.

We have decided to do this. This issue is a tracking issue against which all tasks will be managed.

**Describe the solution you'd like**

**Describe alternatives you've considered**
The current `vue.js` solution isn't getting any traction.

**Approach to be followed (optional)**
Migrate to `react.js` to get more activity in this repo.

**Child Issues**

A list of issues will be placed here as they are generated.

**Comment by XshubhamX** [comment]
@palisadoes sir the base architecture for react app is ready should i make the pr.

**Comment by palisadoes** [comment]
Yes. Ask Xavier or Jason to review.

**Comment by yasharth291** [comment]
@palisadoes i think this issue can be closed sir it is completed
