### ISSUE TITLE
Bug: List of organizations not loading upon a new registration

### ISSUE THREAD

**Issue by vaibhavityagi** [PalisadoesFoundation/talawa-admin#2303]
**Describe the bug**

**To Reproduce**

1. Select Register
2. Fill all the details
3. Submit the form

**Expected behavior**
While filling the form, a list of organisations should appear and the user should be able to register successfully.

**Actual behavior**
Due to the list of organizations not begin displayed, an error is thrown and the user is not able to register.

**Screenshots**
![image](https://github.com/user-attachments/assets/bdce2083-4817-4676-b812-e5af0d4b7c71)
![image](https://github.com/user-attachments/assets/67f5f472-e97c-4d75-9243-1135eb81484a)

**Additional details**
The error is arising as the server is returning an empty list of organizations.
![image](https://github.com/user-attachments/assets/708abfad-83ee-4a40-8522-38ce7ce2e306)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by vaibhavityagi** [comment]
I would like to take it up!

**Comment by akshayw1** [comment]
Please assign

**Comment by Yashgupta9330** [comment]
@palisadoes please assign
