### ISSUE TITLE
Upgrade @pdfme/generator from 4.5.2 to 5.0.0

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2317]
## Rationale
1. This was previously attempted by the automated dependabot job but the PR tests failed.
1. This issue has been created to fix the issue as there may be multiple dependency requirements that need updating

This is a major revision upgrade and many files may need to be updated to the new syntax, functions, methods and classes

## Task
1. Upgrade the package
1. Remove this package if it is: 
    1. unused
    3. unnecessary. For example:
        1. the functionality can be maintained by using another package we are already using, 
        3. If we are using only one function or class in the package you can consider replacing it with code that resides in this repository
        4. It is used by a feature that the end user is unlikely to ever use

## Background Failing PRs and Tests
- https://github.com/PalisadoesFoundation/talawa-admin/pull/2313
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/11097331491/job/30828434661?pr=2313

**Comment by Sumitsh28** [comment]
Can I work on this issue?

**Comment by Aryan4884** [comment]
@palisadoes if no one working,please assign this to me.

**Comment by Sumitsh28** [comment]
I was tied up with some other tasks. I'll create a PR soon.

**Comment by Sumitsh28** [comment]
I'm getting some errors while committing my code. Please help!

**Comment by palisadoes** [comment]
Please ask the #talawa-admin slack channel. Provide screen shots

**Comment by Kunalpal216** [comment]
If there are no updates by @Sumitsh28  , Can this issue be assigned to me @palisadoes ?
