### ISSUE TITLE
GSoC: Add support for Event Volunteer/Group/Membership in User/Admin Portal

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-admin#2327]
**Is your feature request related to a problem? Please describe.**
The Admin Portal & User Portal misses functionality of creating volunteers/ volunteer groups/inviting volunteers, etc.

**Describe the solution you'd like**
In Admin Portal (for Admin/Super Admin/Event Admin) in event Dashboard:
 - Add support for CRUD of Event Volunteers (Individual)
 - Add support for CRUD of Event Volunteer Groups, inviting members, etc.
 - Assign Action Items to Volunteers

In User Portal,
 - User should be able to view upcoming events, and available volunteer groups, join volunteer groups
 - User should be able to accept/reject invitations for joining events & volunteer groups
 - User should be able to view assigned action items.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SGI-CAPP-AT2** [comment]
Hey there @tasneemkoushar @GlenDsza,
Is this issue open for contributions or it's already assigned.
I would like to contribute to this issue.

**Comment by tasneemkoushar** [comment]
@SGI-CAPP-AT2 this issue is of gsoc label, open for the respective gsoc mentee only. That’s why pre-assigned.
 Can you check for any other open issues, can help to assign that.

**Comment by SGI-CAPP-AT2** [comment]
@tasneemkoushar , yes sure
Thanks for response
