### ISSUE TITLE
Upgrade package typescript from 5.6.2 to 5.6.3

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2334]
## Rationale
1. This was previously attempted by the automated dependabot job but the PR tests failed.
1. This issue has been created to fix the issue as there may be multiple dependency requirements that need updating

This is a major revision upgrade and many files may need to be updated to the new syntax, functions, methods and classes

## Task
1. Upgrade the package
1. Remove this package if it is: 
    1. unused
    3. unnecessary. For example:
        1. the functionality can be maintained by using another package we are already using, 
        3. If we are using only one function or class in the package you can consider replacing it with code that resides in this repository
        4. It is used by a feature that the end user is unlikely to ever use

## Background Failing PRs and Tests
- https://github.com/PalisadoesFoundation/talawa-admin/pull/2332
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/11318907519/job/31474168275?pr=2332

**Comment by CHIRANTH-24** [comment]
@palisadoes  could you please assign this to me?

**Comment by mandeepnh5** [comment]
@palisadoes can you please assign to me

**Comment by Anusha-pannati** [comment]
@palisadoes can you assign this issue to me

**Comment by varshith257** [comment]
@Anusha-pannati @mandeepnh5 Thanks for your enthusiasm to contribute. I have assigned to the one first commented. I think are many open good first issues. Have a look and ask to assign

**Comment by CHIRANTH-24** [comment]
@varshith257, when i run "npm run lint:check", im getting ths : 

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.7.4 <5.6.0

YOUR TYPESCRIPT VERSION: 5.6.3

Please only submit bug reports when using the officially supported version.

Do i create PR with this error?

**Comment by varshith257** [comment]
Submit PR, you can get lint fails if any in the workflow

**Comment by CHIRANTH-24** [comment]
@varshith257 
Could you please review it once

**Comment by CHIRANTH-24** [comment]
Thank you for reviewing @varshith257
