### ISSUE TITLE
Unable to run application on ARM based MacOS devices

### ISSUE THREAD

**Issue by adithyanotfound** [PalisadoesFoundation/talawa-admin#2337]
**Describe the bug**
Unable to run the application on ARM based MacOS devices.

**To Reproduce**

On a ARM based MacOS devices run:
1. `npm install`
2. `npm run serve`

**Expected behavior**

<img width="429" alt="Screenshot 2024-10-17 at 11 39 06 AM" src="https://github.com/user-attachments/assets/9db161be-e96c-466f-95df-3500497451f2">

**Actual behavior**

<img width="1195" alt="Screenshot 2024-10-17 at 11 30 40 AM" src="https://github.com/user-attachments/assets/6c0a8eff-8b69-42de-a3e9-7f4d25697bfe">

**Additional details**
1. The application runs on the main branch which suggests that one of the recent PR has caused this issue.
2. Can be fixed by installing 2 packages `@rollup/rollup-darwin-arm64` and  `@esbuild/darwin-arm64`

**System information**
VS code version: Version: 1.94.2 (Universal)
OS version: Darwin arm64 23.0.0
Device: Macbook Air M2

**Comment by DipanshuOjha** [comment]
Hi..
I would like to work on this issue

**Comment by DipanshuOjha** [comment]
Yes I am able to reproduce this in my windows 11. Just waiting to get assigned so that I can put a pull request

**Comment by DipanshuOjha** [comment]
> @DipanshuOjha, the issue is about MacOS?This  issue envolve adding of docker and docker-compose file which will helpful in mac and windows

**Comment by DipanshuOjha** [comment]
@pranshugupta54 
This issue envolves adding dockerising so which will be helpful in both mac and windows

**Comment by DipanshuOjha** [comment]
@pranshugupta54 if you dockerise the application then their is no need to install the dependencies seperately it will be installed within node_modules.

**Comment by adithyanotfound** [comment]
@pranshugupta54 That works but it is not ideal to changes package-lock.json file. Also I found PR #2186 which removes a lot of lines from the package-lock.json file which has probably caused this issue.

**Comment by akshayw1** [comment]
Can I work on the issue
