### ISSUE TITLE
Bug Report:Contributing.md file is not been updated as per the new GSOC 22 Guidelines

### ISSUE THREAD

**Issue by rohit-raje-786** [PalisadoesFoundation/talawa-admin#235]
**Describe the bug**
Looks like the contributing.md file is not been updated.

<img width="885" alt="Screenshot 2022-01-27 at 10 30 00 AM" src="https://user-images.githubusercontent.com/61861303/151294399-5f71825b-ece6-474b-aef4-8a90c0588410.png">

**Additional details**
I would like to work on this issue

**Comment by palisadoes** [comment]
Thanks, this has been updated.
