### ISSUE TITLE
Add feature to view unread messages and mark messages as read in chat (GSoC)

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-admin#2352]
**Is your feature request related to a problem? Please describe.**
Add feature to view unread messages and mark messages as read in chat

**Describe the solution you'd like**
view unread messages and mark messages as read in chat

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Please assign

**Comment by haresahani** [comment]
I’d like to work on this issue. Could you assign it to me?

**Comment by Ameerjafar** [comment]
@palisadoes can i work on this issue

**Comment by palisadoes** [comment]
This is a GSoC issue

**Comment by Faizankhan1104** [comment]
I want to work on this issue. could you plase provide more information about this issue.

**Comment by AkashMundari** [comment]
Can i work on this ??

**Comment by gurramkarthiknetha** [comment]
If no one is currently working on this issue, I would like to take it on. Please assign it to me.

**Comment by amaan-aly246** [comment]
@palisadoes Please assign this to me if possible.
Thanks
