### ISSUE TITLE
[GSoC] Add feature to filter chats, edit messages, add users to group chat, share images as messages, and create dedicated group chats for events

### ISSUE THREAD

**Issue by disha1202** [PalisadoesFoundation/talawa-admin#2359]
**Is your feature request related to a problem? Please describe.**
Add feature to filter chats, edit messages, add users to group chat, share images as messages, and create dedicated group chats for events

**Describe the solution you'd like**
Add feature to filter chats, edit messages, add users to group chat, share images as messages, and create dedicated group chats for events

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by disha1202** [comment]
Please assign

**Comment by amaan-aly246** [comment]
@palisadoes Please assign this to me if possible.
Thanks.
