### ISSUE TITLE
Write Unittests for `src/screens/UserPortal/Settings/Settings.tsx`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2369]
We will need unittests done for all methods, classes and functions found in this file.

### PR Acceptance Criteria

1. When complete this file must show **100%** coverage when merged into the code base.
1. [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/tree/develop/?displayType=list)
1. CodeRabbit must approve all your changes to the test file(s) and the file(s) under test
1. The PR will show a report for the code coverage for the file you have added. You can use that as a guide
1. No functionality must be removed to achieve this goal
1. All tests must be valid and truly test the code base

### Other Criteria

1. If this file isn't referenced in the code base then remove it. We don't want tests run on unused code

### Potential internship candidates

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akshayw1** [comment]
Can I work on issue

**Comment by GriffinAnnshual** [comment]
Hi @palisadoes, is this task still pending? I'd love to work on it and would appreciate if it could be assigned to me, as it seems inactive.

**Comment by akshayw1** [comment]
Almost has the converage, Raising PR soon, Started somewhat late because of some other issues.

**Comment by Cioppolo14** [comment]
@akshayw1  Are you working on this?

**Comment by palisadoes** [comment]
Unassigning due to inactivity and/or no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by IITI-tushar** [comment]
@palisadoes,
There was already a test file named, settings.test.tsx and i have migrated it from jest to vitest and renamed it to settings.spec.tsx in my recent [PR-2718](https://github.com/PalisadoesFoundation/talawa-admin/pull/2718).
i guess it has all unit tests for settings.tsx
If I am wrong can you provide details.
Please assign me this issue , I would love to work on it.

**Comment by IITI-tushar** [comment]
@palisadoes, as i have stated in my previous comment.
there's already a test file for it.

**Comment by palisadoes** [comment]
Closing. It's code coverage is close to 100%
