### ISSUE TITLE
Hard coded values on organization list page.

### ISSUE THREAD

**Issue by asmitsirohi** [PalisadoesFoundation/talawa-admin#237]
**Describe the bug**
There are some hard-coded values while rendering the organization list.

**To Reproduce**

1. Login into the talawa-admin portal as a super admin.
2. You can see the list of organizations (If you created one).  

**Expected behavior**
All the data should be dynamic instead of hard-coded values.

**Actual behavior**
While rendering the organization list, the admins count, members count, created date, and organization location is hard-coded. 

**Screenshots**
![image](https://user-images.githubusercontent.com/63240102/151828804-7e604b6a-659b-4a67-a2af-3933610f5319.png)

**Additional details**
To populate created date dynamically, we need to add a new field in the organization schema as a timestamp.
I'm not sure about organization location, because there is no field for this in a schema and it is not required by the user while creating the organization.

**Comment by palisadoes** [comment]
Would you like to work on this?

**Comment by asmitsirohi** [comment]
Yes, please assign it to me.
