### ISSUE TITLE
Write Unittests for `src/components/OrgSettings/AgendaItemCategories/OrganizationAgendaCategory.tsx`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2372]
We will need unittests done for all methods, classes and functions found in this file.

### PR Acceptance Criteria

1. When complete this file must show **100%** coverage when merged into the code base.
1. [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/tree/develop/?displayType=list)
1. CodeRabbit must approve all your changes to the test file(s) and the file(s) under test
1. The PR will show a report for the code coverage for the file you have added. You can use that as a guide
1. No functionality must be removed to achieve this goal
1. All tests must be valid and truly test the code base

### Other Criteria

1. If this file isn't referenced in the code base then remove it. We don't want tests run on unused code

### Potential internship candidates

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by antilpiyush89** [comment]
please assign it to me

**Comment by avantika-rawat** [comment]
Hi @palisadoes, is this still pending? I would like to work on this and request that the task be assigned to me.

**Comment by palisadoes** [comment]
@avantika-rawat There is a PR for it.

**Comment by Cioppolo14** [comment]
Unassigning due to lack of activity.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and/or no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by im-vedant** [comment]
I would like to work on it.

**Comment by im-vedant** [comment]
@palisadoes  
1. The search bar is not accepting any input and is not functioning as expected.  
2. If the description is too long, it overlaps with the adjacent cell.
Can I fix these in this issue?
![image](https://github.com/user-attachments/assets/75000e02-56f0-4663-ae40-6134c84fc466)
