### ISSUE TITLE
Fix the introspection GitHub action tests (Oct 2024)

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2385]
**Is your feature request related to a problem? Please describe.**

1. Our introspection PR tests have been failing. This seems to be caused by code that references now deprecated Event and User task functionality.
2. Here is a recent example:
    1. https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/11551343486/job/32148153150

**Describe the solution you'd like**

1. Update  the offending code to make the introspection tests pass
2. All existing tests must pass and must be valid tests of the code base
3. No other functionality must be affected

**Describe alternatives you've considered**

Here are some examples of issues fixing this in the past:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/1542
- https://github.com/PalisadoesFoundation/talawa-admin/issues/1491

**Approach to be followed (optional)**

- See above

**Additional context**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@govindsingh3477 You should be assigned to this. Please request

**Comment by govindsingh3477** [comment]
Please assign

**Comment by palisadoes** [comment]
Unassigning. Inactivity
