### ISSUE TITLE
GitHub PR Workflow Check: Talawa Admin app starts `(No Docker)`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2401]
**Describe the bug**

The GitHub PR workflow does not check whether the Talawa Admin app can start

**To Reproduce**

1. Make a change to the repo that makes the Talawa Admin app fail to start
1. Trigger the workflow to run as part of a PR
1. The workflow **_passes_**

and as expected:

1. Make a change to the repo that makes the Talawa Admin app start
1. Trigger the workflow to run as part of a PR
1. The workflow passes

**Expected behavior**

1. Make a change to the repo that makes the Talawa Admin app fail to start
1. Trigger the workflow to run as part of a PR
1. The workflow **_fails_**

and as expected:

1. Make a change to the repo that makes the Talawa Admin app start
1. Trigger the workflow to run as part of a PR
1. The workflow passes

We now have a test data that can be loaded that resides in the repo. This should be used as part of the test.

**Actual behavior**

- The Talawa Admin app isn't started and tested in the PR workflow

**Screenshots**

- N/A

**Additional details**

1. It must verify starting without Docker
1. Use this issue for reference:
    1. https://github.com/PalisadoesFoundation/talawa-api/issues/1343

**Potential internship candidates**

- Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by prashantrai-30** [comment]
Hey @palisadoes,
I would like to work on it.
Can you assign this to me :)

**Comment by adithyanotfound** [comment]
Please assign
