### ISSUE TITLE
Bug: Image Load issue in Avatar across Admin/User Portal

### ISSUE THREAD

**Issue by GlenDsza** [PalisadoesFoundation/talawa-admin#2415]
**Describe the bug**
A recent [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/2411)  to bump dicebear library cause issue due to changing .`toDataUriSync` method to .`toDataUri` and not awaiting for promise.

**To Reproduce**

1. Login to Admin Portal
2. Avatar for organizations is not visible

**Expected behavior**
Organizations avatars should be visible

**Actual behavior**
Organizations avatars are not loaded

**Screenshots**
![image](https://github.com/user-attachments/assets/6d4c97d8-2f24-4a4e-8ec1-203165a68620)

**Comment by GlenDsza** [comment]
Pls Assign

**Comment by nilaygit-10721** [comment]
please assign me this issue

**Comment by Dhiren-Mhatre** [comment]
Hi @GlenDsza, could you assign this issue to me?

Here's how I’d approach it: I’ll start by updating instances of .toDataUriSync to .toDataUri wherever needed. Since .toDataUri now returns a promise, I’ll make sure each instance is properly awaited to handle the async response.

Next, I’ll adjust any functions that depend on .toDataUri by adding async where necessary, or restructuring the function flow to support async calls.

After making these changes, I’ll thoroughly test the Admin Portal to ensure the organization avatars load as expected. If there aren’t already unit tests for avatar generation, I’ll add some to help catch similar issues if there are future updates.

**Comment by varshith257** [comment]
@adityafound

**Comment by GlenDsza** [comment]
> @GlenDsza Would you like to work on this?

Yes I would work on it

**Comment by palisadoes** [comment]
During the week of November 11, 2024 we will start a code freeze on the `develop` branches in Talawa, Talawa Admin and Talawa-API. 

We have completed a project to convert the Talawa-API backend to use PostgreSQL. Work will then begin with us merging code in the `develop` branches to a new `develop-postrgres` branch in each repository.

Planning activities for this will be managed in our #talawa-projects slack channel. A GitHub project will be created to track specially labeled issues. We completed a similar exercise last year using a similar methodology. 

Starting November 12, California time no new PRs will be accepted against the `develop` branch. They must be applied to the `develop-postrgres` branch. 

There are some GSoC project features that will need to be merged into develop. These will be the only exceptions.

This activity and the post GSoC 2024 start date was announced in our #general Slack channel last month as a pinned post.

**Comment by nilaygit-10721** [comment]
Hello @palisadoes, could you please guide me on how to contribute to backend development and suggest where I should focus my contributions?

**Comment by palisadoes** [comment]
> Hello @palisadoes, could you please guide me on how to contribute to backend development and suggest where I should focus my contributions?

Here is Our Getting Started - Developers YouTube playlist, it has all you need to know to get started. Please listen to all of them as they will help to set your expectations.
https://www.youtube.com/watch?v=YpBUoHxEeyg&list=PLv50qHwThlJUIzscg9a80a9-HmAlmUdCF&pp=gAQBiAQB

**Comment by palisadoes** [comment]
> Hello @palisadoes, could you please guide me on how to contribute to backend development and suggest where I should focus my contributions?

This issue is already assigned.

**Comment by AryanSwaroop** [comment]
Can you assign this issue to me !!

**Comment by GlenDsza** [comment]
Closing, the issue seems to have been fixed
