### ISSUE TITLE
Bug: the search button is misplaced

### ISSUE THREAD

**Issue by anuragnegi000** [PalisadoesFoundation/talawa-admin#2429]
**Describe the bug**

The search button is misaligned and not positioned as expected in the Action Items section. It should ideally be located within or immediately after the search input field.

**To Reproduce**

1. Login as admin
2. Click on Manage 
3. Navigate to Action Items
4. Observe the search button

**Expected behavior**

The search button should be positioned directly within or immediately after the search input field for easy access and improved user experience.

**Actual behavior**

The search button appears misaligned or out of place relative to the search input field, affecting usability and visual consistency.

A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

![Screenshot from 2024-11-11 13-50-47](https://github.com/user-attachments/assets/7813bbd6-8fea-4400-a9ed-58e9c326ae31)

**Additional details**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by anuragnegi000** [comment]
i would like to work on this issue

**Comment by Suvendu-UI** [comment]
i would like to work on this issue

**Comment by palisadoes** [comment]
Unassigning. Inactivity. No PR

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

Closing
