### ISSUE TITLE
Bug: address overlaps with the "Manage" button

### ISSUE THREAD

**Issue by utkarshpra78** [PalisadoesFoundation/talawa-admin#2431]
**Describe the bug**
in the /orglist route If we add a longer address, it overlaps with the "Manage" button, causing the button to hide part of the address

**To Reproduce**

1. setup the project locally
2. Login as admin
3. go to  the route /orglist
4. make a new organisation which has large address name 
5. you see that address overlap with the "Mange" button

**Expected behavior**
"Manage" button should be placed slightly below

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![Screenshot 2024-11-13 165425](https://github.com/user-attachments/assets/bdefe815-4dcf-40b8-ab7c-d2f3d71f57cc)

**Comment by utkarshpra78** [comment]
i can work on this issue. Kindly assign me this issue.

**Comment by Dante291** [comment]
@utkarshpra78 assigned

**Comment by PurnenduMIshra129th** [comment]
can i work on this issue ?

**Comment by PurnenduMIshra129th** [comment]
can i work on this issue? I have some idea to make it dynamic.

**Comment by Cioppolo14** [comment]
We only assign one person per issue.  If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.  Please check out other open issues, we would love your help.

**Comment by palisadoes** [comment]
Unassigning. Inactivity. No PR

**Comment by PurnenduMIshra129th** [comment]
assign me. I will do it

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

Closing
