### ISSUE TITLE
Bug : Smooth scrolling interrupted during infinite scroll

### ISSUE THREAD

**Issue by rahulch07** [PalisadoesFoundation/talawa-admin#2437]
**Describe the bug**
When scrolling through the user list, the page should load new users smoothly. However, currently, the screen jumps when new users are loaded, disrupting the scrolling experience.

**To Reproduce**

1. Login as super admin
3. Go to Users tab and scroll down.

**Expected behavior**
New users should load smoothly.

**Actual behavior**
The screen jumps to new users

**Screenshots**

https://github.com/user-attachments/assets/5adf6a62-9aba-494d-b9f4-4123bcb6dc3c

**Comment by rahulch07** [comment]
I would like to work on this.

**Comment by Omkar125683** [comment]
hii @dhanagopu i would like to work on this issue

**Comment by dhanagopu** [comment]
@Omkar125683  If the issue has already been assigned, please don't ask to be assigned.

**Comment by palisadoes** [comment]
unassigning. Inactivity, no PR in queue

**Comment by sezallagwal** [comment]
@palisadoes Can you assign me this issue

**Comment by palisadoes** [comment]
Unassigning. Inactivity.

**Comment by hustlernik** [comment]
I would like to work, @palisadoes
