### ISSUE TITLE
Migrate Testing Framework from Jest to Vitest

### ISSUE THREAD

**Issue by prayanshchh** [PalisadoesFoundation/talawa-admin#2456]
**Is your feature request related to a problem? Please describe.**
We are planning to migrate the testing framework in the admin repository from Jest to Vitest to leverage Vitest's compatibility with Vite and improved performance. The initial step involves setting up Vitest alongside Jest and testing with one file. If successful, further issues will be created to migrate tests incrementally.

**Describe the solution you'd like**
Set Up Vitest Configuration
Add an initial configuration for Vitest.
Ensure compatibility with the existing Vite setup in the admin repo.
Keep Jest configuration intact for now.
Write a test for a single file using Vitest to verify the setup.
Ensure the test passes without any issues.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
Here the docs for reference
https://vitest.dev/guide/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by dhirajudhani** [comment]
@prayanshchh can you assign this to me as i have previously worked with jest

**Comment by prayanshchh** [comment]
I will setup the initial configuration, there will be issues following this to migrate to vitest

**Comment by palisadoes** [comment]
@prayanshchh  There are multiple issues with the PR related to this issue. Large portions of GitHub Actions were overwritten. The quality of our PR process has been very negatively affected. Please work on getting this resolved.

- https://github.com/PalisadoesFoundation/talawa-admin/pull/2457#issuecomment-2505846512
