### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Unnati-Gupta24** [PalisadoesFoundation/talawa-admin#2462]
Currently, Talawa Admin lacks basic analytics capabilities for organization administrators to track member engagement and event participation. This makes it difficult for administrators to understand their organization's performance and growth.

I am aiming to make a simple yet effective analytics dashboard that provides:

1. Member Analytics:
   - Total member count
   - Active vs inactive member counts
   - New member count (last 30 days)

2. Event Analytics:
   - Total events count
   - Upcoming vs past events
   - Basic attendance tracking

3. Core Features:
   - Simple date filter (last 7 days, last 30 days, last 3 months)
   - Basic charts using Recharts
   - CSV export functionality
   - Mobile-responsive design

4. Technical Implementation:
   - React components
   - Apollo Client for GraphQL
   - Recharts for basic charts
   - Tailwind CSS for styling

**Additional context**
- Focus on essential metrics only
- Keep the UI clean and simple
- Ensure good performance on mobile devices
- Use clear, readable charts
- Include loading states and error handling

**Skills Required**
- Basic React knowledge
- Basic GraphQL understanding
- Simple data visualization
- CSS fundamentals

Please review it and allow me to start working on this issue

**Comment by duplixx** [comment]
@Unnati-Gupta24 
please rename the issue with relevant description and member analytics is already present in the event dashboard. It includes analytics like event attendance, demographics, and feedback.
please go through the whole codebase

**Comment by Unnati-Gupta24** [comment]
Ok sure I just rechecked it event dashboard is there. Thanks for the reply. I'll try to find another feature.
