### ISSUE TITLE
Fix the Responsiveness on Smaller Devices

### ISSUE THREAD

**Issue by gurramkarthiknetha** [PalisadoesFoundation/talawa-admin#2470]
**Bug Description**
The responsive design of the application does not work properly on small devices. The layout or specific components (as shown in the attached screenshot) do not adjust correctly when the screen size is reduced.description of what the bug is.

**To Reproduce**
Steps to reproduce the issue:

1.Open the application on a small device (e.g., a phone or small tablet).
2.Navigate to the talawa admin users
3.Observe the layout or element misalignment issues.
4.Test with various screen sizes to confirm the responsiveness problem.

**Expected Behavior**
The application should maintain a user-friendly and visually consistent layout across all devices, including small screens. Elements should dynamically resize or reflow to adapt to the screen size.

**Actual Behavior**
On smaller devices, the design fails to adjust, leading to issues such as:

Overlapping text or elements.
Content overflowing the screen or requiring horizontal scrolling.
Buttons or interactive elements becoming misaligned.

**Screenshots**
<img width="387" alt="image" src="https://github.com/user-attachments/assets/a714494b-df38-4f8c-afda-08c3c9bb9504">

**Additional Details**
This issue affects the usability of the app on mobile devices, which could limit its accessibility. Consider reviewing the CSS styles or implementing a more robust responsive design framework.

**Action for Internship Candidates**
For those interested in applying for a Palisadoes Foundation internship, this issue can be a great opportunity to showcase your skills. Follow these steps to start contributing:

Read through the detailed internship guide: [Palisadoes Foundation Talawa Issue #359](https://github.com/PalisadoesFoundation/talawa/issues/359).
Understand the project's design principles and responsive frameworks in use.
Develop and test a solution for this bug.

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

Closing
