### ISSUE TITLE
Refactor: `src/components/AddOn/core/AddOnRegister/AddOnRegister.test.tsx`from Jest to Vitest

### ISSUE THREAD

**Issue by varshith257** [PalisadoesFoundation/talawa-admin#2479]
**Is your feature request related to a problem? Please describe.**

This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**

1. Replace Jest-specific functions and mocks with Vitest equivalents and rename from `test.tsx` to `spec.tsx`
2. Ensure all tests in `src/components/AddOn/core/AddOnRegister/AddOnRegister.test.tsx`  pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration 
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional Context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation: 
  https://vitest.dev/

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by VishnuGurrapu** [comment]
@varshith257 Could you please assign this issue to me? It was my first contribution, and I would like to continue contributing to this organization.

**Comment by varshith257** [comment]
Welcome @VishnuGurrapu
