### ISSUE TITLE
Refactor : `src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.test.tsx` from Jest to Vitest

### ISSUE THREAD

**Issue by prayanshchh** [PalisadoesFoundation/talawa-admin#2485]
**Is your feature request related to a problem? Please describe.**

This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**

1. Replace Jest-specific functions and mocks with Vitest equivalents and rename from test.tsx to spec.tsx
2. Ensure all tests in `src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.test.tsx` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
 https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93

- Vitest documentation: 
https://vitest.dev/

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by bandhan-majumder** [comment]
Can I work on this issue?

**Comment by palisadoes** [comment]
@bandhan-majumder You already have 2 issues across the repos. Unassign yourself from one of the others. The API issue is on hold until further notice

**Comment by bandhan-majumder** [comment]
One thing to notice here. In this test, the "update advertisement" is checking whether the toast shows the message 'Advertisement created successfully' or not. It should have been 'Advertisement updated successfully'. But how this test was passing everytime? 
https://github.com/PalisadoesFoundation/talawa-admin/blob/c2630ae47b94ddfd787fbd5fb024b57dbbdf8e7c/src/components/Advertisements/core/AdvertisementRegister/AdvertisementRegister.test.tsx#L343

**Comment by palisadoes** [comment]
Please fix the test. There may be test `ignore` statements that are affecting the results

**Comment by bandhan-majumder** [comment]
There is already open PR which is under review.

**Comment by bandhan-majumder** [comment]
Hi @palisadoes . I was working on this issue again after seeing no progress and was able to reach at the completion of test, but when I was about to push, I was someone else has already solved and their code was merged 5 days ago. It means there was a duplicate issue. It did not feel good actually. Anyway, thanks to the person who has already solved it :). You can check [here](https://github.com/PalisadoesFoundation/talawa-admin/tree/develop-postgres/src/components/Advertisements/core/AdvertisementRegister) to verify. This issue can be closed now.
