### ISSUE TITLE
Refactor : `src/components/Advertisements/Advertisements.test.tsx` from Jest to Vitest

### ISSUE THREAD

**Issue by prayanshchh** [PalisadoesFoundation/talawa-admin#2486]
**Is your feature request related to a problem? Please describe.**

This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptane Criteria**

1. Replace Jest-specific functions and mocks with Vitest equivalents and rename from test.tsx to spec.tsx
2. Ensure all tests in `src/components/Advertisements/Advertisements.test.tsx` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
 https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93

- Vitest documentation: 
https://vitest.dev/

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by khushipatil1523** [comment]
can i work on it

**Comment by khushipatil1523** [comment]
hey @prayanshchh  can i work on these issue

**Comment by palisadoes** [comment]
@khushipatil1523  

You made a typo in your PR template which made me think you had not been assigned the original issue. Please resubmit your PR. 

- https://github.com/PalisadoesFoundation/talawa-admin/pull/2705

**Comment by gurramkarthiknetha** [comment]
If no one is currently working on this issue, I would like to take it on. Please assign it to me.

**Comment by khushipatil1523** [comment]
@palisadoes I sincerely apologize for the typo in my PR template that led to the confusion. I've corrected the mistake and resubmitted the PR for your review. Thank you for understanding!

**Comment by palisadoes** [comment]
Glad you're back.
