### ISSUE TITLE
Refactor : `src/components/AgendaItems/AgendaItemsPreviewModal.test.tsx` from Jest to Vitest

### ISSUE THREAD

**Issue by prayanshchh** [PalisadoesFoundation/talawa-admin#2490]
**Is your feature request related to a problem? Please describe.**

This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**

1. Replace Jest-specific functions and mocks with Vitest equivalents and rename from test.tsx to spec.tsx
2. Ensure all tests in `src/components/AgendaItems/AgendaItemsPreviewModal.test.tsx` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
 https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93

- Vitest documentation: 
https://vitest.dev/

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by dhirajudhani** [comment]
Hii @prayanshchh can you assign this me

**Comment by prayanshchh** [comment]
@varshith257

**Comment by gurramkarthiknetha** [comment]
Please assign this issue to me, and I will work on it.

**Comment by palisadoes** [comment]
> Please assign this issue to me, and I will work on it.


Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

https://github.com/PalisadoesFoundation/talawa-admin/issues/assigned/gurramkarthiknetha

![image](https://github.com/user-attachments/assets/73f293bf-fd5b-423a-95f5-0477ded7ea5e)

**Comment by palisadoes** [comment]
@dhirajudhani 

Unassigning due to inactivity and/or no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by arpit-chakraborty** [comment]
If no one is assigned, Can i work on this issue?

**Comment by arpit-chakraborty** [comment]
Can you mention the file paths that is needed for jest to vitest, I got little confused by seeing the prior PR's.

**Comment by palisadoes** [comment]
Please ask in the #talawa-admin Slack channel. There will be others there who have worked on this

**Comment by arpit-chakraborty** [comment]
I have done multiple test and the current file in the develop-postgres branch and there are no further changes to be made. please have a look and close the PR, and unassign me if there are no changes to make. 

![image](https://github.com/user-attachments/assets/f48ece27-b15e-4ec4-ad25-c2fea5eb1f4a)
Here are the test results
