### ISSUE TITLE
Refactor : `src/components/CheckIn/CheckInModal.test.tsx` from Jest to Vitest

### ISSUE THREAD

**Issue by prayanshchh** [PalisadoesFoundation/talawa-admin#2494]
**Is your feature request related to a problem? Please describe.**

This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptane Criteria**

1. Replace Jest-specific functions and mocks with Vitest equivalents and rename from test.tsx to spec.tsx
2. Ensure all tests in `src/components/CheckIn/CheckInModal.test.tsx` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
 https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93

- Vitest documentation: 
https://vitest.dev/

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by shivasankaran18** [comment]
@palisadoes can I work on this issue ..Fixed it locally !

**Comment by dhanagopu** [comment]
@shivasankaran18 Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by shivasankaran18** [comment]
can I work on this issue..?
