### ISSUE TITLE
Bug report for README.md Error

### ISSUE THREAD

**Issue by sumitra19jha** [PalisadoesFoundation/talawa-admin#25]
**Describe the bug**
The `README.md` doesn't contains the link of `contributing.md` and `Talawa Docs` github

**To Reproduce**

1. Open README.md
2. Go to Documentation Section

**Expected behaviour**
Instead of text named link, the actual link should be present

**Actual behaviour**
A text named link is present

**Screenshots**

![Screenshot 2021-05-01 at 7 33 06 PM](https://user-images.githubusercontent.com/35868598/116784862-10f10c00-aab4-11eb-8a69-9a3594a8f7ce.png)

**Others**

**Comment by yasharth291** [comment]
Thank you for showing this i will do this
