### ISSUE TITLE
Refactor CSS files in src/screens/LoginPage

### ISSUE THREAD

**Issue by AVtheking** [PalisadoesFoundation/talawa-admin#2509]
# Refactor CSS files in src/screens/LoginPage

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

**Comment by devender18** [comment]
@AVtheking could you please assign this to me ?

**Comment by puneetk0** [comment]
@palisadoes can you assign this to me ?

**Comment by Cioppolo14** [comment]
@puneetk0 If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by gurramkarthiknetha** [comment]
If no one is currently working on this issue, I would like to take it on. Please assign it to me.

**Comment by palisadoes** [comment]
@devender18

**Comment by devender18** [comment]
> @devender18
> 
> Unassigning due to inactivity and/or no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

Could you please assign this task to me? I've already created the PR, but there are some failing checks that need to be investigated. The failures seem to be related to the tests, and since my changes are limited to the CSS file, there shouldn’t be any issues with the functionality. However, I will look into why the test cases are failing and address the problem accordingly.

**Comment by palisadoes** [comment]
With this issue we are migrating from the previous green based color scheme where the #31bb6b color was used for many elements to one using a color scheme similar to that of Gmail.

This makes the app more usable for people with red/green color blindness

When making your changes, make the effort to use pre-existing colors in the `src/style/app.module.css` file.
