### ISSUE TITLE
Refactor CSS files in src/screens/ManageTag

### ISSUE THREAD

**Issue by AVtheking** [PalisadoesFoundation/talawa-admin#2510]
# Refactor CSS files in src/screens/ManageTag

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

**Comment by MayankJha014** [comment]
I am starting work on this

**Comment by MayankJha014** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/pull/2704

PR for this file

**Comment by MayankJha014** [comment]
@AVtheking @palisadoes Guys check my recent PR

**Comment by gurramkarthiknetha** [comment]
If no one is currently working on this issue, I would like to take it on. Please assign it to me.

**Comment by palisadoes** [comment]
@MayankJha014 You submitted a PR without the issue being assigned. We merged this by accident. Our policy is to ensure PRs are submitted by people assigned the issue to reduce confusion and allow everyone to get a chance to contribute. This is not in keeping with the spirit of the Palisadoes community

**Comment by MayankJha014** [comment]
> @MayankJha014 You submitted a PR without the issue being assigned. We merged this by accident. Our policy is to ensure PRs are submitted by people assigned the issue to reduce confusion and allow everyone to get a chance to contribute. This is not in keeping with the spirit of the Palisadoes community

@palisadoes  Sorry Next time this will not happen i will keep in mind
