### ISSUE TITLE
Refactor CSS files in src/screens/MemberDetail

### ISSUE THREAD

**Issue by AVtheking** [PalisadoesFoundation/talawa-admin#2511]
# Refactor CSS files in src/screens/MemberDetail

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

**Comment by gurramkarthiknetha** [comment]
Please assign this issue to me, and I will work on it.

**Comment by palisadoes** [comment]
> Please assign this issue to me, and I will work on it.


Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

https://github.com/PalisadoesFoundation/talawa-admin/issues/assigned/gurramkarthiknetha

![image](https://github.com/user-attachments/assets/73f293bf-fd5b-423a-95f5-0477ded7ea5e)

**Comment by swastikCommits** [comment]
Please assign me this issue.

**Comment by Cioppolo14** [comment]
Unassigning due to lack of activity.

**Comment by Sumitsh28** [comment]
@Cioppolo14 Can I work on this issue?

**Comment by palisadoes** [comment]
@Sumitsh28 

Unassigning due to inactivity and/or no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by palisadoes** [comment]
With this issue we are migrating from the previous green based color scheme where the #31bb6b color was used for many elements to one using a color scheme similar to that of Gmail.

This makes the app more usable for people with red/green color blindness

When making your changes, make the effort to use pre-existing colors in the `src/style/app.module.css` file.

**Comment by mandeepnh5** [comment]
@palisadoes  can i work on this issue?
