### ISSUE TITLE
Refactor CSS files in src/screens/OrganizationEvents

### ISSUE THREAD

**Issue by AVtheking** [PalisadoesFoundation/talawa-admin#2514]
# Refactor CSS files in src/screens/OrganizationEvents

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

**Comment by harshk-89** [comment]
I have started working on it. I will finish my work as soon as possible. Please assign it to me @palisadoes .

**Comment by harshk-89** [comment]
Please review the approach I have followed. If there are any inconsistencies, I am open to addressing them. My approach is as  follows:

1. Update CSS Import Path:
I updated the import path in the relevant files from ./organizationEvents.module.css to import styles from '../../style/app.module.css';.

2. Identify Similarities and Conflicts:
I carefully analyzed the styles in both app.module.css and organizationEvents.module.css to identify overlapping or similar CSS rules. For entries that were similar, I created a parent class to properly scope the styles. This ensured that there were no conflicts between styles and that the functionality of both components remained intact.

3. Handle Redundancies:
While reviewing organizationEvents.module.css, I discovered several redundant styles, such as duplicate CSS rules applied to multiple elements. I consolidated these redundant entries to streamline the CSS, improving maintainability and reducing unnecessary duplication.

Final Outcome:
I migrated all CSS rules from organizationEvents.module.css to app.module.css, eliminating the dependency on organizationEvents.module.css. This change removed the reliance on local CSS within the organizationEvents directory and made the component dependent on the global CSS file (app.module.css).

**Comment by palisadoes** [comment]
Please open a PR and let the reviewers decide

**Comment by palisadoes** [comment]
With this issue we are migrating from the previous green based color scheme where the #31bb6b color was used for many elements to one using a color scheme similar to that of Gmail.

This makes the app more usable for people with red/green color blindness

When making your changes, make the effort to use pre-existing colors in the `src/style/app.module.css` file.

**Comment by harshk-89** [comment]
Okay, I will take care of that.
