### ISSUE TITLE
Refactor CSS files in src/screens/OrganizationFundCampaign

### ISSUE THREAD

**Issue by AVtheking** [PalisadoesFoundation/talawa-admin#2515]
# Refactor CSS files in src/screens/OrganizationFundCampaign

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is to convert the CSS file in this subdirectory and all the components related to this screen to use this new design pattern. This means that:
1. All CSS files in this subdirectory and all the CSS files in related components must be merged into the global CSS file using pre-existing CSS.
2. All CSS files in this subdirectory and all the CSS files in related components must be deleted after the merge.
3. The remaining relevant files in this subdirectory must only reference the global CSS file.
4. All the CSS files in the related components of this subdirectory must adhere to the same guidelines.

**Comment by Sumitsh28** [comment]
@Cioppolo14 Can I work on this?

**Comment by palisadoes** [comment]
@Sumitsh28

**Comment by palisadoes** [comment]
With this issue we are migrating from the previous green based color scheme where the #31bb6b color was used for many elements to one using a color scheme similar to that of Gmail.

This makes the app more usable for people with red/green color blindness

When making your changes, make the effort to use pre-existing colors in the `src/style/app.module.css` file.

**Comment by mandeepnh5** [comment]
@palisadoes  can i work on this issue?
