### ISSUE TITLE
Refactor: `src/screens/OrganizationActionItems` from Jest to Vitest

### ISSUE THREAD

**Issue by VanshikaSabharwal** [PalisadoesFoundation/talawa-admin#2557]
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**
1. Replace Jest-specific functions and mocks with Vitest equivalents
2. Ensure all tests in `src/screens/OrganizationActionItems` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by bandhan-majumder** [comment]
There are multiple test files in this folder, does this issue refer to all of them or only `OrganizationActionItems.test.tsx`

**Comment by bandhan-majumder** [comment]
Hi @palisadoes . This issue maps a directory. In the directory there are 5 test files. I have refactored 4 files and raise PRs. One file is still remaining. Can you please reopen this issue?

**Comment by bandhan-majumder** [comment]
Hi @palisadoes . I am facing an issue not related to my change in the pre-commit hook. Should I create a new issue or solve it the same PR.

Here is the preview:
![image](https://github.com/user-attachments/assets/0bffd0c8-120e-4583-bd18-0da05c7ac12a)

**Comment by bandhan-majumder** [comment]
Hi @palisadoes . With this PR, this issue can be closed as all the test files inside this directory will be successfully migrated to vitest. It took total 5 PRs to close the issue. Thank you.
