### ISSUE TITLE
Refactor: `src/screens/UserPortal/Organizations` from Jest to Vitest

### ISSUE THREAD

**Issue by VanshikaSabharwal** [PalisadoesFoundation/talawa-admin#2575]
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**
1. Replace Jest-specific functions and mocks with Vitest equivalents
2. Ensure all tests in `src/screens/UserPortal/Organizations` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by CoyoteClear340** [comment]
I'll be taking on this issue and will make sure to keep you updated on my progress. Thank you for your patience and understanding as I work through it!

**Comment by CoyoteClear340** [comment]
My end-semester exams are currently ongoing, so I may need some time to revisit the issue. I’ll do my best to resolve it soon, and if I’m unable to, I’ll let you know so it can be reassigned if needed. Thank you for your understanding!

**Comment by palisadoes** [comment]
Unassigning due to inactivity and/or no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by shivasankaran18** [comment]
Can I work on this issue..?
