### ISSUE TITLE
Refactor: `src/screens/Users`  from Jest to Vitest

### ISSUE THREAD

**Issue by VanshikaSabharwal** [PalisadoesFoundation/talawa-admin#2585]
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**
1. Replace Jest-specific functions and mocks with Vitest equivalents
2. Ensure all tests in `src/screens/Users` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by antriksh-9** [comment]
Hey @VanshikaSabharwal, I want to work on this issue. 
Pleas assign it to me.

**Comment by VanshikaSabharwal** [comment]
Hello @antriksh-9  I am not maintainer.  So, i cannot assign you. Kindly ask  @palisadoes  @varshith257 @pranshugupta54 to assign you the issue

**Comment by Shivanshu34** [comment]
Hey @VanshikaSabharwal I want to work in this

**Comment by VanshikaSabharwal** [comment]
@Shivanshu34 You can ask @palisadoes @varshith257 to assign it to you

**Comment by Cioppolo14** [comment]
If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by palisadoes** [comment]
@antriksh-9 Unassigning due to inactivity and/or no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Ramneet04** [comment]
This issue is resolved I guess I run the test and it is working fine, does it require any changes????
