### ISSUE TITLE
Refactor: `src/screens/UserPortal/Volunteer/Actions`  from Jest to Vitest

### ISSUE THREAD

**Issue by VanshikaSabharwal** [PalisadoesFoundation/talawa-admin#2586]
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**
1. Replace Jest-specific functions and mocks with Vitest equivalents
2. Ensure all tests in `src/screens/UserPortal/Volunteer/Actions` pass after migration using `npm run test:vitest`
3. Maintain the test coverage for the file as 100% after migration
4. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by MayankJha014** [comment]
Hi @VanshikaSabharwal  and @palisadoes ,

The migration for `src/screens/UserPortal/Volunteer/Actions` from Jest to Vitest is now complete. The PR addressing this issue can be found here: [#2611](https://github.com/PalisadoesFoundation/talawa-admin/pull/2611).

Please review the changes and let me know if any further updates are required.

Thank you! 😊

**Comment by MayankJha014** [comment]
Hi @VanshikaSabharwal and @palisadoes,

I have updated the PR to be submitted against the `develop-postgres branch`.You can find the updated PR here: [#2612](https://github.com/PalisadoesFoundation/talawa-admin/pull/2612).

**Comment by MayankJha014** [comment]
Its completed
