### ISSUE TITLE
GitHub Action: Check Code Coverage Bypass Statements

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2594]
**Is your feature request related to a problem? Please describe.**

1. We take our commitment to high quality code seriously. We have test code coverage verification as part of our PR approval process.
1. There is a `.github/workflows/eslint_disable_check.py` file that is run as part of our GitHub actions that checks submitted files for statements in the code base that bypass our linting verification.
1. The Talawa-Admin code coverage levels are unusually high, because many contributors have used `istanbul ignore` statements. This does not create good code quality.
    1. https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md

**Describe the solution you'd like**

1. We need a script similar to the `.github/workflows/eslint_disable_check.py` file that is run as part of our GitHub actions. 
2. The script must check submitted files for statements in the code base that bypass our code coverage verification.
3. The script must be named `.github/workflows/code_coverage_disable_check.py` and must have the CLI option to be run against one or more directories using the `--directory` like the existing lint check script 
4. It must not check unit test files
5. The script must be added to our `develop` and `develop-postgres` branches
6. The script must be written in python3:
   1. python `black`, `pydocstyle`, `pylint`, `pycodestyle` and `flake8` linting and formatting rules applied. 
   2. It must follow the Google Python Code Style guide, especially the doc string formatting
       1. https://google.github.io/styleguide/pyguide.html#383-functions-and-methods 

        ![image](https://github.com/user-attachments/assets/7ca41ec9-ee7e-4e13-8d54-1a3063180a76)

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- See above

**Additional context**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by yashpandey06** [comment]
Hey would like to work on it since I am quite familiar with action work flows .

Can you help assign me this ?

**Comment by yashpandey06** [comment]
> Hey @palisadoes  like to work on it since I am quite familiar with action work flows .
> 
> Can you help assign me this ?

**Comment by palisadoes** [comment]
Unassigning. Inactivity

**Comment by palisadoes** [comment]
> I would like to work on this issue.

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by im-vedant** [comment]
@palisadoes I have unassigned from one of the assigned issue. Can you assign me now?

**Comment by akshayw1** [comment]
Pls assign @palisadoes
