### ISSUE TITLE
Admin: Extremely Poor Docker Resource Utilization Efficiency

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2596]
**Describe the bug**

We run a demonstration instance of Talawa-Admin on a GoDaddy VPS server running Ubuntu. It has the following resources:

1. 1 core
1. 4 GB of RAM
1. 40 GB of disk

Other information:

1. The demo instance is intended to create an evaluation environment for new GtiHub contributors and users alike as they decide to use Talawa. The DB of the demo instance gets reset every day.
2. Talawa Admin runs natively on this VPS server with acceptable performance with one user. The load average is approximately 1, which is the target value for a system with only 1 core.
3. When Talawa Admin runs on the server using docker. The load average reaches 130, the swap process is the top CPU resource user. The system is so overloaded that only one ssh session at a time is achievable.

The purpose of this issue is to find ways to tune all Talawa-Admin Dockerfile and app configurations to lower its CPU and RAM utilization by at least 75% 

1. With the current Docker performance very few developers or end users will want to try Talawa themselves.
2. This has been a recurring issue with Talawa Admin. The poor performance threatens the success of our current MongoDB based MVP.

**To Reproduce**

1. Run Talawa-Admin on a system
2. See excessive resource utilization

**Expected behavior**

1. Acceptable usage information such that it can run easily on a mid-range laptop without impacting its performance

**Actual behavior**

1. Poor performance

**Screenshots**

![image](https://github.com/user-attachments/assets/a48b9d9d-8d1a-40b1-bdc4-c424c9d7809d)

**Additional details**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by adithyanotfound** [comment]
please assign

**Comment by adithyanotfound** [comment]
please assign

**Comment by adithyanotfound** [comment]
Please assign
