### ISSUE TITLE
UI Bug: Left Portion Scrolls with Right Portion on Login Page

### ISSUE THREAD

**Issue by MohitMaulekhi** [PalisadoesFoundation/talawa-admin#2617]
**Bug**
I encountered a UI issue on the login page. The left portion is not independent of the right portion. As a result, while scrolling the right portion, the left portion moves along with it, which is not the intended behavior.

**To Reproduce**

1. Navigate to the login page.
2. Scroll the right portion of the page.
3. Observe that the left portion scrolls along with the right portion.

**Expected behavior**
The left portion should remain static while scrolling the right portion.
![Screenshot 2024-12-07 190526](https://github.com/user-attachments/assets/929999c7-4120-45ea-a93f-66eb1f4ec72d)

**Actual behavior**
I have fixed this issue by making both portions independent of each other. This helps to make right portion static as in the image given below
![Screenshot 2024-12-07 214214](https://github.com/user-attachments/assets/3b2192af-0551-4816-80bc-af7ff7e08974)
![Screenshot 2024-12-07 214226](https://github.com/user-attachments/assets/c23317a7-2e30-479f-acef-849a52bb87ee)

**Additional details**
This fix ensures that the left portion remains static while scrolling the right portion, improving the overall user experience on the login page.

**Request to be Assigned**
Could you please assign this issue to me? I would like to work on it and submit a PR with the fix.

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

Closing
