### ISSUE TITLE
PR Workflow Fails with `npm run format`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2630]
**Describe the bug**

1. Our PR workflows are failing because the `npm run format` command is no longer applicable in the `pull-request.yml`
2. The error can be found here:
    - https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/12245283651/job/34158849856?pr=2629
1. The new command may be `npm run format:fix` but you'll need to verify. You'll need to restore the previous functionality in the workflow.

**To Reproduce**

1. Submit a PR
2. The formatting test fails

**Expected behavior**

1. The formatting fix passes like it used to before the `package.json` file was changed.

**Actual behavior**

- Failure

**Screenshots**

- N/A

**Additional details**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by prathmesh703** [comment]
@palisadoes can i work on this issue ?

**Comment by AQIB-NAWAB** [comment]
Hy @palisadoes , please assign this issue to me 
Thanks

**Comment by AQIB-NAWAB** [comment]
Currently there is no format command in package.json , it is format:fix 
![image](https://github.com/user-attachments/assets/67bd5543-569f-44ec-b951-66fb9d87c262)
