### ISSUE TITLE
Missing "format" Script in package.json

### ISSUE THREAD

**Issue by raggettii** [PalisadoesFoundation/talawa-admin#2634]
**Describe the bug**
The CI/CD pipeline is failing while trying to run the npm run format command. The error message indicates that the format script is missing from package.json.

**To Reproduce**

1.Trigger the CI workflow or run the command locally: **npm run format** 
2.Observe the error:

**Expected behavior**
The format script should run.

**Actual behavior**
It's giving the error.

**Screenshots**
![image](https://github.com/user-attachments/assets/8d48da5e-fe7a-44fa-9076-3c13a5914eb9)

**Additional details**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by raggettii** [comment]
Please assign this issue to me @palisadoes

**Comment by palisadoes** [comment]
Duplicate
