### ISSUE TITLE
Feature: Add Option to Visit Joined Organizations

### ISSUE THREAD

**Issue by dmelloaries** [PalisadoesFoundation/talawa-admin#2642]
**Is your feature request related to a problem? Please describe.**
Currently, there is no option to navigate to an organization's page from the "Joined Organizations" section. This makes it inconvenient for users to access the details or manage their engagement with these organizations.

**Describe the solution you'd like**
Add a button next to each organization in the "Joined Organizations" section. This button would link directly to the respective organization's page, providing quick and seamless navigation.

**Additional context**
Current UI:
![image](https://github.com/user-attachments/assets/fff87a11-0325-4481-b60f-dc6cf954a3a5)

Proposed UI After Adding Button:
![image](https://github.com/user-attachments/assets/0a586568-0e11-423f-b17d-ff3779ae7b33)
This feature would enhance usability and improve the user experience by making the "Joined Organizations" section more interactive and functional.

**Comment by dmelloaries** [comment]
@palisadoes I would like to work on this issue, can you please assign me this issue!

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

Closing
