### ISSUE TITLE
Merge latest `develop-postgres` code into the `develop` branch - 20241215

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2667]
**Is your feature request related to a problem? Please describe.**

Our `develop` branch is out of date and needs to match that of the `develop-postgres` branch.

**Describe the solution you'd like**

1. Merge the latest `develop-postgres` branch into the latest `develop` branch.
2. Fix all merge conflicts such that the new `develop-postgres` branch functionality is maintained in the `develop` branch
3. Make sure all tests are valid and comprehensively test the code base.

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by NishantSinghhhhh** [comment]
@palisadoes , can I work on this issue , I am highly motivated to do so

**Comment by NishantSinghhhhh** [comment]
![Screenshot from 2024-12-16 18-02-53](https://github.com/user-attachments/assets/5e08723d-1dcd-420e-9671-14ab974931d7)

I have worked with docker , I am keeping the incoming changes [DockerFile1 ] as it is good for develop branch
