### ISSUE TITLE
Add Code Style Guide to CONTRIBUTING.md

### ISSUE THREAD

**Issue by DangaRanga** [PalisadoesFoundation/talawa-admin#27]
**Is your feature request related to a problem? Please describe.**
There is a need for a consistent code style within Talawa-Admin to ensure that maintainable and easy to understand components are merged into the repository, similar to what's present in the Talawa and Talawa-API repositories

**Describe the solution you'd like**
This could be similar to AirBnB's react style guide found [here](https://github.com/airbnb/javascript/tree/master/react), but tailored towards using functional components and hooks.

**Describe alternatives you've considered**
Although most style guides use class components as opposed to functional components, a few other style guides that could be considered for reference are as follows:

- [Pagarme React Style Guide](https://github.com/pagarme/react-style-guide)
- [CSS Tricks Style Guide](https://css-tricks.com/react-code-style-guide/)
- [Human Made's React Style Guide](https://engineering.hmn.md/standards/style/react/)

**Approach to be followed (optional)**

**Additional context**
N/A

**Comment by yasharth291** [comment]
@DangaRanga sir this can be closed now
