### ISSUE TITLE
Enhance Clarity of User/Admin Login Toggle Buttons to Prevent Confusion

### ISSUE THREAD

**Issue by Abhay145** [PalisadoesFoundation/talawa-admin#2725]
**Is your feature request related to a problem? Please describe.**
Yes, the User/Admin toggle buttons on the login screen are not visually distinct. This leads to confusion, as users may not immediately understand which mode (User or Admin) is currently selected. When in Admin mode, the Admin button appears greyed out or less visible, while the User button is fully visible (and vice versa). Additionally, when in Admin mode, the form title only shows "Login" instead of "Admin Login," further contributing to the lack of clarity. This visual inconsistency makes it unclear which mode is active.

**Describe the solution you'd like**

Active Button Underline: Ensuring the inactive button is not appearing disabled . Add an underline effect to the active button ("Login" or "Admin Login") to differentiate it from the inactive button.
Dynamic Title Change: Change the form title from "Login" to "Admin Login" when the respective button is clicked.

**Describe alternatives you've considered**
Adding a label near the toggle buttons, such as "Mode: User" or "Mode: Admin," to explicitly indicate the current selection

**Approach to be followed (optional)**
N/A

![image](https://github.com/user-attachments/assets/8b9aabbe-feab-4ec9-9d67-3e3011e9c990)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Abhay145** [comment]
I’d like to work on this issue. Please assign it to me.

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

Closing
