### ISSUE TITLE
Refactor:  `src/components/MemberDetail/customTableCell.test.tsx` from Jest to Vitest

### ISSUE THREAD

**Issue by bandhan-majumder** [PalisadoesFoundation/talawa-admin#2746]
### Is your feature request related to a problem? Please describe.

This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

### Acceptance Criteria
1. Replace Jest-specific functions and mocks with Vitest equivalents.
2. Ensure all tests in `src/components/MemberDetail/customTableCell.test.tsx ` pass after migration using `npm run test:vitest`.
3. Maintain the test coverage for the file as 100% after migration.
4. Upload a video or photo proving that the specific file coverage is 100% in the PR description.

### Additional Context
- Refer to the merged PR for the base Vitest configuration:  
  [Base Vitest Configuration PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4ceb4607980aa3d93)
- Vitest documentation:  
  [https://vitest.dev/](https://vitest.dev/)

### Potential Internship Candidates
Please read this if you are planning to apply for a Palisadoes Foundation internship:  
- [Student Internship Programs](https://github.com/PalisadoesFoundation/talawa-admin/issues/359)

**Comment by Ramneet04** [comment]
Can I work on this issue?

**Comment by gurramkarthiknetha** [comment]
If no one is currently working on this issue, I would like to take it on. Please assign it to me.

**Comment by abbi4code** [comment]
This issue has already been resolved by this merged PR #2665.

**Comment by bandhan-majumder** [comment]
Thanks
