### ISSUE TITLE
Bug Report : `TestingLibraryElementError`: Unable to find an element with the text: May 1, 2023

### ISSUE THREAD

**Issue by bandhan-majumder** [PalisadoesFoundation/talawa-admin#2747]
**Describe the bug**
While running `npm run test`, one test fails inside `src/components/MemberDetail/customTableCell.test.tsx`. 

**To Reproduce**

1. clone the repo
2. install dependencies with `yarn install`
3. Run `npm run test`

**Expected behavior**
Should pass

**Actual behavior**
Fails

**Screenshots**
**Particular result**
![image](https://github.com/user-attachments/assets/06a6ade5-39a2-4bfb-9a90-155aa61e45fe)

**Overall result**
![image](https://github.com/user-attachments/assets/a801748f-cad7-4b7f-97f4-1e7cfed4995e)

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Dhiren-Mhatre** [comment]
@palisadoes I'd like to help fix this test failure in the customTableCell component. I have experience with React Testing Library and can debug why the date text isn't being found in the rendered component. Would you please assign this bug to me?

**Comment by palisadoes** [comment]
> @palisadoes I'd like to help fix this test failure in the customTableCell component. I have experience with React Testing Library and can debug why the date text isn't being found in the rendered component. Would you please assign this bug to me?

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by gurramkarthiknetha** [comment]
If no one is currently working on this issue, I would like to take it on. Please assign it to me.

**Comment by gurramkarthiknetha** [comment]
<img width="560" alt="image" src="https://github.com/user-attachments/assets/4eca194f-6eac-4499-adb9-279d03e118e1" />
all tests are passing

**Comment by bandhan-majumder** [comment]
It was an issue but I guess someone has already solved it in their merged pr.

**Comment by bandhan-majumder** [comment]
@palisadoes can i close the issue?

**Comment by gurramkarthiknetha** [comment]
> It was an issue but I guess someone has already solved it in their merged pr.

Okay, thank you for confirming! I'm glad to hear the issue has already been addressed in the merged PR.
