### ISSUE TITLE
Refactor: `src/setup/askForCustomPort/askForCustomPort.test.ts` from Jest to Vitest

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2748]
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**
1. Replace Jest-specific functions and mocks with Vitest equivalents
1. Rename the test file from having a `.test.*` suffix to  a `.spec.*` suffix
1. Ensure all tests in the file pass after migration using `npm run test:vitest`
1. Maintain the test coverage for the file as 100% after migration
1. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by gurramkarthiknetha** [comment]
If no one is currently working on this issue, I would like to take it on. Please assign it to me.

**Comment by hustlernik** [comment]
@palisadoes Want to take this up.

**Comment by palisadoes** [comment]
> @palisadoes Want to take this up.

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by palisadoes** [comment]
> If no one is currently working on this issue, I would like to take it on. Please assign it to me.

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by hustlernik** [comment]
@palisadoes Currently, only one issue is assigned to me.

**Comment by palisadoes** [comment]
> @palisadoes Currently, only one issue is assigned to me.

1. You are already working on two issues.
    ![image](https://github.com/user-attachments/assets/6bc6e077-6259-4b76-8e7e-ae59dd197b45)
1. You also have no submitted PRs
    ![image](https://github.com/user-attachments/assets/2691475f-8eaf-4958-9527-46e8fbea69d7)

Please give others a chance

**Comment by hustlernik** [comment]
@palisadoes Issue is not closed but PR is merged. So I am just one active issue to work on. No Problem everyone should get a chance, I agree.

![image](https://github.com/user-attachments/assets/9d607d9a-f994-489f-b08d-2da5d0465ec9)

**Comment by palisadoes** [comment]
My error. I've assigned it.

**Comment by hustlernik** [comment]
It happens, thanks.
