### ISSUE TITLE
Refactor: `src/utils/useSession.test.tsx` from Jest to Vitest

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2754]
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**
1. Replace Jest-specific functions and mocks with Vitest equivalents
1. Rename the test file from having a `.test.*` suffix to  a `.spec.*` suffix
1. Ensure all tests in the file pass after migration using `npm run test:vitest`
1. Maintain the test coverage for the file as 100% after migration
1. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by vivekbisen04** [comment]
@palisadoes  I would like to work on issue #2754 to migrate useSession.test.tsx from Jest to Vitest.

I understand this requires:
- Converting Jest tests to Vitest equivalents
- Maintaining 100% test coverage
- Following the project's migration standards

I've reviewed the base Vitest config PR and documentation.

May I be assigned to this task?

**Comment by palisadoes** [comment]
We have a policy of unassigning contributors who close PRs without getting validation from our reviewer team. This is because:

1. We start looking for people to review PRs when you submit them. 
2. We often contact them and link to the PR. If the PR is closed the whole effort is wasted.
3. The historical thread of reviewer comments is broken when the work is spread across multiple PRs. The quality of our code is affected negatively.

Please be considerate of our volunteers' limited time and our desire to improve our code base.

This policy is stated as a pinned post in all our Talawa repositories. Our YouTube videos explain why this practice is not acceptable to our Community.

In most cases you don’t have to close the PR to trigger the GitHub workflow to run again. Making a new commit and pushing it to your GitHub account will normally be sufficient.

Unfortunately, if this continues we will have to close the offending PR and unassign you from the issue.



- This can be seen here
![image](https://github.com/user-attachments/assets/6054c0d5-9b37-4742-bb09-d02d2690d7c6)
- And here too
![image](https://github.com/user-attachments/assets/24da4c29-e015-4479-b323-14fbedfdda9e)

**Comment by vivekbisen04** [comment]
Dear Peter Harrison,

I sincerely apologize for closing the pull request without validation from
the reviewer team. The branch had some issues, which I have now resolved,
but I realize this disrupted the workflow and wasted valuable effort.

Moving forward, I’ll ensure all changes comply with our community’s
policies and avoid such actions in the future. Thank you for your
understanding.

Best regards,
Vivek Bisen
