### ISSUE TITLE
Refactor: `src/utils/timezoneUtils/dateTimeMiddleware.test.ts` from Jest to Vitest

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2756]
**Is your feature request related to a problem? Please describe.**
This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor this file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**
1. Replace Jest-specific functions and mocks with Vitest equivalents
1. Rename the test file from having a `.test.*` suffix to  a `.spec.*` suffix
1. Ensure all tests in the file pass after migration using `npm run test:vitest`
1. Maintain the test coverage for the file as 100% after migration
1. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
> @palisadoes I'd love to help migrate the dateTimeMiddleware tests to Vitest! I have testing experience and will ensure all acceptance criteria are met, with 100% coverage maintained. Could you please assign this issue to me?

Our policy is to assign no more than two issues to each contributor across all repositories. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by Ramneet04** [comment]
please assign it to me!

**Comment by Ramneet04** [comment]
@palisadoes 
This is something naming convention error, all test are passing. What to do in this??

![issue3-error](https://github.com/user-attachments/assets/7c042472-552b-41ab-8ea3-15c62c194548)

**Comment by palisadoes** [comment]
1. Please fix it according to the suggestions in the error.
2. If the error is universal, then we'll need to address it as a separate issue.
