### ISSUE TITLE
Code Coverage: Create tests for LoginPage.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#276]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

The Talawa-Admin code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/screens/LoginPage/LoginPage.tsx`

- When complete, all methods, classes and/or functions in the file will need to be tested.
- These tests must be placed in a single file with the name `src/screens/LoginPage/LoginPage.test.tsx`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- #241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/tree/develop/src/screens/LoginPage/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- Create a code coverage account for your repo's preferred branch to generate the values when you do your commits for that branch to your repo.
    - _**NOTE:**_ Make sure you select the correct branch when you do the setup, or else the reporting will fail. You must also create a `CODECOV` GitHub secret for your repo as part of the process.
- The PR will show a report for the code coverage for the file you have added. You can also use that as a guide.

**Comment by ANKIT-art-spec** [comment]
Would love to contribute to it @palisadoes Can I be assigned

**Comment by yasharth291** [comment]
@ANKIT-art-spec  are u working on it?

**Comment by ANKIT-art-spec** [comment]
Yes

**Comment by ANKIT-art-spec** [comment]
How do I add the screen shot of the result?

**Comment by palisadoes** [comment]
Copy the screenshot to your clipboard and paste the result in the GitHub comments. GitHub will create a unique link to your content.

**Comment by ANKIT-art-spec** [comment]
[TestScrShot.docx](https://github.com/PalisadoesFoundation/talawa-admin/files/8356051/TestScrShot.docx)

**Comment by ANKIT-art-spec** [comment]
Is this fine?

**Comment by ANKIT-art-spec** [comment]
![Uploading image.png…]()

**Comment by ANKIT-art-spec** [comment]
This one is the final one

**Comment by palisadoes** [comment]
What I meant was:

1. Copy the screen shot to an image editor. 
2. In the editor copy the image to the image editor's clipboard.
3. Put your cursor in the GitHub comment box
4. Paste the clipboard into the comment

If you use the Microsoft clipping tool, there is an option to copy the clip into the clipboard. You can then paste the image into comment box

Please try that.

**Comment by ANKIT-art-spec** [comment]
![WhatsApp Image 2022-03-27 at 15 45 58](https://user-images.githubusercontent.com/78015603/160276869-882b59e5-19d3-4b3f-a133-8e6fc5b74528.jpeg)

**Comment by ANKIT-art-spec** [comment]
This is my contribution for GSoC 2022. Is this fine?

**Comment by palisadoes** [comment]
Please put in a PR. The mentors use merged PRs as part of their evaluations.

**Comment by ANKIT-art-spec** [comment]
In which branch do I submit my PR?

**Comment by palisadoes** [comment]
develop

**Comment by ANKIT-art-spec** [comment]
Why was my PR closed?

**Comment by palisadoes** [comment]
The reason is stated here:

- https://github.com/PalisadoesFoundation/talawa-admin/pull/323#issuecomment-1086677021

**Comment by asmitsirohi** [comment]
@palisadoes, If @ANKIT-art-spec is not working on it, can you please assign it to me. I want to work on this.

**Comment by rv602** [comment]
@palisadoes sir, I would like to work on this issue

**Comment by VaibhavJak** [comment]
Since it seems no one working on it and I am interested in solving, @palisadoes can you please assign this issue to me?

**Comment by palisadoes** [comment]
@rv602 I'm going to assign this to someone else. It's been over a month

**Comment by noman2002** [comment]
@VaibhavJak Any update ?

**Comment by noman2002** [comment]
Unassigned due ti inactivity.

**Comment by KrutikaBhatt** [comment]
Hey, can I work on this?

**Comment by adi-uchiha** [comment]
@palisadoes   Please assign me

**Comment by violetakpeh** [comment]
@palisadoes kindly assign me

**Comment by palisadoes** [comment]
@adi-uchiha I'm assigning to @violetakpeh as a newcomer.

**Comment by violetakpeh** [comment]
@palisadoes  I ran the tests that where previously done on this. 
![Screenshot 2023-03-08 at 11 29 35](https://user-images.githubusercontent.com/110561563/223689507-14a91bbe-78dc-488d-97cf-86c5d6e9b7a5.png)

above is what I got. All the tests passed.
Can you please throw more light on what I am expected to do

**Comment by aashimawadhwa** [comment]
Above the passed test can you see the console loge errors, you've to fix them @violetakpeh

**Comment by violetakpeh** [comment]
@palisadoes I have fixed the errors
![Screenshot 2023-03-08 at 17 32 24](https://user-images.githubusercontent.com/110561563/223772849-6efc877a-9b94-4dba-8d32-013fb90f7f2a.png)
Is it ok, or is there something else I should do?

**Comment by palisadoes** [comment]
If it's fixed, then submit a PR. There is no need for requesting to do so.

**Comment by violetakpeh** [comment]
okay

**Comment by violetakpeh** [comment]
@palisadoes @aashimawadhwa I am trying to commit but I am stuck on this part
![Screenshot 2023-03-08 at 17 52 35](https://user-images.githubusercontent.com/110561563/223777708-285d9e0d-984c-43c4-aed4-f5c014ea5dfb.png)

**Comment by aashimawadhwa** [comment]
You can use cntrl q to exit this or can simply open a new terminal

**Comment by violetakpeh** [comment]
@aashimawadhwa  I tried both, but it did not work

**Comment by violetakpeh** [comment]
@palisadoes I am trying to push to the repository, but it's like I don't have access
![Screenshot 2023-03-10 at 21 15 12](https://user-images.githubusercontent.com/110561563/224419606-064e189b-6ec5-4517-8234-d5cb23a071f1.png)

**Comment by rv602** [comment]
@violetakpeh you can't push to the repository directly.
You have to fork the repository, make a new branch and submit that as a PR.

**Comment by violetakpeh** [comment]
@rv602  thank you

**Comment by violetakpeh** [comment]
@noman2002 @xoldyckk  please help to issue reviewers for my PR

**Comment by violetakpeh** [comment]
@palisadoes I just requested another PR but its still showing the wrong issue number. I filled the write issue number in the PR template so I don't know why its using a wrong issue number. Please help
![Screenshot 2023-03-11 at 00 41 21](https://user-images.githubusercontent.com/110561563/224448874-4249c23f-7ad1-43ad-b678-81705b110fb1.png)

**Comment by palisadoes** [comment]
You should be able to edit the comment by clicking on the `...` icon in the light blue menu bar

**Comment by palisadoes** [comment]
> @palisadoes I just requested another PR but its still showing the wrong issue number. I filled the write issue number in the PR template so I don't know why its using a wrong issue number. Please help ![Screenshot 2023-03-11 at 00 41 21](https://user-images.githubusercontent.com/110561563/224448874-4249c23f-7ad1-43ad-b678-81705b110fb1.png)

You should be able to edit the comment by clicking on the `...` icon in the light blue menu bar

**Comment by violetakpeh** [comment]
@palisadoes The issue number in the comment is correct, its just the heading that has the wrong issue number

**Comment by palisadoes** [comment]
That's the pull request number. It matches the end part of the URL for the page.

**Comment by violetakpeh** [comment]
> That's the pull request number. It matches the end part of the URL for the page.

So does that mean that he pull request is ok?

**Comment by violetakpeh** [comment]
@xoldyckk I cloned the repository again and used yarn instead of npm. After I run the test on the Login page, there was no issue on the console. So I dont know what exactly I am to work on. please help
![Screenshot 2023-03-13 at 16 43 59](https://user-images.githubusercontent.com/110561563/224756520-0c60592d-5e66-4401-bb2f-5fefc1c85987.png)
![Screenshot 2023-03-13 at 16 50 21](https://user-images.githubusercontent.com/110561563/224756579-b626d965-5733-4e51-beae-0f419517b244.png)

**Comment by violetakpeh** [comment]
@aashimawadhwa  I had to start working on this issue from the beginning because I was using npm instead yarn. After I finished installing yarn, I cant see any issue with the loginPage test. Please I need help
![Screenshot 2023-03-13 at 16 50 21](https://user-images.githubusercontent.com/110561563/224966484-8e3490f3-1690-4ce7-b9d8-457cb5e723dd.png)

**Comment by violetakpeh** [comment]
> Letme check I'll get back to you in sometime. In college right now @violetakpeh

thank you

**Comment by adi-uchiha** [comment]
How much coverage are you able to achieve now ?

**Comment by violetakpeh** [comment]
> How much coverage are you able to achieve now ?

the work already has 100% coverage. 
![Screenshot 2023-03-13 at 16 43 59](https://user-images.githubusercontent.com/110561563/224991449-2fedfb6a-334b-41e6-8774-2b52d7512151.png)

**Comment by violetakpeh** [comment]
> > How much coverage are you able to achieve now ?
> 
> the work already has 100% coverage. ![Screenshot 2023-03-13 at 16 43 59](https://user-images.githubusercontent.com/110561563/224991449-2fedfb6a-334b-41e6-8774-2b52d7512151.png)

I have not yet work on it. That's the problem I'm having, I don'
t know what I am suppose to do because everything looks ok

**Comment by palisadoes** [comment]
You need to open a pull request for this issue. There should be many examples of how to do this on YouTube.

**Comment by violetakpeh** [comment]
@palisadoes how do I close the issue?
