### ISSUE TITLE
Bug Report : Language Button is Not Responsive Across Screen Sizes

### ISSUE THREAD

**Issue by harshal050** [PalisadoesFoundation/talawa-admin#2772]
**Describe the bug**
The language button maintains a fixed size regardless of the screen size or resolution, causing a lack of responsiveness. This results in inconsistent user experiences, especially on smaller or larger devices.

**To Reproduce**

1. Open the website http://localhost:4321/ In  **REGISTER**or application on any device.
2. Resize the browser window or switch to a device with a smaller/larger screen.
3. Observe the language button's size remains unchanged.
4. Compare its appearance and alignment with other responsive elements on the screen.

**Expected behavior**
The language button should adjust its size dynamically based on the screen size or viewport, ensuring consistency with other responsive elements.

**Actual behavior**
The language button should adjust its size dynamically based on the screen size or viewport, ensuring consistency with other responsive elements.

**Screenshots**

![Screenshot 2024-12-24 182317](https://github.com/user-attachments/assets/953ded6c-6851-4c26-b259-1ed8701916cd)

**video**

Uploading Recording 2024-12-24 182247.mp4…

**Comment by khushipatil1523** [comment]
can i work on this issue

**Comment by srijantrpth** [comment]
Hi @harshal050 , Kindly assign me this issue so that I can start working on this issue. Thanks

**Comment by harshal050** [comment]
@palisadoes I will like to start contributing in this issue please assign me this issue

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

Closing
