### ISSUE TITLE
Refactor `src/components/AddOn/*` from Jest to Vitest

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2788]
**Is your feature request related to a problem? Please describe.**

This files in this directory and all its subdirectories are currently tested using Jest. As part of our migration to Vitest, we need to refactor all these files' test cases to align with Vitest's syntax and features.

Files:

1. Refactor `src/components/AddOn/core/AddOnEntry/AddOnEntry.test.tsx` from Jest to Vitest
2. Refactor `src/components/AddOn/core/AddOnRegister/AddOnRegister.test.tsx` from Jest to Vitest
3. Refactor `src/components/AddOn/core/AddOnStore/AddOnStore.test.tsx` from Jest to Vitest
4. Refactor `src/components/AddOn/support/components/Action/Action.test.tsx` from Jest to Vitest
5. Refactor `src/components/AddOn/support/components/MainContent/MainContent.test.tsx` from Jest to Vitest

**Acceptance Criteria**

For each `*.test.ts` and `*.test.tsx` file found under the parent:

1. Replace Jest-specific functions and mocks with Vitest equivalents
1. Rename the test file from having a `.test.*` suffix to  a `.spec.*` suffix
1. Ensure all tests in the file pass after migration using `npm run test:vitest`
1. Maintain the test coverage for the file as 100% after migration
1. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AceHunterr** [comment]
@palisadoes can I work on this issue?

**Comment by AceHunterr** [comment]
@palisadoes there already exists a src/components/AddOn/core/AddOnEntry/AddOnEntry.spec.tsx and it has tests  written in jest 
 
so should I just modify `src/components/AddOn/core/AddOnEntry/AddOnEntry.spec.tsx` 
and leave `src/components/AddOn/core/AddOnEntry/AddOnEntry.test.tsx` for good?


![image](https://github.com/user-attachments/assets/0c7ebb4b-9a29-433a-83f5-74273bf62f4e)

**Comment by palisadoes** [comment]
1. Please remove `src/components/AddOn/core/AddOnEntry/AddOnEntry.test.tsx`
2. We are removing jest completely

**Comment by AceHunterr** [comment]
can I work on other issues now?

**Comment by palisadoes** [comment]
Yes
