### ISSUE TITLE
Code Coverage: Create tests for routesReducer.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#279]
The Talawa-Admin code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/state/reducers/routesReducer.ts`

- When complete, all methods, classes and/or functions in the file will need to be tested.
- These tests must be placed in a single file with the name `src/state/reducers/routesReducer.test.ts`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- #241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/tree/develop/src/state/reducers/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- Create a code coverage account for your repo's preferred branch to generate the values when you do your commits for that branch to your repo.
    - _**NOTE:**_ Make sure you select the correct branch when you do the setup, or else the reporting will fail. You must also create a `CODECOV` GitHub secret for your repo as part of the process.
- The PR will show a report for the code coverage for the file you have added. You can also use that as a guide.

**Comment by SiddheshKukade** [comment]
I want to work on this please assign this to me :+1:

**Comment by yasharth291** [comment]
continue @SiddheshKukade

**Comment by SiddheshKukade** [comment]
Ok :+1:

**Comment by SiddheshKukade** [comment]
@yasharth291 sir I have  a doubt:
     I caanot find the actions for routesReducer

## In the ` src/state/action-creators/index.js ` I can see the follwing code :
```javascript 
export const updateInstalled = (plugin: any) => {
  return (dispatch: any) => {
    dispatch({
      type: 'UPDATE_INSTALLED',
      payload: plugin,
    });
  };
};

export const installPlugin = (plugin: any) => {
  return (dispatch: any) => {
    dispatch({
      type: 'INSTALL_PLUGIN',
      payload: plugin,
    });
  };
};

export const removePlugin = (plugin: any) => {
  return (dispatch: any) => {
    dispatch({
      type: 'REMOVE_PLUGIN',
      payload: plugin,
    });
  };
};

export const updatePluginLinks = (plugins: any) => {
  return (dispatch: any) => {
    dispatch({
      type: 'UPDATE_P_TARGETS',
      payload: plugins,
    });
  };
};

```
### I think these are plugin reducer actions can you please tell me where are the actions of the route reducer ?

**Comment by SiddheshKukade** [comment]
@yasharth291  @palisadoes  @DangaRanga I am just asking if there is any action file for routesReducer so that I can use them for writing tests on the reducer

**Comment by palisadoes** [comment]
@yasharth291  @DangaRanga please respond.

**Comment by yasharth291** [comment]
@SiddheshKukade I think there is no action file for the same
