### ISSUE TITLE
Refactor `src/components/OrgSettings/ActionItemCategories/*` from Jest to Vitest

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2795]
**Is your feature request related to a problem? Please describe.**

This files in this directory and all its subdirectories are currently tested using Jest. As part of our migration to Vitest, we need to refactor all these files' test cases to align with Vitest's syntax and features.

Files:
1. Refactor `src/components/OrgSettings/ActionItemCategories/CategoryModal.test.tsx` from Jest to Vitest
1. Refactor `src/components/OrgSettings/ActionItemCategories/OrgActionItemCategories.test.tsx` from Jest to Vitest
1. Refactor `src/components/OrgSettings/AgendaItemCategories/AgendaCategoryCreateModal.test.tsx` from Jest to Vitest
1. Refactor `src/components/OrgSettings/AgendaItemCategories/AgendaCategoryUpdateModal.test.tsx` from Jest to Vitest
1. Refactor `src/components/OrgSettings/AgendaItemCategories/OrganizationAgendaCategory.test.tsx` from Jest to Vitest

**Acceptance Criteria**

For each `*.test.ts` and `*.test.tsx` file found under the parent:

1. Replace Jest-specific functions and mocks with Vitest equivalents
1. Rename the test file from having a `.test.*` suffix to  a `.spec.*` suffix
1. Ensure all tests in the file pass after migration using `npm run test:vitest`
1. Maintain the test coverage for the file as 100% after migration
1. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by abbi4code** [comment]
can i work on this issue ? @palisadoes

**Comment by abbi4code** [comment]
In the `` src/components/Orgsettings/General`` file, there are three more tests that can be refactored to Vitest. Should they also be included in the PR?

**Comment by palisadoes** [comment]
Yes

**Comment by shivasankaran18** [comment]
can I work on this issue..? @palisadoes

**Comment by abbi4code** [comment]
I have already started working on this and will raise a PR soon.
