### ISSUE TITLE
Bug Report : Bug Report: Footer Icons Overflow on Mobile

### ISSUE THREAD

**Issue by harshal050** [PalisadoesFoundation/talawa-admin#2800]
**Describe the bug**
Icons for different platforms in the footer section are overflowing beyond the mobile screen boundaries, leading to layout issues.

**To Reproduce**

Open the website http://localhost:4321/ In REGISTERor application on any device.
Resize the browser window or switch to a device with a smaller/larger screen.
Observe the language button's size remains unchanged.
Compare its appearance and alignment with other responsive elements on the screen.

**Expected behavior**
The icons should remain within the bounds of the mobile screen, properly aligned and responsive to screen size.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**video**

https://github.com/user-attachments/assets/a0ae757d-a859-423e-adfe-e943c32707d7

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens.
4. The creation of additional or updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Cosmetic changes that require only a few lines of code, or relate to screen sizes unlikely to be used are not acceptable under this policy.

Closing
