### ISSUE TITLE
Feature Request: Implement Multi-Language Support with Next.js i18n

### ISSUE THREAD

**Issue by harshal050** [PalisadoesFoundation/talawa-admin#2801]
**Is your feature request related to a problem? Please describe.**
The current language switching functionality is not working. Users are unable to view the application in their preferred language, leading to a poor user experience and limited accessibility.

**Describe the solution you'd like**
I would like the language switching feature to be implemented using the next-i18next library. This will enable:

Seamless internationalization with support for multiple languages.
Dynamic translations for both client-side and server-side rendered pages.
Easy management of language resources through JSON files.

**Describe alternatives you've considered**
Manually implementing a custom language switching system using React Context.
Using a third-party library like react-i18next, but it lacks the deep integration with Next.js features.

**Approach to be followed (optional)**
Install and configure next-i18next in the project.
Set up a central i18n.js configuration file for languages and namespaces.
Create JSON translation files for each supported language (e.g., en.json, fr.json).
Integrate language detection and switching logic in the UI.
Ensure that translated content works seamlessly with both static and dynamic routes.

![Screenshot 2024-12-24 235249](https://github.com/user-attachments/assets/9a2041e9-4cd6-418d-bba6-534e55fad2ed)

**Additional context**
Users have reported dissatisfaction with the current inability to switch languages.
Here’s a link to the Next.js i18n documentation for reference.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
1. We already have a functioning multilingual capability. 
2. It fails where the functionality isn't implemented for certain text. If you have found a specific issue, then open an issue for that. We will not rewrite our existing subsystem. 
3. Closing

**Comment by harshal050** [comment]
@palisadoes you are big issue...

**Comment by palisadoes** [comment]
In what sense?
