### ISSUE TITLE
Refactor `src/components/UserPortal/*` from Jest to Vitest

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2803]
**Is your feature request related to a problem? Please describe.**

This files in this directory and all its subdirectories are currently tested using Jest. As part of our migration to Vitest, we need to refactor all these files' test cases to align with Vitest's syntax and features.

Files:

1. Refactor `src/components/UserPortal/ChatRoom/ChatRoom.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/CommentCard/CommentCard.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/ContactCard/ContactCard.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/CreateDirectChat/CreateDirectChat.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/CreateGroupChat/CreateGroupChat.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/DonationCard/DonationCard.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/EventCard/EventCard.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/OrganizationCard/OrganizationCard.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/OrganizationNavbar/OrganizationNavbar.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/OrganizationSidebar/OrganizationSidebar.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/PeopleCard/PeopleCard.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/PostCard/PostCard.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/PromotedPost/PromotedPost.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/Register/Register.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/SecuredRouteForUser/SecuredRouteForUser.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/StartPostModal/StartPostModal.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/UserNavbar/UserNavbar.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/UserProfile/EventsAttendedByUser.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/UserProfile/UserAddressFields.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/UserSidebar/UserSidebar.test.tsx` from Jest to Vitest
1. Refactor `src/components/UserPortal/UserSidebarOrg/UserSidebarOrg.test.tsx` from Jest to Vitest

**Acceptance Criteria**

For each `*.test.ts` and `*.test.tsx` file found under the parent:

1. Replace Jest-specific functions and mocks with Vitest equivalents
1. Rename the test file from having a `.test.*` suffix to  a `.spec.*` suffix
1. Ensure all tests in the file pass after migration using `npm run test:vitest`
1. Maintain the test coverage for the file as 100% after migration
1. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by abbi4code** [comment]
can i work on this issue ? @palisadoes

**Comment by abbi4code** [comment]
Since there are a significant number of test files, I would like to kindly ask for your preference regarding the migration process. Would it be preferable for me to handle this in a single pull request (PR) that includes all the files, or should I submit individual PRs for each test file?

**Comment by palisadoes** [comment]
Just do one. As they are components the number of changed lines  will be few

**Comment by abbi4code** [comment]
Could you please assign the issue to me so I can proceed?
