### ISSUE TITLE
Refactor `src/components/OrganizationDashCards/CardItem.test.tsx` from Jest to Vitest

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2806]
**Is your feature request related to a problem? Please describe.**

This files in this directory and all its subdirectories are currently tested using Jest. As part of our migration to Vitest, we need to refactor all these files' test cases to align with Vitest's syntax and features.

Files:
1. Refactor `src/components/OrganizationDashCards/CardItem.test.tsx` from Jest to Vitest
1. Refactor `src/components/OrganizationDashCards/DashboardCard.test.tsx` from Jest to Vitest

**Acceptance Criteria**

For each `*.test.ts` and `*.test.tsx` file found under the root:

1. Replace Jest-specific functions and mocks with Vitest equivalents
1. Rename the test file from having a `.test.*` suffix to  a `.spec.*` suffix
1. Ensure all tests in the file pass after migration using `npm run test:vitest`
1. Maintain the test coverage for the file as 100% after migration
1. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

- Refer to the merged PR for the base Vitest configuration:
https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
- Vitest documentation:
https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by amaan-aly246** [comment]
@palisadoes Please assign this to me. 
Since we have to shift jest code to vitest code, is vitest dependency installed or we have to do it ourself ? and if not installed should I  install it as dev-dependency ?
Thanks.

**Comment by palisadoes** [comment]
All the required packages are already in `package.json`

**Comment by amaan-aly246** [comment]
@palisadoes  I have migrated all the tests to Vitest. Before raising the PR, I wanted to confirm something: some components are using CSS from their corresponding CSS files. Would you prefer me to merge the CSS from those files into the global `app.module.css` file (considering there are refactoring issues related to this, one of which I resolved earlier) and then raise the PR, or should I simply raise the PR without merging the CSS?
Thanks
![Screenshot 2024-12-25 235223](https://github.com/user-attachments/assets/6ea43093-7f29-4b90-ac08-1362c7642ebd)

**Comment by palisadoes** [comment]
Yes, please take the time to merge the CSS files.

**Comment by palisadoes** [comment]
With this issue we are migrating from the previous green based color scheme where the #31bb6b color was used for many elements to one using a color scheme similar to that of Gmail.

This makes the app more usable for people with red/green color blindness

When making your changes, make the effort to use pre-existing colors in the `src/style/app.module.css` file.
