### ISSUE TITLE
Refactor `src/components/UpdateSession/UpdateSession.test.tsx` from Jest to Vitest

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2823]
**Is your feature request related to a problem? Please describe.**
A clear and concise descr**Is your feature request related to a problem? Please describe.**

This file is currently tested using Jest. As part of our migration to Vitest, we need to refactor the file's test cases to align with Vitest's syntax and features.

**Acceptance Criteria**

1. Replace Jest-specific functions and mocks with Vitest equivalents
1. Rename the test file from having a `.test.*` suffix to  a `.spec.*` suffix
1. Ensure all tests in the file pass after migration using `npm run test:vitest`
1. Maintain the test coverage for the file as 100% after migration
1. Upload a video or photo for this specific file coverage is 100% in the PR description

**Additional context**

1. Refer to the merged PR for the base Vitest configuration:
    1. https://github.com/PalisadoesFoundation/talawa-admin/pull/2457/files#diff-9a5a35cf8d7f02b2bba90905714b762560579c4789e9eb4cebb4607980aa3d93
1. Vitest reference site:
    1. https://vitest.dev/

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359
iption of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by abbi4code** [comment]
can i work on this issue ? @palisadoes
