### ISSUE TITLE
Talawa-admin installer need to be improved!

### ISSUE THREAD

**Issue by asmitsirohi** [PalisadoesFoundation/talawa-admin#286]
**Describe the bug**
The current talawa-admin installer has some bugs that need to be resolved.

**Expected behavior**
When the talawa-admin installer runs, it should prompt for the talawa-API URL, and then after verifying the URL the project is set up.

**Actual behavior**
Currently, it is prompting for ACCESS TOKEN and REFRESH TOKEN as well, which is of no use here.

**Screenshots**
![image](https://user-images.githubusercontent.com/63240102/157076907-ab4a287e-7ca5-4794-bdaa-1f02b49d29ff.png)

**Additional details**
Please assign it to me.

**Comment by palisadoes** [comment]
@asmitsirohi You now have three issues assigned to you. We will soon be enforcing one issue per person per repo. Please close your other issues before asking for new assignments.
