### ISSUE TITLE
Refactor CSS in `src/screens/OrganizationActionItems/ItemViewModal.tsx`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2886]
# Refactor CSS in this file

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

This file contains embedded CSS references that should be completely moved to:
- `src/style/app.module.css`

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is for this file to use this new design pattern. This means that:
1. All embedded CSS in this file must be merged into the global CSS file using pre-existing CSS.
1. All embedded CSS in this file must be removed

**Comment by pranavnathe** [comment]
Please assign this issue to me.

**Comment by pranavnathe** [comment]
Hi @palisadoes ,
The file is already referring to src/style/app.module.css. Am I missing something here? I also noticed a minor issue with the avatar alignment.
![Screenshot 2024-12-27 at 7 27 26 PM](https://github.com/user-attachments/assets/985dfb18-e7e1-447c-923e-9e54e8070d34)

**Comment by palisadoes** [comment]
Please take the time to fix it and submit a PR
