### ISSUE TITLE
Refactor CSS in `src/components/RecurrenceOptions/CustomRecurrence.test.tsx`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2898]
# Refactor CSS in this file

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

This file contains embedded CSS references that should be completely moved to:
- `src/style/app.module.css`

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is for this file to use this new design pattern. This means that:
1. All embedded CSS in this file must be merged into the global CSS file using pre-existing CSS.
1. All embedded CSS in this file must be removed

**Comment by hustlernik** [comment]
@palisadoes want to take this up.
