### ISSUE TITLE
Bug Report : Can't Scroll in the register page of talawa-admin home page 

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-admin#290]
**Describe the bug**
In the register page you can see that the form is not scrollable for example is some one is zoomed in on that page lets say 125% he /she should be able to scroll below to click on the register button

**To Reproduce**

Are you working on this ? 
yes

1. git clone https://github.com/PalisadoesFoundation/talawa-admin.git
2. npm install
3. npm run start
4. go to register page

**Expected behavior**
 In the register page you can see that the form is should be scrollable for example is some one is zoomed in on that page lets say 125% he /she should be able to scroll below to click on the register button 

**Actual behavior**
User cant scroll on form if he/she is zoomed in 
**Screenshots**
![image](https://user-images.githubusercontent.com/65951872/158760989-1a0ded5a-9069-4652-a1a3-22f3845c7367.png)
## now zoomed in 125% still no scroll bar and thus can't fill next inputs and also cannot click the register button
![image](https://user-images.githubusercontent.com/65951872/158761343-97327c7b-afed-40cc-8a27-63cb2dc0050e.png)

**Comment by yasharth291** [comment]
@SiddheshKukade  carry out the work

**Comment by SiddheshKukade** [comment]
#### Sir, I have created a Pull request #291  
#### Please let me know if something is wrong or If  I can improve onto something
