### ISSUE TITLE
Refactor CSS in `src/components/CheckIn/tagTemplate.ts`

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2906]
# Refactor CSS in this file

To improve the UI/UX of Talawa-Admin we have been working on:
1. making the application more suitable to color blind users
2. streamlining all CSS into a single global file

This file contains embedded CSS references that should be completely moved to:
- `src/style/app.module.css`

## Additional information:
1. The foundational work for this was completed in this PR:
    - https://github.com/PalisadoesFoundation/talawa-admin/pull/2466
2. The desired single CSS file is:
    - `src/style/app.module.css`

## The challenge:
The goal is for this file to use this new design pattern. This means that:
1. All embedded CSS in this file must be merged into the global CSS file using pre-existing CSS.
1. All embedded CSS in this file must be removed

**Comment by IITI-tushar** [comment]
@palisadoes, please assign.. I will submit a PR soon...

**Comment by abhassen44** [comment]
@palisadoes,you mean all .modules.css + tailwind + inline  css we have to combine and place them in app.module.css
or only tailwind  + inline css we have place them in app.module.css

**Comment by palisadoes** [comment]
1. Please move all the inline CSS to app.module.css 
2. We will need to do this so that we can easily implement
    1. light/dark mode
    2. custom css for the end user

**Comment by IITI-tushar** [comment]
@abhassen44 This issue is assigned to me. If you want to work on an issue please try to find another and get assigned to it...

**Comment by abhassen44** [comment]
@IITI-tushar ,i am just asking to understand the requirement and to understand the codebase
