### ISSUE TITLE
Bug: Google ReCAPTCHA not refreshing after submitting Login/SignUp Form

### ISSUE THREAD

**Issue by PratapRathi** [PalisadoesFoundation/talawa-admin#2928]
**Describe the bug**
Google ReCAPTCHA is not refreshing after submitting Login/SignUp Form with wrong credentials, so to login again we need to reload the page to reset the ReCAPTCHA.

**To Reproduce**
1. Open the Talawa-Admin Homepage 
2. Enter wrong credentials in Login Form, click submit

1. Open the Talawa-Admin Homepage 
2. Switch to SignUp Form
3. Enter wrong credentials in SignUp Form, click submit

**Expected behavior**
After submitting Login/SignUp form with wrong credentials, Google ReCAPTCHA must reset so the person can login again with correct credentials without reloading the page

**Actual behavior**
Google ReCAPTCHA still remain checked after submitting Login/SignUp form with wrong credentials and gives error on submitting form 2nd time.

**Screen-Recording**

https://github.com/user-attachments/assets/9dc3b8a3-697c-4673-9a05-db33a1b6f2cb

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by PratapRathi** [comment]
@palisadoes please assign this issue to me.

**Comment by palisadoes** [comment]
Is ReCAPTCHA fixed in the app now?

**Comment by PratapRathi** [comment]
Yes I fixed it.

**Comment by palisadoes** [comment]
Please add tests to make sure it doesn't break again

**Comment by PratapRathi** [comment]
I fixed it and Added specific test for this and Migrated LoginPage.test.tsx to Vitest.
