### ISSUE TITLE
Bug Report: Flickering screen when port localhost:4000/graphql is not found(copied from talawa-api)

### ISSUE THREAD

**Issue by Aad1tya27** [PalisadoesFoundation/talawa-admin#2936]
Describe the bug
When starting the talawa-admin application, the screen begins to flicker if the GraphQL API endpoint (localhost:4000/graphql) is not reachable.

To Reproduce

Start talawa-api using docker
Start talawa-admin
The screen will start flickering if localhost:4000/graphql is not found
Logs shows the error.
 Error logs: - Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:4000/graphql/. (Reason: CORS request did not succeed). Status code: (null)
Expected behavior

The screen should not flicker when the API endpoint is unreachable.
Instead, a clear error message should be displayed to the user indicating that the GraphQL endpoint is down or inaccessible.
Actual behavior
-The screen flickers continuously when the API endpoint (localhost:4000/graphql) is not found.
-Logs indicate a CORS request failure with no clear status code.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Aad1tya27** [comment]
@palisadoes The changed in this issue have to be done in the talawa-admin repo instead of talawa-api so I raised it here.
I'll submit a pr soon.

**Comment by Aad1tya27** [comment]
![image](https://github.com/user-attachments/assets/0914dc31-b1f8-4062-8836-83762bbbfdeb)
I've made a one line change in a different file and file ```src/components/CheckIn/tagTemplate.ts``` is giving error on running npm run typecheck. I think the name attribute is not required so I'll remove it.

**Comment by hustlernik** [comment]
@Aad1tya27 Take a pull from `develop-postgres` branch and npm i as new package was introduced. This will remove type error.
