### ISSUE TITLE
Issue in Admin and User Login buttons when in focus at Login Page

### ISSUE THREAD

**Issue by aadhil2k4** [PalisadoesFoundation/talawa-admin#2977]
**Describe the bug**
The Admin and User buttons in the Login page have a font color problem(same font as background) when in focus. This causes the makes the button contents invisible.

**To Reproduce**

1. Go to Login Page
2. Click the User/Admin button 

**Expected behavior**
The font color of the button in focus should not be same as the background colour of the button.

**Actual behavior**
The font colour of the button that is clicked is changed to that of its background.

**Screenshots**

https://github.com/user-attachments/assets/80959189-6089-47cc-be16-1d65a63575eb

**Comment by mandeepnh5** [comment]
can i work on this issue?

**Comment by GovindSinghh** [comment]
@aadhil2k4 
Assign this issue to me

**Comment by palisadoes** [comment]
@aadhil2k4 Do you want to work on this?

**Comment by CHIRANTH-24** [comment]
Im sorry @palisadoes I should have asked for assignement

**Comment by CHIRANTH-24** [comment]
@palisadoes Can i work on it?

**Comment by ARYPROGRAMMER** [comment]
@palisadoes  i have finished working on this can i submit the PR for the same.

Please look into the video and assign me for the same.

My working example:

https://github.com/user-attachments/assets/e0615e83-8718-49f3-89e0-b2d4194463e6

**Comment by monk0707** [comment]
@palisadoes Can I work on this issue?
