### ISSUE TITLE
Using Global CSS root variables for better consistency

### ISSUE THREAD

**Issue by AceHunterr** [PalisadoesFoundation/talawa-admin#2983]
**Is your feature request related to a problem? Please describe.**
The hardcoded values in the tsx files for the styles such as those present in the 'sx' prop can be replaced with global css root variables. 

**Describe the solution you'd like**
Simply import the styles from the global CSS and therefore use the global root variables.

For example :

For this style
![original](https://github.com/user-attachments/assets/62f0820b-ff55-441c-9b6e-be4daaf4dc82)

We have the output:
![2nd](https://github.com/user-attachments/assets/1e6457fb-629b-4da4-86c5-43b8be231a0b)

But by simply replacing the hardcoded backgroundcolor value with global variable root variable we can ensure much higher consistency for the CSS:
![after change](https://github.com/user-attachments/assets/654b9236-565d-42aa-a08a-e9e68a1a99ad)

We get the same result:
![4th](https://github.com/user-attachments/assets/636c67dd-a4e5-4d25-89f4-500da98b1fbc)

**Approach to be followed (optional)**
1. Visit all the .tsx files in the `src` directory.
2. Ensure they have styles imported from global css something like this: `import styles from '../../style/app.module.css'; `
3. Replace all the possible hard coded values with global css root variables.
4. Run the server before making the changes and after the changes making sure CSS do not gets disrupted for any component.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AceHunterr** [comment]
May I work on this issue?

**Comment by monk0707** [comment]
@palisadoes Can I work on this issue?

**Comment by sandeepshegane5** [comment]
can i work on this issue?

**Comment by sandeepshegane5** [comment]
@palisadoes May i work on this issue?
