### ISSUE TITLE
Streamline `src/style/app.module.css` CSS file

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#2985]
**Is your feature request related to a problem? Please describe.**

1. We are migrating to a centralized CSS file with a single stylesheet file `src/style/app.module.css `
2. The aim is to eventually allow us to implement:
    1. light/dark mode
    2. a user defined custom CSS file that overrides `src/style/app.module.css `

The current approach uses repetitive hard coded colors that could be better defined as a single variable. This will make these tasks easier.

**Describe the solution you'd like**

- Replace the hard coded color values as variables whose names match their use in the various elements.
- This does not mean that the color must be defined only once if it is suitable in more than one design element area. This is expected to be a rare possibility. **As much as possible, define the color once.**

**Describe alternatives you've considered**
 
- N/A

**Approach to be followed (optional)**

- See above

**Additional context**

List of colors

- 000000
- 0056b3
- 08780b
- 1e293b
- 21d015
- 23864c
- 286fe0
- 39a440
- 555555
- 5e5e5e
- 5f7e91
- 707070
- 737373
- 7c9beb
- 808080
- a8c7fa
- afffe8
- dddddd
- e0e0e0
- e2e8f0
- e8e5e5
- eaebef
- eff1f7
- f1f3f6
- f6f8fc
- f7f7f7
- f8d6dc
- febc59
- ff4d4f
- ffffff

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by abhassen44** [comment]
can i work on this issue

**Comment by mandeepnh5** [comment]
Can I work on this issue?

**Comment by abhassen44** [comment]
@palisadoes , I only make variable of colors that are used but not all according to list,
 is this ok
 
![Screenshot 2024-12-28 161417](https://github.com/user-attachments/assets/557729bd-a4e8-455b-a8dc-8a9e539fa830)

**Comment by palisadoes** [comment]
Yes
