### ISSUE TITLE
The husky pre-commit script is failing on committing changes.

### ISSUE THREAD

**Issue by Suyash878** [PalisadoesFoundation/talawa-admin#2987]
**Describe the bug**
Whenever we try to commit our staged changes, the husky pre-commit fails at:
> talawa-admin@3.0.0 typecheck
> tsc --project tsconfig.json --noEmit

When executed, This command fails and we see a number of type-check errors on the terminal. 

**To Reproduce**

1. Make some changes in any file.
2. Stage those changes.
3. Commit those changes.
4. See the script failing at `tsc --project tsconfig.json --noEmit`

**Expected behavior**
The changes should be committed and no such error must be encountered.

**Actual behavior**
The script fails at `talawa-admin@3.0.0 typecheck` which leads to changes failing to commit.

**Screenshots**
![image](https://github.com/user-attachments/assets/335a8cc4-297c-4fdd-b669-2a59ef65e7e0)

**Additional details**
None.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by amitb0ra** [comment]
yeah i got that too.

can you assign this to me? 
@palisadoes

**Comment by Suyash878** [comment]
I have figured in the files 'VolunteerDeleteModal.spec.tsx' the issue was:
- Here actually waitFor should be imported from the library `@testing-library/react` initally
![image](https://github.com/user-attachments/assets/1ef5e17d-7a11-44c3-84c1-aefe28f3529d)
- When instead it should've been imported from `@testing-library/dom` and render would still be imported from `@testing-library/react`
![image](https://github.com/user-attachments/assets/c1afce3e-44de-452f-beb9-613602183ae6)

I made these changes and re-ran the command, I did not come across any issues, However we will be required to install an additional, `@testing-library/dom` to solve this issue.

I have the changes made and I would like to work on this.

**Comment by Suyash878** [comment]
I would like to work on this.

**Comment by PratapRathi** [comment]
If you encounter with such issue, just run `npm install` it will refresh your node_modules and such error will be disappear.

**Comment by Suyash878** [comment]
I tried that too, but it did not work.
