### ISSUE TITLE
Main Container Fails to Expand on Sidebar Collapse

### ISSUE THREAD

**Issue by CHIRANTH-24** [PalisadoesFoundation/talawa-admin#2994]
**Describe the bug**
The main container of the chat does not expand when the sidebar is collapsed, leaving empty space where the sidebar was previously displayed.

**To Reproduce**

1. Go to Chat in sidebar
2. Click on Collapse
3. Observe the main chat container not expanding to occupy the freed space.

**Expected behavior**
When the sidebar is collapsed, the main chat container should expand to occupy the full width of the screen, ensuring an optimal user experience.

**Actual behavior**
The main chat container remains the same size, leaving an empty area where the sidebar was, resulting in a suboptimal layout.

**Screenshots**
Video Replicating the problem:

https://github.com/user-attachments/assets/23c79b7c-a1f6-44fb-9f67-f65cf6fd283c

**Additional details**
None

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by CHIRANTH-24** [comment]
@palisadoes and @rishav-jha-mech 
I would like to work on this issue
Could you please assign this to me?

**Comment by palisadoes** [comment]
Please write tests to make sure this isn't repeated

**Comment by CHIRANTH-24** [comment]
@palisadoes this issue is in the develop branch.
Should i checkout a new branch from develop?

I am not able to find "Chat" section in develop-postgres branch

**Comment by palisadoes** [comment]
1. This should be closed. 
2. We are only working with the `develop-postgres` branch until further notice
