### ISSUE TITLE
GitHub Action: Code Rabbit Approval Check

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#3003]
**Is your feature request related to a problem? Please describe.**

1. We have a policy of not merging PRs unless CodeRabbit.ai approves the PR
2. This requires a manual verification which takes time and is unreliable
3. We need a GitHub Action workflow that automates this

With this check we will only need to review PRs that have green ticks that are truly valid.
- https://github.com/PalisadoesFoundation/talawa-admin/pulls

**Describe the solution you'd like**

1. CodeRabbit.ai usually approves the PR before the workflow run is complete
2. We need to have a check at the end of the PR workflow that checks whether the PR has been approved
3. If it is not approved, then the check must fail. Ideally it should check the name of the reviewer as being the CodeRabbit user
5. The test for starting the app in docker and without docker must always pass first. This is a mandatory dependency

**Describe alternatives you've considered**

- N/A

**Approach to be followed (optional)**

- N/A

**Additional context**

- N/A

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by mandeepnh5** [comment]
Can i work on this issue?
