### ISSUE TITLE
Large Amount of linting errors.

### ISSUE THREAD

**Issue by Suyash878** [PalisadoesFoundation/talawa-admin#3020]
**Describe the bug**
When we run the linting tests, we come across a huge number of linting errors mainly across the `src/` directory. 
Now this can hamper the overall code quality of the codebase.

**To Reproduce**

1. Open the terminal
2. Run `npm run lint:fix`
3. Observe the linting errors.

**Expected behavior**
The number of linting errors should be relatively lesser or we should atleast try to minimize them.

**Actual behavior**
There are a lot of linting errors 

**Screenshots**
![image](https://github.com/user-attachments/assets/e2ce883e-1ac1-4a71-9b8c-09a162b847e8)
![image](https://github.com/user-attachments/assets/3c3661ee-cd86-43a8-9b5e-caaa2f8cd060)

**Additional details**
None.

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Suyash878** [comment]
I would like to work on this.

**Comment by palisadoes** [comment]
This used to work, and only on changed files in a commit. What changed?

**Comment by Suyash878** [comment]
Yes, you are right that it works. 
   Normally as part of our CI/CD pipeline workflow test, it runs the command `npx eslint ${CHANGED_FILES}` and this showes the linting issues in all the files that may have been changed as a part of the contribution.
**What this PR focuses on**
This PR focuses on finding all the files which may have some linting issues at present and fixing them. This would ensure proper uniformity of the linting rules across the repo.

**Comment by palisadoes** [comment]
It would fix it in the PR versus making the person do the linting manually?

**Comment by Suyash878** [comment]
Apologies for the prior confusion, 
The aim of this issue is to resolve linting errors across the entire repo (we can get this info by using `npm run lint:fix`).

**Comment by palisadoes** [comment]
This will cause our latest checks to fail as you will update files with `istanbul-ignore` statements. Fixing that too will also cause the code coverage level to fall making us have to manually update the threshold upward with each new testing PR. We did that once before and it was too labor intensive, that is why we chose the incremental per-PR approach

**Comment by Suyash878** [comment]
Thanks for the clarification, I understand why you prefer the per-PR approach. Considering that, I think it would make sense to close this issue as it will bring more complexity than actually fixing something.
