### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by Devesh21700Kumar** [PalisadoesFoundation/talawa-admin#304]
**Describe the bug**
Unable to Login
![image](https://user-images.githubusercontent.com/59202075/159343828-4af50616-4b9e-4408-bb44-0e73993a9c36.png)

**To Reproduce**
Click on the login button after entering credentials

Looks like there is an extra ```<``` appearing somewhere that's causing the issue

**Comment by asmitsirohi** [comment]
@Devesh21700Kumar, it's working fine on my side. Maybe your current commits are behind from current development branch.

**Comment by Devesh21700Kumar** [comment]
> @Devesh21700Kumar, it's working fine on my side. Maybe your current commits are behind from current development branch.

My commits are on par with the develop branch in both the client repo and server side repo, which I just checked. 
I'll check again once but looks like there is an extra < coming somewhere.

**Comment by Devesh21700Kumar** [comment]
There was a typo from my end in the .env file which went unnoticed that led to this issue.
