### ISSUE TITLE
Bug Report: Admin/User Toggle Becomes Invisible Upon Selection

### ISSUE THREAD

**Issue by Shahmaz0** [PalisadoesFoundation/talawa-admin#3059]
**Describe the bug**
When toggling between "Admin" and "User" modes using a toggle switch on login/signup page, the selected option becomes invisible or disappears. This makes it difficult to determine which mode is currently active and affects the usability of the feature.

**To Reproduce**

1. Navigate to '/' endpoint.
2. Try to toggle switch for selecting between "Admin" and "User."
3. Click on either "Admin" or "User."
4. Observe that the selected option becomes invisible or disappears.

**Expected behavior**
The selected option should remain visible to indicate the current mode clearly.

**Actual behavior**
The selected option becomes invisible after toggling, making it unclear which mode is active.

**Screenshots**

https://github.com/user-attachments/assets/6ceefc7e-af1b-4c27-97b3-875c36d619e1

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship 
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by amitb0ra** [comment]
please assign this to me.

**Comment by palisadoes** [comment]
1. This has been fixed in the `develop-postgres` branch that we are working on until further notice.
2. Closing

**Comment by Shahmaz0** [comment]
okay.
