### ISSUE TITLE
Changes in CONTRIBUTING.md file

### ISSUE THREAD

**Issue by arnab8335** [PalisadoesFoundation/talawa-admin#327]
In order for newcomers to contribute in the project we should apply some visual snapshots in order for newcomers to understand how to generate a PR a in case gets the PR pushed and a good UI can make it even better.

**Comment by arnab8335** [comment]
I want to work on this issue.

**Comment by arnab8335** [comment]
It will help new beginners

**Comment by palisadoes** [comment]
This is not necessary. We will be duplicating documentation on GitHub that will be hard to keep up to date. Closing.
