### ISSUE TITLE
Create setup.md in setup folder

### ISSUE THREAD

**Issue by evasharma12** [PalisadoesFoundation/talawa-admin#328]
The Talawa-Api repository has a setup.md file explaining the folder structure and the function of each file. It makes it easier for users to understand the functioning of the files.

A similar file should be added to this repository. The file will contain brief explanations for each file and illustrations/snapshots wherever required for better information.

**Comment by evasharma12** [comment]
Please assign me this issue.

**Comment by palisadoes** [comment]
Please also update the .js files to have comments that explain their purpose. Ensure that they are JSDocs compliant as we will be using this in future.

**Comment by evasharma12** [comment]
I have created a file named Setup.md and made a [Pull request](https://github.com/PalisadoesFoundation/talawa-admin/pull/329).

About the requirement of comments in the .js files, I think that the files already have commented code in the Setup directory. If you want me to work on some other directory, do let me know.

Thank you.

**Comment by SiddheshKukade** [comment]
Closing due to no further activities
