### ISSUE TITLE
Home page and login page for portal

### ISSUE THREAD

**Issue by XshubhamX** [PalisadoesFoundation/talawa-admin#35]
**Is your feature request related to a problem? Please describe.**
Its a new feature

**Describe the solution you'd like**
I will use chakra/ui for creating UI .

The home page and login page will provide the base for a user to know what this portal can perform and the user having a valid ID can also signin to the portal.

@palisadoes sir can I work on this

Parent Issue:
#49

**Comment by yasharth291** [comment]
I think @Sagar2366 sir this is under gsoc so is it not wrong to start work before results?

**Comment by XshubhamX** [comment]
@yasharth291 there is a need to increase the contributions in this repo which are currently very low. so having a login and home page will give a clear idea about he portal and I dont think it will affect gsoc in any way after all There is a lot to be done

**Comment by yasharth291** [comment]
@XshubhamX talking about me my proposal is totally dependent on talawa admin if homepage and login page is made i have to change my whole idea of UI i have to create a new UI for every page and it will increase work for the selected students so i think waiting till 17 will not effect so much

**Comment by XshubhamX** [comment]
@yasharth291 you are using react js right ?

**Comment by yasharth291** [comment]
yeah but is it really have any point regarding ui here?

**Comment by XshubhamX** [comment]
@yasharth291 lets talk on slack

**Comment by Sagar2366** [comment]
@XshubhamX keeping this issue on hold until GSoC students announcement.

**Comment by XshubhamX** [comment]
@Sagar2366 sure sir I just  just discussed this with @yasharth291 on slack.

**Comment by XshubhamX** [comment]
@yasharth291 When can we start work on this.
