### ISSUE TITLE
Code Coverage : Create Tests for OrganizatioEvents.tsx

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-admin#367]
The Talawa-Admin code base needs to be 100% reliable. This means we need to have 100% test code coverage.

Tests need to be written for file `src/screens/OrganizationEvents/OrganizationEvents.tsx`

- When complete, all methods, classes and/or functions in the file will need to be tested.
- These tests must be placed in a single file with the name `src/screens/OrganizationEvents/OrganizationEvents.test.tsx`. You may need to create the appropriate directory structure to do this.

### IMPORTANT:
Please refer to the parent issue on how to implement these tests correctly:

- #241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base. This will be clearly visible when you submit your PR.
- [The current code coverage for the file can be found here](https://codecov.io/gh/PalisadoesFoundation/talawa-admin/tree/develop/src/screens/OrganizationEvents/OrganizationEvents.tsx/). If the file isn't found in this directory, or there is a 404 error, then tests have not been created.
- Create a code coverage account for your repo's preferred branch to generate the values when you do your commits for that branch to your repo.
    - _**NOTE:**_ Make sure you select the correct branch when you do the setup, or else the reporting will fail. You must also create a `CODECOV` GitHub secret for your repo as part of the process.
- The PR will show a report for the code coverage for the file you have added. You can also use that as a guide.

**Comment by VenomFate-619** [comment]
hello 👋🏽 
I would like to work on this.

**Comment by VenomFate-619** [comment]
unable to open `orgevents`  page.
whenever I go to `orgevents`  page it gets redirected to the home page i.e. `orglist` page
I think it is happening due to the failed request.

![image](https://user-images.githubusercontent.com/67755128/211381930-a8335b44-28f4-4254-b959-11f4d874c515.png)

**Comment by shivakr07** [comment]
hello @palisadoes  i would like to work on this issue .could you please assign this task to me

**Comment by palisadoes** [comment]
@VenomFate-619 Are you still working on this?

**Comment by VenomFate-619** [comment]
I'm on it.
But due to some issue I am unable to access organization event page on frontend.
Many people have reported that issue on slack.
So , this  issue is an blockage for me , that why's I am unable to do that.

**Comment by palisadoes** [comment]
@VenomFate-619 Is there an issue created for the organization access difficulty?

**Comment by Ayush-sss** [comment]
I want to work on this issue. Please allow me to work on it.

**Comment by palisadoes** [comment]
I'm going to reassign this to @shivakr07. This issue has been open for some time without action.

**Comment by noman2002** [comment]
@shivakr07 Any progress ?

**Comment by noman2002** [comment]
Unassigned due to inactivity.

**Comment by bigBrain1901** [comment]
I just saw GH-527 with @beingnoble03. Linking the PR to this issue would be great.

Do let me know if I may help with this, anyways :v:

**Comment by beingnoble03** [comment]
Thanks @bigBrain1901!
@palisadoes we'll let you know if there are any other duplicate issues. I think this one can be safely closed, it's a duplicate for #482.
