### ISSUE TITLE
Upgrade react-scripts package to the latest v5.0.1

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#368]
**Describe the bug**

React-scripts has numerous dependencies with known security flaws. Upgrading to the latest version should resolve them. Please refer to the package's release notes.

We will need to check whether the react-scripts package is being used anywhere in our code base. If not, the package should be removed.

- https://github.com/facebook/create-react-app/releases

**To Reproduce**
See above

**Expected behavior**
No vulnerabiltiy present

**Actual behavior**
See above

**Screenshots**
See above

**Additional details**

**Comment by prathamesh-mutkure** [comment]
Hi @palisadoes, I'd like to work on this issue, can you please assign me this? Thank You :)
