### ISSUE TITLE
Not able to create organisation

### ISSUE THREAD

**Issue by VenomFate-619** [PalisadoesFoundation/talawa-admin#370]
**Describe the bug**
Not able to create an organisation, getting an error of 400

**To Reproduce**
Steps to reproduce the behaviour:

1. Click on the `Create Organisation` button
2. Fill up the info
3. Click submit

**Screenshots**
![image](https://user-images.githubusercontent.com/67755128/210196175-a97f1dd2-5b32-4a29-b5b8-0bdfaba4f4d6.png)

Response:-
![image](https://user-images.githubusercontent.com/67755128/210196192-effa4267-12ac-4a4e-b36e-9abc158236a8.png)

**Additional details**
This is happening because the tags field is removed from the model
https://thepalisadoes-dyb6419.slack.com/archives/CSWGQ70UQ/p1671096149533199?thread_ts=1670743751.586029&cid=CSWGQ70UQ
@yasharth291

**Comment by VenomFate-619** [comment]
I would like to fix this.
May be we can remove the tag field form frontend or fix it from the backend

**Comment by SiddheshKukade** [comment]
Hi @VenomFate-619 if the `tag` property is  not present. Then I would suggest  implementing that instead of deleting the input field from the front end

**Comment by rv602** [comment]
A temporary fix to this issue would be to remove the tags property from all the places.

<ol>
<li>GraphQl/Mutations/mutation.ts</li>
<li>GraphQl/Queries/Queries.ts</li>
<li>Screens/LoginPage.tsx</li>
<li>OrgList/OrgList.tsx</li>
</ol>

Hope it helps you.

**Comment by prathamesh-mutkure** [comment]
Okay this issue still seems to be here, the error has evolved 

<img width="757" alt="Screenshot 2023-01-29 at 2 53 19 AM" src="https://user-images.githubusercontent.com/28570857/215292412-79eca324-3559-444f-88a9-9b6bf8af3ccc.png">

I've figured out the error and have the solution ready.

@SiddheshKukade @palisadoes can I take up this issue?

**Comment by noman2002** [comment]
@VenomFate-619 Are you still working on this issue ?

**Comment by VenomFate-619** [comment]
I had fixed this from the backend, test it on the latest code of backend.

**Comment by prathamesh-mutkure** [comment]
@VenomFate-619 I actually had the latest code across frontend and backend and I found it to be a frontend issue, can you try it once?

**Comment by prathamesh-mutkure** [comment]
Okay, the issue was @VenomFate-619 updated and fixed the backend but that caused a type mismatch with the frontend, which I've fixed in #422

**Comment by palisadoes** [comment]
This means that the API has incomplete testing for organization creation. For this issue to be closed we need to ensure 100% code coverage for new organization testing in the API. @VenomFate-619 please propose a solution.

**Comment by VenomFate-619** [comment]
this issue is more concerned with the integration part rather than the unit test of code.

The solution to this would be 

- A  creation of an issue at frontend to match the query or mutation of the backend with the frontend, the docs should also be updated


I had already raised a discussion of this on slack, so do refer to [this](https://thepalisadoes-dyb6419.slack.com/archives/CSWH4PN0M/p1674999104333239)
