### ISSUE TITLE
Organisation icon not visible

### ISSUE THREAD

**Issue by rv602** [PalisadoesFoundation/talawa-admin#375]
In the homepage of the admin portal, the icons of the organisations aren't visible. Screenshot attached below.

### Steps to reproduce the behaviour:
<ol>
<li>Open the Admin Portal Homepage</li>
<li>Create a new organisation</li>
<li>The icon you uploaded for the organisation won't be visible, as shown in the screenshot below</li>
</ol>

![image](https://user-images.githubusercontent.com/92572013/211197996-82714c23-1acb-4603-8056-40a125978c43.png)

**Expected behaviour**
Icons of the organisation should be visible for better user experience.

**Actual behaviour**
Currently, any of the organisations icons aren't visible.

**Additional information**
I even tried uploading images with the 200x100 height width requirements. Still same issue persists.

**Comment by rv602** [comment]
@palisadoes could you please let me know if I can work on this issue?

**Comment by noman2002** [comment]
Unassigned due to inactivity

**Comment by adi-uchiha** [comment]
Can I work on this ?

**Comment by rishav-jha-mech** [comment]
@palisadoes is this not a duplicate issue ? #477

**Comment by palisadoes** [comment]
Yes. Closing

**Comment by noman2002** [comment]
@adi-uchiha Please work on some other issue.
