### ISSUE TITLE
Bug: The Developer installation UX must be improved 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#377]
Our INSTALATION.md documentation is incomplete which makes it difficult for new Talawa contributors to add new features and fix bugs.

The existing INSTALLATION.md file must clearly explain:

1. The pre-requisite Talawa apps that must be running before the mobile app will work and why.
1. The default URLs to use to interact with this and any other Talawa apps where applicable.
1. All the possible configuration parameters that can be used.
1. What needs to be done after changing any configuration parameter (if necessary)
1. The preferred way to install the app as a developer
1. The preferred way to install the app as a non-developer

Links to the INSTALLATION.md files of other repos should be used to help remove ambiguity.

The existing CONTRIBUTING.md file must:

1. only refer to the INSTALLATION.md file for setting up the app.

This is being classified as a bug as the resolution of this issue will make the app run more predictably.

**Comment by aashimawadhwa** [comment]
I would like to work on this , please assign it to me. @palisadoes .

**Comment by palisadoes** [comment]
Please work with @Kevoniat on this.

**Comment by aashimawadhwa** [comment]
> Please work with @Kevoniat on this for PR approval.

Okay , Thankyou. 
I will create a PR soon.

**Comment by aashimawadhwa** [comment]
There are some installation instructions in the README.md as well . do I have to remove it from there and put it in INSTALLATION.md ? @palisadoes

**Comment by palisadoes** [comment]
Yes, or else it will cause confusion. Please add a link to this file in the README.md under the `Documentation` section.
