### ISSUE TITLE
Captcha Error! while registering on talawa-admin.

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#380]
The Bug here is related to the registering to talawa-admin while setting up the apllication on the local system.(Screenshot added below)

**Steps to reproduce the behavior:**

1.Clone the repository and follow the instruction to locally setup the application and then start your application.
2.The Register/Login page will appear. 
3.Fill out the details required on the register page  and click the checkbox( i am not a robot).
4.Click the register button and u will get the error

**Expected behavior**
The user should be successfully registered and should be able to later login to the application.

**Actual behavior**
Currently , the reCaptcha is giving some error because of which the user isn't able to register.

**Screenshots**
![Screenshot from 2023-01-18 01-10-28](https://user-images.githubusercontent.com/107215525/212999672-2bfb53ef-15f4-40dc-b067-55acad5cbc03.png)

**Comment by anurag0006** [comment]
@palisadoes, i think more information should be added to the installation guide and i would like to work on that...Please do assign it to me.

**Comment by palisadoes** [comment]
1. We have a PR open for significantly updating the` INSTALLATION.md` file: https://github.com/PalisadoesFoundation/talawa-admin/pull/379
2. Please wait for that to be closed before adding your comments to that file as part of the PR.

**Comment by anurag0006** [comment]
@palisadoes , i searched on internet regarding this issue but wasn't able to find any useful resource for it, though i have a sort of solution :
1.when setting up the talawa-admin in local system, we can change isVerified variable(for the captcha) as true So that we wont have to verify the captcha when working locally...

2.Along with that ,when registering the user on the talawa-admin portal, we receive a message:"You have registered successfully, Please wait for the approval from the organisation" . To solve this, we can reach out to the Mongodb where we have to change the values of some variables in user collections ...(making adminApproved as true and usertype to SuperAdmin).

so what should i do to solve this issue, please guide.

**Comment by palisadoes** [comment]
@xoldyckk This is the issue I mentioned to you. Can you get clarification as to what is going wrong?

**Comment by karthxk07** [comment]
@palisadoes Is the issue resolved or just a hack has been done to opt out of recaptcha for dev purposes, because I am still facing the issue. If yes , I have a fix for the issue , should I open a new issue?

**Comment by palisadoes** [comment]
If you find an issue open it. You don't need permission. I don't generally check issues, even if I create them. I assume a degree of coder initiative and independence

**Comment by karthxk07** [comment]
@palisadoes Understood sir, I'll open a issue then , and wait for it to get assigned. Thank you.
