### ISSUE TITLE
Toggle eye icon in the password Textfiled.

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#386]
**Describe the bug**
Eye icon in the password text field will improve the user experience

**To Reproduce**

1. Run Talawa API
2. Run Talawa Admin
3. Hit local-host
4. See the issue in the login page

**Expected behavior**
A toggle eye icon to show and hide password
![eye-icon-toggle](https://user-images.githubusercontent.com/73706697/213514581-c86f3229-3280-4b72-b165-15e29b529caa.png)

**Actual behavior**
No way of viewing the password for user
![212999672-2bfb53ef-15f4-40dc-b067-55acad5cbc03](https://user-images.githubusercontent.com/73706697/213514573-33e0f764-2dbf-445f-bb1d-6c5600f12645.png)

**Comment by palisadoes** [comment]
@aashimawadhwa Thanks for observing this. We are focusing on fixing bugs and adding tests to our repositories at this time. New features will be included as part of our GSoC ideas. We will be applying again this year. I'll close the issue.

**Comment by aashimawadhwa** [comment]
> @aashimawadhwa Thanks for observing this. We are focusing on fixing bugs and adding tests to our repositories at this time. New features will be included as part of our GSoC ideas. We will be applying again this year. I'll close the issue.

Okay, Thankyou.

**Comment by aashimawadhwa** [comment]
@palisadoes @xoldyckk @noman2002  can we reopen this issue?

**Comment by ibimina** [comment]
@aashimawadhwa @palisadoes please can I work on this?

**Comment by palisadoes** [comment]
> @aashimawadhwa @palisadoes please can I work on this?

If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.
