### ISSUE TITLE
Buttons on talawa-admin show different behaviour on hovering over them(few buttons are responsive to hovering while few of tht buttons aren't)

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#389]
**Describe the bug**
Few buttons on the portal have hover properties while few dont respond to hovering over them

**To Reproduce**

1.To the talwa-admin portal and try to hover on the login or register button,You will see no hover effect
2.Whereas when u reach to the dashboard after logging in, there is this another button named as "create organizations" which responses to hovering

**Expected behavior**
All the buttons should have hovering properties to make make user experince better.

**Actual behavior**
few buttons are responsive to hoverness while few aren't.

**Screenshots**
[Screencast from 20-01-23 01:09:36 AM IST.webm](https://user-images.githubusercontent.com/107215525/213545034-794b72ae-224c-452d-8139-a7ec3f4cd899.webm)
the video shows how hovering on the lower button shows responsiveness while upper button doesn't show any response.

**Comment by anurag0006** [comment]
@palisadoes , I would like to solve this issue by making all the buttons responsive to the hovering to make a better user experience for the user. Please do assign it to me.

**Comment by anurag0006** [comment]
Along with that , these two buttons have different background colors(screenshot attached)...If that is done purposly, then its totally fine, else i can also work to make the color scheme same for all the buttons.
![Screenshot from 2023-01-20 01-24-45](https://user-images.githubusercontent.com/107215525/213546675-35c4ffb1-0af7-4dfc-8c73-830e55a2af78.png)

**Comment by palisadoes** [comment]
- Wherever possible the colors must match our branding guidelines: https://docs.talawa.io/docs/branding/branding-color-palette. 
- Is there a way to make all buttons be a subclass with the proposed property?

**Comment by palisadoes** [comment]
Please make sure to write tests for the change as we don't want this to happen again.

**Comment by anurag0006** [comment]
@palisadoes , while working on this issue , i came accross the forgot page and am not sure if its a bug or it was done intentionally:
![image](https://user-images.githubusercontent.com/107215525/215441689-df973090-a62c-4460-b581-f59ee3f3ae2c.png)
Here the css file should be ForgotPage.module.css instead of just ForgotPage.css which might affect the functionality of page...
Should i change it to ForgotPage.module.css or it was done intenionally?

**Comment by palisadoes** [comment]
It seems that we have `.css` files in most directories in the repo where there are inconsistencies between them. 
1. What strategies do you suggest to have better consistency?

**Comment by anurag0006** [comment]
@palisadoes, I think we should shift to .module.css files because they have a lot of advantages over the other...For example if we use simple css files and give a classname(say "IntroText")...Now there can be a possibility that  there could be styling for a class with same name in global css file which is applied to everything...So even when we try to make some changes in the component , the global css file will have higher precedence and will overtake the styles of  local css file ...But its not a possibility in css modules(.module.css files)...Hence css modules will reduce the errors and also the confusions


Here is a attached link for the advantages of css modules over simple css files:
[https://stackoverflow.com/questions/73588742/benefits-of-using-css-modules-with-react-vue](url)

Also guide me, how to move further on this?

**Comment by palisadoes** [comment]
@Kevoniat What do you recommend?

**Comment by anurag0006** [comment]
@palisadoes  any updates on this ?
