### ISSUE TITLE
Improve Talawa-Admin Installation Documentation

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#390]
Our `Talawa-Admin` installation documentation still needs improvement. It suffers from these shortcomings:

1. `Talawa-Admin` installation instructions are included in other repositories.
    1.  In Talawa's  [INSTALLATION.md](https://github.com/PalisadoesFoundation/talawa/blob/develop/INSTALLATION.md) document under the `Developer Environment Setup` heading, there is extensive setup instructions for `Talawa-Admin` where they should be in the `Talawa-Admin` [INSTALLATION.md](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/INSTALLATION.md) file instead. The Talawa instructions must be updated when this is done.
1. Configuration parameters are not intuitively named adding difficulties to configuration
    1. For example, in `Talawa-API`, the ReCAPTCHA secret key parameter is stored as `RECAPTCHA_SECRET_KEY`,  however in `Talawa-Admin` the site key parameter is stored as `REACT_APP_RECAPTCHA_KEY`.  We should consider using `REACT_APP_RECAPTCHA_KEY` -> `RECAPTCHA_SITE_KEY` or something similar.
    1. We also use the Talawa-Admin configuration parameter `REACT_APP_BACKEND_ENDPOINT` to store the API's URL. A more intuitive name for the parameter such as `TALAWA_API_URL` would be easier for everyone to use.

Where necessary we need to update both the documentation and the code base accordingly.

This is a joint issue with: https://github.com/PalisadoesFoundation/talawa/issues/1389

**Comment by aashimawadhwa** [comment]
As I already worked on this issue, can I take it forward?
@palisadoes .

**Comment by SiddheshKukade** [comment]
@palisadoes sir, actually the prefix `REACT_APP- ` is required for enabling environment variables in react. [reference](https://create-react-app.dev/docs/adding-custom-environment-variables/)
But still, I think we can make the following changes to names: 
`REACT_APP_BACKEND_ENDPOINT` to `REACT_APP_TALAWA_URL`
`REACT_APP_RECAPTCHA_KEY` to `REACT_APP_RECAPTCHA_SITE_KEY`

what are your thoughts on this?

**Comment by palisadoes** [comment]
> @palisadoes sir, actually the prefix `REACT_APP- ` is required for enabling environment variables in react. [reference](https://create-react-app.dev/docs/adding-custom-environment-variables/) But still, I think we can make the following changes to names: `REACT_APP_BACKEND_ENDPOINT` to `REACT_APP_TALAWA_URL` `REACT_APP_RECAPTCHA_KEY` to `REACT_APP_RECAPTCHA_SITE_KEY`
> 
> what are your thoughts on this?

Thanks for the clarification. That makes sense.

**Comment by palisadoes** [comment]
> As I already worked on this issue, can I take it forward? @palisadoes .

1. It requires accepting to fixing this and the joint issue: https://github.com/PalisadoesFoundation/talawa/issues/1389. There will need to be code changes with this issue. I'd prefer to assign the same person to both.

So...

1. Are you willing to do both? Typescript knowledge will be necessary.
1. Can you complete this over the weekend? If not I'll have to reassign it.

**Comment by palisadoes** [comment]
@SiddheshKukade I'll assign you the other issue as we've been talking about this offline.
