### ISSUE TITLE
Code Coverage: Create tests for reportWebVitals.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#397]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
src/reportWebVitals.ts
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by arunavabasu-03** [comment]
Can I work on this ??

**Comment by noman2002** [comment]
@arunavabasu-03 2 issues are assigned to you. Get the PRs merged first.

**Comment by arunavabasu-03** [comment]
ok !!

**Comment by noman2002** [comment]
Thank You for your contributions. Keep contributing. :)

**Comment by arunavabasu-03** [comment]
can you now assign me @noman2002 ??

**Comment by palisadoes** [comment]
@arunavabasu-03 You have six issues assigned to you across all the repositories. Please wait until your PRs are merged.
- https://github.com/PalisadoesFoundation/talawa-admin/issues/assigned/arunavabasu-03
- https://github.com/PalisadoesFoundation/talawa/issues/assigned/arunavabasu-03
- https://github.com/PalisadoesFoundation/talawa-api/issues/assigned/arunavabasu-03

**Comment by arunavabasu-03** [comment]
i gonna tackle all of this , if you want you can assign this too !!

**Comment by palisadoes** [comment]
You are working on too many issues across the repos. Please wait until your changes are merged.

The enthusiasm is appreciated but everyone needs a turn.

**Comment by arunavabasu-03** [comment]
@palisadoes  can you assign me this ?? Actually some `talawa` issues i unassigned because of some `sdk` issue !!

**Comment by palisadoes** [comment]
@arunavabasu-03 You still have 3 issues open across the repos. Please wait until your PRs are merged before asking for more assignments. Others need to have a chance. We try to ensure persons are not working on more than three issues at a time. This is stated in our guidelines.

**Comment by aviraldevv** [comment]
Can I get to work on this issue??

**Comment by aviraldevv** [comment]
@palisadoes we can close this issue. This file is auto-generated and is irrelevant with the the project. I can move it to jest-ignore patterns so that jest doesn't ask for coverage.

**Comment by palisadoes** [comment]
Please submit a PR with the jest update so that we don't forget.
