### ISSUE TITLE
Code Coverage: Create tests for Pagination.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#400]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
src/components/Pagination/Pagination.tsx
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by anshgoyalevil** [comment]
Could you please assign this issue to me @noman2002
