### ISSUE TITLE
Code Coverage: Create tests for Plugin.helper.ts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#401]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
src/components/AddOn/support/services/Plugin.helper.ts
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by anshgoyalevil** [comment]
Could you please assign this issue to me. I have created the test with updated coverage of 100% for this file.

![image](https://user-images.githubusercontent.com/94157520/215547209-f5db9515-1bbc-49cf-a470-52fc43738db0.png)
![image](https://user-images.githubusercontent.com/94157520/215547275-fc91fc40-d7e8-434e-b112-c63562b2f9f6.png)
