### ISSUE TITLE
Code Coverage: Create tests for AddOnStore.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#402]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359

We will need unittests done for all methods, classes and functions found in this file.

Any widgets referenced in this file must also have unittests done

```
src/components/AddOn/core/AddOnStore/AddOnStore.tsx
```

- Parent Issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/241

### PR Acceptance Criteria

- When complete this file must show **100%** coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Comment by anshgoyalevil** [comment]
Could you please assign this issue to me.

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil You already have 3 assigned issues. Please wait for others to close before asking for more assignments.

Sure Sir, Thanks

**Comment by Aankirz** [comment]
Hi @palisadoes sir, I am willing to solve this issue, can you please assign this to me 😄

**Comment by Aankirz** [comment]
Hey @noman2002 & @palisadoes, I have almost made the test cases for this file  but I'm getting an error in the  "AddOnStore.tsx", file, I don't know the type of getPlugins , I tried to google it but I'm not able to find, Pls help.

line no. 176 of "AddOnStore.tsx" file

<img width="782" alt="Screenshot 2023-02-04 at 5 56 33 PM" src="https://user-images.githubusercontent.com/95562947/216767570-61db8c3a-8707-4dab-a136-d0737cc844c4.png">

**Comment by palisadoes** [comment]
@yasharth291 Do you have any insights into this?

**Comment by noman2002** [comment]
@Aankirz Any progress? Its been more than 2 weeks.

**Comment by anayo-hub** [comment]
Hi @palisadoes , can you please assign this to me, it would be my first

**Comment by xoldyckk** [comment]
@anayo-hub go ahead

**Comment by anayo-hub** [comment]
@xoldyckk thanks a lot.

**Comment by palisadoes** [comment]
Unassigning due to inactivity others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by saadabban76** [comment]
Can you please assign this issue to me @palisadoes  ?

**Comment by saadabban76** [comment]
Hi @palisadoes Sir, I looked into the Plugin Store Page, the plugin store component data is all static and is broken with GraphQl queries not being configured correctly, the add new, filters, uninstall functionality doesn't work and the plugins displayed in the page are all static, I would like to solve these issues first before moving on to its test.tsx file.

Below is the screen recording of the above issue : 

https://user-images.githubusercontent.com/115649011/226155175-e548d579-d10d-41a3-93df-b758def04143.mp4

**Comment by palisadoes** [comment]
I'll close the issue. Plugins will be redesigned for GSoC

**Comment by saadabban76** [comment]
> I'll close the issue. Plugins will be redesigned for GSoC

alright 👍🏼
