### ISSUE TITLE
Update OrgDelete.test.tsx: Remove herokuapp.com reference 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#409]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359
 
We are no longer using the `talawa-graphql-api.herokuapp.com` domain as an external API testing URL. This is because we had no feasible way of controlling access, cost and long term maintainability. This file has these references to the URL which must be removed.

Testing integrity must be maintained. Removing the specific tests is not an acceptable solution

```
talawa-admin/src/components/OrgDelete/OrgDelete.test.tsx:16:  uri: 'https://talawa-graphql-api.herokuapp.com/graphql',

```

**Comment by prathamesh-mutkure** [comment]
Hey, @noman2002 @nesiann @tonythegr8 can you please assign me this issue?
