### ISSUE TITLE
Update user_configuration.js: Remove herokuapp.com reference 

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#411]
- Please coordinate **issue assignment** and **PR reviews** with the contributors listed in this issue https://github.com/PalisadoesFoundation/talawa/issues/359
 
We are no longer using the `talawa-graphql-api.herokuapp.com` domain as an external API testing URL. This is because we had no feasible way of controlling access, cost and long term maintainability. This file has these references to the URL which must be removed.

Testing integrity must be maintained. Removing the specific tests is not an acceptable solution

```
talawa-admin/setup/user_configuration.js:93:          'https://talawa-graphql-api.herokuapp.com/graphql',

```

**Comment by aashimawadhwa** [comment]
I am willing to work on this issue, can you please assign it to me.
