### ISSUE TITLE
Cannot open orgdash

### ISSUE THREAD

**Issue by VenomFate-619** [PalisadoesFoundation/talawa-admin#412]
**Describe the bug**
On clicking the manage button on orglist it is not going to orgdash page, it gets back to orglist pagr

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an organization
2. click on the `manage` button

**Expected behaviour**

On clicking the `manage` button orgdash should be open.

**Actual behaviour**

it gets redirected back to orglist

**Screenshots**

https://user-images.githubusercontent.com/67755128/215266911-2f07daa5-cd58-4e5b-a70f-113e09c28f31.mov

**Additional details**
https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1673430600985429

**Comment by VenomFate-619** [comment]
Can I fix this.
I had investigated why it is happening 
https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1674557631837709

I had made the changes and got this

![2023-01-28_18-13](https://user-images.githubusercontent.com/67755128/215267094-034cd28d-55fd-4110-ae2a-71da3cbdd69b.png)

**Comment by beingnoble03** [comment]
@VenomFate-619 Can you please open a PR for this issue as soon as possible?

**Comment by VenomFate-619** [comment]
Working on it , it is blocked by some other things

**Comment by palisadoes** [comment]
- Is it being blocked by unsolved issues in the code base?
- Do you need assistance from the mentor community?

**Comment by VenomFate-619** [comment]
https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1675423483895689
I mentioned the blockage here.
I need assistance from a mentor
I thought of an approach for this.

I would remove spamOrganization from the query and make UI work without spamOrganization means will handle the case if it does not exist.
remove spamOrganization from the test also.
spamOrganization value is used in AdminNavbar component only

**Comment by palisadoes** [comment]
OK, please proceed. We have a GSoC SPAM should restore functionality as a plugin.
