### ISSUE TITLE
[ UI Optimization ] add spacing to the header and footer and change the font size of the navlinks.

### ISSUE THREAD

**Issue by saadabban76** [PalisadoesFoundation/talawa-admin#413]
**Describe the issue :**
The Spacing between the Copyright and the social links tab in the footer does not have any spacing which does not look good, and giving some more padding to the navbar will give a good look to the navbar, also the font size of the nav links and logo are same which does not look good. ***please check out below screenshot for reference***

The navbar : 
![nav](https://user-images.githubusercontent.com/115649011/215272963-3a602833-a0a6-4781-9216-1a69e55acf5a.png)

The Footer : 
![footer](https://user-images.githubusercontent.com/115649011/215272976-96531b66-420c-4b61-b73d-43419f43f4d8.png)

**Describe the solution :** 
I want to add some spacing on the footer section between copyright and links tab, and change the font size of the nav links on the navbar as it is the same size as the Logo, also increase the padding on the navbar.

If this Issue is relevant, please assign me this issue to work on ❤️ 

the website link : https://docs.talawa.io/

**Comment by palisadoes** [comment]
We are focusing on bugs affecting the core functionally and improving reliability through testing.

Our volunteers' time is precious and we prefer not to be reviewing minor cosmetic changes.

Please read the pinned issue about issue quality.

Closing.
