### ISSUE TITLE
Automate org and admin user addition during installation

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#414]
## It is very important that we fix this immediately

**Describe the bug**
The current INSTALLATION.md file describes how to add an organization and user as part of the installation process.

It then explains how to upgrade the user's administrative level.

This creates unnecessary hardship for new administrative users as it requires technical database knowledge.

1. The organizational and user administration must be automated in such a way that it can only be run once for brand new installations. 
1. If run a second time, there must be a descriptive error.
1. The use of the methodology should be inserted into INSTALLATION.md as it's own section. The existing manual method of doing this must remain. This is to ensure a backup option exists if the automated method fails.

**To Reproduce**
See the INSTALLATION.md file.

**Expected behavior**
See above.

**Actual behavior**
See above.

**Screenshots**
Not applicable

**Additional details**
None

**Comment by rv602** [comment]
I am willing to work on this. I am already trying to tackle this in the script I'm writing in the backend.
https://github.com/PalisadoesFoundation/talawa-api/pull/941

**Comment by noman2002** [comment]
Unassigned due to inactivity.
