### ISSUE TITLE
bug:create organisation button(on the dashboard page) has different background color than the color used on the other buttons in application

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#416]
**Describe the bug**
The color of the create organisation button is different than that of the others making a bad user experience.
**To Reproduce**

1.Go to the dashboard page.
2.You can notice the difference in colors of the buttons on this page.
3.Or go to the developers tools and inspect the buttons to see the difference.

**Expected behavior**
The color scheme should be consistant through out the application.
**Actual behavior**
the color scheme is not same.
**Screenshots**
![Screenshot from 2023-01-29 02-54-40](https://user-images.githubusercontent.com/107215525/215292405-c3a7151c-9983-4068-ac7d-bd39e6cdad9a.png)

![image](https://user-images.githubusercontent.com/107215525/215292070-953c0fb3-5499-4e99-bcb6-46717fef8ee4.png)

**Additional details**
The official color provided by the palisadoes foundation is #31bb6b and the create org button has color : #28a745 .

**Comment by anurag0006** [comment]
I would like to solve this bug, Please assign this to me.

**Comment by palisadoes** [comment]
@anurag0006 we are focusing on fixing bugs that affect functionally and on testing to improve our code reliability.

Please review this pinned issue https://github.com/PalisadoesFoundation/talawa/issues/1152

Minor design changes are not on current score
