### ISSUE TITLE
(chore) Use constants instead of environment variables across the app

### ISSUE THREAD

**Issue by prathamesh-mutkure** [PalisadoesFoundation/talawa-admin#417]
**Is your feature request related to a problem? Please describe.**

- This isn't particularly a bug or anything but rather a code improvement
- Currently, the following files access the backend URL directly through `process.env.REACT_APP_TALAWA_URL`
- <img width="388" alt="Screenshot 2023-01-29 at 3 28 42 AM" src="https://user-images.githubusercontent.com/28570857/215292971-3a640f9e-ce52-41ac-b83a-4b6d46a68d5f.png">
- This is a bad coding practice since it is difficult to maintain and refactor the code

**Describe the solution you'd like**

- A better approach will be to store the value extracted from the environment variable in constant files
- And the constant will be used across the app 
- <img width="579" alt="Screenshot 2023-01-29 at 3 30 45 AM" src="https://user-images.githubusercontent.com/28570857/215293011-1d2d3f5d-0345-488a-8e01-40b326b79fb7.png">

**Describe alternatives you've considered**

This seems to be the best approach

**Additional context**

- This will make it easy to update names of environment variables like done in this [commit](https://github.com/PalisadoesFoundation/talawa-admin/commit/f659baf02e55b302d41bd929523610bd37ca951b)
- This commit could have been much less work if we used the approach I proposed above

**Comment by prathamesh-mutkure** [comment]
I'm willing to work on this @noman2002

**Comment by palisadoes** [comment]
Thanks for pointing this out.

Please apply this strategy for all environmental variables found in the `.env` file.

**Comment by prathamesh-mutkure** [comment]
Hi@noman2002, is this PR eligible for internship points?

**Comment by noman2002** [comment]
Yes, Every PR is eligible. The tag will be added later.
