### ISSUE TITLE
Bug:Some components use css modules for styling while others use css files which creates inconsistancy.

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#426]
**Describe the bug**
Inconsistancy in the type of files used for the styling the components(some components are using css files while others are using css modules for styling)

**To Reproduce**
1.locally setup the project
2.open your code editor
3.open the forgotPassword component which has used 'ForgotPassword.css' file while just under it is LoginPage component which is using 'LoginPage.module.css'

**Expected behavior**
A general React project has one global css file and then rest of the components are styled using css modules.

**Actual behavior**
some components using css modules files while some use css files
**Screenshots**
![image](https://user-images.githubusercontent.com/107215525/216169760-329c14dc-d0ca-492d-ae05-8bb46ee5d3d0.png)

**Comment by anurag0006** [comment]
I would like to work on this issue but first i need some guidance from @kevoniat sir on how to proceed on this issue...

**Comment by anurag0006** [comment]
@palisadoes sir, i talked to @kevoniat sir regarding this and he asked me to switch to css module approach,so can u please assign this issue to me

**Comment by palisadoes** [comment]
Please work with @Kevoniat  for reviewing the PR
