### ISSUE TITLE
Code Coverage: Create tests for OrganizationPeople.tsx

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-admin#428]
Currently the file `/src/screens/OrganizationPeople/OrganizationPeople.tsx` doesn't have 100% coverage, and isn't included in the parent issue #241.
The coverage needs to be increased to 100%

**Comment by EshaanAgg** [comment]
Can I work on this issue?

**Comment by palisadoes** [comment]
You are working on many issues across the repos. Please make merges close some of them before asking for more. Everyone needs an opportunity.

**Comment by EshaanAgg** [comment]
@noman2002 Closing this issue as the file now has 100% coverage due to latest commits.
