### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ssaumyaa7** [PalisadoesFoundation/talawa-admin#43]
**Is your feature request related to a problem? Please describe.**
This is a new feature that can be added when a person register themselves with any organisation.

**Describe the solution you'd like**
Any person registered as attendee for any organisation should be given choice to volunteer the event.

**Approach to be followed (optional)**
Add a new feature of the volunteers while registering for any organisation. Organisation can outline what they expect from volunteers and if a person can fulfill the requirements they can request organisation to accept them as volunteer.

Whether to select that person as volunteer or not solely depends on organisation, they can accept or decline request.

Also organisation can mention the number of volunteers required.

**Additional context**
NA

@palisadoes sir

**Comment by XshubhamX** [comment]
@ssaumyaa7 I think these tasks will be performed by the talawa app, admin portal should be used for CRUD operations on the organization. So the work needs to be done in talawa and talawa-API. Further, you can ask mentors about that.

**Comment by ssaumyaa7** [comment]
@XshubhamX If so then the admin portal should have a list of volunteers associated with the specific organization. 
Further rest depends on mentors as in where to add this feature.

@Sagar2366 sir @palisadoes sir
