### ISSUE TITLE
Clarify MongoDB section of INSTALLATION.md

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#430]
**Describe the bug**
The current guide instructs the user on how to edit the _**local**_ MongoDB instance through a Web UI edits without showing how to launch the Web UI. 

We need very clear and comprehensive instructions on how to do the required edits via:

1. The web UI
2. The MongoDB CLI.

Both methods should show:

1. How to view the state of a newly installed database
2. How to view the records for the ADMIN user
3. How to correctly edit the records for the ADMIN user
4. How to confirm the edits were correct

## This issue is for installing on a local, not cloud based, instance

**Expected behavior**
See above

**Actual behavior**
Look at the existing INSTALLATION.md file

**Screenshots**
N/A

**Additional details**
N/A

**Comment by aviraldevv** [comment]
@palisadoes I am up for fixing this.

**Comment by AjayMaheshwari23** [comment]
@aviraldevv are you working on this ?

**Comment by aviraldevv** [comment]
@AjayMaheshwari23 I have already submitted a PR for it.

**Comment by AjayMaheshwari23** [comment]
Cool
