### ISSUE TITLE
Bug Report: Invalid Image URL in INSTALLATION.md

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-admin#431]
**Describe the bug**
The image referenced in the `Setting up RECAPTCHA_SITE_KEY` in `INSTALLATION.md` does not exist at the given URL.
![image](https://user-images.githubusercontent.com/96648934/216533530-a69566b0-1ed3-4981-9132-256e9b08b55c.png)

**To Reproduce**
1. Open `INSTALLATION.md`.

**Comment by EshaanAgg** [comment]
I can work on this issue.

**Comment by palisadoes** [comment]
Make the image reside in this repo, with a relative link so that it won't break across branches.
