### ISSUE TITLE
Bug Report: Multiple warnings being logged in console with `yarn serve`

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-admin#432]
**Describe the bug**
![image](https://user-images.githubusercontent.com/96648934/216534628-c4729bdb-c1e6-4e0e-8fa1-de46864c2e9e.png)
Many `@typescript-eslint/no-unused-vars` warnings are logged in the console on starting up the development server.

**To Reproduce**
1. Run `yarn serve`

**Expected behavior**
No warnings should be logged on starting the server.
 
**Actual behavior**
Multiple warnings are logged.

**Comment by prathamesh-mutkure** [comment]
Hi @noman2002, I'd like to resolve this

**Comment by palisadoes** [comment]
@EshaanAgg Is there a way to make our GitHub actions fail if there are these types of errors so that we don't repeat this difficulty?

**Comment by EshaanAgg** [comment]
I'm not sure, but I can read about it and get back to you within 24 hours. @palisadoes

**Comment by EshaanAgg** [comment]
Update:-
We can configure the `eslint` to throw an error while linting on even warnings with the `--max-warnings=0` flag. Changing this is in GitHub action should protect the repository from these of errors in future. Should I add a PR modifying the GitHub action?

**Comment by palisadoes** [comment]
Add the update to the PR that is addressing this issue. They are too closely related.

**Comment by EshaanAgg** [comment]
Sure.

**Comment by palisadoes** [comment]
@EshaanAgg We missed something
- In [pull-requests.yml](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml) you have linting taking place in the `Count-lines-of-code` section. That should be the `Linter` section. 
- I'm going to reopen the issue. Please submit another PR to fix this.

![image](https://user-images.githubusercontent.com/16875803/216843458-34488a21-0908-429e-a50d-24a4277dd69b.png)
