### ISSUE TITLE
Feature Request: Script to setup some "starter" database objects for first time users 

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-admin#433]
**Is your feature request related to a problem? Please describe.**
After setting up the `talawa-admin` repository locally, a user needs to manually needs to register a user, elevates its privileges, and then create more objects linked to it, such as organization, direct and group chats before the user can explore all the functionalities of the portal.

**Describe the solution you'd like**
We can create a simple script (in `ts` or in `py`) that the user can run once after setting up the repository, in which the user can interactively provide data like `username` and `password` for the user, ` organization name` etc. (or the script can go to default values if the user omits them). Then the script can make the mutation requests to the backend to set up all these objects for the user initially so that the developers can directly get to testing.

This script can be in later stages also expanded to mass-populate data, as some devs might need to measure performance, or for more complex relations.

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
1. Discuss in this issue what all objects we should create for the user so that they can have the best experience as well as get acquainted with all of the features of `talawa-admin`.
2. Write a script that makes the required requests, while allowing the user to skip some values (the script would provide a default template for them)
3. Update the documentation about the same.
4.  (Optional) Make the script more general purpose, allowing for creating large datasets.

**Additional context**
I am still unsure as to what would be the best place to create a script such a script. Creating the same in `talawa-admin` ensures that the script is where the "functionality" resides, but placing the same in `talawa-api` ensures that it resides where the "data" is actually present, and would make writing the script easier too, as we would be able to access the database directly through `Mongo`.
Would appreciate your views and opinions on such a feature.

**Comment by palisadoes** [comment]
- This is being addressed in https://github.com/PalisadoesFoundation/talawa-api/pull/941
- Please take a look and comment

Closing.
