### ISSUE TITLE
Bug : receiving warning of "caniuse-lite is outdated" in terminal when running "yarn test"

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#436]
**Describe the bug**
The bug here is related to the dependencies of the testing system...when we try to test our files using yarn test, we receive this message on the top in the terminal
**To Reproduce**

1.Open the repo
2.Run "yarn test"
3.U will receive this(screenshot attached) in the terminal

**Expected behavior**
The should be no warning or signal in the terminal.
**Actual behavior**
a sort of warning that we are getting when testing our code.
**Screenshots**
![image](https://user-images.githubusercontent.com/107215525/216686788-80ed1f68-7413-4bd8-905a-e626defd74f6.png)

**Comment by anurag0006** [comment]
I would like to work on this issue...Please assign it to me

**Comment by palisadoes** [comment]
- Make sure that all errors and warnings are fixed 
- Determine whether there is a way to have our pull-request GitHub action fail if these errors persist.

**Comment by anurag0006** [comment]
sir, the problem is we are using older version of caniuse-lite which is outdated...We need to just shift to the latest version of it...Still i will try to find if we can make our github action fail if such error persist.
