### ISSUE TITLE
Org Create: Missing code for org image upload

### ISSUE THREAD

**Issue by prathamesh-mutkure** [PalisadoesFoundation/talawa-admin#438]
**Describe the bug**
- I was creating an organization and noticed that the image is not getting saved in that database
- Upon inspecting the code, I found out that the `onChange` property of image input has been commented out
- Thus, the code is missing

**To Reproduce**

1. Start the `talawa-api`
2. Start `talawa-admin`
3. Login and click the create organization button
4. Fill all the fields and upload a image
5. Click the submit button
6. The organization will be created without the photo

**Expected behavior**

Ideally, the image should be uploaded and saved to the database.

**Actual behavior**

The image is not being sent to the server, thus the organisation is getting created without any image

**Screenshots**

The `onChange` property on line [374](https://github.com/prathamesh-mutkure/talawa-admin/blob/develop/src/screens/OrgList/OrgList.tsx#L374) is commented out - 

<img width="911" alt="Screenshot 2023-02-04 at 6 43 28 PM" src="https://user-images.githubusercontent.com/28570857/216769672-51dfcdee-5fbe-40c0-9271-fd490b3afae4.png">

**Additional details**

Organizations getting created without any images

<img width="1222" alt="Screenshot 2023-02-04 at 6 44 30 PM" src="https://user-images.githubusercontent.com/28570857/216769714-e481103b-c56f-4d17-b6df-aa2394a127ca.png">

**Comment by palisadoes** [comment]
1. Thanks, we are working on an overall image storage strategy here. When that is complete week be able to address this: https://github.com/PalisadoesFoundation/talawa-api/issues/952
2. Please follow that progress

**Comment by palisadoes** [comment]
1. Thanks, we are working on an overall image storage strategy here. When that is complete week be able to address this: https://github.com/PalisadoesFoundation/talawa-api/issues/952
2. Please follow that progress

**Comment by kb-0311** [comment]
@prathamesh-mutkure I have been working on coming up with strategies to tackle file uploads pls bear with me. You can follow up the progress [here](https://github.com/PalisadoesFoundation/talawa-api/issues/952)

@palisadoes pls check slack channel.

**Comment by palisadoes** [comment]
@xoldyckk please check the slack channel regarding this issue

**Comment by SiddheshKukade** [comment]
I think, adding a photo to the Organization should not be a compulsion admin can add that later on so this not any `bug`.

**Comment by palisadoes** [comment]
1. @SiddheshKukade you are right. This is something that could be included as part of a GSoC idea for adding functionality.
1. Converting this to a feature. We are not focusing on features now.

**Comment by noman2002** [comment]
@palisadoes As the discussions suggests this is not any bug. So, should we close this for now ?
