### ISSUE TITLE
[ Issue ] Fixing Images in Carousel of Home page 

### ISSUE THREAD

**Issue by AjayMaheshwari23** [PalisadoesFoundation/talawa-admin#448]
In the home page , carousel contains 3 images , out of which 2 are of same dimensions but the 3rd one has different dimensions .  These unequal dimensions of images are creating an uneven effect on the size of carousel.

 I want to fix this by making the dimensions of 3rd image same as the other two, so that it feels even.

Here's a demo video describing the same : 

https://user-images.githubusercontent.com/96301800/217273617-4cfd810a-1798-421b-a530-4285852e6ee0.mov

**Comment by palisadoes** [comment]
We need to completely remove the carousel. We cannot confirm the copyright of the images used. It may have been part of the template that was used for the design, but it leaves us at risk.

1. Please remove the carousel and the related images.
1. Replace the images with a single Palisadoes Foundation logo. 
1. Leave the rest of the design and layout as is.
![Palisadoes Logo - White - 600 x 600](https://user-images.githubusercontent.com/16875803/217308725-f5dca210-cab0-430c-bb06-6cff77e03602.png)
