### ISSUE TITLE
Resolve dependency conflicts

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#453]
**Describe the bug**
1. Run the commands
     ```
            npm i --package-lock-only
            npm audit
     ```
1. The output shows a large number of dependency conflicts

**To Reproduce**
See above

**Expected behavior**
1. These conflicts need to be resolved.
1.  Update the GitHub action for pull-requests so that they fail when future dependency conflicts are found.

**Actual behavior**

See above

**Screenshots**
This is sample output from the `npm i --package-lock-only` command
![image](https://user-images.githubusercontent.com/16875803/217605282-f6339d1d-6005-49af-878e-2455d2219de2.png)

**Additional details**
See above

**Comment by palisadoes** [comment]
@xoldyckk @noman2002 
1. Is this issue worthwhile to pursue?
2. We also have a large number of vulnerabilities related to `react-scripts` and I'd like to know whether we should consider removing it from the application. Should we?

**Comment by noman2002** [comment]
I read somewhere that these warnings arise due to conflicts between the packages we used. I don't know if it possible to remove all of them or not.

**Comment by palisadoes** [comment]
@noman2002 What about `react-scripts`? We have close to a dozen reported vulnerabilities that cannot be updated because the latest version of `react-scripts` requires vulnerable dependencies. Is there an alternative we could use?

**Comment by aashimawadhwa** [comment]
is this somewhere related to issue #394 ? @palisadoes

**Comment by palisadoes** [comment]
@aashimawadhwa 
1. Yes it is.  I forgot about that one. There may be a way to run a command to automatically fix the dependencies.
2. What are your thoughts about `react-scripts`?

**Comment by AjayMaheshwari23** [comment]
@aashimawadhwa i think you are working on #394 , so if you want you can assign this to me so that i can also give it a try

**Comment by aashimawadhwa** [comment]
> @aashimawadhwa
> 
>     1. Yes it is.  I forgot about that one. There may be a way to run a command to automatically fix the dependencies.
> 
>     2. What are your thoughts about `react-scripts`?

i tired updating the dependencies automatically and right now i am doing everything manually

**Comment by palisadoes** [comment]
Hopefully when we get them all OK we can then add the test to GitHub actions so that we never have to go through this again.

**Comment by aashimawadhwa** [comment]
https://stackoverflow.com/questions/16073603/how-to-update-each-dependency-in-package-json-to-the-latest-version 
https://classic.yarnpkg.com/lang/en/docs/cli/upgrade-interactive/

**Comment by aashimawadhwa** [comment]
According to  TL;DR: peerDependencies is for dependencies that are exposed to (and expected to be used by) the consuming code, as opposed to "private" dependencies that are not exposed, and are only an implementation detail.

If P1 and P2 indeed both have peer dependencies on incompatible versions of P3 you will need to either find versions of P1 and P2 with compatible peer dependencies of P3 or abandon the use of either P1 or P2.

**Comment by aashimawadhwa** [comment]
and abandoning dependencies does not feel right to me for some reason, it will break the code to great extent.

**Comment by aashimawadhwa** [comment]
I updated all the packages in package.JSON and tried everything but the npm warnings still exists. @palisadoes 
![Screenshot 2023-02-09 at 2 39 20 AM (2)(1)](https://user-images.githubusercontent.com/73706697/217651765-5cdab5c6-47c6-46e3-99df-be95f5ef49d0.png)
![Screenshot 2023-02-09 at 2 39 20 AM (2)](https://user-images.githubusercontent.com/73706697/217651784-5c6913ad-d71e-4029-a2cf-091df427da41.png)

**Comment by aashimawadhwa** [comment]
1.) For warnings there are no changes as of now , if we look closely into them many dependencies are deprecated and therefore the warning is generated.
2.) most of the issues are there because of the react scripts , I am not sure if we should continue using them but we can use the following alternatives for react scripts i.e : 
- [@craco/craco](https://openbase.com/js/react-scripts/alternatives) (It has built in typescript support, you can read more about it in the link I have attached.)

@palisadoes

**Comment by palisadoes** [comment]
Using deprecated packages is a risk we should not take. How easy would it be to do the replacement?

@noman2002 @xoldyckk what are your thoughts?

**Comment by noman2002** [comment]
It it a bit tedious task to change packages as we might not have exact same replacement for it. I think we should keep this as it is for now and update in one of gsoc projects.

**Comment by palisadoes** [comment]
Thanks Noman,
1. @aashimawadhwa Please submit a PR for what works so far. 
1. @noman2002 Please update the GSoC security to cover this

**Comment by xoldyckk** [comment]
@palisadoes create-react-app is outdated. It focuses on backward compatiblity whereas web ecosystem is moving forward at a rapid rate. Modern web technologies don't work with create-react-app and even if they somehow do you'll spend more time configuring create-react-app than working on the business logic. Also it's built on webpack which is extremely slow.

I'd recommend migrating the project to vite with react and typescript.

**Comment by aashimawadhwa** [comment]
Wdyt Craco migration will help ? @xoldyckk

**Comment by xoldyckk** [comment]
@aashimawadhwa It may work but it's a wasted effort. Even when using craco you're still relying on create-react-app indirectly. You're trying to maintain a whole legacy module system by yourself. If something in create-react-app's core is broken craco can't fix that.

There's a whole war going on with official react team and big influencers and developers in javascript ecosystem to ban the recommendation of using of create-react-app in react docs. 

Look:- https://github.com/reactjs/reactjs.org/pull/5487

**Comment by aashimawadhwa** [comment]
So wdyt updating the yarn.lock  and package.json will create some difference??  @palisadoes @xoldyckk

**Comment by xoldyckk** [comment]
@aashimawadhwa btw talawa-admin uses a outdated version of yarn too. It uses v1 when current yarn version is v3.
