### ISSUE TITLE
OTP Feature Request

### ISSUE THREAD

**Issue by AjayMaheshwari23** [PalisadoesFoundation/talawa-admin#457]
There is an option for forget password but OTP feature in that is not working. 

I would like to implement OTP feature using Nodemailer which sends an mail with random OTP to given mail. 

Demo video of Forget Password section:

https://user-images.githubusercontent.com/96301800/217863410-a091da3a-96ca-400c-a494-03e4105e01aa.mov

Can I work on this ?

**Comment by AjayMaheshwari23** [comment]
@noman2002 @palisadoes  , can i work on this ?

**Comment by palisadoes** [comment]
There are some background discussions that need to be had. We'll get back to you early next week.

**Comment by AjayMaheshwari23** [comment]
Oh Okay

**Comment by palisadoes** [comment]
Remember to have 100% test coverage on the files edited

**Comment by AjayMaheshwari23** [comment]
okay

**Comment by palisadoes** [comment]
Unassigning due to inactivity. We need to give others a chance.

**Comment by AjayMaheshwari23** [comment]
I have carefully observed the whole code and it is working after very minor changes . ( I will attach a video in 10 mins)
Some changes are required in installation docs.

**Comment by AjayMaheshwari23** [comment]
I will create a PR within next 24 hours. Can you please reassign it to me.

**Comment by AjayMaheshwari23** [comment]
I made changes in installation doc in talawa-api , so can i directly create PR in that repository with this issue number or am i required to create another issue in that first ?

**Comment by palisadoes** [comment]
Does your solution require the user to send email through their Gmail account? If this is so, then this will not work for a large organization. Google will stop emails as SPAM as the number of emails sent increases. I have experienced this many times.

It will need to be done via a mail server where no modifications to the installation process will be required.

**Comment by AjayMaheshwari23** [comment]
So are you planning to use some paid mail server because free mail servers have a limit associated with them.

**Comment by palisadoes** [comment]
Whatever the service used, the email relay would be setup in the operating system either in `sendmail` or `postfix` outside of the app. Hosting providers will do this as a part of their service.

You need a solution that will:

1. Work without having to configure a third party in the app
2. Use a recovery URL that is accessible by both developers and end users. So for example, 
    1. As a Developer: If recovery is done on your home wifi, when the email is received you should be able to click the link and recovery should work.
    2. As an End User: The same would be true

This determination would best be automatic. At most the only configuration parameter to use be the one to specify the DNS domain of the recovery link. For example
    1. talawa-recovery.example.org
    1. 192.168.1.35 if on local wifi. This can easily be detected with an RFC-1918 check. So configuration may not be necessary
     1. Use there IPv6 address of the Talawa host

**Comment by AjayMaheshwari23** [comment]
Okay understood i need to make more changes for this then

**Comment by AjayMaheshwari23** [comment]
I am facing difficulty in implementing such a solution .

**Comment by anshgoyalevil** [comment]
@palisadoes 

This issue needs to be closed.

The current implementation of forgot password works as expected.

@AjayMaheshwari23 You might haven't setup the MAIL Variables in .env file of Talawa API, so it is not working on your side.

**Comment by AjayMaheshwari23** [comment]
> @palisadoes 
> 
> This issue needs to be closed.
> 
> The current implementation of forgot password works as expected.
> 
> @AjayMaheshwari23 You might haven't setup the MAIL Variables in .env file of Talawa API, so it is not working on your side.

I have set the variables and that is working fine , but sending mails using a Google account is not recommended

**Comment by anshgoyalevil** [comment]
@AjayMaheshwari23 

We are sending mails using Gmail in our local environment only. 

The way, mailer is setup in Talawa Api, we have option to fill out SMTP server credentials.

So, no issues with that.

**Comment by palisadoes** [comment]
I forgot about that. This was to use email that didn't use your personal email account. This still needs to be fixed.

**Comment by anshgoyalevil** [comment]
@palisadoes 

This doesn't needs to be reopened.

We already have SMTP compatible function.

**Comment by palisadoes** [comment]
OK.

**Comment by anshgoyalevil** [comment]
@palisadoes 

Sorry about that, I just checked, and we are using Hardcoded GMAIL Transporter. Please reopen the issue and assign it to me. 
We need to add the Service variable also to .env file.
