### ISSUE TITLE
Refactor Installation.md

### ISSUE THREAD

**Issue by aviraldevv** [PalisadoesFoundation/talawa-admin#458]
**Describe the bug**
Talawa admin uses yarn version 1.x update  Installation.md in context to it

**To Reproduce**
Add information that Talawa admin works only on version1.x and it blows on newer version.
This would be helpful for beginners as they often face similar issues.

**Expected behavior**
Installation doc will be more beginner friendly.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aviraldevv** [comment]
@palisadoes I would like to work on this issue.

**Comment by aviraldevv** [comment]
@noman2002 due to screen issues the issue was clodeb by mistake

**Comment by aviraldevv** [comment]
Just minor update that we need to make sure that we have installed yarn 1.x version otherwise the talawa admin blows up.

**Comment by aviraldevv** [comment]
https://classic.yarnpkg.com/lang/en/docs/install/#debian-stable

**Comment by noman2002** [comment]
We are working on the yarn thing to get it fixed. This issues is not needed for now.
