### ISSUE TITLE
Cannot Update the Post inside Talawa-Admin

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa-admin#464]
**Describe the bug**
Whenever we create a Post using the Talawa-Admin, it gets created successfully. But, when we try to update it using the pencil icon, it open the update post dialog, but, on making the changes, and clicking on ```Update Post``` button, it gives a ```400 error code```

**To Reproduce**

1. Go to Talawa-Admin Panel
2. Create a new post
3. Click on the pencil icon, and try updating the post.
4. The post will not be updated and will throw an error on clicking the update button.

**Expected behavior**
The post must be updated.

**Actual behavior**
It is throwing an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/94157520/218243713-3ce94ff9-5f88-4b6d-a2a2-112e85290412.png)
.
Open the Developer Console, and Check the Network tab. It will show an error ```{"errors":[{"message":"Cannot query field \"updatePost\" on type \"Mutation\". Did you mean \"createPost\", \"updateTask\", \"unlikePost\", \"updateEvent\", or \"likePost\"?","status":422,"data":[]}]}```

**Additional details**
This error can cause the following problems:
- Data loss: If the request fails to reach the server, any data that was supposed to be updated or added to the database can be lost.
- Inconsistent state: In case of a partial failure of the request, the state of the data in the database can become inconsistent, leading to unexpected results.
- Reduced user experience: If the request fails, the user may not be able to perform the intended actions on the application, leading to frustration and a poor user experience.
- Increased load on the server: If the request fails, the user may attempt to resend the request, leading to increased load on the server and potentially causing performance issues.

**Comment by anshgoyalevil** [comment]
I would like to work upon this issue.

**Comment by palisadoes** [comment]
Please remember to also add tests so that this issue isn't repeated.

**Comment by anshgoyalevil** [comment]
> Please remember to also add tests so that this issue isn't repeated.

Yes Sure. I will be opening the corresponding issue in the Talawa-API project for the same.
