### ISSUE TITLE
Improving UI of Organisation Dashboard

### ISSUE THREAD

**Issue by AjayMaheshwari23** [PalisadoesFoundation/talawa-admin#465]
I would like to improve the UI of organisation dashboard.

Changes I want to implement:
1.) Removing recurrence of pagination bar in posts page
2.) Show a message "No Events now" , in place of blank page 
3.)  similar message for all pages if number of events/posts etc is zero
4.) Replacing the alert on deleting an Event by rc-notification on the right side.

Demo videos describing above points:

https://user-images.githubusercontent.com/96301800/218244059-859cdcf5-7a31-44d4-90e0-edec717d9a99.mov

https://user-images.githubusercontent.com/96301800/218244073-be899df7-d656-473c-8879-901e8cc111ab.mov

Can I work on this ?

**Comment by AjayMaheshwari23** [comment]
@palisadoes @noman2002

**Comment by noman2002** [comment]
@AjayMaheshwari23 We are not planning to add any new feature for now. We will be adding these in gsoc project.

**Comment by palisadoes** [comment]
FYI @AjayMaheshwari23 we are really trying to focus on features where the result

1. Fixes expected functionality
2. The updated functionality has a material impact on the usability of project.

This is outlined in the pinned issue that was mentioned in the issue creation template

**Comment by AjayMaheshwari23** [comment]
Okay

**Comment by palisadoes** [comment]
@AjayMaheshwari23 Please check slack on the #talawa-admin channel
