### ISSUE TITLE
Bug Report: Hint text not translating according to the language in the org dashboard placholders.

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#469]
**Describe the bug**
on changing the language the hint text in the Text filed remains in English and it does not look good.

**To Reproduce**

1. run talawa api and admin in your local machine
2. choose any other language expect English
3. see the issue is on the manage organization dashboard in all the tabs.

**Expected behavior**
The hint text should change as per the language.

**Actual behavior**
The hint text is not changing as of now.

**Comment by aashimawadhwa** [comment]
@noman2002 @palisadoes  i would like to take this.

**Comment by noman2002** [comment]
@aashimawadhwa If I'm not wrong, Signup and login page is fixed in your previous PR.

**Comment by aashimawadhwa** [comment]
yes I have completed for the sign up and login , in this PR i will be working on the remaining placeholders.

**Comment by noman2002** [comment]
Okay, make sure all the placeholders are covered in this PR.

**Comment by noman2002** [comment]
You have 3 issues assigned get all the PRs merged before asking for more. @aashimawadhwa

**Comment by palisadoes** [comment]
@aashimawadhwa Please remember the tests. We wouldn't have to open this issue if we had more rigor  before. We all make mistakes, let's get this fixed quickly.

**Comment by aashimawadhwa** [comment]
> @aashimawadhwa Please remember the tests. We wouldn't have to open this issue if we had more rigor before. We all make mistakes, let's get this fixed quickly.

this is a seprate issue for the rest of the pages , this issue #455 was for only signup and login page.

**Comment by palisadoes** [comment]
Are you still working on this? You are now assigned more than our limit of 2 issues. Please unassign yourself the ones that have the least priority for you.

**Comment by palisadoes** [comment]
Are you still working on this?

**Comment by noman2002** [comment]
Completed in #487

**Comment by noman2002** [comment]
Completed in #487
