### ISSUE TITLE
Screen and Functionality for Admins to View, Delete, Modify and Flag Comments/Posts

### ISSUE THREAD

**Issue by DangaRanga** [PalisadoesFoundation/talawa-admin#47]
**Describe the solution you'd like**
An admin should be able to view, modify, delete and flag comments or inappropriate posts from Talawa

**Describe alternatives you've considered**
This could also be automated using machine learning to check for inappropriate keywords as Talawa-Admin scales up

Parent Issue:
#49

**Comment by yasharth291** [comment]
hello
