### ISSUE TITLE
Removing DOMNesting Error

### ISSUE THREAD

**Issue by AjayMaheshwari23** [PalisadoesFoundation/talawa-admin#471]
**Bug**
In the organisation list page, DOMNesting is not done properly , I would like to remove this error.

**Expected behavior**
Error Free console

**Actual behavior**
validateDOMNesting(...) Error

**Screenshots**
<img width="1440" alt="Screenshot 2023-02-12 at 2 43 29 AM" src="https://user-images.githubusercontent.com/96301800/218283963-b8edd148-1c41-4c5a-9652-4ab1aaafbd5d.png">

Can I work on this issue ?

**Comment by AjayMaheshwari23** [comment]
Along with this , I will also remove the icon fetching Error.

**Comment by AjayMaheshwari23** [comment]
@noman2002 if you think removing error’s is something which should be fixed , then please approve this issue.

**Comment by noman2002** [comment]
@AjayMaheshwari23 Sure. Go ahead
