### ISSUE TITLE
Feature Request: Proper Testing of pagination in all List Views

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-admin#472]
**Is your feature request related to a problem? Please describe.**
We are displaying various lists throughout our UI, like `OrgList`, `UserList`, `AdminList` etc. A common problem across the tests of all these components is that there is no check on the fact if the pagination of the results is working correctly or not (i.e. the right cards are being displayed on the right page, and the results are displayed in the correct order)

**Describe the solution you'd like**
In all of these components/screens, we must add additional tests.
1. Use a library like `faker.js` to pro-grammatically generate large `MOCKS` (around 100-150 items).
2. Add tests that mock and test the following functionality:
- When the `itemsPerPage` is all, the count of the elements rendered must be equal to the length of the items mocked.
- For any two randomly chosen `itemsPerPage` values, we must choose two random `pageNumbers` and compare the data of the first and the last elements of the page to that of the MOCK. Random selection of the numbers must be done, to ensure the tests are non deterministic and thus offer more comprehensive testing.

**Approach to be followed (optional)**
- Migrate one such component according to the approach described. 
- Treat it as a parent issue, and open child issues for all components where such pagination components are being used.

**Additional context**
This would help to improve the quality of our testing, and not just the coverage.

**Comment by EshaanAgg** [comment]
I would like to work on this issue.

**Comment by noman2002** [comment]
@xoldyckk Please have look here.

**Comment by palisadoes** [comment]
@Kevoniat @Tajcore Please comment on this approach

**Comment by palisadoes** [comment]
@Tajcore @Kevoniat @xoldyckk please comment on this approach

**Comment by EshaanAgg** [comment]
@xoldyckk My bad. It's called 'rowsPerPage`.

**Comment by xoldyckk** [comment]
@EshaanAgg Seems like a good thing to test.

**Comment by EshaanAgg** [comment]
I couldn't find any such limit in the code anywhere. The reason for choosing 150 items was to ensure that approximately 8-10 pages of data are generated so that the random selection of pages and items is from a big pool of possible values. 

Should I start working on this?

**Comment by xoldyckk** [comment]
@EshaanAgg 150 seems redundant. Also it'll slow down the tests. You don't need to test 10-20 pages. If it works for at least 3 pages it should work for any more number of pages. 

Yeah you can start working on it.

**Comment by EshaanAgg** [comment]
Sure! I'll try to make a PR to show my testing strategy in a couple of days. Having my exams right now, so that's why I might be a little inactive :(

**Comment by palisadoes** [comment]
@EshaanAgg are you still working in this?

**Comment by EshaanAgg** [comment]
I am working on it, but am stuck at a step, about which I posted here (https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1677082330809849)

Still haven't been able to debug it. I will un-assign myself in the meantime so that anyone can take it and hopefully help debug the same.

**Comment by lata-11** [comment]
Hey! I want to work on this issue. Please assign me.

**Comment by Sheguun** [comment]
@palisadoes I'd like to be assigned this issue.

**Comment by Sheguun** [comment]
Thanks, @palisadoes  I'll start working on it immediately.

**Comment by Sheguun** [comment]
![IMG-20230318-WA0000](https://user-images.githubusercontent.com/114509848/226095723-11783b33-608c-421b-baf2-fa3b8938f05a.jpg)
@palisadoes Can I pass in optional props for the rowsPerPage?

**Comment by EshaanAgg** [comment]
You shouldn't be passing arguments to the page like this. They should be changed in the component itself by mocking the user's behaviour of choosing one option from the drop down.

**Comment by Sheguun** [comment]
Thanks @EshaanAgg

**Comment by Sheguun** [comment]
Hello @EshaanAgg @palisadoes 

I have a question please:
Is the user mock object supposed to return an array or a single object in the OrgList.test.tsx file?
![Screenshot_20230321-122658](https://user-images.githubusercontent.com/114509848/226594233-1fdff9af-848e-4ffe-b166-396f023c3b46.jpg)

**Comment by palisadoes** [comment]
Typically you want the mock to return what the code being tested expects
