### ISSUE TITLE
Convert Events Page into a Calender View

### ISSUE THREAD

**Issue by anwersayeed** [PalisadoesFoundation/talawa-admin#478]
**Is your feature request related to a problem? Please describe.**
The events are currently displayed in a tile view on the events page. We have a button that we can use to create events with, however they just show up as tiles. The creation and viewing of events over a calendar is what we actually desire. It will be easier to use and more convenient in this way.

**Describe the solution you'd like**
Events can be added to, viewed, edited, and deleted on a calendar. An event should have descriptions that include the title, start and conclusion times, the nature of the event, etc.

**Additional context**
You can take reference from the images below.
![3](https://user-images.githubusercontent.com/57287988/219852769-b7efe58a-22c6-4133-8aaf-34d897b902ca.PNG)
![4](https://user-images.githubusercontent.com/57287988/219852772-deab5517-ac15-499e-a64e-f2149d0a0507.PNG)

**Comment by anshgoyalevil** [comment]
I have my exams till 27 Feb, 2023, after that I can work upon this issue.

If we can wait till then, please assign it to me, else, please go ahead with fellow contributors.

**Comment by anwersayeed** [comment]
> I have my exams till 27 Feb, 2023, after that I can work upon this issue.
> 
> If we can wait till then, please assign it to me, else, please go ahead with fellow contributors.

@anshgoyalevil Because of your impending exams, I am unable to assign you this issue. I will wait for other contributors.

**Comment by anwersayeed** [comment]
We wish to make as few changes as possible to the current design. So, we require no new CSS or responsive design now, rather, work only on previously disabled or improperly implemented functionalities.

**Comment by aashimawadhwa** [comment]
I would like to take this issue @anwersayeed .

**Comment by noman2002** [comment]
@anwersayeed @palisadoes  We already have this for one of our gsoc ideas. Should we have this as an issue now ?

**Comment by palisadoes** [comment]
@noman2002 I understand your concern. This was a glaring omission in the original design and we're treating it as an exception.  We will be creating other issues to activate features that don't work. We want to create the basic functionality that is currently unavailable. There will be room for improvements in the calendar view for GSoC.

**Comment by anwersayeed** [comment]
@aashimawadhwa Any update?

**Comment by palisadoes** [comment]
@aashimawadhwa For clarity, we prefer the use of a calendaring system in our code and not a third party service.

**Comment by aashimawadhwa** [comment]
yes I have implemented a individual calendar system which is working perfectly. 
right now I am working on removing the event card list with the event tile of the calendar without changing much of the code. I may take a day or two to wrap this up. @palisadoes

**Comment by palisadoes** [comment]
This is going to be a major change. Please remember the tests, our code coverage automation now requires:
1. The overall test coverage level to go down
1. All the edited files in the PR have coverage legless equal or better than the overall threshold.

**Comment by aashimawadhwa** [comment]
[www_screencapture_com_2023-3-5_05_41.webm](https://user-images.githubusercontent.com/73706697/222934682-e7bffc00-481e-4dc0-971c-7300391780c0.webm)

This is the calendar view yet
I have to add 
    1. add event view in the calendar on dates
    2. make a few changes in the modal
    
    so should I open a new issue or continue in this PR? @palisadoes
