### ISSUE TITLE
Implement the ability to view information about people who are members to your organization.

### ISSUE THREAD

**Issue by anwersayeed** [PalisadoesFoundation/talawa-admin#479]
**Is your feature request related to a problem? Please describe.**
If you select the People menu option from the Navbar, you may get a complete list of all the members of your organization. The member's name displays on the list with a "Add Admin" button next to it. Nothing occurs if we click on any of the names in the list. Furthermore, there is no other method to view any potential further information on that person. 
Below is the image for the current functionality that needs below feature:-
![8](https://user-images.githubusercontent.com/57287988/219868559-95b71f46-1af4-4f98-a3ac-ca124599d585.PNG)

**Describe the solution you'd like**
When an admin clicks on a name in the member list, all of the information about that person should be displayed. Also, once we have drilled down to the person page, where all of his available information is visible, we want the "Add Admin" button to be available there.

**Approach to be followed (optional)**
Refer to the images below. First, we require the member list, and after selecting a member, we require information similar to that shown in the second image below.
![6](https://user-images.githubusercontent.com/57287988/219868629-15f47ab9-3b63-46cd-bf56-5568abd8102d.PNG)
![7](https://user-images.githubusercontent.com/57287988/219868632-bfe92df2-50cb-4c27-a76b-36b334e90547.PNG)

**Comment by rishav-jha-mech** [comment]
I can implement this feature, please assign it to me.

**Comment by anwersayeed** [comment]
> I can implement this feature, please assign it to me.

@rishav-jha-mech  We wish to make as few changes as possible to the current design. So, we require no new CSS or responsive design now, rather, work only on previously disabled or improperly implemented functionalities.

**Comment by noman2002** [comment]
@anwersayeed @palisadoes We already have this for one of our gsoc ideas. Should we have this as an issue now ?

**Comment by palisadoes** [comment]
This is a feature that currently doesn't work. The GSoC idea will be to improve the feature once activated.

**Comment by noman2002** [comment]
> This is a feature that currently doesn't work. The GSoC idea will be to improve the feature once activated.

Its alright.

**Comment by anwersayeed** [comment]
@rishav-jha-mech Any update?

**Comment by rishav-jha-mech** [comment]
Yes my last PR got merged yesterday night, now i will be opening a PR soon for the Profile Screen.

**Comment by rishav-jha-mech** [comment]
# Initial Designs

![Image 1](https://user-images.githubusercontent.com/76212518/222975020-23353ebd-ecef-41d9-84e5-13e9a3dfe704.png)
![Image 2](https://user-images.githubusercontent.com/76212518/222975015-2d3aba8b-c8eb-4125-9092-eb9654ccb0c4.png)


Open to suggestions about the text content layout or anything, the buttons on the left side don't work for now.

**Comment by palisadoes** [comment]
Please do the following:
1. Remove the organizations and events buttons
1. Submit a PR

Are any of the girls editable now? If not, we will need to create another issue to edit them. We'll need to figure out which ones will need editing and why. I don't want there to be able creep on this PR

**Comment by rishav-jha-mech** [comment]
Are we talking about the fields?, Okay I'll remove the organizations and events btn, but as you know its too easy to implement this, because the code is already present in the website to list and paginate the organizations and events. 

But this isn't the issue, and again it maybe for gsoc. I'll remove them for sure.

No, none of the fields are editable for now, if we are planning to edit the user details I'll be glad to work on it.

Right now I'm working on writing the tests for the files that i have changed. 💪

**Comment by anshgoyalevil** [comment]
@rishav-jha-mech @palisadoes 

I guess, having the ability to edit user details from this page should not be there. 
We have an other Settings page for this purpose.

**Comment by palisadoes** [comment]
The settings page is for the Admin. This page is for the members/users of the organization.

Hold on. @rishav-jha-mech Have you done work for the Admin profile page or the members/users page?

Now I understand why the events and organization buttons were there.

The intention was for this to be for the members / users page. If you have done it for the admin, then you could move this page there with edit options. 

We still need a view page for members/users

**Comment by anshgoyalevil** [comment]
@palisadoes 

We should rethink about why are we implementing this for users/members of the organization.

They cannot even login to the Talawa Admin Dashboard, then how would they edit their details from this page?

**Comment by palisadoes** [comment]
1. Please refer to the [demo page of BreezeCHM](https://www.breezechms.com/) to see why this is important.
2. [Event checkins for organization members](https://www.youtube.com/watch?v=TOxBoMVWaF4)
3. [Scheduling volunteers](https://www.youtube.com/watch?v=0NFze2bM5eE)
4. [Profile filtering for members](https://www.youtube.com/watch?v=uqPCLMYB8DA)

The GSoC ideas page mentions these videos and more. To have a good understanding of what we want to achieve you must do the research.

**Comment by rishav-jha-mech** [comment]
Thank y'all now i understand what i need to do.

**Comment by palisadoes** [comment]
Editing people needs to be on the organization page and accessible to both Admins and Super Admins

**Comment by rishav-jha-mech** [comment]
Yes for sure, can you please look this gif, and please let me know what i need to change. I thought i was assigned to make this screen.

![ezgif-2-f44dd59042](https://user-images.githubusercontent.com/76212518/223027918-4429b893-347a-4b08-8c29-45a8f3512a22.gif)

**Comment by palisadoes** [comment]
Thanks for the clarification. Yes, that's what we want. Please submit a PR.
