### ISSUE TITLE
Increase the code coverage for OrganizationPeople.tsx

### ISSUE THREAD

**Issue by beingnoble03** [PalisadoesFoundation/talawa-admin#480]
**Describe the bug**

- Increase the code coverage for `/screens/OrganizationPeople/OrganizationPeople.tsx` to 100%.
- Add required tests or alter the existing tests in the `/screens/OrganizationPeople/OrganizationPeople.test.tsx` file.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by beingnoble03** [comment]
This issue can only be assigned if #476 is merged.

**Comment by noman2002** [comment]
@beingnoble03 You have two other issues assigned. Unassigned this one to give everyone a chance.

**Comment by adi-uchiha** [comment]
Is this fixed ?
