### ISSUE TITLE
Increase the code coverage for OrgPost.tsx

### ISSUE THREAD

**Issue by beingnoble03** [PalisadoesFoundation/talawa-admin#481]
**Describe the bug**

- Increase the code coverage for `/screens/OrgPost/OrgPost.tsx` to 100%.
- Add required tests or alter the existing tests in the `/screens/OrgPost/OrgPost.test.tsx` file.

**Additional details**
Assignable only after #476 is merged.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by beingnoble03** [comment]
This issue can only be assigned if #476 is merged.

**Comment by AjayMaheshwari23** [comment]
#476 is merged so i would like to work on this issue

**Comment by palisadoes** [comment]
This was already assigned to @beingnoble03 earlier today. Please look for other issues on the queue

**Comment by beingnoble03** [comment]
@palisadoes @noman2002 this is being fixed by #489. Right? I think it's a duplicate for #271.
This issue was created after merging #476 but #271 is being fixed now. So, it should cover the updated `OrgPost.tsx`.

**Comment by palisadoes** [comment]
Closing
