### ISSUE TITLE
Increase the code coverage for OrganizationEvents.tsx

### ISSUE THREAD

**Issue by beingnoble03** [PalisadoesFoundation/talawa-admin#482]
**Describe the bug**

- Increase the code coverage for `/screens/OrganizationEvents/OrganizationEvents.tsx` to 100%.
- Add required tests or alter the existing tests in the `/screens/OrganizationEvents/OrganizationEvents.test.tsx` file.

**Additional details**
Assignable only after #476 is merged.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by beingnoble03** [comment]
This issue can only be assigned if #476 is merged.

**Comment by AjayMaheshwari23** [comment]
Can you assign it to me

**Comment by palisadoes** [comment]
This was already assigned to @beingnoble03 earlier today. Please look for other issues on the queue

**Comment by palisadoes** [comment]
@beingnoble03 This PR significantly changed the file under test. Please update your local repo.

- https://github.com/PalisadoesFoundation/talawa-admin/pull/537
