### ISSUE TITLE
Fix the Settings Page's header

### ISSUE THREAD

**Issue by tasneemkoushar** [PalisadoesFoundation/talawa-admin#486]
**Is your feature request related to a problem? Please describe.**
On the settings page, we have four options
+ Update your details.
+ Update Organizations.
+ Delete Organization.
+ See Request.

When We choose any of the above options, the Title at the top remains the same that is `Settings`. We want this title to reflect which option is chosen among the above four.
![Screenshot from 2023-02-19 14-46-34](https://user-images.githubusercontent.com/58592306/219939685-028b0953-f1e3-48e8-a33b-4c7774f00a92.png)

**Describe the solution you'd like**
Once We click on any of the options above. For example, Update Organization, then in place of `Settings ` `Update Organization `should appear as header

**Describe alternatives you've considered**
The contributor is free to pitch any other idea on this.

**Approach to be followed (optional)**
We want to minimize changes to the existing design. Hence no new CSS, no new responsive design, just the enabling of previously disabled or incorrectly implemented features

**Comment by anurag0006** [comment]
I think we can use a useState to dynamically rerender the title from "setting" to any other which we wish to be displayed there as soon as any of the buttons on the sidebar are clicked🤔
