### ISSUE TITLE
Image not visible on orglist page

### ISSUE THREAD

**Issue by VenomFate-619** [PalisadoesFoundation/talawa-admin#488]
**Describe the bug**
The image is not being displayed on the orgist page,despite the the image is selected while creating the org

I think it is happening because of image is not being sent in payload while creating an organization

**To Reproduce**

1. Create an organization with a display image

**Expected behaviour**

**Actual behaviour**
A clear and concise description of how the code performed w.r.t expectations.
![image](https://user-images.githubusercontent.com/67755128/220258327-a48cb851-04a9-4081-a000-031d197583fa.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by VenomFate-619** [comment]
I would like to fix this.
@anwersayeed @tasneemkoushar

**Comment by palisadoes** [comment]
Closing: Duplicate issue https://github.com/PalisadoesFoundation/talawa-admin/issues/375
