### ISSUE TITLE
Need for Additional Validation on data while creating organizations

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-admin#494]
**Describe the bug**
The current create organization form doesn't properly validate the data become the sending a mutation request. Some bugs that I have spotted:
1. The description field can't contain symbols like `?` , `'` and `;` (I can't contemplate a reason why we must filter them out)
![image](https://user-images.githubusercontent.com/96648934/220702902-8a1c343b-3e95-4b20-a879-f6a5b14a2477.png)
2. All the input fields do not clear trailing white space, which is not a good practice on the frontend. 
3. It is possible to create blank tags for organizations. 
![image](https://user-images.githubusercontent.com/96648934/220703517-03561ed3-2f9e-4999-a358-2791fa5c9aed.png)
4. Repeated tags can be created for an organization.
![image](https://user-images.githubusercontent.com/96648934/220703791-e3f1d2ea-722f-44e0-b9b5-0d375ad069e4.png)

**To Reproduce**
Open the Admin Portal and provide suitable inputs.

**Expected behavior**
These bugs should be caught before making the request to the backend, and we must notify the user to correct the input. 

**Actual behavior**
The code performs no such validations.

**Screenshots**
Attached above.

**Additional details**
NA

**Comment by EshaanAgg** [comment]
I want to work on this issue, and add relevant validation to this form.

**Comment by anshgoyalevil** [comment]
@EshaanAgg I excluded the ```?``` and other such symbols using the ```stringValidator.ts```

The code for it is 
```
export function isValidString(str: string, maxLength: number) {
  const pattern = /^[a-zA-Z0-9!@#$%^&*()_\-+. ,]+$/;
  const isFollowingPattern: boolean = pattern.test(str);
  const isLessThanMaxLength: boolean = str.length < maxLength;
  return {
    isFollowingPattern,
    isLessThanMaxLength,
  };
}
```
You may update the pattern in this function to allow ```?``` and other such characters.

**Comment by EshaanAgg** [comment]
@anshgoyalevil Yes, I traced it back to this as well. But is there a specific reason for filtering them out here?

**Comment by EshaanAgg** [comment]
Sure that makes sense. Other symbols being used are fairly commonly used, and thus it would make sense to allow them.

**Comment by palisadoes** [comment]
@EshaanAgg Please close your PR until you figure out right solution.

**Comment by EshaanAgg** [comment]
@palisadoes Can you please review #497, as it is independent from #494 and the changes proposed in it are just good UI practice in general? I have closed the later, and would continue it's discussion in this issue now.

**Comment by EshaanAgg** [comment]
@palisadoes You can close this issue for now, as other contributors have already begun to implement checks on the database level, and the `GraphQL-Scalars` has been integrated now with most of the breaking changes migrated.
