### ISSUE TITLE
Add Husky to improve developer experience

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-admin#495]
**Is your feature request related to a problem? Please describe.**
The user needs to run linting and formatting scripts before submitting a PR. This process can be automated with the help of Husky. 

**Describe the solution you'd like**
Use Husky to run the scripts that we are currently checking for in the PR Workflow files/

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
Refer [here](https://github.com/PalisadoesFoundation/talawa-api/pull/1030)

**Additional context**
This would help to unify the developer experience across all the Talawa repositories, and would new potential GSoC candidates to contribute code with greater ease.

**Comment by palisadoes** [comment]
Please ask people here for assignments and reviews:
- https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by arnab15** [comment]
@palisadoes Can I work on it I would like to set up husky as a pre-commit. hook so that linting can be forced in code based .
can i work on it??

**Comment by palisadoes** [comment]
@EshaanAgg did you still want to work on this?

**Comment by EshaanAgg** [comment]
Thanks for the chance @palisadoes. I would like to work on this issue.

**Comment by palisadoes** [comment]
@arnab15 There was a thread in another issue that triggered this issue to be created by @EshaanAgg. That's why he was contacted. Please take a look at other issues we have in the queue and thanks for wanting to participate.
