### ISSUE TITLE
Add filtering on the basis of tags for organizations

### ISSUE THREAD

**Issue by EshaanAgg** [PalisadoesFoundation/talawa-admin#496]
**Is your feature request related to a problem? Please describe.**
Currently, we are storing the tags for all the organizations with us, but there is no practical use of them anywhere in the Admin portal, other than displaying them on the Organization detail page. The main purpose of such tags is to mostly ease the job of filtering of objects, and thus even we must provide this functionality to the users.

**Describe the solution you'd like**
Implement a `Search by Tags` section under the `Search by Name` section in the `OrgList` view. The same would allow the users to choose one or more tags, and would filter the organizations displayed on the basis of the same.

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
1. Implement a function to list all the different tags across all the organizations being listed.
2. Implement a UI that allows the filtering on the basis on the above generated list.

**Additional context**
It would help in productivity and give meaning to the inclusion of tags in the model of `Organization`.

**Comment by EshaanAgg** [comment]
I would like to work on this issue.

**Comment by anikdhabal** [comment]
can i work on this ?

**Comment by EshaanAgg** [comment]
I was trying to think the best way to implement the same, and have reached the conclusion that implementing the same will require a few changes to the backend as well:
1. We must first modify `OrganizationsConnection` query on the backend to return the tags of each organization as well.
2. Modify the `SuperDashListCard` UI to show a small row of all the `tags` of the organization as well.
3. In the `OrgList` component, loop over all the organizations to get all the possible tags, and then implement the filtering logic.

What are your views on the same? @palisadoes @xoldyckk @anshgoyalevil @kb-0311

**Comment by xoldyckk** [comment]
> I was trying to think the best way to implement the same, and have reached the conclusion that implementing the same will require a few changes to the backend as well:
> 
> 1. We must first modify `OrganizationsConnection` query on the backend to return the tags of each organization as well.
> 2. Modify the `SuperDashListCard` UI to show a small row of all the `tags` of the organization as well.
> 3. In the `OrgList` component, loop over all the organizations to get all the possible tags, and then implement the filtering logic.
> 
> What are your views on the same? @palisadoes @xoldyckk @anshgoyalevil @kb-0311

First find out whether the tags should be pre-defined in the database(like a list of tag enums) or they'll be dynamic(dependent on what client inserts). Properly filtering organizations based on tags is only feasible when they are pre-defined(as an enum).

In any case implement a check in resolvers(or the mongoose/database schema) to check if the tags that client wants to add already exist for their organization. They should not be duplicated.

**Comment by xoldyckk** [comment]
> > I was trying to think the best way to implement the same, and have reached the conclusion that implementing the same will require a few changes to the backend as well:
> > 
> > 1. We must first modify `OrganizationsConnection` query on the backend to return the tags of each organization as well.
> > 2. Modify the `SuperDashListCard` UI to show a small row of all the `tags` of the organization as well.
> > 3. In the `OrgList` component, loop over all the organizations to get all the possible tags, and then implement the filtering logic.
> > 
> > What are your views on the same? @palisadoes @xoldyckk @anshgoyalevil @kb-0311
> 
> First find out whether the tags should be pre-defined in the database(like a list of tag enums) or they'll be dynamic(dependent on what client inserts). Properly filtering organizations based on tags is only feasible when they are pre-defined(as an enum).
> 
> In any case implement a check in resolvers(or the mongoose/database schema) to check if the tags that client wants to add already exist for their organization. They should not be duplicated.

Idk how they're supposed to be used on clients and every use case of theirs. So, can't really provide any input on that.

**Comment by EshaanAgg** [comment]
Tags currently have been implemented simply as an array of strings and have no model of their own. Thus there is no concept of "pre-defining" them as of now. 

As for the check for duplication of tags, I have implemented the same in the `Talawa-Admin` PR, where I am filtering out the tags to only contain the unique ones. Never the less, a functionality to handle duplicate tags for an organization should exist on the backend as well, and thus I'll try to update the resolvers for the same. 

But the question still remains, should we try to move tags to something more `enum` like, or we leave them as is, strings which the user can define to label the organizations? I personally would advocate for the later, as the same allows more flexibility. A fix set of tags (or a separate model to register tags, and then assign them to an organization) seems like an un-neccesary hassle that no one would be practically willing to undertake, just to categorise their organizations better.

**Comment by xoldyckk** [comment]
> Tags currently have been implemented simply as an array of strings and have no model of their own. Thus there is no concept of "pre-defining" them as of now.
> 
> As for the check for duplication of tags, I have implemented the same in the `Talawa-Admin` PR, where I am filtering out the tags to only contain the unique ones. Never the less, a functionality to handle duplicate tags for an organization should exist on the backend as well, and thus I'll try to update the resolvers for the same.
> 
> But the question still remains, should we try to move tags to something more `enum` like, or we leave them as is, strings which the user can define to label the organizations? I personally would advocate for the later, as the same allows more flexibility. A fix set of tags (or a separate model to register tags, and then assign them to an organization) seems like an un-neccesary hassle that no one would be practically willing to undertake, just to categorise their organizations better.

Yeah, I guess they shouldn't be enums.

**Comment by palisadoes** [comment]
As part of any long term design:

- Tags are to help with categorizations and filtering. 
- They will need to support people, and possibly events too. 

Consider this in the solution.

**Comment by EshaanAgg** [comment]
Okay. I'll try to brainstorm a bit about the design principles for the same, and post updates about my ideas here.

**Comment by xoldyckk** [comment]
@EshaanAgg How about providing both ways. Provide some common tags which are intrinsic to most organizations so they won't have to create their own tags. They can select tags from a pre defined list of tags and if they choose to add a custom tag they're free to. 

It'll make it more homogeneous because most organizations will probably choose from a pre-defined set of tags. There'll always be the option to be out of the ordinary and choose their own tag.

**Comment by EshaanAgg** [comment]
I like the idea of having some pre-defined tags that the users can opt into, as they might help the user gauge the reason and idea behind this feature. But implementation of the same would be a purely front-end thing, as we would have to alter the UI of the `Create Organization` dialog there and show some commonly used (or as default) tags to the users.

The same would make no difference in the backend as their implementation would remain the same, array of unique strings.

**Comment by xoldyckk** [comment]
> I like the idea of having some pre-defined tags that the users can opt into, as they might help the user gauge the reason and idea behind this feature. But implementation of the same would be a purely front-end thing, as we would have to alter the UI of the `Create Organization` dialog there and show some commonly used (or as default) tags to the users.
> 
> The same would make no difference in the backend as their implementation would remain the same, array of unique strings.

Yeah, that's what I meant.

**Comment by palisadoes** [comment]
> I like the idea of having some pre-defined tags that the users can opt into, as they might help the user gauge the reason and idea behind this feature. But implementation of the same would be a purely front-end thing, as we would have to alter the UI of the `Create Organization` dialog there and show some commonly used (or as default) tags to the users.
> 
> The same would make no difference in the backend as their implementation would remain the same, array of unique strings.

There will need to be some sort of categorization of tags as one set may not be meaningful for other categories.

- Organization: bakery, restaurant, supermarket
- Person: married, male, father
- Event: wedding, parade, concert

Showing wedding, parade, and concert tags when filtering for people won't make sense.

There will need to be some backend effort.

**Comment by xoldyckk** [comment]
> > I like the idea of having some pre-defined tags that the users can opt into, as they might help the user gauge the reason and idea behind this feature. But implementation of the same would be a purely front-end thing, as we would have to alter the UI of the `Create Organization` dialog there and show some commonly used (or as default) tags to the users.
> > The same would make no difference in the backend as their implementation would remain the same, array of unique strings.
> 
> There will need to be some sort of categorization of tags as one set may not be meaningful for other categories.
> 
> * Organization: bakery, restaurant, supermarket
> * Person: married, male, father
> * Event: wedding, parade, concert
> 
> Showing wedding, parade, and concert tags when filtering for people won't make sense.
> 
> There will need to be some backend effort.

The predefined tags will be front-end only. Since we can't force clients to use only the tags that server provides as they might need some custom tags. The server will only make sure that one tag cannot be added more than once for a data object. 

Therefore, differentiation of tags for different categories can only be done on client side.

**Comment by EshaanAgg** [comment]
I agree with @xoldyckk.
I propose that we should start to rework the functionality of tags, first from the backend, making the following changes:
1. Update the mutations to check for only distinct tags, and the tags should be stored only as lowercase strings.
2. Update the `OrganizationsConnection` query to return all the tags of the organization as well. 

Once the above changes are implemented, we can make the following changes in the frontend:
1. Modify the `SuperDashListCard` UI to show a small row of all the tags of the organization as well.
2. In the `OrgList` component, loop over all the organizations to get all the possible tags, and then implement the filtering logic.
3. In the `Create Organization` component, add a neat UI to show some common pre-defined tags to the user.

Views?

**Comment by xoldyckk** [comment]
@EshaanAgg Shouldn't there also be a limit on min/max number of tags you can add to an object's tags list?

**Comment by palisadoes** [comment]
Before we get too far on this.

1. We are focusing on tags for organizations and the there is minimal use for this. 
1. The fact that it is currently available doesn't mean that it's required.
1. Most clubs (our whatever type of community organization they may be) will probably use Talawa for only one location, so categorization by tag won't be that necessary. Even with large clubs, the current mobile app's selection drawer allows you to easily select from a list.
1. There is far greater value in implementing this for members and possibly events.

Please take a look at the mobile app and see whether this feature is currently used at all, if not, our efforts should be directed elsewhere. 

I don't see the case for keeping this feature for organizations. It was interesting in the beginning, but in reality the need isn't strong at this stage.

The discussions we've had about implementing tags in general are valid, but we need to focus our efforts on implementing features that will probably be used.

**Comment by EshaanAgg** [comment]
@palisadoes I have never worked with the talawa mobile app before, so am completely clueless about it. Nevertheless, I will try to set it up once and try to figure out the same. If you can tag someone who actively works the `talawa` repository, their review in this case would be much more helpful.

**Comment by EshaanAgg** [comment]
Thanks @palisadoes! Will do so and post about it here.

**Comment by EshaanAgg** [comment]
@palisadoes There is no current UI in the talawa mobile that allows filtering on the basis of tags for members or events. 
Do you think there is merit in continuing the implementation of the same for organizations?

**Comment by palisadoes** [comment]
The purpose of tags is solely for the Admin panel to filter members in searches. It is not a mobile function as you have noted.

Please take a look at the demo website for Breeze CHM. It will give you a view into how they could be used.

**Comment by EshaanAgg** [comment]
Got it. 
@palisadoes @xoldyckk 
So should I get on with just implementing some basic checks on the organization tags, and then filtering on the basis of them? On approval, we can extend the same to members.

**Comment by palisadoes** [comment]
@EshaanAgg Please read my comments with more care. 

1. There is very limited need for tags for organizations. This feature was not fully evaluated when it was added. We thought there would be so many organizations per API instance that people would need tags to filter the ones they needed. That most likely won't happen in reality.
1. Tags are now only intended for people and possibly events where they will be much more useful.

We therefore must remove tag support for organizations.

Look at the Breeze demo to see the use cases as to why tags make more sense there.

**Comment by EshaanAgg** [comment]
Sorry for the misinterpretation on my part @palisadoes.
So as for this issue, should I change the same to `Removing tags for Organizations`, and try to implement the same for both the backend API as well as the Admin portal?

Then I can subsequently open a new issue, for introducing these tags for members (and possibly events), where we can have discussions about the architecture of the same.

**Comment by palisadoes** [comment]
Yes

1. Close this issue
1. Open a new one to remove tags functionality from organizations. 
     1. Refer to this issue
     2. Coordinate with people in API, Mobile and Admin to make sure they remove any related functionality. Create issues for these when appropriate.
1. When that is all complete. We need to add tags for users

**Comment by EshaanAgg** [comment]
Okay!
