### ISSUE TITLE
First Registered User not SUPERADMIN by Default

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#499]
**Describe the bug**

1. When you install Talawa-Admin. The first registered user is given default user privileges and not that of a Super Admin. This makes the UX unpleasant as they have to change the user settings to fix the inconsistency.
1. Making the first registered user automatically a Super Admin could create a security breech. There needs to be a configuration option where at least one Super Admin can be predefined, so that the are automatically elevated on registration

**To Reproduce**

1. Install Talawa-API with a new mongo instance
2. Install Talawa-Admin
3. Register a user in Talawa-Admin
4. The user is regular

**Expected behavior**
1. Making the first registered user automatically a Super Admin could create a security breech. There needs to be a configuration option where at least one Super Admin can be predefined, so that the are automatically elevated on registration
2. Document any mutation changes in our Talawa-Docs repository. DOCUMENTATION.md has the details.

**Actual behavior**
See above

**Screenshots**
N/A

**Additional details**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by BhuvaneshPatil** [comment]
I would like to explore on this issue. It will give a good idea about the repository

**Comment by BhuvaneshPatil** [comment]
My Idea for implementing this - 
- In dev env - 
- Upon creation of user, fetch all users in the DB.
- If there are none, we can make the user as super admin

**Comment by noman2002** [comment]
Please go ahead with you approach. @BhuvaneshPatil

**Comment by BhuvaneshPatil** [comment]
sure @noman2002

**Comment by BhuvaneshPatil** [comment]
@noman2002 

It's mentioned in the issue description to avoid the security breach. I am not sure how we can go ahead and implement it. 
Do we have any env variable for describing in which environment we are (dev/prod). If not we can create it and add the condition to for creating the first user as super user for local environment.

**Comment by palisadoes** [comment]
> My Idea for implementing this -
> 
>     * In dev env -
> 
>     * Upon creation of user, fetch all users in the DB.
> 
>     * If there are none, we can make the user as super admin
> 
> 
> Please provide any extra info if it's needed. @palisadoes

1. You need to consider security more carefully. 
1. Please re-read the second point of this issue.
1. Your solution does not take that requirement into account.

**Comment by palisadoes** [comment]
> @noman2002
> 
> It's mentioned in the issue description to avoid the security breach. I am not sure how we can go ahead and implement it. Do we have any env variable for describing in which environment we are (dev/prod). If not we can create it and add the condition to for creating the first user as super user for local environment.

1. You will need to create it if necessary.
1. Use the approaches that others have when accessing the configuration

**Comment by BhuvaneshPatil** [comment]
Hello @palisadoes,
I have found the solution, and the changes for that are need to be done in the talawa-api repo.
I will create a PR and then we can discuss if it will be a valid solution or not.

**Comment by palisadoes** [comment]
Please discuss what you plan to do here first

**Comment by BhuvaneshPatil** [comment]
Sure
My changes are in signUp mutation.
Once all checks are done and before creating user - 
We will create a object that will have two properties - `userType` and `adminApproved`. The value for these will be the default value that we assigned them in the `User` schema.
Then we check for two conditions - 
- If we are not in production environment, i.e. `if ( process.env.NODE_ENV !== "production" )`
- And there are no users in the DB, i.e.
`
const users = await User.find({});
if(users.length === 0 ){
...
}
`

If both of these conditions are satisfied, we change the properties to `"SUPERADMIN"` and `true`. 
we use those properties when creating the user.

**Comment by BhuvaneshPatil** [comment]
Here is link to comparison - https://github.com/PalisadoesFoundation/talawa-api/compare/develop...BhuvaneshPatil:talawa-api:first-user-super-user?expand=1

**Comment by palisadoes** [comment]
There are a couple things to consider:
1. We have moved to using constants for tracking environment variables. Please look to see how that has been done in the past. This is what I meant when I asked you to research this topic. Searching for `.env` in the repository should have revealed this.
1. This does not address the possibility of: 
     1. an attacker becoming a super admin between the time the API is installed and the person who installs the API manages to install the Talawa Admin and register. This the reason for the security breach concern. This was explained in the original text of the issue above.
`Making the first registered user automatically a Super Admin could create a security breech. There needs to be a configuration option where at least one Super Admin can be predefined, so that the are automatically elevated on registration`
     1.  the only super admin in the organization leaving. This means there would only be admins remaining and they cannot promote themselves to a super admin unless done so through the database. This is a skill the Talawa Admin user will most likely not have.

This is why the Talawa Admin of last resort, who at the very beginning would be the person installing the API, needs to be defined in the configuration file. If the Admin leaves, then someone with access to the configuration file would just change the super admin of last resort and be promoted. There would only be one super admin of last resort.

The super admin of last resort would then be able to promote other admins to super admins.

Please adjust your code to take these factors into consideration once more.

**Comment by palisadoes** [comment]
Automatically promoting the first user to register is a very bad idea.

**Comment by BhuvaneshPatil** [comment]
One possible solution can be - 
- Create the ENV variables for first SUPERADMIN. Keeping them in the ENV file will ensure they are secure.
- For local env - When user is setting up the repo, he will create his own credentials.
- Once the credentials are ready, the `listen()` function of our express app ( that is called when we deploy the app ), will connect to DB.
- After it's connected to DB, we will query the User model with userType = "SUPERADMIN", and if that's empty we will use the credentials in the ENV file to create the SUPERADMIN. So next time when someone starts the application there will already be a SUPERADMIN so no creation of SUPERADMIN.
- This ensures that no one can create super user between the API is setup and first user registers as mentioned above.

**Comment by palisadoes** [comment]
You haven't considered the other possibility I gave where the original super admin leaves before promoting anyone to a super admin.

How will you handle that case?

**Comment by BhuvaneshPatil** [comment]
While we are deleting the any user, we will check if it's SUPERADMIN. If it's then we will check if there is another superadmin present in the database. If yes then we will allow it to leave.

To handle leaving the superadmin without creating another admin a superadmin. There are two ways to handle this - 
- Either force to super admin to create any other super admin before deleting itself.
- Or we can promote the oldest joined ADMIN to SUPERADMIN. ( this can be the earliest created ADMIN ).
- There can be scenario where no ADMIN is present in DB. We need to take care of that.

**Comment by palisadoes** [comment]
What happens if the super admin leaves and the email used is their personal email so you can't recover it?

What is there is no deletion, they just disappear. They get laid off and people forget they are there super admin or they die.

This is something that needs to be configured on the API side, not Admin even though the user experience is in Admin.

Please consider the most likely scenarios. People don't always act the way developers want.

The only certain way is to configure a last resort admin, who in the beginning would be the first user, but the feature would be retired in other later scenarios.

Think of the long term. It needs to be fail safe.

We need to get this fixed soon.

**Comment by anshgoyalevil** [comment]
@BhuvaneshPatil

**Comment by BhuvaneshPatil** [comment]
Thank you so much @anshgoyalevil .

As last resort admin is same as that of the default super admin, we can follow the same approach as we are for default admin. What are your thoughts on the same?

**Comment by palisadoes** [comment]
Just like you have a recovery email address if you can't login to many websites with your regular email address we need something similar for Admin.

In our case, if no one can login as a Super Admin, there needs to be a way to make someone else a Super Admin without editing the database from the CLI. This is because the typical Talawa use will not have DBA skills.

The easiest way to do this is to configure an email address, in the configuration file, of at least one person who will always be Super Admin.

If the the last remaining Super Admin dies for example, this parameter could be modified to make someone else be automatically promoted to Super Admin.

We don't have a help desk to show people how to do this, so we will have to make sure it can be done easily and intuitively.

So in our case, if we add the very first super admin to this configuration property, they will automatically be promoted to Super Admin on registration, and they would always be the Super Admin of last resort until the next person is given that responsibility.

It would need to be a one time promotion or else if some other super admin demotes them, they will stay demoted.

**Comment by palisadoes** [comment]
Have you managed to make any progress on this? It's really affecting other developers

**Comment by anshgoyalevil** [comment]
@palisadoes Should I give it a try if @BhuvaneshPatil is okay with that?

**Comment by BhuvaneshPatil** [comment]
The first solution can be implemented and we can solve this issue with.
- We can add last login time field in the DB for user
- Setting up the cron jobs, they will check the last login time of super admin and send the automated emails if the last login time is old than decided time.

I am in process of thinking how its workflow will be

**Comment by palisadoes** [comment]
Guys, there is a very simple solution that I have described repeatedly.

Please have a PR submitted in the next day or I'll have to reassign it. 

The lack of this capability is hurting the community as I have stated before and the urgency is not being shown in the long duration of this discussion.

**Comment by BhuvaneshPatil** [comment]
Yes @palisadoes . I can understand your concern and I am working on it.

**Comment by BhuvaneshPatil** [comment]
I can understand your concern @palisadoes .

This is my solution - It need some security enhancement inputs from you.
I am assuming the configuration file is .env file.
- Creating two variables in .env file - One for primary admin and secondary for last resort admin (backup admin)
- There will be two functions - One for creating the primary admin and one for creating backup admin
- The function will take the email as input and check if it's same as of mentioned in the env file, upon its execution the user with email ( super admin ), will be promoted. This can be executed in the sign up request in the talawa-api.
- The second function will be the same, it will take an input email, if that is same that of last resort admin defined in the .env file, it will promote the user with given email to super admin.

The first function ( the one to promote user to primary admin can be called in sign up end point.
For second function, my proposal is to call it through two ways 
- In the primary super admin UI, there will be a page/button, on click it will hit the API and promote the user with email that of last resort admin to SUPER ADMIN
- Other way ( very insecure ) - To just execute the request in the browser, `<>/promote-last-resort-admin?email=lastresortadmin@email.com`, this will call the second function and check if the email in query is that of last resort admin in configuration file and then promote it.

Please provide your views on this idea.

cc - @xoldyckk @anshgoyalevil @noman2002

**Comment by anshgoyalevil** [comment]
@BhuvaneshPatil

The .env based solution looks good, since, environment variables can easily be changed inside any Node server.

> - In the primary super admin UI, there will be a page/button, on click it will hit the API and promote the user with email that of last resort admin to SUPER ADMIN

This shouldn't be implemented, as in case the Primary Super Admin dies, or becomes inactive, how will that button be accessed, which would further promote the last resort email.

> - Other way ( very insecure ) - To just execute the request in the browser, <>/promote-last-resort-admin?email=lastresortadmin@email.com, this will call the second function and check if the email in query is that of last resort admin in configuration file and then promote it.

Instead of this, you may just introduce a lastLogin field in the user model. Check for the lastLogin time to the current time using a cron job with 24 hours interval.

In case the user got inactive for a certain period, the backup email address will be made admin automatically.

--------------------
We have to keep the end user experience as simple as possible. Using the cron job based login seems valid here.

**Comment by BhuvaneshPatil** [comment]
Thank you for your suggestions @anshgoyalevil

**Comment by palisadoes** [comment]
@anshgoyalevil Thanks for the suggestions. They could be implemented as a second issue related to recovery after installation. This is needed also.

They also assume the last supper admin standing has configured a recovery email and that the address is valid. We need a fail safe solution that will work for both during and after installation which is what this issue will hopefully solve.

**Comment by palisadoes** [comment]
@BhuvaneshPatil Let's focus on solving the very first user in the system who will be the Super Admin.

1. The person who installs Talawa API will be assumed to be be Super Admin of last resort.
2. Put the Super Admin of last resort's email address in the `.env` file.
3. All users who register will be checked against the `.env` file. 
     1. If their registration is is successful **_AND_** 
     2. their email address is in the `.env` file, then they get promoted to Super Admin

That's all we need for this issue to be resolved. Please work on this quickly.

**Comment by BhuvaneshPatil** [comment]
I have created a function to promote user to super admin,
the diff is is here - 
https://github.com/PalisadoesFoundation/talawa-api/compare/develop...BhuvaneshPatil:talawa-api:first-user-default-super-admin?expand=1

**Comment by palisadoes** [comment]
Thanks. I know there has been a lot of back and forth, but it has been worth it. Please do the following:
1. Create an issue in Talawa-API for this. Reference this issue.
1. Submit a PR in Talawa-API for this new issue.
1. Update the INSTALLATION.md file for Talawa-API with this new information
1. Ensure the tests pass with a randomly generated email address
1. Close this issue

**Comment by anshgoyalevil** [comment]
@BhuvaneshPatil 

I saw you are creating 2 API calls for the signUp.

This can be done using a single call, and can further improve the performance.

- Just check for the env email, like you already did, and add the updated args in the createUser mutation only.

**Comment by BhuvaneshPatil** [comment]
I understand your concern @anshgoyalevil , there are two reasons I think this approach is better - 
- The number of super admins will be far lesser compared to regular users, so there is no harm calling the API twice regarding the performance
- And having the promote functionality in separate function is useful - the sign up function's use is to create a entry in the database, it will be overhead and makes it bulky if we add promotion logic into it. It can be used in some other part of the application as well.

**Comment by anshgoyalevil** [comment]
@BhuvaneshPatil Agreed! Proceed with your existing solution.

**Comment by faraz16iqbal** [comment]
@anshgoyalevil has this been resolved yet? If not, can I work on this?

**Comment by anshgoyalevil** [comment]
@faraz16iqbal 

Thanks for contributing to Talawa projects. 

This issue is already assigned to @BhuvaneshPatil 

Please check other issues across different Talawa Repos, and select the ones which are not assigned to anyone
