### ISSUE TITLE
Translation is not working for Plugin tab

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#504]
**Describe the bug**
Many entities in the plugin section are not translating during the toggle in languages.
 

**To Reproduce**

1. run talawa API locally
2. run talawa admin in your local machine
3.  login to the admin
4.  from the dashboard of the organization, reach plugins
5.  see the issue.

**Expected behavior**
All the translations should work properly in the plugin section

**Actual behavior**
some text is not being translated.

**Screenshots**

![Screenshot 2023-02-25 at 3 02 37 AM (2)](https://user-images.githubusercontent.com/73706697/221297760-a3a85ac8-4fe8-40fa-85da-6a9a84cfb525.png)
![Screenshot 2023-02-25 at 3 02 48 AM (2)](https://user-images.githubusercontent.com/73706697/221297885-63cfc695-8a46-45f8-8b64-84bce7ae2193.png)

**Additional details**
That might be some hard-coded text which needs to be passed from the predefined translation function.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
This is going to be a major change. Please remember the tests, our code coverage automation now requires:
1. The overall test coverage level to go down
1. All the edited files in the PR have coverage legless equal or better than the overall threshold.
