### ISSUE TITLE
Add content upload support to create Org mutation

### ISSUE THREAD

**Issue by kb-0311** [PalisadoesFoundation/talawa-admin#505]
**Describe the bug**
Related to 
https://github.com/PalisadoesFoundation/talawa-api/pull/1086

After the above PR is merged, the content upload will be functional for the client apps for development purposes. 

adding this functionality for the create Org thing will be a good starting point.
**To Reproduce**

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kb-0311** [comment]
pls assign this to me.

**Comment by rishav-jha-mech** [comment]
This is a duplicate issue #477

**Comment by kb-0311** [comment]
@rishav-jha-mech 

1. #477 deals with not being able to access the uploaded image. This issue and my PR deals with the content upload support . Difference.
2. Although,  check this out for fixing that issue https://github.com/PalisadoesFoundation/talawa-admin/pull/506/files#diff-be2c18a48bc6d2ef7ab0a4daa4a3030ff1ebcea914ea3ff8a755a3cc86e2f491 This is an unoptimal approach and I will be uncommiting that particular file because the URL should not be hardcoded like that. Go ahead and make sure that the URL would be dynamic.

**Comment by kb-0311** [comment]
@rishav-jha-mech I already had the code for this PR ready even before I opened an issue for this to test my backend code. But I had not implemented this in other places where we might need upload support like events , projects, users in the admin portal etc.

 I was thinking about opening a PR for that too tomorrow but as I basically submitted a PR with conflicting interest with yours would you like to work on that issue instead?

**Comment by rishav-jha-mech** [comment]
The issue was to "Choose the Display image for an Organisation", not to display it or not being able to access the uploaded image. I have already commented on that issue about the image upload functionality and i was told to wait for the backend to be functional (which is probably working right now thanks to you 🎉).

**Comment by rishav-jha-mech** [comment]
> @rishav-jha-mech I already had the code for this PR ready even before I opened an issue for this to test my backend code. But I had not implemented this in other places where we might need upload support like events , projects, users in the admin portal etc.
> 
> I was thinking about opening a PR for that too tomorrow but as I basically submitted a PR with conflicting interest with yours would you like to work on that issue instead?

I was thinking about doing the same but for that the backend needed to be functional. Now that it is functional i am open to work on that as well.

**Comment by kb-0311** [comment]
@rishav-jha-mech alright then would you be open to exchange those two issues?

**Comment by rishav-jha-mech** [comment]
> @rishav-jha-mech alright then would you be open to exchange those two issues?
> 
> Because I also did make your job easier with this PR which will act as a reference point for you.

Thanks for that, but i have already wrote the code for that one week ago.

I think we should stick to the contributing guidelines, and let `Palisadoes decide for us`  🙌.

**Comment by kb-0311** [comment]
@rishav-jha-mech I would guess peter would be busy rn with a lot of other stuff in the all the three projects. Go ahead ,submit your PR for 477, closing this issue and the PR attached.

**Comment by rishav-jha-mech** [comment]
> @rishav-jha-mech I would guess peter would be busy rn with a lot of other stuff in the all the three projects. Go ahead ,submit your PR for 477, closing this issue and the PR attached.

Thank you for being so considerate, and also for fixing the image upload issue in the backend, more power to you keep it up 💪.
