### ISSUE TITLE
Users that are not member of the organisation should not be fetched for any manage organisation feature

### ISSUE THREAD

**Issue by Manoramsharma** [PalisadoesFoundation/talawa-admin#507]
**Is your feature request related to a problem? Please describe.**
 In block/unblock page of the Talawa-admin portal, there are users that are no longer the part of the organisation but still present on the page and there is block button present for them, which will surely give you error `'Member Not Found'`. Need to change the query for fetching the member information in block/unblock, remove member features so that only the members belonging to organisations can have the option for those features.
**Describe the solution you'd like**
According to me in there is` USER_LIST` query in block/unblock page that fetches the user data as whole irrespective of the user being member of the organisation that is need to be replaced `MEMBER_LIST` query that fetches the members for the organisation wherever this kind of issue is there.
Change is required in this code block of block/unblock page
```
const {
    data,
    loading: spammers_loading,
    error,
    refetch,
  } = useQuery(USER_LIST);
```
**Describe alternatives you've considered**
Any alternative approach suggestion is welcomed.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Manoramsharma** [comment]
Hi @palisadoes, kindly assign the issue to me as it will affect the other feature issues that I am working on.

**Comment by palisadoes** [comment]
@Manoramsharma 

- Are you still working on this? 
- I see that you said that other issues need to be created to support this issue. Have they been created? If not, please do so. 
- We may also assign others to those issues to get quicker rectification.

**Comment by Manoramsharma** [comment]
@palisadoes the same issue where the users which were not the members are fetched I'm organisation people page with block/unblock page but it was resolved already for people page, so there is no need to create any related issue also I will be submitting a PR for this in a day. I was busy with my mid-semester exams.

**Comment by Manoramsharma** [comment]
Regarding this issue https://github.com/PalisadoesFoundation/talawa-admin/issues/507 
I implemented the approach discussed got MEMBERS_LIST array then filtered out the ids that corresponds to the current orgId then after modified the USER_LIST according to the ids that we filtered earlier and got the desired output (i.e only the members are fetched for the manage organization functionality)
<img width="1440" alt="Screenshot 2023-03-10 at 1 49 26 AM" src="https://user-images.githubusercontent.com/84619980/224148402-74bd66e4-5a51-4709-8de6-ca8fe72614cb.png">
But these changes are generating a test to fail in corresponding test file , i am not able to figure out why this is happening.
<img width="618" alt="Screenshot 2023-03-10 at 1 57 22 AM" src="https://user-images.githubusercontent.com/84619980/224148936-d157bbfa-2e02-43c1-9b87-2591dce9ff24.png">
<img width="631" alt="Screenshot 2023-03-10 at 1 56 45 AM" src="https://user-images.githubusercontent.com/84619980/224149020-e4dbf54c-f4c7-48ab-aef9-529ff99bcd7e.png">

**Comment by Manoramsharma** [comment]
@DMills27 @noman2002 @xoldyckk @anwersayeed I am not able to figure out the corresponding change in test file?
