### ISSUE TITLE
Bug: Wrong error message on signup page

### ISSUE THREAD

**Issue by Ayush0Chaudhary** [PalisadoesFoundation/talawa-admin#514]
**Describe the bug**
It gives a wrong error message of wrong captcha

**To Reproduce**

1. Keep the talawa-api down
2. try to register

**Expected behavior**
should give appropriate error msg

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![Screenshot from 2023-02-27 06-16-57](https://user-images.githubusercontent.com/95746190/221449135-0cbe6217-1f1e-4c4f-8d9a-8b39edf2c6e1.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Ayush0Chaudhary** [comment]
@palisadoes @noman2002  can i work on this?

**Comment by Cioppolo14** [comment]
@Ayush0Chaudhary You currently have 2 issues assigned to you.  When one is completed, let me know and we can look at a new assignment.

**Comment by anurag0006** [comment]
@Ayush0Chaudhary , i was also getting the same error earlier...As @EshaanAgg has made 2 PRs to both talawa-admin and talawa-api, the he also added some dependencies to the pakage.json...and maybe the node modules for those were pakages were not in our local system so we were getting some errors....I recommend you to reinstall the node modules and the error should go away(also some one correct me if am wrong)

**Comment by Ammy198488** [comment]
I would like to work on this

**Comment by Ammy198488** [comment]
I would like to work on this.

**Comment by siddhi-244** [comment]
Hello. I am an outreachy participant, can I work on this ?

**Comment by anurag0006** [comment]
@siddhi-244 , @Ammy198488  this was a minor issue that had occured but has already been sorted...So this isn't an issue anymore.

**Comment by anurag0006** [comment]
@noman2002 , @palisadoes  please close this issue as its still confusing people whereas it wasn't a required issue and bug has already been sorted
