### ISSUE TITLE
Image not showing up in the Header of Organization

### ISSUE THREAD

**Issue by rishav-jha-mech** [PalisadoesFoundation/talawa-admin#528]
**Describe the bug**
Image not showing up in the Header of Organization

**To Reproduce**

1. Make an organization while adding a picture
2. Go to that organisation dashboard and see the top-left corner of the screen

**Expected behavior**
Image should be there

**Actual behavior**
Its not there

**Screenshots**
![Image not shown](https://user-images.githubusercontent.com/76212518/222948872-677fecf6-0a75-4b78-aae7-8a53917d9698.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by rishav-jha-mech** [comment]
Please assign this issue to me.

**Comment by aashimawadhwa** [comment]
I wanted to ask what is the use of having organization picture on the left side and the same picture on the top left, they seem repetitive to me .

**Comment by palisadoes** [comment]
1. It is repetitive on this page.
2. The original issue was to add the image in the header as on other screens there is no way of easily knowing which organization you are working on.
3. The Admin layout redesign GSoC idea will need to take this into consideration.

**Comment by rishav-jha-mech** [comment]
@aashimawadhwa maybe removing it will also work, but for now its looking ugly. Maybe we should remove this icon in the header then but leave the name of the organization as is, coz the placeholder image is not properly sized.

**Comment by palisadoes** [comment]
Please leave it for now. We are trying to get the basic functionality working. The streaming of the design can be a part of GSoC. This will most likely remain as a design element and it will be good for us to have it operational even at the most basic level

**Comment by rishav-jha-mech** [comment]
Yes i agree, but it not just about the design, here there is something that should work. Even if it does not looks that good.

**Comment by palisadoes** [comment]
@rishav-jha-mech do you want to be assigned this issue?

**Comment by rishav-jha-mech** [comment]
Yes sure please assign it to me.
