### ISSUE TITLE
Add the Ability to Disable Users

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#53]
**Is your feature request related to a problem? Please describe.**

There will be times when we will need to disable users, for example:

1. Breeches of codes of conduct
2. Users leave the organization's membership

**Describe the solution you'd like**

1. There must be screen for disabling users for an organization
2. The API must only accept this disabling from `talawa-admin`
3. The API must immediately log out the user as soon as `talawa-admin` disables them

**Describe alternatives you've considered**

See above

**Approach to be followed (optional)**

See above

**Additional context**

Related Issue: https://github.com/PalisadoesFoundation/talawa-api/issues/256

**Comment by yasharth291** [comment]
Hello @palisadoes sir this will come under admin ability to delete user so i think this is a duplicate issue

**Comment by palisadoes** [comment]
@yasharth291  I forgot, however in hindsight, we may not want to delete a user. Just disable them. Deleted users will have historical data that twe will want to maintain, chats, calendar entries, uploads share with others etc. If we delete them, where does the deletion stop? Disabling is a simpler solution

**Comment by palisadoes** [comment]
@yasharth291 please work with @DangaRanga on the best solution. I think disabling is more prudent.

**Comment by yasharth291** [comment]
yeah sir i will add both options to delete and disable
