### ISSUE TITLE
Update Your Details Page on Settings Page is not working as it should be

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa-admin#530]
**Is your feature request related to a problem? Please describe.**
Settings page has a lot of bugs, which makes its functionality useless.

![image](https://user-images.githubusercontent.com/94157520/222953116-e6193abc-9d5e-4099-9f79-3a33d15e950a.png)
.
Actual: In this page, we have to fill a new email every time we want to update something. A user may not want to update their email address while updating their name.

Expected: Every field should have the capability to update standalone, just like most of the online applications. Also, the password field should have a separate page for it to be updated. A user may not want to update the password.
Additionally, updating the password must include ```current password``` ```new password``` and ```confirm new password``` fields.

**Describe the solution you'd like**
There should be a different page to update user details and each mutation can be created standalone. 
There should be a different update password page, with the above fields.

**Describe alternatives you've considered**
There is no alternative solution, as we want to make the admin panel's existing feature to be working, and this page is not working as expected.

**Approach to be followed (optional)**

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by anshgoyalevil** [comment]
@palisadoes Please assign this issue to me.

**Comment by zitodev** [comment]
Please assign this issue to me

**Comment by lata-11** [comment]
Hey! I am interested in working on this issue. Please assign me.

**Comment by palisadoes** [comment]
If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.
