### ISSUE TITLE
No Super Admin Dashboard Error When Organizations Absent

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#533]
**Describe the bug**

There is no notification in the Super Admin dashboard that there are no created organizations. This has consequences.

1. Mobile App users have no organizations to select in their login screen (see screenshot). This is a poor user experience. The mobile side messaging is being addressed by this issue but we need something in Talawa-Admin too.
    1.  https://github.com/PalisadoesFoundation/talawa/issues/1612
1. The Super Admin is unaware that this very important action needs to be taken.

**To Reproduce**

1. Login as a Super Admin
3. No error message when there are no created organizations

**Expected behavior**

1. A very visible and clear error message must be visible on login that this needs to be done.
1. Some less intrusive message or notification on all super admin screens until this action is taken.
1. Tests created so that this doesn't occur again

**Actual behavior**

1. No message

**Screenshots**

![image](https://user-images.githubusercontent.com/16875803/222994441-7307131f-ae1c-4433-a00b-b79241f18d23.png)

**Additional details**

- None

**Potential internship candidates**

Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by prathamesh-mutkure** [comment]
Hi @palisadoes, can I take up this issue?

**Comment by KrutikaBhatt** [comment]
Hey, can I work on this issue?

**Comment by prathamesh-mutkure** [comment]
Hi @palisadoes, what will be the nature of this error/warning message?

There are two approaches -

- A more intrusive message on login, this will be a persistent text message on `/orglist` page
- A less intrusive message on other screens in form of a toast message (might use a library for this)

Is this a good approach? Feedback welcomed.

cc: @noman2002 @xoldyckk @asmitsirohi @anwersayeed

**Comment by palisadoes** [comment]
1. We need a persistent message after login on the Super Admin, pages. Adding this to the Admin pages don't make sense as there will be no organization.
1. We'll need a noticeable message on login. 

Minimize the need for new libraries.

**Comment by prathamesh-mutkure** [comment]
Hi @palisadoes, this is how `OrgList` page looks like on login if there are no organizations, is this okay?

Should this be added to the `Roles` and `Requests` pages as well (in form of a toast message)?

<img width="1858" alt="Screenshot 2023-03-17 at 3 07 28 AM" src="https://user-images.githubusercontent.com/28570857/225758226-493e30ab-926a-4477-89dd-cb753af41a41.png">

**Comment by palisadoes** [comment]
The requirement was to have a message on all super admin screens. Please create a PR with screen shots on any other appropriate pages.
