### ISSUE TITLE
Rerouting should be done throguh router

### ISSUE THREAD

**Issue by VenomFate-619** [PalisadoesFoundation/talawa-admin#540]
**Describe the bug**
Rerouting should be done through the router package instead of a window.
Doing through the window will take time to get to that page and reset the state of react query.

**To Reproduce**
Steps to reproduce the behaviour:

1. Login
2. go to the orglist page
3. click the manage button
4. the page will reload and go there

**Expected behaviour**

https://user-images.githubusercontent.com/67755128/223178937-af842166-5db3-4075-9421-0aa2ddb38a0c.mp4

visit this [link](https://drive.google.com/file/d/1wCxHhXYLEDpj7Szbfx_Hg1B2t9j3c-3O/view?usp=share_link) if the above video not working

**Actual behaviour**
A clear and concise description of how the code performed w.r.t expectations.

https://user-images.githubusercontent.com/67755128/223178089-d91bcbfe-4d6e-477d-b25a-26d76e62f982.mp4

visit this link if the above video is not working

https://drive.google.com/file/d/12gyXcOKyk-vDNRhrq39Jtrp_BNDwYkmB/view?usp=share_link

**Additional details**

Do click on roles , request navlink and see the difference

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by siddhi-244** [comment]
Would like to work on this ! But the videos you uploaded are not playing. I mean I don't know if there is any issue from my side !

**Comment by VenomFate-619** [comment]
I like to fix this.
I think it would be better to make that manage text as a link (react router link)

**Comment by VenomFate-619** [comment]
> Would like to work on this ! But the videos you uploaded are not playing. I mean I don't know if there is any issue from my side !

it is working on my side , do recheck it.

**Comment by anshgoyalevil** [comment]
@siddhi-244 

You may try changing the DNS server of your browser to Cloudflare from setting. (Search DNS in settings)

**Comment by palisadoes** [comment]
@siddhi-244 You may have a browser ad blocker or cookie filter extension that is incompatible with playing the video. Try a private session or another browser.

**Comment by pratik9333** [comment]
hey @VenomFate-619, feel free to lmk if you need my help!
