### ISSUE TITLE
Bug in Posts section:  Entered value must be a valid string format

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#542]
**Describe the bug**
Whenever you write to write the description of a post, there might be a possibility that you use words which contain  's...This should be allowed but we receive an error saying entered string is not valid...

For eg: "I am Anurag's friend" is not a valid string as it containes  's .
**To Reproduce**

1.Log into talawa-admin
2.Try to create a new post
3.write a description which contains a word with  's
4.Try to create the post.

**Expected behavior**
's should be permissbile as it is part english langauge and should not be treated as special letters 

**Actual behavior**
getting errors on creating such string with 's.

**Screenshots**

![Screenshot from 2023-03-07 14-00-10](https://user-images.githubusercontent.com/107215525/223403220-621963b1-953e-433a-a675-4315766d39c4.png)

**Comment by anshgoyalevil** [comment]
@anurag0006 

Please pull the latest API repo to your local machine. This issue was resolved a few hours ago.

**Comment by anurag0006** [comment]
Ok thankyou i thought it hasnt been resolved yet!
