### ISSUE TITLE
Bug: the rows per page component is repeated twice

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#544]
**Describe the bug**
The rows per page component at the bottom of the application is repeated twice for the OrgPost page

**To Reproduce**

1.log into talawa-admin
2.create an Org and then click on manage
3.Go to posts section from the navbar
4.you will see the bug

**Expected behavior**
There should be single rows per page section
**Actual behavior**
There is duplicate component which is not required
**Screenshots**
![image](https://user-images.githubusercontent.com/107215525/223415610-5e004660-0554-4c90-b3b0-683265bbc68d.png)

**Comment by pratik9333** [comment]
Can I work on this issue?

**Comment by anurag0006** [comment]
I found the bug and i am already here to solve this issue...Can this issue be please assigned to me

**Comment by anurag0006** [comment]
@pratik9333  i was writing comment for this issue and you commented first...Even i wanted this issue to be solved by a newcomer...when you commented i felt bad and changed my comment...i shouldn't have done that, sorry for that...best of luck for issue

**Comment by pratik9333** [comment]
@anurag0006 no worries!

**Comment by pratik9333** [comment]
@palisadoes thanks for assigning me!
