### ISSUE TITLE
Feature Request: Creating a separate page for each Post when clicked on the post

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#545]
**Is your feature request related to a problem? Please describe.**
We can write an much as content in the description of a post and the whole description is rendered in that post in the posts sections which makes things look uneven

**Describe the solution you'd like**
I suggest to reduce the length of description to 100 letters (or any other limit) and then render it on the main page where all the posts will be there...
Then if a user wants to see the whole post, he can click on that post and a new page with whole post will appear.

The image clears all:

![Screenshot from 2023-03-07 17-24-59](https://user-images.githubusercontent.com/107215525/223417895-e7fb87ae-3315-4fd7-904c-ae165d92df90.png)

and i think it should be something like this where the string is shortened to 100 letters followed by '...' and then if the user wants to see the whole post, he can click on the post:
![Screenshot from 2023-03-07 17-22-19](https://user-images.githubusercontent.com/107215525/223418122-b0488134-ff40-4d48-bbff-f841714817c3.png)

This will make all the postCards to be of the same size and the improve the UI
**Describe alternatives you've considered**
Or we can skip making a new page and instead add a button of readmore at the end after shortening the string and if the user clicks on it, the post should expand.

**Comment by anurag0006** [comment]
I can work on this...Please assign it to me

**Comment by anurag0006** [comment]
@xoldyckk @palisadoes should i create a separate new page which should open when clicked on a post or try to make the same better...Which way should i proceed?

**Comment by anurag0006** [comment]
I worked on this..Have a look...I think this one is also looking fine...
[Screencast from 09-03-23 01:13:53 AM IST.webm](https://user-images.githubusercontent.com/107215525/223830108-948c34ac-7308-476f-9cb9-ad1edf96a0c4.webm)



Alternatively Approach:
 we can also make a separate page..Whenever someone clicks on a post from the post section, the whole post will load in a new page

**Comment by palisadoes** [comment]
- Yes go ahead.
- The layout will probably change with the redesign idea, and this will be good functionality to have.

**Comment by anurag0006** [comment]
@palisadoes  your comment got me a bit confused(english isn't my first language)...So should i create new page or just keep the things as shown in the upper video?

**Comment by palisadoes** [comment]
I also was not clear. The approach in the video is OK.
