### ISSUE TITLE
Convert Talawa-Admin to use the NPM package manager

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#546]
**Describe the bug**

1. Talawa-Admin currently uses Yarn v1. This is end of life.
1. We need to upgrade the package manager to a current product
1. For the sake of consistency, we want to use NPM like Talawa-API

This has caused problems with developing new code like this:

- https://github.com/PalisadoesFoundation/talawa-admin/issues/493#issuecomment-1458162310

**To Reproduce**

1. Update packages
2. Incompatibility errors

**Expected behavior**

When updating packages:

1. No deprecation warnings. 
1. No package incompatibilities 

**Actual behavior**

1. Deprecation warnings. 
1. Package incompatibilities 

**Screenshots**

![image](https://user-images.githubusercontent.com/16875803/223446234-1f1f0a49-2836-4489-a22b-da8e050e2c51.png)

**Additional details**

- See above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by anurag0006** [comment]
I would like to work on this issue

**Comment by Shofiya2003** [comment]
Can I take up this issue?

**Comment by akankshat05** [comment]
Hello @xoldyckk @Shofiya2003 If this issue is not getting addressed, I would like to be assigned and work on it. Thank you!

**Comment by Shofiya2003** [comment]
Yo!
I am working on it.

**Comment by Shofiya2003** [comment]
@palisadoes do I need to upgrade the yarn version too or just change the package manager to npm?

**Comment by Shofiya2003** [comment]
I plan to remove `yarn.lock` from the repository and generate a `package-lock.json` file.

**Comment by palisadoes** [comment]
1. Change the package manager.
1. Update the installation documentation to
    1. reference NPM
    2. have references to Yarn removed

**Comment by Shofiya2003** [comment]
@palisadoes
 Should I change the pre-commit file since it uses yarn ?

**Comment by Shofiya2003** [comment]
Also, I changed `.gitignore` to include `yarn.lock` file and removed `package-lock.json` from it

**Comment by palisadoes** [comment]
Do you mean these files?

1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml
1. https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/push.yml

They will need to be updated too. You can work with @xoldyckk on this. This is not an area of strength for me.

**Comment by xoldyckk** [comment]
> Also, I changed `.gitignore` to include `yarn.lock` file and removed `package-lock.json` from it

Don't remove them, if a user accidently installs packages with some other package manager the lock file just needs to be ignored. If you remove them the user will push lock files of other package managers along with their PRs.

Also, they can't make changes to package.json without those changes also reflecting in package-lock.json, so even if a different package manager is used to upgrade the packages or something, until and unless package-lock.json doesn't update along with it the PR won't be merged.

**Comment by Shofiya2003** [comment]
`CONTRIBUTING.md` , `INSTALLATION.md` , `PR_GUIDELINES.md` , `pull-requests.yml` , `push.yml` and post-merge hook file 
These are the files that need changes. I am working on it. Will refer to `talawa-api` repository since it uses npm in case I am stuck.
@xoldyckk

**Comment by Shofiya2003** [comment]
> > Also, I changed `.gitignore` to include `yarn.lock` file and removed `package-lock.json` from it
> 
> Include both yarn.lock and pnpm-lock.yaml, if a user accidently installs packages with some other package manager the lock file just needs to be ignored. This'll prevent users from pushing lock files of yarn and pnpm along with their PRs.
> 
> Also, they can't make changes to package.json without those changes also reflecting in package-lock.json, so even if a different package manager is used to upgrade the packages or something, until and unless package-lock.json doesn't update along with it the PR won't be merged.

Do I need to implement the condition mentioned in the second paragraph or does it already exist?

**Comment by Shofiya2003** [comment]
@palisadoes @xoldyckk 
Do we need [this part of the doucmentation](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/PR_GUIDELINES.md#linting-and-formatting) , since we are already using pre-commit hooks to run these commands [here](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.husky/pre-commit) ?

**Comment by Shofiya2003** [comment]
Also, [documentation related to yarn](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/INSTALLATION.md#setting-up-yarn) is no longer required. I think we should have a link to the getting started page of NPM, which has installation steps.

**Comment by xoldyckk** [comment]
> > > Also, I changed `.gitignore` to include `yarn.lock` file and removed `package-lock.json` from it
> > 
> > 
> > Include both yarn.lock and pnpm-lock.yaml, if a user accidently installs packages with some other package manager the lock file just needs to be ignored. This'll prevent users from pushing lock files of yarn and pnpm along with their PRs.
> > Also, they can't make changes to package.json without those changes also reflecting in package-lock.json, so even if a different package manager is used to upgrade the packages or something, until and unless package-lock.json doesn't update along with it the PR won't be merged.
> 
> Do I need to implement the condition mentioned in the second paragraph or does it already exist?

You don't need to implement some check for it, it'll need to be enforced while reviewing PRs.

**Comment by xoldyckk** [comment]
> Also, [documentation related to yarn](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/INSTALLATION.md#setting-up-yarn) is no longer required. I think we should have a link to the getting started page of NPM, which has installation steps.

Once migration to npm is successful, you may make the changes to docs.

**Comment by palisadoes** [comment]
@Shofiya2003 Are you still working on this? The PR has errors that need to be fixed.

**Comment by Shofiya2003** [comment]
@anurag0006 already raised a PR for this issue. 
It's not passing a test working on it. 
Thanks a ton

**Comment by anurag0006** [comment]
Sorry, @Shofiya2003  i thought u weren't hete

**Comment by Shofiya2003** [comment]
No worries @anurag0006

**Comment by palisadoes** [comment]
@Shofiya2003 the PR has been unchanged for almost 2 weeks. Do you plan to update it soon? There are others who can work on this.

**Comment by Shofiya2003** [comment]
@palisadoes all the changes have been made.
I am encountering this error https://github.com/reduxjs/react-redux/issues/1886 due to which one check in the CI pipeline fails. 
I have tried solutions but none seem to work.

**Comment by Shofiya2003** [comment]
This error occurs because multiple packages use different versions of `@types/react` . I tried using resolutions in npm but to no avail

**Comment by palisadoes** [comment]
Have you tried alternatives to those packages or upgrading them?

**Comment by Shofiya2003** [comment]
@palisadoes @xoldyckk  I tried
- Using `npm explain @types/react` to get different versions of `@types/react` being used. Upgraded the version of the package.
Used https://www.npmjs.com/package/npm-force-resolutions to install the package version mentioned in `resolution`. But same error occurs when `npm run typecheck` runs

Interestingly, these errors do not occur when we use `yarn.lock` to install the node modules. Trying to find a solution that works

**Comment by Shofiya2003** [comment]
I cannot consider alternative to this package since it is a peer dependency of many prominently used packages like `react-router-dom` and `redux` . It is not directly used.

**Comment by Shofiya2003** [comment]
@xoldyckk I am stuck on this issue. I have made all the necessary changes. Just the `npm run typecheck` test is not passing. 
Errors similar to this occur
```
error TS2786: 'Provider' cannot be used as a JSX component.
  Its instance type 'Provider<Action>'
```
I did use google and tried out solutions but to no avail
I need help. Thanks a ton

**Comment by xoldyckk** [comment]
@Shofiya2003 You see I too tried doing this locally on my system, and I wasn't able to. That's why I opened it as an issue. This is related to the outdated packages talawa-admin uses. Unless they are upgraded, the fix will probably be some hack, which will keep breaking from time to time.

**Comment by anshgoyalevil** [comment]
@xoldyckk @palisadoes 

I would like to work on this issue. It has been more than 2 weeks, @Shofiya2003 is trying to resolve this.

**Comment by palisadoes** [comment]
@Shofiya2003 I'm going to reassign this. This is a prerequisite for our planned summer projects that will kickoff soon.

**Comment by Shofiya2003** [comment]
No worries
