### ISSUE TITLE
Code Coverage: Create tests for BlockUser.tsx

### ISSUE THREAD

**Issue by aakarshee2000** [PalisadoesFoundation/talawa-admin#548]
**Describe the bug**
Code Coverage: Create tests for talawa-admin/src/screens/BlockUser/BlockUser.tsx.
[The current code coverage can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/blob/develop/src/screens/BlockUser/BlockUser.tsx)

**Expected behavior**
When complete this file must show 100% coverage when merged into the code base.

**Actual behavior**
The current coverage is "88.80%", which needs to be made 100%.

Kindly have a look at this issue and assign it to me. Thanks!

**Comment by palisadoes** [comment]
Unassigning due to inactivity others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by NjRhina** [comment]
can i please have this assigned to me
