### ISSUE TITLE
 Increase the code coverage for Calendar.tsx #482 

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#550]
**Describe the bug**

- Increase the code coverage for components/EventCalendar/Calendar.tsx to 100%.
- Initiate a test file in  components/EventCalendar and add required tests 

The current code coverage can be found here:
- https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/blob/develop/src/components/EventCalendar/Calendar.tsx

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Reopening. The code coverage is only 67%

**Comment by adi-uchiha** [comment]
I got it!
