### ISSUE TITLE
Updated user role doesn't change until page refresh

### ISSUE THREAD

**Issue by Sedoid** [PalisadoesFoundation/talawa-admin#551]
*** Describe the bug ***
User role remains the same even after updating the role

*** To Reproduce ***

1. Log in as a superadmin
2. Navigate to /roles
3. Change a users Role/User-Type
4. Navigate out of /roles
5. Navigate back to roles

*** Expected behavior ***
I expect the ui to display the updated users role

*** Actual behavior ***
What displays is rather a previous user role, and this behavior fixes only after refreshing the page

*** Solution ***
include refetch after the update mutation has occured

Pls assign this task to me

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@Sedoid do you want to be assigned this issue?

**Comment by Sedoid** [comment]
Yes, i can solve it
