### ISSUE TITLE
Register button to add a plugin doesn't work

### ISSUE THREAD

**Issue by chiinelo** [PalisadoesFoundation/talawa-admin#553]
**Describe the bug**
Register button to add a plugin doesn't work

**To Reproduce**

1. Log in as a superadmin
2. create an organization
3. navigate to manage
4. navigate to plugins
5. Select Plugin Store
6. Click add new 
7. fill in the information 
8. click the register button

**Expected behavior**
I expect the register button to be functional/ carry out an action

**Actual behavior**
The register button is dormant/unclickable 

**Additional details**
I am an outreach contributor and I  want to be assigned this issue

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Unassigning due to inactivity others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by NjRhina** [comment]
can i please have this issue assigned to me?

**Comment by NjRhina** [comment]
thank you

**Comment by anshgoyalevil** [comment]
@palisadoes @NjRhina 

The plugin system doesn't work, and there is no proper resolver to handle the plugins data.

Currently, we are taking the input of a plugin as if they are a blog post. There is a separate GSoC idea for this functionality.

**Comment by palisadoes** [comment]
True. Closing.
