### ISSUE TITLE
Inability to set user roles for specific organizations

### ISSUE THREAD

**Issue by Sedoid** [PalisadoesFoundation/talawa-admin#556]
**Describe the bug**
As a superadmin, i can change user roles but i found out that in order to assign a regular admin to a specific organisation, i had to manually update the organisation data directly from the database.

So, want i want to implement a feature for the superadmin to easily assign new members or admins to specific organisations

**To Reproduce**

1. Login as superadmin
2. navigate to /roles
3. You can only set the user roles 

**Expected behavior**
Setting of all roles (member, admin) should be associated with  specific organisations except for superadmin(as he gets that privilege by default)  .

**Actual behavior**
There is no option to select the organisation to associate with the new roles.

**Screenshots**
[Image of how roles are currently assigned](https://firebasestorage.googleapis.com/v0/b/sama-d512d.appspot.com/o/files%2FScreenshot%20from%202023-03-08%2002-16-02.png?alt=media&token=b066182f-d810-42e9-af02-982c61f50a46)

**Additional details**
Allowing for the option of selecting organisation will also lead to possibility of exploring the app as an admin and checking for issues there as well,

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sedoid** [comment]
Hello, ive been stuck on this issue cus i lack information and i couldnt get answers on slack.

Can i pose my questions here?

**Comment by Sedoid** [comment]
[A Link to a video of the admins current behaviour](https://thepalisadoes-dyb6419.slack.com/files/U04SN1ZDHK5/F04T4RWB1U4/kazam_screencast_00001.mp4 )

whenever i change the user roles, the server sends an error response, ...what condition am i to validate in order to make a proper server response

**Comment by palisadoes** [comment]
Take a look at the  API mutations folder for the files that might contain your answers. We are working on automating our document creation.

https://github.com/PalisadoesFoundation/talawa-api/tree/develop/src/resolvers/Mutation

**Comment by nishtha981** [comment]
Hey!
Can I work on this if the assignee hasn't provided any updates?

**Comment by palisadoes** [comment]
@Sedoid have you been able to make any progress?

**Comment by Sedoid** [comment]
Yes i could use an assistance....., a discussion was had on slack about the current structure of the roles, it got me anticipating an upcoming major change,

**Comment by palisadoes** [comment]
Please post the details of the issues you are facing here so that others can comment.

**Comment by Sedoid** [comment]
alright, issue is about  dynamically changing any users role, to either Admin,Super admin or regular user of an organisation

the available mutations i found to do this  are 
ADD_ADMIN_MUTATION  (createAdmin)
ADD_MEMBER_MUTATION  (AddNewMember)

**Comment by Sedoid** [comment]
When implementing the ADD_MEMEBER_MUTATION... 

![Screenshot from 2023-03-20 02-34-33](https://user-images.githubusercontent.com/24408690/226227036-cf98b757-e8b2-40b1-acf9-02cdb13159f4.png)

**Comment by palisadoes** [comment]
Thanks. Take a look at past closed  PRs that have been merged. Try contacting those persons who submitted them directly on slack. Link to this issue.

**Comment by Sedoid** [comment]
alright,  found one

https://github.com/PalisadoesFoundation/talawa-admin/pull/704

**Comment by nishtha981** [comment]
Can I also work on this issue if you need assistance?

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Maagztech** [comment]
@palisadoes please assign me this issues.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Sumitmaithani** [comment]
@palisadoes can I take this issue
