### ISSUE TITLE
Bug Report: Two Pagination Bars in OrgPost Page

### ISSUE THREAD

**Issue by Kodecheff** [PalisadoesFoundation/talawa-admin#557]
**Describe the bug**
In the org post page, the pagination bar is rendered twice.

**To Reproduce**

1. Login as SUPERADMIN
2. Click on _manage_ on any organization 
3. Click on _Posts_ on the navigation bar
4. Pagination bar is displayed twice

**Expected behavior**
Only on pagination bar should be displayed

**Actual behavior**
Two pagination bars are displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/48069624/223602344-23d4aee2-3695-4fc7-8646-c3f4acad60d4.png)

I have fixed the problem, should I make a PR yet?

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by noman2002** [comment]
@aashimawadhwa This issue was fixed earlier by you, Right ? Please confirm the status.

**Comment by aashimawadhwa** [comment]
It is fixed is the pull up to date for @Kodecheff ?

**Comment by Kodecheff** [comment]
Yes, I just pull the latest commits. Is it fixed on your end? @aashimawadhwa

**Comment by aashimawadhwa** [comment]
I will check giveme 1 hr and then I'll update @Kodecheff
