### ISSUE TITLE
Bug Report: OrgSettings page bugs

### ISSUE THREAD

**Issue by bigBrain1901** [PalisadoesFoundation/talawa-admin#559]
# Describe the Bug
The OrgSettings view has a few bugs. These bugs need both frontend and backend fixes.

- [ ] The delete Organization page is not configured to work correctly. The rendered page does not have a button to help with Organization deletion. Instead, it just has the text "Delete Org".
![image](https://user-images.githubusercontent.com/55971005/223614845-2d430dc1-a530-48f3-a301-55e92b1f69b9.png)

- [ ] The "See Request" page never shows any requests, even if they exist. This is because of a code fault described in the [thread here](https://github.com/PalisadoesFoundation/talawa-admin/issues/396#issuecomment-1457867253).
![image](https://user-images.githubusercontent.com/55971005/223615735-4b7ed1cf-876d-464d-8dc3-989ccd33caec.png)

- [ ] While fixing these issues, template refactoring for the file can be achieved. Adding the "Delete Organization" bugfix might involve the creation of a new translation key for that partial.

# Expected Behaviour
[screen-recorder-wed-mar-08-2023-09-38-53.webm](https://user-images.githubusercontent.com/55971005/223617476-f0945872-fa7e-4a51-9a97-8adc2668adbb.webm)

> Please feel free to add to this issue list. Will fix them in GH-549.

**Comment by aashimawadhwa** [comment]
we already have a delete organization button in the dashboard this would be a redundant feature which i think we do no need, we can simply remove the delete organization button from the settings and make room for other functionalities that we will be implementing later @palisadoes @noman2002  WDYT?

**Comment by bigBrain1901** [comment]
Also, the placement of the Settings option in the navbar is not intuitive imo. It is not clear if that menu item means "User Settings" or "Organization Settings", while the logo on the navbar is the organization logo.

The page contains both user and org settings, though. Maybe we should decouple these 2 settings and show only the user setting in the navbar. A button for the org settings page can be shown on the org management page itself?

**Comment by palisadoes** [comment]
- @aashimawadhwa Yes we need only one location for deleting the organization.
- @bigBrain1901 Can you show provide rough diagrams of what you are proposing for the two screens? Paste the images into the comments.

**Comment by kayceeDev** [comment]
> Also, the placement of the Settings option in the navbar is not intuitive imo. It is not clear if that menu item means "User Settings" or "Organization Settings", while the logo on the navbar is the organization logo.
> 
> The page contains both user and org settings, though. Maybe we should decouple these 2 settings and show only the user setting in the navbar. A button for the org settings page can be shown on the org management (OrgDashboard) page itself?

I don't think decoupling the settings is ideal since there is only a single button that says **update user settings**.

**Comment by kayceeDev** [comment]
Please can you assign me this issue? I have a partial fix for deleting the organization.

**Comment by bigBrain1901** [comment]
Having "User Settings" inside the "Organisation Settings" page seemed a bit off, especially since talawa-admin will be used by admins only. Hence, the organisation settings page could be more suited for managing organisation settings, member requests and deleting the organization. User settings for the logged-in admin can be decoupled.

![image](https://user-images.githubusercontent.com/55971005/224044376-470d65fa-6903-48a3-960c-15b31879541f.png)

This is what I suggested
1. User settings on the navbar
2. Organization Settings in the sidebar
3. Organization Delete button in the Organization Settings page

@kayceeDev, PS: #549 already does what you achieved in #600

**Comment by palisadoes** [comment]
@kayceeDev 

Thanks for highlighting these deficiencies.

1. We now have the organization icon shown twice in the menu bar. One will need to be replaced. How do you propose to fix that?
1. The clicking manage organization button should take the user to the settings layout. 
    1. Possibly with a statistics button to get the stats. Propose which screen would be the default on clicking through to the manage organization section.
1. The settings screen is now blank when you get there. It should go to a screen with content (see above)
1. Where do you propose to place the organization notifications information?
1. What solution do you propose for the “Update your details” button. Should this be be a user specific profile page accessible via the top right dropdown?
    1. It would make sense to have the language change option on a profile page.

We will need to create multiple issues to fix each of these areas after you clarify the approaches to be taken.

**Comment by palisadoes** [comment]
I originally meant @bigBrain1901, please comment also

**Comment by kayceeDev** [comment]
> I originally meant @bigBrain1901, please comment also

Alright.

**Comment by bigBrain1901** [comment]
These are my observations. They are in slight contrast with that of @kayceeDev but that comes from the kind of apps that we have seen, I guess. Here is how I see the best UX for our admin app.

1. The right end of the navbar usually stands for user profile interactions. We should do the same as it makes UX sense for the user. Further, the picture shown there should always be the user profile photo. This must be retained on all screens in the admin app. Within that dropdown, there must be the following options.
    a. Notifications (across all orgs, for that admin user)
    b. Settings (corresponds to user settings always)
    c. Language
    d. Logout
2. As of now, the landing page of the app shows a list of all organizations with a "manage" button on each of those cards. That page only contains statistics, so the indicative name for this button should be "More Details" or simple "Details".
3. On the orgDash page, there must be a button to edit organization settings in the sidebar (shown in my comment above).
4. The settings page has a few bugs.
    a. It loads an empty page by default. Instead, "Update Organization" must load by default. The other buttons on the sidebar must be - "See Member Requests" and "Delete Organization".
    b. A few other smaller bugs have been addressed in the issue description on the top.

Personally, keeping user settings and organization-specific settings on the same page is not something I find intuitive. User settings are a global config across all organizations.

The primary idea of this thread is that the right end of the navbar must be user specific and uniform across all screens. That way, the UX stays nice and consistent. with other apps out there.

Something like this...

### The Manage Organization (orgDashboard) Page
![image](https://user-images.githubusercontent.com/55971005/224127086-a51e073d-6c1a-4c1a-9cdf-3af8c8d6a65d.png)

### The Organization Settings (orgSettings) Page - landing view and modified sidebar
![image](https://user-images.githubusercontent.com/55971005/224127253-2d1b1c1c-67ed-498b-ace5-b704bfe03858.png)

**Comment by palisadoes** [comment]
@bigBrain1901 

1. The manage button text needs to remain. 
1. The `update your details` user page should be a separate profile page where you can select your preferred language for using any Admin dashboard. Putting language in the dropdown increases the chances of making a mistake when the person uses it. Especially as it is a one-time change. The less options the better.

@bigBrain1901 Please submit a PR. When we see the results @kayceeDev can work on the fine tuning.

**Comment by SamMintah** [comment]
@palisadoes as I suggested yesterday on slack, I've found that it can be time-consuming to navigate to the settings page to update my an Organization. That's why I propose adding an 'Update' button alongside the existing 'Delete' button on the main page, making it easy for users to quickly update their information without any hassle. Below is an example of how it could look, I hope you find my suggestion valuable, and I would love to hear your opinion on this. Thank you 
![mobile (8)](https://user-images.githubusercontent.com/100992913/224467103-43c4ec1d-64e1-4aa7-b8aa-e7592f7c47ff.gif)

**Comment by palisadoes** [comment]
@bigBrain1901 Are you going to submit a pull request?

**Comment by bigBrain1901** [comment]
Yes! Please give me a day, max. I will do it.

**Comment by bigBrain1901** [comment]
Hi @kayceeDev,  
I have the redesign ready. But that ended up breaking about 10 tests in the repo.

Can you help me out with a quick review of the UX and a few tests?  
I'll open up a draft PR to track tuning and test fixes if this is okay, @palisadoes.

**Comment by kayceeDev** [comment]
> Hi @kayceeDev, I have the redesign ready. But that ended up breaking 7 tests in the repo.
> 
> Can you help me out with a quick review of the UX and a few tests? I'll open up a draft PR to track tuning and test fixes if this is okay, @palisadoes.

Alright, I will take a look. Well done bro.

**Comment by palisadoes** [comment]
We don't do draft PRs. 

We get notified of every event in the queue, and draft PRs like these, and their updates that require no action can be a distraction. We need our reviewers to focus on updates that are ready. 

Please submit when you are ready.

**Comment by palisadoes** [comment]
Are you going to work on this? I'll need to requirement this soon without a PR. There are many people creating similar issues

**Comment by bigBrain1901** [comment]
I'll resolve the remaining issues with the PR in 24 hrs. Working on re-writing the tests that broke as part of the UI redesign,

**Comment by adi-uchiha** [comment]
(Suggestion): Plan a the entire settings page keeping the UX in mind, ease of use, considering user human mistake responsiveness and consistent UI. Also take suggestions from others as how would they like the settings  (UI is very subjective)
Make this as a parent issue and create multiple child issues.
Keep the changes incremental. Big changes in UI result in bugginess and also disturbs the workflow of other devs.

**Comment by bigBrain1901** [comment]
Please feel free to review the PR and suggest other UX options. I was not sure how I could split this issue into smaller issues, as all the ideas were coherent. But, I am very happy to take suggestions and collaborate :angel:

**Comment by palisadoes** [comment]
@bigBrain1901 Why did you close the PR? We need the improvements, the fine tuning suggestions can occur later.

**Comment by bigBrain1901** [comment]
I am still stuck on the same step, actually. In fact, all the fine-tuning is complete as well.

The feature set is ready, but the tests need to be rewritten.  
The issue I am facing is with the MockProvider feature that was recently merged into `develop`.

Before opening an issue, I wanted to confirm if that is the cause.  
In all this, I was not keeping well, and I am probably taking a lot of time to get this PR rolling.

Shall I create the PR as is, and can the community take up the tests?  
This way, this issue with the tests can be identified/dismissed as well.

**Comment by palisadoes** [comment]
The tests need to be a part of the PR. There is no guarantee that they will be done otherwise

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

If you cannot progress with it, I'll close the issue as we are getting close to starting a complete UI/UX overhaul.

**Comment by adi-uchiha** [comment]
@palisadoes this will get covered in Admin UI Redesign gsoc idea

**Comment by palisadoes** [comment]
Closing
