### ISSUE TITLE
Add Test Coverage Check for Pull Requests as a GitHub Action

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#56]
**Is your feature request related to a problem? Please describe.**

1. The code base is insufficiently testable.
1. We need all code to be tested as part of each pull request.

**Describe the solution you'd like**

1. We need a way to add a GitHub action that automatically checks the codebase for the percentage coverage by tests.
1. The check should error out when the percentage is below a predefined level
1. The aim is that we’ll set increasingly higher percentage coverage until the codebase is 100% covered
1. We also want to ensure and verify that all tests in the repo are automatically run as part of each pull request as a GitHub action.

**Describe alternatives you've considered**

1. We have seen solutions such as those by [CodeCov](https://about.codecov.io/blog/javascript-code-coverage-using-github-actions-and-codecov/) for Javascript. Using CodeCov is the preferred approach.
2. We have decided against using a  `jest` script.

**Approach to be followed**

1. This must be added as a [GitHub action in the repository’s issues.yml file](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions) 
1. There are many examples of how to implement this that you can consider
    1. From the [CodeCov website](https://about.codecov.io/blog/javascript-code-coverage-using-github-actions-and-codecov/)
    1. [Another example](https://michaelzanggl.com/articles/github-actions-coverage-setup/)
1. We need this to comply with our [GitHub actions policy](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/README.md).
1. We want this to only done on pull requests to start, so edit the `pull-requests.yml` file only in the [GitHub actions folder](https://github.com/PalisadoesFoundation/talawa-admin/tree/develop/.github/workflows).
1. Determine the current code coverage level. Set the GitHub action to pass at that threshold.
1. We will increase the GitHub action value after successful submission of the PR that closes this issue.

**Additional context**

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

**Comment by palisadoes** [comment]
@muskan399 This is something that may interest you too seeing that you've worked with GitHub actions before.

**Comment by Prathamesh010** [comment]
Can i work on this issue?

**Comment by PSY27** [comment]
can i work on this issue

**Comment by palisadoes** [comment]
@Prathamesh010 Are you still working on this?

**Comment by Prathamesh010** [comment]
No, i unassigned myself as you can see above.
I think you accidentally assigned me again instead of PSY27.

**Comment by SiddheshKukade** [comment]
@PSY27 I have unassigned you due to no response. @palisadoes Sir I think there is already a check for coverage.

**Comment by palisadoes** [comment]
OK. This should be closed.
