### ISSUE TITLE
Rectify Errors/Warnings : `src/screens/OrgContribution/OrgContribution.test.tsx`

### ISSUE THREAD

**Issue by aviraldevv** [PalisadoesFoundation/talawa-admin#562]
**Describe the bug**
There are certain warning in the console when we run the test ```OrgContribution.test.tsx``` using the command ```yarn test OrgContribution.test```

**To Reproduce**

1. Open a terminal inside the Talawa Admin Project
2. Run the command ```yarn test OrgContribution.test.tsx```
3. The tests will pass but, there would be many warning in the terminal.

#### Issue tracker for this file:
Make sure to complete the following issues.

* [ ] Removed the warning with statement ```This typically indicates a configuration error in your mocks setup, usually due to a typo or mismatched variable.```
* [ ] The terminal has no other warning

### PR Acceptance Criteria
- When complete this file must show 100% coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

Parent issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/555

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by KrutikaBhatt** [comment]
Can I take up this issue ?

**Comment by adi-uchiha** [comment]
@KrutikaBhatt What is the progress ?

**Comment by KrutikaBhatt** [comment]
It's done. I will raise a PR soon. Sorry for the delay

**Comment by adi-uchiha** [comment]
Alright! No worries
