### ISSUE TITLE
Rectify Errors/Warnings : `src/App.test.tsx`

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#563]
**Describe the bug**
There are certain warning in the console when we run the test `App.test.tsx` using the  yarn test command

**To Reproduce**

1. Open a terminal inside the Talawa Admin Project
2. Run the command yarn test App.test
3. The tests will pass but, there would be many warning in the terminal.

**Issue tracker for this file:**

- [ ] Removed the warning with statement `This typically indicates a configuration error in your mocks setup, usually due to a typo or mismatched variable`
- [ ] The terminal has no other warning

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Parent Issue #555**

**Comment by aviraldevv** [comment]
@aashimawadhwa Please keep the title consistent and tag the parent issue.

**Comment by techfussion** [comment]
I would like to work on this @aashimawadhwa

**Comment by palisadoes** [comment]
@techfussion 

Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues.

**Comment by Himanshiii-14** [comment]
Hello @palisadoes 
I would like to work on this, please assign this to me

**Comment by adi-uchiha** [comment]
@Himanshiii-14 Do you need any help ?
