### ISSUE TITLE
Rectify Errors/Warnings : `src/components/OrgPostCard/OrgPostCard.test.tsx`

### ISSUE THREAD

**Issue by aviraldevv** [PalisadoesFoundation/talawa-admin#566]
**Describe the bug**
There are certain warning in the console when we run the test ```OrgPostCard.test.tsx``` using the command ```yarn test OrgPostCard.test```

**To Reproduce**

1. Open a terminal inside the Talawa Admin Project
2. Run the command ```yarn test OrgPostCard.test```
3. The tests will pass but, there would be many warning in the terminal.

#### Issue tracker for this file:
Make sure to complete the following issues.

* [ ] Removed the warning with statement ```This typically indicates a configuration error in your mocks setup, usually due to a typo or mismatched variable.```
* [ ] The terminal has no other warning

Parent Issue: #555 

### PR Acceptance Criteria
- When complete this file must show 100% coverage when merged into the code base.
- [The current code coverage for the file can be found here](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin?search=&displayType=list)
- The PR will show a report for the code coverage for the file you have added. You can use that as a guide

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akankshat05** [comment]
I would like go fix this issue

**Comment by akankshat05** [comment]
I would like to fix this issue

**Comment by noman2002** [comment]
@akankshat05 Assigned you two issues . As we rule only 2 issues can be assigned to you at once. Get the PRs merged for assigned issues then as for more issues.

**Comment by Himanshiii-14** [comment]
Hello @noman2002 ,
I would like to work on this Please assign this to me

**Comment by palisadoes** [comment]
Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues.

**Comment by palisadoes** [comment]
> Hello @noman2002 , I would like to work on this Please assign this to me

@Himanshiii-14  Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues.

**Comment by rishav-jha-mech** [comment]
Please aassign this issue to me

**Comment by palisadoes** [comment]
@rishav-jha-mech We are reserving this series of errors to newcomers

**Comment by palisadoes** [comment]
> Please aassign this issue to me

@rishav-jha-mech We are reserving this series of errors to newcomers

**Comment by techfussion** [comment]
I would like to work on this.

**Comment by palisadoes** [comment]
> I would like to work on this.

Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues.

**Comment by shahx95** [comment]
Hi. I'm interested in taking this up

**Comment by kayceeDev** [comment]
@shahx95 what is your status on this issue? Have you submitted a PR yet? do you have any block? Please comment.
