### ISSUE TITLE
Rectify Errors/Warnings : `src/components/AdminNavbar/AdminNavbar.test.tsx`

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#567]
**Describe the bug**
 There are certain warning in the console when we run the test `AdminNavbar.test.tsx` using the yarn test command

**To Reproduce**

1. Open a terminal inside the Talawa Admin Project
2. Run the command yarn test `AdminNavbar.test.tsx`
3. The tests will pass but, there would be many warning in the terminal.

**Issue tracker for this file:**

- [ ] Removed the warning with statement `This typically indicates a configuration error in your mocks setup, usually due to a typo or mismatched variable`
- [ ] The terminal has no other warning

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Parent Issue #555**

**Comment by oreoluwadnd** [comment]
I would like to work on this. Could you assign it to me?

**Comment by adi-uchiha** [comment]
@oreoluwadnd Do you need any help?

**Comment by oreoluwadnd** [comment]
Yeah I can't seem to trace where the warning is coming from

**Comment by adi-uchiha** [comment]
I helped you in another comment 🙂

**Comment by kayceeDev** [comment]
@aashimawadhwa what is your status on this issue?
