### ISSUE TITLE
Rectify Errors/Warnings : `src/screens/Roles/Roles.tsx`

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#568]
**Describe the bug**
 There are certain warning in the console when we run the test Roles.tsx using the yarn test command

**To Reproduce**

1. Open a terminal inside the Talawa Admin Project
2. Run the command yarn test `Roles.tsx`
3. The tests will pass but, there would be many warning in the terminal.

**Issue tracker for this file:**

- [ ] Removed the warning with statement `This typically indicates a configuration error in your mocks setup, usually due to a typo or mismatched variable`
- [ ] The terminal has no other warning

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Parent Issue #555**

**Comment by ceasar28** [comment]
Hello I am an outreachy applicant, I would love to work on this issue

**Comment by adi-uchiha** [comment]
@ceasar28 Do need any help for this ?
