### ISSUE TITLE
JSON Language packs must be able to be uploaded to API from the Web Portal

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#57]
**Is your feature request related to a problem? Please describe.**

1. The mobile app currently has a set of pre-defined JSON files used for translating menu items
1. The API will store: 
     1. Updated versions of existing files 
     1. New files for previously unsupported languages

**Describe the solution you'd like**

1. New files for previously unsupported languages will need to be uploaded in the `talawa-admin` portal
2. These files will need to be stored in a well known location so that they can be retrieved by the mobile app.

**Describe alternatives you've considered**

N/A

**Approach to be followed (optional)**

None

**Additional context**

1. Mobile App Retrieval Process: https://github.com/PalisadoesFoundation/talawa/issues/859
2. Discussion of the strategy: https://github.com/PalisadoesFoundation/talawa-api/pull/281
3. Issue for API storage of files: https://github.com/PalisadoesFoundation/talawa-api/issues/283

**Comment by yasharth291** [comment]
hello sir
