### ISSUE TITLE
Enhancing dashboard and removing redundant functionalities

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#570]
**Describe the bug**
notifications are redundant we can remove the icon from the dashboard as we continue to keep them in the drop down.

**To Reproduce**

1. create a organization
2. click on manage
3. click on drop down option in the top left
4. see the issue

**Expected behavior**
remove the bell icon and related tests properly

**Actual behavior**
we have 2 notification in the dashboard

**Screenshots**

![Screenshot 2023-03-08 at 9 05 15 AM](https://user-images.githubusercontent.com/73706697/223613181-d652ef04-e3c7-4d19-87c8-3377b1be5251.png)

**Additional details**
**This is a good first issue and we welcome newcomers and beginners to  look into them**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
Outreachy candidates and new comers can try this out .

**Comment by akankshat05** [comment]
hello @aashimawadhwa! I would like to work on this

**Comment by techfussion** [comment]
I would like to work on this
