### ISSUE TITLE
Add talawa admin logo in the Dashboard navbar 

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#571]
**Is your feature request related to a problem? Please describe.**
On dashboard's navbar we do not have logo for talwa-admin, we already have access to the organization picture in the about section having another on the top left will moreover make it redundant  Also remove the name of the organization from the navbar.

**Describe the solution you'd like**
Follow the navbar from other screens and change this 
![Screenshot 2023-03-08 at 9 12 13 AM](https://user-images.githubusercontent.com/73706697/223614110-1c3d5824-c2c6-426e-9ec5-423563658a83.png)

to this
![Screenshot 2023-03-08 at 9 08 02 AM](https://user-images.githubusercontent.com/73706697/223613880-ddfaacfa-c9d0-4b20-b2c8-04e2578289c8.png)

**Approach to be followed (optional)**
you can check out the implementation from the registration page navbar 

**Additional context**
**This is a good first issue and we welcome newcomers and beginners to  look into them**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
Outreachy candidates and new comers can try this out .

**Comment by adi-uchiha** [comment]
I want to work on this assign me please

**Comment by Folarh** [comment]
I wamt to work on the Dashboard logo, please assign me

**Comment by techfussion** [comment]
I would like to work on this

**Comment by noman2002** [comment]
@Folarh Assigned you as a new comer.

**Comment by Yemihunter** [comment]
Hello, can multiple persons be assigned a task? if yes, I would also love to work on this task

**Comment by anshgoyalevil** [comment]
@palisadoes @noman2002 

I guess this was a feature, and not an issue. This feature was recently added intentionally.

**Comment by aashimawadhwa** [comment]
@anshgoyalevil  but don't you think the navbar should consist of the talwa admin logo and not this to make sure the navbar is consistent what is the use of  org picture and name on the navbar?

**Comment by palisadoes** [comment]
- @aashimawadhwa I understand the intent, but this was added as mentioned before for a reason to make administration easier.
- @Folarh We are going to have to close this issue.
