### ISSUE TITLE
Move the location to the about section of the organization

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#572]
**Is your feature request related to a problem? Please describe.**

currently location is rendering to the left side , we can change the location to the about section, it will make more sense in that section 

**Describe the solution you'd like**
The location should render above or below the description in the about section
![Screenshot 2023-03-08 at 9 12 13 AM(1)](https://user-images.githubusercontent.com/73706697/223614991-7b81a0cc-301f-419d-b5a6-34fdf5e763f7.png)

**Additional context**
**This is a good first issue and we welcome newcomers and beginners to  look into them**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
Outreachy candidates and new comers can try this out .

**Comment by somu5307** [comment]
In which page does the location is rendering to the left side.
I couldn't find this in - https://www.palisadoes.org/
Kindly, help me to make my first open source contribution.

**Comment by noman2002** [comment]
> In which page does the location is rendering to the left side. I couldn't find this in - https://www.palisadoes.org/ Kindly, help me to make my first open source contribution.

Run the project locally you'll find it.

**Comment by techfussion** [comment]
I would like to work on this

**Comment by techfussion** [comment]
I think it would be better to move the location below the organization description

**Comment by Queen-codes** [comment]
I would like to work on this, could I be assigned the issue?

**Comment by ShravaniAK** [comment]
i would like to work upon this issue

**Comment by oreoluwadnd** [comment]
I would like to work on this

**Comment by Phyya** [comment]
Hello @aashimawadhwa, I would like to work on this. Kindly assign. Thanks

**Comment by aashimawadhwa** [comment]
You can ask @noman2002 @xoldyckk @palisadoes

**Comment by Phyya** [comment]
Hi @xoldyckk, I would like to work on this. Kindly assign, thanks

**Comment by adepeju4** [comment]
Hi @aashimawadhwa, do you mean the location is rendering at the right side and it should be moved to the same section as the about section?

**Comment by techfussion** [comment]
Yes, but I've been assigned the task.

**Comment by adepeju4** [comment]
oh okayyyyyy
