### ISSUE TITLE
Fix yarn installation instructions in INSTALLATION.md

### ISSUE THREAD

**Issue by xoldyckk** [PalisadoesFoundation/talawa-admin#578]
**Describe the bug**
Yarn v3 doesn't work with talawa-admin, only yarn v1 does. The installation instructions for yarn are incorrect.

**To Reproduce**

1. Install yarn v3
2. Run `yarn serve`
3. Go to `http://localhost:3000`, nothing works

**Expected behavior**
Talawa-admin's installation instructions should mention how to accurately install yarn v1.

**Actual behavior**
Talawa-admin's current installation instructions mention how to install yarn v3 which doesn't work with talawa-admin and is not backwards compatible with yarn v1.

**Screenshots**
 -

**Additional details**
 -

**Potential internship candidates**
 -

**Comment by aviraldevv** [comment]
@xoldyckk Assign this issue to me I will  be working on installation part again due to a error on my system.

**Comment by Manoramsharma** [comment]
@xoldyckk  I already encountered this issue and raised the concern for same I think I can clearly update the installation guide. I can work on this
