### ISSUE TITLE
Parent Issue: Fix Numerous GitHub Actions Issues

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#58]
**Describe the bug**

This is a tracking issue for these good starter issues for new contributors.

1. Standardize GitHub Actions file layout: https://github.com/PalisadoesFoundation/talawa-admin/issues/52
1. Add Test Coverage Check for Pull Requests as a GitHub Action: https://github.com/PalisadoesFoundation/talawa-admin/issues/56
1. Organise github workflow and add script: https://github.com/PalisadoesFoundation/talawa-admin/issues/37
1. Verify the ordering of GitHub Actions and ensure linting is occurring: https://github.com/PalisadoesFoundation/talawa-admin/issues/59
1. GitHub Action: JavaScript Code Formatter #61
1. CodeQL must only run on pull requests: https://github.com/PalisadoesFoundation/talawa-admin/issues/62

**To Reproduce**

N/A

**Expected behavior**

N/A

**Actual behavior**

N/A

**Screenshots**

**Additional details**

**Comment by akshatgarg12** [comment]
@palisadoes assign it to me.

**Comment by akshatgarg12** [comment]
@palisadoes I have separated actions for pull-request and issues in separate files, can you confirm whether this order of action in PR Workflow is suitable or should i change it.
1. The Greeting message
2. Linting runs (we can add code formatter just before lint check #61 ) 
3. Then it runs the test (continuous integration) [after this we can add the codecov #56]
4. Code QL analyse 
![Screenshot 2021-06-07 at 1 19 56 PM](https://user-images.githubusercontent.com/60404253/120979776-8f1b8f00-c793-11eb-98b2-edb8b611bfbb.png)

**Comment by palisadoes** [comment]
@akshatgarg12 Yes that is the correct order. Please proceed.

**Comment by akshatgarg12** [comment]
@palisadoes With CodeQL configured in pull-request.yml i am getting this warning also. Although the action in running in the PR flow. 

![Screenshot 2021-06-07 at 11 45 45 PM](https://user-images.githubusercontent.com/60404253/121069089-b5204e00-c7ea-11eb-8514-56d86639b37b.png)

Along with the one action in PR flow, its creating a second action for CodeQL separately also, which is not resolving and giving this warning.
![Screenshot 2021-06-07 at 11 55 50 PM](https://user-images.githubusercontent.com/60404253/121070087-e8afa800-c7eb-11eb-9575-4e125675b339.png)

**Comment by palisadoes** [comment]
So CodeQL is being run twice? Which one is failing? The standalone item or the ones in PR flow? If PR flow is working and using CodeQL then that's the one we should keep

**Comment by akshatgarg12** [comment]
> So CodeQL is being run twice? Which one is failing? The standalone item or the ones in PR flow? If PR flow is working and using CodeQL then that's the one we should keep

Yes it's being run twice, the standalone one is failing. I have not configured it to run a standalone action, don't know why its running

**Comment by palisadoes** [comment]
@akshatgarg12 Do you still have the standalone codeql YAML file in the `.github/workflows` directory? If it is, that may be the reason it's running twice.

**Comment by palisadoes** [comment]
@akshatgarg12 

1. The CodeQL [README.md](https://github.com/github/codeql-action) has a section _**If you prefer to integrate this within an existing CI workflow, it should end up looking something like this:**_ that should help.
1. There is also a [Configuration File section](https://github.com/github/codeql-action#configuration-file) that should help fix the issue of not finding the correct branch.

Let me know if that helps.

**Comment by akshatgarg12** [comment]
> @akshatgarg12 Do you still have the standalone codeql YAML file in the `.github/workflows` directory? If it is, that may be the reason it's running twice.

Noo I have removed it

**Comment by SiddheshKukade** [comment]
Closing this as no PR is associated with this issue.
