### ISSUE TITLE
Duplicacy in Posts section

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#582]
**Describe the bug**
Duplicate posts can be created with same title and even same description...
**To Reproduce**

1.Login to talawa-admin
2. Create a new post by going into post section of an Org.
3.Now create another post with same title and description

**Expected behavior**
No two posts should be same(not be duplicate of each other)

**Actual behavior**
posts can be duplicated

**Screenshots**
![image](https://user-images.githubusercontent.com/107215525/223852397-f2f3e01b-1a03-4894-ba04-19b170cf3e3e.png)

**Comment by anurag0006** [comment]
i want to solve this issue..Please assign it to me

**Comment by brownboy3047** [comment]
pls can you assign this to me

**Comment by Yass32** [comment]
Hello, I'm an outreachy applicant. id really like to work on this

**Comment by palisadoes** [comment]
Assigning to @brownboy3047 as a newcomer

**Comment by anshgoyalevil** [comment]
@palisadoes 

Don't you think it is a redundant check. 

Every website on the internet allows user to create posts with duplicate title and content.

Consider a case when admin posts "Happy new year" on 01-01-2023 and again posts that on 01-01-2024.

I guess, we should think of all corner cases when taking such issues into account.

**Comment by palisadoes** [comment]
Yes this isn't necessary. It makes sense if it's a news website, but this is a user news feed.

It's even debatable whether we need titles. Twitter, LinkedIn and Instagram feeds don't

**Comment by palisadoes** [comment]
This should be closed

**Comment by Cioppolo14** [comment]
Closing this based on the above conversation.
