### ISSUE TITLE
Change the heading of all the users from "List of users you spammed" to "All users"

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#583]
**Describe the bug**
The heading of user's section in an Org is "List of users who spammed"...Instead of it should be something else like "All users"
**To Reproduce**

1.Login to talawa-admin
2.go to all users section in any Org

**Expected behavior**
The Heading should be something else

**Actual behavior**
The heading is "List of All the users who spammed"

**Screenshots**
![WhatsApp Image 2023-03-09 at 3 00 22 AM](https://user-images.githubusercontent.com/107215525/223854909-cba63a90-feaa-4510-a51e-51cc9ea73e3d.jpeg)

**Comment by anurag0006** [comment]
Any of the new comers please ask this issue to be assigned by the maintainer or mentors...I think this can be a good issue to get started

**Comment by techfussion** [comment]
I can work on this

**Comment by Yass32** [comment]
Hello, I'm an outreachy applicant. id really like to work on this

**Comment by anshgoyalevil** [comment]
@palisadoes @anurag0006 

This feature was added last year keeping Spam Plugin in mind.

When a user will spam in the Talawa App, that user will be displayed here. After that, its the duty of admin to block or unblock them.

If we change it to ```All users```, its use case will be changed to viewing users, which is same as ```People``` tab.

**Comment by palisadoes** [comment]
Yes you are right. This issue needs to be closed

**Comment by Cioppolo14** [comment]
Closing this based on the above conversation.
