### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by arushi2715** [PalisadoesFoundation/talawa-admin#585]
On the talawa admin portal the password field shows that the password should be 8 characters long. When user types in the password and it satisfies the 8 character long criteria then that should disappear which isn't happening now.

* The 8 character long criteria for password should disappear when the user types a password which satisfies it because it leaves a sense of confusion.

![image](https://user-images.githubusercontent.com/78142604/223941080-e5592232-be63-48c5-b3a3-4eae33167105.png)

**Comment by arushi2715** [comment]
@palisadoes can you please look into this?
I would like to work on this.

**Comment by Phyya** [comment]
@xoldyckk I would love to work on this please

**Comment by aashimawadhwa** [comment]
@Phyya  before making the PR you have to wait for the mentors to assign it to you, Ideally because @arushi2715 asked first, she should have solved this.

@noman2002 @xoldyckk @palisadoes

**Comment by arushi2715** [comment]
hey!
thanks @xoldyckk i will push the changes soon.

**Comment by arushi2715** [comment]
Hey @xoldyckk @palisadoes can you please reopen this and give proper labels to this issue?
In the meantime I'll work on this.

**Comment by xoldyckk** [comment]
@palisadoes Explained here https://github.com/PalisadoesFoundation/talawa-admin/pull/607#issuecomment-1463687159

**Comment by xoldyckk** [comment]
@palisadoes why close?

**Comment by palisadoes** [comment]
Apparently one of the commits in this PR closed it:

- https://github.com/PalisadoesFoundation/talawa-admin/pull/603

Unintended.
