### ISSUE TITLE
Bug Report : Talawa-Admin-Icon

### ISSUE THREAD

**Issue by iamyelex** [PalisadoesFoundation/talawa-admin#586]
**Describe the bug**
The Talawa logo on the Talawa admin site should be clickable to be able to take admin back to the landing page. 

**To Reproduce**
 I attach the home page link to the logo, so wherever on the page you are and you need to go back to the landing page, clicking on the logo will do that for you.

**Expected behavior**
When clicked, it should take you to the landing page.

**Actual behavior**
rather it's not doing anything.

**Screenshots**
![talawa-admin-logo](https://user-images.githubusercontent.com/95015039/223957261-57cbcf8a-86f7-49d9-a3d1-9f4720bb9785.PNG)

**Comment by iamyelex** [comment]
Please, I'd like to be assigned this issue. Thank you

**Comment by iamyelex** [comment]
![talawa-admin-landingPage](https://user-images.githubusercontent.com/95015039/224018526-04d3dd3a-7f7b-456b-b871-c63941a3d04f.png)

**Comment by aashimawadhwa** [comment]
This is working fine for me, from the roles and request section i am easily able to navigate back on the organization list page by clicking on the talawa icon

**Comment by iamyelex** [comment]
@aashimawadhwa it is not working when you are in the manage organization section. kindly check it. Thanks

**Comment by aashimawadhwa** [comment]
We have a button all organization for that in the navbar of the dashboard.

**Comment by palisadoes** [comment]
Closing.
