### ISSUE TITLE
Feature Request : Search by Location

### ISSUE THREAD

**Issue by iamyelex** [PalisadoesFoundation/talawa-admin#587]
**Is your feature request related to a problem? Please describe.**
On the Talawa-Admin landing page, the admin can only search organizations by name. I strongly believe admin should be able to search content by location, we can help them narrow down their search results to only those that are relevant to their geographic area.

**Describe the solution you'd like**
To create the search by location feature which will also be a good way to filter the search result

**Describe alternatives you've considered**
1. put the search by the location under the search by name.

**Comment by xoldyckk** [comment]
@iamyelex I disagree. Location is a random string and it has no order and neither it is a unique constraint. It's not a good candidate for filtering and indexing it would be wasteful.

**Comment by palisadoes** [comment]
I agree, the app does not support locations currently. @iamyelex please reconsider your approach. I'll close this issue.
