### ISSUE TITLE
Bug Report: Delete not working

### ISSUE THREAD

**Issue by iamyelex** [PalisadoesFoundation/talawa-admin#588]
**Describe the bug**
When you click on manage on organization and navigate to settings, the delete organization section is not working.

**To Reproduce**
1.  To make the key working 
2.  or remove the key since a delete key is at the dashboard page

**Expected behavior**
It ought to delete an organization when clicked but it does not have any functionality

**Actual behavior**
doing nothing. unclickable

**Screenshots**
![talawa-admin-delete](https://user-images.githubusercontent.com/95015039/223965778-0dbf0255-25d9-4b25-9e1b-e4d7416ecfaf.PNG)

**Comment by aashimawadhwa** [comment]
I guess someone is already working on this issue.

**Comment by xoldyckk** [comment]
> #559 @xoldyckk @iamyelex

Are you sure?

**Comment by aashimawadhwa** [comment]
@xoldyckk  please go through the issue once.

**Comment by xoldyckk** [comment]
Yeah I saw

**Comment by xoldyckk** [comment]
@iamyelex I'm closing this issue as it's already registered under a different name.

**Comment by iamyelex** [comment]
okay . Thanks
