### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by iamyelex** [PalisadoesFoundation/talawa-admin#589]
**Is your feature request related to a problem? Please describe.**
Adding a dark mode is a nice feature. You can switch between dark mode or light mode depending on your choice.
Research has shown that dark mode can have a significant positive impact on experience.

**Describe the solution you'd like**
create a button to click to toggle the dark mode and light mode functionality

**Comment by xoldyckk** [comment]
@palisadoes This is a good feature request and you can provide more info on color scheme.

**Comment by KrutikaBhatt** [comment]
Is this issue open to work on?

**Comment by palisadoes** [comment]
We are focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
