### ISSUE TITLE
Delete Organization functionality should moved to organisation settings only

### ISSUE THREAD

**Issue by kayceeDev** [PalisadoesFoundation/talawa-admin#592]
**Is your feature request related to a problem? Please describe.**
On the Talawa dashboard, the `delete organization` button is found, I believe that this button should be in the dashboard because users can accidentally delete an organization even without the intention. This functionality should only be in the settings section of the organization. This helps improve the UX

**Describe the solution you'd like**
Replicate the same functionality on the settings page and remove it from the dashboard.

**Describe alternatives you've considered**
To change the button color to red as well as move it to the dashboard settings page

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
#559 please refer to this, if both the PR gets merged we will be removing the delete organization functionality completely @xoldyckk . we are removing it from settings already.

**Comment by xoldyckk** [comment]
@kayceeDev Closing this issue as it's a duplicate.
