### ISSUE TITLE
Bug Report: Updating Organization

### ISSUE THREAD

**Issue by iamyelex** [PalisadoesFoundation/talawa-admin#594]
**Describe the bug**
After successfully updating an organization, it should return to the dashboard page, so you see your update instantly.

**To Reproduce**
swift access to what you updated.

**Expected behavior**
A successful change should return to the dashboard page.

**Actual behavior**
it just opens a blank settings page.

**Screenshots**
![talawa-admin-updated](https://user-images.githubusercontent.com/95015039/224008652-076cf2e4-5e6c-491c-812b-13453faa93bf.PNG)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by iamyelex** [comment]
Please I'd be glad if you assign this issue to me. Thanks

**Comment by palisadoes** [comment]
Unassigning due to inactivity others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by prathamesh-mutkure** [comment]
Hi @palisadoes, I'd like to work on this

**Comment by prathamesh-mutkure** [comment]
Hi @StrangeJay, I'll submit a PR on this soon
