### ISSUE TITLE
Bug Report: Organization section

### ISSUE THREAD

**Issue by iamyelex** [PalisadoesFoundation/talawa-admin#596]
**Describe the bug**
When you are in the manage organization, navigating the dashboard, people, etc should be made known by having a border under the section you are in. That will help you easily know which part you are in the section. 

**To Reproduce**
You can add a CSS class that contains the border, so on clicking on each of the sections the border-bottom is activated.

**Expected behavior**
when you click on either of the section, it should have a bottom border as a sign of you are currently in this section.

**Actual behavior**
It does not show anything and no way to know which part of the section you are in.

**Screenshots**
![talawa-admin-border](https://user-images.githubusercontent.com/95015039/224016226-48066bf1-a77d-4535-8e94-40a79fbb4ba6.PNG)

That is a screenshot of me in the people section, you can not tell easily which section you are in. But with a border-bottom on each section you are, it will improve User Experience

**Comment by iamyelex** [comment]
Please I'd be glad if you assign this issue to me. Thanks

**Comment by palisadoes** [comment]
Unassigning due to inactivity others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by prathamesh-mutkure** [comment]
Hey @palisadoes, can I take this up?
