### ISSUE TITLE
Adding check for the length of the organization name

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#598]
**Describe the bug**
As now we are rendering name of the organization on the dashboard, having large name will break the styling 

**To Reproduce**

1.  create an organization
2.  give it a big name
3. open dashboard of that organization
4. see the error

**Expected behavior**
- Either we can check the length or can control the overflow situation at the navbar.

**Actual behavior**
it is overflowing and breaking the styling.

**Screenshots**
![Screenshot 2023-03-09 at 6 25 57 PM (2)](https://user-images.githubusercontent.com/73706697/224031496-c143b6ac-b312-467b-b1ba-30721515350d.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
@palisadoes  i would like to work on this issue.

**Comment by SamMintah** [comment]
I would like to work on this
