### ISSUE TITLE
About Organization overflows the container

### ISSUE THREAD

**Issue by kayceeDev** [PalisadoesFoundation/talawa-admin#604]
**Describe the bug**
The about organization overflows its container when user enters long characters

**To Reproduce**
When creating an organization, in the description, type long characters and save.

**Expected behavior**
The about section should be moved under the organization image and it shouldn't overflow its container

**Actual behavior**
It overflows its container

**Screenshots**
![Capture](https://user-images.githubusercontent.com/42142223/224047951-0e9f8db7-6553-4c84-99a2-5c4cc05a4903.PNG)

**Additional details**
Additionally, I think we should have a sidebar in the dashboard with an overview section with the Name of the organization, its image if any, the Location of the organization, and then the written description of the organization. We should also have a statistics section in the sidebar that shows the statistics of the organization. The statistics card can be made interactive and we should remove some the buttons on the navbar.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kayceeDev** [comment]
Can I be assigned to this issue?

**Comment by palisadoes** [comment]
What action do you propose as the fix?

**Comment by kayceeDev** [comment]
> What action do you propose as the fix?

I outlined it in the expected behavior and also share more context in the additional details. This is just a sub issue of the overall fix. I will create more issues and mention you. Thanks for assigning me.

**Comment by palisadoes** [comment]
OK.
