### ISSUE TITLE
No prompt for Register button 

### ISSUE THREAD

**Issue by Wineshuga** [PalisadoesFoundation/talawa-admin#609]
**Is your feature request related to a problem? Please describe.**
It is confusing When an admin tries to login on the Login page and there is a register button without a prompt stating the need for the button.

**Describe the solution you'd like**
Some texts should be added to make a user friendly page

**Approach to be followed (optional)**
1. Add texts afterwards to show a need for the Register button on a Login page.
2. Switch colors of button for better UI experience

**Additional context**
![IMG-20230309-WA0026](https://user-images.githubusercontent.com/99335288/224063800-11af4f82-e752-4c08-a68b-3600d6891c74.jpg)

**Comment by palisadoes** [comment]
Please post a screen shot of the new output when submitting your PR.

**Comment by Shugo52** [comment]
Can I be assigned this task?

**Comment by Wineshuga** [comment]
> 

I will do that. Thank you
