### ISSUE TITLE
GitHub Action: JavaScript Code Formatter

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#61]
**Describe the bug**

1. To reduce the risk of conflicting files, we need a standardized way of formatting the JavaScript code before a pull request.
2. [There are a number of solutions for this](https://www.google.com/search?q=GitHub+action+formatter+node.js&oq=GitHub+action+formatter+node.js&aqs=chrome..69i57j69i64.9200j1j7&client=ubuntu&sourceid=chrome&ie=UTF-8)

**To Reproduce**

N/A

**Expected behavior**

N/A

**Actual behavior**

N/A

**Screenshots**

N/A

**Additional details**

Parent Issue: Fix Numerous GitHub Actions Issues #58

## This is labeled as a bug as it hinders our ability to test properly and impacts our ability to launch bug free code. All bugs depend on this issue

**Comment by akshatgarg12** [comment]
@palisadoes Can i work on this? I'll add [run-node-formatter](https://github.com/MarvinJWendt/run-node-formatter) in the github workflow

**Comment by palisadoes** [comment]
@akshatgarg12 You'll need to complete #52 first. We need a:

1. standardized layout for the files
2. predefined order for the execution of GitHub actions

Unpredictable ordering has created difficulties in the past.

**Comment by Rottenblasters** [comment]
@palisadoes can I work on this issue if its no one is working on it ?

**Comment by palisadoes** [comment]
@Rottenblasters [Looking at the GitHub Action for pull requests](https://github.com/PalisadoesFoundation/talawa-admin/blob/develop/.github/workflows/pull-requests.yml), we already have the following running for each Pull Request

- a Linter
- CodeQL 
- Tests

I think this issue is already complete. 

@yasharth291 is my analysis correct?

**Comment by palisadoes** [comment]
This is complete.
