### ISSUE TITLE
Event page and Calender Improvement

### ISSUE THREAD

**Issue by EBILITE** [PalisadoesFoundation/talawa-admin#611]
**Is your feature request related to a problem? Please describe.**
Yes Improving the alignment of all the component for more and better visual uniformity experience

**Describe the solution you'd like**
Improve the calender toggles, the user experience is poorly made and lacks interactivity and good UI: By making the calender Modal  to be able to toggle btw dates and years faster , and also making it possible for the calender Output to display activities of each day inside its units, for interactive

**Describe alternatives you've considered**

Instead of allowing the UI to be clustered together that is not virtually attractive, I suggest making a more classic and user friendly UI, Where users can even see the activities of the day in the calender spaces and time for each. 

**Approach to be followed (optional)**

#First: I will make the components above the calender to be in alignment with other values in the page

#Secondly: Make sure the option to toggle date and time, are not just beiing done with arrow buttons, but make sure it uses calender modal to toggle Month and Years faster, There saving time

Thirdly: I will make the calender session more spaces out, because its clustered together and also make sure, it has the option to input activities for each day.

**Additional context**
Below is a sample of what I wish to implement :

##Current Change
![Talawa-1](https://user-images.githubusercontent.com/42316219/224072013-d38d567c-a487-45b7-9407-4f1d213de011.PNG)
![Talawa-2](https://user-images.githubusercontent.com/42316219/224072028-9e6a4af5-b01e-407d-916d-c762fc468f0c.PNG)

##Suggested Changes sample

![Talawa-3](https://user-images.githubusercontent.com/42316219/224072099-1918d1bf-e2af-4cce-8e42-ee6653814280.PNG)
![Talawa-4](https://user-images.githubusercontent.com/42316219/224072108-cde45f4f-1477-4faf-88ae-daa59f0b9b5a.PNG)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by EBILITE** [comment]
Please assign this issue back to me

Thanks

**Comment by EBILITE** [comment]
Assign to me

**Comment by palisadoes** [comment]
1. @aashimawadhwa If this work is done would it affect the calendar tests?
1. @EBILITE Are you familiar with testing typescript code as we are doing it in this repository?

We need answers to both these questions before assigning.

**Comment by EBILITE** [comment]
I'm not so strong at writing tests in typescript but I believe with help it will be possible.

**Comment by aashimawadhwa** [comment]
@palisadoes  yes test will be affected with this change and will drop

**Comment by EBILITE** [comment]
With your help @aashimawadhwa, cant we work it out.

**Comment by noman2002** [comment]
This is just a UI change and we just shifted to calendar view and its working fine there is no need to change the UI and also writing test is will be very complicated for it. 
@palisadoes I think we should not proceed with this. This is not needed for now.

**Comment by satyamksharma** [comment]
Hi there, I'm an outreachy contributor and i would like to work on this issue as I have some design I would like to apply so I request to assign me @palisadoes 
thank you

**Comment by palisadoes** [comment]
Thanks Noman. Closing
