### ISSUE TITLE
Feature Request: In place of these images we can use direct link

### ISSUE THREAD

**Issue by lata-11** [PalisadoesFoundation/talawa-admin#615]
**Is your feature request related to a problem? Please describe.**

Currently, we have images of the link in place of the link itself. This may be a bit time taking for someone interested in opening these links.

**Describe the solution you'd like**

We can replace these link images with the link itself so we can open it directly without going into the browser and typing.

**Describe alternatives you've considered**

We can also have both the images of link and links too here.

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
![image](https://user-images.githubusercontent.com/103296906/224080655-cce2b42b-7855-4d14-8be2-7be6200b40a9.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by lata-11** [comment]
I want to work on this issue. Please assign me.

**Comment by palisadoes** [comment]
Thanks for noticing this. We don't want to have links as spammers will use them to send us emails. Closing.
