### ISSUE TITLE
Feature Request for pagination

### ISSUE THREAD

**Issue by akankshat05** [PalisadoesFoundation/talawa-admin#616]
**Is your feature request related to a problem? Please describe.**
The fields in pagination are not properly aligned.
Desktop :
![pagination_desktop](https://user-images.githubusercontent.com/72144454/224082342-8c17c4c0-d9ef-46da-a78c-4281f106be8e.png)
Mobile :
![pagination_mobile](https://user-images.githubusercontent.com/72144454/224082366-8f568cb6-5474-494e-87fe-65789880409d.png)

**Describe the solution you'd like**
Fields should be aligned properly and pagination can be centered.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Yemihunter** [comment]
Hello, I would love to solve this issue, can I be assigned this?

**Comment by palisadoes** [comment]
We are focusing on two types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of serious bugs. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing

**Comment by Yemihunter** [comment]
Alright, thanks for the feedback.
