### ISSUE TITLE
Improving the Visibility and Alignment of the Pagination Component

### ISSUE THREAD

**Issue by EBILITE** [PalisadoesFoundation/talawa-admin#618]
**Is your feature request related to a problem? Please describe.**
Component not well aligned and not visibily seen , this is not good for those with eye issues.

**Describe the solution you'd like**

first: I will align the component and there happens to be places where the component are rendered twice, will remove those that occured twice in the pages

secondly: : A good pagination UI should be on a little bolder in text or size for those with eyes issues

**Describe alternatives you've considered**

None

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

#current screenshot
![Talawa-5](https://user-images.githubusercontent.com/42316219/224091466-93fec5a7-7d04-450a-95cc-5c2df15656b7.PNG)

#suggested screenshot

Please this is not to redo the whole Component But to Increase the font and alignment
![Talawa-6](https://user-images.githubusercontent.com/42316219/224092207-8cd45792-16a3-4ac8-9126-232784871d73.PNG)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by EBILITE** [comment]
Assign this issue to me

**Comment by EBILITE** [comment]
Hi @satyamksharma, I created the issue was waiting for approval, its also fine if the mentor approve of two people working on it but its a slight error anyway.

**Comment by satyamksharma** [comment]
Can I be Assigned?

**Comment by akankshat05** [comment]
@EBILITE @palisadoes this issue was already opened., #616
