### ISSUE TITLE
Bug Report : Event Modal form does not close automatically after submitting a new event

### ISSUE THREAD

**Issue by SamMintah** [PalisadoesFoundation/talawa-admin#625]
**Describe the bug**
When creating a new event on the event page, the modal form does not close automatically after submitting the event. This can lead to confusion for users who expect the form to close after successful submission.

**To Reproduce**

1.Go to the event page
2.Click on the "Create Event" button
3.Fill in the required fields and submit the form
4.Notice that the modal form does not close automatically

**Expected behavior**
The modal form should close automatically after successful submission of the event.

**Actual behavior**
The modal form remains open after submitting the event.

**Screenshots**
![mobile (6)](https://user-images.githubusercontent.com/100992913/224122210-aab47d4c-5234-4b6a-a396-d45925d98938.gif)

**Additional details**
Impact:
This bug affects user experience by causing confusion and frustration. It should be fixed as soon as possible.

Priority:
This bug has a medium priority, as it does not affect the functionality of the website, but it does impact user experience.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by SamMintah** [comment]
I would like to work on this.

**Comment by Kelvyn2012** [comment]
Hi I would like to work on this. @palisadoes

**Comment by noman2002** [comment]
@SamMintah Fixed in #623

**Comment by SamMintah** [comment]
@noman2002 this is a different bug regarding "event" modal the  issue #623 is about post
kindly recheck  thanks.
