### ISSUE TITLE
Date Picker view in the events section

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#627]
**Is your feature request related to a problem? Please describe.**
Currently we have filter functionalities in the event section which are now not working for the calendar, we can replace it with a live small DatePicker.

**Describe the solution you'd like**
A small date picker like in general calendars
**Actual behaviour**
![Screenshot 2023-03-10 at 12 54 30 AM (2)](https://user-images.githubusercontent.com/73706697/224133004-81ade040-9fb1-4bff-9d4a-22db666b9ca3.png)

**Expected behaviour**
![Screenshot 2023-03-10 at 12 18 16 AM (2)](https://user-images.githubusercontent.com/73706697/224125410-a44095f0-e5d8-4e34-be7f-6d6baf2fcfcb.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
I would like to take this issue.

**Comment by palisadoes** [comment]
Unassigning due to inactivity others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by aashimawadhwa** [comment]
Sir I have started working on itnI had my exams previously. Will make an pr today.

**Comment by Jemeelah1** [comment]
@palisadoes can i take up this issue

**Comment by palisadoes** [comment]
> @palisadoes can i take up this issue

There is an active pull request related to this.

**Comment by aashimawadhwa** [comment]
I am making some changes in the date-picker @palisadoes  will update ASAP
