### ISSUE TITLE
Bug Report - Inatalling docusaurus when using npm specific information from the docs does not install succesfully

### ISSUE THREAD

**Issue by Collette-vershalli** [PalisadoesFoundation/talawa-admin#630]
**Describe the bug**
Installing docusaurua using the npm specific information from the docs as an option for the installation process does not install docusaurus successfully

**To Reproduce**

1. Follow the steps under the  npm specific information installation option from the docs.
2. Run the  three commands under step 3 still for the npm specific information installation option from the docs.

**Expected behavior**
All three commands are supposed to run successfully, followed by the installation of docusaurus.

**Actual behavior**
Only the first 2 commands run the last command "npm install docusaurus" keeps sending an error message preventing the next command from running to open the browser.

**Screenshots**
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Collette-vershalli** [comment]
I would like to work on this issue @palisadoes , @xoldyckk

**Comment by palisadoes** [comment]
Closing. This is the wrong repository.
