### ISSUE TITLE
Change search bar location

### ISSUE THREAD

**Issue by kayceeDev** [PalisadoesFoundation/talawa-admin#633]
**Describe the bug**
The search bar in the organization list is not well placed and should be moved as it affects the UI of the application.

**To Reproduce**

1. When you log in you will see the search bar in the header.

**Expected behavior**
The search bar should be under the "organization list header" and should be styled properly.
The search can be either in the middle taking the full width of the container or you can bring down the "create organization" button with the search bar and place them side by side under the organization header. Make sure they are properly aligned.
Make styling consistent on mobile.

The screenshot should give you an intuition of expectations.
![Capture](https://user-images.githubusercontent.com/42142223/224244354-1f16d9d6-e095-41a7-b91c-f7829e96698d.PNG)
![Capture](https://user-images.githubusercontent.com/42142223/224244477-539ded8b-0e12-4418-82d7-65adb68ce852.PNG)

**Actual behavior**
Currently, the search bar is placed in between the "Organization list header" and the "Create organization button".
There is no equal spacing provided between the search bar and other headers.
The styling is not consistent on mobile.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/42142223/224242724-cb7b25be-80e0-4990-a8c3-16cf5bf06859.PNG)
![Capture](https://user-images.githubusercontent.com/42142223/224243013-b8fa40c2-dac4-4462-a985-2b09a8268422.PNG)
![Capture](https://user-images.githubusercontent.com/42142223/224243899-ab91ee36-6e62-47a2-96ed-e28fb38a2013.PNG)

**Additional details**
Let your creativity go wild. Make things beautiful.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sumitmaithani** [comment]
hey can I take this issue?

**Comment by arushi2715** [comment]
hey @kayceeDev i would like to work on this.
Please assign this to me.

**Comment by palisadoes** [comment]
@kayceeDev Please ask for comments on this. Admin has been crashing recently because of PRs without adequate tests. Find out how to do them as part of this issue from slack.

**Comment by kayceeDev** [comment]
> @kayceeDev Please ask for comments on this. Admin has been crashing recently because of PRs without adequate tests. Find out how to do them as part of this issue from slack.

Do you mean I should ask for opinions on slack or I should ask contributors what steps they would take to achieve the expected results?

**Comment by KASHISH17RAMANI** [comment]
can i take up this issue?
