### ISSUE TITLE
Organization card image not taking full width on mobile

### ISSUE THREAD

**Issue by kayceeDev** [PalisadoesFoundation/talawa-admin#634]
**Describe the bug**
The organization card doesn't take full width on mobile view

**To Reproduce**

Shrink screen size below 400px

**Expected behavior**
Card images should take full width on mobile.

**Actual behavior**
The images are smaller than the container on mobile view.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/42142223/224247063-bb8e7585-f1c7-464d-bd75-0f219e1e092f.PNG)

**Additional details**
While this issue is well described, you can be more creative. You can improve the card fonts, add border or box shadows to each card and add more spacing between cards on mobile.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by NabajitS** [comment]
I would like to work on this issue.

**Comment by arushi2715** [comment]
hey @kayceeDev i would like to work on this.

**Comment by palisadoes** [comment]
Unassigning due to inactivity others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by kayceeDev** [comment]
Hello @palisadoes I will make a PR on this issue today. Please reassign me.

**Comment by kayceeDev** [comment]
Changes pushed. Waiting for reassignment to make a PR @palisadoes
