### ISSUE TITLE
Screen Responsiveness: Unresponsive on bigger and small screen display

### ISSUE THREAD

**Issue by EBILITE** [PalisadoesFoundation/talawa-admin#640]
**Describe the bug**

There is lack of responsiveness and staying together of the web pages component, when viewed on bigger screen or smaller screen type, affects the uniformity of the pages or screen.

**To Reproduce**

1. Set a general max-width to the whole page
2. Give it a minWidth or width where needed.

**Expected behavior**

The Web page should always stay together no matter the screen being viewed on, Mostly in big screens because not doing so will affect the display if we are in the near future try to project the project in a bigger screen only to be seeing lack of uniformity in the display of the components.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

When Zooming in and out the web page there are lack of uniformity  of the whole component, meaning it stretches and make the UI look bad and when zoomed in, it clusters the whole images together.

**Screenshots**

![Talawa-1](https://user-images.githubusercontent.com/42316219/224294721-4947b2ea-800f-4b79-8a1a-903bcccd3f2a.PNG)
![Talawa-2](https://user-images.githubusercontent.com/42316219/224294742-47e86ab1-9e8a-4856-a296-6a68e5dfea8f.PNG)

**Additional details**

Using Github platform as Example : No matter how you zoom in there is uniformity on how it displays

![Talawa-3](https://user-images.githubusercontent.com/42316219/224295407-65db2616-83d0-49b2-84f3-7ea3174b9a6e.PNG)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by EBILITE** [comment]
Kindly Assign this issue back to me, when approved

**Comment by noman2002** [comment]
We are currently focusing on basic functionality to be working  for now, please try to find some functionality break and feel free to create a issue for that.
