### ISSUE TITLE
Remove the Overlapping

### ISSUE THREAD

**Issue by akhilender-bongirwar** [PalisadoesFoundation/talawa-admin#641]
**Describe the bug**
Plugins dropdown menu when opened is overlapping with All Organizations button 

**To Reproduce**
While on a desktop view, try minimizing the page to a mobile view to see the distortions.

**Expected behavior**
There should be a margin between them for clear view.

**Actual behavior**
There is no margin between them and they look like they overlap each other.

**Screenshots**
The Problem
![palisadoes](https://user-images.githubusercontent.com/112749383/224307337-771f3986-039f-4321-a007-e974ad48e3f8.png)

**Additional details**
The bootstrap of these elements should be adjusted to improve the UI.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akhilender-bongirwar** [comment]
Please assign this issue to me when approved.

**Comment by adi-uchiha** [comment]
@akhilender-bongirwar Please read pinned message in #talawa-admin on slack

**Comment by akhilender-bongirwar** [comment]
> @akhilender-bongirwar Please read pinned message in #talawa-admin on slack

@adi-uchiha Thank you for informing me. Will check that out

**Comment by akhilender-bongirwar** [comment]
Hi @noman2002, could you please review the PR and accept it.
