### ISSUE TITLE
Bug Report : orglist pagination is not aligned

### ISSUE THREAD

**Issue by Sumitmaithani** [PalisadoesFoundation/talawa-admin#643]
**Describe the bug**
In /orglist the pagination is not properly aligned.

**To Reproduce**

1. First login to website.
2. Go to /orglist and find at the bottom pagination.

**Expected behavior**
![Talawa Organizations - Google Chrome 3_10_2023 7_01_43 PM](https://user-images.githubusercontent.com/86047367/224330155-ba34e1b1-ee01-40d8-b305-82c8a6a902d7.png)

**Actual behavior**
![Talawa Organizations - Google Chrome 3_10_2023 7_02_08 PM](https://user-images.githubusercontent.com/86047367/224330235-1c942067-b0d2-4308-8b3e-919043459c58.png)

I would like to work on this.

**Comment by jadeharr** [comment]
@Sumitmaithani this issue has been referenced in #635. Since it is a duplicate this will be closed.
