### ISSUE TITLE
Feature Request : use of toast in place of window.alert 

### ISSUE THREAD

**Issue by Sumitmaithani** [PalisadoesFoundation/talawa-admin#645]
**Is your feature request related to a problem? Please describe.**
To impore UI we can use of toast in place of window.alert and in button text should be "Update Event".

**Describe the solution you'd like**
In window.alert we can replace by toast because it already use in most of place to make UI similar in all pages.

**Approach to be followed**
1. First Login to website.
2. Create organization and go to manage.
3. Then from navbar go to Events section.
4. Click on Add event and create event.
5. Now edit event and click on Update Post also edit this to "Update Event".
6. You see window alert same seen on deleting the event also.

**Screenshot**
**Actual behavior**
![Talawa Posts - Google Chrome 3_10_2023 8_13_28 PM](https://user-images.githubusercontent.com/86047367/224348096-8670a22b-2499-4c64-99b0-a399b41b8b53.png)

**Expected behavior**
![Talawa Events - Google Chrome 3_10_2023 8_15_00 PM](https://user-images.githubusercontent.com/86047367/224348012-c5a62840-da05-47e1-a169-8ee4176567f4.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

I would like to take up this issue.

**Comment by Girish-Jangam** [comment]
Could you please assign this task to me

**Comment by KrutikaBhatt** [comment]
Hey, @palisadoes can I take this issue?

**Comment by palisadoes** [comment]
@Sumitmaithani Do you want to be assigned this issue?

**Comment by BhuvaneshPatil** [comment]
I have mentioned same [here](https://github.com/PalisadoesFoundation/talawa-admin/issues/403#issuecomment-1455076639).

I am also working on the same, the reason behind doing it (at many places) is to refresh the page once user clicks the button in alert dialog, and this refresh is for updating the data in component.
When we submit the data using child component, there is no way implemented to update parent component's state, I am experimenting with possible ways for doing the same.

**Comment by Sumitmaithani** [comment]
@palisadoes yes i want to take this issue and @BhuvaneshPatil by using toast we can refresh the page also.
