### ISSUE TITLE
Bug: No way to add new members and update info in the people section of an organization

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#646]
**Describe the bug**
Currently it shows that there is only single member in the Org and there is only the remove funcitonality in it...Instead we should have this functionality...

**To Reproduce**

1.Open talawa-admin portal 
2.Click on manage button on any organization
3.Move to the people section from the navbar

**Expected behavior**
There should be some way to add members and also update himself
**Actual behavior**
No way to do so

**Screenshots**
![image](https://user-images.githubusercontent.com/107215525/224378636-e212b8a9-d1ea-493a-9068-b6d30f18bf92.png)

**Comment by anurag0006** [comment]
I think this is needed and we also have a gsoc idea organizing people and newsfeed...Solving this issue earlier can reduce the workload in gsoc period...

**Comment by anurag0006** [comment]
i was trying to figure out how to solve this issue and came to see that to add a user to admin, he/she needs to an memeber first
![image](https://user-images.githubusercontent.com/107215525/224504476-7230bf97-3e17-4370-ae65-a30f64a72583.png)

because of this, i am thinking of adding a button on users page  to add user to member first?
@palisadoes any thoughts on this?

**Comment by palisadoes** [comment]
Yes we will need this functionality because it will help with the required checkin process that most apps like Talawa have.

**Comment by anurag0006** [comment]
Then i will have to first create a mutation query on the api first then.., i shall now create a issue on api side first
