### ISSUE TITLE
Search bar not mobile responsive

### ISSUE THREAD

**Issue by Ladyperpetua** [PalisadoesFoundation/talawa-admin#647]
I noticed that the search bar for the organization is not mobile responsive. I would like to work on it by making the placeholder text visible.
I would like this issue to be assigned to me.

**Comment by anurag0006** [comment]
@Ladyperpetua  You should clearly state the issue...Please attach scrreenshots and more relevant info related to the issue else the mentors will discard this issue

**Comment by Ladyperpetua** [comment]
okay, thank you...i'll get more information about the issue and try again

**Comment by noman2002** [comment]
Insufficient information in the first comment. Please follow the issue template for creating an new issue and please attach a screenshot for reference.
