### ISSUE TITLE
inconsistent styling with the login and logout button on mobile

### ISSUE THREAD

**Issue by Ladyperpetua** [PalisadoesFoundation/talawa-admin#649]
**Describe the bug**
the padding and the width of the login button is inconsistent with the logout button
**To Reproduce**

1.open the talawa app website on your mobile
2.click on the hamburger menu

**Expected behavior**
![expected-behaviour](https://user-images.githubusercontent.com/70077989/224424034-d931de53-de2c-4698-9c6b-a4ac2dc7a7c7.jpeg)

**Actual behavior**
![actual-behaviour](https://user-images.githubusercontent.com/70077989/224424594-6ca2bf3f-0e53-4917-8c37-efce6fc6abf2.jpeg)

**Comment by noman2002** [comment]
@Ladyperpetua I'm not able to reproduce this.
