### ISSUE TITLE
Allow users to send request to join private organizations

### ISSUE THREAD

**Issue by bonnie-23** [PalisadoesFoundation/talawa-admin#65]
**When a user views a private organization** 

- The user should be presented with the option to send a request to join the organization.
- A notification should appear in the admin portal  for that organization.
- The administrator should have the option to approve or decline the request to join #63

**Comment by Maagztech** [comment]
sir can i start working on this issue.

**Comment by cAmartya** [comment]
hey, @bonnie-23 , I wan to work on this issue, if it has not been previously fixed. Can you assign it to me?
