### ISSUE TITLE
Isolate Admins from Viewing any Super Admin pages

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#650]
**Is your feature request related to a problem? Please describe.**
Admins of several organizations may control the personnel and operations of their own organizations using talawa-admin. Presently, when you attempt to connect into talawa-admin, you are logged in as super-admin and are able to access information for other organizations in addition to your own.
You can refer to the image below.
![11](https://user-images.githubusercontent.com/58592306/220532908-12fc733f-8ed6-4c02-b83a-cf9a8f42f1e8.PNG)

**Describe the solution you'd like**
1. The login screen should stay the same, but when a user enters their credentials, it should automatically determine if they are an admin or a super-admin. 
1. Although the super admin might travel down through all the organizations, the admin should only be allowed access and view their specific organization.
1. No screens accessible only to Super Admins must be visible to Admins.
1. If an Admin gets sent a link to a Super Admin page while they are logged in as an Admin, then there should be no access provided.

This is an extension of this issue:
- https://github.com/PalisadoesFoundation/talawa-admin/issues/493

**Current  Behaviour**

https://user-images.githubusercontent.com/16875803/224429182-092ce9ca-c0ff-4ce3-9202-a8e1c4b01ed6.mp4

**Describe alternatives you've considered**
The contributor can come up with her/ his own ideas.

**Approach to be followed**
- We want to minimize changes to the existing design. Keep the current design.
- Code coverage for all files editor must be 100%

**Additional context**
 - API calls may have to be modified and the relevant issues created

**Comment by aashimawadhwa** [comment]
@palisadoes  what are the pages and functionalities that are specifically accessible to admins ?

**Comment by palisadoes** [comment]
1. They should not be able to access the manage organizations screen.
1. The manage organizations button should not be visible
1. An admin shouldn't be able to delete their own organization, because what would the next screen be?
1.  Any screen that allows them to change or view the information or state of other organizations.

**Comment by aashimawadhwa** [comment]
So I think an admin can only navigate in roles and request section? As we're not giving access to manage the organization, to solve this

We can do conditional rendering, wdyt will this be the correct approach?

**Comment by palisadoes** [comment]
The only conditional rendering I can see is the `manage organizations` and `delete organization` buttons on the Admin screen. The Super Admin menus would not need that. I'm not an expert in this field, I'm assuming what this means.

Please ask community members on Slack for suggestions.

**Comment by techfussion** [comment]
@palisadoes I would like to work on this

**Comment by palisadoes** [comment]
> @palisadoes I would like to work on this

Our policy is to assign no more than two issues to each contributor. This way everyone gets a chance to participate in the projects. We sometimes give exceptions for more urgent cases and sometimes we lose track, but the policy stands. You have reached your limit, please wait until your existing issues are closed before requesting more issues. You could unassign yourself from one of the other issues too.

**Comment by aviraldevv** [comment]
@palisadoes I would like to work on this issue.

**Comment by AnishaSingh0118** [comment]
@palisadoes since most of the issues have already been taken up in this case what should we do?

**Comment by kayceeDev** [comment]
> @palisadoes since most of the issues have already been taken up in this case what should we do?

You shouldn't worry. The interns' task will be revamped soon and you can take a shot at it. There is still an opportunity for you to make contributions.

**Comment by aviraldevv** [comment]
@palisadoes I have done some changes if it looks sufficient to you I will submit a PR.

SUPERADMIN-

![Screenshot_453](https://user-images.githubusercontent.com/121368112/226329550-3c1a31d4-82f9-4385-a8ff-9441f03660c7.png)

![Screenshot_454](https://user-images.githubusercontent.com/121368112/226329629-d1e466b8-ad07-46ba-a954-045e617eaef5.png)

ADMIN-

![Screenshot_451](https://user-images.githubusercontent.com/121368112/226329698-bca89837-c19a-49d8-88cd-1df886531c02.png)

![Screenshot_452](https://user-images.githubusercontent.com/121368112/226329753-e9abe1fe-c49e-4592-b5b9-0907fa95321e.png)

**Comment by palisadoes** [comment]
1. Can we use an icon instead of the "All Organizations" button?
2. Why do we have the hamburger icon on the organization, but it disappears for Super Admin? They should be the same.
3. Similarly the logout mechanisms should be the same, preferably under the hamburger
 

Submit your PR with these changes.

![image](https://user-images.githubusercontent.com/16875803/226396340-7a57c43e-0a7b-4e24-be58-db5693e57229.png)

**Comment by aviraldevv** [comment]
@palisadoes 
1. I have conditionally rendered "Your Organization" button in case of ADMIN.
2. Also fixed the relative position of the hamburger icon.

Before:
![Screenshot_462](https://user-images.githubusercontent.com/121368112/227333828-01552401-e0e9-44a2-b69c-101d64b2c646.png)

After:
![Screenshot_463](https://user-images.githubusercontent.com/121368112/227334115-f3e13a7a-eb17-42d0-ad25-f479d4983a2f.png)

3. Regarding the addition of hamburger icon for the ADMIN/SUPERADMIN list page instead of logout and multi lingual support button. I feel we should not change the present UI for the page as we have very less fucntionality for now, removing them would make the page look empty. What are your views on this??

**Comment by palisadoes** [comment]
Please proceed with this approach. The final GSoC layouts will probably build upon this workflow.

**Comment by aviraldevv** [comment]
Shall I then add hamburger icon instead of login and multi lingual support button?? Or proceed with my current changes??

**Comment by palisadoes** [comment]
The icons in the images are OK

**Comment by Pranauv-Kumar1803** [comment]
@palisadoes Correct me if I'm wrong.
An Admin can still manage the organization like add events and manage them.
So it is just the delete organization from the org dashboard that we are not rendering right?

**Comment by palisadoes** [comment]
Partially correct. An admin must have absolutely no access to the super admin screens. They must not be able to see which organizations are available to be managed by the super admin.

**Comment by Pranauv-Kumar1803** [comment]
> Partially correct. An admin must have absolutely no access to the super admin screens. They must not be able to see which organizations are available to be managed by the super admin.

So, As an admin can manage his org, shouldn't it be manage button for admin also? Why is it view?

**Comment by Pranauv-Kumar1803** [comment]
> I don't understand, please clarify.

Since an admin can still add events and manage his particular organization, why is the button on the org list for admins saying "view" instead of "manage"?

**Comment by palisadoes** [comment]
1. Yes, it should be `manage`
2. (In future, after this PR) Ideally the Admin should login and go straight to some type of dashboard about the status of their organization. So the manage button would not transfer the Admin to a SuperAdmin URI endpoint.

**Comment by Pranauv-Kumar1803** [comment]
> 1. Yes, it should be `manage`
> 2. (In future, after this PR) Ideally the Admin should login and go straight to some type of dashboard about the status of their organization. So the manage button would not transfer the Admin to a SuperAdmin URI endpoint.

Also, if say an org is deleted, should the concerned admin still hold his position or be removed of it?

**Comment by Pranauv-Kumar1803** [comment]
> It would be an invalid state, so yes.

removed of it?
