### ISSUE TITLE
Feature Request: Clickable Links and Browsable profiles in all screens

### ISSUE THREAD

**Issue by rishav-jha-mech** [PalisadoesFoundation/talawa-admin#654]
**Is your feature request related to a problem? Please describe.**
The Roles and Request screen don't have clickable links on profile.
The Block/Unblock screen don't have clickable links too.

**Describe the solution you'd like**
The roles and requests screen should have clickable links, because for an admin to change the status of Role/User-Type he may need to see the profile of that user.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
These names should be clickable.
![Talawa Roles - Google Chrome 11-03-2023 07_08_50](https://user-images.githubusercontent.com/76212518/224457945-c7ae77f6-1130-4790-bad6-0afc1c853549.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by rishav-jha-mech** [comment]
Please assign this to me

**Comment by noman2002** [comment]
We are not planning to implement this for now. This is not appropriate for our current design.
