### ISSUE TITLE
Bug Report : On Adding Event checkbox of "Recurring Event", "Is Registrable?" is not working

### ISSUE THREAD

**Issue by Sumitmaithani** [PalisadoesFoundation/talawa-admin#658]
**Describe the bug**
On Adding Event checkbox of "Recurring Event", "Is Registrable?" is not working. On click in checkbox still on edit it is not checked.

**To Reproduce**

1. Login the website and create organization.
2. Click on manage organization.
3. Go to event section and add event.
4. On filling event details check "Recurring Event", "Is Registrable?" box and create event.

**Expected behavior**
On Adding Event checkbox of "Recurring Event", "Is Registrable?" it should work.

**Actual behavior**

https://user-images.githubusercontent.com/86047367/224483841-fb5e8c00-249d-4b52-9813-e7341ac876d4.mp4

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akankshat05** [comment]
hello @Sumitmaithani, can I work on this?

**Comment by Sumitmaithani** [comment]
@akankshat05 Yes, you can

**Comment by akankshat05** [comment]
@palisadoes can I please be assigned to this. Thank you

**Comment by aashimawadhwa** [comment]
There are four checkboxes as of now that is all day , registrable, reoccurring and public 

All day event and reoccurring:  until all day calendar view is implemented this checkbox functionality cannot work

Registrable and public : we're planning to give calendar access to only superamin so we have to make a interface where members can perform registration and  then only this checkbox will work

@palisadoes .

**Comment by palisadoes** [comment]
> There are four checkboxes as of now that is all day , registrable, reoccurring and public
> 
> All day event and reoccurring: until all day calendar view is implemented this checkbox functionality cannot work
> 
> Registrable and public : we're planning to give calendar access to only superamin so we have to make a interface where members can perform registration and then only this checkbox will work
> 
> @palisadoes .

1. People should be able to register through:
    1. the mobile app as an end user
    2. an admin using Talawa-admin.
    3. a future type of Talawa-admin user with limited access to Admin features.
1. These checkbox flags will need to remain.

**Comment by kamtoeddy** [comment]
I would love to work on this. Can I be assigned?

**Comment by palisadoes** [comment]
Fix everything here. We need to reduce our issue and PR review workload.
