### ISSUE TITLE
Bug Report : On Settings -->  Update Your Details page all inputs default value are blank.

### ISSUE THREAD

**Issue by Sumitmaithani** [PalisadoesFoundation/talawa-admin#660]
**Describe the bug**
On settings if you go to update your details you find all inputs default value are blank not similar to update organization page.

**To Reproduce**

1. Login the website and create organization.
2. Click on manage organization.
3. Go navbar right corner organization logo in settings.
4. Click on Update Your Details in left side.

**Expected behavior**
In Update Your Details page all inputs have your current details like firstname, lastname ..etc. just like in update organization page.

**Actual behavior**
In Update Your Details page all inputs default value are placeholder text.

**Screenshots**

https://user-images.githubusercontent.com/86047367/224485663-96401695-2b39-4bae-9548-84ba75a87b7a.mp4

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by anshgoyalevil** [comment]
@Sumitmaithani 

This issue is being resolved by the PR https://github.com/PalisadoesFoundation/talawa-admin/pull/657

You may close this issue.
