### ISSUE TITLE
Feature Request - Adding images and videos to posts

### ISSUE THREAD

**Issue by Phyya** [PalisadoesFoundation/talawa-admin#662]
**Is your feature request related to a problem? Please describe.**
I noticed that when i added an image or video when creating a post, nothing happens. Same as when updating. So I took a look at the codebase and I saw that the feature is yet to be implemented.

**Describe the solution you'd like**
The fields  $imageUrl: URL and videoUrl: $videoUrl suggests that URLs need to be provided. How would these URLs be generated?
I suggest Firebase or Cloudinary to host the assets. Or let me know if there is an alternative? 

**Describe alternatives you've considered**
No alternatives. The input fields are there on the form, meaning it has been intended.

**Approach to be followed (optional)**
The approach would be to first host these assets add the URLs to the missing fields in the data submitted when creating a post. Or changing the graphql mutations from URL to file, maybe?

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Phyya** [comment]
Hello, I would really like to look into this. Thank you

**Comment by palisadoes** [comment]
This is being addressed here.

- https://github.com/PalisadoesFoundation/talawa-admin/issues/538
- https://github.com/PalisadoesFoundation/talawa-api/issues/952 (Background)

Please communicate with @ kb-0311 for details. There may be scope for improvement. Please read the background issue.

Closing.
