### ISSUE TITLE
Feature Request : Style the sidebar on the dashboard.

### ISSUE THREAD

**Issue by Graycemuthui** [PalisadoesFoundation/talawa-admin#663]
**Is your feature request related to a problem? Please describe.**
The sidebar on the dashboard page seems to be quite flat . Therefore my thought is to style it make the content more concise. This will help improve the users experience with the page.

**Describe the solution you'd like**
Well for one all the different features on the container will be more clear and adding a bit of styling will help the dashboard look better of course taking note of the color palette.

**Describe alternatives you've considered**
Using different stylings to separate the content on the sidebar.
Making the description look more appealing.

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Please provide screen shots of what you plan to do.

**Comment by Graycemuthui** [comment]
This is the part I'm talking about. Thinking we could add the name of the organization as well in the about section.

![palisadoes](https://user-images.githubusercontent.com/95374858/224472165-14b05ae7-6247-428c-893d-408068a4efa6.jpg)

**Comment by palisadoes** [comment]
Isn't the name of the organization already in the menu bar?

**Comment by Graycemuthui** [comment]
I mean but we can still do something about the sidebar add some touch. Just some basic styling on it.

**Comment by palisadoes** [comment]
Please be specific. It's important to know what you are planning to do. Screen shots, diagrams, paragraphs etc.

**Comment by Graycemuthui** [comment]
As you can see on the picture one of the styling I can done is putting in a hover styling whenever someone taps on the description or even the image. Also if its okay I can create a dark mode palette for the admin page.

![remy](https://user-images.githubusercontent.com/95374858/224507378-87a88791-9897-45bd-b81e-71109eb05cd1.jpg)

**Comment by noman2002** [comment]
@Graycemuthui Currently we are focusing on functionality only, We are not planning any major UI change for now. Don't be discouraged, please try to find some functionality breaks and feel free to create an issue for that.
