### ISSUE TITLE
Adding a preview modal for the events in the calendar.

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#664]
**Is your feature request related to a problem? Please describe.**
Currently, we can only edit and delete the event, there is no preview for the event. A view modal for the same  can help to solve this.

**Describe the solution you'd like**
A preview modal that will pop up on clicking upon the event

**Approach to be followed (optional)**
There exists a lot of modals in the talawa admin web application , I will take inspiration from one of them to create this one.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
@palisadoes  can you please assign this to me?

**Comment by palisadoes** [comment]
We need the tests done at the same time.

**Comment by aashimawadhwa** [comment]
okay sure I will write the test in this PR itself, thankyou. @palisadoes
