### ISSUE TITLE
Restore the Talawa Logo to the Menu Bar & More

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#666]
**Is your feature request related to a problem? Please describe.**

Branding of our product is important.  When an organization is selected:

1. the talawa logo disappears
2. the right and left hand icons in the menu bars are identical

**Describe the solution you'd like**

1. A way for the Talawa icon to be restored while showing the organization icon and name
1. The icon to the top right to be replaced with a standard one suitable for its function. A user profile photo will not be appropriate at this time.

**Comment by Muvvahhed** [comment]
can you assign this to me to work on? Thank you

**Comment by AnishaSingh0118** [comment]
Hello @palisadoes is this an issue or do we have to suggest ideas for improvement ?

**Comment by pushpanjali-10** [comment]
Hello, I would love to work on this to get it fixed.

**Comment by palisadoes** [comment]
> Hello @palisadoes would love to work to get it fixed.

If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by palisadoes** [comment]
> Hello, I would love to work on this to get it fixed.

If the issue has already been assigned, please don't ask to be assigned. We want everyone to get a chance.

**Comment by Frey0-0** [comment]
Hey @palisadoes if there is not activity on this issue, I would like to work on this and complete it.

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
