### ISSUE TITLE
Request for Storybook Documentation of Frontend Components

### ISSUE THREAD

**Issue by adepeju4** [PalisadoesFoundation/talawa-admin#667]
Is your feature request related to a problem? Please describe.
 As a developer, having access to clear and concise documentation is essential to understand how to use these components effectively. Unfortunately, I have been unable to find sufficient documentation for Talawa's frontend components.

Describe the solution you'd like
I would like to request the addition of Storybook documentation for Talawa's frontend components. Storybook is a great tool for documenting UI components and provides a clean and user-friendly interface for developers to browse, search and test components. With Storybook documentation, it would be easier for developers to understand how to use these components, see examples, and customize them as per their requirements.

Describe alternatives you've considered
I have considered creating a documentation website or a PDF file, but these options would be less interactive and less developer-friendly than Storybook. Moreover, it would require a significant amount of time and effort to create and maintain such documentation.

Additional context
I believe that having proper documentation for frontend components is crucial for the success of any project. Moreover, Storybook documentation will not only help Talawa's current users but also attract new users to use Talawa's components in their projects.

**Comment by palisadoes** [comment]
@adepeju4

1. How would this integrate with our current automated TSdoc automated workflow to the Talawa-Docs repository? 
2. How can we make this work with Talawa-Docs in general. Does it need to reside in Talawa-Admin?

Your comments would be welcome. 

- @tasneemkoushar 
- @evasharma12 
- @anwersayeed

**Comment by adepeju4** [comment]
I believe that the Storybook documentation can reside in a separate repository, possibly named Talawa-UI-Components or Talawa-UI-Storybook. This repository can be integrated with the existing automated TSdoc workflow in Talawa-Docs by adding a script to automatically deploy the Storybook documentation to a dedicated section or page on the Talawa-Docs website.

In addition, we can set up an automated process that listens for changes to Talwa's frontend components in Talwa-Admin, and automatically updates the Storybook documentation in Talawa-UI-Storybook. This process can ensure that the Storybook documentation remains up-to-date with the latest changes to Talwa's frontend components.

I believe that separating the Storybook documentation into its own repository provides several benefits, including modularity, easier maintenance, and clearer separation of concerns. It also allows developers to easily reference the Storybook documentation without having to navigate through Talawa-Admin or other repositories.

I'm open to any additional suggestions and feedback!

**Comment by anwersayeed** [comment]
Hi @adepeju4 , please connect with me on Slack (anwersayeed) and explain to me about the automated process for changes to Talwa's frontend components.

**Comment by adepeju4** [comment]
> anwersayeed

okay, i'll message you soon

**Comment by evasharma12** [comment]
> Hi @adepeju4 , please connect with me on Slack (anwersayeed) and explain to me about the automated process for changes to Talwa's frontend components.

@anwersayeed Please continue the conversation here only.
If discussed here, other contributors can also put in their ideas and keep a healthy discussion.

Thus, maintain transparency, and knowledge of the project status to everyone and for future references as well.

**Comment by adepeju4** [comment]
Hi @evasharma12 @palisadoes @anwersayeed 

Thanks for your interest in the automated process for changes to Talwa's frontend components.
first, we need to differentiate the ui components from the functional components, then fetch changes from the folder in the ui-components.
we can detect the changes by creating a pipeline that compares the current ui-components folder with the incoming ui-components folder on the PRs. Run a diff command and fetch the changes if any.
To fetch changes to a specific component in Talwa-Admin, we can use Octokit, which is a JavaScript client for GitHub's API.
Octokit allows us to interact with GitHub's API and perform various actions, such as creating and managing webhooks. In this case, we can create a webhook that listens for changes to the repository and calls the octokit.repos.getContent method when triggered.
these are the general steps we can follow to create a webhook using Octokit:
Install the Octokit library in your project using npm or yarn.
Authenticate with GitHub's API using your GitHub account credentials or a personal access token.
Use the Octokit library to create a webhook in the Talwa-Admin repository that listens for changes to the frontend components. You can set the webhook to trigger whenever there is a push event or a pull request event in the repository.
When the webhook is triggered, use Octokit to fetch the updated frontend components from the Talwa-Admin repository.
Use the Storybook tool to generate the Storybook documentation for the updated components.
Finally, use Octokit to deploy the generated documentation to a dedicated section or page on the Talawa-Docs website.
this is an example of how we would use octokit



```
const { Octokit } = require("@octokit/rest");
// Authenticate with GitHub's API using your GitHub account credentials or a personal access token.
const octokit = new Octokit({
  auth: "your_personal_access_token",
});

// Use the Octokit library to fetch the changes to a specific file in the Talwa-Admin repository.
async function fetchComponentChanges(owner, repo, filepath) {
  const { data } = await octokit.repos.getContent({
    owner,
    repo,
    path: filepath,
  });
  return data;
}

// Example usage: Fetch the changes to the "Button" component in the Talwa-Admin repository.
const owner = "TalawaTech";
const repo = "Talwa-Admin";
const filepath = "src/components/Button/Button.js";
const componentChanges = await fetchComponentChanges(owner, repo, filepath);
console.log(componentChanges);
```


```

{
  "name": "Button.js",
  "path": "src/components/Button/Button.js",
  "url": "https://api.github.com/repos/TalawaTech/Talwa-Admin/contents/src/components/Button/Button.js?,
  "type": "file",
  "content": "IyBUaGlzIGlzIGEgdGVzdCBjb21wb25lbnQKCnZhciBCdXR0b24gPSBmdW5jdGlvbiAoKSB7CiAgcmV0dXJuIFwiSGVsbG8gV29ybGQhXCI7Cn0KCmV4cG9ydCBkZWZhdWx0IEJ1dHRvbg==\n",
  "encoding": "base64",
}
```


then on the documentation repo, we can have a script that decodes the content with the Buffer module
const decodedContent = Buffer.from(data.content, "base64").toString();
console.log(decodedContent);
// Output: `"This is a test component\n\nvar Button = function () {\n  return \"Hello World!\";\n};\n\nexport default Button;"`

**Comment by evasharma12** [comment]
Hey @adepeju4,
It seems to be an interesting idea. But I have a few doubts.
When a component is changed, where will the record be stored? 
And, can we add these checks in GitHub Actions so that they get executed whenever a new PR is made?

Also, how do you document using Storybook? Do you add comments in the same file as the components or create new files.
Won't creating new files for each component be inefficient?

**Comment by adepeju4** [comment]
Hiii @evasharma12 

Thanks for your questions and feedback. Regarding your first question, the changes to the components can be recorded in the respective GitHub repository where the component is located. We can use GitHub Actions to automatically trigger the deployment process of the Storybook documentation whenever a change is made to the components.

To answer your second question, Storybook provides several ways to document components. We can add comments to the same file as the components or create separate files for each component. In my opinion, creating separate files for each component can be more organized and easier to navigate for developers. Moreover, it allows us to add more information and examples for each component without cluttering the original component file.

However, I understand your concern about the efficiency of creating new files for each component. To address this concern, we can group related components into the same file and add comments to each component within the file. This approach can help us strike a balance between efficiency and organization.

Let me know if you have any further questions or suggestions.

**Comment by evasharma12** [comment]
Hey @adepeju4,
I think that is a great idea, and you seem to be clear with the concept as well.
So, you can start working on it, but try not to create another repository for this.

**Comment by adepeju4** [comment]
thank you very much @evasharma12 

The issue is still unapproved, i don't know if i can start with it yet

**Comment by palisadoes** [comment]
@adepeju4 Are you still working on this?

**Comment by adepeju4** [comment]
Hi Peter, yes I am. This will need some children issues to be created
because it cannot be solved at once. I am creating those issues and making
sure they’re appropriate for the solutions --
 OREFEJO  ADEPEJU

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by akankshat05** [comment]
@palisadoes I would like to work on this issue. For this, I will create a separate branch in my fork and install storybook in that repo (instead of creating a separate repo). Then write stories for each component. For now, i plan on using chromatic for the storybook deployment.

**Comment by palisadoes** [comment]
Please add more detail to your plan and work with @evasharma12 on your assignment.

**Comment by akankshat05** [comment]
@palisadoes @evasharma12 Firstly I will install storybook in the repo using npx storybook@latest init. After this I will write stories for each component in a separate file in the component's folder. Next, I will follow these steps for publishing storybook and automating it's build:
1. Build storybook with "npm run build-storybook"
2. Install chromatic with "npm install chromatic --save-dev"
3. Deploy on chromatic with "npx chromatic --project-token=<your-project-token>" 
4. Configure the CI to publish storybook and run chromatic when code is pushed to the repo. 
For this I will follow the steps mentioned in the docs - https://www.chromatic.com/docs/github-actions. There are several ways to deploy storybook, but i have found chromatic the most beneficial as we can view the changes with each PR.

**Comment by anwersayeed** [comment]
Hi @akankshat05, I have assigned this issue to you, please go ahead and report your progress!

**Comment by akankshat05** [comment]
I have installed storybook and written stories for five components. I will write stories for few other components, but not for functional ones. Next i will work on the deployment.
