### ISSUE TITLE
No User deletion option available

### ISSUE THREAD

**Issue by AnishaSingh0118** [PalisadoesFoundation/talawa-admin#668]
**Is your feature request related to a problem? Please describe.**

- When a user logs in with and email id and password they got listed in the dashboard but if someone wants to delete the 
   previous user or dummy user (in case they forgot the password), there is no such option available.

**Describe the solution you'd like**

- There should be a delete option provided to each user who have logged in once they can easily delete the 
   the previous dummy user with that functionality.

**Describe alternatives you've considered**

**Additional context**

- This is a good suggestion to provide more user friendly interface.
- Attaching a picture for better understanding of the issue.

![delete-01](https://user-images.githubusercontent.com/76876709/224506566-1d3686b8-bea3-444a-ae85-74618dd87d42.jpg)
 

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by AnishaSingh0118** [comment]
I have been finding this hard for me to delete a user, so it would be a great feature to add. 
@palisadoes Kindly look into it and let me provide my best.


Thank you!

**Comment by palisadoes** [comment]
Please research this some more. Deleting a user has many implications. Do all their posts, calendar invitations, events the have created get deleted too?

Please ask in the #talawa-api slack channel about how this is handled in the backend, if at all.

**Comment by AnishaSingh0118** [comment]
> Please research this some more. Deleting a user has many implications. Do all their posts, calendar invitations, events the have created get deleted too?
> 
> Please ask in the #talawa-api slack channel about how this is handled in the backend, if at all.

We could provide edit user function because if someone forgets the password they can change it easily.

**Comment by palisadoes** [comment]
- That would be a separate issue that would need to be opened.
- Please do the research on this one.

**Comment by AnishaSingh0118** [comment]
> * That would be a separate issue that would need to be opened.
> * Please do the research on this one.

Yes, I have the approach for it. I am working on it.

**Comment by AnishaSingh0118** [comment]
> Please research this some more. Deleting a user has many implications. Do all their posts, calendar invitations, events the have created get deleted too?

No, the user post, etc will not be affected.
> 
> Please ask in the #talawa-api slack channel about how this is handled in the backend, if at all.

**Comment by palisadoes** [comment]
How can you ensure that user posts etc will not be deleted? You will have to research if there is a deletion option in the API and what it does. You will have to suggest methods of ensuring that your expected behaviour is maintained in the API. 

Talawa Admin is for Administrators. The talawa mobile app is for end users. There the API deletion functionality will need to be different for both scenarios.

Are you prepared to do the coding for this feature on both the frontend and backend? You will still need to solicit comments on what exactly it will do.

Please find a way to get comments on this in this issue as part of your research in proposing a comprehensive solution.

**Comment by AnishaSingh0118** [comment]
> How can you ensure that user posts etc will not be deleted? You will have to research if there is a deletion option in the API and what it does. You will have to suggest methods of ensuring that your expected behaviour is maintained in the API.
> 
> Talawa Admin is for Administrators. The talawa mobile app is for end users. There the API deletion functionality will need to be different for both scenarios.
> 
> Are you prepared to do the coding for this feature on both the frontend and backend? You will still need to solicit comments on what exactly it will do.
> 
> Please find a way to get comments on this in this issue as part of your research in proposing a comprehensive solution.
