### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Nitya-Pasrija** [PalisadoesFoundation/talawa-admin#671]
**Describe the bug**
The Introduction page in the Desired Features (further from the Requirement Docs), is blank.

**Expected behavior**
The Introduction page is blank, and should have a proper introduction to all the features by listing out atleast one liners about all them. 

**Actual behavior**
This page feels unnecessary, until there is a summary to all the features and linked up tabs to them.

**Screenshots**
![image](https://user-images.githubusercontent.com/97171261/224533831-0bfc1e1b-22a9-4298-9765-6c0daef5a9eb.png)

**Additional details**
I would like to add the features here, and even create hyperlinks for the user to jump to that specific feature from the Introduction tab to the feature's overview. This would ease in the smooth flow of routing through the documentation.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Closing. This issue is opened in the wrong repository. Please correct it.

**Comment by Nitya-Pasrija** [comment]
Oh sorry. I'll correct it.
