### ISSUE TITLE
Bug Report for undefined organization id on organization dashboard pages navigation

### ISSUE THREAD

**Issue by benshidanny11** [PalisadoesFoundation/talawa-admin#672]
**Describe the bug**
On the organization dashboard, when I try to navigate through pages, the routes come with an undefined id. And the app redirects to the organization list.

**To Reproduce**

1. Make sure the id is always set to value instead of undefined

**Expected behavior**
- When I click on any navigation menu of the organization dashboard I should see the expected page

**Actual behavior**
- The initial value of `configUrl` is set to `undefined`, which is in the end set to the organization id.

**Screenshots**

https://user-images.githubusercontent.com/45577181/224537955-a4f2e916-9df8-4200-8b73-1ed8805a4f2e.mov

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by benshidanny11** [comment]
@palisadoes, please assign this issue to me.

**Comment by Sumitmaithani** [comment]
@benshidanny11 your repo is 13 commits behind develop branch just sync fork and vola! issue is resolved than closed this issue.

**Comment by anshgoyalevil** [comment]
@benshidanny11 

Please sync your repo to the remote origin. This issue is fixed with PR https://github.com/PalisadoesFoundation/talawa-admin/pull/638
