### ISSUE TITLE
The alert after a certain request takes too much time loading

### ISSUE THREAD

**Issue by Graycemuthui** [PalisadoesFoundation/talawa-admin#673]
**Is your feature request related to a problem? Please describe.**
Most of the alerts are taking a long time to load. 

**Describe the solution you'd like**
Reduce the timer on the alert messages. 

**Describe alternatives you've considered**
Just updating the function that sets the timer and reduce the seconds on it

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**
![talawa alert](https://user-images.githubusercontent.com/95374858/224538864-239647e2-be8c-4803-a3cf-cc0b70f7af5f.jpg)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sumitmaithani** [comment]
@Graycemuthui there is no setTimeout() method is used to show toast messages.

**Comment by Graycemuthui** [comment]
Which raises my next question. Was it done in the backend side of this project?

**Comment by Sumitmaithani** [comment]
@Graycemuthui  Can you elaborate on what you mean by toast taking a long time to load with exact seconds it takes vs. what used to be the ideal timing?

**Comment by Graycemuthui** [comment]
Performing an action such as changing the user-role it takes close to 5 seconds just to show the error. My solution is to at least reduce the amount of time an alert takes to load before it disappears.

**Comment by Graycemuthui** [comment]
@palisadoes  could you assign me this task?

**Comment by palisadoes** [comment]
Unassigning due to inactivity others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by KhushiTayal** [comment]
@palisadoes may you please assign this issue to me.

**Comment by Graycemuthui** [comment]
I'm working on it @palisadoes

**Comment by palisadoes** [comment]
@KhushiTayal I've reassigned it to @Graycemuthui

**Comment by akankshat05** [comment]
@palisadoes may I work on this?

**Comment by palisadoes** [comment]
We are focusing on breaking bugs and features that don't work out are not intuitive to use prior to the GSoC and Outreachy announcements.

Closing
