### ISSUE TITLE
Bug Report for showing links to image and video on the post, and the reason for this is that there is no implementation of file upload on create post form. 

### ISSUE THREAD

**Issue by benshidanny11** [PalisadoesFoundation/talawa-admin#680]
**Describe the bug**
The links to the image and the video are not shown on the post item card.
**To Reproduce**

1. Make sure these links are visible

**Expected behavior**
- When I open the posts page I should see links to the image and video.

**Actual behavior**
- Currently, these links are not visible on the post item card. and The issue is with image and video upload features that are not implemented.

**Screenshots**
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/45577181/224567694-db7f1611-70a8-4286-bc71-5bfb5df3a5b4.png">
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/45577181/224568751-ca9eef5e-4d3d-45d0-87e3-d3382cc69233.png">

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by benshidanny11** [comment]
@palisadoes please assign this issue to me. Thanks!

**Comment by palisadoes** [comment]
Please verify whether the API has the mutation to do this, if so then we can consider assignment.

**Comment by benshidanny11** [comment]
@palisadoes, the API has the mutation for the image only. So I do the implementation for the image!
<img width="591" alt="image" src="https://user-images.githubusercontent.com/45577181/224788445-ba665f2a-78c5-45a4-bbdb-573a38f7e24c.png">

**Comment by benshidanny11** [comment]
I think it is not dependent on this PR, because it uses the same implementation as create Organization and for creating an organization, the image upload is working perfectly. 

<img width="591" alt="image" src="https://user-images.githubusercontent.com/45577181/224791052-c4f22c67-628b-452d-b927-ee973269a12c.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/45577181/224793913-6e821713-57d2-44ef-bfda-57fe2af8853b.png">

**Comment by kb-0311** [comment]
@benshidanny11  I am the one who implemented the image uploads function in organization. @palisadoes is right , this depends on that linked PR. 

Also video uploads are not done yet, sorry for the trouble.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by KrutikaBhatt** [comment]
@palisadoes, can I work on this ?

**Comment by kb-0311** [comment]
@KrutikaBhatt @palisadoes I think this issue has already been solved since the merge of this PR https://github.com/PalisadoesFoundation/talawa-admin/issues/680#issuecomment-1466645779.

Yoy can close this issue, it has been fixed.

**Comment by palisadoes** [comment]
Closing as duplicate
