### ISSUE TITLE
Bug Report: Multiple scroll bars on the body of the admin web page and misaligned pagination element

### ISSUE THREAD

**Issue by BlessingOkonkwo** [PalisadoesFoundation/talawa-admin#683]
**Describe the bug**
Multiple scroll bars on the body of the admin web page, issue with overflow properties on the page. Also the pagination element at the foot of the page is not properly aligned (screenshot below)

**To Reproduce**

1. Log in to the admin site
2. multiple scroll appear to the right of the orglist page

**Expected behavior**
There should be just one major scroll bar

**Actual behavior**
multiple scroll bars

**Screenshots**
<img width="249" alt="image" src="https://user-images.githubusercontent.com/67244439/224596277-b0d5f75d-d8fb-43b5-a79d-5fa6a5f91d33.png">

<img width="438" alt="image" src="https://user-images.githubusercontent.com/67244439/224601291-99dec380-48f2-48af-a22a-f6881e3d48ec.png">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by BlessingOkonkwo** [comment]
Please assign this issue to me @palisadoes

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by BlessingOkonkwo** [comment]
@palisadoes I'm so sorry for the delay, sadly I have been indisposed and haven't been able to work. I have now fixed the issue, can I still make a pull request? If not, I will probably create and work on another issue now. Thank you

**Comment by palisadoes** [comment]
Please work on another issue. This one has been assigned

**Comment by BlessingOkonkwo** [comment]
Alright
