### ISSUE TITLE
Bug Report: The roles and requests tabs (in the header) have no active styling for when the roles/requests page is in display

### ISSUE THREAD

**Issue by BlessingOkonkwo** [PalisadoesFoundation/talawa-admin#684]
**Describe the bug**
The roles and requests tabs (in the header) have no active styling for when the roles or request page is in display to let the user know what page they're currently viewing 

**To Reproduce**

1. Login to Talawa admin portal
2. Click on either the roles tab in the header or the requests tab

**Expected behavior**
There should be styling on the tabs to indicate to the user that they are currently viewing that page

**Actual behavior**
No styling whatsoever when either the roles tab or requests tabs are clicked and displayed

**Screenshots**
<img width="914" alt="image" src="https://user-images.githubusercontent.com/67244439/224599470-0c919163-83f8-4525-8b6e-bc7072c6953e.png">

<img width="938" alt="image" src="https://user-images.githubusercontent.com/67244439/224599556-c86c76ed-4d70-4f07-9873-e6eebf30981e.png">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by BlessingOkonkwo** [comment]
@palisadoes Please assign this issue to me

**Comment by Sumitmaithani** [comment]
@BlessingOkonkwo this issue has been raised [#665 ](https://github.com/PalisadoesFoundation/talawa-admin/issues/665)

**Comment by adi-uchiha** [comment]
@palisadoes I think We can set active link styling for all navbar link and remove the H1 from every component that will utilise the top space we are wasting

**Comment by adi-uchiha** [comment]
@palisadoes I think We can set active link styling for all navbar link and remove the H1 from every component that will utilise the top space we are wasting

**Comment by BlessingOkonkwo** [comment]
> @BlessingOkonkwo this issue has been raised [#665 ](https://github.com/PalisadoesFoundation/talawa-admin/issues/665)

Oh I see, Thanks. I did not realize this issue had been raised
