### ISSUE TITLE
Bug Report: Invalid UI state of Event data in Edit modal

### ISSUE THREAD

**Issue by kamtoeddy** [PalisadoesFoundation/talawa-admin#685]
**Describe the bug**
The modal to edit an Event does not reflect the correct values of the `allDay`, `isPublic`, `isRegisterable` and `recurring` properties of an event

**To Reproduce**

1. Log in as SUPER ADMIN
2. Select an Organization to manage
3. Navigate to the organization's events page
4. Create an event if none available
5. Select the created event by clicking on the edit icon of the event on the events table
6. Update any of `allDay`, `isPublic`, `isRegisterable` and `recurring` properties of the event and save
7. Even upon refreshing the UI will be the same

**Expected behavior**
The UI should reflect the correct values of the `allDay`, `isPublic`, `isRegisterable` and `recurring` properties of an event

**Actual behavior**
The UI is stuck in the state as shown in the screenshot attached, irrespective of the state of an event for the properties mentioned above

**Screenshots**
![Screenshot (565)](https://user-images.githubusercontent.com/65472478/224709139-95b2e93c-5b84-4926-8548-f9d935466b4b.jpg)
![Screenshot (566)](https://user-images.githubusercontent.com/65472478/224709150-49cc51c4-bf15-4d0f-a2a7-d7f1b4cb8945.jpg)

**Comment by kamtoeddy** [comment]
@palisadoes please assign the issue to me. Thank you

**Comment by Sumitmaithani** [comment]
@kamtoeddy for this checkout this issue [#658  ](https://github.com/PalisadoesFoundation/talawa-admin/issues/658)

**Comment by kamtoeddy** [comment]
Hi @Sumitmaithani, sorry I missed that but can I also work on #658?
