### ISSUE TITLE
Bug Report :  [The Time is static on the Organizations Card in organization list page]

### ISSUE THREAD

**Issue by saadabban76** [PalisadoesFoundation/talawa-admin#686]
**Describe the bug**
In the Organization List Tab, the organization created Date&Time is assigned to static data as "01/01/1970" check the below screenshot for the reference, I've already worked on this Issue and made the changes now it works fine with correct time.

**To Reproduce**
I've Changed the source code from " dayjs(parseInt(datas?.created).format('DD/MM/YYYY') " to " {dayjs(datas?.createdAt).format('DD/MM/YYYY')} " in the OrgList.tsx file.

**ScreenShots : **

**Before - **
![Screenshot 2023-03-13 211036](https://user-images.githubusercontent.com/115649011/224766494-0735ae2c-84e3-4ddb-bf5d-1592033df145.png)

**After - **
![Screenshot 2023-03-13 211620](https://user-images.githubusercontent.com/115649011/224766551-e85c5edc-a64a-4de3-ba51-a74d0921affa.png)

**Comment by Girish-Jangam** [comment]
can i work on this issue?
