### ISSUE TITLE
Bug Report : organization default image is not same in all pages.

### ISSUE THREAD

**Issue by Sumitmaithani** [PalisadoesFoundation/talawa-admin#688]
**Describe the bug**
If user create an organization without upload a image its default image is not same in all pages like in /orglist page it show 200 x 100 image but if you click on manage, it show organization image of dog in left and in right side corner it show talawa logo.

**To Reproduce**

1. First Login to website.
2. Create organization without any image and go to manage.
3. You find all three place a different default image.

**Expected behavior**
We can make deafult image of talawa logo in all places if user is not upload organization image to increase the branding of our organizaation.

**Actual behavior**
organization default image should be same in all pages.

**Screenshots**

https://user-images.githubusercontent.com/86047367/224807850-c913ec89-16ee-4693-80e2-d4e94fd6c96a.mp4

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by DMills27** [comment]
Thanks for raising this point! I suggest using a question mark svg or something similar in place of the current images.

**Comment by palisadoes** [comment]
@Sumitmaithani We want all stock images to be removed from the app. We have no knowledge of the copyright implications. Please remove that dog image or any similar stock images that may have come with the template used.

**Comment by itsAkshat-jain** [comment]
what we can do is, make it compulsory for organizations to insert an image and we can also show a default image to all who not upload their image
