### ISSUE TITLE
Feature Request: No indicator when the query output is null

### ISSUE THREAD

**Issue by resonating-homesh** [PalisadoesFoundation/talawa-admin#692]
**Is your feature request related to a problem? Please describe.**
There is no indicator for letting users know that the search query has ended and there is no organization named with particular input which the user has entered in 'Search by Name' input.

**Describe the solution you'd like**
For the query returning null, displaying 'No Organization Found' would improve the overall user experience. Along with that an image/svg will go good.

**Describe alternatives you've considered**
Instead of returning a hard-coded string in such scenarios, we can just return just an image/svg containing the message in text. 
For example. 
![p3](https://user-images.githubusercontent.com/75970868/224838547-689f89fc-c84c-45f1-bd97-3188d5575eab.jpg)

**Additional context**
Below are the images showcasing the issue mentioned above:
![p1](https://user-images.githubusercontent.com/75970868/224837973-a01c70b3-00a3-428c-916e-c870c7beb5ff.jpg)
![p2](https://user-images.githubusercontent.com/75970868/224838026-0910d9f2-1837-466b-9723-6fbc524ee101.jpg)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by resonating-homesh** [comment]
@palisadoes may you please assign this issue to me?

**Comment by Pranauv-Kumar1803** [comment]
hey there @resonating-homesh ! 

I updated my talawa-admin ( just pulled the new changes )  but still I don't have any "Search By Name" search-bar in my orglist page... Am I doing anything wrong ?

**Comment by resonating-homesh** [comment]
> hey there @resonating-homesh !
> 
> I updated my talawa-admin ( just pulled the new changes ) but still I don't have any "Search By Name" search-bar in my orglist page... Am I doing anything wrong ?

Did u create any test organizations yet? U need to create them by yourselves. In the above screenshots, you can see the organizations that i created are for testing only. U can create them by clicking on the 'Create Organization' button.
Hope this helps.

**Comment by Pranauv-Kumar1803** [comment]
I have 2-3 test organizations but not that search bar ( search by name ) in the left hand side of the screen

**Comment by palisadoes** [comment]
Closing. Duplicate issue and PR
