### ISSUE TITLE
Create tests for the "Calendar.tsx" functions to ensure correctness and increase code coverage.

### ISSUE THREAD

**Issue by Aimanosi** [PalisadoesFoundation/talawa-admin#693]
**Describe the bug**
Create tests for the "Calendar.tsx" functions to ensure correctness and increase code coverage.

**To Reproduce**

1. Open the talawa-admin app
2.  run yarn "test --watchAll=false --coverage"
3. Inspect the table to see the low coverage results

**Expected behavior**
The code coverage should be at least 90% and all lines of code should be included.

**Actual behavior**
The code coverage is less than 90% and all lines of code are not included.

**Screenshots**

![Calender error](https://user-images.githubusercontent.com/104039356/224850422-d5979776-f479-4af8-b0c7-a89820ae316d.jpg)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Girish-Jangam** [comment]
can i please work on this issue?

**Comment by Girish-Jangam** [comment]
can i work on this when its  get approved?

**Comment by Aimanosi** [comment]
@palisadoes please assign this issue to me.

**Comment by palisadoes** [comment]
@Aimanosi Please update your repo daily. The coverage on the file is > 97% now. Closing.

- https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/blob/develop/src/components/EventCalendar/Calendar.tsx
