### ISSUE TITLE
Password Validations are not enforced across the app.

### ISSUE THREAD

**Issue by aakarshee2000** [PalisadoesFoundation/talawa-admin#696]
**The bug**
In case of registering a user on the portal, there is a constraint imposed saying that the password should be 8 characters long, but no such checks are being taken care of at the time of creating the passwords or on the **Forget Password** pages.
Passwords of length smaller are also being allowed. Further Only strong passwords should be allowed on our App for better security.

**Expected behavior**
After the solving of this issue, only the passwords adhering to the constraints will be allowed during new user registration and on the forgot password page.

**Screenshot**
![WhatsApp Image 2023-03-14 at 3 05 04 PM](https://user-images.githubusercontent.com/72440467/224962022-0af3ac9f-d178-4d4b-a188-bf8b44720cd2.jpeg)
![WhatsApp Image 2023-03-14 at 3 20 58 PM](https://user-images.githubusercontent.com/72440467/224963095-5b2a9ed9-057a-4972-ad44-f48db239e610.jpeg)

I will happily take up this issue, if approved.

**Comment by Sheguun** [comment]
Can this task be assigned to me @palisadoes @aakarshee2000

**Comment by TEE-JAY12** [comment]
Hey, i would like to work on this issue

**Comment by palisadoes** [comment]
@aakarshee2000 Do you want to work on this?

**Comment by Sheguun** [comment]
> 

Yes I'd like to work on it, please

**Comment by palisadoes** [comment]
> > 
> 
> Yes I'd like to work on it, please @aakarshee2000

@Sheguun I was asking @aakarshee2000. Please be patient.

**Comment by Sheguun** [comment]
> > > 
> > 
> > 
> > Yes I'd like to work on it, please @aakarshee2000
> 
> @Sheguun I was asking @aakarshee2000. Please be patient.

Alright sir @palisadoes

**Comment by palisadoes** [comment]
> Please @palisadoes I'd like to be assigned an issue. It seems most of them have been assigned

Run the application and try to find bugs. That's what all the others have done.

**Comment by Sheguun** [comment]
> > Please @palisadoes I'd like to be assigned an issue. It seems most of them have been assigned
> 
> Run the application and try to find bugs. That's what all the others have done. Make sure that you don't create any duplicate issues. The ISSUE_GUIDELINES.md file has details on how to do this.

Alright sir @palisadoes

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by jmalisha** [comment]
@palisadoes Could you please assign me this issue

**Comment by palisadoes** [comment]
Please fix the conflicting files in PR #828
