### ISSUE TITLE
Feature RequestBug Report [In Organization Post's tab there is no prompt if the search query output is Null]

### ISSUE THREAD

**Issue by saadabban76** [PalisadoesFoundation/talawa-admin#698]
**Is your feature request related to a problem? Please describe.**
In the Organization Post tab, there is no text/prompt for users if there is no Post that the user is searching.

**Describe the solution you'd like**
Create a reusable PostNotFound Component that will render a good "Post Not found" card result.

**Describe alternatives you've considered**
the reusable PostNotFound Component containing a cool text or the Image would improve the UX.

**Screenshot**
![sfsd](https://user-images.githubusercontent.com/115649011/224974454-2311624d-5968-4d28-a297-5f094f4b7eba.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Graycemuthui** [comment]
@palisadoes  and @saadabban76 can I work on this?

**Comment by saadabban76** [comment]
> @palisadoes and @saadabban76 can I work on this?

Sorry @Graycemuthui ,but I'm already working on this issue,  If you are interested you can also work on this contribution.

**Comment by palisadoes** [comment]
> > @palisadoes and @saadabban76 can I work on this?
> 
> Sorry @Graycemuthui ,but I'm already working on this issue, If you are interested you can also work on this contribution.

You are not assigned this task. You need to request it. Assignment is not automatic. Sometimes people don't know how to fix the issue reported.

**Comment by saadabban76** [comment]
yes please assign me this issue.

**Comment by Graycemuthui** [comment]
@saadabban76 no worries! good luck!

**Comment by saadabban76** [comment]
@palisadoes I accidently removed my assignment, can you please reassign me ? my bad

**Comment by adi-uchiha** [comment]
Make sure you are making this in the components folder. Also if the user re-enters the search text the not found component should disappear and results should appear

**Comment by saadabban76** [comment]
> Make sure you are making this in the components folder. Also if the user re-enters the search text the not found component should disappear and results should appear 

You mean if the user creates new post and re enters the title, the error should disappear?

**Comment by adi-uchiha** [comment]
While the user is typing-> user types a incorrect letter-> not found will appear -> user hits backspace on that letter and enters correct letter-> not found should disappear and results should appear without delay
