### ISSUE TITLE
Bug Report: Org setting page is Blank by default

### ISSUE THREAD

**Issue by adi-uchiha** [PalisadoesFoundation/talawa-admin#699]
**Describe the bug**
When we open the settings page from org page. The main screen is in blank and we get to see options on the left. User have to choose from that options to see the settings of org. By default when we visit from org page to settings, org settings should be open.

**To Reproduce**

1. Run the app
2. Open any org page (org prople, org events etc)
3. Open settings from navbar
4. See the bug

**Expected behavior**
org settings component should be active by default

**Actual behavior**
None of the settings are active
**Screenshots**

**Additional details**
Add any other context or
<img width="960" alt="chrome_UJ6Ov0n2cF" src="https://user-images.githubusercontent.com/103348863/224995198-95b4b085-13f6-4078-b096-659491a0d935.png">
 screenshots about the feature request here.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by adi-uchiha** [comment]
@palisadoes I want this to be assigned to a new comer. How can I add good-frist-issue label ?

**Comment by palisadoes** [comment]
This is a duplicate

- https://github.com/PalisadoesFoundation/talawa-admin/issues/559

**Comment by palisadoes** [comment]
Thanks for noticing this. Please comment on the other issue so we can get the best results
