### ISSUE TITLE
Bug Report: Users filter at organisation's people page should fetch corresponding Users to Organisation

### ISSUE THREAD

**Issue by Manoramsharma** [PalisadoesFoundation/talawa-admin#701]
**Describe the bug**
On the same outlines as discussed in the issue #507 the filter for users in the organisation people's page in not fetching the users corresponding to the particular organisation rather all users including the outsiders for an organisation that is not recommended behaviour.
<img width="960" alt="chrome_Fft6OaTqYY" src="https://user-images.githubusercontent.com/84619980/225009474-e5764888-31bf-43c3-8d3b-5de43c2ecdfb.png">

**To Reproduce**

1. Fetching the complete User list.
2.Filter out the users which have the current `orgId` present corresponding to the `joinedOrganizations` array field
3.Return the users data after filter.

**Expected behavior**
Only the users which have the corresponding orgId in the `joinedorganization` field should only be fetched as users to the organisation not all the users present in the database.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
1. It is a bug. Do you want to fix this?
2. We will also need tests for this as we don't want a recurrence

**Comment by TEE-JAY12** [comment]
@palisadoes  Please can i work on this

**Comment by Sheguun** [comment]
I'd like to be assigned to the issue please @palisadoes

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by TEE-JAY12** [comment]
Yeah i am still interested on working on this and i am currently on it

**Comment by Manoramsharma** [comment]
Hi @TEE-JAY12 can you please share your progress on slack, else I can start working on this. @palisadoes this bug is on same outline as issue #507 I previously worked on. Also a question regarding this, currently any user signing in by default become the member of the particular organisation where according to the business idea that I can understand is that a mere user need to have some kind of member ship request for being a member for the particular org can you please enlighten more on this?

**Comment by Manoramsharma** [comment]
@palisadoes kindly assign this issue to me.Also a question regarding this, currently any user signing in by default become the member of the particular organisation where according to the business idea that I can understand is that a mere user need to have some kind of member ship request for being a member for the particular org can you please enlighten more on this?

**Comment by palisadoes** [comment]
There will need to be some type or authorization for someone to start using the apps.

**Comment by Sumitmaithani** [comment]
@palisadoes Can I take this issue

**Comment by Sumitmaithani** [comment]
@palisadoes I think you mistakenly assigned @saadabban76

**Comment by Sumitmaithani** [comment]
@palisadoes this issue has been resolved in this [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/853) you may close this issue
