### ISSUE TITLE
Event Modal Window Not Closing

### ISSUE THREAD

**Issue by Sheguun** [PalisadoesFoundation/talawa-admin#709]
**Describe the bug**
The event modal does not close after an event has been created.

**To Reproduce**

1. Login on the talawa-admin portal
2. Click on the event link in the top nav bar
3. Click on add event 
4. Fill out the event details form and submit

**Expected behavior**
After filling in the event details, the modal window is expected to close.

**Actual behavior**
The modal window is still displayed after the event has been created.

**Screenshots**
![New issue](https://user-images.githubusercontent.com/114509848/225042182-bd4eb02f-7863-40cc-92d9-d6aee8633ae1.png)
![New issue 2](https://user-images.githubusercontent.com/114509848/225045298-04b86165-3417-4dcd-a245-c28d040c6891.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sheguun** [comment]
I'd like to be assigned this issue @palisadoes

**Comment by palisadoes** [comment]
We are focusing on two types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of serious bugs. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
