### ISSUE TITLE
Create tests for the "OrgPost.tsx" functions to ensure correctness and increase code coverage.

### ISSUE THREAD

**Issue by Aimanosi** [PalisadoesFoundation/talawa-admin#711]
**Describe the bug**
Create tests for the "OrgPost.tsx" functions to ensure correctness and increase code coverage.

**To Reproduce**

1. Open the talawa-admin app
2. run yarn "test --watchAll=false --coverage"
3. Inspect the table to see the low coverage results

**Expected behavior**
The code coverage should be at least 90% and all lines of code should be included.

**Actual behavior**
The code coverage is less than 90% and all lines of code are not included.

**Screenshots**
![orgPost error](https://user-images.githubusercontent.com/104039356/225166219-a7fbeccd-de68-4240-bfbd-38ce37c352c9.jpg)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Aimanosi** [comment]
@palisadoes Please assign this to me.

**Comment by adi-uchiha** [comment]
Thanks for noticing! Good job, this is a duplicate issue of #271

**Comment by palisadoes** [comment]
Closing duplicate
