### ISSUE TITLE
Bug Report: Improve user experience and modification of the settings page

### ISSUE THREAD

**Issue by Afola-Ode** [PalisadoesFoundation/talawa-admin#712]
**Describe the bug**
1. Upon clicking the 'Settings' icon, the user is directed to a page where only the sidebar displays the options, and the main window remains empty, which is not a very good user experience.
2. While managing an organization, the update your details input field is populated with the wrong details. 
3. Delete organization button not working.
4. Proper alignment of the input fields (update your details, update your password, update organization) and their attached buttons.
5. `See request` page is empty when there is no data.

**To Reproduce**

1. Login to the website.
2. Click on manage on the organization list.
3. Select settings on the header dropdown.
4. All the button are listed there.

**Expected behavior**
1. User should be able to view the input field of the first settings option on page load.
2. Correct input details on `update your details` input field.
3. Confirmation to delete organization
4. Proper alignment of the input fields (update your details, update your password, update organization) and their attached butt
5. An image with a caption of "no data" should be used to indicate the absence of information.

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**
![screencapture-localhost-3000-orgsetting-id-6410fea80fec36183ca2c44a-2023-03-15-05_20_29](https://user-images.githubusercontent.com/36237399/225208774-4ee7e301-53d0-46fa-abce-53cc01945555.png)
![screencapture-localhost-3000-orgsetting-id-6410fea80fec36183ca2c44a-2023-03-15-05_25_08](https://user-images.githubusercontent.com/36237399/225208786-ad8d158e-35ed-4507-96cd-32532b9a52c6.png)
![screencapture-localhost-3000-orgsetting-id-6410fea80fec36183ca2c44a-2023-03-15-05_27_57](https://user-images.githubusercontent.com/36237399/225208794-738da4de-468f-4a2e-be96-290fc529345a.png)
![screencapture-localhost-3000-orgsetting-id-6410fea80fec36183ca2c44a-2023-03-15-05_28_11](https://user-images.githubusercontent.com/36237399/225208799-9c199b31-e5ac-4e64-8b11-ba8e4ce0c973.png)
![screencapture-localhost-3000-orgsetting-id-6410fea80fec36183ca2c44a-2023-03-15-05_28_24](https://user-images.githubusercontent.com/36237399/225208815-fc0810d5-9779-4f29-94df-9f8b05f50b7a.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Afola-Ode** [comment]
Please, I'd like to be assigned this issue. Thank you.

**Comment by Karnankita04** [comment]
Please assign this issue to me.
