### ISSUE TITLE
Bug Report : In Update Organization page updating org image is not working

### ISSUE THREAD

**Issue by Sumitmaithani** [PalisadoesFoundation/talawa-admin#713]
**Describe the bug**
In Update Organization page updating org image is not working.

**To Reproduce**

1. First Login to website.
2. Create organization and go to manage.
3. Go to settings and Update organization page.
4. Update new image.

**Expected behavior**
On updating image it should update the org image.

**Actual behavior**
On updating image is not working.

**Screenshots**

https://user-images.githubusercontent.com/86047367/225312021-62a709dd-03c7-4363-97be-d7dacead6d30.mp4

**Additional details**
For make it work first set up all things in frontend and then changes also required in talawa-api to make this work.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Pranauv-Kumar1803** [comment]
Hey there @Sumitmaithani ! This is not a bug because they haven't implemented it in the codebase itself. So I would say this is a feature request!!

Also , I would love to contribute to this feature!

@palisadoes Can you please assign me this?

**Comment by anshgoyalevil** [comment]
@Sumitmaithani 

This issue is being covered under the image uploading functionality issue https://github.com/PalisadoesFoundation/talawa-admin/issues/538
