### ISSUE TITLE
On the Admin Dashboard, The "manage" Button Is Not Functional

### ISSUE THREAD

**Issue by Sheguun** [PalisadoesFoundation/talawa-admin#714]
**Describe the bug**
When logged in as an admin, the admin can not manage the organization.

**To Reproduce**

1. Login as an admin
2. Click on the "manage" button
3. The "manage" button is not functional

**Expected behavior**
It should show a list of operations that the admin can perform in an organization. Example: adding members to the organization.

**Actual behavior**
.

**Screenshots**
![Issue1](https://user-images.githubusercontent.com/114509848/225330229-1fdf3cca-40bc-4ad0-aa71-0805b16e2121.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sheguun** [comment]
@palisadoes  I'd like to be assigned this issue.

**Comment by palisadoes** [comment]
Closing as a duplicate issue. Feel free to comment on what you see here:
__
- https://github.com/PalisadoesFoundation/talawa-admin/issues/559

Please keep the suggestions coming.

**Comment by Pranauv-Kumar1803** [comment]
Hey @Sheguun ! It works fine for me! Please recheck and let me know.

**Comment by Pranauv-Kumar1803** [comment]
I am logged in as a superadmin

**Comment by Sheguun** [comment]
@Pranauv-Kumar1803 it works well for super admins. However, it doesn't work logging in as an admin.
Here's the question:👇
Can you add a member to an organization as an admin or view the members of an organization as an admin?

**Comment by Sheguun** [comment]
Additionally, @Pranauv-Kumar1803 @palisadoes As a super admin, I tried making some users become admin, and I tried logging in with their details but it's still showing that they are users

I know how to fix this if the task is assigned to me. Thanks

**Comment by Pranauv-Kumar1803** [comment]
@Sheguun Can you tell me how to add a person to an organization?

**Comment by Pranauv-Kumar1803** [comment]
@noman2002 I just have a doubt in the admin dashboard.

In the Home Page, when the admin is logged in (/orglist page) ,  shouldn't you show the organizations that the admin is a part of rather than showing all the organizations and then disabling the manage button for the admin?

As fas as I have seen, if I'm logged in as an admin, its just the manage buttons which are disabled.

**Comment by Sheguun** [comment]
@Pranauv-Kumar1803 @noman2002 The manage buttons are not disabled. However they are not functional yet..

**Comment by Sheguun** [comment]
@palisadoes @Pranauv-Kumar1803 Can a SUPERADMIN add an admin to an organization yet?

**Comment by palisadoes** [comment]
The expected behaviors can be  found here

- https://docs.talawa.io/docs/applications/overview

**Comment by Pranauv-Kumar1803** [comment]
@Sheguun I dont see any option where a superadmin can add an admin or anybody to an org

**Comment by Pranauv-Kumar1803** [comment]
@palisadoes 

![image](https://user-images.githubusercontent.com/97829544/225619012-c30e08e1-700f-4f6a-a7ab-9a7ba14c4d61.png)

Here it means that an admin can be a part of many organizations but can only access one at a time right?

So in the orglist page , when an admin logs in , shouldn't we show only those organizations that he's present in instead of all?

**Comment by Pranauv-Kumar1803** [comment]
Sorry for the inconvenience...
what I was saying is already an issue and is being worked on by somebody else! 
Pls ignore!

**Comment by Sheguun** [comment]
@Pranauv-Kumar1803 I'm logged in as a super admin here. Which means I can add an admin and a user.
![Issue3](https://user-images.githubusercontent.com/114509848/225622627-554697a8-cfbc-4b70-9a21-c047de1ea8f0.png)

**Comment by Sheguun** [comment]
> Sorry for the inconvenience... what I was saying is already an issue and is being worked on by somebody else! #650 Pls ignore!

Oww! I'm just seeing this. Alright I understand

**Comment by Sheguun** [comment]
> @palisadoes
> 
> ![image](https://user-images.githubusercontent.com/97829544/225619012-c30e08e1-700f-4f6a-a7ab-9a7ba14c4d61.png)
> 
> Here it means that an admin can be a part of many organizations but can only access one at a time right?
> 
> if so, in the orglist page , when an admin logs in , shouldn't we show only those organizations that he's present in instead of all?
> 
> if not also, when we log in as an admin, we're able to see all the organizations that are formed which I think is wrong.

Yes, I agree with you on this. Since someone is already working on it already, then I guess its settled.

**Comment by Sheguun** [comment]
In addition, I saw went through the breeze we site   @palisadoes @Pranauv-Kumar1803 and I feel I can add the "Tags" feature on the talawa website too.

Let me know if I should go ahead with it. Thanks sir

**Comment by palisadoes** [comment]
> In addition, I went through the breeze website @palisadoes @Pranauv-Kumar1803 and I feel I can add the "Tags" feature on the talawa website too.
> 
> Let me know if I should go ahead with it. Thanks sir

Tags support is already being added in the API. Work on implementing it in the Admin panel will need to be deferred to formal GSoC and Outreachy proposals.

- https://github.com/PalisadoesFoundation/talawa-api/pull/1179

**Comment by palisadoes** [comment]
> settled

That was not the intention. The current workflow doesn't work in the context of the example given in the core concepts page. I've updated it. We must restrict Admins to the management of one and no more organizations.

- https://docs.talawa.io/docs/applications/overview

**Comment by Pranauv-Kumar1803** [comment]
> > settled
> 
> That was not the intention. The current workflow doesn't work in the context of the example given in the core concepts page. I've updated it. We must restrict Admins to the management of one and no more organizations.
> 
> * https://docs.talawa.io/docs/applications/overview

Ok thank you
