### ISSUE TITLE
Bug Report - Search for users in Roles Section is laggy and not consistent

### ISSUE THREAD

**Issue by Pranauv-Kumar1803** [PalisadoesFoundation/talawa-admin#716]
**Describe the bug**
When logged in as the superadmin, in the roles section of the website, searching for users according to their name is not consistent ( it is one step behind )

**To Reproduce**

1. Log in as a super admin
2. Go to the Roles section of the website
3. Try searching for a name ( letter by letter )

**Expected behavior**
It is expected that the search should be as smooth and consistent as possible!

**Screenshots**
![image](https://user-images.githubusercontent.com/97829544/225362976-facbbeb0-956a-4b5a-b76d-920f5ee87f7b.png)

**Additional details**
Here's a video example :-

https://user-images.githubusercontent.com/97829544/225363433-26ca22a7-227e-4ff0-9967-baf938845137.mp4

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Pranauv-Kumar1803** [comment]
@palisadoes 
Please look into this and assign it to me if correct.

**Comment by palisadoes** [comment]
Please change the title of this issue so that it will be more easily searchable.

**Comment by Pranauv-Kumar1803** [comment]
Done @palisadoes!

**Comment by palisadoes** [comment]
If it does something predictably, then it's consistent. 

1. What is unpredictable? 
2. When you say `one step behind`, what do you mean?

**Comment by Pranauv-Kumar1803** [comment]
Answering you 2. question , what is happening there is when I type "f" (just one letter and then leave it), it doesn't show the expected users list ( which has to be the users whose first name starts with 'f' ) but shows it only when I type one more letter like for example 'fa' - this is when it shows the filtered users for the previous input ( which was just 'f' ) 

So what I am saying is that it is one step behind in the sense that searchByName ( value in the input ) is applied only in the next step.

This maybe because of the fact that searchByName( the input box's value) is being applied only after the results are refetched.

**Comment by Pranauv-Kumar1803** [comment]
@palisadoes Can you please review this?
