### ISSUE TITLE
Unmatched password filed validation between Talawal mobile app &  Talwal admin 

### ISSUE THREAD

**Issue by khaledmurtaja** [PalisadoesFoundation/talawa-admin#720]
when i tried to register a new account `on the admin `portal i was able to register an account with a password which has the following validation **(at least 8 characters long ),** but when i tried to use the same password to login `using the mobile app` it gave me the error **(password must have at least 8 char, one upper Case , one number ,one special characters)**

**To Reproduce**

1. first choice is to edit the validation on the `mobile app` to (**at least 8 characters )**
2.second choice is to edit the validation on the `admin portal` to (**password must have at least 8 char, one upper Case , one number ,one special characters)**
 i am ready to be assigned for this issue

**Expected behavior**
matched password validation between mobile app & admin portal

**Actual behavior**
unmatched password validation between mobile app & admin portal

**Screenshots**
![WhatsApp Image 2023-03-15 at 8 53 01 PM (1)](https://user-images.githubusercontent.com/79102102/225413969-1869a623-f56e-4fc3-a897-e4d5d251eeb2.jpeg)
![WhatsApp Image 2023-03-15 at 8 53 01 PM (2)](https://user-images.githubusercontent.com/79102102/225413981-016d16bd-8527-4fb4-a351-67effb2ee53c.jpeg)
![WhatsApp Image 2023-03-15 at 8 53 01 PM](https://user-images.githubusercontent.com/79102102/225413987-ebd70044-7f7b-4130-8ec9-cb0ef51d980f.jpeg)
![WhatsApp Image 2023-03-15 at 8 53 02 PM](https://user-images.githubusercontent.com/79102102/225413990-efc5aeb3-1e0c-47b4-9f43-475100a999fd.jpeg)

**Comment by palisadoes** [comment]
Do you want to work on this issue? If so you should do so immediately after creating it. That way we don’t have to visit the issue twice. Once to ask you and then again to assign you. We’ll update the ISSUE_GUIDELINES.md to state this.

**Comment by khaledmurtaja** [comment]
> Do you want to work on this issue? If so you should do so immediately after creating it. That way we don’t have to visit the issue twice. Once to ask you and then again to assign you. We’ll update the ISSUE_GUIDELINES.md to state this.

Yes i wants to work on it.
But i need to know which choice suitable for the use case?

**Comment by palisadoes** [comment]
The one with the better security features.

**Comment by khaledmurtaja** [comment]
@palisadoes 
Okay that means that i will work on the talawa admin side.
Assign me for this issue
On the commings days if i have opend any issues this means that i want to be assigned.
If i figured out that i wont finish the task i will unassign myself to give chances to other devs.

**Comment by palisadoes** [comment]
Thanks, however we cannot assume that people who open an issue automatically want to be assigned. Sometimes an end user notices the problem and reports it, sometimes a developer opens an issue in another talawa repository after they realize it's affecting their work, there are many other reasons.

**Comment by khaledmurtaja** [comment]
> Thanks, however we cannot assume that people who open an issue automatically want to be assigned. Sometimes an end user notices the problem and reports it, sometimes a developer opens an issue in another talawa repository after they realize it's affecting their work, there are many other reasons. 
> 

You are right, but i have mentioned that i am ready to work on this issue at the same time i created the issue, maybe you did not see it because it was not bolded.
This is a good way to let you know if the issue creator wants to work on the issue or just opening it to the talawa community.

**Comment by Sumitmaithani** [comment]
@khaledmurtaja You can also add show hide feature in registering user password. This feature adds in login but not in registration.

**Comment by anshgoyalevil** [comment]
@khaledmurtaja @palisadoes 

We previously encountered this issue. Below are the points which stopped us from implementing a validation check for password field.

- In all of the tests, we are creating a test user which is relying on lowercase password using nanoid. Those tests need to be updated in case we add a validation over here.
- There needs to be taken care of i18n inputs

**Comment by khaledmurtaja** [comment]
> @khaledmurtaja @palisadoes 
> 
> We previously encountered this issue. Below are the points which stopped us from implementing a validation check for password field.
> 
> - In all of the tests, we are creating a test user which is relying on lowercase password using nanoid. Those tests need to be updated in case we add a validation over here.
> - There needs to be taken care of i18n inputs so a regex check won't work here.
> 

Aha
So we need to update the tests validation too.
Its a real bug which will prevent the user from logging it even if he entered right credintials.

**Comment by anshgoyalevil** [comment]
> > @khaledmurtaja @palisadoes
> > We previously encountered this issue. Below are the points which stopped us from implementing a validation check for password field.
> > 
> > * In all of the tests, we are creating a test user which is relying on lowercase password using nanoid. Those tests need to be updated in case we add a validation over here.
> > * There needs to be taken care of i18n inputs so a regex check won't work here.
> 
> Aha So we need to update the tests validation too. Its a real bug which will prevent the user from logging it even if he entered right credintials.

This bug won't stop users from signing in as you said.

An admin account is not supposed to be logged in using the mobile app.
Accounts made using mobile app are supposed to be logged in from mobile app only.

**Comment by palisadoes** [comment]
@khaledmurtaja Continue with the issue. Then open another one to figure out a way to do this for each supported language. This may require the person to select their preferred language earlier in the login and/or registration phase

**Comment by khaledmurtaja** [comment]
**Update**
 These days i am trying to work on the `Talawa mobile issues`, may someone else could work on this issue.
i am unassigning my self.
please, if you know someone who would like to contribute on this wonderful project mention him.

**Comment by Frey0-0** [comment]
I would like to work on this issue @palisadoes. Please assign it to me.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by BhuvanAde** [comment]
@palisadoes, I have fixed this issue and sent a PR. Can you please review it

**Comment by BhuvanAde** [comment]
I'm really sorry! As I saw It was unassigned I started on that. Can you please assign me this so that I can work? @palisadoes

**Comment by BhuvanAde** [comment]
What validations are to be applied for mail?

**Comment by palisadoes** [comment]
It's stated.
