### ISSUE TITLE
Mismatched passwords validation

### ISSUE THREAD

**Issue by Hikmahx** [PalisadoesFoundation/talawa-admin#722]
**Is your feature request related to a problem? Please describe.**
Currently when registering, if the two passwords don't match, it doesn't show until after the form is submitted.

**Describe the solution you'd like**
Raise the issue as soon as the user clicks the submit button before the form is allowed to be submitted, and when the confirmed password is being typed so the user can know immediately whether or not the passwords match.

**Actual behaviour**
<img width="1666" alt="Screenshot 2023-03-15 at 9 48 35 PM" src="https://user-images.githubusercontent.com/54153841/225440999-b1b390cf-7315-4ac2-b997-b9ac5033733d.png">

**Expected behavior**
<img width="763" alt="Screenshot 2023-03-15 at 10 13 03 PM" src="https://user-images.githubusercontent.com/54153841/225445178-048aa41b-4310-45b6-944b-a510be2912aa.png">

**Additional details**
An alternative could be to have a toggle button for the password inputs so the user can see and compare the passwords

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Hikmahx** [comment]
I would like to take this issue @palisadoes

**Comment by palisadoes** [comment]
Please change the title of this issue so that it will be more easily searchable.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Sumitmaithani** [comment]
@palisadoes can I take this issue..

**Comment by Hikmahx** [comment]
@palisadoes please I'd like to be reassigned
