### ISSUE TITLE
Bug Report: TImeout for User is short

### ISSUE THREAD

**Issue by Shugo52** [PalisadoesFoundation/talawa-admin#723]
**Describe the bug**
When signed in as superadmin, after about 17 minutes I get logged out automatically.

**To Reproduce**

1. Update or fix a timer that doesn't log users out untimely

**Expected behavior**
The admin portal would seize to log users out untimely and would allow users use the admiin portal much longer.

**Screenshots**
NO screenshots or video available for this issue raised

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Shugo52** [comment]
Please assign me this issue.

**Comment by palisadoes** [comment]
How long would you set it for and why?

**Comment by Shugo52** [comment]
First time I was logged in and going through the admin portal I got logged out automatically, which means whatever changes I was trying to make in the portal had to be started again from scratch. Say a user was inputting details about an organization and got logged out, the user would have to start again.
I propose to set the timer to be between 30 - 60 minutes to allow users to both make changes and cross check carefully whatever change is being made.

**Comment by palisadoes** [comment]
Would that be 30-60 minutes total, or after 30-60 minutes of inactivity?

**Comment by Shugo52** [comment]
I suggest 40 minutes in total. This should be enough to make changes on the admin portal.

**Comment by Shugo52** [comment]
I worked on an update for this bug but realized the implementation for this update is on the API. Am I allowed to update the API?

**Comment by palisadoes** [comment]
Yes

**Comment by palisadoes** [comment]
Yes. You need to create a separate issue for it in that repository.

**Comment by Shugo52** [comment]
Okay, thank you.
