### ISSUE TITLE
Feature Request: Adding Documentation to talawa-admin

### ISSUE THREAD

**Issue by AryanKoundal** [PalisadoesFoundation/talawa-admin#724]
**Is your feature request related to a problem? Please describe.**
The talawa-admin repository lacks documentation. Hence, as a reference for the contributors and to aid them in understanding the codebase this repository can be improved by documenting it. I found the organization wants to add documentation in this repository from https://docs.talawa.io/docs/internships/gsod/gsod-ideas/#add-base-documentation-to-talawa-and-talawa-admin-repositories section. 

**Describe the solution you'd like**
I would like to document the React Components https://github.com/PalisadoesFoundation/talawa-admin/tree/develop/src/components . I am thinking about starting from the first three, which are 
1. [AdminDashListCard](https://github.com/PalisadoesFoundation/talawa-admin/tree/develop/src/components/AdminDashListCard)
2. [AdminNavbar](https://github.com/PalisadoesFoundation/talawa-admin/tree/develop/src/components/AdminNavbar)
3. [ContriStats](https://github.com/PalisadoesFoundation/talawa-admin/tree/develop/src/components/ContriStats)

and then complete the rest as well.

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
I'll be using *TSDocs* for documenting the codebase.
*Reason to use TSDocs* : TSdocs has already been used by the organization and it provides a standard format to create efficient typescript documentation.

**Additional context**
I am not sure whom to tag. Since I found this from the https://docs.talawa.io/docs/internships/gsod/gsod-ideas#add-base-documentation-to-talawa-and-talawa-admin-repositories. So I'm tagging @palisadoes @anwersayeed

**Comment by adi-uchiha** [comment]
But why do components require docs they are pretty self-explanatory

**Comment by palisadoes** [comment]
Closing. This is issue is opened in the wrong repository. It should be in Talawa-Docs
