### ISSUE TITLE
Bug Report - Correctly Implement Admin / Super Admin Roles

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#727]
**Describe the bug**

This Admin/Super Admin functionality is not currently implemented correctly. This is how it should work:

**Background**

Say for example that a chain of non-profit community centers with branches in multiple neighborhoods decides to use Talawa. They have a large membership across the region but each member tends to use only their local community center. From time to time members move into new neighborhoods where they decide to switch their membership to their new local branch.

The VP of community relations would want to be the Super Admin as they would be able to add new branches as they were established. The VP would then delegate the management of community relations to each branch manager who would then become an Admin for their local membership.

The VP doesn’t want the branch managers to manage the members who have joined other branches, just the branch they are running.

It is for this reason that we have two types of administrators. Admins and Super Admins.

1. **Admin**: These are members who use use Talawa Admin to manage the people in an organization. This would also include calendars and the organization's news feed.
    1. Admins can only manage a single organization and cannot access any data from other organizations. Expanding this capability is a long term goal.
    1. Admins can promote Users and Members to Admin status for their organization only
1. **Super Admin:** These are members who use use Talawa Admin to manage all organizations in a community.
    1. Super Admins can promote Users and Members to Admin or Super Admin status.
    1. Super Admins have access to all the privileges that an Admin may have over the Admin's organization.

Like other people, an administrator may or may not have joined an organization in the mobile app.

**Expected behavior**
See above. 

**Actual behavior**

Depending on the PR.

1. Admins can manage multiple organizations
2. Admins can freely upgrade and downgrade themselves to SuperAdmin status

**Screenshots**
N/A

**Additional details**
Read the core concepts document for more details
- https://docs.talawa.io/docs/applications/overview
- https://github.com/PalisadoesFoundation/talawa-api/issues/1185

**Comment by adi-uchiha** [comment]
@palisadoes I have thought about something. I want to know your view.
1. For now we will create a page in admin which can only be accessed by superadmin. In that page super admin will be able to assign admin to each org. For now to keep logic simple and implement that first. We will allow only one admin per org and one admin can control only one org. 
This page will then can be incrementally developed along with api to provide more options to superadmin on what admins have access to eg: event control, post control, org settings control etc

**Comment by palisadoes** [comment]
Yes. It's s starting point.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by prathamesh-mutkure** [comment]
Hi @palisadoes, can I solve this issue?

**Comment by prathamesh-mutkure** [comment]
@palisadoes I don't understand this issue

A user can be an admin for multiple organizations. 

<img width="1018" alt="Screenshot 2023-04-04 at 11 25 34 AM" src="https://user-images.githubusercontent.com/28570857/229700332-d3e6dcd0-529c-4422-9333-2541317adb6e.png">

> Admins can only manage a single organization and cannot access any data from other organizations. Expanding this capability is a long-term goal

The Admins can already manage multiple organizations

> Admins can promote Users and Members to Admin status for their organization only

This will need a change in the `Roles` page, we'll only display users that belong to the admin's organization

> Super Admins can promote Users and Members to Admin or Super Admin status

> Super Admins have access to all the privileges that an Admin may have over the Admin's organization

These seem to be already implemented

**Comment by adi-uchiha** [comment]
@prathamesh-mutkure Currently one admin can manage multiple org. We need to change that to, Manage only single org. Later expanding this feature to -> admin can manage multiple orgs with macro permissions in other org while having a full control on only one org. Also there is no clear way in panel to assign admin to org. Such many things needs to be implemented

**Comment by palisadoes** [comment]
Take guidance from here:

- https://docs.talawa.io/docs/introduction/core-concepts#people-in-communities

The expected behaviour is clearly defined.

**Comment by prathamesh-mutkure** [comment]
This issue depends on https://github.com/PalisadoesFoundation/talawa-api/issues/1185, first needs to fixed from backend and then from front end based on it
