### ISSUE TITLE
userSettings: Need for the new endpoint

### ISSUE THREAD

**Issue by bigBrain1901** [PalisadoesFoundation/talawa-admin#728]
This is a followup on a thread described below.  
**Required: UX Redesign**

---

## Why is the update password on the organization settings page and not the person's profile?

This opens the requirement for a new page called ''User Settings' that houses 2 entries in the sidebar.
1. Update Profile
2. Change Your Password

---

## Feature Description

Via the 'Update Profile' component, the editable fields about a user include the following only.
1. firstName
2. lastName
4. appLang
5. displayImage

The following fields cannot be edited on the 'Update Profile' component.
1. userType
2. email
4. password

The 'Change Your Password' component only handles password changes for that user.

---

> The ability to freely switch between admin and superadmin is undesirable. Changing that in the PR is beyond the scope. We'll need to create a separate issue for that.

Yea, that makes sense. Thanks!

_Originally posted by @bigBrain1901 in https://github.com/PalisadoesFoundation/talawa-admin/issues/721#issuecomment-1472312432_
 
---

I request to be assigned this issue as it can be taken up as a continuation to #721

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by prathamesh-mutkure** [comment]
Hi @palisadoes, can this be made part of GSoC?

I'm planning to create a separate user profile page that can be accessed through Navbar 

Improving Navbar is already part of GSoC
