### ISSUE TITLE
Bug Report : Change Cursor for "show" in Log in dialog

### ISSUE THREAD

**Issue by BhuvaneshPatil** [PalisadoesFoundation/talawa-admin#729]
**Describe the bug**
Currently,, the `show` text doesn't have any special effect ( cursor ) that shows it's clickable, having it changed a bit ( color, cursor to pointer ) will improve UX.

**To Reproduce**

1. Go to localhost
2. Open log in dialog
3. Type something in email and password field
4. Click show button

**Expected behavior**
we will change cursor to pointer and make text darker on hover.

**Actual behavior**
Current style doesn't give sense to user if it's clickable or does something.

**Screenshots**
NA

**Additional details**
If this makes a valid issue I would like to work on this.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
We are focusing on two types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of serious bugs. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
