### ISSUE TITLE
Inefficient Query Filter On The People's Page

### ISSUE THREAD

**Issue by Sheguun** [PalisadoesFoundation/talawa-admin#730]
**Describe the bug**
When filtering by name, the result only works when the first name is inputted in the filter field and doesn't work for the surname. i.e you can't filter the name by their surname.

**To Reproduce**

1. Login into the super admin dashboard
2. Go to the people's page
3. Search for people in the input field in the FILTER BY NAME section

**Expected behavior**
It should return results irrespective of the inputted value (first name or surname), NOT just by the first name.

**Actual behavior**
It only returns results when the first name is inputted into the search box.

**Screenshots**
![Bug](https://user-images.githubusercontent.com/114509848/225711462-376c1074-f174-4b10-abea-3eb32257c338.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Sheguun** [comment]
@palisadoes I'd like to be assigned this issue. Thanks

**Comment by Sheguun** [comment]
@palisadoes Right on it sir

**Comment by saadabban76** [comment]
Nice Observation 👏🏼 @Sheguun

**Comment by Sheguun** [comment]
Thanks @saadabban76

**Comment by Sheguun** [comment]
@palisadoes For this issue, what I intend doing is I need to allow the firstName position to be interchanged with the lastName. So that irrespective of their positions, the same result will be produced.

**Comment by palisadoes** [comment]
Use the most appropriate strategy that will:

1. make the user experience excellent
2. have code that will make your changes testable
3. be the best approach in creating sustainably manageable code for the foreseeable future.

Please submit a PR for review.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by prathamesh-mutkure** [comment]
Hi @palisadoes, can I take this up?
