### ISSUE TITLE
Bug Report : user image is not same in all pages

### ISSUE THREAD

**Issue by Sumitmaithani** [PalisadoesFoundation/talawa-admin#736]
**Describe the bug**
In users section all user have 200 x 100 image but on click on specific user they have their name image.

**To Reproduce**

1. First Login to website.
2. Create organization and go to manage.
3. From navbar go to people section.

**Expected behavior**
In users section image should be same image as user detail page.

**Actual behavior**
Right now it is different.

**Screenshots**

https://user-images.githubusercontent.com/86047367/225830928-c1b9865e-f896-4e73-8c44-74eebfddd794.mp4

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by anshgoyalevil** [comment]
@Sumitmaithani 

This is the expected behavior. 

Those images are as per industry standards. Those images represent the initials of a person's name.
Check out other CHMS like BreezeCHMS. They too use the same strategy.

We are using https://www.dicebear.com/ to parse the dynamic images.

**Comment by Sumitmaithani** [comment]
@anshgoyalevil 
but same dynamic images should be used in users list also like you said BreezeCHMS also used avatar on basis of gender in all places.

**Comment by anshgoyalevil** [comment]
@Sumitmaithani 

We don't have a field for Gender in User Model, so we cannot specify an image according to user's gender.

Also, have you observed the avatar image when we create a new account on Gmail.

I guess @anurag0006 would be able to explain it better, since he introduced this feature. According to me, this is the expected behavior.

**Comment by Sumitmaithani** [comment]
@anshgoyalevil 
I'm just giving an example of gender as we used initials of name we used it in user list also

**Comment by anshgoyalevil** [comment]
@Sumitmaithani 

Thanks for pointing it out.

Please change the Users List Page to use the image of their initials just like the User Details page.
Vice versa wouldn't look good.

**Comment by anurag0006** [comment]
I think the expected behavior is Ok right now... The blank 200x100 was used as a placeholder until we get our adding image functionality Up and running....Later we can also make changes to the user model where we can have a field for gender i think

**Comment by Sumitmaithani** [comment]
@anurag0006 Okay, you reason understandable
