### ISSUE TITLE
Improve the current UI

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa-admin#74]
the current UI of the admin panel is not according to the figma designs. Someone can take this issue to improve the UI

link of the figma UI https://www.figma.com/file/KMO0QXuppBfxH9PyuI5mn2/Talawa-Admin?node-id=1%3A4

**Comment by ssaumyaa7** [comment]
@DangaRanga sir , assign me this ... it will be considered under the pull request #84
