### ISSUE TITLE
99+ Warnings in CI Workflow for Testing Application [Priority Needed]

### ISSUE THREAD

**Issue by anshgoyalevil** [PalisadoesFoundation/talawa-admin#741]
**Describe the bug**
There are a lot of warning in PR workflow for testing application. Due to which it is becoming very difficult to identify the errors while reviewing the new PRs.

The warnings state
```This typically indicates a configuration error in your mocks setup, usually due to a typo or mismatched variable.```

**To Reproduce**

1. Check PR workflow https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/4434989741/jobs/7790275873

**Expected behavior**
There should be no warning

**Actual behavior**
A lot of warnings

**Screenshots**
![image](https://user-images.githubusercontent.com/94157520/225857141-5a9fcd11-cc62-4189-a901-e5534561968a.png)

**Additional details**
This issue is connected to the issue https://github.com/PalisadoesFoundation/talawa-admin/issues/555

A lot of issues are pending under this issue which are blocking the new PRs.

Reviewing new PRs have become very difficult due to this.

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil are you looking forward to the temporary `MockLink` solution??

Yes. We need to stick to that only, since a lot of PRs are being affected.

**Comment by aviraldevv** [comment]
@anshgoyalevil its a temporary solution tbh ;)

**Comment by aviraldevv** [comment]
Not even a solution, I feel its not a good practice even to hide the warnings by the testing library. Configuration warnings may not affect the functionality of our application directly I know, but later some important warning might arise which could hamper the functionality indirectly which we will not be aware of if we use the same practice.

**Comment by anshgoyalevil** [comment]
@aviraldevv 

We need to focus more on errors rather than warnings, and hence require a quick solution since a lot of PRs are being affected.

If you will research a bit about this warning, you would observe this is arising because we can use a Mock only one time, but here, we are using it multiple times.

It will not break the functionality, rather the errors which would hide under these warning would surely break.

If you have a better solution, please go ahead and resolve it. It is affecting all of the PRs now, so please be quick.

**Comment by aviraldevv** [comment]
@anshgoyalevil I feel we should take our time to find a better solution and not hide warnings for the time being.
Can you explain me as to how `MockLink` solution can prevent the errors which hide under these warnings??

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil I feel we should take our time to find a better solution and not hide warnings for the time being. Can you explain me as to how `MockLink` solution can prevent the errors which hide under these warnings??

Okay, let me explain:

- [ ] Run tests in your local environment. Did they all pass? 
- Go to https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/4434989741/jobs/7790275873
- [ ] Were you able to find the error. Since all tests were passing in local machine?

**Comment by anshgoyalevil** [comment]
> > @anshgoyalevil I feel we should take our time to find a better solution and not hide warnings for the time being. Can you explain me as to how `MockLink` solution can prevent the errors which hide under these warnings??
> 
> Okay, let me explain:
> 
> * [x]  Run tests in your local environment. Did they all pass?
> * Go to https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/4434989741/jobs/7790275873
> * [ ]  Were you able to find the error. Since all tests were passing in local machine?

After a lot of scrolling through warning you would find an error as 
![image](https://user-images.githubusercontent.com/94157520/225869751-12e415d4-b8aa-4686-a940-5a4489919c92.png)


What if there were no warnings. This console.error would come at top. Think about it @aviraldevv

**Comment by aviraldevv** [comment]
@anshgoyalevil I understand your point but we should not hide the warnings if we cannot fix it.

Also the log you sent me I checked it out the guy has not added filter variable in mocks also he didn't modified the tests for the chagnes he made.

**Comment by anshgoyalevil** [comment]
> @anshgoyalevil 
> I understand your point but we should not hide the warnings if we cannot fix it.
> Also the log you sent me I checked it out the guy has not added filter variable in mocks also he didn't modified the tests for the chagnes he made.

Exactly, but how would that guy know about the error if there are a lot of warnings already.

**Comment by aviraldevv** [comment]
As far as I have noticed errors are just shown above the report in the logs. Also when you click on falied tests it takes you to the report section one could easily scroll a little bit up to find the error.
