### ISSUE TITLE
Failing test in LandingPage.test

### ISSUE THREAD

**Issue by akankshat05** [PalisadoesFoundation/talawa-admin#742]
**Describe the bug**
A test is failing in the LandingPage.test.

**To Reproduce**

1. Run "yarn test"

**Expected behavior**
All tests should successfully pass.

**Screenshots**

![Screenshot_2](https://user-images.githubusercontent.com/72144454/225903687-f1f72e42-2d56-4a9b-9bf3-e857cbd4e8fc.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by noman2002** [comment]
Please Pull the latest code, there might be some issue with you existing code.
