### ISSUE TITLE
Bug Report [Fix the unwanted space above the input field in the orgList component]

### ISSUE THREAD

**Issue by saadabban76** [PalisadoesFoundation/talawa-admin#744]
**Describe the bug**
Fix the unwanted margin above the search input above the search input field in orgList Page.

**Expected behavior**
Fixing this will make the UI look much better in the orgList Page.

**Actual behavior**
The Extra space wasn't there before a day or so, I would like it change the styling for Orglist Page.

**Screenshots**
![orglist](https://user-images.githubusercontent.com/115649011/225951328-762c30c2-bf10-496e-b208-1effe50d260d.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by saadabban76** [comment]
@palisadoes I'd like to be assigned to this Issue

**Comment by palisadoes** [comment]
We are focusing on two types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing

**Comment by palisadoes** [comment]
Reopening. This could be useful to have fixed in time for the UI redesign project.

**Comment by saadabban76** [comment]
Thanks for reconsidering this ❤
