### ISSUE TITLE
Bug Report for improper rendering of organization name

### ISSUE THREAD

**Issue by arushi2715** [PalisadoesFoundation/talawa-admin#747]
**Describe the bug**
This bug is for proper rendering of organization name.

**To Reproduce**
The organization name should appear as this.
`Organization Name: abc`
and the organization description should appear as this.
`Organization Description: abc`

**Actual behavior**
This is how it looks right now.

![image](https://user-images.githubusercontent.com/78142604/226027806-b5b77df0-f529-456f-a28e-0830a7294a93.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by arushi2715** [comment]
Hey @palisadoes @xoldyckk I would like to work on this. Will you please assign this to me?

**Comment by palisadoes** [comment]
It's obvious that these are the organization name. Thanks for submitting this. Please look for other issues that create a material hardship for the user. Closing
