### ISSUE TITLE
Eliminate huge white space on the Organization navbar and remove repetitive organization image when screen size is <=1199px.

### ISSUE THREAD

**Issue by Aimanosi** [PalisadoesFoundation/talawa-admin#748]
**Describe the bug**
Eliminate huge white space on the Organization navbar by aligning all nav items to the center when the screen size is <=1199px and remove repetitive organization image at the bottom of the navbar and replace it with text "more" close to the drop down arrow.

This white space makes the navbar look incomplete, It can lead to poor user experience.

**To Reproduce**

1. Open the talawa-admin app
2. Create an organization
3. Open the organization and shrink the screen size to 1199px and below.
4. click on the hamburger icon on the navbar and inspect the navbar.

**Expected behavior**
All navbar items should be aligned to the center to eliminate the huge white space and the organization image should not be repeated on the navbar.

**Actual behavior**
All navbar items are aligned to the left thereby creating a huge white space to the right when screen size is <=1199px, and the organization image is repeated on the navbar.

**Screenshots**
![nav 02](https://user-images.githubusercontent.com/104039356/226065337-d04d21ec-5869-420d-9251-b587523029c5.jpg)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Aimanosi** [comment]
Please assign this to me.

**Comment by palisadoes** [comment]
PR has been merged. Closing
