### ISSUE TITLE
Bug Report : Plugin - Add new Plugin isn't working

### ISSUE THREAD

**Issue by BhuvaneshPatil** [PalisadoesFoundation/talawa-admin#752]
**Describe the bug**
Adding plugin is not working.

**To Reproduce**

1. Create an organization.
2. Go to any organization.
3. Go to plugin store, from navbar.
4. Try adding new plugin

**Expected behavior**
Plugin should be created

**Actual behavior**
Creating plugin is not working, we are getting error

**Screenshots**
![image](https://user-images.githubusercontent.com/27822551/226097912-124466c2-7e3e-4f03-bbe1-85fa501102c8.png)

**Additional details**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by BhuvaneshPatil** [comment]
this is a valid issue, I want to work on this.

**Comment by anshgoyalevil** [comment]
@palisadoes @BhuvaneshPatil 

This is duplicate to the issue https://github.com/PalisadoesFoundation/talawa-admin/issues/553#issuecomment-1475104443

The plugin system doesn't work, and there is no proper resolver to handle the plugins data.

Currently, we are taking the input of a plugin as if they are a blog post. There is a separate GSoC idea for this functionality.

**Comment by palisadoes** [comment]
Correct. Closing.
