### ISSUE TITLE
Bug Report: Organizations Post Media Upload Issues

### ISSUE THREAD

**Issue by Hikmahx** [PalisadoesFoundation/talawa-admin#756]
**Describe the bug**

There are a number of issues I found on the Organisation Post Page when a user tries uploading an image or a video, from the empty links to the video input field error, making it impossible to upload an image to video to a post

**To Reproduce**

1. Login to talawa admin after setting up talawa admin and API
2. Click on the manage button of any organization on the Organization List page
3. Click on Post on the Statistics Page
4. Create a Post

**Expected behavior**

The video file input should only allow videos to be uploaded through it. The image and video should be uploaded into the database when a user uploads them, and the image URL and video URL should either display 'No image/video uploaded' or should be hidden if either isn't uploaded by the user

**Actual behavior**

1.  The image URL and video URL are empty, even when a user uploads a video and an image.
2. The video accepts images only instead of only video files
3. I checked the database and the imageUrl field shows null while the videoUrl field is not found in the database even though it is in the model.

**Screenshots**

<img width="1680" alt="Screenshot 2023-03-18 at 4 53 49 PM" src="https://user-images.githubusercontent.com/54153841/226116596-6f54e492-8d5e-4934-a0d5-9afcd2f12911.png">

<img width="1680" alt="Screenshot 2023-03-18 at 4 34 26 PM" src="https://user-images.githubusercontent.com/54153841/226116386-d4f00827-6864-4616-84b4-101dc7e88298.png">

<img width="1680" alt="Screenshot 2023-03-18 at 4 32 43 PM" src="https://user-images.githubusercontent.com/54153841/226116405-9e84aa54-1dec-48ad-ad64-3e9cf8bb5f89.png">

**Additional details**

I think maybe after solving the issue of the image upload, perhaps it should be displayed above the post details. Also, it may be better to have a separate page for the post to be displayed when the user clicks on it.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Hikmahx** [comment]
I would like to take this issue @palisadoes

**Comment by palisadoes** [comment]
@Hikmahx This may be related to this PR. https://github.com/PalisadoesFoundation/talawa-api/pull/1168
Take a look and and your comments if required.

**Comment by adi-uchiha** [comment]
This requires api changes

**Comment by palisadoes** [comment]
Closing. This is solved
