### ISSUE TITLE
Bug Report : Eliminate huge white space on the super admin navbar when screen size is <=1199px. 

### ISSUE THREAD

**Issue by Aimanosi** [PalisadoesFoundation/talawa-admin#757]
**Describe the bug**
Eliminate huge white space on the super admin navbar by aligning all nav items to the center when the screen size is <=1199px, This white space makes the navbar look incomplete, It can lead to poor user experience.

**To Reproduce**

1. Open the talawa-admin app.
2. Log in as super admin.
3. Reduce screen size to <=1199 and observe the navbar.

**Expected behavior**
All navbar items should be aligned to the center to eliminate the huge white space.

**Actual behavior**
All navbar items are aligned to the left thereby creating a huge white space to the right when screen size is <=1199px.

**Screenshots**
![superAdmin navbar](https://user-images.githubusercontent.com/104039356/226118608-149e734c-60b3-4b7c-9c87-9214fa9b7e14.jpg)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Aimanosi** [comment]
Please assign this to me.

**Comment by palisadoes** [comment]
This is your third assignment. Our policy is to only assign 2 issues per person so that others can get a chance. This is and important bug as it will remind people redesigning the UI/UX to think of this.

Make sure to request new assignments when you are under 2 assigned issues.

**Comment by Aimanosi** [comment]
Okay, thank you very much!
