### ISSUE TITLE
New Talawa-Docs HomePage - React/Typescript Experience Needed

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#759]
The Talawa Documentation site at https://docs.talawa.io has a very basic home page. 

![image](https://user-images.githubusercontent.com/16875803/226144878-28129214-7b13-46f5-bac3-a9865801e537.png)

The home page will be catering to non-profit administrators who want to manage their teams. So the layouts need to have a higher quality of clipart and greater use of royalty free images of people. The focus needs to be on:
1. the various features;
2. the advantages of using each of these features;
3. the benefits to the organization of using the feature, not to the IT team.

We need a more modern template, possibly one with screen width images and/or graphics. We are a small group of volunteers, and we need to project ourselves globally with confidence. Therefore we need the look of a Fortune 500 company on the home page. What’s behind the home page can be updated later. 

Take a look at these global and industry specific sites for inspiration. 

1. [ChurchCRM](http://churchcrm.io/)
4. [Infosys](https://www.infosys.com/)
5. [Nokia](https://www.nokia.com/)
6. [Tata](https://www.tata.com/)
7. [SalesForce](https://www.salesforce.com/)
8. [Cisco](https://www.cisco.com/)
9. [Microsoft](https://www.microsoft.com/)
10. [Nestle](https://www.nestle.com/)
11. [Bua Foods](https://www.buafoodsplc.com/)

Take a look at the [Talawa Branding Requirements](https://docs.talawa.io/docs/design/branding) We need to make sure the design incorporates subtle elements of the Talawa color scheme.

We also need to address the key aspects not just of Talawa features but also that:

1. We are an open source project run 100% by volunteers.
2. We have been recognized by open source programs such as GSoC, Outreachy and the GitHub Externship.

We started working on this, but the idea stalled. There is a lot of guidance on that page as to what the content would be.

- https://github.com/PalisadoesFoundation/talawa-docs/issues/344

The  https://docs.talawa.io website is automatically updated with new PR merges of the Talawa Docs repository. 

1. Talawa Docs uses Docusaurus to generate its HTML content from markdown files.
2. You will need to be familiar with how to run docusaurus to verify any changes you make. The instructions are easy.
3. The current home page files seem to reside here: https://github.com/PalisadoesFoundation/talawa-docs/tree/develop/src
4. Docusaurus provides information on how to use non-markdown React and Typescript files with it. https://docusaurus.io/docs/creating-pages

Some additional information:

1. We will only consider persons with proven experience merging multiple typescript code PRs in this repository. 
2. We will reopen the original https://github.com/PalisadoesFoundation/talawa-docs/issues/344 issue and assign it to you.
3. Using a template will be OK, as long as it meets the requirements in this and the other issue.

https://docs.talawa.io is the first impression people get of our website and it needs to be world class. Surprise us!

**Comment by aviraldevv** [comment]
@palisadoes Assign this to me I will fix it up on priority.

**Comment by palisadoes** [comment]
Ask to be assigned the Talawa-Docs issue too

**Comment by palisadoes** [comment]
@aviraldevv 

1. Try to find a template that has similar elements to the last template discussed in the Docs issue. We already have suggestions related to it.
2. Try to use [the Talawa branding colors](https://docs.talawa.io/docs/design/branding) for subtle highlights.
    1. In other words, a blue or red theme won't work.
    2. Yellow on white is not a good combination.

**Comment by saadabban76** [comment]
@palisadoes sir, can I also collaborate on this issue ?, I would like to work on the development part after the redesign of this home page.

**Comment by aviraldevv** [comment]
> @aviraldevv
> 
> 1. Try to find a template that has similar elements to the last template discussed in the Docs issue. We already have suggestions related to it.
> 2. Try to use [the Talawa branding colors](https://docs.talawa.io/docs/design/branding) for subtle highlights.
>    
>    1. In other words, a blue or red theme won't work.
>    2. Yellow on white is not a good combination.

@palisadoes I am up on it and doing the needful.

**Comment by TheoCathy** [comment]
Can we work together to solve this particular issue? I can collaborate with @aviraldevv  on design or development aspect. It seems like a two man task given its priority.  @palisadoes

**Comment by kayceeDev** [comment]
If this issue requires collaboration, Can I collaborate with @aviraldevv on this?

**Comment by aviraldevv** [comment]
Thanks for reaching out, @saadabban76, @TheoCathy, and @kayceeDev. I appreciate your willingness to offer assistance. I am open to any ideas or suggestions that you may have for improving the end user experience. I will surely consult you'll in case I get stuck.
p.s.- Design ideas and feedbacks will definitely help.

**Comment by aviraldevv** [comment]
@palisadoes @saadabban76 @TheoCathy @kayceeDev some inital work :) A lot of changes are coming up.

![Screenshot_446](https://user-images.githubusercontent.com/121368112/226179362-e6d9bcd8-549f-48a2-b4be-04726648885a.png)

**Comment by saadabban76** [comment]
@aviraldevv the blur effect around the center title will highlight the title text in homepage, try to add it 👍🏼

**Comment by kayceeDev** [comment]
Yes. Add a dark overlay on the background image. This will help show the text content in the hero section.

**Comment by aviraldevv** [comment]
Does the image look good to you guys?? if you find any image which might look better send it to me I'll give it a try.

**Comment by aashimawadhwa** [comment]
We can also try adding Carousel of various images for the hero section.

**Comment by palisadoes** [comment]
> Does the image look good to you guys?? if you find any image which might look better send it to me I'll give it a try.

We can fix the image later. The other components need attention as mentioned in the original issue.

**Comment by literalEval** [comment]
@aviraldevv please let me know if you have any discussion regarding the design :)

**Comment by Aimanosi** [comment]
This is an interesting project.

**Comment by aviraldevv** [comment]
EOD Update -

https://user-images.githubusercontent.com/121368112/226208443-c64f4ac5-9908-4541-8290-cf7d06b4024a.mp4

**Comment by palisadoes** [comment]
This is very good. It seems like you have figured out the basics. 
1. Is there a way to mimic the design in the original issue? 
2. For example export a similar one page typescript based template from an open source repo and adjust it to what we have?

**Comment by Cioppolo14** [comment]
It's looking good! I appreciate the updates!

**Comment by saadabban76** [comment]
> EOD Update -
> 
> https://user-images.githubusercontent.com/121368112/226208443-c64f4ac5-9908-4541-8290-cf7d06b4024a.mp4
> 
> 
> 
> 
> 
> 

The design looks very good, appreciative 👏

**Comment by aviraldevv** [comment]
@palisadoes give me some time to explore available one-page templates. If I find a suitable template, I'll try to adapt it to our homepage. Alternatively, I can continue customizing our current design as we've been doing so far. It might take a bit of time, please let me know if you have any preferences or additional suggestions.

**Comment by aviraldevv** [comment]
@palisadoes @Cioppolo14 

I was considering creating the basic layout for our homepage by adding content row-wise, accompanied by appropriate headings. I would greatly appreciate your input and suggestions on the number of rows we should include, their order, and a basic idea of the content each row should have. We can customize on top of it later on.

**Comment by palisadoes** [comment]
@aviraldevv Check slack for the content

**Comment by aviraldevv** [comment]
Guys check out our new website it's up and running!

**Comment by aviraldevv** [comment]
@palisadoes we can close this issue now.

**Comment by literalEval** [comment]
@aviraldevv where ?

**Comment by anshgoyalevil** [comment]
@aviraldevv 

I just checked the website.

- You have removed the dark theme support from the complete website.
- The home page is not 100% responsive.

**Comment by aviraldevv** [comment]
@anshgoyalevil I know that I will be working on it in subsequent PRs.

**Comment by aviraldevv** [comment]
> @aviraldevv where ?

bro checkout docs.talawa.io/

**Comment by literalEval** [comment]
Cool

**Comment by saadabban76** [comment]
> > @aviraldevv where ?
> 
> bro checkout  http://docs.talawa.io/

Nice work 👏

**Comment by aviraldevv** [comment]
Thanks @saadabban76 it really means a lot.
