### ISSUE TITLE
Figma design - add registration option too

### ISSUE THREAD

**Issue by ssaumyaa7** [PalisadoesFoundation/talawa-admin#76]
The current Figma design has just one entry point that is the login page.
![pali1](https://user-images.githubusercontent.com/64359826/121460772-29194c80-c9cb-11eb-90c1-f2e29e5f274f.PNG)

There is a big question that how organization would register and get verified to have their own account.
Every organization account created should be verified by a few documents and organization should be registered.

So on the entry page design needs to be edited
![pali2](https://user-images.githubusercontent.com/64359826/121463990-aabfa900-c9d0-11eb-9c9a-165270a5662a.PNG)

**Additional details**
GitHub Externship : 19-05_Sin666_tfa_262

Would like to work on improving UI/UX of the admin portal.
@palisadoes @yasharth291

**Comment by ssaumyaa7** [comment]
The organization creator (super admin) needs to be verified and registered else anyone can register themselves as super admin so for anyone to apply as super admin we need them to register then we can verify them and only after super admin can be assigned and we can move further.

**Comment by ssaumyaa7** [comment]
The question is why should super admin be allowed to register ?
Well, I think the admin portal should be open to people across, people can register but only the ones who are verified can become super admin and can create an organization.

@DangaRanga

**Comment by DangaRanga** [comment]
Good day Samuya, I apologize for the late response
I do agree that super admins should be able to register for accounts, which would include adding their organization, along with the administrators that may fall underneath their organization, but I'll have to confirm  if this was one of the requirements of Talawa-Admin or if we had another method for giving Super Admins and Admins access to Talawa-Admin to manage their organization, such as them registering through the app, and using those credentials to log into Talawa-Admin

But in general, if super admins could register, it could potentially improve the user experience of Talawa Admin.

**Comment by ssaumyaa7** [comment]
Yes sir this will give better insight to user's about the working of the Talawa app and will give every organization a chance to get themselves registered for the same.

If assigned I would like to move ahead to present a design for the same. 

1. Get super admin register
2. verify the organization they work for by ID proof
3. get OTP and email verification 
4. after that allow login of super admin to create events for organization

@DangaRanga sir

**Comment by yasharth291** [comment]
@ssaumyaa7 on question who will be verifying the super admins

**Comment by ssaumyaa7** [comment]
@yasharth291 let's discuss this with @DangaRanga sir, because for now, someone is adding super admin on backend right that's the flow for now.
Moreover, without the right verfication, it's not so good to allow them to create organization and events.

Once getting a headstart on this feature will work more to join all the edges for the right flow.

**Comment by ssaumyaa7** [comment]
@palisadoes sir @DangaRanga sir, please assign me this, I would like to work on it.

**Comment by yasharth291** [comment]
@DangaRanga  its done you can close it
