### ISSUE TITLE
Bug allowing Superadmins to downgrade themselves to lower roles

### ISSUE THREAD

**Issue by Kelvyn2012** [PalisadoesFoundation/talawa-admin#764]
**Describe the bug**
There is a feature that allows superadmin/admin users to downgrade their roles. This can potentially result in a superadmin or admin being locked out of the system if they are the only users with that high level of access. which could cause disruptions in the system's workflow.

**Proposed Solution**
To address this issue, I propose preventing an admin/superadmin from updating their own role by disabling the role update input.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by Kelvyn2012** [comment]
@palisadoes Please assign this to me

**Comment by palisadoes** [comment]
This also needs to be added to the API. Please add an issue there too.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by prathamesh-mutkure** [comment]
Hi @palisadoes, can I take this up?

**Comment by adi-uchiha** [comment]
This also needs to be implemented in api also. Anyone can easily bypass this.

**Comment by adi-uchiha** [comment]
@prathamesh-mutkure i think it was added recently. I'm not up-to-date with latest commits. MB!
