### ISSUE TITLE
Code Coverage: Create tests for AddOnStore.tsx

### ISSUE THREAD

**Issue by Sumitmaithani** [PalisadoesFoundation/talawa-admin#768]
**Describe**

`src/components//AddOn/core/AddOnStore/AddOnStore.tsx`

**Expected behavior**
![Code coverage report for components_AddOn_core_AddOnStore - Google Chrome 3_20_2023 12_19_21 PM](https://user-images.githubusercontent.com/86047367/226267597-0c69eed3-f01f-405e-9a9c-44ee2fdc0522.png)

**Actual behavior**
![Code coverage report for src_components_UserPasswordUpdate - Personal - Microsoft​ Edge 3_20_2023 11_49_58 AM](https://user-images.githubusercontent.com/86047367/226267563-6ea9601f-d8ec-4be7-a82e-5f3401867b91.png)

**Summary**
This file must show 100% coverage

**Comment by KrutikaBhatt** [comment]
Hey, can I work on this ?

**Comment by anshgoyalevil** [comment]
@Sumitmaithani @KrutikaBhatt 
This issue is duplicate for https://github.com/PalisadoesFoundation/talawa-admin/issues/402#issuecomment-1475111187

The above issue was closed because of plugin system as a GSoC idea.

**Comment by Sumitmaithani** [comment]
@anshgoyalevil 
Write tests for a code and code coverage are two different things. As you see In my local i solved that without getPluging data and why to solved it because  see report on this [PR](https://app.codecov.io/gh/PalisadoesFoundation/talawa-admin/pull/750) getting error on CI.

**Comment by anshgoyalevil** [comment]
@Sumitmaithani 

We don't have to chase code coverage. Code coverage is a measure of how much code is tested, and is working perfectly.

In this case, the AddOnStore.tsx is relying on Plugin Mutation. If the Plugin Mutation doesn't work, does that makes sense to write test for such a thing?

**Comment by Sumitmaithani** [comment]
@anshgoyalevil 
"We don't have to chase code coverage." wat are you saying please read talawa contribution guide theyy clearly mention "All code submitted must be tested. We are working towards getting to 100% test code coverage on all Talawa repositories."
