### ISSUE TITLE
Bug Report: change the "Show" & "text on the password preview feature to an icon to prevent the need for translation.

### ISSUE THREAD

**Issue by Aimanosi** [PalisadoesFoundation/talawa-admin#769]
**Describe the bug**

**To Reproduce**

1.
2.
3.
4.

**Expected behavior**

**Actual behavior**
A clear and concise description of how the code performed w.r.t expectations.

**Screenshots**

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
This issue is already fixed in #758 . Try taking a pull to view recent changes.

**Comment by Aimanosi** [comment]
@aashimawadhwa @palisadoes  Hi, I had not completed the application before I mistakenly submitted it, I was proposing to the do this for the log-in page.

**Comment by aashimawadhwa** [comment]
Yes i have changed for login modal to in that pr

**Comment by Aimanosi** [comment]
Oh, okay, thank you.
