### ISSUE TITLE
Usability issues with Notification

### ISSUE THREAD

**Issue by BhuvanAde** [PalisadoesFoundation/talawa-admin#771]
**Describe the bug**
After opening organisation page in TALAWA ADMIN. We need to click TALAVA ICON to navigate through the notifications.
**To Reproduce**

1. Open TALAWA ADMIN 
2. Open Organisation page
3. Click TALAWA ICON in the top right corner.
4. Then you could see Notifications .
5. Click Notifications to access notifications

**Expected behavior**
After accessing the Organization page beside TALAWA ICON, I expected to see it there which takes only around two steps. My research indicates that finding the notification icon requires upto five steps, and that the task itself is difficult to complete. Instead, adding notifications to the organisation page would enhance usability overall.
**Actual behavior**
After opening the organization page and clicking the TALAWA ICON, from there I could access Notification. And people aren't expecting it to be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/81461629/226433739-44cf2572-af05-4dd0-aca8-535fb8374a9e.png)

**Additional details**
People struggle with usability when trying to access the organization's notification panel. Some people in TALAWA-ADMIN are similarly unaware of the notifications that are intended to help them navigate. Although this might be considered a minor issue, it would greatly enhance the process of exploring notifications.
**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by noman2002** [comment]
This is not needed for now, we are currently focusing on functionality. We will be improving the UI as a part of GSoC project.
