### ISSUE TITLE
More detailed or Functional Plugin page

### ISSUE THREAD

**Issue by TheoCathy** [PalisadoesFoundation/talawa-admin#774]
**Is your feature request related to a problem? Please describe.**
The current page gives a false impression that plugins needs to be installed and user might go ahead to try to install a plugin but  is met with a non functional page.

**Describe the solution you'd like**
Since the application is still working on getting the necessary 3rd party plugins why not make everything on the page static and uneditable while showing the message "Plugins Coming Soon" to pass a clear message to the user that the particular feature is not available yet.

**Describe alternatives you've considered**
Prioritise or include accessible  plugins to allow the plugin feature functional

**Approach to be followed (optional)**
If the former:
1. make page uneditable
2. Display a more informative message for users

If the later
1. Decide on what plugins to integrate
2. Download and Install plugin for typescript and react framework
3. Integrate and test plugin 

**Additional context**
<img width="1440" alt="Screenshot 2023-03-20 at 21 46 51" src="https://user-images.githubusercontent.com/107179983/226470546-702a5caa-1795-48ab-b416-8285636460b4.png">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
Thanks. Fixing plugins is a GSOC 2023 idea. This will most likely be resolved this summer as part of a bigger project. Thanks for pointing this out. Please continue to make issue suggestions on major bugs or features that provide the end user with serious hardship. Closing.
