### ISSUE TITLE
Bug Report :  Drawer menu options are not clearly visible 

### ISSUE THREAD

**Issue by indresh149** [PalisadoesFoundation/talawa-admin#775]
**Describe the bug**
Options in the Drawer menu of the Talawa Admin portal are not visible clearly due to overflow from the screen.

**To Reproduce**

1. Set up the Talawa-admin project on your local machine.
2. log in to the Talawa-admin.
3. On the dashboard click on the drawer menu option on the top right.
4. The menu options are not visible clearly.

**Expected behavior**
The menu options should be clearly visible to the end user.

**Actual behavior**
The menu options are not clearly visible due to overflow issues.

**Screenshots**
![image](https://user-images.githubusercontent.com/76736055/226565382-da555a50-f6ba-47dd-8d6f-15b807cea23b.png)

**Additional details**
See above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by indresh149** [comment]
@palisadoes may I work on this issue?

**Comment by aashimawadhwa** [comment]
I think #776 and #775 these both can be soled in a single PR both are related to each other.

**Comment by palisadoes** [comment]
Closing

**Comment by indresh149** [comment]
@palisadoes sir may I now work on this issue?
