### ISSUE TITLE
Bug Report :  Nav bar options are not aligned properly

### ISSUE THREAD

**Issue by indresh149** [PalisadoesFoundation/talawa-admin#776]
**Describe the bug**
Nav bar options are not aligned properly in Talawa- Admin portal.

**To Reproduce**

1. Set up the Talawa-admin project on your local machine.
2.log into the Talawa-admin.
3. On the organization's dashboard the plugin menu is not properly aligned with other menu options

**Expected behavior**
All the Nav Bar options should be in the same alignment.

**Actual behavior**
The plugin menu in Nav Bar is not properly aligned with other options.

**Screenshots**
![image](https://user-images.githubusercontent.com/76736055/226568854-055f5209-8b73-4708-b777-5a98c8e58666.png)

**Additional details**
See Above

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by indresh149** [comment]
@palisadoes sir may I work on this?

**Comment by palisadoes** [comment]
We need to focus on issues that fix real hardships for the end user. This includes breaking bugs or fixing features that don't work causing administration to be difficult. Closing
