### ISSUE TITLE
Change the delete icon to red in the events card

### ISSUE THREAD

**Issue by Ladyperpetua** [PalisadoesFoundation/talawa-admin#782]
**Describe the bug**
The current calendar on the "events page" shows the bin/delete icon that is displayed on a new event card created on a particular date, the bin/delete icon appears to be black when hovered on, this could turn out insignificant when hovered on and could lead to accidental deletions. I suggest the color of the bin/delete icon be changed from black to red to ensure more significance. And I also propose there be a pop hover text around the icons delete and edit for assurance before clicking. this change would help young and old users to be sure of their actions on the screen before taking them.  

**To Reproduce**

1. Set up the talawa-admin project on your local machine
2. Login to the talawa admin
3. Click on any "manage" button on the organizations list
4. Go to events and click on it
5.  Click the "+add events" button on the top right corner and create an event
6. An events would be created on a date on the calendar therefore showing the delete and edit icon 

**Expected behavior**
The delete icon should appear in red and there is no hover text around the icon to indicate it is a delete and edit icon 

**Actual behavior**
The delete icon appears to be black. also there should be a hover text around the icons 

**Screenshots**
![events calendar](https://user-images.githubusercontent.com/70077989/226793463-fa2d0d28-3dbf-456c-9a52-c63ea9532519.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
Hey this is solved in #772 .

**Comment by Ladyperpetua** [comment]
> Hey this is solved in #772 .

I don't think so, I checked to change bin color to red and also hover text around the icon, couldn't find

**Comment by aashimawadhwa** [comment]
Please check the requested changes I am working on it, will push them today.

**Comment by Ladyperpetua** [comment]
if you please point me in the right direction of when that change was implemented

**Comment by aashimawadhwa** [comment]
https://github.com/PalisadoesFoundation/talawa-admin/pull/772/files#r1143592369 
I am working on it.

**Comment by DishaRawal** [comment]
hey, if the issue's still open, i would be glad to work on it. kindly assign it to me.

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
