### ISSUE TITLE
Events card should span across dates

### ISSUE THREAD

**Issue by Ladyperpetua** [PalisadoesFoundation/talawa-admin#783]
**Describe the bug**
When you try to create a new event by clicking the "add events" button on the events page, you're directed to a new page where you fill out an "events details" form; say you fill out the date duration by giving the start date 3/22 and end date 3/26, After filling out the form and you by chance make the event a RECURRING EVENT by ticking the recurring box, you finally create an event, and close that page. you would only find your event card on the start date and not till the end or on the end date. I propose making the date span across the dates you applied if you make the event a recurring event. That way it clears confusion for end users. 

**To Reproduce**

1. login to the talawa admin
2. click on manage on one of the organizations
3. click on events
4.click on "add events"

**Expected behavior**
the events card should span across both the start date till the end date should one click on recurring events when creating a new event.

**Actual behavior**
the events card only shows on the start date of the event created.

**Screenshots**
![recurring span](https://user-images.githubusercontent.com/70077989/226796236-cbd5c0cb-f60f-426b-8158-67dd2e1c302d.png)
![events card one](https://user-images.githubusercontent.com/70077989/226796423-16ab7cf4-b713-4539-9b47-c0d1515271a6.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by KrutikaBhatt** [comment]
Hey, can I work on this issue?

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
