### ISSUE TITLE
pop-up hover text on questions

### ISSUE THREAD

**Issue by Ladyperpetua** [PalisadoesFoundation/talawa-admin#784]
**Describe the bug**
The "create events" on the events page displays a form on events details. This form consists of title, description, location, dates and a few questions with checkboxes below. The questions like the "all day?", "recurring events", "is registrable" could appear a confusing and vague for some users. A pop-up hover text would provide an explanation of what those questions mean in particular. Without this feature, users may be confused or unsure about what the questions represent. this could lead to incorrect selections for users who are trying to fix appointments for example. 

**To Reproduce**

1. login to the talawa admin portal
2. click on manage on an organization
3. click on events 
4. click on add events

**Expected behavior**
There should be a pop-up hover text/explanation of what the questions mean

**Actual behavior**
There is no explanation of what the questions mean

**Screenshots**
![pop hover text to show what they mean](https://user-images.githubusercontent.com/70077989/226798905-2fae6b29-d027-4784-beb7-79c401ab91e8.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by nishtha981** [comment]
I have solved this issue.
What exactly would you like the text to be in the hover for different options.

![image](https://user-images.githubusercontent.com/92522516/226830726-5d04a618-d802-4c66-8a92-f97aa12ca1bf.png)

**Comment by Ladyperpetua** [comment]
@palisadoes please sir, can you please assign this issue to me if approved?

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
