### ISSUE TITLE
Admin card redirects to members page

### ISSUE THREAD

**Issue by Ladyperpetua** [PalisadoesFoundation/talawa-admin#787]
**Describe the bug**
The admin card on the organization dashboard shows the admin of the organization when registering on the talawa portal. the admin card directs to a members page instead of the admins page when clicked on. this action makes the site not work as expected. this could cause a user to make changes to the wrong profile if not carefully examined.

**To Reproduce**

1. login to the talawa portal
2.click manage on the organization created
3. click on the admin card on the admin dashboard

**Expected behavior**
the admin card when clicked on should be directed to an admin page

**Actual behavior**
the admin card when clicked on directs to a members page

**Screenshots**

https://user-images.githubusercontent.com/70077989/226917461-ea92d103-ca74-489c-bd63-36a41c35c5a6.mp4

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
This is the expected behaviour for now. Closing.
