### ISSUE TITLE
Make website responsive

### ISSUE THREAD

**Issue by ssaumyaa7** [PalisadoesFoundation/talawa-admin#79]
The admin portal is not responsive on any screen sizes. This is a problem as the admin might access it through different screens and variation in UI would not result in a good user experience.

@palisadoes sir would like to work on this issue.

![res](https://user-images.githubusercontent.com/64359826/121650243-fea4bd80-cab6-11eb-94d0-54bd2f102e1d.PNG)

**Additional details**
GitHub Externship : 19-05_Sin666_tfa_262

**Comment by yasharth291** [comment]
@palisadoes i don't think sir the admin panel should be responsive as it is mainly for the use of desktop

**Comment by ssaumyaa7** [comment]
@DangaRanga sir, 
@yasharth291 if with minor changes we can make it responsive than I think that would add bonus

**Comment by Sagar2366** [comment]
@ssaumyaa7 use issue template while creating new issues and always  provide meaningful title to it.
