### ISSUE TITLE
Feature Request [Filter by Event field is not necessary in orgPeople's Page]

### ISSUE THREAD

**Issue by saadabban76** [PalisadoesFoundation/talawa-admin#790]
**Describe the solution you'd like**
Filter by Event in the orgPeople's page is not necessary and the field does not perform any operation on searching in the input field.

**Describe alternatives you've considered**
Remove the Filter By Event section and filter the users by name, admin and members.

**Additional context**
![people paeg](https://user-images.githubusercontent.com/115649011/227114428-57cbb547-5edb-47cc-96cf-c4135e014e6e.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by KrutikaBhatt** [comment]
Can I work on this issue?

**Comment by saadabban76** [comment]
Thanks for the interest @KrutikaBhatt but I'll like to work on this, You can check out other un assigned issues in issues page

**Comment by aashimawadhwa** [comment]
Hey this is a duplicated of #627 we bave to remove serach and implement a datepicker instead.

**Comment by saadabban76** [comment]
> Hey this is a duplicated of #627 we bave to remove serach and implement a datepicker instead.

Cool 👍I'll close this issue.

**Comment by aashimawadhwa** [comment]
@saadabban76 i am sorry i misread it i am working on filter for events in the events tab it is in organization people tab as well. You can reopen it. I apologise for the comment.

**Comment by saadabban76** [comment]
> @saadabban76 i am sorry i misread it i am working on filter for events in the events tab it is in organization people tab as well. You can reopen it. I apologise for the comment.

Opps even I didn't see it's orgPeople page not event page my bad 😅

**Comment by saadabban76** [comment]
@palisadoes can you please assign this to me?
