### ISSUE TITLE
Bug: Menu bar is not responsive

### ISSUE THREAD

**Issue by nishant3721** [PalisadoesFoundation/talawa-admin#791]
**Describe the bug**
The menu navigation bar is not responsive.

**To Reproduce**

1. Signup/Login to Talawa Admin
2. Navigate to the main homepage
3. Click on Menu Button in Navbar

**Expected behavior**
All the menu items should be UI-friendly and responsive

**Actual behavior**
Menu items are expanding out of the screen and are not responsive

**Screenshots**
![image](https://user-images.githubusercontent.com/76558924/227127983-41fc7325-799f-4ef8-ac72-ff08b40289d8.png)

**Additional details**
Not Required

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by nishant3721** [comment]
@palisadoes I would like to work on this issue.

**Comment by KrutikaBhatt** [comment]
@nishant3721, this issue is a duplicate to issue mentioned in #775.

**Comment by nishant3721** [comment]
@KrutikaBhatt Oh apologies for that!

**Comment by KrutikaBhatt** [comment]
No issues!
