### ISSUE TITLE
Bug Report: Recurring Events checkbox does not perform the required functions

### ISSUE THREAD

**Issue by nishtha981** [PalisadoesFoundation/talawa-admin#793]
**Describe the bug**
The recurring events checkbox does not work i.e. when selected while creating an event it does not provide an option to specify the recurring time span.

**To Reproduce**

1.Set up the Talawa-admin project on your local machine.
2. log in to the Talawa-admin.
3. On the dashboard click on the Events tab
4. Create an event using the add events button on the top right
5. Select the recurring event checkbox

**Expected behavior**
There should be an option to select the repeat duration ex. if the event is a daily, weekly, monthly etc event. Based on the recurring pattern the event should show up on the calendar.

**Actual behavior**
It just creates an event therefore it's a dummy checkbox and the event will not show up in the calendar beside the date it is scheduled.

**Screenshots**

<img width="618" alt="image" src="https://user-images.githubusercontent.com/92522516/227167431-6ea4d326-916c-4aef-b71c-df9a9289ceb3.png">
After clicking on the checkbox no options show up

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by nishtha981** [comment]
Can I be assigned this issue?

**Comment by KrutikaBhatt** [comment]
Hey @nishtha981, this issue was covered in  #783. It is a pending feature which is closed for now as it will very difficult to operate the apps.
