### ISSUE TITLE
Feature Request: Private Events 

### ISSUE THREAD

**Issue by kayceeDev** [PalisadoesFoundation/talawa-admin#795]
**Is your feature request related to a problem? Please describe.**
The participants in all events are publicly visible to everyone. There need to be options for more privacy.

REF : [#354](https://github.com/PalisadoesFoundation/talawa-api/issues/354)

**Describe the solution you'd like**
1. The ability to make events private where only participants can see who is attending
2. The optional ability to make private events invisible to persons not attending

**Describe alternatives you've considered**
This is my thought process:
When a user is added as a participant to an event, the user details are added to the participants' array. We could actually make that happen, for example, after we fetched events, when rendering the event in the admin, we can have a check that filters on event visibility. If the event is private, we will then check if the user id is in the list of participants. If it is present then we add the private event to the calendar, else we don't add it. But if the event visibility is public then we don't need this check. We will just add it to the calendar.

The `SUPERADMIN` will have the right to see both private and public events. The `ADMIN` will see both Private and Public events of the organizations he is in charge of.

**Additional context**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kayceeDev** [comment]
@palisadoes Please assign me.

**Comment by palisadoes** [comment]
This is going to be addressed in a GSoC idea. Closing.

**Comment by palisadoes** [comment]
Reopening. It's not specifically highlighted in the ideas page.
