### ISSUE TITLE
Adding PR template 

### ISSUE THREAD

**Issue by yasharth291** [PalisadoesFoundation/talawa-admin#8]
Adding a pr template is also good

**Comment by palisadoes** [comment]
Please make sure your work includes these pre-existing files imported from our other repos.

1. https://github.com/PalisadoesFoundation/talawa-admin/tree/master/.github/ISSUE_TEMPLATE
1. https://github.com/PalisadoesFoundation/talawa-admin/blob/master/.github/pull_request_template.md
