### ISSUE TITLE
develop branch

### ISSUE THREAD

**Issue by ssaumyaa7** [PalisadoesFoundation/talawa-admin#80]
Navbar is only perfectly visible on laptop screen: 1440 x 570
Besides that, the navbar is not perfectly placed on either the laptop screen greater than 1440 x 570 neither on the laptop screen 1024 x 570.

Talawa logo goes missing on laptop screen change : 
![nav](https://user-images.githubusercontent.com/64359826/121657282-e4baa900-cabd-11eb-9644-ea413bb1b3a2.PNG)

Need to improve this. (at least for laptop screen there needs to be consistency)

@palisadoes sir can I work on this issue ?

**Comment by yasharth291** [comment]
i think this will come under responsive so its duplicate

**Comment by yasharth291** [comment]
@palisadoes this issue is duplicate and could be closed

**Comment by Sagar2366** [comment]
@yasharth291 please mention duplicate issue as well here.

**Comment by yasharth291** [comment]
#79

**Comment by Sagar2366** [comment]
Great, @ssaumyaa7 please mention all your observations in issue 79.
