### ISSUE TITLE
Events Page: Calendar cells increase in height and width as new events are added

### ISSUE THREAD

**Issue by BlessingOkonkwo** [PalisadoesFoundation/talawa-admin#806]
**Describe the bug**
The height and width of the cells for the days on the calendar increases as you add more events to a particular day. The number of events displayed on each day is not limited, so if one was to add 5-10 events for a particular day, it would display all 5-10 events and increase the length of the cell to accommodate all events.

**To Reproduce**
1. Login to the admin
2. Select an organization (click the "manage" button next to it)
3. Click on the events tab
4. Create multiple events for a particular day on the calendar

**Expected behavior**
The table cells should have a maximum height and width so the size doesn't change after adding new events. 
A maximum maximum of 1 or 2 events should be displayed on a calendar cell with a small clickable "more..." label that displays a small modal of all events for that day when clicked OR to make the table cells scrollable so that the user can scroll on the cell to see the remaining events.
Also in cases where the title of the event is long, the title should be truncated to accommodate a maximum number of characters and make the rest ellipse to make it more visually appealing.

**Actual behavior**
Cells sizes increases with each event added and keeps increasing to display all events no matter the number of events created for a day.

**Screenshots**
//

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

@palisadoes I'd love to work on this

**Comment by BlessingOkonkwo** [comment]
@palisadoes Please assign this issue to me

**Comment by Jemeelah1** [comment]
@palisadoes can i work on this

**Comment by BlessingOkonkwo** [comment]
@Jemeelah1 I am currently working on this

**Comment by BlessingOkonkwo** [comment]
> @palisadoes can i work on this

@Jemeelah1 I am currently working on this issue already

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by BlessingOkonkwo** [comment]
@palisadoes Please reassign the issue to me. I am still working on it. I ran into a few issues while working on it but I'm almost done working on it

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.
