### ISSUE TITLE
functions are inside fields

### ISSUE THREAD

**Issue by ssaumyaa7** [PalisadoesFoundation/talawa-admin#81]
It is good to write the function outside of the fields.

Why ?
Because in the future there will be a point where we will check more conditions for onChange of either email or password. For example, we may need to check for errors or regex checks then writing them outside is better in way of coding as well as for any person working to understand and rework on code.

onChange Function can be written outside of the input field:

![page](https://user-images.githubusercontent.com/64359826/121763060-ca80d980-cb56-11eb-8b5c-eaa77329e500.PNG)

**Comment by yasharth291** [comment]
keep in mind we can't use classes

**Comment by yasharth291** [comment]
and @ssaumyaa7 this code is temporarily written for any onchange value we will change it once all the pages are made so i think @palisadoes this issue can be closed

**Comment by yasharth291** [comment]
@Sagar2366  sir this also could be closed as it will be implemented in near future

**Comment by Sagar2366** [comment]
Though I agree we may need to relocate some of these functions outside or keep them outside to avoid duplication of code, whenever needed we can open new issue for that. @ssaumyaa7 for now closing this issue.
If you have any good reason to keep it open, feel free to discuss and we can reopen it again.

**Comment by ssaumyaa7** [comment]
@Sagar2366 sir, when should we start working on such issue as @yasharth291 mentioned to be duplicate issue... 
I didnt exactly understand when should we raise this issue ... 
could you please explain so that I'll avoid raising code improvement issue from now on.

**Comment by yasharth291** [comment]
this one is not duplicate issue is when you have covered the issue in past issues
