### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by NabajitS** [PalisadoesFoundation/talawa-admin#810]
**Describe the bug**
The links of the images in all the posts seem to overflow both on desktop and mobile.

**To Reproduce**

1. Set up Talawa-admin locally and log in.
2. Open any organization's dashboard. 
3. Create a post, if no post exists
4. The link to the image inputted as part of the post overflow the screen

**Expected behavior**
The image links should fit within their containers.

**Actual behavior**
The links to the image overflow

**Screenshots**
![overflow-link](https://user-images.githubusercontent.com/86390740/227830530-01eb5af7-a013-48ff-8baa-1e18e9da8250.png)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by NabajitS** [comment]
@palisadoes can you assign this issue to me

**Comment by anshgoyalevil** [comment]
@NabajitS 

Please reload the page, this issue is fixed already, since Image URL is replaced with image.

**Comment by NabajitS** [comment]
Ok
