### ISSUE TITLE
Feature Request [organization created date is missing in org dashboard page]

### ISSUE THREAD

**Issue by saadabban76** [PalisadoesFoundation/talawa-admin#813]
**Describe the solution you'd like**
The created org date is missing in managing org page, adding the created date in org dashboard will enhance better user experience.

**Describe alternatives you've considered**
the created date of org is present in orgList page but not included in orgDashboard page. check out the screenshots of orgList and orgDashboard pages down below ⬇️ 

**Additional context**
orgList page Screenshot : 
![createdorglist](https://user-images.githubusercontent.com/115649011/228024647-49aa6f1a-d3db-4c05-83b0-8833b5725cda.png)

orgDashboard page Screenshot : 
![onclickorg](https://user-images.githubusercontent.com/115649011/228024773-c06d1c5e-f2c0-4cfa-8e56-acdbbe35b000.png)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by saadabban76** [comment]
please assign this issue to me if its valid @palisadoes

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
