### ISSUE TITLE
Bug Report: Replace Talawa Portal with Talawa Admin Portal

### ISSUE THREAD

**Issue by beingnoble03** [PalisadoesFoundation/talawa-admin#817]
**Describe the bug**
This portal is specifically for Admins and Super Admins, still it doesn't say anywhere on the Login Page. Replacing the heading with "Talawa Admin Portal" can solve this issue.

*Note that it needs to done in every language.*

**Expected behavior**
Navbar says "Talawa Admin Portal"

**Actual behavior**
Navbar says "Talawa Portal"

**Screenshots**

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/62551163/228208819-b72b9cb6-380f-4617-9238-815f5db717a8.png">

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by sarazaToussaint** [comment]
@beingnoble03, @palisadoes  can you assign this to me please

**Comment by Jemeelah1** [comment]
@palisadoes can i work on this

**Comment by anshgoyalevil** [comment]
@sarazaToussaint You may close this as completed. Make sure to use GitHub's syntax to link issues to PR for auto-closing next time you create a PR. Read contributing.md for more details.
