### ISSUE TITLE
Tests Need to Fail on Warning

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#819]
**Describe the bug**
We have many cases where our tests are accepted in our workflow but are issuing warnings. Here are examples

- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/4544798203/jobs/8011306229
- https://github.com/PalisadoesFoundation/talawa-admin/actions/runs/4622064669/attempts/1

**To Reproduce**

1. Run tests
1. See warnings

**Expected behavior**

1. Fix tests
1. Run tests
1. No warnings
1. Fail on warning

:dart: The code coverage level must not decline

**Actual behavior**

See above

**Screenshots**

![image](https://user-images.githubusercontent.com/16875803/228289735-ac0c5512-34ae-45b0-b27a-58d988ecccd2.png)

**Additional details**
N/A

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by saadabban76** [comment]
> You'll need to fix the tests too.

Got it 👍

**Comment by palisadoes** [comment]
1. Are you still working on this?
1. We had to revert a PR because of intermittent failing tests and this is a good first step to making sure we reduce this risk.

**Comment by saadabban76** [comment]
Yes I'm working on it, today I'll make a PR.

**Comment by palisadoes** [comment]
1. @saadabban76 please make sure @tasneemkoushar reviews your PR. 
2. We really need this implemented quickly

**Comment by saadabban76** [comment]
> 1. @saadabban76 please make sure @tasneemkoushar reviews your PR. 
> 2. We really need this implemented quickly

Sure 👍

**Comment by saadabban76** [comment]
I regret to inform you that I am currently unable to solve the issue at hand as I am occupied with my ongoing examinations. Please accept my apologies for any inconvenience caused. @palisadoes

**Comment by anshgoyalevil** [comment]
@saadabban76 That's alright! Thanks for giving it a try.

@palisadoes Could you please assign this issue to me.

**Comment by KrutikaBhatt** [comment]
Hey, can I work on this issue?

**Comment by tasneemkoushar** [comment]
@anshgoyalevil  I can assign this to you, but we need quick progress on this issue. 
If you assure me to make PR quick, then I can assign it.

**Comment by anshgoyalevil** [comment]
@tasneemkoushar 

Yes. I am assure you 🥇

**Comment by tasneemkoushar** [comment]
once done, tag me in the comments @anshgoyalevil

**Comment by anshgoyalevil** [comment]
@tasneemkoushar 

Done! Please check the linked PR.
