### ISSUE TITLE
Add tests for Search Bar in the Organization List Page of SUPERADMIN

### ISSUE THREAD

**Issue by aviraldevv** [PalisadoesFoundation/talawa-admin#827]
**Describe the bug**
The tests for the search bar will be removed after the merge of the PR #826 

**Expected behavior**
Proper tests should be there for there for the search bar functionality

**Actual behavior**
Currently there will be no unit tests for search bar functionality.

**Screenshots**
Not Required

**Additional details**
Not Required

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aviraldevv** [comment]
@palisadoes Assign this issue to me.

**Comment by palisadoes** [comment]
Unassigning due to inactivity and no submitted PR. Others need to get a chance. Please let us know whether you want to be reassigned before someone else requests assignment or select another issue.

**Comment by Sumitmaithani** [comment]
@palisadoes can I take this issue...

**Comment by aviraldevv** [comment]
@palisadoes 
Apologies for the delay in submitting the PR. I was almost finished with the work and would have submitted it this week, but had a very hectic week at college. I will make sure this doesn't repeat.
