### ISSUE TITLE
Post image not being updated after post edit

### ISSUE THREAD

**Issue by akankshat05** [PalisadoesFoundation/talawa-admin#844]
**Describe the bug**
Post image is not getting displayed/updated after it is uploaded from edit post option for the post.
**To Reproduce**

1. Create an organization and click on "Manage" to view dashboard
2. Click posts 
3. From any new (or existing post) click the edit option
4. Upload any image and update post

**Expected behavior**
After editing and update post, image should be updated

**Screenshots**

https://user-images.githubusercontent.com/72144454/230031297-2b824f1f-15a9-47f0-a4ca-62a1c60e9196.mp4

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by akankshat05** [comment]
If it's a valid issue, I would work on it. Thank you.

**Comment by palisadoes** [comment]
Closing this issue until we have a permanent image upload solution
