### ISSUE TITLE
recreate organization home-page

### ISSUE THREAD

**Issue by ssaumyaa7** [PalisadoesFoundation/talawa-admin#85]
**Describe the bug**
1. Not according to Figma design
2. Could have better UI/UX
3. Need to be screen adaptable
4. Non-uniform spacing
5. Inconsistent sizing of components

**Expected behavior**
1. Edit Figma design for better UI/UX
2. Have engaging web-page construction
3. Provide responsiveness 
4. Consistency in components and elements on the page

**Screenshots**
![palisa3](https://user-images.githubusercontent.com/64359826/122106034-0b1e7280-ce37-11eb-8609-5cd60f367168.PNG)
![palisa2](https://user-images.githubusercontent.com/64359826/122106935-28077580-ce38-11eb-86a0-2713b63eb351.PNG)

**Additional details**
GitHub Externship : 19-05_Sin666_tfa_262

@DangaRanga sir, @palisadoes sir, @Sagar2366 sir,
 I would like to work on this task, please assign me.

**Comment by palisadoes** [comment]
@ssaumyaa7 Please provide a Figma design you'd like to use instead. Please share it on the #talawa-design slack channel before approval. This is what @yasharth291 had to do too.

**Comment by yasharth291** [comment]
Sir i have shared it in the talawa design

**Comment by palisadoes** [comment]
@yasharth291 The design that @ssaumyaa7  is considering or the one that we are using now?

**Comment by yasharth291** [comment]
we are using now because saumya hasn't changed anything till now

**Comment by ssaumyaa7** [comment]
@palisadoes sir, @yasharth291 , there are very minor changes that I'll change and share on slack soon.

**Comment by ssaumyaa7** [comment]
@DangaRanga sir, please assign me
