### ISSUE TITLE
Bug Report: Adding back the plugin architecture logic for talawa-admin 

### ISSUE THREAD

**Issue by SiddheshKukade** [PalisadoesFoundation/talawa-admin#859]
**Describe the bug**
Recently, due to a code commenting error, some part of the code has been deleted from talawa, talawa-admin and talawa-api.
The reason for this being contributors didn't read the [docs on Plugins](https://docs.talawa.io/docs/category/plugins) before deleting those files and comments from the code. That code needs to be re-added and made supportive of the current major changes in the project to make it work again.
 
**To Reproduce**
Steps to reproduce the behaviour:

1. Try installing plugins on talawa-admin
2. See changes in the app
3. nothing happens

**Expected behaviour**
Plugins should work fine means app features should be controlled by talawa-admin

**Actual behaviour**
Nothing happens after uninstalling or installing plugins on the app.

**Screenshots**
N/A

**Additional details**
N/A

**Comment by SiddheshKukade** [comment]
@palisadoes Sir, please assign.

**Comment by SiddheshKukade** [comment]
@palisadoes I'll also add the docs for talawa-admin related to plugins if required in the future. 👍🏻 So that this problem won't occur in future.

**Comment by palisadoes** [comment]
Add comments in the code as well.

**Comment by literalEval** [comment]
@SiddheshKukade @palisadoes what will be the "restored" implementation? Will it be the same as it was before?

**Comment by Ayush0Chaudhary** [comment]
@palisadoes this is a GSoC project.
Why are we implementing this now?
This should be implemented in a correct method by someone who is assigned this project.

Also @SiddheshKukade can you provide a commit hash in which your work was deleted?

**Comment by SiddheshKukade** [comment]
@Ayush0Chaudhary This isn't a GSoC project, I'm trying to fix which has been broke due to past PRs

**Comment by palisadoes** [comment]
1. #856 triggered this issue to be created. 
1. The plugin code was working and documented in talawa docs. It was possible to accept funds from Paypal. 
1. It was disabled this year.

We need additional plugins created and an overhaul of what appears to be an insufficient implementation. This was shown in the videos we did about the failings of Talawa and Talawa Admin. We then created issues to get the most obviously broken features working so that developers would have a minimally usable platform on which to build.

Unfortunately instead of trying to figure out why plugins didn't seem to work and fix it. The feature was disabled.

There is legitimate concern about working on projects for GSoC. There is a similar concern about having minimally working features, especially if they were working before.

**Comment by literalEval** [comment]
@palisadoes I think we should make a group on Slack and discuss this serious issue, what changes might have triggered this, and what can be done to fix this :)

Your opinion?

**Comment by palisadoes** [comment]
@SiddheshKukade can provide the links to the commits. I remember this happening, but cannot remember the exact circumstances.

If the commits cannot be found then we can discuss on slack.

**Comment by literalEval** [comment]
Sure. @SiddheshKukade we can discuss and resolve this issue together. Since I have done a lot of refactoring and migrations, I can be of great help in resolving this :)

**Comment by SiddheshKukade** [comment]
> @SiddheshKukade can provide the links to the commits. I remember this happening, but cannot remember the exact circumstances.
> 
> If the commits cannot be found then we can discuss on slack.

@palisadoes Sure, I'm checking the code, I'll post links to the commits as I discover them 👍

**Comment by Ayush0Chaudhary** [comment]
@SiddheshKukade you can use git blame, you won't have to search it manually.

**Comment by SiddheshKukade** [comment]
@Ayush0Chaudhary I already know about that.

**Comment by SiddheshKukade** [comment]
Update: I couldn't find any further deletions of code related to plugins in the talawa-admin,
 I'm currently testing https://github.com/PalisadoesFoundation/talawa/pull/1778 with the talawa-admin.
 I'll fix the errors if they occur in talawa-admin while using plugins.

**Comment by SiddheshKukade** [comment]
Update: I've had a small medical operation for my left eye. I will complete this in a few days.

**Comment by SiddheshKukade** [comment]
Update: I've made It to work we can close this.

For additional details: https://github.com/SiddheshKukade/Google-Summer-of-Code-2023-Work-Product
