### ISSUE TITLE
Support to run tests in browser for better debugging

### ISSUE THREAD

**Issue by prathamesh-mutkure** [PalisadoesFoundation/talawa-admin#863]
**Is your feature request related to a problem? Please describe.**

I was recently working on #855, the changes caused almost all tests to fail and I had to spend hours debugging the issue as all the HTML was simply being dumped into the console which made understanding the issue very difficult and time-consuming.

We can solve this issue by rendering the UI of failed tests in the browser.

**Describe the solution you'd like**

We can integrate the [jest-preview](https://www.jest-preview.com/) package which can simulate failing tests in the browser, thus making the debugging much easier and faster.

**Describe alternatives you've considered**
I could not find any other library capable of running tests in the browser.

**Approach to be followed (optional)**

- Install the `jest-preview` package
- Setup tests configuration files
- Configure the package to be able to load our custom CSS
- Test if everything works properly

**Additional context**

Here's a screenshot of when the `OrganizationPeople.test.tsx` test failed with `jest-preview` configured -

<img width="1904" alt="Screenshot 2023-04-10 at 11 30 16 PM" src="https://user-images.githubusercontent.com/28570857/230962741-f88e2997-8835-4894-8271-0b0ce7bdcdd9.png">

The failing test is running on browser, this will make debugging test much faster and easier.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by prathamesh-mutkure** [comment]
I'd like to work on this if it's a valid issue

**Comment by anshgoyalevil** [comment]
@prathamesh-mutkure 

This is a very much needed feature. Thanks for finding a solution to it.
