### ISSUE TITLE
Restore Search Testing for OrgList.test.tsx

### ISSUE THREAD

**Issue by palisadoes** [PalisadoesFoundation/talawa-admin#870]
**Describe the bug**
We discovered that large sections of test code have been removed:
- https://github.com/PalisadoesFoundation/talawa-admin/pull/867#discussion_r1163969971

The sections of test code that need to be restored can be found here
- https://github.com/PalisadoesFoundation/talawa-admin/pull/826/files#diff-969071a6467f507443e6dded253411e5478202bb363f6b760369fffeba3a307dL459-L469

**To Reproduce**

See Above

**Expected behavior**

Tests for `src/screens/OrgList/OrgList.test.tsx` need to be restored to 100% coverage with search being thoroughly tested.

**Actual behavior**

See Above

**Screenshots**

N/A

**Additional details**

N/A

**Comment by aviraldevv** [comment]
@palisadoes  Please assign this issue to me.

**Comment by palisadoes** [comment]
Reopening as the testing was unsatisfactory.

**Comment by palisadoes** [comment]
Please resubmit the PR

**Comment by aviraldevv** [comment]
@palisadoes  Please check the new PR I haven't made any changes.
