### ISSUE TITLE
Organization Dashboard - Fix Console Error 

### ISSUE THREAD

**Issue by prathamesh-mutkure** [PalisadoesFoundation/talawa-admin#872]
**Describe the bug**

**To Reproduce**

1. Run Talawa Admin and Log In
2. Open the console
3. On the OrgList page, click the `Manage` button for any organization
4. It should display a `TypeError` in the console

**Expected behavior**
There should not be any error

**Actual behavior**
The console displayed the following error -

```
Uncaught TypeError: Cannot read properties of undefined (reading 'organizations')
```

**Screenshots**

<img width="607" alt="Screenshot 2023-04-13 at 1 28 15 AM" src="https://user-images.githubusercontent.com/28570857/231570668-489647e6-09e2-4282-9114-dcd891282a36.png">

**Additional details**

NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by prathamesh-mutkure** [comment]
I'd like to resolve this error

**Comment by aashimawadhwa** [comment]
Is this an actual error? I don't see this.
it can be compatibility issue, try using another browser. @prathamesh-mutkure

**Comment by prathamesh-mutkure** [comment]
@aashimawadhwa you're right.

It's giving error on Chrome but works fine in Safari and Firefox

**Comment by aashimawadhwa** [comment]
Now i had the same error a few days back you can try fixing the extension it is definitely due to a chrome extension.

**Comment by prathamesh-mutkure** [comment]
It seems that `data` is not being immediately updated after `loading` becomes `false`, which causes it to be `undefined`

It might be due to an extension or something, but we must still handle this situation by adding a conditional check.

Other components like `OrganizationPeople` have this conditional check in place

<img width="646" alt="Screenshot 2023-04-13 at 1 56 26 AM" src="https://user-images.githubusercontent.com/28570857/231576498-0992f69c-dfee-489f-8a0f-7361c7306284.png">
