### ISSUE TITLE
Cannot go to current date in calendar

### ISSUE THREAD

**Issue by adi-uchiha** [PalisadoesFoundation/talawa-admin#883]
**Describe the bug**
The calendar does not highlight current date. Also there is no button to directly go to current date in the calendar from any month. 

**To Reproduce**

1.Go to manage org
2.Go to events page
3.See the calendar
4.Current date is unknown

**Expected behavior**

https://user-images.githubusercontent.com/103348863/232000694-49beb1be-8a97-4425-b28c-0fe0a1d20d5a.mp4

**Actual behavior**
Current date has no significance in calendar

**Screenshots**
N/A

**Comment by adi-uchiha** [comment]
I would like to take this

**Comment by aashimawadhwa** [comment]
I fell for this, we need a current date highlighter, because on refreshing the calendar automatically shows the current month. We need to add a date preview
