### ISSUE TITLE
Redirect to Last Page After Logging In

### ISSUE THREAD

**Issue by prathamesh-mutkure** [PalisadoesFoundation/talawa-admin#904]
**Is your feature request related to a problem? Please describe.**

- Currently, the user gets logged out after a time interval
- Then they need to log in again
- The user is redirected to the home page again
- Thus, users need to manually navigate to the last page they were working with

**Describe the solution you'd like**

- The user should be redirected to the last page they were on

**Describe alternatives you've considered**
NA

**Approach to be followed (optional)**
NA

**Additional context**
NA

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by prathamesh-mutkure** [comment]
@palisadoes I'd like to resolve this

**Comment by palisadoes** [comment]
@aashimawadhwa Aren't you working on something similar?

**Comment by aashimawadhwa** [comment]
Yes sir it is the same issue as #899

**Comment by aashimawadhwa** [comment]
moreover, once #899 is implemented, there is no need to redirect to the history.
as the user will logout by it's own will and then every login will be apparently a fresh login. @prathamesh-mutkure

**Comment by palisadoes** [comment]
Closing. Duplicate
