### ISSUE TITLE
Inefficient code implementation

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#908]
**Describe the bug**
A few days ago, I implemented the code to render the OrgPeople list in reverse order but I later realized that there is a better to implement the same.

**To Reproduce**
1. Have a look at the screenshot

**Expected behavior**
The code works as required but is inefficient and could lead to errors.

**Actual behavior**
The data should be rendered in reverse order.

**Screenshots**
![image](https://user-images.githubusercontent.com/107215525/235311733-184fc671-6dd6-46f5-a664-3272b31e107a.png)

**Additional details**
I would like to implement the better code version where we directly access data in reverse order from the database

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by anurag0006** [comment]
I would like to work on this issue...The implementation is that we directly access the data from the database in reverse order by making changes in the query fields

**Comment by palisadoes** [comment]
Unassigned due to inactivity
