### ISSUE TITLE
Feature Request: common standard between api and Admin

### ISSUE THREAD

**Issue by anurag0006** [PalisadoesFoundation/talawa-admin#909]
**Is your feature request related to a problem? Please describe.**
Currently, we use different commands to run the API and admin respectively in our local system. Its better to have a command standard. I suggest to shift our admin scripts to npm from yarn.

![image](https://user-images.githubusercontent.com/107215525/235375605-be4ef38e-0715-4de0-96ca-1d2c0770534e.png)

**Comment by anurag0006** [comment]
I would like to work on this issue

**Comment by anshgoyalevil** [comment]
@anurag0006 

The project was shifted to NPM long way back. This issue can be closed

**Comment by anurag0006** [comment]
My bad, i thought it wasn't implemented
