### ISSUE TITLE
Check-ins functionality - Admin Portal

### ISSUE THREAD

**Issue by AdityaBirangal** [PalisadoesFoundation/talawa-admin#91]
**Is your feature request related to a problem? Please describe.**
- Organiser need know to how many registered users actually attended event
- Verify identity to give entry

**Describe the solution you'd like**
In first way organiser should be able to mark check-in from admin portal also
![Talawa Event Check-ins-2](https://user-images.githubusercontent.com/43909309/123597830-74c45680-d811-11eb-9834-3bb32bb6053e.png)

**Describe alternatives you've considered**
Self Check-in

**Approach to be followed (optional)**
Need to do update in Admin UI
somewhat like this 
![Screenshot 2021-06-28 at 1 10 49 PM](https://user-images.githubusercontent.com/43909309/123599050-c91c0600-d812-11eb-84c8-3b799cacff61.png)

**Additional context**
App - PalisadoesFoundation/talawa#901
API - PalisadoesFoundation/talawa-api#319

**Comment by palisadoes** [comment]
Check-ins must only be handled with the mobile app as the attendees and persons at the gate will most likely both have phones
