### ISSUE TITLE
Bug Report : Update user password do not validate the password

### ISSUE THREAD

**Issue by adi-uchiha** [PalisadoesFoundation/talawa-admin#912]
**Describe the bug**
Admin have a option to update the password the settings. Where he have to enter the previous password and give a new password. 
The new password is not validated as it was during register process, because of that user can set simple password like 123 and it works. This is a security flaw

**To Reproduce**

1. Login as a superadmin
2. Go to settings page
3. Update the password page
4. Use a password like 123
5. Changes are applied successfully

**Expected behavior**
User should be prompted to enter a stronger password

**Actual behavior**
No password validation are present 

**Screenshots**
N/A

**Additional details**
N/A

**Comment by adi-uchiha** [comment]
Please assign me

**Comment by palisadoes** [comment]
Duplicate issue. Closing
- https://github.com/PalisadoesFoundation/talawa-admin/issues/720
