### ISSUE TITLE
Improved Grid view for the post newsfeed dashboard

### ISSUE THREAD

**Issue by aashimawadhwa** [PalisadoesFoundation/talawa-admin#921]
**Is your feature request related to a problem? Please describe.**

Currently we have various cards to manage the post of an organization which is not up to the design standards .

**Describe the solution you'd like**
I suggest using grid system like Instagram web to provide with a concise and neat view of all the posts.

**Additional context**
Features to be added in this PR:

1. Improved grid view for the dashboard in the post management.
2. A detailed view for post
3.  elimination pagination to introduce infinite scroll.

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by aashimawadhwa** [comment]
@ttaylor92 @tonythegr8 can you please assign this to me.

**Comment by palisadoes** [comment]
@aashimawadhwa What's the progress on this?

**Comment by aashimawadhwa** [comment]
I took a pull and I am resolving the conflicts will raise a PR soon after that. @palisadoes
