### ISSUE TITLE
Customisation of Bootstrap Theme

### ISSUE THREAD

**Issue by rishav-jha-mech** [PalisadoesFoundation/talawa-admin#928]
**Is your feature request related to a problem? Please describe.**
Current develop branch has default bootstrap theme, it would help our website stand out if we modify its components according to our own needs.

**Describe the solution you'd like**
Customisation of CSS, setup of SCSS files for bootstrap and installation of a sass compiler to compile our modified sass files.

**Describe alternatives you've considered**
None

**Approach to be followed (optional)**
- Setup a `scss` folder inside the projects assets directory
- install `node-css` to compile the scss into a single `main.css` file inside the css folder in assets directory

The developmental process will be simple, you have to recompile the scss file only when you change one of its files, the file structuring will be done in a proper and easy way so that new developers should not face any trouble in modifying the scss files.
I'll also document the file naming convention and folder structure and its purpose.

**Additional context**
Admin UI Redesign

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@rishav-jha-mech Do you need to be assigned this issue?

**Comment by rishav-jha-mech** [comment]
@palisadoes please assign this issue to me
