### ISSUE TITLE
Improve data update mechanism throughout the application after query/mutation

### ISSUE THREAD

**Issue by JamarTG** [PalisadoesFoundation/talawa-admin#933]
**Describe the bug**
Currently, the code is using `window.location.reload()` to refresh the page after a query. Hard refreshing does not give the best user experience and is quite annoying.

**To Reproduce**

1. Navigate to the 'orgpost' route
2. Click 'Delete on a Post' (error exists in multiple places in the application)

**Expected behavior**
The data should be refetch the data and update the data instantly without having to reload the entire page. 

**Actual behavior**
The entire page is reloaded creating a bad user experience

**Screenshots**
N/A

**Comment by JamarTG** [comment]
@palisadoes May I work on this issue sir? Thanks

**Comment by palisadoes** [comment]
@JamarTG Are you still working on this?

**Comment by JamarTG** [comment]
> @JamarTG Are you still working on this?
@palisadoes 
I made a silly mistake which forced me to restart entirely. Since I'm going to be working on other tasks, I'd like to pass this task onto someone else. Basically, my solution was to pass the refetch function along with the data to the components and call it when a deletion or update happens. My bad

**Comment by git-init-priyanshu** [comment]
Please assign this to me.

**Comment by git-init-priyanshu** [comment]
Hey @JamarTG , I didn't look up your solution but ended up with the same one. So, is this approach bad? Is that why you had to restart?

**Comment by JamarTG** [comment]
> Hey @JamarTG , I didn't look up your solution but ended up with the same one. So, is this approach bad? Is that why you had to restart?

The solution works beautifully actually. I embarrassingly forked the wrong repo and was going to deal with it but was assigned my actual tasks for my internship.  I figured I would copy the code over at a later date or just let someone handle it. Quick note, You'll also have to handle automatically hiding the modal after a refetch which I believe is controlled by the data-dismiss attribute.

**Comment by git-init-priyanshu** [comment]
> > Hey @JamarTG , I didn't look up your solution but ended up with the same one. So, is this approach bad? Is that why you had to restart?
> 
> The solution works beautifully actually. I embarrassingly forked the wrong repo and was going to deal with it but was assigned my actual tasks for my internship. I figured I would copy the code over at a later date or just let someone handle it. Quick note, You'll also have to handle automatically hiding the modal after a refetch which I believe is controlled by the 'data-dismiss' attribute.

Okay, got it. 
I have a question: I need to trigger a refetch in OrgPostCard, and I'm considering using Redux. However, I noticed that the current Redux version is quite old, and the createStore function has been deprecated. Should I use a newer version of Redux, or is there another method I should use?

**Comment by palisadoes** [comment]
@git-init-priyanshu Wherever possible use the latest version of the package. Upgrade if you have to. Reducing the chance of using deprecated packages in future must always be a goal.

**Comment by git-init-priyanshu** [comment]
> @git-init-priyanshu Wherever possible use the latest version of the package. Upgrade if you have to. Reducing the chance of using deprecated packages in future must always be a goal.

For this issue, I used the same version of Redux. Upgrading to the latest version of Redux could be dealt with through a separate GitHub issue.

**Comment by git-init-priyanshu** [comment]
Every time I run the development server I get an error in every test file. The error is:
<img width="395" alt="Screenshot 2023-07-22 082225" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/c4a50678-9f6d-4332-a157-2773fab25f81">
I have my code ready, but I can't make a PR until this issue is fixed. ;(. I have asked the same doubt in the slack channel.

**Comment by git-init-priyanshu** [comment]
> Every time I run the development server I get an error in every test file. The error is:
> <img width="395" alt="Screenshot 2023-07-22 082225" src="https://github.com/PalisadoesFoundation/talawa-admin/assets/110045644/c4a50678-9f6d-4332-a157-2773fab25f81">
> I have my code ready, but I can't make a PR until this issue is fixed. ;(. I have asked the same doubt in the slack channel.

Hey @palisadoes can you help me with this please. Thanks

**Comment by git-init-priyanshu** [comment]
> Have you merged the latest version of the code from the Palisadoes Foundation repo to your local branch?

Yeah, I have, but it did not fix it.

**Comment by palisadoes** [comment]
Unassigning due to inactivity

**Comment by git-init-priyanshu** [comment]
> Unassigning due to inactivity

Hey @palisadoes, could you please reassign this issue to me? I had my semester exams, so I couldn't focus on this. Now, I have my code ready and I am ready to make a PR.

**Comment by ThePiyushAggarwal** [comment]
@palisadoes I have looked into the solution for this issue. May I work on this? Please assign this issue to me. Thank you!

**Comment by ThePiyushAggarwal** [comment]
@palisadoes Reminder - please assign this issue to me. I have a PR ready. I will raise the PR within 24 hours.
