### ISSUE TITLE
Adding a short note on how to rectify errors in `Introspection` check. 

### ISSUE THREAD

**Issue by kb-0311** [PalisadoesFoundation/talawa-admin#944]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
When the errors are logged on the terminal in the `Runs Introspection`  check in the current CI/CD contributors find it confusing how exactly to solve the error 
**Describe the solution you'd like**
A small statement which echos how exactly to rectify the errors if any and what is the overall problem there can be added within the check itself.

**Describe alternatives you've considered**

**Approach to be followed (optional)**
A clear and concise description of approach to be followed.

**Additional context**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by kb-0311** [comment]
@palisadoes Pls assign this to me.

**Comment by kb-0311** [comment]
@palisadoes oh no it was meant as a good first issue for new contributors, unassigning myself

**Comment by racky7** [comment]
@palisadoes can I work on this?

**Comment by nick2432** [comment]
The current assignee has been inactive for one week. Could you please assign this task to me?

**Comment by dhanagopu** [comment]
Unassigned due to inactivity

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by aarishshahmohsin** [comment]
@Cioppolo14 The errors seem good enough. 
```
[log] 
Detected 3 invalid documents:

[log] error
[log] in /home/runner/work/talawa-admin/talawa-admin/src/GraphQl/Mutations/EventAttendeeMutations.ts:

[log]  - Field allotedRoom is not defined by type CheckInInput.
 - Field allotedSeat is not defined by type CheckInInput.
[log] 


[log] error
[log] in /home/runner/work/talawa-admin/talawa-admin/src/GraphQl/Queries/PlugInQueries.ts:

[log]  - Cannot query field _id on type AdvertisementsConnection.
 - Cannot query field name on type AdvertisementsConnection.
 - Cannot query field type on type AdvertisementsConnection.
 - Cannot query field organization on type AdvertisementsConnection.
 - Cannot query field mediaUrl on type AdvertisementsConnection.
 - Cannot query field endDate on type AdvertisementsConnection.
 - Cannot query field startDate on type AdvertisementsConnection.
[log] 


[log] error
[log] in /home/runner/work/talawa-admin/talawa-admin/src/GraphQl/Queries/Queries.ts:

[log]  - Cannot query field allotedRoom on type CheckIn.
 - Cannot query field allotedSeat on type CheckIn.
[log] 


Error: Process completed with exit code 1.
```
These are the errors in a previous PR. These list which files contain the error and on checking them with API, we see that there are contradictions in the declarations of the types. 

for example, 
in the admin repo, the type checkIn is defined as 
```
type CheckIn {
  _id: ID!
  allotedRoom: String
  allotedSeat: String
  event: Event!
  feedbackSubmitted: Boolean!
  time: DateTime!
  user: User!
}
```

while in the API repo, the type checkIn is defined as 
```
  type CheckIn {
    _id: ID!
    time: DateTime!
    user: User!
    event: Event!
    feedbackSubmitted: Boolean!
    createdAt: DateTime!
    updatedAt: DateTime!
  }
```

the error message states clearly, that the allotedRoom and the allotedSeat Property do not exist on the type CheckIn.
So I don't think there is any need of any PR for this issue.
