### ISSUE TITLE
Docker for Easy Local Devlopment

### ISSUE THREAD

**Issue by vasujain275** [PalisadoesFoundation/talawa-admin#974]
**Is your feature request related to a problem? Please describe.**
Yes, it is very tedious process to first setup api with mongodb other talawa-api dependencies. 

**Describe the solution you'd like**
A Docker compose file that can setup all that using Docker Compose.

**Describe alternatives you've considered**
 Did not find any

**Approach to be followed **
I will write a docker compose file to automate this process and will also update the read-me with new instructions

**Comment by vasujain275** [comment]
Can I work on this?

**Comment by palisadoes** [comment]
@vasujain275 We are discussing whether this is the correct long term approach. Please give us a few days.

**Comment by vasujain275** [comment]
Okay, will wait

**Comment by vinfinity7** [comment]
Hi @palisadoes , would love to hear about update on this issue !

**Comment by palisadoes** [comment]
@DMills27 Is investigating how we could us nix across all repos to make the installation easier across all the repos.

**Comment by palisadoes** [comment]
@vasujain275 The preferred alternative approach is taking much longer than expected. Please proceed with this approach which we'll adopt until the long term solution is implemented. You will need to update our installation and configuration documentation too.

**Comment by vasujain275** [comment]
Okay @palisadoes. I will start working on this and will update the installation and configuration documentation too.

**Comment by vasujain275** [comment]
Hello @palisadoes, to enhance developer convenience, I suggest we create a Docker image for the talawa-api. This way, it can be readily pulled from Docker Hub, and we can implement continuous integration/continuous deployment (CI/CD) to keep the image up to date. Alternatively, I am creating a Dockerfile in the talawa-api repository, allowing developer to manually build it when working on talwa-admin locally. Which approach do you think is more suitable for our project?

**Comment by palisadoes** [comment]
@vasujain275 Your idea for Docker Hub is a good one, but please add it to the code base at this time. Our default branch is currently develop and even the master branch will be in test for some time. Formalizing is premature at this time.

**Comment by vasujain275** [comment]
@palisadoes, I've included a Dockerfile and a docker-compose.yaml in the talawa-api repository at https://github.com/PalisadoesFoundation/talawa-api/pull/1418. Would it be beneficial to do the same for talawa-admin? This would streamline the setup process for talawa flutter app developers who also need talawa-admin.

**Comment by palisadoes** [comment]
> @palisadoes, I've included a Dockerfile and a docker-compose.yaml in the talawa-api repository at [PalisadoesFoundation/talawa-api#1418](https://github.com/PalisadoesFoundation/talawa-api/pull/1418)

Yes that will be useful

**Comment by vasujain275** [comment]
@palisadoes are there any more changes required to in pr?

**Comment by vasujain275** [comment]
> > @palisadoes, I've included a Dockerfile and a docker-compose.yaml in the talawa-api repository at [PalisadoesFoundation/talawa-api#1418](https://github.com/PalisadoesFoundation/talawa-api/pull/1418)
> 
> Yes that will be useful

Okay, I'll start working on containerization talawa admin too
