### ISSUE TITLE
Bug report: Input Field Outline Display Issue

### ISSUE THREAD

**Issue by TusharKumawat1** [PalisadoesFoundation/talawa-admin#988]
**Describe the bug**
In the "Forgot Password" page, the issue is that the bottom outline of the input field is hidden behind the input field's background color. This makes it hard to notice and can affect the user experience.

**To Reproduce**

1.Head to the login section.
2.Click on  the "Forgot Password" link.
3.Click on the 'Enter OTP' input field.

**Expected behavior**
It is crucial that the outline of these input fields is clearly visible.

**Actual behavior**
The input field's bottom outline is hidden by its background.

**Video**

https://github.com/PalisadoesFoundation/talawa-admin/assets/133745159/970a734c-da9e-41d8-9fe3-a6fa43a587b1

**Additional details**
"I am requesting to be assigned to this issue because I am attempting to resolve it."

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens. Stay tuned, we expect these issues to be created during the first week of November 2023. @rishav-jha-mech is leading this process for the Talawa Admin project
4. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing in anticipation of our work on the design. Responsiveness will be a part of this re-evaluation.
