### ISSUE TITLE
Feature Request: Redesign the create post modal

### ISSUE THREAD

**Issue by TusharKumawat1** [PalisadoesFoundation/talawa-admin#991]
**Is your feature request related to a problem? Please describe.**
The aim of this feature report is to outline the proposed changes for the "Redesigning the Create Post Modal" feature. The goal is to improve the user experience and ensure that the design is consistent with the rest of the application. The current user interface (UI) for the Create Post Modal is not in line with the overall application design, which is why this feature is necessary.

**Describe the solution you'd like**

To improve the way the Create Post Modal looks and fits in with the rest of the page, we suggest taking a comprehensive approach. This includes making sure the design matches in terms of colors and typography, and making the layout easy to use and adaptable to different devices.

**Describe alternatives you've considered**
We need at least some refactoring to improve its design of create post modal

**Additional context**
Could you please assign me the issue? I'm currently working on it. 
..
..
 Screenshot of the current user interface
![Screenshot 2023-10-13 143639](https://github.com/PalisadoesFoundation/talawa-admin/assets/133745159/97fe65de-f867-432a-8aff-9a6c54fe6881)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
https://www.figma.com/file/UEygJJsZxAQRPPw3XR5elX/Palisadoes-Logo-SVG?type=design&node-id=4%3A45&mode=design&t=EaoW3SSUpOfPAk0J-1

Closing. @rishav-jha-mech is working on an overall design that is documented in this Figma site
