### ISSUE TITLE
Feature Request: Refactor Style Components for Improved Design Consistency

### ISSUE THREAD

**Issue by TusharKumawat1** [PalisadoesFoundation/talawa-admin#995]
**Is your feature request related to a problem? Please describe.**
It is not a problem, but various components of Talawa-Admin require refactoring to improve their appearance in the UI.

**Describe the solution you'd like**
1. Consistency: We maintained design consistency throughout the application by standardizing CSS classes, resulting in a unified styling approach.

2. Responsive Design: The updated styles are designed to adapt seamlessly to various screen sizes, ensuring a more responsive and accessible UI.

3. Modern UI Elements: We've incorporated modern UI elements and techniques to stay current with design trends and deliver a fresh and engaging user experience.

4. Optimized Performance: The CSS changes are optimized to minimize unnecessary rendering and improve page loading times.

**Approach to be followed (optional)**
To enhance the components' user interface and maintain a streamlined, efficient codebase, I have thoroughly reviewed our CSS styling files. During this review, I identified multiple instances of repetitive styling patterns and numerous unnecessary CSS properties. To improve our components' UI, my approach involves introducing targeted additional CSS to meet the evolving design requirements and, equally important, removing any redundant or superfluous properties. This initiative is aimed at optimizing our codebase, improving performance, and ensuring that our UI remains sleek and responsive. By implementing these changes, we can provide a more efficient, user-friendly experience for our application's end-users and streamline our development process by maintaining a cleaner and more organized codebase.

**Additional context**
In addition, I'm eager for the repository mentor to engage in productive discussions with the team regarding these proposed changes. Your feedback and insights are essential to ensure that these CSS improvements align with our collective goals. To help the team better understand the potential enhancements, I can provide the original, unaltered images and examples of our organization's current UI components. These images serve as a baseline for the proposed changes, allowing for informed decision-making. While I have not made any changes to the images yet, I kindly request you to assign me to this issue, so I can work with our mentor to facilitate the discussion and actively contribute to this initiative. I look forward to collaborating with your team to enhance our user experience and maintain a consistent design.
![collage](https://github.com/PalisadoesFoundation/talawa-admin/assets/133745159/d92a4ed3-605c-4bfc-937a-9c70a2dc8da0)

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by palisadoes** [comment]
@rishav-jha-mech created our [overall design as shared in Talawa Admin GitHub discussion channel](https://github.com/PalisadoesFoundation/talawa-admin/discussions/915#discussioncomment-6337379). 

Thanks @TusharKumawat1 We will used the design to create an overall design guide that we will be formalizing shortly. This will be used to create more specific GitHub issues in the coming weeks.

This will help us create more specific roadmap, one component at time per issue that will be a better approach to solving this situation.

I'll close this issue in anticipation of the creation of the new issues. Thanks again, and stay tuned for the upcoming work. All assistance at that time will be very appreciated.
