### ISSUE TITLE
Bug Report: Unresponsiveness and Overlapping Elements in 'Organization Events'

### ISSUE THREAD

**Issue by SURAJ-SHARMA27** [PalisadoesFoundation/talawa-admin#997]
**Describe the bug**
The issue on the "Organization Events" page arises when the screen width falls below 1400px, causing the site to become entirely unresponsive. The search date calendar shrinks as the screen size decreases, rendering the dates unclearly visible at that dimension. Also, the month and year names overlap with the "Add Event" element. Additionally, when the screen width is below 1400px, a vertical line appears on the far right of the page, which overlaps with the navigation buttons and the "Add Event" button. This unexpected behaviour can significantly impact the user experience.

**To Reproduce**

1. After login go to manage organization page. 
2. In dashboard page click on view all under upcoming events element.

**Expected behavior**
The page should be responsive for all screen sizes, and there should be no unwanted elements overlapping each other.

**Actual behavior**
The site becomes unresponsive when the screen width is <1400px.
The search date calendar shrinks, making dates unclear.
Month and year names overlap with the "Add Event" element.
A vertical line appears, overlapping navigation buttons and the "Add Event" button, affecting user experience.

**Additional details**
Assign this issue to me

https://github.com/PalisadoesFoundation/talawa-admin/assets/90304648/1ae7aae2-a289-4db6-92e8-d51d5b2930cd

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens. Stay tuned, we expect these issues to be created during the first week of November 2023. @rishav-jha-mech is leading this process for the Talawa Admin project
4. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
