### ISSUE TITLE
Feature Request: Logout Confirmation Modal

### ISSUE THREAD

**Issue by skbhagat0502** [PalisadoesFoundation/talawa-admin#998]
Increasing Access

**Feature request details**
Description:
Currently, the website includes a logout button to allow users to sign out. To enhance the user experience and prevent accidental logouts, I propose the implementation of a logout confirmation modal.

**Benefits:**
User-Friendly: Reduces the likelihood of accidental logouts.
Enhanced Security: Provides an additional layer of confirmation for sensitive actions.
Consistency: Aligns with modern web practices for user interactions.

**Details:**
Upon clicking the logout button, a modal should appear, asking the user to confirm their intention to log out. The modal should include a clear message such as "Are you sure you want to log out?" along with buttons for "Confirm" and "Cancel."

**Comment by skbhagat0502** [comment]
@palisadoes , Please assign me this issue.

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. This may include updates to existing screens. Stay tuned, we expect these issues to be created during the first week of November 2023. @rishav-jha-mech is leading this process for the Talawa Admin project
4. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
