### ISSUE TITLE
The UI for creating a Post is not looking good.

### ISSUE THREAD

**Issue by skbhagat0502** [PalisadoesFoundation/talawa-admin#999]
**Describe the bug**
The UI for creating a Post is not looking good. The information box is broken.

**To Reproduce**

1.Login with email and password.
2.Go to your organisation.
3.Try to create a post.
4.You see the information box is broken in the modal.

**Expected behavior**
It should look same as the Update post modal. The information box in update post modal is looking good. I have given the images of both for reference.

**Actual behavior**
The information box is the create post modal is broken.

**Screenshots**
The ui of the create post modal
![Screenshot 2023-10-23 001621](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/86fb4e91-437d-4ed3-a65d-764467623f79)

The ui of the update post modal:
![Screenshot 2023-10-23 004937](https://github.com/PalisadoesFoundation/talawa-admin/assets/109683163/13fc0dac-aba7-4cd5-b8fc-5668395d0f1a)

**Additional details**

**Potential internship candidates**
Please read this if you are planning to apply for a Palisadoes Foundation internship https://github.com/PalisadoesFoundation/talawa/issues/359

**Comment by skbhagat0502** [comment]
@palisadoes Please assign me this issue.

**Comment by palisadoes** [comment]
We are now focusing on three types of issues as priority areas:

1. The improvement in the reliability of our code base. There are many issues created to test existing code. It is a good place to start if you want to understand the operation of various apps. When you submit PRs, we automatically check to see whether the code you submitted has been covered by testing and that each file meets the minimum standard level of the repository as a whole. You won’t be able to avoid understanding testing regimes to contribute to Talawa.
2. The fixing of bugs and features that seriously hamper the user from using the application. The apps have various shortcomings. The most obvious ones are where the apps do not work as expected. For example buttons that don’t work, errors or messages that are not displayed to make the user understand what to do and many more. Think of any difficulty you have had in getting things working, there could be a bug there waiting for you.
3. Coding of screens for issues created by our Contributor team based on our soon to be updated design guide. Stay tuned.
4. The creation of additional our updated documentation that helps with improving both the experience of the end user and the various GitHub contributors who support the development of our software. This would include user guides.

We will only be accepting feature issues for deficiencies that are obviously lacking in the apps. These are things that make it very difficult to operate the apps. Even so, the PRs will still require you to understand testing as stated before.

Closing
